.TH "_LCEVC_IMGB" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_LCEVC_IMGB
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <LcevcMd5\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBcs\fP"
.br
.ti -1c
.RI "int \fBnp\fP"
.br
.ti -1c
.RI "int \fBw\fP [\fBLCEVC_IMGB_MAX_PLANE\fP]"
.br
.ti -1c
.RI "int \fBh\fP [\fBLCEVC_IMGB_MAX_PLANE\fP]"
.br
.ti -1c
.RI "int \fBx\fP [\fBLCEVC_IMGB_MAX_PLANE\fP]"
.br
.ti -1c
.RI "int \fBy\fP [\fBLCEVC_IMGB_MAX_PLANE\fP]"
.br
.ti -1c
.RI "int \fBs\fP [\fBLCEVC_IMGB_MAX_PLANE\fP]"
.br
.ti -1c
.RI "int \fBe\fP [\fBLCEVC_IMGB_MAX_PLANE\fP]"
.br
.ti -1c
.RI "void * \fBa\fP [\fBLCEVC_IMGB_MAX_PLANE\fP]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB129\fP of file \fBLcevcMd5\&.hpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "void* _LCEVC_IMGB::a[\fBLCEVC_IMGB_MAX_PLANE\fP]"

.PP
Definition at line \fB145\fP of file \fBLcevcMd5\&.hpp\fP\&.
.SS "int _LCEVC_IMGB::cs"

.PP
Definition at line \fB130\fP of file \fBLcevcMd5\&.hpp\fP\&.
.SS "int _LCEVC_IMGB::e[\fBLCEVC_IMGB_MAX_PLANE\fP]"

.PP
Definition at line \fB143\fP of file \fBLcevcMd5\&.hpp\fP\&.
.SS "int _LCEVC_IMGB::h[\fBLCEVC_IMGB_MAX_PLANE\fP]"

.PP
Definition at line \fB135\fP of file \fBLcevcMd5\&.hpp\fP\&.
.SS "int _LCEVC_IMGB::np"

.PP
Definition at line \fB131\fP of file \fBLcevcMd5\&.hpp\fP\&.
.SS "int _LCEVC_IMGB::s[\fBLCEVC_IMGB_MAX_PLANE\fP]"

.PP
Definition at line \fB141\fP of file \fBLcevcMd5\&.hpp\fP\&.
.SS "int _LCEVC_IMGB::w[\fBLCEVC_IMGB_MAX_PLANE\fP]"

.PP
Definition at line \fB133\fP of file \fBLcevcMd5\&.hpp\fP\&.
.SS "int _LCEVC_IMGB::x[\fBLCEVC_IMGB_MAX_PLANE\fP]"

.PP
Definition at line \fB137\fP of file \fBLcevcMd5\&.hpp\fP\&.
.SS "int _LCEVC_IMGB::y[\fBLCEVC_IMGB_MAX_PLANE\fP]"

.PP
Definition at line \fB139\fP of file \fBLcevcMd5\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
