.TH "AccessUnit" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AccessUnit
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <NAL\&.h>\fP
.PP
Inherits std::list< NALUnitEBSP * >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB~AccessUnit\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBtemporalId\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
An \fBAccessUnit\fP is a list of one or more NAL units, according to the working draft\&. All NAL units within the object belong to the same access unit\&.
.PP
NALUnits held in the \fBAccessUnit\fP list are in EBSP format\&. Attempting to insert an OutputNALUnit into the access unit will automatically cause the nalunit to have its headers written and anti-emulation performed\&.
.PP
The \fBAccessUnit\fP owns all pointers stored within\&. Destroying the \fBAccessUnit\fP will delete all contained objects\&. 
.PP
Definition at line \fB154\fP of file \fBNAL\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AccessUnit::~AccessUnit ()\fC [inline]\fP"

.PP
Definition at line \fB158\fP of file \fBNAL\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int AccessUnit::temporalId"

.PP
Definition at line \fB157\fP of file \fBNAL\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
