.TH "deps/base_vvc/minimum_VTM/source/Lib/CommonLib/AdaptiveLoopFilter.h" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deps/base_vvc/minimum_VTM/source/Lib/CommonLib/AdaptiveLoopFilter.h \- adaptive loop filter class (header)  

.SH SYNOPSIS
.br
.PP
\fC#include 'CommonDef\&.h'\fP
.br
\fC#include 'Unit\&.h'\fP
.br
\fC#include 'UnitTools\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBvtm::AlfClassifier\fP"
.br
.ti -1c
.RI "class \fBvtm::AdaptiveLoopFilter\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBvtm\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBvtm::Direction\fP { \fBvtm::HOR\fP, \fBvtm::VER\fP, \fBvtm::DIAG0\fP, \fBvtm::DIAG1\fP, \fBvtm::NUM_DIRECTIONS\fP }"
.br
.in -1c
.SH "Detailed Description"
.PP 
adaptive loop filter class (header) 


.PP
Definition in file \fBAdaptiveLoopFilter\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
