.TH "deps/base_vvc/minimum_VTM/source/Lib/CommonLib/AdaptiveLoopFilter.cpp" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deps/base_vvc/minimum_VTM/source/Lib/CommonLib/AdaptiveLoopFilter.cpp \- adaptive loop filter class  

.SH SYNOPSIS
.br
.PP
\fC#include 'AdaptiveLoopFilter\&.h'\fP
.br
\fC#include 'CodingStructure\&.h'\fP
.br
\fC#include 'Picture\&.h'\fP
.br
\fC#include <array>\fP
.br
\fC#include <cmath>\fP
.br

.SH "Detailed Description"
.PP 
adaptive loop filter class 


.PP
Definition in file \fBAdaptiveLoopFilter\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
