.TH "deps/base_vvc/minimum_VTM/source/Lib/CommonLib/AffineGradientSearch.h" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deps/base_vvc/minimum_VTM/source/Lib/CommonLib/AffineGradientSearch.h \- Declaration of \fBAffineGradientSearch\fP class\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'CommonDef\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAffineGradientSearch\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Declaration of \fBAffineGradientSearch\fP class\&. 


.PP
Definition in file \fBAffineGradientSearch\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
