.TH "AffineGradientSearch" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AffineGradientSearch
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <AffineGradientSearch\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB~AffineGradientSearch\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "void(* \fBm_HorizontalSobelFilter\fP )(Pel *const pPred, const int predStride, int *const pDerivate, const int derivateBufStride, const int width, const int height)"
.br
.ti -1c
.RI "void(* \fBm_VerticalSobelFilter\fP )(Pel *const pPred, const int predStride, int *const pDerivate, const int derivateBufStride, const int width, const int height)"
.br
.ti -1c
.RI "void(* \fBm_EqualCoeffComputer\fP )(Pel *pResidue, int residueStride, int **ppDerivate, int derivateBufStride, int64_t(*pEqualCoeff)[7], int width, int height, bool b6Param)"
.br
.in -1c
.in +1c
.ti -1c
.RI "\fBstatic\fP void \fBxHorizontalSobelFilter\fP (Pel *const pPred, const int predStride, int *const pDerivate, const int derivateBufStride, const int width, const int height)"
.br
.ti -1c
.RI "\fBstatic\fP void \fBxVerticalSobelFilter\fP (Pel *const pPred, const int predStride, int *const pDerivate, const int derivateBufStride, const int width, const int height)"
.br
.ti -1c
.RI "\fBstatic\fP void \fBxEqualCoeffComputer\fP (Pel *pResidue, int residueStride, int **ppDerivate, int derivateBufStride, int64_t(*pEqualCoeff)[7], int width, int height, bool b6Param)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB47\fP of file \fBAffineGradientSearch\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AffineGradientSearch::AffineGradientSearch ()"

.PP
Definition at line \fB53\fP of file \fBAffineGradientSearch\&.cpp\fP\&.
.SS "AffineGradientSearch::~AffineGradientSearch ()\fC [inline]\fP"

.PP
Definition at line \fB63\fP of file \fBAffineGradientSearch\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void AffineGradientSearch::xEqualCoeffComputer (Pel * pResidue, int residueStride, int ** ppDerivate, int derivateBufStride, int64_t(*) pEqualCoeff[7], int width, int height, bool b6Param)\fC [static]\fP"

.PP
Definition at line \fB132\fP of file \fBAffineGradientSearch\&.cpp\fP\&.
.SS "void AffineGradientSearch::xHorizontalSobelFilter (Pel *const pPred, const int predStride, int *const pDerivate, const int derivateBufStride, const int width, const int height)\fC [static]\fP"

.PP
Definition at line \fB66\fP of file \fBAffineGradientSearch\&.cpp\fP\&.
.SS "void AffineGradientSearch::xVerticalSobelFilter (Pel *const pPred, const int predStride, int *const pDerivate, const int derivateBufStride, const int width, const int height)\fC [static]\fP"

.PP
Definition at line \fB99\fP of file \fBAffineGradientSearch\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "void(* AffineGradientSearch::m_EqualCoeffComputer) (Pel *pResidue, int residueStride, int **ppDerivate, int derivateBufStride, int64_t(*pEqualCoeff)[7], int width, int height, bool b6Param)"

.PP
Definition at line \fB54\fP of file \fBAffineGradientSearch\&.h\fP\&.
.SS "void(* AffineGradientSearch::m_HorizontalSobelFilter) (Pel *const pPred, const int predStride, int *const pDerivate, const int derivateBufStride, const int width, const int height)"

.PP
Definition at line \fB50\fP of file \fBAffineGradientSearch\&.h\fP\&.
.SS "void(* AffineGradientSearch::m_VerticalSobelFilter) (Pel *const pPred, const int predStride, int *const pDerivate, const int derivateBufStride, const int width, const int height)"

.PP
Definition at line \fB52\fP of file \fBAffineGradientSearch\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
