.TH "deps/base_vvc/minimum_VTM/source/Lib/CommonLib/AffineGradientSearch.cpp" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deps/base_vvc/minimum_VTM/source/Lib/CommonLib/AffineGradientSearch.cpp \- Implementation of \fBAffineGradientSearch\fP class\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'AffineGradientSearch\&.h'\fP
.br

.SH "Detailed Description"
.PP 
Implementation of \fBAffineGradientSearch\fP class\&. 


.PP
Definition in file \fBAffineGradientSearch\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
