.TH "deps/base_vvc/minimum_VTM/source/Lib/CommonLib/AlfParameters.h" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deps/base_vvc/minimum_VTM/source/Lib/CommonLib/AlfParameters.h \- Define types for storing ALF parameters\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <vector>\fP
.br
\fC#include 'CommonDef\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBvtm::AlfFilterShape\fP"
.br
.ti -1c
.RI "struct \fBvtm::AlfParam\fP"
.br
.ti -1c
.RI "struct \fBvtm::CcAlfFilterParam\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBvtm\fP"
.br
.in -1c
.in +1c
.ti -1c
.RI "enum \fBvtm::AlfFilterType\fP { \fBvtm::ALF_FILTER_5\fP, \fBvtm::ALF_FILTER_7\fP, \fBvtm::CC_ALF\fP, \fBvtm::ALF_NUM_OF_FILTER_TYPES\fP }"
.br
.in -1c
.SH "Detailed Description"
.PP 
Define types for storing ALF parameters\&. 


.PP
Definition in file \fBAlfParameters\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
