.TH "deps/base_avc/src/annexb.c" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deps/base_avc/src/annexb.c \- Annex B Byte Stream format\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'global\&.h'\fP
.br
\fC#include 'annexb\&.h'\fP
.br
\fC#include 'memalloc\&.h'\fP
.br
\fC#include 'fast_memory\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBinject_annex_b_bitstream\fP (byte *data, unsigned size)"
.br
.ti -1c
.RI "void \fBmalloc_annex_b\fP (VideoParameters *p_Vid, ANNEXB_t **p_annex_b)"
.br
.ti -1c
.RI "void \fBinit_annex_b\fP (ANNEXB_t *annex_b)"
.br
.ti -1c
.RI "void \fBfree_annex_b\fP (ANNEXB_t **p_annex_b)"
.br
.ti -1c
.RI "int \fBget_annex_b_NALU\fP (VideoParameters *p_Vid, NALU_t *nalu, ANNEXB_t *annex_b)"
.br
.RI "Returns the size of the NALU (bits between start codes in case of Annex B\&. nalu->buf and nalu->len are filled\&. Other field in nalu-> remain uninitialized (will be taken care of by NALUtoRBSP\&. "
.ti -1c
.RI "void \fBopen_annex_b\fP (char *fn, ANNEXB_t *annex_b)"
.br
.RI "Opens the bit stream file from hook\&. "
.ti -1c
.RI "void \fBclose_annex_b\fP (ANNEXB_t *annex_b)"
.br
.RI "Closes the bit stream\&. "
.ti -1c
.RI "void \fBreset_annex_b\fP (ANNEXB_t *annex_b)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Annex B Byte Stream format\&. 


.PP
\fBAuthor\fP
.RS 4
Main contributors (see contributors\&.h for copyright, address and affiliation details)
.IP "\(bu" 2
Stephan Wenger stewe@cs.tu-berlin.de 
.PP
.RE
.PP

.PP
Definition in file \fBannexb\&.c\fP\&.
.SH "Function Documentation"
.PP 
.SS "void close_annex_b (ANNEXB_t * annex_b)"

.PP
Closes the bit stream\&. 
.PP
Definition at line \fB321\fP of file \fBannexb\&.c\fP\&.
.SS "void free_annex_b (ANNEXB_t ** p_annex_b)"

.PP
Definition at line \fB56\fP of file \fBannexb\&.c\fP\&.
.SS "int get_annex_b_NALU (VideoParameters * p_Vid, NALU_t * nalu, ANNEXB_t * annex_b)"

.PP
Returns the size of the NALU (bits between start codes in case of Annex B\&. nalu->buf and nalu->len are filled\&. Other field in nalu-> remain uninitialized (will be taken care of by NALUtoRBSP\&. 
.PP
\fBReturns\fP
.RS 4
0 if there is nothing any more to read (EOF) -1 in case of any error
.RE
.PP
\fBNote\fP
.RS 4
Side-effect: Returns length of start-code in bytes\&.
.PP
get_annex_b_NALU expects start codes at byte aligned positions in the file 
.RE
.PP

.PP
Definition at line \fB136\fP of file \fBannexb\&.c\fP\&.
.SS "void init_annex_b (ANNEXB_t * annex_b)"

.PP
Definition at line \fB46\fP of file \fBannexb\&.c\fP\&.
.SS "void inject_annex_b_bitstream (byte * data, unsigned size)"

.PP
Definition at line \fB26\fP of file \fBannexb\&.c\fP\&.
.SS "void malloc_annex_b (VideoParameters * p_Vid, ANNEXB_t ** p_annex_b)"

.PP
Definition at line \fB32\fP of file \fBannexb\&.c\fP\&.
.SS "void open_annex_b (char * fn, ANNEXB_t * annex_b)"

.PP
Opens the bit stream file from hook\&. 
.PP
\fBReturns\fP
.RS 4
none 
.RE
.PP

.PP
Definition at line \fB295\fP of file \fBannexb\&.c\fP\&.
.SS "void reset_annex_b (ANNEXB_t * annex_b)"

.PP
Definition at line \fB327\fP of file \fBannexb\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
