.TH "decoder/include/BaseVideoDecoderCodecApi.hpp" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
decoder/include/BaseVideoDecoderCodecApi.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'BaseVideoDecoder\&.hpp'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBlctm\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::unique_ptr< \fBBaseVideoDecoder\fP > \fBlctm::CreateBaseVideoDecoderCodecApi\fP (\fBBaseVideoDecoder::Output\fP &output, \fBEncapsulation\fP encapsulation, \fBBaseCoding\fP base_coding, const std::string &\fBname\fP, const std::string &selection_options, const std::string &create_options)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
