.TH "decoder/src/BaseVideoDecoderJM.cpp" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
decoder/src/BaseVideoDecoderJM.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'BaseVideoDecoder\&.hpp'\fP
.br
\fC#include <queue>\fP
.br
\fC#include <vector>\fP
.br
\fC#include 'Diagnostics\&.hpp'\fP
.br
\fC#include 'Misc\&.hpp'\fP
.br
\fC#include 'Packet\&.hpp'\fP
.br
\fC#include 'ScanEnhancement\&.hpp'\fP
.br
\fC#include 'BitstreamStatistic\&.hpp'\fP
.br
\fC#include 'Codec\&.hpp'\fP
.br
\fC#include 'h264decoder\&.h'\fP
.br
\fC#include 'inject_annexb\&.h'\fP
.br
\fC#include 'configfile\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBlctm::PssPacket\fP"
.br
.ti -1c
.RI "struct \fBlctm::BufferCompare\fP"
.br
.ti -1c
.RI "class \fBlctm::BaseVideoDecoderJM\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBlctm\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBQUEUE_LIMIT\fP   32"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "unique_ptr< \fBBaseVideoDecoder\fP > \fBlctm::CreateBaseVideoDecoderJM\fP (\fBBaseVideoDecoder::Output\fP &output, \fBEncapsulation\fP encapsulation)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "DecoderParams * \fBp_Dec\fP"
.br
.ti -1c
.RI "\fBPsnrStatistic\fP \fBgoPsnr\fP"
.br
.ti -1c
.RI "uint8_t \fBgaucMd5Digest\fP [][16]"
.br
.ti -1c
.RI "\fBReportStructure\fP \fBgoReportStructure\fP"
.br
.ti -1c
.RI "std::priority_queue< \fBReportStructure\fP, std::vector< \fBReportStructure\fP, std::allocator< \fBReportStructure\fP > >, \fBReportStructureComp\fP > \fBgoReportQueue\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define QUEUE_LIMIT   32"

.PP
Definition at line \fB80\fP of file \fBBaseVideoDecoderJM\&.cpp\fP\&.
.SH "Variable Documentation"
.PP 
.SS "uint8_t gaucMd5Digest[][16]\fC [extern]\fP"

.PP
Definition at line \fB76\fP of file \fBModelDecoderApp\&.cpp\fP\&.
.SS "\fBPsnrStatistic\fP goPsnr\fC [extern]\fP"

.PP
Definition at line \fB75\fP of file \fBModelDecoderApp\&.cpp\fP\&.
.SS "std::priority_queue<\fBReportStructure\fP, std::vector<\fBReportStructure\fP, std::allocator<\fBReportStructure\fP> >, \fBReportStructureComp\fP> goReportQueue\fC [extern]\fP"

.PP
Definition at line \fB79\fP of file \fBModelDecoderApp\&.cpp\fP\&.
.SS "\fBReportStructure\fP goReportStructure\fC [extern]\fP"

.PP
Definition at line \fB77\fP of file \fBModelDecoderApp\&.cpp\fP\&.
.SS "DecoderParams* p_Dec\fC [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
