.TH "decoder/src/BaseVideoDecoderCodecApi.cpp" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
decoder/src/BaseVideoDecoderCodecApi.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'BaseVideoDecoderCodecApi\&.hpp'\fP
.br
\fC#include <queue>\fP
.br
\fC#include <vector>\fP
.br
\fC#include 'BitstreamStatistic\&.hpp'\fP
.br
\fC#include 'Codec\&.hpp'\fP
.br
\fC#include 'Diagnostics\&.hpp'\fP
.br
\fC#include 'Misc\&.hpp'\fP
.br
\fC#include 'Packet\&.hpp'\fP
.br
\fC#include 'ScanEnhancement\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBlctm::PssPacket\fP"
.br
.ti -1c
.RI "struct \fBlctm::BufferCompare\fP"
.br
.ti -1c
.RI "class \fBlctm::BaseVideoDecoderCodecApi\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBlctm\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBQUEUE_LIMIT\fP   32"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::unique_ptr< \fBBaseVideoDecoder\fP > \fBlctm::CreateBaseVideoDecoderCodecApi\fP (\fBBaseVideoDecoder::Output\fP &output, \fBEncapsulation\fP encapsulation, \fBBaseCoding\fP base_coding, const std::string &\fBname\fP, const std::string &selection_options, const std::string &create_options)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBPsnrStatistic\fP \fBgoPsnr\fP"
.br
.ti -1c
.RI "uint8_t \fBgaucMd5Digest\fP [][16]"
.br
.ti -1c
.RI "\fBReportStructure\fP \fBgoReportStructure\fP"
.br
.ti -1c
.RI "std::priority_queue< \fBReportStructure\fP, std::vector< \fBReportStructure\fP, std::allocator< \fBReportStructure\fP > >, \fBReportStructureComp\fP > \fBgoReportQueue\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define QUEUE_LIMIT   32"

.PP
Definition at line \fB70\fP of file \fBBaseVideoDecoderCodecApi\&.cpp\fP\&.
.SH "Variable Documentation"
.PP 
.SS "uint8_t gaucMd5Digest[][16]\fC [extern]\fP"

.PP
Definition at line \fB76\fP of file \fBModelDecoderApp\&.cpp\fP\&.
.SS "\fBPsnrStatistic\fP goPsnr\fC [extern]\fP"

.PP
Definition at line \fB75\fP of file \fBModelDecoderApp\&.cpp\fP\&.
.SS "std::priority_queue<\fBReportStructure\fP, std::vector<\fBReportStructure\fP, std::allocator<\fBReportStructure\fP> >, \fBReportStructureComp\fP> goReportQueue\fC [extern]\fP"

.PP
Definition at line \fB79\fP of file \fBModelDecoderApp\&.cpp\fP\&.
.SS "\fBReportStructure\fP goReportStructure\fC [extern]\fP"

.PP
Definition at line \fB77\fP of file \fBModelDecoderApp\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
