.TH "decoder/include/BaseVideoDecoder.hpp" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
decoder/include/BaseVideoDecoder.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <cstddef>\fP
.br
\fC#include <cstdint>\fP
.br
\fC#include <memory>\fP
.br
\fC#include <string>\fP
.br
\fC#include <queue>\fP
.br
\fC#include <vector>\fP
.br
\fC#include 'BitstreamStatistic\&.hpp'\fP
.br
\fC#include 'Dimensions\&.hpp'\fP
.br
\fC#include 'Image\&.hpp'\fP
.br
\fC#include 'SignaledConfiguration\&.hpp'\fP
.br
\fC#include 'Types\&.hpp'\fP
.br
\fC#include 'CodecApi\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBlctm::BaseVideoDecoder\fP"
.br
.ti -1c
.RI "class \fBlctm::BaseVideoDecoder::Output\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBlctm\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::unique_ptr< \fBBaseVideoDecoder\fP > \fBlctm::CreateBaseVideoDecoder\fP (\fBBaseVideoDecoder::Output\fP &output, \fBBaseCoding\fP base, \fBEncapsulation\fP encapulation, bool external, const std::string &prepared_yuv_file, bool keep_base)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
