.TH "deps/base_vvc/minimum_VTM/source/Lib/DecoderLib/BinDecoder.h" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deps/base_vvc/minimum_VTM/source/Lib/DecoderLib/BinDecoder.h \- Low level binary symbol writer\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'CommonLib/Contexts\&.h'\fP
.br
\fC#include 'CommonLib/BitStream\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBvtm::BinDecoderBase\fP"
.br
.ti -1c
.RI "class \fBvtm::TBinDecoder< BinProbModel >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBvtm\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBTBinDecoder\fP< \fBBinProbModel_Std\fP > \fBvtm::BinDecoder_Std\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Low level binary symbol writer\&. 


.PP
Definition in file \fBBinDecoder\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
