.TH "BitstreamStatistic" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BitstreamStatistic
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <BitstreamStatistic\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "int \fBReset\fP ()"
.br
.ti -1c
.RI "int \fBUpdate\fP (char *pcCategory, int iSize)"
.br
.ti -1c
.RI "int \fBDump\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB57\fP of file \fBBitstreamStatistic\&.hpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "int BitstreamStatistic::Dump ()"

.PP
Definition at line \fB79\fP of file \fBBitstreamStatistic\&.cpp\fP\&.
.SS "int BitstreamStatistic::Reset ()"

.PP
Definition at line \fB45\fP of file \fBBitstreamStatistic\&.cpp\fP\&.
.SS "int BitstreamStatistic::Update (char * pcCategory, int iSize)"

.PP
Definition at line \fB59\fP of file \fBBitstreamStatistic\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
