.TH "util/include/BitstreamPacker.hpp" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
util/include/BitstreamPacker.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <cstdint>\fP
.br
\fC#include <string>\fP
.br
\fC#include 'Config\&.hpp'\fP
.br
\fC#include 'Packet\&.hpp'\fP
.br
\fC#include 'Misc\&.hpp'\fP
.br
\fC#include 'BitstreamStatistic\&.hpp'\fP
.br
\fC#include <stdio\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBlctm::BitstreamPacker\fP"
.br
.ti -1c
.RI "class \fBlctm::BitstreamPacker::ScopedContextLabel\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBlctm\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBBitstreamStatistic\fP \fBgoStat\fP"
.br
.ti -1c
.RI "FILE * \fBgoBits\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "FILE* goBits\fC [extern]\fP"

.PP
Definition at line \fB74\fP of file \fBModelDecoderApp\&.cpp\fP\&.
.SS "\fBBitstreamStatistic\fP goStat\fC [extern]\fP"

.PP
Definition at line \fB73\fP of file \fBModelDecoderApp\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
