.TH "util/include/BitstreamStatistic.hpp" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
util/include/BitstreamStatistic.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <math\&.h>\fP
.br
\fC#include <stdint\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBitstreamStatistic\fP"
.br
.ti -1c
.RI "struct \fBPsnrStatistic\fP"
.br
.ti -1c
.RI "struct \fBReportStructure\fP"
.br
.ti -1c
.RI "struct \fBReportStructureComp\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSTATISTIC_CATEGORIES\fP   64"
.br
.ti -1c
.RI "#define \fBSTAT_DATA_SIZE\fP   12"
.br
.ti -1c
.RI "#define \fBSTAT_ENTROPY_ENABLED\fP   13"
.br
.ti -1c
.RI "#define \fBSTAT_RLE_ONLY\fP   14"
.br
.ti -1c
.RI "#define \fBSTAT_ENTROPY_CODE\fP   15"
.br
.ti -1c
.RI "#define \fBSTAT_ENTROPY_SYMBOL\fP   16"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBPsnrStatistic\fP \fBPsnrStatistic\fP"
.br
.ti -1c
.RI "typedef struct \fBReportStructure\fP \fBReportStructure\fP"
.br
.ti -1c
.RI "typedef struct \fBReportStructureComp\fP \fBReportStructureComp\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBPicturePsnr15bpp\fP (int16_t *pIn, int16_t *pOut, unsigned plane, int iWidth, int iHeight, \fBPsnrStatistic\fP &oPsnr)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define STAT_DATA_SIZE   12"

.PP
Definition at line \fB51\fP of file \fBBitstreamStatistic\&.hpp\fP\&.
.SS "#define STAT_ENTROPY_CODE   15"

.PP
Definition at line \fB54\fP of file \fBBitstreamStatistic\&.hpp\fP\&.
.SS "#define STAT_ENTROPY_ENABLED   13"

.PP
Definition at line \fB52\fP of file \fBBitstreamStatistic\&.hpp\fP\&.
.SS "#define STAT_ENTROPY_SYMBOL   16"

.PP
Definition at line \fB55\fP of file \fBBitstreamStatistic\&.hpp\fP\&.
.SS "#define STAT_RLE_ONLY   14"

.PP
Definition at line \fB53\fP of file \fBBitstreamStatistic\&.hpp\fP\&.
.SS "#define STATISTIC_CATEGORIES   64"

.PP
Definition at line \fB49\fP of file \fBBitstreamStatistic\&.hpp\fP\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBPsnrStatistic\fP \fBPsnrStatistic\fP"

.SS "typedef struct \fBReportStructure\fP \fBReportStructure\fP"

.SS "typedef struct \fBReportStructureComp\fP \fBReportStructureComp\fP"

.SH "Function Documentation"
.PP 
.SS "int PicturePsnr15bpp (int16_t * pIn, int16_t * pOut, unsigned plane, int iWidth, int iHeight, \fBPsnrStatistic\fP & oPsnr)"

.PP
Definition at line \fB87\fP of file \fBBitstreamStatistic\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
