.TH "deps/base_vvc/minimum_VTM/source/Lib/CommonLib/BitStream.cpp" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deps/base_vvc/minimum_VTM/source/Lib/CommonLib/BitStream.cpp \- class for handling bitstream  

.SH SYNOPSIS
.br
.PP
\fC#include <stdint\&.h>\fP
.br
\fC#include <vector>\fP
.br
\fC#include 'BitStream\&.h'\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <memory\&.h>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBvtm\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
class for handling bitstream 


.PP
Definition in file \fBBitStream\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
