.TH "util/src/BitstreamStatistic.cpp" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
util/src/BitstreamStatistic.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'BitstreamStatistic\&.hpp'\fP
.br
\fC#include 'Diagnostics\&.hpp'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBPicturePsnr15bpp\fP (int16_t *pIn, int16_t *pOut, unsigned plane, int iWidth, int iHeight, \fBPsnrStatistic\fP &oPsnr)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int PicturePsnr15bpp (int16_t * pIn, int16_t * pOut, unsigned plane, int iWidth, int iHeight, \fBPsnrStatistic\fP & oPsnr)"

.PP
Definition at line \fB87\fP of file \fBBitstreamStatistic\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
