.TH "deps/base_vvc/minimum_VTM/source/Lib/CommonLib/BitStream.h" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deps/base_vvc/minimum_VTM/source/Lib/CommonLib/BitStream.h \- class for handling bitstream (header)  

.SH SYNOPSIS
.br
.PP
\fC#include <stdint\&.h>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include 'CommonDef\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBvtm::OutputBitstream\fP"
.br
.ti -1c
.RI "class \fBvtm::InputBitstream\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBvtm\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
class for handling bitstream (header) 


.PP
Definition in file \fBBitStream\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
