.TH "util/include/Buffer.hpp" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
util/include/Buffer.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <cstddef>\fP
.br
\fC#include <cstdint>\fP
.br
\fC#include <memory>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBlctm::Buffer\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBlctm\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::unique_ptr< \fBBuffer\fP > \fBlctm::CreateBufferVector\fP (const uint8_t *data, unsigned size)"
.br
.ti -1c
.RI "std::unique_ptr< \fBBuffer\fP > \fBlctm::CreateBufferVector\fP (unsigned size)"
.br
.ti -1c
.RI "std::unique_ptr< \fBBuffer\fP > \fBlctm::CreateBufferAligned\fP (const uint8_t *data, unsigned size)"
.br
.ti -1c
.RI "std::unique_ptr< \fBBuffer\fP > \fBlctm::CreateBufferAligned\fP (unsigned size)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
