.TH "deps/base_vvc/minimum_VTM/source/Lib/CommonLib/Buffer.h" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deps/base_vvc/minimum_VTM/source/Lib/CommonLib/Buffer.h \- Low-overhead class describing 2D memory layout\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'Common\&.h'\fP
.br
\fC#include 'CommonDef\&.h'\fP
.br
\fC#include 'ChromaFormat\&.h'\fP
.br
\fC#include 'MotionInfo\&.h'\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <type_traits>\fP
.br
\fC#include <typeinfo>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBvtm::PelBufferOps\fP"
.br
.ti -1c
.RI "struct \fBvtm::AreaBuf< T >\fP"
.br
.ti -1c
.RI "struct \fBvtm::UnitBuf< T >\fP"
.br
.ti -1c
.RI "struct \fBvtm::PelStorage\fP"
.br
.ti -1c
.RI "struct \fBvtm::CompStorage\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBvtm\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSIZE_AWARE_PER_EL_OP\fP(OP,  INC)"
.br
.ti -1c
.RI "#define \fBFILL_INC\fP   dest      += stride"
.br
.ti -1c
.RI "#define \fBFILL_OP\fP(ADDR)   dest[ADDR] = val"
.br
.ti -1c
.RI "#define \fBSUBS_INC\fP"
.br
.ti -1c
.RI "#define \fBSUBS_OP\fP(ADDR)   dest[ADDR] \-= subs[ADDR]"
.br
.ti -1c
.RI "#define \fBREM_HF_INC\fP"
.br
.ti -1c
.RI "#define \fBREM_HF_OP_CLIP\fP(ADDR)   dst[ADDR] = ClipPel<T>( T((dst[ADDR]*weight0 \- src[ADDR]*weight1 + (1<<15))>>16), clpRng )"
.br
.ti -1c
.RI "#define \fBREM_HF_OP\fP(ADDR)   dst[ADDR] =             T((dst[ADDR]*weight0 \- src[ADDR]*weight1 + (1<<15))>>16)"
.br
.ti -1c
.RI "#define \fBREM_HF_INC\fP"
.br
.ti -1c
.RI "#define \fBREM_HF_OP_CLIP\fP(ADDR)   dst[ADDR] = ClipPel<T>( 2 * dst[ADDR] \- src[ADDR], clpRng )"
.br
.ti -1c
.RI "#define \fBREM_HF_OP\fP(ADDR)   dst[ADDR] =             2 * dst[ADDR] \- src[ADDR]"
.br
.ti -1c
.RI "#define \fBMEAN_DIFF_INC\fP"
.br
.ti -1c
.RI "#define \fBMEAN_DIFF_OP\fP(ADDR)   acc += src1[ADDR] \- src2[ADDR]"
.br
.ti -1c
.RI "#define \fBOFFSET_INC\fP   dst       += stride"
.br
.ti -1c
.RI "#define \fBOFFSET_OP\fP(ADDR)   dst[ADDR] \-= val"
.br
.ti -1c
.RI "#define \fBAVG_INC\fP   src += stride"
.br
.ti -1c
.RI "#define \fBAVG_OP\fP(ADDR)   acc += src[ADDR]"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBAreaBuf\fP< \fBPel\fP > \fBvtm::PelBuf\fP"
.br
.ti -1c
.RI "typedef \fBAreaBuf\fP< const \fBPel\fP > \fBvtm::CPelBuf\fP"
.br
.ti -1c
.RI "typedef \fBAreaBuf\fP< \fBTCoeff\fP > \fBvtm::CoeffBuf\fP"
.br
.ti -1c
.RI "typedef \fBAreaBuf\fP< const \fBTCoeff\fP > \fBvtm::CCoeffBuf\fP"
.br
.ti -1c
.RI "typedef \fBAreaBuf\fP< \fBMotionInfo\fP > \fBvtm::MotionBuf\fP"
.br
.ti -1c
.RI "typedef \fBAreaBuf\fP< const \fBMotionInfo\fP > \fBvtm::CMotionBuf\fP"
.br
.ti -1c
.RI "typedef \fBAreaBuf\fP< \fBTCoeff\fP > \fBvtm::PLTescapeBuf\fP"
.br
.ti -1c
.RI "typedef \fBAreaBuf\fP< const \fBTCoeff\fP > \fBvtm::CPLTescapeBuf\fP"
.br
.ti -1c
.RI "typedef \fBAreaBuf\fP< bool > \fBvtm::PLTtypeBuf\fP"
.br
.ti -1c
.RI "typedef \fBAreaBuf\fP< const bool > \fBvtm::CPLTtypeBuf\fP"
.br
.ti -1c
.RI "typedef \fBUnitBuf\fP< \fBPel\fP > \fBvtm::PelUnitBuf\fP"
.br
.ti -1c
.RI "typedef \fBUnitBuf\fP< const \fBPel\fP > \fBvtm::CPelUnitBuf\fP"
.br
.ti -1c
.RI "typedef \fBUnitBuf\fP< \fBTCoeff\fP > \fBvtm::CoeffUnitBuf\fP"
.br
.ti -1c
.RI "typedef \fBUnitBuf\fP< const \fBTCoeff\fP > \fBvtm::CCoeffUnitBuf\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBvtm::paddingCore\fP (\fBPel\fP *ptr, int stride, int width, int height, int padSize)"
.br
.ti -1c
.RI "void \fBvtm::copyBufferCore\fP (\fBPel\fP *src, int srcStride, \fBPel\fP *dst, int dstStride, int width, int height)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Low-overhead class describing 2D memory layout\&. 


.PP
Definition in file \fBBuffer\&.h\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define AVG_INC   src += stride"

.SS "#define AVG_OP(ADDR)   acc += src[ADDR]"

.SS "#define FILL_INC   dest      += stride"

.SS "#define FILL_OP(ADDR)   dest[ADDR] = val"

.SS "#define MEAN_DIFF_INC"
\fBValue:\fP.PP
.nf
  src1 +=       stride; \\
  src2 += other\&.stride; \\
.fi

.SS "#define MEAN_DIFF_OP(ADDR)   acc += src1[ADDR] \- src2[ADDR]"

.SS "#define OFFSET_INC   dst       += stride"

.SS "#define OFFSET_OP(ADDR)   dst[ADDR] \-= val"

.SS "#define REM_HF_INC"
\fBValue:\fP.PP
.nf
  src += srcStride; \\
  dst += dstStride; \\
.fi

.SS "#define REM_HF_INC"
\fBValue:\fP.PP
.nf
  src += srcStride; \\
  dst += dstStride; \\
.fi

.SS "#define REM_HF_OP(ADDR)   dst[ADDR] =             T((dst[ADDR]*weight0 \- src[ADDR]*weight1 + (1<<15))>>16)"

.SS "#define REM_HF_OP(ADDR)   dst[ADDR] =             2 * dst[ADDR] \- src[ADDR]"

.SS "#define REM_HF_OP_CLIP(ADDR)   dst[ADDR] = ClipPel<T>( T((dst[ADDR]*weight0 \- src[ADDR]*weight1 + (1<<15))>>16), clpRng )"

.SS "#define REM_HF_OP_CLIP(ADDR)   dst[ADDR] = ClipPel<T>( 2 * dst[ADDR] \- src[ADDR], clpRng )"

.SS "#define SIZE_AWARE_PER_EL_OP(OP, INC)"

.PP
Definition at line \fB178\fP of file \fBBuffer\&.h\fP\&.
.SS "#define SUBS_INC"
\fBValue:\fP.PP
.nf
  dest +=       stride; \\
  subs += other\&.stride; \\
.fi

.SS "#define SUBS_OP(ADDR)   dest[ADDR] \-= subs[ADDR]"

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
