.TH "util/src/Buffer.cpp" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
util/src/Buffer.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'Buffer\&.hpp'\fP
.br
\fC#include 'Diagnostics\&.hpp'\fP
.br
\fC#include <cassert>\fP
.br
\fC#include <cstring>\fP
.br
\fC#include <stdlib\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBlctm::BufferVector\fP"
.br
.ti -1c
.RI "class \fBlctm::BufferAligned\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBlctm\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::unique_ptr< \fBBuffer\fP > \fBlctm::CreateBufferVector\fP (const uint8_t *data, unsigned size)"
.br
.ti -1c
.RI "std::unique_ptr< \fBBuffer\fP > \fBlctm::CreateBufferVector\fP (unsigned size)"
.br
.ti -1c
.RI "std::unique_ptr< \fBBuffer\fP > \fBlctm::CreateBufferAligned\fP (const uint8_t *data, unsigned size)"
.br
.ti -1c
.RI "std::unique_ptr< \fBBuffer\fP > \fBlctm::CreateBufferAligned\fP (unsigned size)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
