.TH "deps/base_vvc/minimum_VTM/source/Lib/DecoderLib/CABACReader.h" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deps/base_vvc/minimum_VTM/source/Lib/DecoderLib/CABACReader.h \- Reader for low level syntax\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'BinDecoder\&.h'\fP
.br
\fC#include 'CommonLib/ContextModelling\&.h'\fP
.br
\fC#include 'CommonLib/MotionInfo\&.h'\fP
.br
\fC#include 'CommonLib/UnitPartitioner\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBvtm::CABACReader\fP"
.br
.ti -1c
.RI "class \fBvtm::CABACDecoder\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBvtm\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Reader for low level syntax\&. 


.PP
Definition in file \fBCABACReader\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
