.TH "deps/base_vvc/minimum_VTM/source/Lib/CommonLib/CacheModel.h" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deps/base_vvc/minimum_VTM/source/Lib/CommonLib/CacheModel.h \- general cache class (header)  

.SH SYNOPSIS
.br
.PP
\fC#include 'Picture\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBvtm\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBJVET_J0090_SET_CACHE_ENABLE\fP(enable)   /* do nothing */"
.br
.ti -1c
.RI "#define \fBJVET_J0090_SET_REF_PICTURE\fP(refPic,  compID)   /* do nothing */"
.br
.ti -1c
.RI "#define \fBJVET_J0090_CACHE_ACCESS\fP(src,  fileName,  line)   /* do nothing */"
.br
.in -1c
.SH "Detailed Description"
.PP 
general cache class (header) 


.PP
Definition in file \fBCacheModel\&.h\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define JVET_J0090_CACHE_ACCESS(src, fileName, line)   /* do nothing */"

.PP
Definition at line \fB49\fP of file \fBCacheModel\&.h\fP\&.
.SS "#define JVET_J0090_SET_CACHE_ENABLE(enable)   /* do nothing */"

.PP
Definition at line \fB47\fP of file \fBCacheModel\&.h\fP\&.
.SS "#define JVET_J0090_SET_REF_PICTURE(refPic, compID)   /* do nothing */"

.PP
Definition at line \fB48\fP of file \fBCacheModel\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
