.TH "deps/base_vvc/minimum_VTM/source/Lib/CommonLib/CacheModel.cpp" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deps/base_vvc/minimum_VTM/source/Lib/CommonLib/CacheModel.cpp \- general cache class  

.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <memory\&.h>\fP
.br
\fC#include <inttypes\&.h>\fP
.br
\fC#include 'Utilities/program_options_lite\&.h'\fP
.br
\fC#include 'CacheModel\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB__STDC_FORMAT_MACROS\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
general cache class 


.PP
Definition in file \fBCacheModel\&.cpp\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define __STDC_FORMAT_MACROS"

.PP
Definition at line \fB42\fP of file \fBCacheModel\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
