.TH "deps/base_vvc/minimum_VTM/source/Lib/CommonLib/ChromaFormat.h" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deps/base_vvc/minimum_VTM/source/Lib/CommonLib/ChromaFormat.h
.SH SYNOPSIS
.br
.PP
\fC#include 'Common\&.h'\fP
.br
\fC#include 'CommonDef\&.h'\fP
.br
\fC#include 'Rom\&.h'\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <vector>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBvtm\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBInputColourSpaceConversion\fP \fBvtm::stringToInputColourSpaceConvert\fP (const std::string &value, const bool bIsForward)"
.br
.ti -1c
.RI "std::string \fBvtm::getListOfColourSpaceConverts\fP (const bool bIsForward)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
