.TH "cmake/CMakeBuild/bin/cmakebuild_update.py" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cmake/CMakeBuild/bin/cmakebuild_update.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBcmakebuild_update\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBcmakebuild_update\&.app\fP = pyhhi\&.build\&.app\&.cmbldup\&.CMakeBuildUpdateApp()"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
