.TH "cmake/CMakeBuild/bin/cmake.py" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cmake/CMakeBuild/bin/cmake.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBcmake\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBcmake\&.app\fP = pyhhi\&.build\&.app\&.cmk\&.CMakeLauncherApp()"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
