.TH "cmake" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cmake
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBapp\fP = pyhhi\&.build\&.app\&.cmk\&.CMakeLauncherApp()"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "cmake\&.app = pyhhi\&.build\&.app\&.cmk\&.CMakeLauncherApp()"

.PP
Definition at line \fB10\fP of file \fBcmake\&.py\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
