.TH "util/include/Codec.hpp" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
util/include/Codec.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <cstdint>\fP
.br
\fC#include <string>\fP
.br
\fC#include 'CodecApi\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBlctm\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBCodec\fP * \fBlctm::CodecCreate\fP (const std::string &\fBname\fP, \fBCodecOperation\fP operation, const std::string &json_codec_selection_options)"
.br
.ti -1c
.RI "void \fBlctm::CodecRelease\fP (\fBCodec\fP *codec)"
.br
.ti -1c
.RI "std::string \fBlctm::CodecErrorToString\fP (\fBCodec\fP *codec, \fBCodecError\fP error)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
