.TH "codectest" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
codectest
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBmake_opt\fP (d, k, v)"
.br
.ti -1c
.RI "\fBmd5sum\fP (filename, blocksize=65536)"
.br
.ti -1c
.RI "\fBparse_filename\fP (name)"
.br
.ti -1c
.RI "\fBrun_subprocess\fP (title, \fBargs\fP, logfile, show_progress)"
.br
.ti -1c
.RI "\fBrun_testmodel_encode_decode\fP (encoder, decoder, input_dir, params, label, show_progress)"
.br
.ti -1c
.RI "\fBrun_testmodel_decode\fP (decoder, input_dir, params, label, show_progress)"
.br
.ti -1c
.RI "\fBrun_tests\fP (label, encoder, decoder, input_dir, configs, show_progress)"
.br
.ti -1c
.RI "\fBplatform_exe\fP (path, name)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "list \fBTEST_PARAMETERS\fP = [ 'checksum' ]"
.br
.ti -1c
.RI "list \fBINPUTS\fP = ['input_file', 'base', 'base_recon']"
.br
.ti -1c
.RI "list \fBIMAGE_NAME_PARAMS\fP"
.br
.ti -1c
.RI "\fBparser\fP = argparse\&.ArgumentParser()"
.br
.ti -1c
.RI "\fBhelp\fP"
.br
.ti -1c
.RI "\fBdefault\fP"
.br
.ti -1c
.RI "\fBargs\fP = parser\&.parse_args()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "codectest\&.make_opt ( d,  k,  v)"

.PP
.nf
Convert key,value into a command line parameter, prefixing any inputs with input base dir\&.
.fi
.PP
 
.PP
Definition at line \fB16\fP of file \fBcodectest\&.py\fP\&.
.SS "codectest\&.md5sum ( filename,  blocksize = \fC65536\fP)"

.PP
.nf
    Compute MD5 checksum of named file\&.
.fi
.PP
 
.PP
Definition at line \fB24\fP of file \fBcodectest\&.py\fP\&.
.SS "codectest\&.parse_filename ( name)"

.PP
.nf
    Extract vooya-ish image metadata from filename in form suitable for use as encoder parameters\&.
.fi
.PP
 
.PP
Definition at line \fB42\fP of file \fBcodectest\&.py\fP\&.
.SS "codectest\&.platform_exe ( path,  name)"

.PP
.nf
Given a directory and an executable file name, return platform specifix path\&.
.fi
.PP
 
.PP
Definition at line \fB183\fP of file \fBcodectest\&.py\fP\&.
.SS "codectest\&.run_subprocess ( title,  args,  logfile,  show_progress)"

.PP
.nf
Run a comamnd as a subprocess - report progress and capture output (both stderr and stdout) to a log file\&.
.fi
.PP
 
.PP
Definition at line \fB61\fP of file \fBcodectest\&.py\fP\&.
.SS "codectest\&.run_testmodel_decode ( decoder,  input_dir,  params,  label,  show_progress)"

.PP
.nf
    Run an decode of prepared ES file\&.
    Return true is recon & decoded yuv match required checksum\&.
.fi
.PP
 
.PP
Definition at line \fB131\fP of file \fBcodectest\&.py\fP\&.
.SS "codectest\&.run_testmodel_encode_decode ( encoder,  decoder,  input_dir,  params,  label,  show_progress)"

.PP
.nf
    Run an encode followed by decode of given file (using given params)
    Return true is recon & decoded yuv match required checksum\&.
.fi
.PP
 
.PP
Definition at line \fB88\fP of file \fBcodectest\&.py\fP\&.
.SS "codectest\&.run_tests ( label,  encoder,  decoder,  input_dir,  configs,  show_progress)"

.PP
.nf
Read a \&.CSV file and run test described by each line\&.
.fi
.PP
 
.PP
Definition at line \fB158\fP of file \fBcodectest\&.py\fP\&.
.SH "Variable Documentation"
.PP 
.SS "codectest\&.args = parser\&.parse_args()"

.PP
Definition at line \fB197\fP of file \fBcodectest\&.py\fP\&.
.SS "codectest\&.default"

.PP
Definition at line \fB191\fP of file \fBcodectest\&.py\fP\&.
.SS "codectest\&.help"

.PP
Definition at line \fB191\fP of file \fBcodectest\&.py\fP\&.
.SS "list codectest\&.IMAGE_NAME_PARAMS"
\fBInitial value:\fP.PP
.nf
1 =  [
2     ("width", re\&.compile("([0\-9]+)x[0\-9]+")),
3     ("height", re\&.compile("[0\-9]+x([0\-9]+)")),
4     ("fps", re\&.compile("([0\-9]+)(fps|hz)")),
5     ("bit_depth", re\&.compile("([0\-9]+)(bits?|bpp)")),
6     ("format", re\&.compile("^(420p|422p|yuv|yuyv|y|)$"))
7 ]
.fi

.PP
Definition at line \fB34\fP of file \fBcodectest\&.py\fP\&.
.SS "list codectest\&.INPUTS = ['input_file', 'base', 'base_recon']"

.PP
Definition at line \fB15\fP of file \fBcodectest\&.py\fP\&.
.SS "codectest\&.parser = argparse\&.ArgumentParser()"

.PP
Definition at line \fB190\fP of file \fBcodectest\&.py\fP\&.
.SS "list codectest\&.TEST_PARAMETERS = [ 'checksum' ]"

.PP
Definition at line \fB13\fP of file \fBcodectest\&.py\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
