.TH "util/src/Codec.cpp" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
util/src/Codec.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'Codec\&.hpp'\fP
.br
\fC#include <memory>\fP
.br
\fC#include 'Misc\&.hpp'\fP
.br
\fC#include 'Diagnostics\&.hpp'\fP
.br
\fC#include 'Platform\&.hpp'\fP
.br
\fC#include 'SharedLibrary\&.hpp'\fP
.br
\fC#include 'CodecApi\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBlctm\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef uint32_t(* \fBlctm::codec_api_version_fn_t\fP) ()"
.br
.ti -1c
.RI "typedef uint32_t(* \fBlctm::codec_api_query_fn_t\fP) (int num, const char *buffer, uint32_t buffer_size)"
.br
.ti -1c
.RI "typedef \fBCodec\fP *(* \fBlctm::codec_api_create_fn_t\fP) (const char *\fBname\fP, \fBCodecOperation\fP operation, const char *json_configuration)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBCodec\fP * \fBlctm::CodecCreate\fP (const string &\fBname\fP, \fBCodecOperation\fP operation, const string &create_options)"
.br
.ti -1c
.RI "void \fBlctm::CodecRelease\fP (\fBCodec\fP *codec)"
.br
.ti -1c
.RI "std::string \fBlctm::CodecErrorToString\fP (\fBCodec\fP *codec, \fBCodecError\fP error)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
