.TH "CodecImage" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CodecImage
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CodecApi\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBbpp\fP"
.br
.ti -1c
.RI "uint32_t \fBwidth_y\fP"
.br
.ti -1c
.RI "uint32_t \fBheight_y\fP"
.br
.ti -1c
.RI "uint32_t \fBstride_y\fP"
.br
.ti -1c
.RI "uint32_t \fBwidth_uv\fP"
.br
.ti -1c
.RI "uint32_t \fBheight_uv\fP"
.br
.ti -1c
.RI "uint32_t \fBstride_uv\fP"
.br
.ti -1c
.RI "const uint8_t * \fBdata_y\fP"
.br
.ti -1c
.RI "const uint8_t * \fBdata_u\fP"
.br
.ti -1c
.RI "const uint8_t * \fBdata_v\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB58\fP of file \fBCodecApi\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "uint32_t CodecImage::bpp"

.PP
Definition at line \fB59\fP of file \fBCodecApi\&.h\fP\&.
.SS "const uint8_t* CodecImage::data_u"

.PP
Definition at line \fB69\fP of file \fBCodecApi\&.h\fP\&.
.SS "const uint8_t* CodecImage::data_v"

.PP
Definition at line \fB70\fP of file \fBCodecApi\&.h\fP\&.
.SS "const uint8_t* CodecImage::data_y"

.PP
Definition at line \fB68\fP of file \fBCodecApi\&.h\fP\&.
.SS "uint32_t CodecImage::height_uv"

.PP
Definition at line \fB65\fP of file \fBCodecApi\&.h\fP\&.
.SS "uint32_t CodecImage::height_y"

.PP
Definition at line \fB61\fP of file \fBCodecApi\&.h\fP\&.
.SS "uint32_t CodecImage::stride_uv"

.PP
Definition at line \fB66\fP of file \fBCodecApi\&.h\fP\&.
.SS "uint32_t CodecImage::stride_y"

.PP
Definition at line \fB62\fP of file \fBCodecApi\&.h\fP\&.
.SS "uint32_t CodecImage::width_uv"

.PP
Definition at line \fB64\fP of file \fBCodecApi\&.h\fP\&.
.SS "uint32_t CodecImage::width_y"

.PP
Definition at line \fB60\fP of file \fBCodecApi\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
