.TH "util/include/CodecApi.h" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
util/include/CodecApi.h
.SH SYNOPSIS
.br
.PP
\fC#include <stdlib\&.h>\fP
.br
\fC#include <stdint\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBCodecImage\fP"
.br
.ti -1c
.RI "struct \fBCodec\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBLOADABLE_CODEC_API_VERSION\fP   1"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef void * \fBCodecContext\fP"
.br
.ti -1c
.RI "typedef void * \fBCodecError\fP"
.br
.ti -1c
.RI "typedef void * \fBCodecMetadata\fP"
.br
.ti -1c
.RI "typedef enum \fBCodecOperation\fP \fBCodecOperation\fP"
.br
.ti -1c
.RI "typedef struct \fBCodecImage\fP \fBCodecImage\fP"
.br
.ti -1c
.RI "typedef struct \fBCodec\fP \fBCodec\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBCodecOperation\fP { \fBCodecOperation_Encode\fP, \fBCodecOperation_Decode\fP, \fBCodecOperation_Parse\fP }"
.br
.ti -1c
.RI "enum \fBPropertyID\fP { \fBPropertyID_None\fP = 0, \fBPropertyID_Timestamp\fP = 1, \fBPropertyID_PictureOrderCount\fP = 2, \fBPropertyID_QP\fP = 3, \fBPropertyID_FrameType\fP = 4 }"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define LOADABLE_CODEC_API_VERSION   1"

.PP
Definition at line \fB45\fP of file \fBCodecApi\&.h\fP\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBCodec\fP \fBCodec\fP"

.SS "typedef void* \fBCodecContext\fP"

.PP
Definition at line \fB47\fP of file \fBCodecApi\&.h\fP\&.
.SS "typedef void* \fBCodecError\fP"

.PP
Definition at line \fB48\fP of file \fBCodecApi\&.h\fP\&.
.SS "typedef struct \fBCodecImage\fP \fBCodecImage\fP"

.SS "typedef void* \fBCodecMetadata\fP"

.PP
Definition at line \fB49\fP of file \fBCodecApi\&.h\fP\&.
.SS "typedef enum \fBCodecOperation\fP \fBCodecOperation\fP"

.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBCodecOperation\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fICodecOperation_Encode \fP\fP
.TP
\fB\fICodecOperation_Decode \fP\fP
.TP
\fB\fICodecOperation_Parse \fP\fP
.PP
Definition at line \fB51\fP of file \fBCodecApi\&.h\fP\&.
.SS "enum \fBPropertyID\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIPropertyID_None \fP\fP
.TP
\fB\fIPropertyID_Timestamp \fP\fP
.TP
\fB\fIPropertyID_PictureOrderCount \fP\fP
.TP
\fB\fIPropertyID_QP \fP\fP
.TP
\fB\fIPropertyID_FrameType \fP\fP
.PP
Definition at line \fB123\fP of file \fBCodecApi\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
