.TH "Codec" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Codec
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CodecApi\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBapi_version\fP"
.br
.ti -1c
.RI "const char * \fBname\fP"
.br
.ti -1c
.RI "const char * \fBversion_string\fP"
.br
.ti -1c
.RI "\fBCodecOperation\fP \fBoperation\fP"
.br
.ti -1c
.RI "void * \fBinternal\fP"
.br
.ti -1c
.RI "int32_t(* \fBcreate_context\fP )(\fBCodecContext\fP *context, const char *json_configuration, \fBCodecError\fP *error)"
.br
.ti -1c
.RI "int32_t(* \fBpush_packet\fP )(\fBCodecContext\fP context, const uint8_t *data, size_t length, \fBCodecMetadata\fP metadata, int8_t eos, \fBCodecError\fP *error)"
.br
.ti -1c
.RI "int32_t(* \fBpull_packet\fP )(\fBCodecContext\fP context, const uint8_t *data, size_t length, \fBCodecMetadata\fP *metadata, int8_t *eos, \fBCodecError\fP *error)"
.br
.ti -1c
.RI "int32_t(* \fBpush_image\fP )(\fBCodecContext\fP context, const \fBCodecImage\fP *image, \fBCodecMetadata\fP metadata, int8_t eos, \fBCodecError\fP *error)"
.br
.ti -1c
.RI "int32_t(* \fBpull_image\fP )(\fBCodecContext\fP context, \fBCodecImage\fP *image, \fBCodecMetadata\fP *metadata, int8_t *eos, \fBCodecError\fP *error)"
.br
.ti -1c
.RI "int32_t(* \fBcreate_metadata\fP )(\fBCodecMetadata\fP *metadata, \fBCodecError\fP *error)"
.br
.ti -1c
.RI "void(* \fBrelease_context\fP )(\fBCodecContext\fP context)"
.br
.ti -1c
.RI "void(* \fBrelease_error\fP )(\fBCodecError\fP error)"
.br
.ti -1c
.RI "void(* \fBrelease_metadata\fP )(\fBCodecMetadata\fP metadata)"
.br
.ti -1c
.RI "const char *(* \fBget_metadata_property_name\fP )(\fBCodecMetadata\fP metadata, uint32_t id)"
.br
.ti -1c
.RI "uint32_t(* \fBget_metadata_property_u32\fP )(\fBCodecMetadata\fP metadata, uint32_t id)"
.br
.ti -1c
.RI "int32_t(* \fBget_metadata_property_i32\fP )(\fBCodecMetadata\fP metadata, uint32_t id)"
.br
.ti -1c
.RI "uint64_t(* \fBget_metadata_property_u64\fP )(\fBCodecMetadata\fP metadata, uint32_t id)"
.br
.ti -1c
.RI "int64_t(* \fBget_metadata_property_i64\fP )(\fBCodecMetadata\fP metadata, uint32_t id)"
.br
.ti -1c
.RI "int8_t(* \fBget_metadata_property_bool\fP )(\fBCodecMetadata\fP metadata, uint32_t id)"
.br
.ti -1c
.RI "void(* \fBset_metadata_property_u32\fP )(\fBCodecMetadata\fP metadata, uint32_t id, uint32_t v)"
.br
.ti -1c
.RI "void(* \fBset_metadata_property_i32\fP )(\fBCodecMetadata\fP metadata, uint32_t id, int32_t v)"
.br
.ti -1c
.RI "void(* \fBset_metadata_property_u64\fP )(\fBCodecMetadata\fP metadata, uint32_t id, uint64_t v)"
.br
.ti -1c
.RI "void(* \fBset_metadata_property_i64\fP )(\fBCodecMetadata\fP metadata, uint32_t id, uint64_t v)"
.br
.ti -1c
.RI "void(* \fBset_metadata_property_bool\fP )(\fBCodecMetadata\fP metadata, uint32_t id, uint8_t v)"
.br
.ti -1c
.RI "int32_t(* \fBget_error_code\fP )(\fBCodecError\fP error)"
.br
.ti -1c
.RI "size_t(* \fBget_error_message\fP )(\fBCodecError\fP error, char *data, size_t length)"
.br
.ti -1c
.RI "size_t(* \fBget_error_file\fP )(\fBCodecError\fP error, char *filename, size_t length)"
.br
.ti -1c
.RI "uint32_t(* \fBget_error_line\fP )(\fBCodecError\fP error)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB75\fP of file \fBCodecApi\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "uint32_t Codec::api_version"

.PP
Definition at line \fB76\fP of file \fBCodecApi\&.h\fP\&.
.SS "int32_t(* Codec::create_context) (\fBCodecContext\fP *context, const char *json_configuration, \fBCodecError\fP *error)"

.PP
Definition at line \fB84\fP of file \fBCodecApi\&.h\fP\&.
.SS "int32_t(* Codec::create_metadata) (\fBCodecMetadata\fP *metadata, \fBCodecError\fP *error)"

.PP
Definition at line \fB94\fP of file \fBCodecApi\&.h\fP\&.
.SS "int32_t(* Codec::get_error_code) (\fBCodecError\fP error)"

.PP
Definition at line \fB115\fP of file \fBCodecApi\&.h\fP\&.
.SS "size_t(* Codec::get_error_file) (\fBCodecError\fP error, char *filename, size_t length)"

.PP
Definition at line \fB117\fP of file \fBCodecApi\&.h\fP\&.
.SS "uint32_t(* Codec::get_error_line) (\fBCodecError\fP error)"

.PP
Definition at line \fB118\fP of file \fBCodecApi\&.h\fP\&.
.SS "size_t(* Codec::get_error_message) (\fBCodecError\fP error, char *data, size_t length)"

.PP
Definition at line \fB116\fP of file \fBCodecApi\&.h\fP\&.
.SS "int8_t(* Codec::get_metadata_property_bool) (\fBCodecMetadata\fP metadata, uint32_t id)"

.PP
Definition at line \fB106\fP of file \fBCodecApi\&.h\fP\&.
.SS "int32_t(* Codec::get_metadata_property_i32) (\fBCodecMetadata\fP metadata, uint32_t id)"

.PP
Definition at line \fB103\fP of file \fBCodecApi\&.h\fP\&.
.SS "int64_t(* Codec::get_metadata_property_i64) (\fBCodecMetadata\fP metadata, uint32_t id)"

.PP
Definition at line \fB105\fP of file \fBCodecApi\&.h\fP\&.
.SS "const char *(* Codec::get_metadata_property_name) (\fBCodecMetadata\fP metadata, uint32_t id)"

.PP
Definition at line \fB101\fP of file \fBCodecApi\&.h\fP\&.
.SS "uint32_t(* Codec::get_metadata_property_u32) (\fBCodecMetadata\fP metadata, uint32_t id)"

.PP
Definition at line \fB102\fP of file \fBCodecApi\&.h\fP\&.
.SS "uint64_t(* Codec::get_metadata_property_u64) (\fBCodecMetadata\fP metadata, uint32_t id)"

.PP
Definition at line \fB104\fP of file \fBCodecApi\&.h\fP\&.
.SS "void* Codec::internal"

.PP
Definition at line \fB82\fP of file \fBCodecApi\&.h\fP\&.
.SS "const char* Codec::name"

.PP
Definition at line \fB77\fP of file \fBCodecApi\&.h\fP\&.
.SS "\fBCodecOperation\fP Codec::operation"

.PP
Definition at line \fB79\fP of file \fBCodecApi\&.h\fP\&.
.SS "int32_t(* Codec::pull_image) (\fBCodecContext\fP context, \fBCodecImage\fP *image, \fBCodecMetadata\fP *metadata, int8_t *eos, \fBCodecError\fP *error)"

.PP
Definition at line \fB92\fP of file \fBCodecApi\&.h\fP\&.
.SS "int32_t(* Codec::pull_packet) (\fBCodecContext\fP context, const uint8_t *data, size_t length, \fBCodecMetadata\fP *metadata, int8_t *eos, \fBCodecError\fP *error)"

.PP
Definition at line \fB88\fP of file \fBCodecApi\&.h\fP\&.
.SS "int32_t(* Codec::push_image) (\fBCodecContext\fP context, const \fBCodecImage\fP *image, \fBCodecMetadata\fP metadata, int8_t eos, \fBCodecError\fP *error)"

.PP
Definition at line \fB91\fP of file \fBCodecApi\&.h\fP\&.
.SS "int32_t(* Codec::push_packet) (\fBCodecContext\fP context, const uint8_t *data, size_t length, \fBCodecMetadata\fP metadata, int8_t eos, \fBCodecError\fP *error)"

.PP
Definition at line \fB87\fP of file \fBCodecApi\&.h\fP\&.
.SS "void(* Codec::release_context) (\fBCodecContext\fP context)"

.PP
Definition at line \fB96\fP of file \fBCodecApi\&.h\fP\&.
.SS "void(* Codec::release_error) (\fBCodecError\fP error)"

.PP
Definition at line \fB97\fP of file \fBCodecApi\&.h\fP\&.
.SS "void(* Codec::release_metadata) (\fBCodecMetadata\fP metadata)"

.PP
Definition at line \fB98\fP of file \fBCodecApi\&.h\fP\&.
.SS "void(* Codec::set_metadata_property_bool) (\fBCodecMetadata\fP metadata, uint32_t id, uint8_t v)"

.PP
Definition at line \fB112\fP of file \fBCodecApi\&.h\fP\&.
.SS "void(* Codec::set_metadata_property_i32) (\fBCodecMetadata\fP metadata, uint32_t id, int32_t v)"

.PP
Definition at line \fB109\fP of file \fBCodecApi\&.h\fP\&.
.SS "void(* Codec::set_metadata_property_i64) (\fBCodecMetadata\fP metadata, uint32_t id, uint64_t v)"

.PP
Definition at line \fB111\fP of file \fBCodecApi\&.h\fP\&.
.SS "void(* Codec::set_metadata_property_u32) (\fBCodecMetadata\fP metadata, uint32_t id, uint32_t v)"

.PP
Definition at line \fB108\fP of file \fBCodecApi\&.h\fP\&.
.SS "void(* Codec::set_metadata_property_u64) (\fBCodecMetadata\fP metadata, uint32_t id, uint64_t v)"

.PP
Definition at line \fB110\fP of file \fBCodecApi\&.h\fP\&.
.SS "const char* Codec::version_string"

.PP
Definition at line \fB78\fP of file \fBCodecApi\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
