.TH "util/src/CodecUtils.c" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
util/src/CodecUtils.c
.SH SYNOPSIS
.br
.PP
\fC#include 'CodecUtils\&.h'\fP
.br
\fC#include <memory\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBCodec\fP * \fBLTMCodecAllocate\fP (const char *name, const char *version_string, \fBCodecOperation\fP operation)"
.br
.ti -1c
.RI "void \fBLTMCodecFree\fP (\fBCodec\fP *codec)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBCodec\fP * LTMCodecAllocate (const char * name, const char * version_string, \fBCodecOperation\fP operation)"

.PP
Definition at line \fB132\fP of file \fBCodecUtils\&.c\fP\&.
.SS "void LTMCodecFree (\fBCodec\fP * codec)"

.PP
Definition at line \fB167\fP of file \fBCodecUtils\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
