.TH "tests/codectest.py" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tests/codectest.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBcodectest\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBcodectest\&.make_opt\fP (d, k, v)"
.br
.ti -1c
.RI "\fBcodectest\&.md5sum\fP (filename, blocksize=65536)"
.br
.ti -1c
.RI "\fBcodectest\&.parse_filename\fP (name)"
.br
.ti -1c
.RI "\fBcodectest\&.run_subprocess\fP (title, \fBargs\fP, logfile, show_progress)"
.br
.ti -1c
.RI "\fBcodectest\&.run_testmodel_encode_decode\fP (encoder, decoder, input_dir, params, label, show_progress)"
.br
.ti -1c
.RI "\fBcodectest\&.run_testmodel_decode\fP (decoder, input_dir, params, label, show_progress)"
.br
.ti -1c
.RI "\fBcodectest\&.run_tests\fP (label, encoder, decoder, input_dir, configs, show_progress)"
.br
.ti -1c
.RI "\fBcodectest\&.platform_exe\fP (path, name)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "list \fBcodectest\&.TEST_PARAMETERS\fP = [ 'checksum' ]"
.br
.ti -1c
.RI "list \fBcodectest\&.INPUTS\fP = ['input_file', 'base', 'base_recon']"
.br
.ti -1c
.RI "list \fBcodectest\&.IMAGE_NAME_PARAMS\fP"
.br
.ti -1c
.RI "\fBcodectest\&.parser\fP = argparse\&.ArgumentParser()"
.br
.ti -1c
.RI "\fBcodectest\&.help\fP"
.br
.ti -1c
.RI "\fBcodectest\&.default\fP"
.br
.ti -1c
.RI "\fBcodectest\&.args\fP = parser\&.parse_args()"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
