.TH "deps/base_vvc/src/codec_api.cpp" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deps/base_vvc/src/codec_api.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <cstdio>\fP
.br
\fC#include <cstdlib>\fP
.br
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <thread>\fP
.br
\fC#include 'memory\&.h'\fP
.br
\fC#include 'VideoIOYuvMem\&.h'\fP
.br
\fC#include 'DecAppMem\&.h'\fP
.br
\fC#include 'CodecApi\&.h'\fP
.br
\fC#include 'CodecUtils\&.h'\fP
.br
\fC#include 'Diagnostics\&.hpp'\fP
.br
\fC#include 'Misc\&.hpp'\fP
.br
\fC#include 'RingBuffer\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBMetadata\fP"
.br
.ti -1c
.RI "struct \fBError\fP"
.br
.ti -1c
.RI "struct \fBDecodedImage\fP"
.br
.ti -1c
.RI "class \fBContext\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBState\fP { \fBStateNone\fP = 0, \fBStatePushing\fP, \fBStateDecoding\fP, \fBStateFlushing\fP, \fBStateFinished\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "CODEC_API_EXPORT uint32_t \fBCodecAPI_Version\fP ()"
.br
.ti -1c
.RI "CODEC_API_EXPORT uint32_t \fBCodecAPI_Query\fP (int num, const char *buffer, uint32_t buffer_size)"
.br
.ti -1c
.RI "CODEC_API_EXPORT \fBCodec\fP * \fBCodecAPI_Create\fP (const char *name, \fBCodecOperation\fP operation, const char *json_create_options)"
.br
.ti -1c
.RI "CODEC_API_EXPORT void \fBCodecAPI_Release\fP (\fBCodec\fP *codec)"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBState\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIStateNone \fP\fP
.TP
\fB\fIStatePushing \fP\fP
.TP
\fB\fIStateDecoding \fP\fP
.TP
\fB\fIStateFlushing \fP\fP
.TP
\fB\fIStateFinished \fP\fP
.PP
Definition at line \fB45\fP of file \fBcodec_api\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "CODEC_API_EXPORT \fBCodec\fP * CodecAPI_Create (const char * name, \fBCodecOperation\fP operation, const char * json_create_options)"

.PP
Definition at line \fB244\fP of file \fBcodec_api\&.cpp\fP\&.
.SS "CODEC_API_EXPORT uint32_t CodecAPI_Query (int num, const char * buffer, uint32_t buffer_size)"

.PP
Definition at line \fB237\fP of file \fBcodec_api\&.cpp\fP\&.
.SS "CODEC_API_EXPORT void CodecAPI_Release (\fBCodec\fP * codec)"

.PP
Definition at line \fB255\fP of file \fBcodec_api\&.cpp\fP\&.
.SS "CODEC_API_EXPORT uint32_t CodecAPI_Version ()"

.PP
Definition at line \fB233\fP of file \fBcodec_api\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
