.TH "deps/base_vvc/minimum_VTM/source/Lib/CommonLib/CodingStructure.h" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deps/base_vvc/minimum_VTM/source/Lib/CommonLib/CodingStructure.h \- A class managing the coding information for a specific image part\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'Unit\&.h'\fP
.br
\fC#include 'Buffer\&.h'\fP
.br
\fC#include 'CommonDef\&.h'\fP
.br
\fC#include 'UnitPartitioner\&.h'\fP
.br
\fC#include 'Slice\&.h'\fP
.br
\fC#include <vector>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBvtm::CodingStructure\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBvtm\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBvtm::PictureType\fP { \fBvtm::PIC_RECONSTRUCTION\fP = 0, \fBvtm::PIC_ORIGINAL\fP, \fBvtm::PIC_TRUE_ORIGINAL\fP, \fBvtm::PIC_FILTERED_ORIGINAL\fP, \fBvtm::PIC_PREDICTION\fP, \fBvtm::PIC_RESIDUAL\fP, \fBvtm::PIC_ORG_RESI\fP, \fBvtm::PIC_RECON_WRAP\fP, \fBvtm::PIC_ORIGINAL_INPUT\fP, \fBvtm::PIC_TRUE_ORIGINAL_INPUT\fP, \fBvtm::PIC_FILTERED_ORIGINAL_INPUT\fP, \fBvtm::NUM_PIC_TYPES\fP }"
.br
.in -1c
.SH "Detailed Description"
.PP 
A class managing the coding information for a specific image part\&. 


.PP
Definition in file \fBCodingStructure\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
