.TH "CodingStatistics::StatTool" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CodingStatistics::StatTool
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CodingStatistics\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBStatTool\fP ()"
.br
.ti -1c
.RI "void \fBclear\fP ()"
.br
.ti -1c
.RI "\fBStatTool\fP & \fBoperator+=\fP (const \fBStatTool\fP &src)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int64_t \fBcount\fP"
.br
.ti -1c
.RI "int64_t \fBpixels\fP"
.br
.ti -1c
.RI "int64_t \fBclassCount\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB339\fP of file \fBCodingStatistics\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CodingStatistics::StatTool::StatTool ()\fC [inline]\fP"

.PP
Definition at line \fB341\fP of file \fBCodingStatistics\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void CodingStatistics::StatTool::clear ()\fC [inline]\fP"

.PP
Definition at line \fB347\fP of file \fBCodingStatistics\&.h\fP\&.
.SS "\fBStatTool\fP & CodingStatistics::StatTool::operator+= (const \fBStatTool\fP & src)\fC [inline]\fP"

.PP
Definition at line \fB349\fP of file \fBCodingStatistics\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int64_t CodingStatistics::StatTool::classCount"

.PP
Definition at line \fB345\fP of file \fBCodingStatistics\&.h\fP\&.
.SS "int64_t CodingStatistics::StatTool::count"

.PP
Definition at line \fB343\fP of file \fBCodingStatistics\&.h\fP\&.
.SS "int64_t CodingStatistics::StatTool::pixels"

.PP
Definition at line \fB344\fP of file \fBCodingStatistics\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
