.TH "CodingStatistics::StatLogValue" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CodingStatistics::StatLogValue
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CodingStatistics\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBStatLogValue\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBvalues\fP [512+1]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB299\fP of file \fBCodingStatistics\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CodingStatistics::StatLogValue::StatLogValue ()\fC [inline]\fP"

.PP
Definition at line \fB302\fP of file \fBCodingStatistics\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "uint32_t CodingStatistics::StatLogValue::values[512+1]"

.PP
Definition at line \fB301\fP of file \fBCodingStatistics\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
