.TH "deps/base_vvc/minimum_VTM/source/Lib/CommonLib/CodingStructure.cpp" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deps/base_vvc/minimum_VTM/source/Lib/CommonLib/CodingStructure.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'CodingStructure\&.h'\fP
.br
\fC#include 'Unit\&.h'\fP
.br
\fC#include 'Slice\&.h'\fP
.br
\fC#include 'Picture\&.h'\fP
.br
\fC#include 'UnitTools\&.h'\fP
.br
\fC#include 'UnitPartitioner\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBvtm\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBXUCache\fP \fBvtm::g_globalUnitCache\fP = \fBXUCache\fP()"
.br
.ti -1c
.RI "const \fBUnitScale\fP \fBvtm::UnitScaleArray\fP [\fBNUM_CHROMA_FORMAT\fP][\fBMAX_NUM_COMPONENT\fP]"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
