.TH "CodingStatistics::CodingStatisticsData" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CodingStatistics::CodingStatisticsData
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CodingStatistics\&.h>\fP
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBCodingStatistics\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB385\fP of file \fBCodingStatistics\&.h\fP\&.
.SH "Friends And Related Symbol Documentation"
.PP 
.SS "friend class \fBCodingStatistics\fP\fC [friend]\fP"

.PP
Definition at line \fB395\fP of file \fBCodingStatistics\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
