.TH "CodingStatisticsClassType" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CodingStatisticsClassType
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CodingStatistics\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCodingStatisticsClassType\fP (const \fBCodingStatisticsType\fP t)"
.br
.ti -1c
.RI "\fBCodingStatisticsClassType\fP (const \fBCodingStatisticsType\fP t, const uint32_t width, const uint32_t height)"
.br
.ti -1c
.RI "\fBCodingStatisticsClassType\fP (const \fBCodingStatisticsType\fP t, const int width, const int height)"
.br
.ti -1c
.RI "\fBCodingStatisticsClassType\fP (const \fBCodingStatisticsType\fP t, const ComponentID cid)"
.br
.ti -1c
.RI "\fBCodingStatisticsClassType\fP (const \fBCodingStatisticsType\fP t, const ChannelType chid)"
.br
.ti -1c
.RI "\fBCodingStatisticsClassType\fP (const \fBCodingStatisticsType\fP t, const uint32_t width, const uint32_t height, const ComponentID cid)"
.br
.ti -1c
.RI "\fBCodingStatisticsClassType\fP (const \fBCodingStatisticsType\fP t, const uint32_t width, const uint32_t height, const ChannelType chid)"
.br
.ti -1c
.RI "\fB~CodingStatisticsClassType\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "\fBstatic\fP uint32_t \fBGetSubClassWidth\fP (const uint32_t \fBsubClass\fP)"
.br
.ti -1c
.RI "\fBstatic\fP uint32_t \fBGetSubClassHeight\fP (const uint32_t \fBsubClass\fP)"
.br
.ti -1c
.RI "\fBstatic\fP const char * \fBGetSubClassString\fP (const uint32_t \fBsubClass\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBCodingStatisticsType\fP \fBtype\fP"
.br
.ti -1c
.RI "uint32_t \fBsubClass\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB233\fP of file \fBCodingStatistics\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CodingStatisticsClassType::CodingStatisticsClassType (const \fBCodingStatisticsType\fP t)\fC [inline]\fP"

.PP
Definition at line \fB237\fP of file \fBCodingStatistics\&.h\fP\&.
.SS "CodingStatisticsClassType::CodingStatisticsClassType (const \fBCodingStatisticsType\fP t, const uint32_t width, const uint32_t height)\fC [inline]\fP"

.PP
Definition at line \fB241\fP of file \fBCodingStatistics\&.h\fP\&.
.SS "CodingStatisticsClassType::CodingStatisticsClassType (const \fBCodingStatisticsType\fP t, const int width, const int height)\fC [inline]\fP"

.PP
Definition at line \fB245\fP of file \fBCodingStatistics\&.h\fP\&.
.SS "CodingStatisticsClassType::CodingStatisticsClassType (const \fBCodingStatisticsType\fP t, const ComponentID cid)\fC [inline]\fP"

.PP
Definition at line \fB249\fP of file \fBCodingStatistics\&.h\fP\&.
.SS "CodingStatisticsClassType::CodingStatisticsClassType (const \fBCodingStatisticsType\fP t, const ChannelType chid)\fC [inline]\fP"

.PP
Definition at line \fB253\fP of file \fBCodingStatistics\&.h\fP\&.
.SS "CodingStatisticsClassType::CodingStatisticsClassType (const \fBCodingStatisticsType\fP t, const uint32_t width, const uint32_t height, const ComponentID cid)\fC [inline]\fP"

.PP
Definition at line \fB257\fP of file \fBCodingStatistics\&.h\fP\&.
.SS "CodingStatisticsClassType::CodingStatisticsClassType (const \fBCodingStatisticsType\fP t, const uint32_t width, const uint32_t height, const ChannelType chid)\fC [inline]\fP"

.PP
Definition at line \fB261\fP of file \fBCodingStatistics\&.h\fP\&.
.SS "CodingStatisticsClassType::~CodingStatisticsClassType ()\fC [inline]\fP"

.PP
Definition at line \fB265\fP of file \fBCodingStatistics\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBstatic\fP uint32_t CodingStatisticsClassType::GetSubClassHeight (const uint32_t subClass)\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line \fB277\fP of file \fBCodingStatistics\&.h\fP\&.
.SS "\fBstatic\fP const char * CodingStatisticsClassType::GetSubClassString (const uint32_t subClass)\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line \fB282\fP of file \fBCodingStatistics\&.h\fP\&.
.SS "\fBstatic\fP uint32_t CodingStatisticsClassType::GetSubClassWidth (const uint32_t subClass)\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line \fB272\fP of file \fBCodingStatistics\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "uint32_t CodingStatisticsClassType::subClass"

.PP
Definition at line \fB290\fP of file \fBCodingStatistics\&.h\fP\&.
.SS "\fBCodingStatisticsType\fP CodingStatisticsClassType::type"

.PP
Definition at line \fB289\fP of file \fBCodingStatistics\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
