.TH "CodingStatistics::SStat" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CodingStatistics::SStat
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CodingStatistics\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSStat\fP ()"
.br
.ti -1c
.RI "void \fBclear\fP ()"
.br
.ti -1c
.RI "\fBSStat\fP & \fBoperator+=\fP (const \fBSStat\fP &src)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int64_t \fBbits\fP"
.br
.ti -1c
.RI "int64_t \fBcount\fP"
.br
.ti -1c
.RI "int64_t \fBsum\fP"
.br
.ti -1c
.RI "int64_t \fBclassCount\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB315\fP of file \fBCodingStatistics\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CodingStatistics::SStat::SStat ()\fC [inline]\fP"

.PP
Definition at line \fB317\fP of file \fBCodingStatistics\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void CodingStatistics::SStat::clear ()\fC [inline]\fP"

.PP
Definition at line \fB324\fP of file \fBCodingStatistics\&.h\fP\&.
.SS "\fBSStat\fP & CodingStatistics::SStat::operator+= (const \fBSStat\fP & src)\fC [inline]\fP"

.PP
Definition at line \fB326\fP of file \fBCodingStatistics\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int64_t CodingStatistics::SStat::bits"

.PP
Definition at line \fB319\fP of file \fBCodingStatistics\&.h\fP\&.
.SS "int64_t CodingStatistics::SStat::classCount"

.PP
Definition at line \fB322\fP of file \fBCodingStatistics\&.h\fP\&.
.SS "int64_t CodingStatistics::SStat::count"

.PP
Definition at line \fB320\fP of file \fBCodingStatistics\&.h\fP\&.
.SS "int64_t CodingStatistics::SStat::sum"

.PP
Definition at line \fB321\fP of file \fBCodingStatistics\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
