.TH "CodingStatistics" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CodingStatistics
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CodingStatistics\&.h>\fP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCodingStatisticsData\fP"
.br
.ti -1c
.RI "struct \fBSStat\fP"
.br
.ti -1c
.RI "struct \fBStatLogValue\fP"
.br
.ti -1c
.RI "struct \fBStatTool\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB~CodingStatistics\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "\fBstatic\fP \fBCodingStatistics\fP & \fBGetSingletonInstance\fP ()"
.br
.ti -1c
.RI "\fBstatic\fP void \fBDestroyInstance\fP ()"
.br
.ti -1c
.RI "\fBstatic\fP const \fBCodingStatisticsData\fP & \fBGetStatistics\fP ()"
.br
.ti -1c
.RI "\fBstatic\fP void \fBSetStatistics\fP (const \fBCodingStatisticsData\fP &src)"
.br
.ti -1c
.RI "\fBstatic\fP \fBSStat\fP & \fBGetStatisticEP\fP (const \fBCodingStatisticsClassType\fP &stat)"
.br
.ti -1c
.RI "\fBstatic\fP \fBSStat\fP & \fBGetStatisticEP\fP (const std::string &str)"
.br
.ti -1c
.RI "\fBstatic\fP \fBSStat\fP & \fBGetStatisticEP\fP (const char *pKey)"
.br
.ti -1c
.RI "\fBstatic\fP \fBStatTool\fP & \fBGetStatisticTool\fP (const \fBCodingStatisticsClassType\fP &stat)"
.br
.ti -1c
.RI "\fBstatic\fP int \fBgetNumOnes\fP (int bins)"
.br
.ti -1c
.RI "\fBstatic\fP void \fBIncrementStatisticEP\fP (const \fBCodingStatisticsClassType\fP &stat, const int numBits, const int value)"
.br
.ti -1c
.RI "\fBstatic\fP void \fBIncrementStatisticEP\fP (const std::string &str, const int numBits, const int value)"
.br
.ti -1c
.RI "\fBstatic\fP void \fBIncrementStatisticEP\fP (const char *pKey, const int numBits, const int value)"
.br
.ti -1c
.RI "\fBstatic\fP void \fBIncrementStatisticTool\fP (const \fBCodingStatisticsClassType\fP &stat)"
.br
.ti -1c
.RI "\fBstatic\fP void \fBUpdateCABACStat\fP (const \fBCodingStatisticsClassType\fP &stat, uint32_t uiRangeBefore, uint32_t uiRangeAfter, int val)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBm_mode\fP"
.br
.ti -1c
.RI "\fBStatLogValue\fP \fBvalues\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB295\fP of file \fBCodingStatistics\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CodingStatistics::~CodingStatistics ()\fC [inline]\fP"

.PP
Definition at line \fB762\fP of file \fBCodingStatistics\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBstatic\fP void CodingStatistics::DestroyInstance ()\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line \fB786\fP of file \fBCodingStatistics\&.h\fP\&.
.SS "\fBstatic\fP int CodingStatistics::getNumOnes (int bins)\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line \fB808\fP of file \fBCodingStatistics\&.h\fP\&.
.SS "\fBstatic\fP \fBCodingStatistics\fP & CodingStatistics::GetSingletonInstance ()\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line \fB775\fP of file \fBCodingStatistics\&.h\fP\&.
.SS "\fBstatic\fP \fBSStat\fP & CodingStatistics::GetStatisticEP (const char * pKey)\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line \fB800\fP of file \fBCodingStatistics\&.h\fP\&.
.SS "\fBstatic\fP \fBSStat\fP & CodingStatistics::GetStatisticEP (const \fBCodingStatisticsClassType\fP & stat)\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line \fB796\fP of file \fBCodingStatistics\&.h\fP\&.
.SS "\fBstatic\fP \fBSStat\fP & CodingStatistics::GetStatisticEP (const std::string & str)\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line \fB798\fP of file \fBCodingStatistics\&.h\fP\&.
.SS "\fBstatic\fP const \fBCodingStatisticsData\fP & CodingStatistics::GetStatistics ()\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line \fB792\fP of file \fBCodingStatistics\&.h\fP\&.
.SS "\fBstatic\fP \fBStatTool\fP & CodingStatistics::GetStatisticTool (const \fBCodingStatisticsClassType\fP & stat)\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line \fB802\fP of file \fBCodingStatistics\&.h\fP\&.
.SS "\fBstatic\fP void CodingStatistics::IncrementStatisticEP (const char * pKey, const int numBits, const int value)\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line \fB846\fP of file \fBCodingStatistics\&.h\fP\&.
.SS "\fBstatic\fP void CodingStatistics::IncrementStatisticEP (const \fBCodingStatisticsClassType\fP & stat, const int numBits, const int value)\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line \fB821\fP of file \fBCodingStatistics\&.h\fP\&.
.SS "\fBstatic\fP void CodingStatistics::IncrementStatisticEP (const std::string & str, const int numBits, const int value)\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line \fB834\fP of file \fBCodingStatistics\&.h\fP\&.
.SS "\fBstatic\fP void CodingStatistics::IncrementStatisticTool (const \fBCodingStatisticsClassType\fP & stat)\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line \fB858\fP of file \fBCodingStatistics\&.h\fP\&.
.SS "\fBstatic\fP void CodingStatistics::SetStatistics (const \fBCodingStatisticsData\fP & src)\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line \fB794\fP of file \fBCodingStatistics\&.h\fP\&.
.SS "\fBstatic\fP void CodingStatistics::UpdateCABACStat (const \fBCodingStatisticsClassType\fP & stat, uint32_t uiRangeBefore, uint32_t uiRangeAfter, int val)\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line \fB872\fP of file \fBCodingStatistics\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int CodingStatistics::m_mode"

.PP
Definition at line \fB398\fP of file \fBCodingStatistics\&.h\fP\&.
.SS "\fBStatLogValue\fP CodingStatistics::values"

.PP
Definition at line \fB870\fP of file \fBCodingStatistics\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
