.TH "coeffGroupRDStats" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
coeffGroupRDStats
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBiNNZbeforePos0\fP"
.br
.ti -1c
.RI "double \fBd64CodedLevelandDist\fP"
.br
.ti -1c
.RI "double \fBd64UncodedDist\fP"
.br
.ti -1c
.RI "double \fBd64SigCost\fP"
.br
.ti -1c
.RI "double \fBd64SigCost_0\fP"
.br
.ti -1c
.RI "int \fBiNumSbbCtxBins\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB52\fP of file \fBQuantRDOQ\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "double coeffGroupRDStats::d64CodedLevelandDist"

.PP
Definition at line \fB55\fP of file \fBQuantRDOQ\&.cpp\fP\&.
.SS "double coeffGroupRDStats::d64SigCost"

.PP
Definition at line \fB57\fP of file \fBQuantRDOQ\&.cpp\fP\&.
.SS "double coeffGroupRDStats::d64SigCost_0"

.PP
Definition at line \fB58\fP of file \fBQuantRDOQ\&.cpp\fP\&.
.SS "double coeffGroupRDStats::d64UncodedDist"

.PP
Definition at line \fB56\fP of file \fBQuantRDOQ\&.cpp\fP\&.
.SS "int coeffGroupRDStats::iNNZbeforePos0"

.PP
Definition at line \fB54\fP of file \fBQuantRDOQ\&.cpp\fP\&.
.SS "int coeffGroupRDStats::iNumSbbCtxBins"

.PP
Definition at line \fB59\fP of file \fBQuantRDOQ\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
