.TH "deps/base_vvc/minimum_VTM/source/Lib/CommonLib/CommonDef.h" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deps/base_vvc/minimum_VTM/source/Lib/CommonLib/CommonDef.h \- Defines version information, constants and small in-line functions\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <algorithm>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <iomanip>\fP
.br
\fC#include <limits>\fP
.br
\fC#include 'TypeDef\&.h'\fP
.br
\fC#include 'version\&.h'\fP
.br
\fC#include <stdarg\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBvtm::ClpRng\fP"
.br
.ti -1c
.RI "struct \fBvtm::ClpRngs\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBvtm\fP"
.br
.ti -1c
.RI "namespace \fBvtm::detail\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename T > T * \fBvtm::detail::aligned_malloc\fP (size_t len, size_t alignement)"
.br
.in -1c
.in +1c
.ti -1c
.RI "#define \fBNVM_COMPILEDBY\fP   '[Unk\-CXX]'"
.br
.ti -1c
.RI "#define \fBNVM_ONOS\fP   '[Unk\-OS]'"
.br
.ti -1c
.RI "#define \fBNVM_BITS\fP   '[%d bit] ', (sizeof(void*) == 8 ? 64 : 32)"
.br
.RI "used for checking 64-bit O/S "
.ti -1c
.RI "#define \fBNULL\fP   0"
.br
.ti -1c
.RI "#define \fBMAX_NUM_CC_ALF_FILTERS\fP   4"
.br
.ti -1c
.RI "#define \fBMEMORY_ALIGN_DEF_SIZE\fP   32"
.br
.ti -1c
.RI "#define \fBCACHE_MEM_ALIGN_SIZE\fP   1024"
.br
.ti -1c
.RI "#define \fBALIGNED_MALLOC\fP   1"
.br
.RI "use 32-bit aligned malloc/free "
.ti -1c
.RI "#define \fBxMalloc\fP(type,  len)   detail::aligned_malloc<type>( len, \fBMEMORY_ALIGN_DEF_SIZE\fP )"
.br
.ti -1c
.RI "#define \fBxFree\fP(ptr)   free( ptr )"
.br
.ti -1c
.RI "#define \fBALIGN_DATA\fP(nBytes,  v)   v __attribute__ ((aligned (nBytes)))"
.br
.ti -1c
.RI "#define \fBGCC_VERSION_AT_LEAST\fP(x,  y)   0"
.br
.ti -1c
.RI "#define \fBCLANG_VERSION_AT_LEAST\fP(x,  y)   0"
.br
.ti -1c
.RI "#define \fBALWAYS_INLINE\fP"
.br
.ti -1c
.RI "#define \fB_CASE\fP(\&.\&.\&.)"
.br
.ti -1c
.RI "#define \fB_BREAK\fP"
.br
.ti -1c
.RI "#define \fB_AREA_AT\fP(\&.\&.\&.)"
.br
.ti -1c
.RI "#define \fB_AREA_CONTAINS\fP(_a,  _x,  _y)"
.br
.ti -1c
.RI "#define \fB_UNIT_AREA_AT\fP(_a,  _x,  _y,  _w,  _h)"
.br
.ti -1c
.RI "#define \fBPARL_PARAM\fP(DEF)"
.br
.ti -1c
.RI "#define \fBPARL_PARAM0\fP(DEF)"
.br
.ti -1c
.RI "enum \fBvtm::EAffineModel\fP { \fBvtm::AFFINEMODEL_4PARAM\fP, \fBvtm::AFFINEMODEL_6PARAM\fP, \fBvtm::AFFINE_MODEL_NUM\fP }"
.br
.ti -1c
.RI "\fBMsgLevel\fP \fBvtm::g_verbosity\fP = \fBVERBOSE\fP"
.br
.ti -1c
.RI "template<typename T > T \fBvtm::Clip3\fP (const T minVal, const T maxVal, const T a)"
.br
.RI "general min/max clip "
.ti -1c
.RI "template<typename T > T \fBvtm::ClipBD\fP (const T x, const int bitDepth)"
.br
.ti -1c
.RI "template<typename T > T \fBvtm::ClipPel\fP (const T a, const \fBClpRng\fP &clpRng)"
.br
.RI "clip reconstruction "
.ti -1c
.RI "template<typename T > void \fBvtm::Check3\fP (T minVal, T maxVal, T a)"
.br
.RI "general min/max clip "
.ti -1c
.RI "void \fBvtm::msg\fP (\fBMsgLevel\fP level, const char *fmt,\&.\&.\&.)"
.br
.ti -1c
.RI "template<typename T > bool \fBvtm::isPowerOf2\fP (const T val)"
.br
.ti -1c
.RI "template<typename ValueType > ValueType \fBvtm::leftShift\fP (const ValueType value, const int shift)"
.br
.ti -1c
.RI "template<typename ValueType > ValueType \fBvtm::rightShift\fP (const ValueType value, const int shift)"
.br
.ti -1c
.RI "template<typename ValueType > ValueType \fBvtm::leftShift_round\fP (const ValueType value, const int shift)"
.br
.ti -1c
.RI "template<typename ValueType > ValueType \fBvtm::rightShift_round\fP (const ValueType value, const int shift)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Defines version information, constants and small in-line functions\&. 


.PP
Definition in file \fBCommonDef\&.h\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define _AREA_AT( \&.\&.\&.)"

.PP
Definition at line \fB702\fP of file \fBCommonDef\&.h\fP\&.
.SS "#define _AREA_CONTAINS(_a, _x, _y)"

.PP
Definition at line \fB703\fP of file \fBCommonDef\&.h\fP\&.
.SS "#define _BREAK"

.PP
Definition at line \fB701\fP of file \fBCommonDef\&.h\fP\&.
.SS "#define _CASE( \&.\&.\&.)"

.PP
Definition at line \fB700\fP of file \fBCommonDef\&.h\fP\&.
.SS "#define _UNIT_AREA_AT(_a, _x, _y, _w, _h)"

.PP
Definition at line \fB704\fP of file \fBCommonDef\&.h\fP\&.
.SS "#define ALIGN_DATA(nBytes, v)   v __attribute__ ((aligned (nBytes)))"

.PP
Definition at line \fB585\fP of file \fBCommonDef\&.h\fP\&.
.SS "#define ALIGNED_MALLOC   1"

.PP
use 32-bit aligned malloc/free 
.PP
Definition at line \fB546\fP of file \fBCommonDef\&.h\fP\&.
.SS "#define ALWAYS_INLINE"

.PP
Definition at line \fB607\fP of file \fBCommonDef\&.h\fP\&.
.SS "#define CACHE_MEM_ALIGN_SIZE   1024"

.PP
Definition at line \fB544\fP of file \fBCommonDef\&.h\fP\&.
.SS "#define CLANG_VERSION_AT_LEAST(x, y)   0"

.PP
Definition at line \fB599\fP of file \fBCommonDef\&.h\fP\&.
.SS "#define GCC_VERSION_AT_LEAST(x, y)   0"

.PP
Definition at line \fB593\fP of file \fBCommonDef\&.h\fP\&.
.SS "#define MAX_NUM_CC_ALF_FILTERS   4"

.PP
Definition at line \fB192\fP of file \fBCommonDef\&.h\fP\&.
.SS "#define MEMORY_ALIGN_DEF_SIZE   32"

.PP
Definition at line \fB543\fP of file \fBCommonDef\&.h\fP\&.
.SS "#define NULL   0"

.PP
Definition at line \fB115\fP of file \fBCommonDef\&.h\fP\&.
.SS "#define NVM_BITS   '[%d bit] ', (sizeof(void*) == 8 ? 64 : 32)"

.PP
used for checking 64-bit O/S 
.PP
Definition at line \fB112\fP of file \fBCommonDef\&.h\fP\&.
.SS "#define NVM_COMPILEDBY   '[Unk\-CXX]'"

.PP
Definition at line \fB97\fP of file \fBCommonDef\&.h\fP\&.
.SS "#define NVM_ONOS   '[Unk\-OS]'"

.PP
Definition at line \fB109\fP of file \fBCommonDef\&.h\fP\&.
.SS "#define PARL_PARAM(DEF)"

.PP
Definition at line \fB713\fP of file \fBCommonDef\&.h\fP\&.
.SS "#define PARL_PARAM0(DEF)"

.PP
Definition at line \fB714\fP of file \fBCommonDef\&.h\fP\&.
.SS "#define xFree(ptr)   free( ptr )"

.PP
Definition at line \fB573\fP of file \fBCommonDef\&.h\fP\&.
.SS "#define xMalloc(type, len)   detail::aligned_malloc<type>( len, \fBMEMORY_ALIGN_DEF_SIZE\fP )"

.PP
Definition at line \fB572\fP of file \fBCommonDef\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
