.TH "deps/base_vvc/minimum_VTM/source/Lib/CommonLib/Common.h" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deps/base_vvc/minimum_VTM/source/Lib/CommonLib/Common.h \- Common 2D-geometrical structures\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'CommonDef\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBvtm::Position\fP"
.br
.ti -1c
.RI "struct \fBvtm::Size\fP"
.br
.ti -1c
.RI "struct \fBvtm::Area\fP"
.br
.ti -1c
.RI "struct \fBvtm::UnitScale\fP"
.br
.ti -1c
.RI "struct \fBstd::hash< vtm::Position >\fP"
.br
.ti -1c
.RI "struct \fBstd::hash< vtm::Size >\fP"
.br
.ti -1c
.RI "class \fBvtm::SizeIndexInfo\fP"
.br
.ti -1c
.RI "class \fBvtm::SizeIndexInfoLog2\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBvtm\fP"
.br
.ti -1c
.RI "namespace \fBstd\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef int \fBvtm::PosType\fP"
.br
.ti -1c
.RI "typedef uint32_t \fBvtm::SizeType\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "size_t \fBvtm::rsAddr\fP (const \fBPosition\fP &pos, const uint32_t stride, const \fBUnitScale\fP &unitScale)"
.br
.ti -1c
.RI "size_t \fBvtm::rsAddr\fP (const \fBPosition\fP &pos, const \fBPosition\fP &origin, const uint32_t stride, const \fBUnitScale\fP &unitScale)"
.br
.ti -1c
.RI "size_t \fBvtm::rsAddr\fP (const \fBPosition\fP &pos, const uint32_t stride)"
.br
.ti -1c
.RI "size_t \fBvtm::rsAddr\fP (const \fBPosition\fP &pos, const \fBPosition\fP &origin, const uint32_t stride)"
.br
.ti -1c
.RI "\fBArea\fP \fBvtm::clipArea\fP (const \fBArea\fP &_area, const \fBArea\fP &boundingBox)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Common 2D-geometrical structures\&. 


.PP
Definition in file \fBCommon\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
