.TH "conformance" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
conformance
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBplatform_exe\fP (path, name)"
.br
.ti -1c
.RI "\fBprefix_path\fP (d, f)"
.br
.ti -1c
.RI "\fBhash\fP (filename, blocksize=65536)"
.br
.ti -1c
.RI "\fBhash_md5\fP (filename, blocksize=65536)"
.br
.ti -1c
.RI "\fBparse_vooya_filename\fP (name)"
.br
.ti -1c
.RI "\fBcreate_opl_file\fP (width, height, output)"
.br
.ti -1c
.RI "\fBcreate_txt_file\fP (width, height, output, description)"
.br
.ti -1c
.RI "\fBrun_subprocess\fP (title, \fBargs\fP, logfile, scriptfile, show_progress)"
.br
.ti -1c
.RI "\fBtest_encode_decode\fP (number, encoder, decoder, input_dir, base_dir, test, default_parameters, show_progress, decode_only, sequence, harness, validator)"
.br
.ti -1c
.RI "\fBrun_test\fP (test_job)"
.br
.ti -1c
.RI "\fBrun_tests\fP (\fBargs\fP)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "list \fBIMAGE_NAME_PARAMS\fP"
.br
.ti -1c
.RI "\fBparser\fP = argparse\&.ArgumentParser()"
.br
.ti -1c
.RI "\fBhelp\fP"
.br
.ti -1c
.RI "\fBdefault\fP"
.br
.ti -1c
.RI "\fBargs\fP = parser\&.parse_args()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "conformance\&.create_opl_file ( width,  height,  output)"

.PP
Definition at line \fB84\fP of file \fBconformance\&.py\fP\&.
.SS "conformance\&.create_txt_file ( width,  height,  output,  description)"

.PP
Definition at line \fB102\fP of file \fBconformance\&.py\fP\&.
.SS "conformance\&.hash ( filename,  blocksize = \fC65536\fP)"

.PP
.nf
    Compute hash of named file\&.
.fi
.PP
 
.PP
Definition at line \fB28\fP of file \fBconformance\&.py\fP\&.
.SS "conformance\&.hash_md5 ( filename,  blocksize = \fC65536\fP)"

.PP
.nf
    Compute md5 hash of named file\&.
.fi
.PP
 
.PP
Definition at line \fB38\fP of file \fBconformance\&.py\fP\&.
.SS "conformance\&.parse_vooya_filename ( name)"

.PP
.nf
    Extract vooya-ish image metadata from filename in form suitable for use as encoder parameters\&.
.fi
.PP
 
.PP
Definition at line \fB56\fP of file \fBconformance\&.py\fP\&.
.SS "conformance\&.platform_exe ( path,  name)"

.PP
.nf
Given a directory and an executable file name, return platform specifix path\&.
.fi
.PP
 
.PP
Definition at line \fB16\fP of file \fBconformance\&.py\fP\&.
.SS "conformance\&.prefix_path ( d,  f)"

.PP
Definition at line \fB22\fP of file \fBconformance\&.py\fP\&.
.SS "conformance\&.run_subprocess ( title,  args,  logfile,  scriptfile,  show_progress)"

.PP
.nf
Run a comamnd as a subprocess - report progress and capture output (both stderr and stdout) to a log file\&.
.fi
.PP
 
.PP
Definition at line \fB127\fP of file \fBconformance\&.py\fP\&.
.SS "conformance\&.run_test ( test_job)"

.PP
.nf
Wrapper for running a parallel test instance - unpacks arguments and forwards to real function\&.
.fi
.PP
 
.PP
Definition at line \fB409\fP of file \fBconformance\&.py\fP\&.
.SS "conformance\&.run_tests ( args)"

.PP
.nf
Read a JSON array and run test described by each entry\&.
.fi
.PP
 
.PP
Definition at line \fB415\fP of file \fBconformance\&.py\fP\&.
.SS "conformance\&.test_encode_decode ( number,  encoder,  decoder,  input_dir,  base_dir,  test,  default_parameters,  show_progress,  decode_only,  sequence,  harness,  validator)"

.PP
.nf
    Run an encode followed by decode of given file (using given params)
    Return true if recon & decoded yuv match required checksum\&.
.fi
.PP
 
.PP
Definition at line \fB171\fP of file \fBconformance\&.py\fP\&.
.SH "Variable Documentation"
.PP 
.SS "conformance\&.args = parser\&.parse_args()"

.PP
Definition at line \fB556\fP of file \fBconformance\&.py\fP\&.
.SS "conformance\&.default"

.PP
Definition at line \fB542\fP of file \fBconformance\&.py\fP\&.
.SS "conformance\&.help"

.PP
Definition at line \fB542\fP of file \fBconformance\&.py\fP\&.
.SS "list conformance\&.IMAGE_NAME_PARAMS"
\fBInitial value:\fP.PP
.nf
1 =  [
2     ("width", re\&.compile("([0\-9]+)x[0\-9]+")),
3     ("height", re\&.compile("[0\-9]+x([0\-9]+)")),
4     ("fps", re\&.compile("([0\-9]+)(fps|hz)")),
5     ("bit_depth", re\&.compile("([0\-9]+)(bits?|bpp)")),
6     ("format", re\&.compile("^(420p|422p|yuv|yuyv|y|)$"))
7 ]
.fi

.PP
Definition at line \fB48\fP of file \fBconformance\&.py\fP\&.
.SS "conformance\&.parser = argparse\&.ArgumentParser()"

.PP
Definition at line \fB541\fP of file \fBconformance\&.py\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
