.TH "stress_tests/conformance.py" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
stress_tests/conformance.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBconformance\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBconformance\&.platform_exe\fP (path, name)"
.br
.ti -1c
.RI "\fBconformance\&.prefix_path\fP (d, f)"
.br
.ti -1c
.RI "\fBconformance\&.hash\fP (filename, blocksize=65536)"
.br
.ti -1c
.RI "\fBconformance\&.hash_md5\fP (filename, blocksize=65536)"
.br
.ti -1c
.RI "\fBconformance\&.parse_vooya_filename\fP (name)"
.br
.ti -1c
.RI "\fBconformance\&.create_opl_file\fP (width, height, output)"
.br
.ti -1c
.RI "\fBconformance\&.create_txt_file\fP (width, height, output, description)"
.br
.ti -1c
.RI "\fBconformance\&.run_subprocess\fP (title, \fBargs\fP, logfile, scriptfile, show_progress)"
.br
.ti -1c
.RI "\fBconformance\&.test_encode_decode\fP (number, encoder, decoder, input_dir, base_dir, test, default_parameters, show_progress, decode_only, sequence, harness, validator)"
.br
.ti -1c
.RI "\fBconformance\&.run_test\fP (test_job)"
.br
.ti -1c
.RI "\fBconformance\&.run_tests\fP (\fBargs\fP)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "list \fBconformance\&.IMAGE_NAME_PARAMS\fP"
.br
.ti -1c
.RI "\fBconformance\&.parser\fP = argparse\&.ArgumentParser()"
.br
.ti -1c
.RI "\fBconformance\&.help\fP"
.br
.ti -1c
.RI "\fBconformance\&.default\fP"
.br
.ti -1c
.RI "\fBconformance\&.args\fP = parser\&.parse_args()"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
