.TH "src/Config.hpp" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Config.hpp
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBVERBOSE_TRACE\fP   0"
.br
.ti -1c
.RI "#define \fBVERBOSE_TRACE_PIXEL\fP   0"
.br
.ti -1c
.RI "#define \fBVERBOSE_TRACE_SURFACE\fP   0"
.br
.ti -1c
.RI "#define \fBVERBOSE_TRACE_TEMPORAL\fP   0"
.br
.ti -1c
.RI "#define \fBVERBOSE_TRACE_HUFFMAN\fP   0"
.br
.ti -1c
.RI "#define \fBBITSTREAM_DEBUG\fP   0"
.br
.ti -1c
.RI "#define \fBUSER_DATA_EXTRACTION\fP   0"
.br
.ti -1c
.RI "#define \fB__OPT_MATRIX__\fP"
.br
.ti -1c
.RI "#define \fB__OPT_INPLACE__\fP"
.br
.ti -1c
.RI "#define \fB__OPT_DIVISION__\fP"
.br
.ti -1c
.RI "#define \fB__OPT_MODULO__\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define __OPT_DIVISION__"

.PP
Definition at line \fB61\fP of file \fBConfig\&.hpp\fP\&.
.SS "#define __OPT_INPLACE__"

.PP
Definition at line \fB58\fP of file \fBConfig\&.hpp\fP\&.
.SS "#define __OPT_MATRIX__"

.PP
Definition at line \fB57\fP of file \fBConfig\&.hpp\fP\&.
.SS "#define __OPT_MODULO__"

.PP
Definition at line \fB62\fP of file \fBConfig\&.hpp\fP\&.
.SS "#define BITSTREAM_DEBUG   0"

.PP
Definition at line \fB51\fP of file \fBConfig\&.hpp\fP\&.
.SS "#define USER_DATA_EXTRACTION   0"

.PP
Definition at line \fB55\fP of file \fBConfig\&.hpp\fP\&.
.SS "#define VERBOSE_TRACE   0"

.PP
Definition at line \fB43\fP of file \fBConfig\&.hpp\fP\&.
.SS "#define VERBOSE_TRACE_HUFFMAN   0"

.PP
Definition at line \fB47\fP of file \fBConfig\&.hpp\fP\&.
.SS "#define VERBOSE_TRACE_PIXEL   0"

.PP
Definition at line \fB44\fP of file \fBConfig\&.hpp\fP\&.
.SS "#define VERBOSE_TRACE_SURFACE   0"

.PP
Definition at line \fB45\fP of file \fBConfig\&.hpp\fP\&.
.SS "#define VERBOSE_TRACE_TEMPORAL   0"

.PP
Definition at line \fB46\fP of file \fBConfig\&.hpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
