.TH "source_patch/configfile.h" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
source_patch/configfile.h \- Prototypes for configfile\&.c and definitions of used structures\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'config_common\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBDEFAULTCONFIGFILENAME\fP   'decoder\&.cfg'"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBJMDecHelpExit\fP ()"
.br
.ti -1c
.RI "void \fBParseCommand\fP (InputParameters *p_Inp, int ac, char *av[])"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "InputParameters \fBcfgparams\fP"
.br
.ti -1c
.RI "Mapping \fBMap\fP []"
.br
.in -1c
.SH "Detailed Description"
.PP 
Prototypes for configfile\&.c and definitions of used structures\&. 

\fBconfigfile\&.h\fP  
.PP
Definition in file \fBconfigfile\&.h\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define DEFAULTCONFIGFILENAME   'decoder\&.cfg'"

.PP
Definition at line \fB14\fP of file \fBconfigfile\&.h\fP\&.
.SH "Function Documentation"
.PP 
.SS "void JMDecHelpExit ()\fC [extern]\fP"

.SS "void ParseCommand (InputParameters * p_Inp, int ac, char * av[])\fC [extern]\fP"

.SH "Variable Documentation"
.PP 
.SS "InputParameters cfgparams\fC [extern]\fP"

.SS "Mapping Map[]\fC [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
