.TH "deps/base_vvc/minimum_VTM/source/Lib/CommonLib/ContextModelling.h" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deps/base_vvc/minimum_VTM/source/Lib/CommonLib/ContextModelling.h \- Classes providing probability descriptions and contexts (header)  

.SH SYNOPSIS
.br
.PP
\fC#include 'CommonDef\&.h'\fP
.br
\fC#include 'Contexts\&.h'\fP
.br
\fC#include 'Slice\&.h'\fP
.br
\fC#include 'Unit\&.h'\fP
.br
\fC#include 'UnitPartitioner\&.h'\fP
.br
\fC#include <bitset>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBvtm::CoeffCodingContext\fP"
.br
.ti -1c
.RI "class \fBvtm::CUCtx\fP"
.br
.ti -1c
.RI "class \fBvtm::MergeCtx\fP"
.br
.ti -1c
.RI "class \fBvtm::AffineMergeCtx\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBvtm\fP"
.br
.ti -1c
.RI "namespace \fBvtm::DeriveCtx\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBUPDATE\fP(x)   {TCoeff a=abs(x);sumAbs+=std::min(4+(a&1),a);numPos+=int(!!a);}"
.br
.ti -1c
.RI "#define \fBUPDATE\fP(x)   {TCoeff a=abs(x);numPos+=int(!!a);}"
.br
.ti -1c
.RI "#define \fBUPDATE\fP(x)   {TCoeff a=abs(x);numPos+=int(!!a);}"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBvtm::DeriveCtx::CtxSplit\fP (const \fBCodingStructure\fP &cs, \fBPartitioner\fP &partitioner, unsigned &ctxSpl, unsigned &ctxQt, unsigned &ctxHv, unsigned &ctxHorBt, unsigned &ctxVerBt, bool *canSplit=nullptr)"
.br
.ti -1c
.RI "unsigned \fBvtm::DeriveCtx::CtxModeConsFlag\fP (const \fBCodingStructure\fP &cs, \fBPartitioner\fP &partitioner)"
.br
.ti -1c
.RI "unsigned \fBvtm::DeriveCtx::CtxQtCbf\fP (const \fBComponentID\fP compID, const bool prevCbf=false, const int ispIdx=0)"
.br
.ti -1c
.RI "unsigned \fBvtm::DeriveCtx::CtxInterDir\fP (const \fBPredictionUnit\fP &pu)"
.br
.ti -1c
.RI "unsigned \fBvtm::DeriveCtx::CtxSkipFlag\fP (const \fBCodingUnit\fP &cu)"
.br
.ti -1c
.RI "unsigned \fBvtm::DeriveCtx::CtxAffineFlag\fP (const \fBCodingUnit\fP &cu)"
.br
.ti -1c
.RI "unsigned \fBvtm::DeriveCtx::CtxPredModeFlag\fP (const \fBCodingUnit\fP &cu)"
.br
.ti -1c
.RI "unsigned \fBvtm::DeriveCtx::CtxIBCFlag\fP (const \fBCodingUnit\fP &cu)"
.br
.ti -1c
.RI "unsigned \fBvtm::DeriveCtx::CtxMipFlag\fP (const \fBCodingUnit\fP &cu)"
.br
.ti -1c
.RI "unsigned \fBvtm::DeriveCtx::CtxPltCopyFlag\fP (const unsigned prevRunType, const unsigned dist)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Classes providing probability descriptions and contexts (header) 


.PP
Definition in file \fBContextModelling\&.h\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define UPDATE(x)   {TCoeff a=abs(x);sumAbs+=std::min(4+(a&1),a);numPos+=int(!!a);}"

.SS "#define UPDATE(x)   {TCoeff a=abs(x);numPos+=int(!!a);}"

.SS "#define UPDATE(x)   {TCoeff a=abs(x);numPos+=int(!!a);}"

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
