.TH "Context" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Context
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBTVideoIOYuvMem::Writer\fP, and \fBVideoIOYuvMem::Writer\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBflush\fP ()"
.br
.ti -1c
.RI "void \fBdecode_enhanced_frames\fP (DecodedPicList *pic, bool all_frames)"
.br
.ti -1c
.RI "\fBContext\fP ()"
.br
.ti -1c
.RI "void \fBdecode\fP ()"
.br
.ti -1c
.RI "void \fBoutput_begin\fP (bool is16bit, uint32_t width, uint32_t height)"
.br
.ti -1c
.RI "size_t \fBoutput_write\fP (const uint8_t *data, size_t size)"
.br
.ti -1c
.RI "void \fBoutput_end\fP ()"
.br
.ti -1c
.RI "void \fBflush\fP ()"
.br
.ti -1c
.RI "void \fBWriteOutput\fP (TComList< TComPic * > *pcListPic, unsigned int tId)"
.br
.ti -1c
.RI "void \fBFlushOutput\fP (TComList< TComPic * > *pcListPic)"
.br
.ti -1c
.RI "void \fBpicture_begin\fP (bool is16bit, UInt width, UInt height, ChromaFormat format) override"
.br
.ti -1c
.RI "void \fBpicture_end\fP () override"
.br
.ti -1c
.RI "int \fBwrite\fP (const uint8_t *data, size_t size) override"
.br
.ti -1c
.RI "\fBContext\fP ()"
.br
.ti -1c
.RI "void \fBdecode\fP ()"
.br
.ti -1c
.RI "void \fBpicture_begin\fP (bool is16bit, uint32_t width, uint32_t height, ChromaFormat format) override"
.br
.ti -1c
.RI "void \fBpicture_end\fP () override"
.br
.ti -1c
.RI "int \fBwrite\fP (const uint8_t *data, size_t size) override"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBconfiguration_\fP"
.br
.ti -1c
.RI "\fBState\fP \fBstate_\fP"
.br
.ti -1c
.RI "vector< uint8_t > \fBbase_bitstream_\fP"
.br
.ti -1c
.RI "int \fBframe_count_\fP = 0"
.br
.ti -1c
.RI "thread \fBdecoder_thread_\fP"
.br
.ti -1c
.RI "unsigned \fBoutput_frame_\fP = 0"
.br
.ti -1c
.RI "\fBRingBuffer\fP< shared_ptr< \fBDecodedImage\fP > > \fBdecoded_images_\fP = {2}"
.br
.ti -1c
.RI "shared_ptr< \fBDecodedImage\fP > \fBdecoded_image_\fP"
.br
.ti -1c
.RI "stringstream \fBbase_bitstream_\fP"
.br
.ti -1c
.RI "unsigned \fBoutput_bitdepth_\fP = 10"
.br
.ti -1c
.RI "shared_ptr< \fBDecodedImage\fP > \fBwriting_image_\fP"
.br
.ti -1c
.RI "int \fBframe_count\fP = 0"
.br
.ti -1c
.RI "TDecTop \fBm_cTDecTop\fP"
.br
.ti -1c
.RI "\fBTVideoIOYuvMem\fP \fBm_cTVideoIOYuvRecon\fP"
.br
.ti -1c
.RI "Int \fBm_iPOCLastDisplay\fP"
.br
.ti -1c
.RI "Int \fBm_outputBitDepth\fP [MAX_NUM_CHANNEL_TYPE]"
.br
.ti -1c
.RI "\fBDecAppMem\fP \fBm_decoder\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB60\fP of file \fBcodec_api\&.cpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Context::Context ()"

.PP
Definition at line \fB75\fP of file \fBcodec_api\&.cpp\fP\&.
.SS "Context::Context ()"

.SH "Member Function Documentation"
.PP 
.SS "void Context::decode ()"

.PP
Definition at line \fB177\fP of file \fBcodec_api\&.cpp\fP\&.
.SS "void Context::decode ()"

.SS "void Context::decode_enhanced_frames (DecodedPicList * pic, bool all_frames)"

.PP
Definition at line \fB250\fP of file \fBcodec_api\&.cpp\fP\&.
.SS "void Context::flush ()"

.PP
Definition at line \fB202\fP of file \fBcodec_api\&.cpp\fP\&.
.SS "void Context::flush ()"

.SS "void Context::FlushOutput (TComList< TComPic * > * pcListPic)"

.PP
\fBParameters\fP
.RS 4
\fIpcListPic\fP list of pictures to be written to file 
.RE
.PP

.PP
Definition at line \fB411\fP of file \fBcodec_api\&.cpp\fP\&.
.SS "void Context::output_begin (bool is16bit, uint32_t width, uint32_t height)"

.PP
Definition at line \fB189\fP of file \fBcodec_api\&.cpp\fP\&.
.SS "void Context::output_end ()"

.PP
Definition at line \fB216\fP of file \fBcodec_api\&.cpp\fP\&.
.SS "size_t Context::output_write (const uint8_t * data, size_t size)"

.PP
Definition at line \fB209\fP of file \fBcodec_api\&.cpp\fP\&.
.SS "void Context::picture_begin (bool is16bit, UInt width, UInt height, ChromaFormat format)\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBTVideoIOYuvMem::Writer\fP\&.
.PP
Definition at line \fB515\fP of file \fBcodec_api\&.cpp\fP\&.
.SS "void Context::picture_begin (bool is16bit, uint32_t width, uint32_t height, ChromaFormat format)\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBVideoIOYuvMem::Writer\fP\&.
.PP
Definition at line \fB188\fP of file \fBcodec_api\&.cpp\fP\&.
.SS "void Context::picture_end ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBTVideoIOYuvMem::Writer\fP\&.
.PP
Definition at line \fB541\fP of file \fBcodec_api\&.cpp\fP\&.
.SS "void Context::picture_end ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBTVideoIOYuvMem::Writer\fP\&.
.SS "int Context::write (const uint8_t * data, size_t size)\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBTVideoIOYuvMem::Writer\fP\&.
.PP
Definition at line \fB535\fP of file \fBcodec_api\&.cpp\fP\&.
.SS "int Context::write (const uint8_t * data, size_t size)\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBTVideoIOYuvMem::Writer\fP\&.
.SS "void Context::WriteOutput (TComList< TComPic * > * pcListPic, unsigned int tId)"

.PP
\fBParameters\fP
.RS 4
\fIpcListPic\fP list of pictures to be written to file 
.br
\fItId\fP temporal sub-layer ID 
.RE
.PP

.PP
Definition at line \fB285\fP of file \fBcodec_api\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "stringstream Context::base_bitstream_"

.PP
Definition at line \fB68\fP of file \fBcodec_api\&.cpp\fP\&.
.SS "stringstream Context::base_bitstream_"

.PP
Definition at line \fB54\fP of file \fBcodec_api\&.cpp\fP\&.
.SS "std::string Context::configuration_"

.PP
Definition at line \fB65\fP of file \fBcodec_api\&.cpp\fP\&.
.SS "shared_ptr< \fBDecodedImage\fP > Context::decoded_image_"

.PP
Definition at line \fB80\fP of file \fBcodec_api\&.cpp\fP\&.
.SS "\fBRingBuffer\fP< shared_ptr< \fBDecodedImage\fP > > Context::decoded_images_ = {2}"

.PP
Definition at line \fB77\fP of file \fBcodec_api\&.cpp\fP\&.
.SS "thread Context::decoder_thread_"

.PP
Definition at line \fB72\fP of file \fBcodec_api\&.cpp\fP\&.
.SS "int Context::frame_count = 0"

.PP
Definition at line \fB82\fP of file \fBcodec_api\&.cpp\fP\&.
.SS "int Context::frame_count_ = 0"

.PP
Definition at line \fB70\fP of file \fBcodec_api\&.cpp\fP\&.
.SS "TDecTop Context::m_cTDecTop"

.PP
Definition at line \fB87\fP of file \fBcodec_api\&.cpp\fP\&.
.SS "\fBTVideoIOYuvMem\fP Context::m_cTVideoIOYuvRecon"

.PP
Definition at line \fB88\fP of file \fBcodec_api\&.cpp\fP\&.
.SS "\fBDecAppMem\fP Context::m_decoder"

.PP
Definition at line \fB81\fP of file \fBcodec_api\&.cpp\fP\&.
.SS "Int Context::m_iPOCLastDisplay"

.PP
Definition at line \fB89\fP of file \fBcodec_api\&.cpp\fP\&.
.SS "Int Context::m_outputBitDepth[MAX_NUM_CHANNEL_TYPE]"

.PP
Definition at line \fB91\fP of file \fBcodec_api\&.cpp\fP\&.
.SS "unsigned Context::output_bitdepth_ = 10"

.PP
Definition at line \fB58\fP of file \fBcodec_api\&.cpp\fP\&.
.SS "unsigned Context::output_frame_ = 0"

.PP
Definition at line \fB74\fP of file \fBcodec_api\&.cpp\fP\&.
.SS "\fBState\fP Context::state_"

.PP
Definition at line \fB67\fP of file \fBcodec_api\&.cpp\fP\&.
.SS "shared_ptr< \fBDecodedImage\fP > Context::writing_image_"

.PP
Definition at line \fB69\fP of file \fBcodec_api\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
