.TH "deps/base_vvc/minimum_VTM/source/Lib/CommonLib/Contexts.h" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deps/base_vvc/minimum_VTM/source/Lib/CommonLib/Contexts.h \- Classes providing probability descriptions and contexts (header)  

.SH SYNOPSIS
.br
.PP
\fC#include 'CommonDef\&.h'\fP
.br
\fC#include 'Slice\&.h'\fP
.br
\fC#include <vector>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBvtm::BinFracBits\fP"
.br
.ti -1c
.RI "class \fBvtm::ProbModelTables\fP"
.br
.ti -1c
.RI "class \fBvtm::BinProbModelBase\fP"
.br
.ti -1c
.RI "class \fBvtm::BinProbModel_Std\fP"
.br
.ti -1c
.RI "class \fBvtm::CtxSet\fP"
.br
.ti -1c
.RI "class \fBvtm::ContextSetCfg\fP"
.br
.ti -1c
.RI "class \fBvtm::FracBitsAccess\fP"
.br
.ti -1c
.RI "class \fBvtm::CtxStore< BinProbModel >\fP"
.br
.ti -1c
.RI "class \fBvtm::SubCtx\fP"
.br
.ti -1c
.RI "class \fBvtm::Ctx\fP"
.br
.ti -1c
.RI "class \fBvtm::TempCtx\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBvtm\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBdynamic_cache\fP< \fBCtx\fP > \fBvtm::CtxCache\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBvtm::BPMType\fP { \fBvtm::BPM_Undefined\fP = 0, \fBvtm::BPM_Std\fP, \fBvtm::BPM_NUM\fP }"
.br
.in -1c
.SH "Detailed Description"
.PP 
Classes providing probability descriptions and contexts (header) 


.PP
Definition in file \fBContexts\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
