.TH "deps/base_vvc/minimum_VTM/source/Lib/CommonLib/Contexts.cpp" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deps/base_vvc/minimum_VTM/source/Lib/CommonLib/Contexts.cpp \- Classes providing probability descriptions and contexts (also contains context initialization values)  

.SH SYNOPSIS
.br
.PP
\fC#include 'Contexts\&.h'\fP
.br
\fC#include <algorithm>\fP
.br
\fC#include <cstring>\fP
.br
\fC#include <limits>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBvtm\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCNU\fP   35"
.br
.in -1c
.SH "Detailed Description"
.PP 
Classes providing probability descriptions and contexts (also contains context initialization values) 


.PP
Definition in file \fBContexts\&.cpp\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define CNU   35"

.PP
Definition at line \fB185\fP of file \fBContexts\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
