.TH "decoder/src/Convert.cpp" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
decoder/src/Convert.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'Convert\&.hpp'\fP
.br
\fC#include 'Config\&.hpp'\fP
.br
\fC#include 'Misc\&.hpp'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBlctm\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
