.TH "cxxopts::KeyValue" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cxxopts::KeyValue
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cxxopts\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBKeyValue\fP (std::string key_, std::string value_)"
.br
.ti -1c
.RI "const std::string & \fBkey\fP () const"
.br
.ti -1c
.RI "const std::string \fBvalue\fP () const"
.br
.ti -1c
.RI "template<typename T > T \fBas\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB615\fP of file \fBcxxopts\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "cxxopts::KeyValue::KeyValue (std::string key_, std::string value_)\fC [inline]\fP"

.PP
Definition at line \fB617\fP of file \fBcxxopts\&.hpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "template<typename T > T cxxopts::KeyValue::as () const\fC [inline]\fP"

.PP
Definition at line \fB623\fP of file \fBcxxopts\&.hpp\fP\&.
.SS "const std::string & cxxopts::KeyValue::key () const\fC [inline]\fP"

.PP
Definition at line \fB619\fP of file \fBcxxopts\&.hpp\fP\&.
.SS "const std::string cxxopts::KeyValue::value () const\fC [inline]\fP"

.PP
Definition at line \fB621\fP of file \fBcxxopts\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
