.TH "cxxopts::values" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cxxopts::values
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBdetail\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBabstract_value\fP"
.br
.ti -1c
.RI "class \fBstandard_value\fP"
.br
.ti -1c
.RI "class \fBstandard_value< bool >\fP"
.br
.ti -1c
.RI "struct \fBtype_is_container\fP"
.br
.ti -1c
.RI "struct \fBtype_is_container< std::vector< T > >\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename R , typename T > R \fBchecked_negate\fP (T &&t, const std::string &, std::true_type)"
.br
.ti -1c
.RI "template<typename R , typename T > T \fBchecked_negate\fP (T &&, const std::string &text, std::false_type)"
.br
.ti -1c
.RI "template<typename T > void \fBinteger_parser\fP (const std::string &text, T &\fBvalue\fP)"
.br
.ti -1c
.RI "template<typename T > void \fBstringstream_parser\fP (const std::string &text, T &\fBvalue\fP)"
.br
.ti -1c
.RI "void \fBparse_value\fP (const std::string &text, uint8_t &\fBvalue\fP)"
.br
.ti -1c
.RI "void \fBparse_value\fP (const std::string &text, int8_t &\fBvalue\fP)"
.br
.ti -1c
.RI "void \fBparse_value\fP (const std::string &text, uint16_t &\fBvalue\fP)"
.br
.ti -1c
.RI "void \fBparse_value\fP (const std::string &text, int16_t &\fBvalue\fP)"
.br
.ti -1c
.RI "void \fBparse_value\fP (const std::string &text, uint32_t &\fBvalue\fP)"
.br
.ti -1c
.RI "void \fBparse_value\fP (const std::string &text, int32_t &\fBvalue\fP)"
.br
.ti -1c
.RI "void \fBparse_value\fP (const std::string &text, uint64_t &\fBvalue\fP)"
.br
.ti -1c
.RI "void \fBparse_value\fP (const std::string &text, int64_t &\fBvalue\fP)"
.br
.ti -1c
.RI "void \fBparse_value\fP (const std::string &text, bool &\fBvalue\fP)"
.br
.ti -1c
.RI "void \fBparse_value\fP (const std::string &text, std::string &\fBvalue\fP)"
.br
.ti -1c
.RI "template<typename T > void \fBparse_value\fP (const std::string &text, T &\fBvalue\fP)"
.br
.ti -1c
.RI "template<typename T > void \fBparse_value\fP (const std::string &text, std::vector< T > &\fBvalue\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "template<typename R , typename T > T cxxopts::values::checked_negate (T &&, const std::string & text, std::false_type)"

.PP
Definition at line \fB307\fP of file \fBcxxopts\&.hpp\fP\&.
.SS "template<typename R , typename T > R cxxopts::values::checked_negate (T && t, const std::string &, std::true_type)"

.PP
Definition at line \fB300\fP of file \fBcxxopts\&.hpp\fP\&.
.SS "template<typename T > void cxxopts::values::integer_parser (const std::string & text, T & value)"

.PP
Definition at line \fB311\fP of file \fBcxxopts\&.hpp\fP\&.
.SS "void cxxopts::values::parse_value (const std::string & text, bool & value)\fC [inline]\fP"

.PP
Definition at line \fB388\fP of file \fBcxxopts\&.hpp\fP\&.
.SS "void cxxopts::values::parse_value (const std::string & text, int16_t & value)\fC [inline]\fP"

.PP
Definition at line \fB378\fP of file \fBcxxopts\&.hpp\fP\&.
.SS "void cxxopts::values::parse_value (const std::string & text, int32_t & value)\fC [inline]\fP"

.PP
Definition at line \fB382\fP of file \fBcxxopts\&.hpp\fP\&.
.SS "void cxxopts::values::parse_value (const std::string & text, int64_t & value)\fC [inline]\fP"

.PP
Definition at line \fB386\fP of file \fBcxxopts\&.hpp\fP\&.
.SS "void cxxopts::values::parse_value (const std::string & text, int8_t & value)\fC [inline]\fP"

.PP
Definition at line \fB374\fP of file \fBcxxopts\&.hpp\fP\&.
.SS "void cxxopts::values::parse_value (const std::string & text, std::string & value)\fC [inline]\fP"

.PP
Definition at line \fB406\fP of file \fBcxxopts\&.hpp\fP\&.
.SS "template<typename T > void cxxopts::values::parse_value (const std::string & text, std::vector< T > & value)"

.PP
Definition at line \fB413\fP of file \fBcxxopts\&.hpp\fP\&.
.SS "template<typename T > void cxxopts::values::parse_value (const std::string & text, T & value)"

.PP
Definition at line \fB411\fP of file \fBcxxopts\&.hpp\fP\&.
.SS "void cxxopts::values::parse_value (const std::string & text, uint16_t & value)\fC [inline]\fP"

.PP
Definition at line \fB376\fP of file \fBcxxopts\&.hpp\fP\&.
.SS "void cxxopts::values::parse_value (const std::string & text, uint32_t & value)\fC [inline]\fP"

.PP
Definition at line \fB380\fP of file \fBcxxopts\&.hpp\fP\&.
.SS "void cxxopts::values::parse_value (const std::string & text, uint64_t & value)\fC [inline]\fP"

.PP
Definition at line \fB384\fP of file \fBcxxopts\&.hpp\fP\&.
.SS "void cxxopts::values::parse_value (const std::string & text, uint8_t & value)\fC [inline]\fP"

.PP
Definition at line \fB372\fP of file \fBcxxopts\&.hpp\fP\&.
.SS "template<typename T > void cxxopts::values::stringstream_parser (const std::string & text, T & value)"

.PP
Definition at line \fB364\fP of file \fBcxxopts\&.hpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
