.TH "cxxopts::ParseResult" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cxxopts::ParseResult
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cxxopts\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBParseResult\fP (const std::unordered_map< std::string, std::shared_ptr< \fBOptionDetails\fP > > &, std::vector< std::string >, bool allow_unrecognised, int &, char **&)"
.br
.ti -1c
.RI "size_t \fBcount\fP (const std::string &o) const"
.br
.ti -1c
.RI "const \fBOptionValue\fP & \fBoperator[]\fP (const std::string &option) const"
.br
.ti -1c
.RI "const std::vector< \fBKeyValue\fP > & \fBarguments\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB634\fP of file \fBcxxopts\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "cxxopts::ParseResult::ParseResult (const std::unordered_map< std::string, std::shared_ptr< \fBOptionDetails\fP > > & options, std::vector< std::string > positional, bool allow_unrecognised, int & argc, char **& argv)\fC [inline]\fP"

.PP
Definition at line \fB859\fP of file \fBcxxopts\&.hpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "const std::vector< \fBKeyValue\fP > & cxxopts::ParseResult::arguments () const\fC [inline]\fP"

.PP
Definition at line \fB662\fP of file \fBcxxopts\&.hpp\fP\&.
.SS "size_t cxxopts::ParseResult::count (const std::string & o) const\fC [inline]\fP"

.PP
Definition at line \fB639\fP of file \fBcxxopts\&.hpp\fP\&.
.SS "const \fBOptionValue\fP & cxxopts::ParseResult::operator[] (const std::string & option) const\fC [inline]\fP"

.PP
Definition at line \fB650\fP of file \fBcxxopts\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
