.TH "cxxopts::OptionAdder" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cxxopts::OptionAdder
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cxxopts\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOptionAdder\fP (\fBOptions\fP &options, std::string group)"
.br
.ti -1c
.RI "\fBOptionAdder\fP & \fBoperator()\fP (const std::string &opts, const std::string &desc, std::shared_ptr< const \fBValue\fP > \fBvalue\fP=\fB::cxxopts::value\fP< bool >(), std::string arg_help='')"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB762\fP of file \fBcxxopts\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "cxxopts::OptionAdder::OptionAdder (\fBOptions\fP & options, std::string group)\fC [inline]\fP"

.PP
Definition at line \fB764\fP of file \fBcxxopts\&.hpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBOptionAdder\fP & cxxopts::OptionAdder::operator() (const std::string & opts, const std::string & desc, std::shared_ptr< const \fBValue\fP > value = \fC\fB::cxxopts::value\fP<bool>()\fP, std::string arg_help = \fC''\fP)\fC [inline]\fP"

.PP
Definition at line \fB868\fP of file \fBcxxopts\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
