.TH "cxxopts::OptionException" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cxxopts::OptionException
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cxxopts\&.hpp>\fP
.PP
Inherits std::exception\&.
.PP
Inherited by \fBcxxopts::OptionParseException\fP, and \fBcxxopts::OptionSpecException\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOptionException\fP (const std::string &message)"
.br
.ti -1c
.RI "virtual const char * \fBwhat\fP () const noexcept"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB192\fP of file \fBcxxopts\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "cxxopts::OptionException::OptionException (const std::string & message)\fC [inline]\fP"

.PP
Definition at line \fB194\fP of file \fBcxxopts\&.hpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual const char * cxxopts::OptionException::what () const\fC [inline]\fP, \fC [virtual]\fP, \fC [noexcept]\fP"

.PP
Definition at line \fB196\fP of file \fBcxxopts\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
