.TH "cxxopts" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cxxopts
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBvalues\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBargument_incorrect_type\fP"
.br
.ti -1c
.RI "struct \fBHelpGroupDetails\fP"
.br
.ti -1c
.RI "struct \fBHelpOptionDetails\fP"
.br
.ti -1c
.RI "class \fBinvalid_option_format_error\fP"
.br
.ti -1c
.RI "class \fBKeyValue\fP"
.br
.ti -1c
.RI "class \fBmissing_argument_exception\fP"
.br
.ti -1c
.RI "class \fBoption_exists_error\fP"
.br
.ti -1c
.RI "class \fBoption_not_exists_exception\fP"
.br
.ti -1c
.RI "class \fBoption_not_has_argument_exception\fP"
.br
.ti -1c
.RI "class \fBoption_not_present_exception\fP"
.br
.ti -1c
.RI "class \fBoption_required_exception\fP"
.br
.ti -1c
.RI "class \fBoption_requires_argument_exception\fP"
.br
.ti -1c
.RI "class \fBOptionAdder\fP"
.br
.ti -1c
.RI "class \fBOptionDetails\fP"
.br
.ti -1c
.RI "class \fBOptionException\fP"
.br
.ti -1c
.RI "class \fBOptionParseException\fP"
.br
.ti -1c
.RI "class \fBOptions\fP"
.br
.ti -1c
.RI "class \fBOptionSpecException\fP"
.br
.ti -1c
.RI "class \fBOptionValue\fP"
.br
.ti -1c
.RI "class \fBParseResult\fP"
.br
.ti -1c
.RI "class \fBValue\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef std::string \fBString\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename T > T \fBtoLocalString\fP (T &&t)"
.br
.ti -1c
.RI "size_t \fBstringLength\fP (const \fBString\fP &s)"
.br
.ti -1c
.RI "\fBString\fP & \fBstringAppend\fP (\fBString\fP &s, \fBString\fP a)"
.br
.ti -1c
.RI "\fBString\fP & \fBstringAppend\fP (\fBString\fP &s, size_t n, char c)"
.br
.ti -1c
.RI "template<typename Iterator > \fBString\fP & \fBstringAppend\fP (\fBString\fP &s, Iterator begin, Iterator end)"
.br
.ti -1c
.RI "template<typename T > std::string \fBtoUTF8String\fP (T &&t)"
.br
.ti -1c
.RI "bool \fBempty\fP (const std::string &s)"
.br
.ti -1c
.RI "template<typename T > std::shared_ptr< \fBValue\fP > \fBvalue\fP ()"
.br
.ti -1c
.RI "template<typename T > std::shared_ptr< \fBValue\fP > \fBvalue\fP (T &t)"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef std::string \fBcxxopts::String\fP"

.PP
Definition at line \fB134\fP of file \fBcxxopts\&.hpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "bool cxxopts::empty (const std::string & s)\fC [inline]\fP"

.PP
Definition at line \fB148\fP of file \fBcxxopts\&.hpp\fP\&.
.SS "template<typename Iterator > \fBString\fP & cxxopts::stringAppend (\fBString\fP & s, Iterator begin, Iterator end)"

.PP
Definition at line \fB144\fP of file \fBcxxopts\&.hpp\fP\&.
.SS "\fBString\fP & cxxopts::stringAppend (\fBString\fP & s, size_t n, char c)\fC [inline]\fP"

.PP
Definition at line \fB142\fP of file \fBcxxopts\&.hpp\fP\&.
.SS "\fBString\fP & cxxopts::stringAppend (\fBString\fP & s, \fBString\fP a)\fC [inline]\fP"

.PP
Definition at line \fB140\fP of file \fBcxxopts\&.hpp\fP\&.
.SS "size_t cxxopts::stringLength (const \fBString\fP & s)\fC [inline]\fP"

.PP
Definition at line \fB138\fP of file \fBcxxopts\&.hpp\fP\&.
.SS "template<typename T > T cxxopts::toLocalString (T && t)"

.PP
Definition at line \fB136\fP of file \fBcxxopts\&.hpp\fP\&.
.SS "template<typename T > std::string cxxopts::toUTF8String (T && t)"

.PP
Definition at line \fB146\fP of file \fBcxxopts\&.hpp\fP\&.
.SS "template<typename T > std::shared_ptr< \fBValue\fP > cxxopts::value ()"

.PP
Definition at line \fB529\fP of file \fBcxxopts\&.hpp\fP\&.
.SS "template<typename T > std::shared_ptr< \fBValue\fP > cxxopts::value (T & t)"

.PP
Definition at line \fB531\fP of file \fBcxxopts\&.hpp\fP\&.
.SH "Variable Documentation"
.PP 
.SS "uint8_t cxxopts::major"

.PP
Definition at line \fB53\fP of file \fBcxxopts\&.hpp\fP\&.
.SS "uint8_t cxxopts::minor"

.PP
Definition at line \fB53\fP of file \fBcxxopts\&.hpp\fP\&.
.SS "uint8_t cxxopts::patch"

.PP
Definition at line \fB53\fP of file \fBcxxopts\&.hpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
