.TH "cxxopts::Value" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cxxopts::Value
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cxxopts\&.hpp>\fP
.PP
Inherits std::enable_shared_from_this< Value >\&.
.PP
Inherited by \fBcxxopts::values::abstract_value< bool >\fP, and \fBcxxopts::values::abstract_value< T >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~Value\fP ()=default"
.br
.ti -1c
.RI "virtual std::shared_ptr< \fBValue\fP > \fBclone\fP () const =0"
.br
.ti -1c
.RI "virtual void \fBparse\fP (const std::string &text) const =0"
.br
.ti -1c
.RI "virtual void \fBparse\fP () const =0"
.br
.ti -1c
.RI "virtual bool \fBhas_default\fP () const =0"
.br
.ti -1c
.RI "virtual bool \fBis_container\fP () const =0"
.br
.ti -1c
.RI "virtual bool \fBhas_implicit\fP () const =0"
.br
.ti -1c
.RI "virtual std::string \fBget_default_value\fP () const =0"
.br
.ti -1c
.RI "virtual std::string \fBget_implicit_value\fP () const =0"
.br
.ti -1c
.RI "virtual std::shared_ptr< \fBValue\fP > \fBdefault_value\fP (const std::string &\fBvalue\fP)=0"
.br
.ti -1c
.RI "virtual std::shared_ptr< \fBValue\fP > \fBimplicit_value\fP (const std::string &\fBvalue\fP)=0"
.br
.ti -1c
.RI "virtual bool \fBis_boolean\fP () const =0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB165\fP of file \fBcxxopts\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "virtual cxxopts::Value::~Value ()\fC [virtual]\fP, \fC [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "virtual std::shared_ptr< \fBValue\fP > cxxopts::Value::clone () const\fC [pure virtual]\fP"

.PP
Implemented in \fBcxxopts::values::standard_value< T >\fP, and \fBcxxopts::values::standard_value< bool >\fP\&.
.SS "virtual std::shared_ptr< \fBValue\fP > cxxopts::Value::default_value (const std::string & value)\fC [pure virtual]\fP"

.PP
Implemented in \fBcxxopts::values::abstract_value< T >\fP, and \fBcxxopts::values::abstract_value< bool >\fP\&.
.SS "virtual std::string cxxopts::Value::get_default_value () const\fC [pure virtual]\fP"

.PP
Implemented in \fBcxxopts::values::abstract_value< T >\fP, and \fBcxxopts::values::abstract_value< bool >\fP\&.
.SS "virtual std::string cxxopts::Value::get_implicit_value () const\fC [pure virtual]\fP"

.PP
Implemented in \fBcxxopts::values::abstract_value< T >\fP, and \fBcxxopts::values::abstract_value< bool >\fP\&.
.SS "virtual bool cxxopts::Value::has_default () const\fC [pure virtual]\fP"

.PP
Implemented in \fBcxxopts::values::abstract_value< T >\fP, and \fBcxxopts::values::abstract_value< bool >\fP\&.
.SS "virtual bool cxxopts::Value::has_implicit () const\fC [pure virtual]\fP"

.PP
Implemented in \fBcxxopts::values::abstract_value< T >\fP, and \fBcxxopts::values::abstract_value< bool >\fP\&.
.SS "virtual std::shared_ptr< \fBValue\fP > cxxopts::Value::implicit_value (const std::string & value)\fC [pure virtual]\fP"

.PP
Implemented in \fBcxxopts::values::abstract_value< T >\fP, and \fBcxxopts::values::abstract_value< bool >\fP\&.
.SS "virtual bool cxxopts::Value::is_boolean () const\fC [pure virtual]\fP"

.PP
Implemented in \fBcxxopts::values::abstract_value< T >\fP, and \fBcxxopts::values::abstract_value< bool >\fP\&.
.SS "virtual bool cxxopts::Value::is_container () const\fC [pure virtual]\fP"

.PP
Implemented in \fBcxxopts::values::abstract_value< T >\fP, and \fBcxxopts::values::abstract_value< bool >\fP\&.
.SS "virtual void cxxopts::Value::parse () const\fC [pure virtual]\fP"

.PP
Implemented in \fBcxxopts::values::abstract_value< T >\fP, and \fBcxxopts::values::abstract_value< bool >\fP\&.
.SS "virtual void cxxopts::Value::parse (const std::string & text) const\fC [pure virtual]\fP"

.PP
Implemented in \fBcxxopts::values::abstract_value< T >\fP, and \fBcxxopts::values::abstract_value< bool >\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
