.TH "cxxopts::values::type_is_container< T >" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cxxopts::values::type_is_container< T >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cxxopts\&.hpp>\fP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "\fBstatic\fP constexpr bool \fBvalue\fP = false"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T>
.br
struct cxxopts::values::type_is_container< T >"
.PP
Definition at line \fB427\fP of file \fBcxxopts\&.hpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "template<typename T > constexpr bool \fBcxxopts::values::type_is_container\fP< T >::value = false\fC [static]\fP, \fC [constexpr]\fP"

.PP
Definition at line \fB427\fP of file \fBcxxopts\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
