.TH "deps/cxxopts/include/cxxopts.hpp" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deps/cxxopts/include/cxxopts.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <cctype>\fP
.br
\fC#include <cstring>\fP
.br
\fC#include <exception>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <map>\fP
.br
\fC#include <memory>\fP
.br
\fC#include <regex>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <string>\fP
.br
\fC#include <unordered_map>\fP
.br
\fC#include <unordered_set>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <limits>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBcxxopts::Value\fP"
.br
.ti -1c
.RI "class \fBcxxopts::OptionException\fP"
.br
.ti -1c
.RI "class \fBcxxopts::OptionSpecException\fP"
.br
.ti -1c
.RI "class \fBcxxopts::OptionParseException\fP"
.br
.ti -1c
.RI "class \fBcxxopts::option_exists_error\fP"
.br
.ti -1c
.RI "class \fBcxxopts::invalid_option_format_error\fP"
.br
.ti -1c
.RI "class \fBcxxopts::option_not_exists_exception\fP"
.br
.ti -1c
.RI "class \fBcxxopts::missing_argument_exception\fP"
.br
.ti -1c
.RI "class \fBcxxopts::option_requires_argument_exception\fP"
.br
.ti -1c
.RI "class \fBcxxopts::option_not_has_argument_exception\fP"
.br
.ti -1c
.RI "class \fBcxxopts::option_not_present_exception\fP"
.br
.ti -1c
.RI "class \fBcxxopts::argument_incorrect_type\fP"
.br
.ti -1c
.RI "class \fBcxxopts::option_required_exception\fP"
.br
.ti -1c
.RI "struct \fBcxxopts::values::detail::SignedCheck< T, true >\fP"
.br
.ti -1c
.RI "struct \fBcxxopts::values::detail::SignedCheck< T, false >\fP"
.br
.ti -1c
.RI "struct \fBcxxopts::values::type_is_container< T >\fP"
.br
.ti -1c
.RI "struct \fBcxxopts::values::type_is_container< std::vector< T > >\fP"
.br
.ti -1c
.RI "class \fBcxxopts::values::abstract_value< T >\fP"
.br
.ti -1c
.RI "class \fBcxxopts::values::standard_value< T >\fP"
.br
.ti -1c
.RI "class \fBcxxopts::values::standard_value< bool >\fP"
.br
.ti -1c
.RI "class \fBcxxopts::OptionDetails\fP"
.br
.ti -1c
.RI "struct \fBcxxopts::HelpOptionDetails\fP"
.br
.ti -1c
.RI "struct \fBcxxopts::HelpGroupDetails\fP"
.br
.ti -1c
.RI "class \fBcxxopts::OptionValue\fP"
.br
.ti -1c
.RI "class \fBcxxopts::KeyValue\fP"
.br
.ti -1c
.RI "class \fBcxxopts::ParseResult\fP"
.br
.ti -1c
.RI "class \fBcxxopts::Options\fP"
.br
.ti -1c
.RI "class \fBcxxopts::OptionAdder\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBcxxopts\fP"
.br
.ti -1c
.RI "namespace \fBcxxopts::values\fP"
.br
.ti -1c
.RI "namespace \fBcxxopts::values::detail\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCXXOPTS__VERSION_MAJOR\fP   2"
.br
.ti -1c
.RI "#define \fBCXXOPTS__VERSION_MINOR\fP   2"
.br
.ti -1c
.RI "#define \fBCXXOPTS__VERSION_PATCH\fP   0"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef std::string \fBcxxopts::String\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename T > T \fBcxxopts::toLocalString\fP (T &&t)"
.br
.ti -1c
.RI "size_t \fBcxxopts::stringLength\fP (const \fBString\fP &s)"
.br
.ti -1c
.RI "\fBString\fP & \fBcxxopts::stringAppend\fP (\fBString\fP &s, \fBString\fP a)"
.br
.ti -1c
.RI "\fBString\fP & \fBcxxopts::stringAppend\fP (\fBString\fP &s, size_t n, char c)"
.br
.ti -1c
.RI "template<typename Iterator > \fBString\fP & \fBcxxopts::stringAppend\fP (\fBString\fP &s, Iterator begin, Iterator end)"
.br
.ti -1c
.RI "template<typename T > std::string \fBcxxopts::toUTF8String\fP (T &&t)"
.br
.ti -1c
.RI "bool \fBcxxopts::empty\fP (const std::string &s)"
.br
.ti -1c
.RI "template<typename T , typename U > void \fBcxxopts::values::detail::check_signed_range\fP (bool negative, U \fBvalue\fP, const std::string &text)"
.br
.ti -1c
.RI "template<typename R , typename T > R \fBcxxopts::values::checked_negate\fP (T &&t, const std::string &, std::true_type)"
.br
.ti -1c
.RI "template<typename R , typename T > T \fBcxxopts::values::checked_negate\fP (T &&, const std::string &text, std::false_type)"
.br
.ti -1c
.RI "template<typename T > void \fBcxxopts::values::integer_parser\fP (const std::string &text, T &\fBvalue\fP)"
.br
.ti -1c
.RI "template<typename T > void \fBcxxopts::values::stringstream_parser\fP (const std::string &text, T &\fBvalue\fP)"
.br
.ti -1c
.RI "void \fBcxxopts::values::parse_value\fP (const std::string &text, uint8_t &\fBvalue\fP)"
.br
.ti -1c
.RI "void \fBcxxopts::values::parse_value\fP (const std::string &text, int8_t &\fBvalue\fP)"
.br
.ti -1c
.RI "void \fBcxxopts::values::parse_value\fP (const std::string &text, uint16_t &\fBvalue\fP)"
.br
.ti -1c
.RI "void \fBcxxopts::values::parse_value\fP (const std::string &text, int16_t &\fBvalue\fP)"
.br
.ti -1c
.RI "void \fBcxxopts::values::parse_value\fP (const std::string &text, uint32_t &\fBvalue\fP)"
.br
.ti -1c
.RI "void \fBcxxopts::values::parse_value\fP (const std::string &text, int32_t &\fBvalue\fP)"
.br
.ti -1c
.RI "void \fBcxxopts::values::parse_value\fP (const std::string &text, uint64_t &\fBvalue\fP)"
.br
.ti -1c
.RI "void \fBcxxopts::values::parse_value\fP (const std::string &text, int64_t &\fBvalue\fP)"
.br
.ti -1c
.RI "void \fBcxxopts::values::parse_value\fP (const std::string &text, bool &\fBvalue\fP)"
.br
.ti -1c
.RI "void \fBcxxopts::values::parse_value\fP (const std::string &text, std::string &\fBvalue\fP)"
.br
.ti -1c
.RI "template<typename T > void \fBcxxopts::values::parse_value\fP (const std::string &text, T &\fBvalue\fP)"
.br
.ti -1c
.RI "template<typename T > void \fBcxxopts::values::parse_value\fP (const std::string &text, std::vector< T > &\fBvalue\fP)"
.br
.ti -1c
.RI "template<typename T > std::shared_ptr< \fBValue\fP > \fBcxxopts::value\fP ()"
.br
.ti -1c
.RI "template<typename T > std::shared_ptr< \fBValue\fP > \fBcxxopts::value\fP (T &t)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define CXXOPTS__VERSION_MAJOR   2"

.PP
Definition at line \fB47\fP of file \fBcxxopts\&.hpp\fP\&.
.SS "#define CXXOPTS__VERSION_MINOR   2"

.PP
Definition at line \fB48\fP of file \fBcxxopts\&.hpp\fP\&.
.SS "#define CXXOPTS__VERSION_PATCH   0"

.PP
Definition at line \fB49\fP of file \fBcxxopts\&.hpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
