.TH "cxxopts::argument_incorrect_type" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cxxopts::argument_incorrect_type
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cxxopts\&.hpp>\fP
.PP
Inherits \fBcxxopts::OptionParseException\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBargument_incorrect_type\fP (const std::string &arg)"
.br
.in -1c

Public Member Functions inherited from \fBcxxopts::OptionParseException\fP
.in +1c
.ti -1c
.RI "\fBOptionParseException\fP (const std::string &message)"
.br
.in -1c

Public Member Functions inherited from \fBcxxopts::OptionException\fP
.in +1c
.ti -1c
.RI "\fBOptionException\fP (const std::string &message)"
.br
.ti -1c
.RI "virtual const char * \fBwhat\fP () const noexcept"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB255\fP of file \fBcxxopts\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "cxxopts::argument_incorrect_type::argument_incorrect_type (const std::string & arg)\fC [inline]\fP"

.PP
Definition at line \fB257\fP of file \fBcxxopts\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
