.TH "cxxopts::OptionParseException" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cxxopts::OptionParseException
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cxxopts\&.hpp>\fP
.PP
Inherits \fBcxxopts::OptionException\fP\&.
.PP
Inherited by \fBcxxopts::argument_incorrect_type\fP, \fBcxxopts::missing_argument_exception\fP, \fBcxxopts::option_not_exists_exception\fP, \fBcxxopts::option_not_has_argument_exception\fP, \fBcxxopts::option_not_present_exception\fP, \fBcxxopts::option_required_exception\fP, and \fBcxxopts::option_requires_argument_exception\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOptionParseException\fP (const std::string &message)"
.br
.in -1c

Public Member Functions inherited from \fBcxxopts::OptionException\fP
.in +1c
.ti -1c
.RI "\fBOptionException\fP (const std::string &message)"
.br
.ti -1c
.RI "virtual const char * \fBwhat\fP () const noexcept"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB207\fP of file \fBcxxopts\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "cxxopts::OptionParseException::OptionParseException (const std::string & message)\fC [inline]\fP"

.PP
Definition at line \fB209\fP of file \fBcxxopts\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
