.TH "cxxopts::values::abstract_value< T >" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cxxopts::values::abstract_value< T >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cxxopts\&.hpp>\fP
.PP
Inherits \fBcxxopts::Value\fP\&.
.PP
Inherited by \fBcxxopts::values::standard_value< T >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBabstract_value\fP ()"
.br
.ti -1c
.RI "\fBabstract_value\fP (T *t)"
.br
.ti -1c
.RI "virtual \fB~abstract_value\fP ()=default"
.br
.ti -1c
.RI "\fBabstract_value\fP (const \fBabstract_value\fP &rhs)"
.br
.ti -1c
.RI "void \fBparse\fP (const std::string &text) const"
.br
.ti -1c
.RI "bool \fBis_container\fP () const"
.br
.ti -1c
.RI "void \fBparse\fP () const"
.br
.ti -1c
.RI "bool \fBhas_default\fP () const"
.br
.ti -1c
.RI "bool \fBhas_implicit\fP () const"
.br
.ti -1c
.RI "std::shared_ptr< \fBValue\fP > \fBdefault_value\fP (const std::string &\fBvalue\fP)"
.br
.ti -1c
.RI "std::shared_ptr< \fBValue\fP > \fBimplicit_value\fP (const std::string &\fBvalue\fP)"
.br
.ti -1c
.RI "std::string \fBget_default_value\fP () const"
.br
.ti -1c
.RI "std::string \fBget_implicit_value\fP () const"
.br
.ti -1c
.RI "bool \fBis_boolean\fP () const"
.br
.ti -1c
.RI "const T & \fBget\fP () const"
.br
.in -1c

Public Member Functions inherited from \fBcxxopts::Value\fP
.in +1c
.ti -1c
.RI "virtual \fB~Value\fP ()=default"
.br
.ti -1c
.RI "virtual std::shared_ptr< \fBValue\fP > \fBclone\fP () const =0"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "std::shared_ptr< T > \fBm_result\fP"
.br
.ti -1c
.RI "T * \fBm_store\fP"
.br
.ti -1c
.RI "bool \fBm_default\fP = false"
.br
.ti -1c
.RI "bool \fBm_implicit\fP = false"
.br
.ti -1c
.RI "std::string \fBm_default_value\fP"
.br
.ti -1c
.RI "std::string \fBm_implicit_value\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T>
.br
class cxxopts::values::abstract_value< T >"
.PP
Definition at line \fB431\fP of file \fBcxxopts\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename T > \fBcxxopts::values::abstract_value\fP< T >::abstract_value ()\fC [inline]\fP"

.PP
Definition at line \fB435\fP of file \fBcxxopts\&.hpp\fP\&.
.SS "template<typename T > \fBcxxopts::values::abstract_value\fP< T >::abstract_value (T * t)\fC [inline]\fP"

.PP
Definition at line \fB437\fP of file \fBcxxopts\&.hpp\fP\&.
.SS "template<typename T > virtual \fBcxxopts::values::abstract_value\fP< T >::~\fBabstract_value\fP ()\fC [virtual]\fP, \fC [default]\fP"

.SS "template<typename T > \fBcxxopts::values::abstract_value\fP< T >::abstract_value (const \fBabstract_value\fP< T > & rhs)\fC [inline]\fP"

.PP
Definition at line \fB441\fP of file \fBcxxopts\&.hpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "template<typename T > std::shared_ptr< \fBValue\fP > \fBcxxopts::values::abstract_value\fP< T >::default_value (const std::string & value)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBcxxopts::Value\fP\&.
.PP
Definition at line \fB465\fP of file \fBcxxopts\&.hpp\fP\&.
.SS "template<typename T > const T & \fBcxxopts::values::abstract_value\fP< T >::get () const\fC [inline]\fP"

.PP
Definition at line \fB483\fP of file \fBcxxopts\&.hpp\fP\&.
.SS "template<typename T > std::string \fBcxxopts::values::abstract_value\fP< T >::get_default_value () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBcxxopts::Value\fP\&.
.PP
Definition at line \fB477\fP of file \fBcxxopts\&.hpp\fP\&.
.SS "template<typename T > std::string \fBcxxopts::values::abstract_value\fP< T >::get_implicit_value () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBcxxopts::Value\fP\&.
.PP
Definition at line \fB479\fP of file \fBcxxopts\&.hpp\fP\&.
.SS "template<typename T > bool \fBcxxopts::values::abstract_value\fP< T >::has_default () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBcxxopts::Value\fP\&.
.PP
Definition at line \fB461\fP of file \fBcxxopts\&.hpp\fP\&.
.SS "template<typename T > bool \fBcxxopts::values::abstract_value\fP< T >::has_implicit () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBcxxopts::Value\fP\&.
.PP
Definition at line \fB463\fP of file \fBcxxopts\&.hpp\fP\&.
.SS "template<typename T > std::shared_ptr< \fBValue\fP > \fBcxxopts::values::abstract_value\fP< T >::implicit_value (const std::string & value)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBcxxopts::Value\fP\&.
.PP
Definition at line \fB471\fP of file \fBcxxopts\&.hpp\fP\&.
.SS "template<typename T > bool \fBcxxopts::values::abstract_value\fP< T >::is_boolean () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBcxxopts::Value\fP\&.
.PP
Definition at line \fB481\fP of file \fBcxxopts\&.hpp\fP\&.
.SS "template<typename T > bool \fBcxxopts::values::abstract_value\fP< T >::is_container () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBcxxopts::Value\fP\&.
.PP
Definition at line \fB457\fP of file \fBcxxopts\&.hpp\fP\&.
.SS "template<typename T > void \fBcxxopts::values::abstract_value\fP< T >::parse () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBcxxopts::Value\fP\&.
.PP
Definition at line \fB459\fP of file \fBcxxopts\&.hpp\fP\&.
.SS "template<typename T > void \fBcxxopts::values::abstract_value\fP< T >::parse (const std::string & text) const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBcxxopts::Value\fP\&.
.PP
Definition at line \fB455\fP of file \fBcxxopts\&.hpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "template<typename T > bool \fBcxxopts::values::abstract_value\fP< T >::m_default = false\fC [protected]\fP"

.PP
Definition at line \fB495\fP of file \fBcxxopts\&.hpp\fP\&.
.SS "template<typename T > std::string \fBcxxopts::values::abstract_value\fP< T >::m_default_value\fC [protected]\fP"

.PP
Definition at line \fB498\fP of file \fBcxxopts\&.hpp\fP\&.
.SS "template<typename T > bool \fBcxxopts::values::abstract_value\fP< T >::m_implicit = false\fC [protected]\fP"

.PP
Definition at line \fB496\fP of file \fBcxxopts\&.hpp\fP\&.
.SS "template<typename T > std::string \fBcxxopts::values::abstract_value\fP< T >::m_implicit_value\fC [protected]\fP"

.PP
Definition at line \fB499\fP of file \fBcxxopts\&.hpp\fP\&.
.SS "template<typename T > std::shared_ptr<T> \fBcxxopts::values::abstract_value\fP< T >::m_result\fC [protected]\fP"

.PP
Definition at line \fB492\fP of file \fBcxxopts\&.hpp\fP\&.
.SS "template<typename T > T* \fBcxxopts::values::abstract_value\fP< T >::m_store\fC [protected]\fP"

.PP
Definition at line \fB493\fP of file \fBcxxopts\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
