.TH "cxxopts::HelpOptionDetails" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cxxopts::HelpOptionDetails
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cxxopts\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBs\fP"
.br
.ti -1c
.RI "std::string \fBl\fP"
.br
.ti -1c
.RI "\fBString\fP \fBdesc\fP"
.br
.ti -1c
.RI "bool \fBhas_default\fP"
.br
.ti -1c
.RI "std::string \fBdefault_value\fP"
.br
.ti -1c
.RI "bool \fBhas_implicit\fP"
.br
.ti -1c
.RI "std::string \fBimplicit_value\fP"
.br
.ti -1c
.RI "std::string \fBarg_help\fP"
.br
.ti -1c
.RI "bool \fBis_container\fP"
.br
.ti -1c
.RI "bool \fBis_boolean\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB562\fP of file \fBcxxopts\&.hpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "std::string cxxopts::HelpOptionDetails::arg_help"

.PP
Definition at line \fB570\fP of file \fBcxxopts\&.hpp\fP\&.
.SS "std::string cxxopts::HelpOptionDetails::default_value"

.PP
Definition at line \fB567\fP of file \fBcxxopts\&.hpp\fP\&.
.SS "\fBString\fP cxxopts::HelpOptionDetails::desc"

.PP
Definition at line \fB565\fP of file \fBcxxopts\&.hpp\fP\&.
.SS "bool cxxopts::HelpOptionDetails::has_default"

.PP
Definition at line \fB566\fP of file \fBcxxopts\&.hpp\fP\&.
.SS "bool cxxopts::HelpOptionDetails::has_implicit"

.PP
Definition at line \fB568\fP of file \fBcxxopts\&.hpp\fP\&.
.SS "std::string cxxopts::HelpOptionDetails::implicit_value"

.PP
Definition at line \fB569\fP of file \fBcxxopts\&.hpp\fP\&.
.SS "bool cxxopts::HelpOptionDetails::is_boolean"

.PP
Definition at line \fB572\fP of file \fBcxxopts\&.hpp\fP\&.
.SS "bool cxxopts::HelpOptionDetails::is_container"

.PP
Definition at line \fB571\fP of file \fBcxxopts\&.hpp\fP\&.
.SS "std::string cxxopts::HelpOptionDetails::l"

.PP
Definition at line \fB564\fP of file \fBcxxopts\&.hpp\fP\&.
.SS "std::string cxxopts::HelpOptionDetails::s"

.PP
Definition at line \fB563\fP of file \fBcxxopts\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
