.TH "cxxopts::Options" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cxxopts::Options
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cxxopts\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOptions\fP (std::string program, std::string help_string='')"
.br
.ti -1c
.RI "\fBOptions\fP & \fBpositional_help\fP (std::string help_text)"
.br
.ti -1c
.RI "\fBOptions\fP & \fBcustom_help\fP (std::string help_text)"
.br
.ti -1c
.RI "\fBOptions\fP & \fBshow_positional_help\fP ()"
.br
.ti -1c
.RI "\fBOptions\fP & \fBallow_unrecognised_options\fP ()"
.br
.ti -1c
.RI "\fBParseResult\fP \fBparse\fP (int &argc, char **&argv)"
.br
.ti -1c
.RI "\fBOptionAdder\fP \fBadd_options\fP (std::string group='')"
.br
.ti -1c
.RI "void \fBadd_option\fP (const std::string &group, const std::string &s, const std::string &l, std::string desc, std::shared_ptr< const \fBValue\fP > \fBvalue\fP, std::string arg_help)"
.br
.ti -1c
.RI "void \fBparse_positional\fP (std::string option)"
.br
.ti -1c
.RI "void \fBparse_positional\fP (std::vector< std::string > options)"
.br
.ti -1c
.RI "void \fBparse_positional\fP (std::initializer_list< std::string > options)"
.br
.ti -1c
.RI "std::string \fBhelp\fP (const std::vector< std::string > &\fBgroups\fP={''}) const"
.br
.ti -1c
.RI "const std::vector< std::string > \fBgroups\fP () const"
.br
.ti -1c
.RI "const \fBHelpGroupDetails\fP & \fBgroup_help\fP (const std::string &group) const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB690\fP of file \fBcxxopts\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "cxxopts::Options::Options (std::string program, std::string help_string = \fC''\fP)\fC [inline]\fP"

.PP
Definition at line \fB692\fP of file \fBcxxopts\&.hpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void cxxopts::Options::add_option (const std::string & group, const std::string & s, const std::string & l, std::string desc, std::shared_ptr< const \fBValue\fP > value, std::string arg_help)\fC [inline]\fP"

.PP
Definition at line \fB1102\fP of file \fBcxxopts\&.hpp\fP\&.
.SS "\fBOptionAdder\fP cxxopts::Options::add_options (std::string group = \fC''\fP)\fC [inline]\fP"

.PP
Definition at line \fB866\fP of file \fBcxxopts\&.hpp\fP\&.
.SS "\fBOptions\fP & cxxopts::Options::allow_unrecognised_options ()\fC [inline]\fP"

.PP
Definition at line \fB712\fP of file \fBcxxopts\&.hpp\fP\&.
.SS "\fBOptions\fP & cxxopts::Options::custom_help (std::string help_text)\fC [inline]\fP"

.PP
Definition at line \fB702\fP of file \fBcxxopts\&.hpp\fP\&.
.SS "const \fBHelpGroupDetails\fP & cxxopts::Options::group_help (const std::string & group) const\fC [inline]\fP"

.PP
Definition at line \fB1240\fP of file \fBcxxopts\&.hpp\fP\&.
.SS "const std::vector< std::string > cxxopts::Options::groups () const\fC [inline]\fP"

.PP
Definition at line \fB1231\fP of file \fBcxxopts\&.hpp\fP\&.
.SS "std::string cxxopts::Options::help (const std::vector< std::string > & groups = \fC{''}\fP) const\fC [inline]\fP"

.PP
Definition at line \fB1212\fP of file \fBcxxopts\&.hpp\fP\&.
.SS "\fBParseResult\fP cxxopts::Options::parse (int & argc, char **& argv)\fC [inline]\fP"

.PP
Definition at line \fB974\fP of file \fBcxxopts\&.hpp\fP\&.
.SS "void cxxopts::Options::parse_positional (std::initializer_list< std::string > options)\fC [inline]\fP"

.PP
Definition at line \fB970\fP of file \fBcxxopts\&.hpp\fP\&.
.SS "void cxxopts::Options::parse_positional (std::string option)\fC [inline]\fP"

.PP
Definition at line \fB961\fP of file \fBcxxopts\&.hpp\fP\&.
.SS "void cxxopts::Options::parse_positional (std::vector< std::string > options)\fC [inline]\fP"

.PP
Definition at line \fB963\fP of file \fBcxxopts\&.hpp\fP\&.
.SS "\fBOptions\fP & cxxopts::Options::positional_help (std::string help_text)\fC [inline]\fP"

.PP
Definition at line \fB697\fP of file \fBcxxopts\&.hpp\fP\&.
.SS "\fBOptions\fP & cxxopts::Options::show_positional_help ()\fC [inline]\fP"

.PP
Definition at line \fB707\fP of file \fBcxxopts\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
