.TH "cxxopts::values::detail::SignedCheck< T, true >" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cxxopts::values::detail::SignedCheck< T, true >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cxxopts\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename U > void \fBoperator()\fP (bool negative, U u, const std::string &text)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T>
.br
struct cxxopts::values::detail::SignedCheck< T, true >"
.PP
Definition at line \fB277\fP of file \fBcxxopts\&.hpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "template<typename T > template<typename U > void \fBcxxopts::values::detail::SignedCheck\fP< T, true >::operator() (bool negative, U u, const std::string & text)\fC [inline]\fP"

.PP
Definition at line \fB278\fP of file \fBcxxopts\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
