.TH "cxxopts::OptionDetails" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cxxopts::OptionDetails
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cxxopts\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOptionDetails\fP (const std::string &short_, const std::string &long_, const \fBString\fP &desc, std::shared_ptr< const \fBValue\fP > val)"
.br
.ti -1c
.RI "\fBOptionDetails\fP (const \fBOptionDetails\fP &rhs)"
.br
.ti -1c
.RI "\fBOptionDetails\fP (\fBOptionDetails\fP &&rhs)=default"
.br
.ti -1c
.RI "const \fBString\fP & \fBdescription\fP () const"
.br
.ti -1c
.RI "const \fBValue\fP & \fBvalue\fP () const"
.br
.ti -1c
.RI "std::shared_ptr< \fBValue\fP > \fBmake_storage\fP () const"
.br
.ti -1c
.RI "const std::string & \fBshort_name\fP () const"
.br
.ti -1c
.RI "const std::string & \fBlong_name\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB535\fP of file \fBcxxopts\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "cxxopts::OptionDetails::OptionDetails (const std::string & short_, const std::string & long_, const \fBString\fP & desc, std::shared_ptr< const \fBValue\fP > val)\fC [inline]\fP"

.PP
Definition at line \fB537\fP of file \fBcxxopts\&.hpp\fP\&.
.SS "cxxopts::OptionDetails::OptionDetails (const \fBOptionDetails\fP & rhs)\fC [inline]\fP"

.PP
Definition at line \fB540\fP of file \fBcxxopts\&.hpp\fP\&.
.SS "cxxopts::OptionDetails::OptionDetails (\fBOptionDetails\fP && rhs)\fC [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "const \fBString\fP & cxxopts::OptionDetails::description () const\fC [inline]\fP"

.PP
Definition at line \fB544\fP of file \fBcxxopts\&.hpp\fP\&.
.SS "const std::string & cxxopts::OptionDetails::long_name () const\fC [inline]\fP"

.PP
Definition at line \fB552\fP of file \fBcxxopts\&.hpp\fP\&.
.SS "std::shared_ptr< \fBValue\fP > cxxopts::OptionDetails::make_storage () const\fC [inline]\fP"

.PP
Definition at line \fB548\fP of file \fBcxxopts\&.hpp\fP\&.
.SS "const std::string & cxxopts::OptionDetails::short_name () const\fC [inline]\fP"

.PP
Definition at line \fB550\fP of file \fBcxxopts\&.hpp\fP\&.
.SS "const \fBValue\fP & cxxopts::OptionDetails::value () const\fC [inline]\fP"

.PP
Definition at line \fB546\fP of file \fBcxxopts\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
