.TH "cxxopts::values::detail" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cxxopts::values::detail
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBSignedCheck\fP"
.br
.ti -1c
.RI "struct \fBSignedCheck< T, false >\fP"
.br
.ti -1c
.RI "struct \fBSignedCheck< T, true >\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename T , typename U > void \fBcheck_signed_range\fP (bool negative, U \fBvalue\fP, const std::string &text)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "template<typename T , typename U > void cxxopts::values::detail::check_signed_range (bool negative, U value, const std::string & text)"

.PP
Definition at line \fB295\fP of file \fBcxxopts\&.hpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
