.TH "cxxopts::values::standard_value< bool >" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cxxopts::values::standard_value< bool >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cxxopts\&.hpp>\fP
.PP
Inherits \fBcxxopts::values::abstract_value< bool >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB~standard_value\fP ()=default"
.br
.ti -1c
.RI "\fBstandard_value\fP ()"
.br
.ti -1c
.RI "\fBstandard_value\fP (bool *b)"
.br
.ti -1c
.RI "std::shared_ptr< \fBValue\fP > \fBclone\fP () const"
.br
.in -1c

Public Member Functions inherited from \fBcxxopts::values::abstract_value< bool >\fP
.in +1c
.ti -1c
.RI "\fBabstract_value\fP ()"
.br
.ti -1c
.RI "\fBabstract_value\fP (bool *t)"
.br
.ti -1c
.RI "\fBabstract_value\fP (const \fBabstract_value\fP &rhs)"
.br
.ti -1c
.RI "virtual \fB~abstract_value\fP ()=default"
.br
.ti -1c
.RI "void \fBparse\fP (const std::string &text) const"
.br
.ti -1c
.RI "void \fBparse\fP () const"
.br
.ti -1c
.RI "bool \fBis_container\fP () const"
.br
.ti -1c
.RI "bool \fBhas_default\fP () const"
.br
.ti -1c
.RI "bool \fBhas_implicit\fP () const"
.br
.ti -1c
.RI "std::shared_ptr< \fBValue\fP > \fBdefault_value\fP (const std::string &value)"
.br
.ti -1c
.RI "std::shared_ptr< \fBValue\fP > \fBimplicit_value\fP (const std::string &value)"
.br
.ti -1c
.RI "std::string \fBget_default_value\fP () const"
.br
.ti -1c
.RI "std::string \fBget_implicit_value\fP () const"
.br
.ti -1c
.RI "bool \fBis_boolean\fP () const"
.br
.ti -1c
.RI "const bool & \fBget\fP () const"
.br
.in -1c

Public Member Functions inherited from \fBcxxopts::Value\fP
.in +1c
.ti -1c
.RI "virtual \fB~Value\fP ()=default"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Attributes inherited from \fBcxxopts::values::abstract_value< bool >\fP
.in +1c
.ti -1c
.RI "std::shared_ptr< bool > \fBm_result\fP"
.br
.ti -1c
.RI "bool * \fBm_store\fP"
.br
.ti -1c
.RI "bool \fBm_default\fP"
.br
.ti -1c
.RI "bool \fBm_implicit\fP"
.br
.ti -1c
.RI "std::string \fBm_default_value\fP"
.br
.ti -1c
.RI "std::string \fBm_implicit_value\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB509\fP of file \fBcxxopts\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBcxxopts::values::standard_value\fP< bool >::~\fBstandard_value\fP ()\fC [default]\fP"

.SS "\fBcxxopts::values::standard_value\fP< bool >::standard_value ()\fC [inline]\fP"

.PP
Definition at line \fB513\fP of file \fBcxxopts\&.hpp\fP\&.
.SS "\fBcxxopts::values::standard_value\fP< bool >::standard_value (bool * b)\fC [inline]\fP"

.PP
Definition at line \fB515\fP of file \fBcxxopts\&.hpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "std::shared_ptr< \fBValue\fP > \fBcxxopts::values::standard_value\fP< bool >::clone () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBcxxopts::Value\fP\&.
.PP
Definition at line \fB517\fP of file \fBcxxopts\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
