.TH "cxxopts::HelpGroupDetails" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cxxopts::HelpGroupDetails
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cxxopts\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBname\fP"
.br
.ti -1c
.RI "std::string \fBdescription\fP"
.br
.ti -1c
.RI "std::vector< \fBHelpOptionDetails\fP > \fBoptions\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB575\fP of file \fBcxxopts\&.hpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "std::string cxxopts::HelpGroupDetails::description"

.PP
Definition at line \fB577\fP of file \fBcxxopts\&.hpp\fP\&.
.SS "std::string cxxopts::HelpGroupDetails::name"

.PP
Definition at line \fB576\fP of file \fBcxxopts\&.hpp\fP\&.
.SS "std::vector<\fBHelpOptionDetails\fP> cxxopts::HelpGroupDetails::options"

.PP
Definition at line \fB578\fP of file \fBcxxopts\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
