.TH "cxxopts::OptionValue" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cxxopts::OptionValue
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cxxopts\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBparse\fP (std::shared_ptr< const \fBOptionDetails\fP > details, const std::string &text)"
.br
.ti -1c
.RI "void \fBparse_default\fP (std::shared_ptr< const \fBOptionDetails\fP > details)"
.br
.ti -1c
.RI "size_t \fBcount\fP () const"
.br
.ti -1c
.RI "template<typename T > const T & \fBas\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB581\fP of file \fBcxxopts\&.hpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "template<typename T > const T & cxxopts::OptionValue::as () const\fC [inline]\fP"

.PP
Definition at line \fB596\fP of file \fBcxxopts\&.hpp\fP\&.
.SS "size_t cxxopts::OptionValue::count () const\fC [inline]\fP"

.PP
Definition at line \fB594\fP of file \fBcxxopts\&.hpp\fP\&.
.SS "void cxxopts::OptionValue::parse (std::shared_ptr< const \fBOptionDetails\fP > details, const std::string & text)\fC [inline]\fP"

.PP
Definition at line \fB583\fP of file \fBcxxopts\&.hpp\fP\&.
.SS "void cxxopts::OptionValue::parse_default (std::shared_ptr< const \fBOptionDetails\fP > details)\fC [inline]\fP"

.PP
Definition at line \fB589\fP of file \fBcxxopts\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
