.TH "DecAppMem" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DecAppMem \- decoder application class  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <DecAppMem\&.h>\fP
.PP
Inherits DecAppCfg\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~DecAppMem\fP ()"
.br
.in -1c
.in +1c
.ti -1c
.RI "\fBDecAppMem\fP (\fBVideoIOYuvMem::Writer\fP *writer)"
.br
.ti -1c
.RI "uint32_t \fBdecode\fP (std::istream &istream)"
.br
.RI "main decoding function "
.in -1c
.SH "Detailed Description"
.PP 
decoder application class 
.PP
Definition at line \fB58\fP of file \fBDecAppMem\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "DecAppMem::DecAppMem (\fBVideoIOYuvMem::Writer\fP * writer)"

.PP
Definition at line \fB59\fP of file \fBDecAppMem\&.cpp\fP\&.
.SS "virtual DecAppMem::~DecAppMem ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Definition at line \fB80\fP of file \fBDecAppMem\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "uint32_t DecAppMem::decode (std::istream & bitstreamFile)"

.PP
main decoding function 
.IP "\(bu" 2
create internal class
.IP "\(bu" 2
initialize internal class
.IP "\(bu" 2
until the end of the bitstream, call decoding function in DecApp class
.IP "\(bu" 2
delete allocated buffers
.IP "\(bu" 2
destroy internal class
.IP "\(bu" 2
returns the number of mismatching pictures 
.PP

.PP
Definition at line \fB82\fP of file \fBDecAppMem\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
