.TH "deps/base_vvc/src/DecAppMem.h" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deps/base_vvc/src/DecAppMem.h
.SH SYNOPSIS
.br
.PP
\fC#include 'VideoIOYuvMem\&.h'\fP
.br
\fC#include 'CommonLib/Picture\&.h'\fP
.br
\fC#include 'DecoderLib/DecLib\&.h'\fP
.br
\fC#include 'DecAppCfg\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDecAppMem\fP"
.br
.RI "decoder application class "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
