.TH "DecoderApp" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DecoderApp
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBlctm::BaseVideoDecoder::Output\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDecoderApp\fP (\fBYUVWriter\fP &writer, \fBYUVReader\fP &reader)"
.br
.ti -1c
.RI "void \fBpush_base_enhancement\fP (const \fBBaseVideoDecoder::BasePicture\fP *base_picture, const uint8_t *enhancement_data, size_t enhancement_data_size, uint64_t pts, bool \fBis_lcevc_idr\fP) override"
.br
.ti -1c
.RI "void \fBpush_base_enhancement\fP (const uint8_t *base_data, size_t base_data_size, \fBSurface\fP(&symbols)[\fBMAX_NUM_PLANES\fP][\fBMAX_NUM_LOQS\fP][\fBMAX_NUM_LAYERS\fP], uint64_t pts, bool \fBis_lcevc_idr\fP) override"
.br
.ti -1c
.RI "void \fBdeserialize_enhancement\fP (const uint8_t *enhancement_data, size_t enhancement_data_size, \fBSurface\fP(&symbols)[\fBMAX_NUM_PLANES\fP][\fBMAX_NUM_LOQS\fP][\fBMAX_NUM_LAYERS\fP]) override"
.br
.ti -1c
.RI "\fBDimensions\fP \fBget_dimensions\fP () override"
.br
.ti -1c
.RI "\fBColourspace\fP \fBget_colourspace\fP () override"
.br
.ti -1c
.RI "unsigned \fBget_base_bitdepth\fP () override"
.br
.in -1c

Public Member Functions inherited from \fBlctm::BaseVideoDecoder::Output\fP
.in +1c
.ti -1c
.RI "virtual \fB~Output\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBYUVWriter\fP & \fBwriter_\fP"
.br
.ti -1c
.RI "\fBYUVReader\fP & \fBreader_\fP"
.br
.ti -1c
.RI "\fBDecoder\fP \fBdecoder_\fP"
.br
.ti -1c
.RI "int \fBcount_\fP = 0"
.br
.ti -1c
.RI "bool \fBreport_\fP = false"
.br
.ti -1c
.RI "bool \fBdithering_switch_\fP = false"
.br
.ti -1c
.RI "bool \fBdithering_fixed_\fP = false"
.br
.ti -1c
.RI "bool \fBapply_enhancement_\fP = true"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB84\fP of file \fBModelDecoderApp\&.cpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "DecoderApp::DecoderApp (\fBYUVWriter\fP & writer, \fBYUVReader\fP & reader)"

.PP
Definition at line \fB324\fP of file \fBModelDecoderApp\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void DecoderApp::deserialize_enhancement (const uint8_t * enhancement_data, size_t enhancement_data_size, \fBSurface\fP(&) symbols[MAX_NUM_PLANES][MAX_NUM_LOQS][MAX_NUM_LAYERS])\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBlctm::BaseVideoDecoder::Output\fP\&.
.PP
Definition at line \fB480\fP of file \fBModelDecoderApp\&.cpp\fP\&.
.SS "unsigned DecoderApp::get_base_bitdepth ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBlctm::BaseVideoDecoder::Output\fP\&.
.PP
Definition at line \fB487\fP of file \fBModelDecoderApp\&.cpp\fP\&.
.SS "\fBColourspace\fP DecoderApp::get_colourspace ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBlctm::BaseVideoDecoder::Output\fP\&.
.PP
Definition at line \fB489\fP of file \fBModelDecoderApp\&.cpp\fP\&.
.SS "\fBDimensions\fP DecoderApp::get_dimensions ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBlctm::BaseVideoDecoder::Output\fP\&.
.PP
Definition at line \fB485\fP of file \fBModelDecoderApp\&.cpp\fP\&.
.SS "void DecoderApp::push_base_enhancement (const \fBBaseVideoDecoder::BasePicture\fP * base_picture, const uint8_t * enhancement_data, size_t enhancement_data_size, uint64_t pts, bool is_lcevc_idr)\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBlctm::BaseVideoDecoder::Output\fP\&.
.PP
Definition at line \fB326\fP of file \fBModelDecoderApp\&.cpp\fP\&.
.SS "void DecoderApp::push_base_enhancement (const uint8_t * base_data, size_t base_data_size, \fBSurface\fP(&) symbols[MAX_NUM_PLANES][MAX_NUM_LOQS][MAX_NUM_LAYERS], uint64_t pts, bool is_lcevc_idr)\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBlctm::BaseVideoDecoder::Output\fP\&.
.PP
Definition at line \fB405\fP of file \fBModelDecoderApp\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bool DecoderApp::apply_enhancement_ = true"

.PP
Definition at line \fB113\fP of file \fBModelDecoderApp\&.cpp\fP\&.
.SS "int DecoderApp::count_ = 0"

.PP
Definition at line \fB108\fP of file \fBModelDecoderApp\&.cpp\fP\&.
.SS "\fBDecoder\fP DecoderApp::decoder_"

.PP
Definition at line \fB106\fP of file \fBModelDecoderApp\&.cpp\fP\&.
.SS "bool DecoderApp::dithering_fixed_ = false"

.PP
Definition at line \fB112\fP of file \fBModelDecoderApp\&.cpp\fP\&.
.SS "bool DecoderApp::dithering_switch_ = false"

.PP
Definition at line \fB111\fP of file \fBModelDecoderApp\&.cpp\fP\&.
.SS "\fBYUVReader\fP& DecoderApp::reader_"

.PP
Definition at line \fB104\fP of file \fBModelDecoderApp\&.cpp\fP\&.
.SS "bool DecoderApp::report_ = false"

.PP
Definition at line \fB110\fP of file \fBModelDecoderApp\&.cpp\fP\&.
.SS "\fBYUVWriter\fP& DecoderApp::writer_"

.PP
Definition at line \fB103\fP of file \fBModelDecoderApp\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
