.TH "decoder/src/Decoder.cpp" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
decoder/src/Decoder.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'Decoder\&.hpp'\fP
.br
\fC#include 'Add\&.hpp'\fP
.br
\fC#include 'Conform\&.hpp'\fP
.br
\fC#include 'Convert\&.hpp'\fP
.br
\fC#include 'Deblocking\&.hpp'\fP
.br
\fC#include 'Deserializer\&.hpp'\fP
.br
\fC#include 'Diagnostics\&.hpp'\fP
.br
\fC#include 'Dithering\&.hpp'\fP
.br
\fC#include 'Expand\&.hpp'\fP
.br
\fC#include 'InverseQuantize\&.hpp'\fP
.br
\fC#include 'InverseTransformDD\&.hpp'\fP
.br
\fC#include 'InverseTransformDDS\&.hpp'\fP
.br
\fC#include 'InverseTransformDDS_1D\&.hpp'\fP
.br
\fC#include 'InverseTransformDD_1D\&.hpp'\fP
.br
\fC#include 'LcevcMd5\&.hpp'\fP
.br
\fC#include 'PredictedResidual\&.hpp'\fP
.br
\fC#include 'TemporalDecode\&.hpp'\fP
.br
\fC#include 'Upsampling\&.hpp'\fP
.br
\fC#include <cstring>\fP
.br
\fC#include <memory>\fP
.br
\fC#include <queue>\fP
.br
\fC#include <vector>\fP
.br
\fC#include 'BitstreamStatistic\&.hpp'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBlctm\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBPsnrStatistic\fP \fBgoPsnr\fP"
.br
.ti -1c
.RI "uint8_t \fBgaucMd5Digest\fP [][16]"
.br
.ti -1c
.RI "\fBReportStructure\fP \fBgoReportStructure\fP"
.br
.ti -1c
.RI "priority_queue< \fBReportStructure\fP, vector< \fBReportStructure\fP, allocator< \fBReportStructure\fP > >, \fBReportStructureComp\fP > \fBgoReportQueue\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "uint8_t gaucMd5Digest[][16]\fC [extern]\fP"

.PP
Definition at line \fB76\fP of file \fBModelDecoderApp\&.cpp\fP\&.
.SS "\fBPsnrStatistic\fP goPsnr\fC [extern]\fP"

.PP
Definition at line \fB75\fP of file \fBModelDecoderApp\&.cpp\fP\&.
.SS "priority_queue<\fBReportStructure\fP, vector<\fBReportStructure\fP, allocator<\fBReportStructure\fP> >, \fBReportStructureComp\fP> goReportQueue\fC [extern]\fP"

.PP
Definition at line \fB79\fP of file \fBModelDecoderApp\&.cpp\fP\&.
.SS "\fBReportStructure\fP goReportStructure\fC [extern]\fP"

.PP
Definition at line \fB77\fP of file \fBModelDecoderApp\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
