.TH "source_patch/defines.h" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
source_patch/defines.h \- Header file containing some useful global definitions\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'typedefs\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTRACE\fP   0"
.br
.RI "0:Trace off 1:Trace on 2:detailed CABAC context information "
.ti -1c
.RI "#define \fBJM\fP   '19 (FRExt)'"
.br
.ti -1c
.RI "#define \fBVERSION\fP   '19\&.0'"
.br
.ti -1c
.RI "#define \fBEXT_VERSION\fP   '(FRExt)'"
.br
.ti -1c
.RI "#define \fBDUMP_DPB\fP   0"
.br
.RI "Dump DPB info for debug purposes\&. "
.ti -1c
.RI "#define \fBPRINTREFLIST\fP   0"
.br
.RI "Print ref list info for debug purposes\&. "
.ti -1c
.RI "#define \fBPAIR_FIELDS_IN_OUTPUT\fP   0"
.br
.RI "Pair field pictures for output purposes\&. "
.ti -1c
.RI "#define \fBIMGTYPE\fP   1"
.br
.RI "Define imgpel size type\&. 0 implies byte (cannot handle >8 bit depths) and 1 implies unsigned short\&. "
.ti -1c
.RI "#define \fBENABLE_FIELD_CTX\fP   1"
.br
.RI "Enables Field mode related context types for CABAC\&. "
.ti -1c
.RI "#define \fBENABLE_HIGH444_CTX\fP   1"
.br
.RI "Enables High 444 profile context types for CABAC\&. "
.ti -1c
.RI "#define \fBZEROSNR\fP   0"
.br
.RI "PSNR computation method\&. "
.ti -1c
.RI "#define \fBENABLE_OUTPUT_TONEMAPPING\fP   1"
.br
.RI "enable tone map the output if tone mapping SEI present "
.ti -1c
.RI "#define \fBJCOST_CALC_SCALEUP\fP   1"
.br
.RI "1: J = (D<<LAMBDA_ACCURACY_BITS)+Lambda*R; 0: J = D + ((Lambda*R+Rounding)>>LAMBDA_ACCURACY_BITS) "
.ti -1c
.RI "#define \fBDISABLE_ERC\fP   0"
.br
.RI "Disable any error concealment processes\&. "
.ti -1c
.RI "#define \fBJM_PARALLEL_DEBLOCK\fP   0"
.br
.RI "Enables Parallel Deblocking\&. "
.ti -1c
.RI "#define \fBSIMULCAST_ENABLE\fP   0"
.br
.RI "to test the decoder "
.ti -1c
.RI "#define \fBMVC_EXTENSION_ENABLE\fP   1"
.br
.RI "enable support for the Multiview High Profile "
.ti -1c
.RI "#define \fBENABLE_DEC_STATS\fP   0"
.br
.RI "enable decoder statistics collection "
.ti -1c
.RI "#define \fBMVC_INIT_VIEW_ID\fP   \-1"
.br
.ti -1c
.RI "#define \fBMAX_VIEW_NUM\fP   1024"
.br
.ti -1c
.RI "#define \fBBASE_VIEW_IDX\fP   0"
.br
.ti -1c
.RI "#define \fBSSE_MEMORY_ALIGNMENT\fP   16"
.br
.ti -1c
.RI "#define \fBMAX_NUM_SLICES\fP   50"
.br
.ti -1c
.RI "#define \fBMAX_REFERENCE_PICTURES\fP   32"
.br
.RI "H\&.264 allows 32 fields\&. "
.ti -1c
.RI "#define \fBMAX_CODED_FRAME_SIZE\fP   8000000"
.br
.RI "bytes for one frame "
.ti -1c
.RI "#define \fBMAX_NUM_DECSLICES\fP   16"
.br
.ti -1c
.RI "#define \fBMAX_DEC_THREADS\fP   16"
.br
.ti -1c
.RI "#define \fBMCBUF_LUMA_PAD_X\fP   32"
.br
.ti -1c
.RI "#define \fBMCBUF_LUMA_PAD_Y\fP   12"
.br
.ti -1c
.RI "#define \fBMCBUF_CHROMA_PAD_X\fP   16"
.br
.ti -1c
.RI "#define \fBMCBUF_CHROMA_PAD_Y\fP   8"
.br
.ti -1c
.RI "#define \fBMAX_NUM_DPB_LAYERS\fP   2"
.br
.ti -1c
.RI "#define \fBFILE_NAME_SIZE\fP   255"
.br
.ti -1c
.RI "#define \fBINPUT_TEXT_SIZE\fP   1024"
.br
.ti -1c
.RI "#define \fBNUM_BLOCK_TYPES\fP   22"
.br
.ti -1c
.RI "#define \fBBLOCK_SHIFT\fP   2"
.br
.ti -1c
.RI "#define \fBBLOCK_SIZE\fP   4"
.br
.ti -1c
.RI "#define \fBBLOCK_SIZE_8x8\fP   8"
.br
.ti -1c
.RI "#define \fBSMB_BLOCK_SIZE\fP   8"
.br
.ti -1c
.RI "#define \fBBLOCK_PIXELS\fP   16"
.br
.ti -1c
.RI "#define \fBMB_BLOCK_SIZE\fP   16"
.br
.ti -1c
.RI "#define \fBMB_PIXELS\fP   256"
.br
.ti -1c
.RI "#define \fBMB_PIXELS_SHIFT\fP   8"
.br
.ti -1c
.RI "#define \fBMB_BLOCK_SHIFT\fP   4"
.br
.ti -1c
.RI "#define \fBBLOCK_MULTIPLE\fP   4"
.br
.ti -1c
.RI "#define \fBMB_BLOCK_PARTITIONS\fP   16"
.br
.ti -1c
.RI "#define \fBBLOCK_CONTEXT\fP   64"
.br
.ti -1c
.RI "#define \fBBLOCK_SIZE_SP\fP   16"
.br
.ti -1c
.RI "#define \fBBLOCK_SIZE_8x8_SP\fP   32"
.br
.ti -1c
.RI "#define \fBNO_INTRA_PMODE\fP   9"
.br
.ti -1c
.RI "#define \fBQ_BITS\fP   15"
.br
.ti -1c
.RI "#define \fBDQ_BITS\fP   6"
.br
.ti -1c
.RI "#define \fBQ_BITS_8\fP   16"
.br
.ti -1c
.RI "#define \fBDQ_BITS_8\fP   6"
.br
.ti -1c
.RI "#define \fBIS_I16MB\fP(MB)   ((MB)\->mb_type==\fBI16MB\fP  || (MB)\->mb_type==\fBIPCM\fP)"
.br
.ti -1c
.RI "#define \fBIS_DIRECT\fP(MB)   ((MB)\->mb_type==0     && (currSlice\->slice_type == B_SLICE ))"
.br
.ti -1c
.RI "#define \fBTOTRUN_NUM\fP   15"
.br
.ti -1c
.RI "#define \fBRUNBEFORE_NUM\fP   7"
.br
.ti -1c
.RI "#define \fBRUNBEFORE_NUM_M1\fP   6"
.br
.ti -1c
.RI "#define \fBMIN_QP\fP   0"
.br
.ti -1c
.RI "#define \fBMAX_QP\fP   51"
.br
.ti -1c
.RI "#define \fBLAMBDA_ACCURACY_BITS\fP   16"
.br
.ti -1c
.RI "#define \fBINVALIDINDEX\fP   (\-135792468)"
.br
.ti -1c
.RI "#define \fBRC_MAX_TEMPORAL_LEVELS\fP   5"
.br
.ti -1c
.RI "#define \fBZEROBYTES_SHORTSTARTCODE\fP   2"
.br
.ti -1c
.RI "#define \fBMAX_PLANE\fP   3"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBProfileIDC\fP { \fBNO_PROFILE\fP = 0, \fBFREXT_CAVLC444\fP = 44, \fBBASELINE\fP = 66, \fBMAIN\fP = 77, \fBEXTENDED\fP = 88, \fBFREXT_HP\fP = 100, \fBFREXT_Hi10P\fP = 110, \fBFREXT_Hi422\fP = 122, \fBFREXT_Hi444\fP = 244, \fBMVC_HIGH\fP = 118, \fBSTEREO_HIGH\fP = 128 }"
.br
.ti -1c
.RI "enum \fBMBModeTypes\fP { \fBPSKIP\fP = 0, \fBBSKIP_DIRECT\fP = 0, \fBP16x16\fP = 1, \fBP16x8\fP = 2, \fBP8x16\fP = 3, \fBSMB8x8\fP = 4, \fBSMB8x4\fP = 5, \fBSMB4x8\fP = 6, \fBSMB4x4\fP = 7, \fBP8x8\fP = 8, \fBI4MB\fP = 9, \fBI16MB\fP = 10, \fBIBLOCK\fP = 11, \fBSI4MB\fP = 12, \fBI8MB\fP = 13, \fBIPCM\fP = 14, \fBMAXMODE\fP = 15 }"
.br
.ti -1c
.RI "enum \fBDirectModes\fP { \fBDIR_TEMPORAL\fP = 0, \fBDIR_SPATIAL\fP = 1 }"
.br
.ti -1c
.RI "enum \fBCAVLCBlockTypes\fP { \fBLUMA\fP = 0, \fBLUMA_INTRA16x16DC\fP = 1, \fBLUMA_INTRA16x16AC\fP = 2, \fBCB\fP = 3, \fBCB_INTRA16x16DC\fP = 4, \fBCB_INTRA16x16AC\fP = 5, \fBCR\fP = 8, \fBCR_INTRA16x16DC\fP = 9, \fBCR_INTRA16x16AC\fP = 10 }"
.br
.ti -1c
.RI "enum \fBCABACBlockTypes\fP { \fBLUMA_16DC\fP = 0, \fBLUMA_16AC\fP = 1, \fBLUMA_8x8\fP = 2, \fBLUMA_8x4\fP = 3, \fBLUMA_4x8\fP = 4, \fBLUMA_4x4\fP = 5, \fBCHROMA_DC\fP = 6, \fBCHROMA_AC\fP = 7, \fBCHROMA_DC_2x4\fP = 8, \fBCHROMA_DC_4x4\fP = 9, \fBCB_16DC\fP = 10, \fBCB_16AC\fP = 11, \fBCB_8x8\fP = 12, \fBCB_8x4\fP = 13, \fBCB_4x8\fP = 14, \fBCB_4x4\fP = 15, \fBCR_16DC\fP = 16, \fBCR_16AC\fP = 17, \fBCR_8x8\fP = 18, \fBCR_8x4\fP = 19, \fBCR_4x8\fP = 20, \fBCR_4x4\fP = 21 }"
.br
.ti -1c
.RI "enum \fBI4x4PredModes\fP { \fBVERT_PRED\fP = 0, \fBHOR_PRED\fP = 1, \fBDC_PRED\fP = 2, \fBDIAG_DOWN_LEFT_PRED\fP = 3, \fBDIAG_DOWN_RIGHT_PRED\fP = 4, \fBVERT_RIGHT_PRED\fP = 5, \fBHOR_DOWN_PRED\fP = 6, \fBVERT_LEFT_PRED\fP = 7, \fBHOR_UP_PRED\fP = 8 }"
.br
.ti -1c
.RI "enum \fBI16x16PredModes\fP { \fBVERT_PRED_16\fP = 0, \fBHOR_PRED_16\fP = 1, \fBDC_PRED_16\fP = 2, \fBPLANE_16\fP = 3 }"
.br
.ti -1c
.RI "enum \fBI8x8PredModes\fP { \fBDC_PRED_8\fP = 0, \fBHOR_PRED_8\fP = 1, \fBVERT_PRED_8\fP = 2, \fBPLANE_8\fP = 3 }"
.br
.ti -1c
.RI "enum \fBColorComponent\fP { \fBY_COMP\fP = 0, \fBU_COMP\fP = 1, \fBV_COMP\fP = 2, \fBR_COMP\fP = 3, \fBG_COMP\fP = 4, \fBB_COMP\fP = 5, \fBT_COMP\fP = 6 }"
.br
.ti -1c
.RI "enum { \fBEOS\fP = 1, \fBSOP\fP = 2, \fBSOS\fP = 3, \fBSOS_CONT\fP = 4 }"
.br
.ti -1c
.RI "enum \fBMVPredTypes\fP { \fBMVPRED_MEDIAN\fP = 0, \fBMVPRED_L\fP = 1, \fBMVPRED_U\fP = 2, \fBMVPRED_UR\fP = 3 }"
.br
.ti -1c
.RI "enum { \fBDECODING_OK\fP = 0, \fBSEARCH_SYNC\fP = 1, \fBPICTURE_DECODED\fP = 2 }"
.br
.in -1c
.SH "Detailed Description"
.PP 
Header file containing some useful global definitions\&. 


.PP
\fBAuthor\fP
.RS 4
Main contributors (see contributors\&.h for copyright, address and affiliation details)
.IP "\(bu" 2
Detlev Marpe
.IP "\(bu" 2
Karsten Suehring
.IP "\(bu" 2
Alexis Michael Tourapis alexismt@ieee.org
.PP
.RE
.PP
\fBDate\fP
.RS 4
.IP "21." 4
March 2001 
.PP
.RE
.PP

.PP
Definition in file \fBdefines\&.h\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define BASE_VIEW_IDX   0"

.PP
Definition at line \fB54\fP of file \fBdefines\&.h\fP\&.
.SS "#define BLOCK_CONTEXT   64"

.PP
Definition at line \fB110\fP of file \fBdefines\&.h\fP\&.
.SS "#define BLOCK_MULTIPLE   4"

.PP
Definition at line \fB108\fP of file \fBdefines\&.h\fP\&.
.SS "#define BLOCK_PIXELS   16"

.PP
Definition at line \fB103\fP of file \fBdefines\&.h\fP\&.
.SS "#define BLOCK_SHIFT   2"

.PP
Definition at line \fB99\fP of file \fBdefines\&.h\fP\&.
.SS "#define BLOCK_SIZE   4"

.PP
Definition at line \fB100\fP of file \fBdefines\&.h\fP\&.
.SS "#define BLOCK_SIZE_8x8   8"

.PP
Definition at line \fB101\fP of file \fBdefines\&.h\fP\&.
.SS "#define BLOCK_SIZE_8x8_SP   32"

.PP
Definition at line \fB114\fP of file \fBdefines\&.h\fP\&.
.SS "#define BLOCK_SIZE_SP   16"

.PP
Definition at line \fB113\fP of file \fBdefines\&.h\fP\&.
.SS "#define DISABLE_ERC   0"

.PP
Disable any error concealment processes\&. 
.PP
Definition at line \fB45\fP of file \fBdefines\&.h\fP\&.
.SS "#define DQ_BITS   6"

.PP
Definition at line \fB187\fP of file \fBdefines\&.h\fP\&.
.SS "#define DQ_BITS_8   6"

.PP
Definition at line \fB189\fP of file \fBdefines\&.h\fP\&.
.SS "#define DUMP_DPB   0"

.PP
Dump DPB info for debug purposes\&. 
.PP
Definition at line \fB36\fP of file \fBdefines\&.h\fP\&.
.SS "#define ENABLE_DEC_STATS   0"

.PP
enable decoder statistics collection 
.PP
Definition at line \fB50\fP of file \fBdefines\&.h\fP\&.
.SS "#define ENABLE_FIELD_CTX   1"

.PP
Enables Field mode related context types for CABAC\&. 
.PP
Definition at line \fB40\fP of file \fBdefines\&.h\fP\&.
.SS "#define ENABLE_HIGH444_CTX   1"

.PP
Enables High 444 profile context types for CABAC\&. 
.PP
Definition at line \fB41\fP of file \fBdefines\&.h\fP\&.
.SS "#define ENABLE_OUTPUT_TONEMAPPING   1"

.PP
enable tone map the output if tone mapping SEI present 
.PP
Definition at line \fB43\fP of file \fBdefines\&.h\fP\&.
.SS "#define EXT_VERSION   '(FRExt)'"

.PP
Definition at line \fB34\fP of file \fBdefines\&.h\fP\&.
.SS "#define FILE_NAME_SIZE   255"

.PP
Definition at line \fB87\fP of file \fBdefines\&.h\fP\&.
.SS "#define IMGTYPE   1"

.PP
Define imgpel size type\&. 0 implies byte (cannot handle >8 bit depths) and 1 implies unsigned short\&. 
.PP
Definition at line \fB39\fP of file \fBdefines\&.h\fP\&.
.SS "#define INPUT_TEXT_SIZE   1024"

.PP
Definition at line \fB88\fP of file \fBdefines\&.h\fP\&.
.SS "#define INVALIDINDEX   (\-135792468)"

.PP
Definition at line \fB264\fP of file \fBdefines\&.h\fP\&.
.SS "#define IS_DIRECT(MB)   ((MB)\->mb_type==0     && (currSlice\->slice_type == B_SLICE ))"

.PP
Definition at line \fB193\fP of file \fBdefines\&.h\fP\&.
.SS "#define IS_I16MB(MB)   ((MB)\->mb_type==\fBI16MB\fP  || (MB)\->mb_type==\fBIPCM\fP)"

.PP
Definition at line \fB192\fP of file \fBdefines\&.h\fP\&.
.SS "#define JCOST_CALC_SCALEUP   1"

.PP
1: J = (D<<LAMBDA_ACCURACY_BITS)+Lambda*R; 0: J = D + ((Lambda*R+Rounding)>>LAMBDA_ACCURACY_BITS) 
.PP
Definition at line \fB44\fP of file \fBdefines\&.h\fP\&.
.SS "#define JM   '19 (FRExt)'"

.PP
Definition at line \fB32\fP of file \fBdefines\&.h\fP\&.
.SS "#define JM_PARALLEL_DEBLOCK   0"

.PP
Enables Parallel Deblocking\&. 
.PP
Definition at line \fB46\fP of file \fBdefines\&.h\fP\&.
.SS "#define LAMBDA_ACCURACY_BITS   16"

.PP
Definition at line \fB263\fP of file \fBdefines\&.h\fP\&.
.SS "#define MAX_CODED_FRAME_SIZE   8000000"

.PP
bytes for one frame 
.PP
Definition at line \fB63\fP of file \fBdefines\&.h\fP\&.
.SS "#define MAX_DEC_THREADS   16"

.PP
Definition at line \fB65\fP of file \fBdefines\&.h\fP\&.
.SS "#define MAX_NUM_DECSLICES   16"

.PP
Definition at line \fB64\fP of file \fBdefines\&.h\fP\&.
.SS "#define MAX_NUM_DPB_LAYERS   2"

.PP
Definition at line \fB70\fP of file \fBdefines\&.h\fP\&.
.SS "#define MAX_NUM_SLICES   50"

.PP
Definition at line \fB61\fP of file \fBdefines\&.h\fP\&.
.SS "#define MAX_PLANE   3"

.PP
Definition at line \fB271\fP of file \fBdefines\&.h\fP\&.
.SS "#define MAX_QP   51"

.PP
Definition at line \fB201\fP of file \fBdefines\&.h\fP\&.
.SS "#define MAX_REFERENCE_PICTURES   32"

.PP
H\&.264 allows 32 fields\&. 
.PP
Definition at line \fB62\fP of file \fBdefines\&.h\fP\&.
.SS "#define MAX_VIEW_NUM   1024"

.PP
Definition at line \fB53\fP of file \fBdefines\&.h\fP\&.
.SS "#define MB_BLOCK_PARTITIONS   16"

.PP
Definition at line \fB109\fP of file \fBdefines\&.h\fP\&.
.SS "#define MB_BLOCK_SHIFT   4"

.PP
Definition at line \fB107\fP of file \fBdefines\&.h\fP\&.
.SS "#define MB_BLOCK_SIZE   16"

.PP
Definition at line \fB104\fP of file \fBdefines\&.h\fP\&.
.SS "#define MB_PIXELS   256"

.PP
Definition at line \fB105\fP of file \fBdefines\&.h\fP\&.
.SS "#define MB_PIXELS_SHIFT   8"

.PP
Definition at line \fB106\fP of file \fBdefines\&.h\fP\&.
.SS "#define MCBUF_CHROMA_PAD_X   16"

.PP
Definition at line \fB68\fP of file \fBdefines\&.h\fP\&.
.SS "#define MCBUF_CHROMA_PAD_Y   8"

.PP
Definition at line \fB69\fP of file \fBdefines\&.h\fP\&.
.SS "#define MCBUF_LUMA_PAD_X   32"

.PP
Definition at line \fB66\fP of file \fBdefines\&.h\fP\&.
.SS "#define MCBUF_LUMA_PAD_Y   12"

.PP
Definition at line \fB67\fP of file \fBdefines\&.h\fP\&.
.SS "#define MIN_QP   0"

.PP
Definition at line \fB200\fP of file \fBdefines\&.h\fP\&.
.SS "#define MVC_EXTENSION_ENABLE   1"

.PP
enable support for the Multiview High Profile 
.PP
Definition at line \fB49\fP of file \fBdefines\&.h\fP\&.
.SS "#define MVC_INIT_VIEW_ID   \-1"

.PP
Definition at line \fB52\fP of file \fBdefines\&.h\fP\&.
.SS "#define NO_INTRA_PMODE   9"

.PP
Definition at line \fB138\fP of file \fBdefines\&.h\fP\&.
.SS "#define NUM_BLOCK_TYPES   22"

.PP
Definition at line \fB91\fP of file \fBdefines\&.h\fP\&.
.SS "#define PAIR_FIELDS_IN_OUTPUT   0"

.PP
Pair field pictures for output purposes\&. 
.PP
Definition at line \fB38\fP of file \fBdefines\&.h\fP\&.
.SS "#define PRINTREFLIST   0"

.PP
Print ref list info for debug purposes\&. 
.PP
Definition at line \fB37\fP of file \fBdefines\&.h\fP\&.
.SS "#define Q_BITS   15"

.PP
Definition at line \fB186\fP of file \fBdefines\&.h\fP\&.
.SS "#define Q_BITS_8   16"

.PP
Definition at line \fB188\fP of file \fBdefines\&.h\fP\&.
.SS "#define RC_MAX_TEMPORAL_LEVELS   5"

.PP
Definition at line \fB266\fP of file \fBdefines\&.h\fP\&.
.SS "#define RUNBEFORE_NUM   7"

.PP
Definition at line \fB196\fP of file \fBdefines\&.h\fP\&.
.SS "#define RUNBEFORE_NUM_M1   6"

.PP
Definition at line \fB197\fP of file \fBdefines\&.h\fP\&.
.SS "#define SIMULCAST_ENABLE   0"

.PP
to test the decoder 
.PP
Definition at line \fB47\fP of file \fBdefines\&.h\fP\&.
.SS "#define SMB_BLOCK_SIZE   8"

.PP
Definition at line \fB102\fP of file \fBdefines\&.h\fP\&.
.SS "#define SSE_MEMORY_ALIGNMENT   16"

.PP
Definition at line \fB58\fP of file \fBdefines\&.h\fP\&.
.SS "#define TOTRUN_NUM   15"

.PP
Definition at line \fB195\fP of file \fBdefines\&.h\fP\&.
.SS "#define TRACE   0"

.PP
0:Trace off 1:Trace on 2:detailed CABAC context information 
.PP
Definition at line \fB29\fP of file \fBdefines\&.h\fP\&.
.SS "#define VERSION   '19\&.0'"

.PP
Definition at line \fB33\fP of file \fBdefines\&.h\fP\&.
.SS "#define ZEROBYTES_SHORTSTARTCODE   2"

.PP
Definition at line \fB269\fP of file \fBdefines\&.h\fP\&.
.SS "#define ZEROSNR   0"

.PP
PSNR computation method\&. 
.PP
Definition at line \fB42\fP of file \fBdefines\&.h\fP\&.
.SH "Enumeration Type Documentation"
.PP 
.SS "anonymous enum"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIEOS \fP\fP
End Of Sequence\&. 
.TP
\fB\fISOP \fP\fP
Start Of Picture\&. 
.TP
\fB\fISOS \fP\fP
Start Of Slice\&. 
.TP
\fB\fISOS_CONT \fP\fP
.PP
Definition at line \fB242\fP of file \fBdefines\&.h\fP\&.
.SS "anonymous enum"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIDECODING_OK \fP\fP
.TP
\fB\fISEARCH_SYNC \fP\fP
.TP
\fB\fIPICTURE_DECODED \fP\fP
.PP
Definition at line \fB257\fP of file \fBdefines\&.h\fP\&.
.SS "enum \fBCABACBlockTypes\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fILUMA_16DC \fP\fP
.TP
\fB\fILUMA_16AC \fP\fP
.TP
\fB\fILUMA_8x8 \fP\fP
.TP
\fB\fILUMA_8x4 \fP\fP
.TP
\fB\fILUMA_4x8 \fP\fP
.TP
\fB\fILUMA_4x4 \fP\fP
.TP
\fB\fICHROMA_DC \fP\fP
.TP
\fB\fICHROMA_AC \fP\fP
.TP
\fB\fICHROMA_DC_2x4 \fP\fP
.TP
\fB\fICHROMA_DC_4x4 \fP\fP
.TP
\fB\fICB_16DC \fP\fP
.TP
\fB\fICB_16AC \fP\fP
.TP
\fB\fICB_8x8 \fP\fP
.TP
\fB\fICB_8x4 \fP\fP
.TP
\fB\fICB_4x8 \fP\fP
.TP
\fB\fICB_4x4 \fP\fP
.TP
\fB\fICR_16DC \fP\fP
.TP
\fB\fICR_16AC \fP\fP
.TP
\fB\fICR_8x8 \fP\fP
.TP
\fB\fICR_8x4 \fP\fP
.TP
\fB\fICR_4x8 \fP\fP
.TP
\fB\fICR_4x4 \fP\fP
.PP
Definition at line \fB160\fP of file \fBdefines\&.h\fP\&.
.SS "enum \fBCAVLCBlockTypes\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fILUMA \fP\fP
.TP
\fB\fILUMA_INTRA16x16DC \fP\fP
.TP
\fB\fILUMA_INTRA16x16AC \fP\fP
.TP
\fB\fICB \fP\fP
.TP
\fB\fICB_INTRA16x16DC \fP\fP
.TP
\fB\fICB_INTRA16x16AC \fP\fP
.TP
\fB\fICR \fP\fP
.TP
\fB\fICR_INTRA16x16DC \fP\fP
.TP
\fB\fICR_INTRA16x16AC \fP\fP
.PP
Definition at line \fB147\fP of file \fBdefines\&.h\fP\&.
.SS "enum \fBColorComponent\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIY_COMP \fP\fP
.TP
\fB\fIU_COMP \fP\fP
.TP
\fB\fIV_COMP \fP\fP
.TP
\fB\fIR_COMP \fP\fP
.TP
\fB\fIG_COMP \fP\fP
.TP
\fB\fIB_COMP \fP\fP
.TP
\fB\fIT_COMP \fP\fP
.PP
Definition at line \fB232\fP of file \fBdefines\&.h\fP\&.
.SS "enum \fBDirectModes\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIDIR_TEMPORAL \fP\fP
Temporal Direct Mode\&. 
.TP
\fB\fIDIR_SPATIAL \fP\fP
Spatial Direct Mode\&. 
.PP
Definition at line \fB141\fP of file \fBdefines\&.h\fP\&.
.SS "enum \fBI16x16PredModes\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIVERT_PRED_16 \fP\fP
.TP
\fB\fIHOR_PRED_16 \fP\fP
.TP
\fB\fIDC_PRED_16 \fP\fP
.TP
\fB\fIPLANE_16 \fP\fP
.PP
Definition at line \fB216\fP of file \fBdefines\&.h\fP\&.
.SS "enum \fBI4x4PredModes\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIVERT_PRED \fP\fP
.TP
\fB\fIHOR_PRED \fP\fP
.TP
\fB\fIDC_PRED \fP\fP
.TP
\fB\fIDIAG_DOWN_LEFT_PRED \fP\fP
.TP
\fB\fIDIAG_DOWN_RIGHT_PRED \fP\fP
.TP
\fB\fIVERT_RIGHT_PRED \fP\fP
.TP
\fB\fIHOR_DOWN_PRED \fP\fP
.TP
\fB\fIVERT_LEFT_PRED \fP\fP
.TP
\fB\fIHOR_UP_PRED \fP\fP
.PP
Definition at line \fB203\fP of file \fBdefines\&.h\fP\&.
.SS "enum \fBI8x8PredModes\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIDC_PRED_8 \fP\fP
.TP
\fB\fIHOR_PRED_8 \fP\fP
.TP
\fB\fIVERT_PRED_8 \fP\fP
.TP
\fB\fIPLANE_8 \fP\fP
.PP
Definition at line \fB224\fP of file \fBdefines\&.h\fP\&.
.SS "enum \fBMBModeTypes\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIPSKIP \fP\fP
.TP
\fB\fIBSKIP_DIRECT \fP\fP
.TP
\fB\fIP16x16 \fP\fP
.TP
\fB\fIP16x8 \fP\fP
.TP
\fB\fIP8x16 \fP\fP
.TP
\fB\fISMB8x8 \fP\fP
.TP
\fB\fISMB8x4 \fP\fP
.TP
\fB\fISMB4x8 \fP\fP
.TP
\fB\fISMB4x4 \fP\fP
.TP
\fB\fIP8x8 \fP\fP
.TP
\fB\fII4MB \fP\fP
.TP
\fB\fII16MB \fP\fP
.TP
\fB\fIIBLOCK \fP\fP
.TP
\fB\fISI4MB \fP\fP
.TP
\fB\fII8MB \fP\fP
.TP
\fB\fIIPCM \fP\fP
.TP
\fB\fIMAXMODE \fP\fP
.PP
Definition at line \fB117\fP of file \fBdefines\&.h\fP\&.
.SS "enum \fBMVPredTypes\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIMVPRED_MEDIAN \fP\fP
.TP
\fB\fIMVPRED_L \fP\fP
.TP
\fB\fIMVPRED_U \fP\fP
.TP
\fB\fIMVPRED_UR \fP\fP
.PP
Definition at line \fB250\fP of file \fBdefines\&.h\fP\&.
.SS "enum \fBProfileIDC\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fINO_PROFILE \fP\fP
disable profile checking for experimental coding (enables FRExt, but disables MV) 
.TP
\fB\fIFREXT_CAVLC444 \fP\fP
YUV 4:4:4/14 'CAVLC 4:4:4'\&. 
.TP
\fB\fIBASELINE \fP\fP
YUV 4:2:0/8 'Baseline'\&. 
.TP
\fB\fIMAIN \fP\fP
YUV 4:2:0/8 'Main'\&. 
.TP
\fB\fIEXTENDED \fP\fP
YUV 4:2:0/8 'Extended'\&. 
.TP
\fB\fIFREXT_HP \fP\fP
YUV 4:2:0/8 'High'\&. 
.TP
\fB\fIFREXT_Hi10P \fP\fP
YUV 4:2:0/10 'High 10'\&. 
.TP
\fB\fIFREXT_Hi422 \fP\fP
YUV 4:2:2/10 'High 4:2:2'\&. 
.TP
\fB\fIFREXT_Hi444 \fP\fP
YUV 4:4:4/14 'High 4:4:4'\&. 
.TP
\fB\fIMVC_HIGH \fP\fP
YUV 4:2:0/8 'Multiview High'\&. 
.TP
\fB\fISTEREO_HIGH \fP\fP
YUV 4:2:0/8 'Stereo High'\&. 
.PP
Definition at line \fB73\fP of file \fBdefines\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
