.TH "deps/base_vvc/minimum_VTM/source/Lib/CommonLib/DepQuant.cpp" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deps/base_vvc/minimum_VTM/source/Lib/CommonLib/DepQuant.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'DepQuant\&.h'\fP
.br
\fC#include 'TrQuant\&.h'\fP
.br
\fC#include 'CodingStructure\&.h'\fP
.br
\fC#include 'UnitTools\&.h'\fP
.br
\fC#include <bitset>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBDQIntern::NbInfoSbb\fP"
.br
.ti -1c
.RI "struct \fBDQIntern::NbInfoOut\fP"
.br
.ti -1c
.RI "struct \fBDQIntern::CoeffFracBits\fP"
.br
.ti -1c
.RI "struct \fBDQIntern::ScanInfo\fP"
.br
.ti -1c
.RI "struct \fBDQIntern::TUParameters\fP"
.br
.ti -1c
.RI "class \fBDQIntern::Rom\fP"
.br
.ti -1c
.RI "class \fBDQIntern::RateEstimator\fP"
.br
.ti -1c
.RI "struct \fBDQIntern::PQData\fP"
.br
.ti -1c
.RI "struct \fBDQIntern::Decision\fP"
.br
.ti -1c
.RI "class \fBDQIntern::Quantizer\fP"
.br
.ti -1c
.RI "struct \fBDQIntern::SbbCtx\fP"
.br
.ti -1c
.RI "class \fBDQIntern::CommonCtx\fP"
.br
.ti -1c
.RI "class \fBDQIntern::State\fP"
.br
.ti -1c
.RI "class \fBDQIntern::DepQuant\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBDQIntern\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBRICEMAX\fP   32"
.br
.ti -1c
.RI "#define \fBUPDATE\fP(k)   {TCoeff t=levels[scanInfo\&.nextNbInfoSbb\&.inPos[k]]; sumAbs1+=std::min<TCoeff>(4+(t&1),t); sumNum+=!!t; }"
.br
.ti -1c
.RI "#define \fBUPDATE\fP(k)   {TCoeff t=levels[scanInfo\&.nextNbInfoSbb\&.inPos[k]]; sumAbs+=t; }"
.br
.ti -1c
.RI "#define \fBUPDATE\fP(k)   {TCoeff t=levels[scanInfo\&.nextNbInfoSbb\&.inPos[k]]; sumAbs+=t; }"
.br
.ti -1c
.RI "#define \fBUPDATE\fP(k)   {TCoeff t=absLevels[nbOut\->outPos[k]]; sumAbs+=t; sumAbs1+=std::min<TCoeff>(4+(t&1),t); sumNum+=!!t; }"
.br
.ti -1c
.RI "#define \fBTINIT\fP(x)   {*this,m_commonCtx,x}"
.br
.ti -1c
.RI "#define \fBDINIT\fP(l,  p)   {std::numeric_limits<int64_t>::max()>>2,l,p}"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBDQIntern::ScanPosType\fP { \fBDQIntern::SCAN_ISCSBB\fP = 0, \fBDQIntern::SCAN_SOCSBB\fP = 1, \fBDQIntern::SCAN_EOCSBB\fP = 2 }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBDQIntern::ceil_log2\fP (uint64_t x)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const int32_t \fBDQIntern::g_goRiceBits\fP [4][\fBRICEMAX\fP]"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define DINIT(l, p)   {std::numeric_limits<int64_t>::max()>>2,l,p}"

.PP
Definition at line \fB1328\fP of file \fBDepQuant\&.cpp\fP\&.
.SS "#define RICEMAX   32"

.PP
Definition at line \fB846\fP of file \fBDepQuant\&.cpp\fP\&.
.SS "#define TINIT(x)   {*this,m_commonCtx,x}"

.PP
Definition at line \fB1309\fP of file \fBDepQuant\&.cpp\fP\&.
.SS "#define UPDATE(k)   {TCoeff t=levels[scanInfo\&.nextNbInfoSbb\&.inPos[k]]; sumAbs1+=std::min<TCoeff>(4+(t&1),t); sumNum+=!!t; }"

.SS "#define UPDATE(k)   {TCoeff t=levels[scanInfo\&.nextNbInfoSbb\&.inPos[k]]; sumAbs+=t; }"

.SS "#define UPDATE(k)   {TCoeff t=levels[scanInfo\&.nextNbInfoSbb\&.inPos[k]]; sumAbs+=t; }"

.SS "#define UPDATE(k)   {TCoeff t=absLevels[nbOut\->outPos[k]]; sumAbs+=t; sumAbs1+=std::min<TCoeff>(4+(t&1),t); sumNum+=!!t; }"

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
