.TH "deps/base_vvc/minimum_VTM/source/Lib/CommonLib/DepQuant.h" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deps/base_vvc/minimum_VTM/source/Lib/CommonLib/DepQuant.h
.SH SYNOPSIS
.br
.PP
\fC#include 'CommonDef\&.h'\fP
.br
\fC#include 'Contexts\&.h'\fP
.br
\fC#include 'Slice\&.h'\fP
.br
\fC#include 'Unit\&.h'\fP
.br
\fC#include 'UnitPartitioner\&.h'\fP
.br
\fC#include 'QuantRDOQ\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBvtm::DepQuant\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBvtm\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB__DEPQUANT__\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define __DEPQUANT__"

.PP
Definition at line \fB37\fP of file \fBDepQuant\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
