.TH "util/src/Diagnostics.cpp" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
util/src/Diagnostics.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'Diagnostics\&.hpp'\fP
.br
\fC#include <cstdarg>\fP
.br
\fC#include <cstdio>\fP
.br
\fC#include <sstream>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBlctm\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::string \fBlctm::format\fP (const char *fmt,\&.\&.\&.)"
.br
.ti -1c
.RI "std::string \fBlctm::join\fP (const std::vector< std::string > &list, const std::string &seperator, bool include_trailing=false)"
.br
.ti -1c
.RI "void \fBlctm::_check_failed\fP (const char *file, int line, const char *func, const std::string &message)"
.br
.ti -1c
.RI "void \fBlctm::_raise\fP (const char *file, int line, const char *func, const std::string &message)"
.br
.ti -1c
.RI "void \fBlctm::_log\fP (const char *file, int line, const char *func, const std::string &message)"
.br
.ti -1c
.RI "void \fBlctm::_log_report\fP (const std::string &message)"
.br
.ti -1c
.RI "std::string \fBlctm::hex_dump\fP (const uint8_t *data, uint64_t size, unsigned int offset)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
