.TH "util/include/Diagnostics.hpp" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
util/include/Diagnostics.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <cstdio>\fP
.br
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBlctm\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCHECK\fP(expr)   \fBlctm::_check\fP(expr, __FILE__, __LINE__, __FUNCTION__, #expr)"
.br
.ti -1c
.RI "#define \fBDBG\fP(fmt, \&.\&.\&.)   \fBlctm::_log\fP(__FILE__, __LINE__, __FUNCTION__, \fBlctm::format\fP(fmt, ##__VA_ARGS__))"
.br
.ti -1c
.RI "#define \fBINFO\fP(fmt, \&.\&.\&.)   \fBlctm::_log\fP(__FILE__, __LINE__, __FUNCTION__, \fBlctm::format\fP(fmt, ##__VA_ARGS__))"
.br
.ti -1c
.RI "#define \fBWARN\fP(fmt, \&.\&.\&.)   \fBlctm::_log\fP(__FILE__, __LINE__, __FUNCTION__, \fBlctm::format\fP(fmt, ##__VA_ARGS__))"
.br
.ti -1c
.RI "#define \fBREPORT\fP(fmt, \&.\&.\&.)   \fBlctm::_log_report\fP(\fBlctm::format\fP(fmt, ##__VA_ARGS__))"
.br
.ti -1c
.RI "#define \fBERR\fP(fmt, \&.\&.\&.)"
.br
.ti -1c
.RI "#define \fBFATAL\fP(fmt, \&.\&.\&.)"
.br
.ti -1c
.RI "#define \fBD\fP(fmt, \&.\&.\&.)   ::fprintf(stderr, fmt '\\n', ##__VA_ARGS__)"
.br
.ti -1c
.RI "#define \fBTRACE\fP(fmt, \&.\&.\&.)   ((void)(0))"
.br
.ti -1c
.RI "#define \fBTRACE_PIXEL\fP(fmt, \&.\&.\&.)   ((void)(0))"
.br
.ti -1c
.RI "#define \fBTRACE_SURFACE\fP(surface)   ((void)(0))"
.br
.ti -1c
.RI "#define \fBTRACE_HUFFMAN\fP(fmt, \&.\&.\&.)   ((void)(0))"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::string \fBlctm::format\fP (const char *fmt,\&.\&.\&.)"
.br
.ti -1c
.RI "std::string \fBlctm::hex_dump\fP (const uint8_t *data, uint64_t size, unsigned int offset)"
.br
.ti -1c
.RI "std::string \fBlctm::join\fP (const std::vector< std::string > &list, const std::string &seperator, bool include_trailing=false)"
.br
.ti -1c
.RI "void \fBlctm::_check_failed\fP (const char *file, int line, const char *func, const std::string &message)"
.br
.ti -1c
.RI "template<typename T > T \fBlctm::_check\fP (T c, const char *file, int line, const char *func, const char *expr)"
.br
.ti -1c
.RI "void \fBlctm::_log\fP (const char *file, int line, const char *func, const std::string &message)"
.br
.ti -1c
.RI "void \fBlctm::_log_report\fP (const std::string &message)"
.br
.ti -1c
.RI "void \fBlctm::_raise\fP (const char *file, int line, const char *func, const std::string &message)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define CHECK(expr)   \fBlctm::_check\fP(expr, __FILE__, __LINE__, __FUNCTION__, #expr)"

.PP
Definition at line \fB67\fP of file \fBDiagnostics\&.hpp\fP\&.
.SS "#define D(fmt,  \&.\&.\&.)   ::fprintf(stderr, fmt '\\n', ##__VA_ARGS__)"

.PP
Definition at line \fB114\fP of file \fBDiagnostics\&.hpp\fP\&.
.SS "#define DBG(fmt,  \&.\&.\&.)   \fBlctm::_log\fP(__FILE__, __LINE__, __FUNCTION__, \fBlctm::format\fP(fmt, ##__VA_ARGS__))"

.PP
Definition at line \fB86\fP of file \fBDiagnostics\&.hpp\fP\&.
.SS "#define ERR(fmt,  \&.\&.\&.)"
\fBValue:\fP.PP
.nf
    do {                                                                                                                           \\
        std::string msg(lctm::format("Error " fmt, ##__VA_ARGS__));                                                                \\
        lctm::_log(__FILE__, __LINE__, __FUNCTION__, msg);                                                                         \\
        lctm::_raise(__FILE__, __LINE__, __FUNCTION__, msg);                                                                       \\
    } while (0)
.fi

.PP
Definition at line \fB93\fP of file \fBDiagnostics\&.hpp\fP\&.
.SS "#define FATAL(fmt,  \&.\&.\&.)"
\fBValue:\fP.PP
.nf
    do {                                                                                                                           \\
        std::string msg(lctm::format("Fatal " fmt, ##__VA_ARGS__));                                                                \\
        lctm::_log(__FILE__, __LINE__, __FUNCTION__, msg);                                                                         \\
        lctm::_raise(__FILE__, __LINE__, __FUNCTION__, msg);                                                                       \\
    } while (0)
.fi

.PP
Definition at line \fB100\fP of file \fBDiagnostics\&.hpp\fP\&.
.SS "#define INFO(fmt,  \&.\&.\&.)   \fBlctm::_log\fP(__FILE__, __LINE__, __FUNCTION__, \fBlctm::format\fP(fmt, ##__VA_ARGS__))"

.PP
Definition at line \fB89\fP of file \fBDiagnostics\&.hpp\fP\&.
.SS "#define REPORT(fmt,  \&.\&.\&.)   \fBlctm::_log_report\fP(\fBlctm::format\fP(fmt, ##__VA_ARGS__))"

.PP
Definition at line \fB91\fP of file \fBDiagnostics\&.hpp\fP\&.
.SS "#define TRACE(fmt,  \&.\&.\&.)   ((void)(0))"

.PP
Definition at line \fB131\fP of file \fBDiagnostics\&.hpp\fP\&.
.SS "#define TRACE_HUFFMAN(fmt,  \&.\&.\&.)   ((void)(0))"

.PP
Definition at line \fB160\fP of file \fBDiagnostics\&.hpp\fP\&.
.SS "#define TRACE_PIXEL(fmt,  \&.\&.\&.)   ((void)(0))"

.PP
Definition at line \fB137\fP of file \fBDiagnostics\&.hpp\fP\&.
.SS "#define TRACE_SURFACE(surface)   ((void)(0))"

.PP
Definition at line \fB154\fP of file \fBDiagnostics\&.hpp\fP\&.
.SS "#define WARN(fmt,  \&.\&.\&.)   \fBlctm::_log\fP(__FILE__, __LINE__, __FUNCTION__, \fBlctm::format\fP(fmt, ##__VA_ARGS__))"

.PP
Definition at line \fB90\fP of file \fBDiagnostics\&.hpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
