.TH "decoder/include/Dithering.hpp" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
decoder/include/Dithering.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'Component\&.hpp'\fP
.br
\fC#include 'Surface\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBlctm::Dithering\fP"
.br
.ti -1c
.RI "class \fBlctm::Random\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBlctm\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBDITHER_BUFFER_SIZE\fP   (64 * 1024)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define DITHER_BUFFER_SIZE   (64 * 1024)"

.PP
Definition at line \fB46\fP of file \fBDithering\&.hpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
