.TH "encoder/src/Downsampling.cpp" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
encoder/src/Downsampling.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'Downsampling\&.hpp'\fP
.br
\fC#include 'Convert\&.hpp'\fP
.br
\fC#include 'Misc\&.hpp'\fP
.br
\fC#include <algorithm>\fP
.br
\fC#include <vector>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBlctm::DownsampleKernel\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBlctm\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBImage\fP \fBlctm::DownsampleImage\fP (const \fBImage\fP &src, \fBDownsample\fP downsample_luma, \fBDownsample\fP downsample_chroma, \fBScalingMode\fP scaling_mode, unsigned dst_bit_depth=0)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
