.TH "DQIntern::Decision" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DQIntern::Decision
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int64_t \fBrdCost\fP"
.br
.ti -1c
.RI "TCoeff \fBabsLevel\fP"
.br
.ti -1c
.RI "int \fBprevId\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB610\fP of file \fBDepQuant\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "TCoeff DQIntern::Decision::absLevel"

.PP
Definition at line \fB613\fP of file \fBDepQuant\&.cpp\fP\&.
.SS "int DQIntern::Decision::prevId"

.PP
Definition at line \fB614\fP of file \fBDepQuant\&.cpp\fP\&.
.SS "int64_t DQIntern::Decision::rdCost"

.PP
Definition at line \fB612\fP of file \fBDepQuant\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
