.TH "DQIntern::ScanInfo" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DQIntern::ScanInfo
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBScanInfo\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBsbbSize\fP"
.br
.ti -1c
.RI "int \fBnumSbb\fP"
.br
.ti -1c
.RI "int \fBscanIdx\fP"
.br
.ti -1c
.RI "int \fBrasterPos\fP"
.br
.ti -1c
.RI "int \fBsbbPos\fP"
.br
.ti -1c
.RI "int \fBinsidePos\fP"
.br
.ti -1c
.RI "bool \fBeosbb\fP"
.br
.ti -1c
.RI "\fBScanPosType\fP \fBspt\fP"
.br
.ti -1c
.RI "unsigned \fBsigCtxOffsetNext\fP"
.br
.ti -1c
.RI "unsigned \fBgtxCtxOffsetNext\fP"
.br
.ti -1c
.RI "int \fBnextInsidePos\fP"
.br
.ti -1c
.RI "\fBNbInfoSbb\fP \fBnextNbInfoSbb\fP"
.br
.ti -1c
.RI "int \fBnextSbbRight\fP"
.br
.ti -1c
.RI "int \fBnextSbbBelow\fP"
.br
.ti -1c
.RI "int \fBposX\fP"
.br
.ti -1c
.RI "int \fBposY\fP"
.br
.ti -1c
.RI "ChannelType \fBchType\fP"
.br
.ti -1c
.RI "int \fBsbtInfo\fP"
.br
.ti -1c
.RI "int \fBtuWidth\fP"
.br
.ti -1c
.RI "int \fBtuHeight\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB73\fP of file \fBDepQuant\&.cpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "DQIntern::ScanInfo::ScanInfo ()\fC [inline]\fP"

.PP
Definition at line \fB75\fP of file \fBDepQuant\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "ChannelType DQIntern::ScanInfo::chType"

.PP
Definition at line \fB92\fP of file \fBDepQuant\&.cpp\fP\&.
.SS "bool DQIntern::ScanInfo::eosbb"

.PP
Definition at line \fB82\fP of file \fBDepQuant\&.cpp\fP\&.
.SS "unsigned DQIntern::ScanInfo::gtxCtxOffsetNext"

.PP
Definition at line \fB85\fP of file \fBDepQuant\&.cpp\fP\&.
.SS "int DQIntern::ScanInfo::insidePos"

.PP
Definition at line \fB81\fP of file \fBDepQuant\&.cpp\fP\&.
.SS "int DQIntern::ScanInfo::nextInsidePos"

.PP
Definition at line \fB86\fP of file \fBDepQuant\&.cpp\fP\&.
.SS "\fBNbInfoSbb\fP DQIntern::ScanInfo::nextNbInfoSbb"

.PP
Definition at line \fB87\fP of file \fBDepQuant\&.cpp\fP\&.
.SS "int DQIntern::ScanInfo::nextSbbBelow"

.PP
Definition at line \fB89\fP of file \fBDepQuant\&.cpp\fP\&.
.SS "int DQIntern::ScanInfo::nextSbbRight"

.PP
Definition at line \fB88\fP of file \fBDepQuant\&.cpp\fP\&.
.SS "int DQIntern::ScanInfo::numSbb"

.PP
Definition at line \fB77\fP of file \fBDepQuant\&.cpp\fP\&.
.SS "int DQIntern::ScanInfo::posX"

.PP
Definition at line \fB90\fP of file \fBDepQuant\&.cpp\fP\&.
.SS "int DQIntern::ScanInfo::posY"

.PP
Definition at line \fB91\fP of file \fBDepQuant\&.cpp\fP\&.
.SS "int DQIntern::ScanInfo::rasterPos"

.PP
Definition at line \fB79\fP of file \fBDepQuant\&.cpp\fP\&.
.SS "int DQIntern::ScanInfo::sbbPos"

.PP
Definition at line \fB80\fP of file \fBDepQuant\&.cpp\fP\&.
.SS "int DQIntern::ScanInfo::sbbSize"

.PP
Definition at line \fB76\fP of file \fBDepQuant\&.cpp\fP\&.
.SS "int DQIntern::ScanInfo::sbtInfo"

.PP
Definition at line \fB93\fP of file \fBDepQuant\&.cpp\fP\&.
.SS "int DQIntern::ScanInfo::scanIdx"

.PP
Definition at line \fB78\fP of file \fBDepQuant\&.cpp\fP\&.
.SS "unsigned DQIntern::ScanInfo::sigCtxOffsetNext"

.PP
Definition at line \fB84\fP of file \fBDepQuant\&.cpp\fP\&.
.SS "\fBScanPosType\fP DQIntern::ScanInfo::spt"

.PP
Definition at line \fB83\fP of file \fBDepQuant\&.cpp\fP\&.
.SS "int DQIntern::ScanInfo::tuHeight"

.PP
Definition at line \fB95\fP of file \fBDepQuant\&.cpp\fP\&.
.SS "int DQIntern::ScanInfo::tuWidth"

.PP
Definition at line \fB94\fP of file \fBDepQuant\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
