.TH "DQIntern::Quantizer" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DQIntern::Quantizer
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBQuantizer\fP ()"
.br
.ti -1c
.RI "void \fBdequantBlock\fP (const TransformUnit &tu, const ComponentID compID, const QpParam &cQP, CoeffBuf &recCoeff, bool enableScalingLists, int *piDequantCoef) const"
.br
.ti -1c
.RI "void \fBinitQuantBlock\fP (const TransformUnit &tu, const ComponentID compID, const QpParam &cQP, const double lambda, int gValue)"
.br
.ti -1c
.RI "void \fBpreQuantCoeff\fP (const TCoeff absCoeff, \fBPQData\fP *pqData, TCoeff quanCoeff) const"
.br
.ti -1c
.RI "TCoeff \fBgetLastThreshold\fP () const"
.br
.ti -1c
.RI "TCoeff \fBgetSSbbThreshold\fP () const"
.br
.ti -1c
.RI "int64_t \fBgetQScale\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB626\fP of file \fBDepQuant\&.cpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "DQIntern::Quantizer::Quantizer ()\fC [inline]\fP"

.PP
Definition at line \fB629\fP of file \fBDepQuant\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void DQIntern::Quantizer::dequantBlock (const TransformUnit & tu, const ComponentID compID, const QpParam & cQP, CoeffBuf & recCoeff, bool enableScalingLists, int * piDequantCoef) const"

.PP
Definition at line \fB705\fP of file \fBDepQuant\&.cpp\fP\&.
.SS "TCoeff DQIntern::Quantizer::getLastThreshold () const\fC [inline]\fP"

.PP
Definition at line \fB633\fP of file \fBDepQuant\&.cpp\fP\&.
.SS "int64_t DQIntern::Quantizer::getQScale () const\fC [inline]\fP"

.PP
Definition at line \fB636\fP of file \fBDepQuant\&.cpp\fP\&.
.SS "TCoeff DQIntern::Quantizer::getSSbbThreshold () const\fC [inline]\fP"

.PP
Definition at line \fB634\fP of file \fBDepQuant\&.cpp\fP\&.
.SS "void DQIntern::Quantizer::initQuantBlock (const TransformUnit & tu, const ComponentID compID, const QpParam & cQP, const double lambda, int gValue = \fC\-1\fP)"

.PP
Definition at line \fB666\fP of file \fBDepQuant\&.cpp\fP\&.
.SS "void DQIntern::Quantizer::preQuantCoeff (const TCoeff absCoeff, \fBPQData\fP * pqData, TCoeff quanCoeff) const\fC [inline]\fP"

.PP
Definition at line \fB772\fP of file \fBDepQuant\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
