.TH "DQIntern::DepQuant" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DQIntern::DepQuant
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBDQIntern::RateEstimator\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDepQuant\fP ()"
.br
.ti -1c
.RI "void \fBquant\fP (TransformUnit &tu, const CCoeffBuf &srcCoeff, const ComponentID compID, const QpParam &cQP, const double lambda, const Ctx &ctx, TCoeff &absSum, bool enableScalingLists, int *quantCoeff)"
.br
.ti -1c
.RI "void \fBdequant\fP (const TransformUnit &tu, CoeffBuf &recCoeff, const ComponentID compID, const QpParam &cQP, bool enableScalingLists, int *quantCoeff)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB1285\fP of file \fBDepQuant\&.cpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "DQIntern::DepQuant::DepQuant ()"

.PP
Definition at line \fB1310\fP of file \fBDepQuant\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void DQIntern::DepQuant::dequant (const TransformUnit & tu, CoeffBuf & recCoeff, const ComponentID compID, const QpParam & cQP, bool enableScalingLists, int * quantCoeff)"

.PP
Definition at line \fB1322\fP of file \fBDepQuant\&.cpp\fP\&.
.SS "void DQIntern::DepQuant::quant (TransformUnit & tu, const CCoeffBuf & srcCoeff, const ComponentID compID, const QpParam & cQP, const double lambda, const Ctx & ctx, TCoeff & absSum, bool enableScalingLists, int * quantCoeff)"

.PP
Definition at line \fB1436\fP of file \fBDepQuant\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
