.TH "DQIntern::Rom" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DQIntern::Rom
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRom\fP ()"
.br
.ti -1c
.RI "\fB~Rom\fP ()"
.br
.ti -1c
.RI "void \fBinit\fP ()"
.br
.ti -1c
.RI "const \fBNbInfoSbb\fP * \fBgetNbInfoSbb\fP (int hd, int vd) const"
.br
.ti -1c
.RI "const \fBNbInfoOut\fP * \fBgetNbInfoOut\fP (int hd, int vd) const"
.br
.ti -1c
.RI "const \fBTUParameters\fP * \fBgetTUPars\fP (const CompArea &area, const ComponentID compID) const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB129\fP of file \fBDepQuant\&.cpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "DQIntern::Rom::Rom ()\fC [inline]\fP"

.PP
Definition at line \fB132\fP of file \fBDepQuant\&.cpp\fP\&.
.SS "DQIntern::Rom::~Rom ()\fC [inline]\fP"

.PP
Definition at line \fB133\fP of file \fBDepQuant\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "const \fBNbInfoOut\fP * DQIntern::Rom::getNbInfoOut (int hd, int vd) const\fC [inline]\fP"

.PP
Definition at line \fB136\fP of file \fBDepQuant\&.cpp\fP\&.
.SS "const \fBNbInfoSbb\fP * DQIntern::Rom::getNbInfoSbb (int hd, int vd) const\fC [inline]\fP"

.PP
Definition at line \fB135\fP of file \fBDepQuant\&.cpp\fP\&.
.SS "const \fBTUParameters\fP * DQIntern::Rom::getTUPars (const CompArea & area, const ComponentID compID) const\fC [inline]\fP"

.PP
Definition at line \fB137\fP of file \fBDepQuant\&.cpp\fP\&.
.SS "void DQIntern::Rom::init ()\fC [inline]\fP"

.PP
Definition at line \fB134\fP of file \fBDepQuant\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
