.TH "DQIntern::CommonCtx" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DQIntern::CommonCtx
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCommonCtx\fP ()"
.br
.ti -1c
.RI "void \fBswap\fP ()"
.br
.ti -1c
.RI "void \fBreset\fP (const \fBTUParameters\fP &tuPars, const \fBRateEstimator\fP &rateEst)"
.br
.ti -1c
.RI "void \fBupdate\fP (const \fBScanInfo\fP &scanInfo, const \fBState\fP *prevState, \fBState\fP &currState)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB814\fP of file \fBDepQuant\&.cpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "DQIntern::CommonCtx::CommonCtx ()\fC [inline]\fP"

.PP
Definition at line \fB817\fP of file \fBDepQuant\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void DQIntern::CommonCtx::reset (const \fBTUParameters\fP & tuPars, const \fBRateEstimator\fP & rateEst)\fC [inline]\fP"

.PP
Definition at line \fB821\fP of file \fBDepQuant\&.cpp\fP\&.
.SS "void DQIntern::CommonCtx::swap ()\fC [inline]\fP"

.PP
Definition at line \fB819\fP of file \fBDepQuant\&.cpp\fP\&.
.SS "void DQIntern::CommonCtx::update (const \fBScanInfo\fP & scanInfo, const \fBState\fP * prevState, \fBState\fP & currState)\fC [inline]\fP"

.PP
Definition at line \fB1206\fP of file \fBDepQuant\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
