.TH "DQIntern::NbInfoOut" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DQIntern::NbInfoOut
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint16_t \fBmaxDist\fP"
.br
.ti -1c
.RI "uint16_t \fBnum\fP"
.br
.ti -1c
.RI "uint16_t \fBoutPos\fP [5]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB59\fP of file \fBDepQuant\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "uint16_t DQIntern::NbInfoOut::maxDist"

.PP
Definition at line \fB61\fP of file \fBDepQuant\&.cpp\fP\&.
.SS "uint16_t DQIntern::NbInfoOut::num"

.PP
Definition at line \fB62\fP of file \fBDepQuant\&.cpp\fP\&.
.SS "uint16_t DQIntern::NbInfoOut::outPos[5]"

.PP
Definition at line \fB63\fP of file \fBDepQuant\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
