.TH "DQIntern::PQData" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DQIntern::PQData
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "TCoeff \fBabsLevel\fP"
.br
.ti -1c
.RI "int64_t \fBdeltaDist\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB603\fP of file \fBDepQuant\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "TCoeff DQIntern::PQData::absLevel"

.PP
Definition at line \fB605\fP of file \fBDepQuant\&.cpp\fP\&.
.SS "int64_t DQIntern::PQData::deltaDist"

.PP
Definition at line \fB606\fP of file \fBDepQuant\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
