.TH "DQIntern::State" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DQIntern::State
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBState\fP (const \fBRateEstimator\fP &rateEst, \fBCommonCtx\fP &commonCtx, const int stateId)"
.br
.ti -1c
.RI "template<uint8_t numIPos> void \fBupdateState\fP (const \fBScanInfo\fP &scanInfo, const \fBState\fP *prevStates, const \fBDecision\fP &decision)"
.br
.ti -1c
.RI "void \fBupdateStateEOS\fP (const \fBScanInfo\fP &scanInfo, const \fBState\fP *prevStates, const \fBState\fP *skipStates, const \fBDecision\fP &decision)"
.br
.ti -1c
.RI "void \fBinit\fP ()"
.br
.ti -1c
.RI "void \fBcheckRdCosts\fP (const \fBScanPosType\fP spt, const \fBPQData\fP &pqDataA, const \fBPQData\fP &pqDataB, \fBDecision\fP &decisionA, \fBDecision\fP &decisionB) const"
.br
.ti -1c
.RI "void \fBcheckRdCostStart\fP (int32_t lastOffset, const \fBPQData\fP &pqData, \fBDecision\fP &decision) const"
.br
.ti -1c
.RI "void \fBcheckRdCostSkipSbb\fP (\fBDecision\fP &decision) const"
.br
.ti -1c
.RI "void \fBcheckRdCostSkipSbbZeroOut\fP (\fBDecision\fP &decision) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned \fBeffWidth\fP"
.br
.ti -1c
.RI "unsigned \fBeffHeight\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBCommonCtx\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB855\fP of file \fBDepQuant\&.cpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "DQIntern::State::State (const \fBRateEstimator\fP & rateEst, \fBCommonCtx\fP & commonCtx, const int stateId)"

.PP
Definition at line \fB1008\fP of file \fBDepQuant\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void DQIntern::State::checkRdCosts (const \fBScanPosType\fP spt, const \fBPQData\fP & pqDataA, const \fBPQData\fP & pqDataB, \fBDecision\fP & decisionA, \fBDecision\fP & decisionB) const\fC [inline]\fP"

.PP
Definition at line \fB877\fP of file \fBDepQuant\&.cpp\fP\&.
.SS "void DQIntern::State::checkRdCostSkipSbb (\fBDecision\fP & decision) const\fC [inline]\fP"

.PP
Definition at line \fB968\fP of file \fBDepQuant\&.cpp\fP\&.
.SS "void DQIntern::State::checkRdCostSkipSbbZeroOut (\fBDecision\fP & decision) const\fC [inline]\fP"

.PP
Definition at line \fB979\fP of file \fBDepQuant\&.cpp\fP\&.
.SS "void DQIntern::State::checkRdCostStart (int32_t lastOffset, const \fBPQData\fP & pqData, \fBDecision\fP & decision) const\fC [inline]\fP"

.PP
Definition at line \fB948\fP of file \fBDepQuant\&.cpp\fP\&.
.SS "void DQIntern::State::init ()\fC [inline]\fP"

.PP
Definition at line \fB866\fP of file \fBDepQuant\&.cpp\fP\&.
.SS "template<uint8_t numIPos> void DQIntern::State::updateState (const \fBScanInfo\fP & scanInfo, const \fBState\fP * prevStates, const \fBDecision\fP & decision)\fC [inline]\fP"

.PP
Definition at line \fB1018\fP of file \fBDepQuant\&.cpp\fP\&.
.SS "void DQIntern::State::updateStateEOS (const \fBScanInfo\fP & scanInfo, const \fBState\fP * prevStates, const \fBState\fP * skipStates, const \fBDecision\fP & decision)\fC [inline]\fP"

.PP
Definition at line \fB1168\fP of file \fBDepQuant\&.cpp\fP\&.
.SH "Friends And Related Symbol Documentation"
.PP 
.SS "friend class \fBCommonCtx\fP\fC [friend]\fP"

.PP
Definition at line \fB857\fP of file \fBDepQuant\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "unsigned DQIntern::State::effHeight"

.PP
Definition at line \fB1004\fP of file \fBDepQuant\&.cpp\fP\&.
.SS "unsigned DQIntern::State::effWidth"

.PP
Definition at line \fB1003\fP of file \fBDepQuant\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
