.TH "DQIntern::TUParameters" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DQIntern::TUParameters
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTUParameters\fP (const \fBRom\fP &rom, const unsigned width, const unsigned height, const ChannelType chType)"
.br
.ti -1c
.RI "\fB~TUParameters\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "ChannelType \fBm_chType\fP"
.br
.ti -1c
.RI "unsigned \fBm_width\fP"
.br
.ti -1c
.RI "unsigned \fBm_height\fP"
.br
.ti -1c
.RI "unsigned \fBm_numCoeff\fP"
.br
.ti -1c
.RI "unsigned \fBm_numSbb\fP"
.br
.ti -1c
.RI "unsigned \fBm_log2SbbWidth\fP"
.br
.ti -1c
.RI "unsigned \fBm_log2SbbHeight\fP"
.br
.ti -1c
.RI "unsigned \fBm_log2SbbSize\fP"
.br
.ti -1c
.RI "unsigned \fBm_sbbSize\fP"
.br
.ti -1c
.RI "unsigned \fBm_sbbMask\fP"
.br
.ti -1c
.RI "unsigned \fBm_widthInSbb\fP"
.br
.ti -1c
.RI "unsigned \fBm_heightInSbb\fP"
.br
.ti -1c
.RI "CoeffScanType \fBm_scanType\fP"
.br
.ti -1c
.RI "const ScanElement * \fBm_scanSbbId2SbbPos\fP"
.br
.ti -1c
.RI "const ScanElement * \fBm_scanId2BlkPos\fP"
.br
.ti -1c
.RI "const \fBNbInfoSbb\fP * \fBm_scanId2NbInfoSbb\fP"
.br
.ti -1c
.RI "const \fBNbInfoOut\fP * \fBm_scanId2NbInfoOut\fP"
.br
.ti -1c
.RI "\fBScanInfo\fP * \fBm_scanInfo\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB99\fP of file \fBDepQuant\&.cpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "DQIntern::TUParameters::TUParameters (const \fBRom\fP & rom, const unsigned width, const unsigned height, const ChannelType chType)"

.PP
Definition at line \fB340\fP of file \fBDepQuant\&.cpp\fP\&.
.SS "DQIntern::TUParameters::~TUParameters ()\fC [inline]\fP"

.PP
Definition at line \fB102\fP of file \fBDepQuant\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "ChannelType DQIntern::TUParameters::m_chType"

.PP
Definition at line \fB107\fP of file \fBDepQuant\&.cpp\fP\&.
.SS "unsigned DQIntern::TUParameters::m_height"

.PP
Definition at line \fB109\fP of file \fBDepQuant\&.cpp\fP\&.
.SS "unsigned DQIntern::TUParameters::m_heightInSbb"

.PP
Definition at line \fB118\fP of file \fBDepQuant\&.cpp\fP\&.
.SS "unsigned DQIntern::TUParameters::m_log2SbbHeight"

.PP
Definition at line \fB113\fP of file \fBDepQuant\&.cpp\fP\&.
.SS "unsigned DQIntern::TUParameters::m_log2SbbSize"

.PP
Definition at line \fB114\fP of file \fBDepQuant\&.cpp\fP\&.
.SS "unsigned DQIntern::TUParameters::m_log2SbbWidth"

.PP
Definition at line \fB112\fP of file \fBDepQuant\&.cpp\fP\&.
.SS "unsigned DQIntern::TUParameters::m_numCoeff"

.PP
Definition at line \fB110\fP of file \fBDepQuant\&.cpp\fP\&.
.SS "unsigned DQIntern::TUParameters::m_numSbb"

.PP
Definition at line \fB111\fP of file \fBDepQuant\&.cpp\fP\&.
.SS "unsigned DQIntern::TUParameters::m_sbbMask"

.PP
Definition at line \fB116\fP of file \fBDepQuant\&.cpp\fP\&.
.SS "unsigned DQIntern::TUParameters::m_sbbSize"

.PP
Definition at line \fB115\fP of file \fBDepQuant\&.cpp\fP\&.
.SS "const ScanElement* DQIntern::TUParameters::m_scanId2BlkPos"

.PP
Definition at line \fB121\fP of file \fBDepQuant\&.cpp\fP\&.
.SS "const \fBNbInfoOut\fP* DQIntern::TUParameters::m_scanId2NbInfoOut"

.PP
Definition at line \fB123\fP of file \fBDepQuant\&.cpp\fP\&.
.SS "const \fBNbInfoSbb\fP* DQIntern::TUParameters::m_scanId2NbInfoSbb"

.PP
Definition at line \fB122\fP of file \fBDepQuant\&.cpp\fP\&.
.SS "\fBScanInfo\fP* DQIntern::TUParameters::m_scanInfo"

.PP
Definition at line \fB124\fP of file \fBDepQuant\&.cpp\fP\&.
.SS "const ScanElement* DQIntern::TUParameters::m_scanSbbId2SbbPos"

.PP
Definition at line \fB120\fP of file \fBDepQuant\&.cpp\fP\&.
.SS "CoeffScanType DQIntern::TUParameters::m_scanType"

.PP
Definition at line \fB119\fP of file \fBDepQuant\&.cpp\fP\&.
.SS "unsigned DQIntern::TUParameters::m_width"

.PP
Definition at line \fB108\fP of file \fBDepQuant\&.cpp\fP\&.
.SS "unsigned DQIntern::TUParameters::m_widthInSbb"

.PP
Definition at line \fB117\fP of file \fBDepQuant\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
