.TH "DQIntern::CoeffFracBits" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DQIntern::CoeffFracBits
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int32_t \fBbits\fP [6]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB65\fP of file \fBDepQuant\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int32_t DQIntern::CoeffFracBits::bits[6]"

.PP
Definition at line \fB67\fP of file \fBDepQuant\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
