.TH "DQIntern::RateEstimator" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DQIntern::RateEstimator
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBDQIntern::DepQuant\fP\fC [private]\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRateEstimator\fP ()"
.br
.ti -1c
.RI "\fB~RateEstimator\fP ()"
.br
.ti -1c
.RI "void \fBinitCtx\fP (const \fBTUParameters\fP &tuPars, const TransformUnit &tu, const ComponentID compID, const FracBitsAccess &fracBitsAccess)"
.br
.ti -1c
.RI "const BinFracBits * \fBsigSbbFracBits\fP () const"
.br
.ti -1c
.RI "const BinFracBits * \fBsigFlagBits\fP (unsigned stateId) const"
.br
.ti -1c
.RI "const \fBCoeffFracBits\fP * \fBgtxFracBits\fP (unsigned stateId) const"
.br
.ti -1c
.RI "int32_t \fBlastOffset\fP (unsigned scanIdx) const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB423\fP of file \fBDepQuant\&.cpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "DQIntern::RateEstimator::RateEstimator ()\fC [inline]\fP"

.PP
Definition at line \fB426\fP of file \fBDepQuant\&.cpp\fP\&.
.SS "DQIntern::RateEstimator::~RateEstimator ()\fC [inline]\fP"

.PP
Definition at line \fB427\fP of file \fBDepQuant\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "const \fBCoeffFracBits\fP * DQIntern::RateEstimator::gtxFracBits (unsigned stateId) const\fC [inline]\fP"

.PP
Definition at line \fB435\fP of file \fBDepQuant\&.cpp\fP\&.
.SS "void DQIntern::RateEstimator::initCtx (const \fBTUParameters\fP & tuPars, const TransformUnit & tu, const ComponentID compID, const FracBitsAccess & fracBitsAccess)"

.PP
Definition at line \fB463\fP of file \fBDepQuant\&.cpp\fP\&.
.SS "int32_t DQIntern::RateEstimator::lastOffset (unsigned scanIdx) const\fC [inline]\fP"

.PP
Definition at line \fB436\fP of file \fBDepQuant\&.cpp\fP\&.
.SS "const BinFracBits * DQIntern::RateEstimator::sigFlagBits (unsigned stateId) const\fC [inline]\fP"

.PP
Definition at line \fB431\fP of file \fBDepQuant\&.cpp\fP\&.
.SS "const BinFracBits * DQIntern::RateEstimator::sigSbbFracBits () const\fC [inline]\fP"

.PP
Definition at line \fB430\fP of file \fBDepQuant\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
