.TH "deps/base_vvc/minimum_VTM/source/Lib/CommonLib/dtrace_blockstatistics.cpp" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deps/base_vvc/minimum_VTM/source/Lib/CommonLib/dtrace_blockstatistics.cpp \- DTrace block statistcis support for next software\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'dtrace_blockstatistics\&.h'\fP
.br
\fC#include 'dtrace\&.h'\fP
.br
\fC#include 'dtrace_next\&.h'\fP
.br
\fC#include 'CommonLib/Unit\&.h'\fP
.br
\fC#include 'CommonLib/Picture\&.h'\fP
.br
\fC#include 'CommonLib/UnitTools\&.h'\fP
.br
\fC#include <queue>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBBLOCK_STATS_POLYGON_MIN_POINTS\fP   3"
.br
.ti -1c
.RI "#define \fBBLOCK_STATS_POLYGON_MAX_POINTS\fP   5"
.br
.in -1c
.SH "Detailed Description"
.PP 
DTrace block statistcis support for next software\&. 


.PP
Definition in file \fBdtrace_blockstatistics\&.cpp\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define BLOCK_STATS_POLYGON_MAX_POINTS   5"

.PP
Definition at line \fB48\fP of file \fBdtrace_blockstatistics\&.cpp\fP\&.
.SS "#define BLOCK_STATS_POLYGON_MIN_POINTS   3"

.PP
Definition at line \fB47\fP of file \fBdtrace_blockstatistics\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
