.TH "deps/base_vvc/minimum_VTM/source/Lib/CommonLib/dtrace_buffer.h" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deps/base_vvc/minimum_VTM/source/Lib/CommonLib/dtrace_buffer.h \- Easy to use dtrace calls concerning buffers\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'dtrace\&.h'\fP
.br
\fC#include 'dtrace_next\&.h'\fP
.br
\fC#include 'CommonLib/CommonDef\&.h'\fP
.br
\fC#include 'CommonLib/Buffer\&.h'\fP
.br
\fC#include 'CommonLib/Unit\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBvtm\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBDTRACE_PEL_BUF\fP(\&.\&.\&.)"
.br
.ti -1c
.RI "#define \fBDTRACE_COEFF_BUF\fP(\&.\&.\&.)"
.br
.ti -1c
.RI "#define \fBDTRACE_BLOCK_REC\fP(\&.\&.\&.)"
.br
.ti -1c
.RI "#define \fBDTRACE_PEL_BUF_COND\fP(\&.\&.\&.)"
.br
.ti -1c
.RI "#define \fBDTRACE_COEFF_BUF_COND\fP(\&.\&.\&.)"
.br
.ti -1c
.RI "#define \fBDTRACE_BLOCK_REC_COND\fP(\&.\&.\&.)"
.br
.ti -1c
.RI "#define \fBDTRACE_UNIT_COMP\fP(\&.\&.\&.)"
.br
.ti -1c
.RI "#define \fBDTRACE_CRC\fP(\&.\&.\&.)"
.br
.ti -1c
.RI "#define \fBDTRACE_CCRC\fP(\&.\&.\&.)"
.br
.ti -1c
.RI "#define \fBDTRACE_MOT_FIELD\fP(\&.\&.\&.)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "unsigned \fBvtm::calcCheckSum\fP (const int iWidth, const int iHeight, const \fBPel\fP *p, const uint32_t stride, const int bitdepth)"
.br
.ti -1c
.RI "unsigned \fBvtm::calcCheckSum\fP (const \fBCPelBuf\fP &buf, int bitdepth)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Easy to use dtrace calls concerning buffers\&. 


.PP
Definition in file \fBdtrace_buffer\&.h\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define DTRACE_BLOCK_REC( \&.\&.\&.)"

.PP
Definition at line \fB205\fP of file \fBdtrace_buffer\&.h\fP\&.
.SS "#define DTRACE_BLOCK_REC_COND( \&.\&.\&.)"

.PP
Definition at line \fB208\fP of file \fBdtrace_buffer\&.h\fP\&.
.SS "#define DTRACE_CCRC( \&.\&.\&.)"

.PP
Definition at line \fB211\fP of file \fBdtrace_buffer\&.h\fP\&.
.SS "#define DTRACE_COEFF_BUF( \&.\&.\&.)"

.PP
Definition at line \fB204\fP of file \fBdtrace_buffer\&.h\fP\&.
.SS "#define DTRACE_COEFF_BUF_COND( \&.\&.\&.)"

.PP
Definition at line \fB207\fP of file \fBdtrace_buffer\&.h\fP\&.
.SS "#define DTRACE_CRC( \&.\&.\&.)"

.PP
Definition at line \fB210\fP of file \fBdtrace_buffer\&.h\fP\&.
.SS "#define DTRACE_MOT_FIELD( \&.\&.\&.)"

.PP
Definition at line \fB212\fP of file \fBdtrace_buffer\&.h\fP\&.
.SS "#define DTRACE_PEL_BUF( \&.\&.\&.)"

.PP
Definition at line \fB203\fP of file \fBdtrace_buffer\&.h\fP\&.
.SS "#define DTRACE_PEL_BUF_COND( \&.\&.\&.)"

.PP
Definition at line \fB206\fP of file \fBdtrace_buffer\&.h\fP\&.
.SS "#define DTRACE_UNIT_COMP( \&.\&.\&.)"

.PP
Definition at line \fB209\fP of file \fBdtrace_buffer\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
