.TH "deps/base_vvc/minimum_VTM/source/Lib/CommonLib/dtrace_codingstruct.h" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deps/base_vvc/minimum_VTM/source/Lib/CommonLib/dtrace_codingstruct.h \- Easy to use dtrace calls concerning coding structures\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'dtrace\&.h'\fP
.br
\fC#include 'dtrace_next\&.h'\fP
.br
\fC#include 'CommonLib/CommonDef\&.h'\fP
.br
\fC#include 'CommonLib/CodingStructure\&.h'\fP
.br
\fC#include 'CommonLib/Slice\&.h'\fP
.br
\fC#include 'CommonLib/Mv\&.h'\fP
.br
\fC#include 'CommonLib/Unit\&.h'\fP
.br
\fC#include 'CommonLib/UnitTools\&.h'\fP
.br
\fC#include <cmath>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBvtm\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBDTRACE_BEST_MODE\fP(\&.\&.\&.)"
.br
.ti -1c
.RI "#define \fBDTRACE_MODE_COST\fP(\&.\&.\&.)"
.br
.ti -1c
.RI "#define \fBDTRACE_STAT\fP(\&.\&.\&.)"
.br
.ti -1c
.RI "#define \fBDTRACE_PIC_COMP\fP(\&.\&.\&.)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Easy to use dtrace calls concerning coding structures\&. 


.PP
Definition in file \fBdtrace_codingstruct\&.h\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define DTRACE_BEST_MODE( \&.\&.\&.)"

.PP
Definition at line \fB189\fP of file \fBdtrace_codingstruct\&.h\fP\&.
.SS "#define DTRACE_MODE_COST( \&.\&.\&.)"

.PP
Definition at line \fB190\fP of file \fBdtrace_codingstruct\&.h\fP\&.
.SS "#define DTRACE_PIC_COMP( \&.\&.\&.)"

.PP
Definition at line \fB192\fP of file \fBdtrace_codingstruct\&.h\fP\&.
.SS "#define DTRACE_STAT( \&.\&.\&.)"

.PP
Definition at line \fB191\fP of file \fBdtrace_codingstruct\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
