.TH "encoder/include/Encoder.hpp" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
encoder/include/Encoder.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <map>\fP
.br
\fC#include <memory>\fP
.br
\fC#include 'Dimensions\&.hpp'\fP
.br
\fC#include 'EncoderConfiguration\&.hpp'\fP
.br
\fC#include 'Image\&.hpp'\fP
.br
\fC#include 'LayerEncodeFlags\&.hpp'\fP
.br
\fC#include 'Parameters\&.hpp'\fP
.br
\fC#include 'SignaledConfiguration\&.hpp'\fP
.br
\fC#include 'Dithering\&.hpp'\fP
.br
\fC#include 'PriorityConfiguration\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBlctm::ConformancePadding\fP"
.br
.ti -1c
.RI "class \fBlctm::Encoder\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBlctm\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
