.TH "encoder/include/EncoderConfiguration.hpp" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
encoder/include/EncoderConfiguration.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include 'Image\&.hpp'\fP
.br
\fC#include 'LayerEncodeFlags\&.hpp'\fP
.br
\fC#include 'PriorityConfiguration\&.hpp'\fP
.br
\fC#include 'SignaledConfiguration\&.hpp'\fP
.br
\fC#include 'Types\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBlctm::EncoderConfiguration\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBlctm\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
