.TH "Error" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Error
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBcode\fP"
.br
.ti -1c
.RI "std::string \fBmsg\fP"
.br
.ti -1c
.RI "std::string \fBfile\fP"
.br
.ti -1c
.RI "uint32_t \fBline\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB40\fP of file \fBcodec_api\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "uint32_t Error::code"

.PP
Definition at line \fB41\fP of file \fBcodec_api\&.cpp\fP\&.
.SS "std::string Error::file"

.PP
Definition at line \fB43\fP of file \fBcodec_api\&.cpp\fP\&.
.SS "uint32_t Error::line"

.PP
Definition at line \fB44\fP of file \fBcodec_api\&.cpp\fP\&.
.SS "std::string Error::msg"

.PP
Definition at line \fB42\fP of file \fBcodec_api\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
