.TH "deps/base_evc/src/evc_decoder_mem.h" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deps/base_evc/src/evc_decoder_mem.h
.SH SYNOPSIS
.br
.PP
\fC#include <stdint\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBevc_writer_t\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBevc_writer_t\fP \fBevc_writer_t\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBevc_decode_mem\fP (const uint8_t *stream, size_t stream_size, unsigned output_bit_depth, const \fBevc_writer_t\fP *writer)"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBevc_writer_t\fP \fBevc_writer_t\fP"

.SH "Function Documentation"
.PP 
.SS "int evc_decode_mem (const uint8_t * stream, size_t stream_size, unsigned output_bit_depth, const \fBevc_writer_t\fP * writer)"

.PP
Definition at line \fB214\fP of file \fBevc_decoder_mem\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
