.TH "deps/base_evc/src/evc_decoder_mem.c" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deps/base_evc/src/evc_decoder_mem.c
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./ETM/src/evc_def\&.h'\fP
.br
\fC#include 'util\&.h'\fP
.br
\fC#include '\&.\&./ETM/src/evc_dra\&.h'\fP
.br
\fC#include 'evc_decoder_mem\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBDECODING_TIME_TEST\fP   1"
.br
.ti -1c
.RI "#define \fBVERBOSE_NONE\fP   \fBVERBOSE_0\fP"
.br
.ti -1c
.RI "#define \fBVERBOSE_FRAME\fP   \fBVERBOSE_1\fP"
.br
.ti -1c
.RI "#define \fBVERBOSE_ALL\fP   \fBVERBOSE_2\fP"
.br
.ti -1c
.RI "#define \fBMAX_BS_BUF\fP   16*1024*1024 /* byte */"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef enum \fB_STATES\fP \fBSTATES\fP"
.br
.ti -1c
.RI "typedef enum \fB_OP_FLAGS\fP \fBOP_FLAGS\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fB_STATES\fP { \fBSTATE_DECODING\fP, \fBSTATE_BUMPING\fP }"
.br
.ti -1c
.RI "enum \fB_OP_FLAGS\fP { \fBOP_FLAG_FNAME_INP\fP, \fBOP_FLAG_FNAME_OUT\fP, \fBOP_FLAG_MAX_FRM_NUM\fP, \fBOP_FLAG_USE_PIC_SIGN\fP, \fBOP_FLAG_OUT_BIT_DEPTH\fP, \fBOP_FLAG_VERBOSE\fP, \fBOP_FLAG_MAX\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBevc_decode_mem\fP (const uint8_t *stream, size_t stream_size, unsigned output_bit_depth, const \fBevc_writer_t\fP *writer)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define DECODING_TIME_TEST   1"

.PP
Definition at line \fB34\fP of file \fBevc_decoder_mem\&.c\fP\&.
.SS "#define MAX_BS_BUF   16*1024*1024 /* byte */"

.PP
Definition at line \fB48\fP of file \fBevc_decoder_mem\&.c\fP\&.
.SS "#define VERBOSE_ALL   \fBVERBOSE_2\fP"

.PP
Definition at line \fB46\fP of file \fBevc_decoder_mem\&.c\fP\&.
.SS "#define VERBOSE_FRAME   \fBVERBOSE_1\fP"

.PP
Definition at line \fB45\fP of file \fBevc_decoder_mem\&.c\fP\&.
.SS "#define VERBOSE_NONE   \fBVERBOSE_0\fP"

.PP
Definition at line \fB44\fP of file \fBevc_decoder_mem\&.c\fP\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef enum \fB_OP_FLAGS\fP \fBOP_FLAGS\fP"

.SS "typedef enum \fB_STATES\fP \fBSTATES\fP"

.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fB_OP_FLAGS\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIOP_FLAG_FNAME_INP \fP\fP
.TP
\fB\fIOP_FLAG_FNAME_OUT \fP\fP
.TP
\fB\fIOP_FLAG_MAX_FRM_NUM \fP\fP
.TP
\fB\fIOP_FLAG_USE_PIC_SIGN \fP\fP
.TP
\fB\fIOP_FLAG_OUT_BIT_DEPTH \fP\fP
.TP
\fB\fIOP_FLAG_VERBOSE \fP\fP
.TP
\fB\fIOP_FLAG_MAX \fP\fP
.PP
Definition at line \fB62\fP of file \fBevc_decoder_mem\&.c\fP\&.
.SS "enum \fB_STATES\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fISTATE_DECODING \fP\fP
.TP
\fB\fISTATE_BUMPING \fP\fP
.PP
Definition at line \fB56\fP of file \fBevc_decoder_mem\&.c\fP\&.
.SH "Function Documentation"
.PP 
.SS "int evc_decode_mem (const uint8_t * stream, size_t stream_size, unsigned output_bit_depth, const \fBevc_writer_t\fP * writer)"

.PP
Definition at line \fB214\fP of file \fBevc_decoder_mem\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
