.TH "evc_writer_t" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
evc_writer_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <evc_decoder_mem\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "void(* \fBoutput_begin_fn\fP )(void *writer_data, int is16bit, uint32_t width, uint32_t height)"
.br
.ti -1c
.RI "size_t(* \fBoutput_write_fn\fP )(void *writer_data, const uint8_t *output_data, size_t size)"
.br
.ti -1c
.RI "void(* \fBoutput_end_fn\fP )(void *writer_data)"
.br
.ti -1c
.RI "void * \fBdata\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB7\fP of file \fBevc_decoder_mem\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "void* evc_writer_t::data"

.PP
Definition at line \fB12\fP of file \fBevc_decoder_mem\&.h\fP\&.
.SS "void(* evc_writer_t::output_begin_fn) (void *writer_data, int is16bit, uint32_t width, uint32_t height)"

.PP
Definition at line \fB8\fP of file \fBevc_decoder_mem\&.h\fP\&.
.SS "void(* evc_writer_t::output_end_fn) (void *writer_data)"

.PP
Definition at line \fB10\fP of file \fBevc_decoder_mem\&.h\fP\&.
.SS "size_t(* evc_writer_t::output_write_fn) (void *writer_data, const uint8_t *output_data, size_t size)"

.PP
Definition at line \fB9\fP of file \fBevc_decoder_mem\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
