.TH "decoder/src/Expand.cpp" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
decoder/src/Expand.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'Expand\&.hpp'\fP
.br
\fC#include 'Misc\&.hpp'\fP
.br
\fC#include <vector>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBlctm\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBImage\fP \fBlctm::ExpandImage\fP (const \fBImage\fP &src, const \fBImageDescription\fP &description)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
