.TH "encoder/src/FileEncoder.cpp" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
encoder/src/FileEncoder.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'FileEncoder\&.hpp'\fP
.br
\fC#include <cinttypes>\fP
.br
\fC#include <cstdint>\fP
.br
\fC#include <cstdio>\fP
.br
\fC#include <cstdlib>\fP
.br
\fC#include <cstring>\fP
.br
\fC#include <atomic>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <list>\fP
.br
\fC#include <map>\fP
.br
\fC#include <mutex>\fP
.br
\fC#include <queue>\fP
.br
\fC#include <stdexcept>\fP
.br
\fC#include <thread>\fP
.br
\fC#include <cassert>\fP
.br
\fC#include 'Config\&.hpp'\fP
.br
\fC#include 'Convert\&.hpp'\fP
.br
\fC#include 'Downsampling\&.hpp'\fP
.br
\fC#include 'Encoder\&.hpp'\fP
.br
\fC#include 'Expand\&.hpp'\fP
.br
\fC#include 'Types\&.hpp'\fP
.br
\fC#include 'Upsampling\&.hpp'\fP
.br
\fC#include 'BitstreamPacker\&.hpp'\fP
.br
\fC#include 'Diagnostics\&.hpp'\fP
.br
\fC#include 'Image\&.hpp'\fP
.br
\fC#include 'Misc\&.hpp'\fP
.br
\fC#include 'Packet\&.hpp'\fP
.br
\fC#include 'Probe\&.hpp'\fP
.br
\fC#include 'TemporalDecode\&.hpp'\fP
.br
\fC#include 'YUVReader\&.hpp'\fP
.br
\fC#include 'YUVWriter\&.hpp'\fP
.br
\fC#include 'uESFile\&.h'\fP
.br
\fC#include 'BitstreamStatistic\&.hpp'\fP
.br
\fC#include 'nlohmann/json\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBlctm::FileEncoderImpl\fP"
.br
.ti -1c
.RI "struct \fBlctm::FileEncoderImpl::RegisteredSEI\fP"
.br
.ti -1c
.RI "struct \fBlctm::FileEncoderImpl::UnregisteredSEI\fP"
.br
.ti -1c
.RI "class \fBlctm::FileEncoderImplAVC\fP"
.br
.ti -1c
.RI "class \fBlctm::FileEncoderImplHEVC\fP"
.br
.ti -1c
.RI "class \fBlctm::FileEncoderImplX265\fP"
.br
.ti -1c
.RI "class \fBlctm::FileEncoderImplVVC\fP"
.br
.ti -1c
.RI "class \fBlctm::FileEncoderImplEVC\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBlctm\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBjson\fP = \fBnlohmann::json\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename T , typename\&.\&.\&. Args> std::unique_ptr< T > \fBlctm::make_unique\fP (Args &&\&.\&.\&.args)"
.br
.ti -1c
.RI "std::unique_ptr< \fBFileEncoder\fP > \fBlctm::CreateFileEncoder\fP (\fBBaseCoding\fP base_encoder, const \fBImageDescription\fP &image_description, unsigned fps, const \fBParameters\fP &parameters)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBPsnrStatistic\fP \fBgoPsnr\fP"
.br
.ti -1c
.RI "uint8_t \fBgaucMd5Digest\fP [][16]"
.br
.ti -1c
.RI "\fBReportStructure\fP \fBgoReportStructure\fP"
.br
.ti -1c
.RI "priority_queue< \fBReportStructure\fP, vector< \fBReportStructure\fP, allocator< \fBReportStructure\fP > >, \fBReportStructureComp\fP > \fBgoReportQueue\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "using \fBjson\fP =  \fBnlohmann::json\fP"

.PP
Definition at line \fB92\fP of file \fBFileEncoder\&.cpp\fP\&.
.SH "Variable Documentation"
.PP 
.SS "uint8_t gaucMd5Digest[][16]\fC [extern]\fP"

.PP
Definition at line \fB76\fP of file \fBModelDecoderApp\&.cpp\fP\&.
.SS "\fBPsnrStatistic\fP goPsnr\fC [extern]\fP"

.PP
Definition at line \fB75\fP of file \fBModelDecoderApp\&.cpp\fP\&.
.SS "priority_queue<\fBReportStructure\fP, vector<\fBReportStructure\fP, allocator<\fBReportStructure\fP> >, \fBReportStructureComp\fP> goReportQueue\fC [extern]\fP"

.PP
Definition at line \fB79\fP of file \fBModelDecoderApp\&.cpp\fP\&.
.SS "\fBReportStructure\fP goReportStructure\fC [extern]\fP"

.PP
Definition at line \fB77\fP of file \fBModelDecoderApp\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
