.TH "deps/base_vvc/minimum_VTM/source/Lib/CommonLib/HRD.cpp" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deps/base_vvc/minimum_VTM/source/Lib/CommonLib/HRD.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'HRD\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBvtm\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
