.TH "deps/base_vvc/minimum_VTM/source/Lib/CommonLib/HRD.h" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deps/base_vvc/minimum_VTM/source/Lib/CommonLib/HRD.h
.SH SYNOPSIS
.br
.PP
\fC#include 'Common\&.h'\fP
.br
\fC#include 'SEI\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBvtm::OlsHrdParams\fP"
.br
.ti -1c
.RI "class \fBvtm::GeneralHrdParams\fP"
.br
.ti -1c
.RI "class \fBvtm::HRD\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBvtm\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBvtm::checkBPSyntaxElementLength\fP (const \fBSEIBufferingPeriod\fP *bp1, const \fBSEIBufferingPeriod\fP *bp2)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
