.TH "IbcHashMap" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IbcHashMap
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <IbcHashMap\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t(* \fBm_computeCrc32c\fP )(uint32_t crc, const Pel pel)"
.br
.in -1c
.in +1c
.ti -1c
.RI "void \fBinit\fP (const int picWidth, const int picHeight)"
.br
.ti -1c
.RI "void \fBdestroy\fP ()"
.br
.ti -1c
.RI "void \fBrebuildPicHashMap\fP (const PelUnitBuf &pic)"
.br
.ti -1c
.RI "bool \fBibcHashMatch\fP (const Area &lumaArea, std::vector< Position > &cand, const CodingStructure &cs, const int maxCand, const int searchRange4SmallBlk)"
.br
.ti -1c
.RI "int \fBgetHashHitRatio\fP (const Area &lumaArea)"
.br
.ti -1c
.RI "int \fBcalHashBlkMatchPerc\fP (const Area &lumaArea)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB58\fP of file \fBIbcHashMap\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "IbcHashMap::IbcHashMap ()"

.PP
Definition at line \fB53\fP of file \fBIbcHashMap\&.cpp\fP\&.
.SS "IbcHashMap::~IbcHashMap ()\fC [virtual]\fP"

.PP
Definition at line \fB68\fP of file \fBIbcHashMap\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "int IbcHashMap::calHashBlkMatchPerc (const Area & lumaArea)"

.PP
Definition at line \fB356\fP of file \fBIbcHashMap\&.cpp\fP\&.
.SS "void IbcHashMap::destroy ()"

.PP
Definition at line \fB90\fP of file \fBIbcHashMap\&.cpp\fP\&.
.SS "int IbcHashMap::getHashHitRatio (const Area & lumaArea)"

.PP
Definition at line \fB339\fP of file \fBIbcHashMap\&.cpp\fP\&.
.SS "bool IbcHashMap::ibcHashMatch (const Area & lumaArea, std::vector< Position > & cand, const CodingStructure & cs, const int maxCand, const int searchRange4SmallBlk)"

.PP
Definition at line \fB270\fP of file \fBIbcHashMap\&.cpp\fP\&.
.SS "void IbcHashMap::init (const int picWidth, const int picHeight)"

.PP
Definition at line \fB73\fP of file \fBIbcHashMap\&.cpp\fP\&.
.SS "void IbcHashMap::rebuildPicHashMap (const PelUnitBuf & pic)"

.PP
Definition at line \fB246\fP of file \fBIbcHashMap\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "uint32_t(* IbcHashMap::m_computeCrc32c) (uint32_t crc, const Pel pel)"

.PP
Definition at line \fB74\fP of file \fBIbcHashMap\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
