.TH "deps/base_avc/include/ifunctions.h" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deps/base_avc/include/ifunctions.h \- define some inline functions that are used within the encoder\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <math\&.h>\fP
.br
\fC#include <limits\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBstatic\fP"
.br
.ti -1c
.RI "#define \fBinline\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
define some inline functions that are used within the encoder\&. 

\fBifunctions\&.h\fP
.PP
\fBAuthor\fP
.RS 4
Main contributors (see contributors\&.h for copyright, address and affiliation details)
.IP "\(bu" 2
Karsten Suehring
.IP "\(bu" 2
Alexis Tourapis alexismt@ieee.org 
.PP
.RE
.PP

.PP
Definition in file \fBifunctions\&.h\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define inline"

.PP
Definition at line \fB23\fP of file \fBifunctions\&.h\fP\&.
.SS "#define static"

.PP
Definition at line \fB22\fP of file \fBifunctions\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
