.TH "util/include/Image.hpp" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
util/include/Image.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <cstddef>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br
\fC#include 'Surface\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBlctm::ImageDescription\fP"
.br
.ti -1c
.RI "class \fBlctm::Image\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBlctm\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBlctm::ImageFormat\fP { \fBlctm::IMAGE_FORMAT_NONE\fP = 0, \fBlctm::IMAGE_FORMAT_YUV420P8\fP = 1, \fBlctm::IMAGE_FORMAT_YUV422P8\fP = 2, \fBlctm::IMAGE_FORMAT_YUV444P8\fP = 3, \fBlctm::IMAGE_FORMAT_Y8\fP = 4, \fBlctm::IMAGE_FORMAT_YUV420P10\fP = 5, \fBlctm::IMAGE_FORMAT_YUV422P10\fP = 6, \fBlctm::IMAGE_FORMAT_YUV444P10\fP = 7, \fBlctm::IMAGE_FORMAT_Y10\fP = 8, \fBlctm::IMAGE_FORMAT_YUV420P12\fP = 9, \fBlctm::IMAGE_FORMAT_YUV422P12\fP = 10, \fBlctm::IMAGE_FORMAT_YUV444P12\fP = 11, \fBlctm::IMAGE_FORMAT_Y12\fP = 12, \fBlctm::IMAGE_FORMAT_YUV420P14\fP = 13, \fBlctm::IMAGE_FORMAT_YUV422P14\fP = 14, \fBlctm::IMAGE_FORMAT_YUV444P14\fP = 15, \fBlctm::IMAGE_FORMAT_Y14\fP = 16, \fBlctm::IMAGE_FORMAT_YUV420P16\fP = 17, \fBlctm::IMAGE_FORMAT_YUV422P16\fP = 18, \fBlctm::IMAGE_FORMAT_YUV444P16\fP = 19, \fBlctm::IMAGE_FORMAT_Y16\fP = 20, \fBlctm::_IMAGE_FORMAT_MAX\fP }"
.br
.ti -1c
.RI "enum \fBlctm::Colourspace\fP { \fBlctm::Colourspace_Y\fP = 0, \fBlctm::Colourspace_YUV420\fP = 1, \fBlctm::Colourspace_YUV422\fP = 2, \fBlctm::Colourspace_YUV444\fP = 3 }"
.br
.ti -1c
.RI "enum \fBlctm::Bitdepth\fP { \fBlctm::Bitdepth_8\fP = 8, \fBlctm::Bitdepth_10\fP = 10, \fBlctm::Bitdepth_12\fP = 12, \fBlctm::Bitdepth_14\fP = 14 }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBlctm::operator==\fP (const class \fBImageDescription\fP &lhs, const class \fBImageDescription\fP &rhs)"
.br
.ti -1c
.RI "std::istream & \fBlctm::operator>>\fP (std::istream &in, \fBImageFormat\fP &v)"
.br
.ti -1c
.RI "std::istream & \fBlctm::operator>>\fP (std::istream &in, \fBColourspace\fP &v)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
