.TH "util/src/Image.cpp" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
util/src/Image.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'Image\&.hpp'\fP
.br
\fC#include 'Diagnostics\&.hpp'\fP
.br
\fC#include 'Misc\&.hpp'\fP
.br
\fC#include <cassert>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBlctm::ImageDescInfo\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBlctm\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBlctm::operator==\fP (const \fBImageDescription\fP &lhs, const \fBImageDescription\fP &rhs)"
.br
.ti -1c
.RI "std::istream & \fBlctm::operator>>\fP (std::istream &in, \fBImageFormat\fP &v)"
.br
.ti -1c
.RI "std::istream & \fBlctm::operator>>\fP (std::istream &in, \fBColourspace\fP &v)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
