.TH "deps/base_avc/include/inject_annexb.h" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deps/base_avc/include/inject_annexb.h
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBinject_annex_b_bitstream\fP (byte *data, unsigned size)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void inject_annex_b_bitstream (byte * data, unsigned size)\fC [extern]\fP"

.PP
Definition at line \fB26\fP of file \fBannexb\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
