.TH "deps/base_vvc/minimum_VTM/source/Lib/CommonLib/InterpolationFilter.h" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deps/base_vvc/minimum_VTM/source/Lib/CommonLib/InterpolationFilter.h \- Declaration of InterpolationFilter class\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'CommonDef\&.h'\fP
.br
\fC#include 'CacheModel\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBvtm::InterpolationFilter\fP"
.br
.RI "Interpolation filter class\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBvtm\fP"
.br
.in -1c
.SS "Macros"

.PP
.RI "\fB\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "#define \fBIF_INTERNAL_PREC\fP   14"
.br
.RI "Number of bits for internal precision\&. "
.ti -1c
.RI "#define \fBIF_FILTER_PREC\fP   6"
.br
.RI "Log2 of sum of filter taps\&. "
.ti -1c
.RI "#define \fBIF_INTERNAL_OFFS\fP   (1<<(\fBIF_INTERNAL_PREC\fP\-1))"
.br
.RI "Offset used internally\&. "
.ti -1c
.RI "#define \fBIF_INTERNAL_PREC_BILINEAR\fP   10"
.br
.RI "Number of bits for internal precision\&. "
.ti -1c
.RI "#define \fBIF_FILTER_PREC_BILINEAR\fP   4"
.br
.RI "Bilinear filter coeff precision so that intermediate value will not exceed 16 bit for SIMD - bit exact\&. "
.ti -1c
.RI "#define \fBIF_INTERNAL_FRAC_BITS\fP(bd)   std::max(2, \fBIF_INTERNAL_PREC\fP \- int(bd))"
.br
.in -1c
.in -1c
.SH "Detailed Description"
.PP 
Declaration of InterpolationFilter class\&. 


.PP
Definition in file \fBInterpolationFilter\&.h\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define IF_FILTER_PREC   6"

.PP
Log2 of sum of filter taps\&. 
.PP
Definition at line \fB51\fP of file \fBInterpolationFilter\&.h\fP\&.
.SS "#define IF_FILTER_PREC_BILINEAR   4"

.PP
Bilinear filter coeff precision so that intermediate value will not exceed 16 bit for SIMD - bit exact\&. 
.PP
Definition at line \fB54\fP of file \fBInterpolationFilter\&.h\fP\&.
.SS "#define IF_INTERNAL_FRAC_BITS(bd)   std::max(2, \fBIF_INTERNAL_PREC\fP \- int(bd))"

.PP
Definition at line \fB55\fP of file \fBInterpolationFilter\&.h\fP\&.
.SS "#define IF_INTERNAL_OFFS   (1<<(\fBIF_INTERNAL_PREC\fP\-1))"

.PP
Offset used internally\&. 
.PP
Definition at line \fB52\fP of file \fBInterpolationFilter\&.h\fP\&.
.SS "#define IF_INTERNAL_PREC   14"

.PP
Number of bits for internal precision\&. 
.PP
Definition at line \fB50\fP of file \fBInterpolationFilter\&.h\fP\&.
.SS "#define IF_INTERNAL_PREC_BILINEAR   10"

.PP
Number of bits for internal precision\&. 
.PP
Definition at line \fB53\fP of file \fBInterpolationFilter\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
