.TH "deps/base_vvc/minimum_VTM/source/Lib/CommonLib/InterPrediction.h" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deps/base_vvc/minimum_VTM/source/Lib/CommonLib/InterPrediction.h \- inter prediction class (header)  

.SH SYNOPSIS
.br
.PP
\fC#include 'InterpolationFilter\&.h'\fP
.br
\fC#include 'WeightPrediction\&.h'\fP
.br
\fC#include 'Buffer\&.h'\fP
.br
\fC#include 'Unit\&.h'\fP
.br
\fC#include 'Picture\&.h'\fP
.br
\fC#include 'RdCost\&.h'\fP
.br
\fC#include 'ContextModelling\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBvtm::InterPrediction\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBvtm\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
inter prediction class (header) 


.PP
Definition in file \fBInterPrediction\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
