.TH "deps/base_vvc/minimum_VTM/source/Lib/CommonLib/InterPrediction.cpp" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deps/base_vvc/minimum_VTM/source/Lib/CommonLib/InterPrediction.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'InterPrediction\&.h'\fP
.br
\fC#include 'Buffer\&.h'\fP
.br
\fC#include 'UnitTools\&.h'\fP
.br
\fC#include 'MCTS\&.h'\fP
.br
\fC#include <memory\&.h>\fP
.br
\fC#include <algorithm>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBvtm\fP"
.br
.in -1c
.SS "Functions"

.PP
.RI "\fB\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "int32_t \fBvtm::div_for_maxq7\fP (int64_t N, int64_t \fBD\fP)"
.br
.ti -1c
.RI "void \fBvtm::xSubPelErrorSrfc\fP (uint64_t *sadBuffer, int32_t *deltaMv)"
.br
.ti -1c
.RI "void \fBvtm::xDMVRSubPixelErrorSurface\fP (bool notZeroCost, int16_t *totalDeltaMV, int16_t *deltaMV, uint64_t *pSADsArray)"
.br
.in -1c
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
