.TH "IntraPrediction" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IntraPrediction
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <IntraPrediction\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "Pel * \fBgetPredictorPtr\fP (const ComponentID compId)"
.br
.ti -1c
.RI "Pel * \fBgetPredictorPtr2\fP (const ComponentID compID, uint32_t idx)"
.br
.in -1c
.SS "Static Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBstatic\fP bool \fBisIntegerSlope\fP (const int absAng)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "Pel \fBm_refBuffer\fP [MAX_NUM_COMPONENT][\fBNUM_PRED_BUF\fP][(MAX_CU_SIZE *2+1+MAX_REF_LINE_IDX) *2]"
.br
.ti -1c
.RI "uint32_t \fBm_refBufferStride\fP [MAX_NUM_COMPONENT]"
.br
.ti -1c
.RI "ChromaFormat \fBm_currChromaFormat\fP"
.br
.ti -1c
.RI "int \fBm_topRefLength\fP"
.br
.ti -1c
.RI "int \fBm_leftRefLength\fP"
.br
.ti -1c
.RI "ScanElement * \fBm_scanOrder\fP"
.br
.ti -1c
.RI "bool \fBm_bestScanRotationMode\fP"
.br
.in -1c
.in +1c
.ti -1c
.RI "void \fBxPredIntraPlanar\fP (const CPelBuf &pSrc, PelBuf &pDst)"
.br
.ti -1c
.RI "void \fBxPredIntraDc\fP (const CPelBuf &pSrc, PelBuf &pDst, const ChannelType channelType, const bool enableBoundaryFilter=true)"
.br
.ti -1c
.RI "void \fBxPredIntraAng\fP (const CPelBuf &pSrc, PelBuf &pDst, const ChannelType channelType, const ClpRng &clpRng)"
.br
.ti -1c
.RI "void \fBinitPredIntraParams\fP (const PredictionUnit &pu, const CompArea compArea, const SPS &sps)"
.br
.ti -1c
.RI "void \fBxPredIntraBDPCM\fP (const CPelBuf &pSrc, PelBuf &pDst, const uint32_t dirMode, const ClpRng &clpRng)"
.br
.ti -1c
.RI "Pel \fBxGetPredValDc\fP (const CPelBuf &pSrc, const Size &dstSize)"
.br
.ti -1c
.RI "void \fBxFillReferenceSamples\fP (const CPelBuf &recoBuf, Pel *refBufUnfiltered, const CompArea &area, const CodingUnit &cu)"
.br
.ti -1c
.RI "void \fBxFilterReferenceSamples\fP (const Pel *refBufUnfiltered, Pel *refBufFiltered, const CompArea &area, const SPS &sps, int multiRefIdx)"
.br
.ti -1c
.RI "void \fBsetReferenceArrayLengths\fP (const CompArea &area)"
.br
.ti -1c
.RI "void \fBdestroy\fP ()"
.br
.ti -1c
.RI "void \fBxGetLMParameters\fP (const PredictionUnit &pu, const ComponentID compID, const CompArea &chromaArea, int &a, int &b, int &iShift)"
.br
.ti -1c
.RI "\fBstatic\fP int \fBgetModifiedWideAngle\fP (int width, int height, int predMode)"
.br
.ti -1c
.RI "void \fBinit\fP (ChromaFormat chromaFormatIDC, const unsigned bitDepthY)"
.br
.ti -1c
.RI "void \fBpredIntraAng\fP (const ComponentID compId, PelBuf &piPred, const PredictionUnit &pu)"
.br
.ti -1c
.RI "void \fBpredIntraChromaLM\fP (const ComponentID compID, PelBuf &piPred, const PredictionUnit &pu, const CompArea &chromaArea, int intraDir)"
.br
.ti -1c
.RI "void \fBxGetLumaRecPixels\fP (const PredictionUnit &pu, CompArea chromaArea)"
.br
.ti -1c
.RI "void \fBinitIntraPatternChType\fP (const CodingUnit &cu, const CompArea &area, const bool forceRefFilterFlag=false)"
.br
.RI "set parameters from CU data for accessing intra data "
.ti -1c
.RI "void \fBinitIntraPatternChTypeISP\fP (const CodingUnit &cu, const CompArea &area, PelBuf &piReco, const bool forceRefFilterFlag=false)"
.br
.ti -1c
.RI "void \fBinitIntraMip\fP (const PredictionUnit &pu, const CompArea &area)"
.br
.ti -1c
.RI "void \fBpredIntraMip\fP (const ComponentID compId, PelBuf &piPred, const PredictionUnit &pu)"
.br
.ti -1c
.RI "void \fBgeneWeightedPred\fP (const ComponentID compId, PelBuf &pred, const PredictionUnit &pu, Pel *srcBuf)"
.br
.ti -1c
.RI "void \fBswitchBuffer\fP (const PredictionUnit &pu, ComponentID compID, PelBuf srcBuff, Pel *dst)"
.br
.ti -1c
.RI "void \fBgeneIntrainterPred\fP (const CodingUnit &cu)"
.br
.ti -1c
.RI "void \fBreorderPLT\fP (CodingStructure &cs, Partitioner &partitioner, ComponentID compBegin, uint32_t numComp)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB66\fP of file \fBIntraPrediction\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "IntraPrediction::IntraPrediction ()"

.PP
Definition at line \fB75\fP of file \fBIntraPrediction\&.cpp\fP\&.
.SS "IntraPrediction::~IntraPrediction ()\fC [virtual]\fP"

.PP
Definition at line \fB91\fP of file \fBIntraPrediction\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void IntraPrediction::destroy ()\fC [protected]\fP"

.PP
Definition at line \fB96\fP of file \fBIntraPrediction\&.cpp\fP\&.
.SS "void IntraPrediction::geneIntrainterPred (const CodingUnit & cu)"

.PP
Definition at line \fB738\fP of file \fBIntraPrediction\&.cpp\fP\&.
.SS "void IntraPrediction::geneWeightedPred (const ComponentID compId, PelBuf & pred, const PredictionUnit & pu, Pel * srcBuf)"

.PP
Definition at line \fB683\fP of file \fBIntraPrediction\&.cpp\fP\&.
.SS "int IntraPrediction::getModifiedWideAngle (int width, int height, int predMode)\fC [static]\fP, \fC [protected]\fP"

.PP
Definition at line \fB183\fP of file \fBIntraPrediction\&.cpp\fP\&.
.SS "Pel * IntraPrediction::getPredictorPtr (const ComponentID compId)\fC [inline]\fP"

.PP
Definition at line \fB151\fP of file \fBIntraPrediction\&.h\fP\&.
.SS "Pel * IntraPrediction::getPredictorPtr2 (const ComponentID compID, uint32_t idx)\fC [inline]\fP"

.PP
Definition at line \fB168\fP of file \fBIntraPrediction\&.h\fP\&.
.SS "void IntraPrediction::init (ChromaFormat chromaFormatIDC, const unsigned bitDepthY)"

.PP
Definition at line \fB113\fP of file \fBIntraPrediction\&.cpp\fP\&.
.SS "void IntraPrediction::initIntraMip (const PredictionUnit & pu, const CompArea & area)"

.PP
Definition at line \fB1812\fP of file \fBIntraPrediction\&.cpp\fP\&.
.SS "void IntraPrediction::initIntraPatternChType (const CodingUnit & cu, const CompArea & area, const bool forceRefFilterFlag = \fCfalse\fP)"

.PP
set parameters from CU data for accessing intra data 
.PP
Definition at line \fB780\fP of file \fBIntraPrediction\&.cpp\fP\&.
.SS "void IntraPrediction::initIntraPatternChTypeISP (const CodingUnit & cu, const CompArea & area, PelBuf & piReco, const bool forceRefFilterFlag = \fCfalse\fP)"

.PP
Definition at line \fB804\fP of file \fBIntraPrediction\&.cpp\fP\&.
.SS "void IntraPrediction::initPredIntraParams (const PredictionUnit & pu, const CompArea compArea, const SPS & sps)\fC [protected]\fP"

.PP
Definition at line \fB357\fP of file \fBIntraPrediction\&.cpp\fP\&.
.SS "\fBstatic\fP bool IntraPrediction::isIntegerSlope (const int absAng)\fC [inline]\fP, \fC [static]\fP, \fC [protected]\fP"

.PP
Definition at line \fB127\fP of file \fBIntraPrediction\&.h\fP\&.
.SS "void IntraPrediction::predIntraAng (const ComponentID compId, PelBuf & piPred, const PredictionUnit & pu)"

.PP
Definition at line \fB215\fP of file \fBIntraPrediction\&.cpp\fP\&.
.SS "void IntraPrediction::predIntraChromaLM (const ComponentID compID, PelBuf & piPred, const PredictionUnit & pu, const CompArea & chromaArea, int intraDir)"

.PP
Definition at line \fB266\fP of file \fBIntraPrediction\&.cpp\fP\&.
.SS "void IntraPrediction::predIntraMip (const ComponentID compId, PelBuf & piPred, const PredictionUnit & pu)"

.PP
Definition at line \fB1826\fP of file \fBIntraPrediction\&.cpp\fP\&.
.SS "void IntraPrediction::reorderPLT (CodingStructure & cs, Partitioner & partitioner, ComponentID compBegin, uint32_t numComp)"

.PP
Definition at line \fB1865\fP of file \fBIntraPrediction\&.cpp\fP\&.
.SS "void IntraPrediction::setReferenceArrayLengths (const CompArea & area)\fC [protected]\fP"

.PP
Definition at line \fB205\fP of file \fBIntraPrediction\&.cpp\fP\&.
.SS "void IntraPrediction::switchBuffer (const PredictionUnit & pu, ComponentID compID, PelBuf srcBuff, Pel * dst)"

.PP
Definition at line \fB725\fP of file \fBIntraPrediction\&.cpp\fP\&.
.SS "void IntraPrediction::xFillReferenceSamples (const CPelBuf & recoBuf, Pel * refBufUnfiltered, const CompArea & area, const CodingUnit & cu)\fC [protected]\fP"

.PP
Definition at line \fB921\fP of file \fBIntraPrediction\&.cpp\fP\&.
.SS "void IntraPrediction::xFilterReferenceSamples (const Pel * refBufUnfiltered, Pel * refBufFiltered, const CompArea & area, const SPS & sps, int multiRefIdx)\fC [protected]\fP"

.PP
Definition at line \fB1171\fP of file \fBIntraPrediction\&.cpp\fP\&.
.SS "void IntraPrediction::xGetLMParameters (const PredictionUnit & pu, const ComponentID compID, const CompArea & chromaArea, int & a, int & b, int & iShift)\fC [protected]\fP"

.PP
Definition at line \fB1584\fP of file \fBIntraPrediction\&.cpp\fP\&.
.SS "void IntraPrediction::xGetLumaRecPixels (const PredictionUnit & pu, CompArea chromaArea)"

.PP
Definition at line \fB1328\fP of file \fBIntraPrediction\&.cpp\fP\&.
.SS "Pel IntraPrediction::xGetPredValDc (const CPelBuf & pSrc, const Size & dstSize)\fC [protected]\fP"

.PP
Definition at line \fB152\fP of file \fBIntraPrediction\&.cpp\fP\&.
.SS "void IntraPrediction::xPredIntraAng (const CPelBuf & pSrc, PelBuf & pDst, const ChannelType channelType, const ClpRng & clpRng)\fC [protected]\fP"
Function for deriving the simplified angular intra predictions\&.
.PP
This function derives the prediction samples for the angular mode based on the prediction direction indicated by the prediction mode index\&. The prediction direction is given by the displacement of the bottom row of the block and the reference row above the block in the case of vertical prediction or displacement of the rightmost column of the block and reference column left from the block in the case of the horizontal prediction\&. The displacement is signalled at 1/32 pixel accuracy\&. When projection of the predicted pixel falls inbetween reference samples, the predicted value for the pixel is linearly interpolated from the reference samples\&. All reference samples are taken from the extended main reference\&. 
.PP
Definition at line \fB460\fP of file \fBIntraPrediction\&.cpp\fP\&.
.SS "void IntraPrediction::xPredIntraBDPCM (const CPelBuf & pSrc, PelBuf & pDst, const uint32_t dirMode, const ClpRng & clpRng)\fC [protected]\fP"

.PP
Definition at line \fB646\fP of file \fBIntraPrediction\&.cpp\fP\&.
.SS "void IntraPrediction::xPredIntraDc (const CPelBuf & pSrc, PelBuf & pDst, const ChannelType channelType, const bool enableBoundaryFilter = \fCtrue\fP)\fC [protected]\fP"

.PP
Definition at line \fB350\fP of file \fBIntraPrediction\&.cpp\fP\&.
.SS "void IntraPrediction::xPredIntraPlanar (const CPelBuf & pSrc, PelBuf & pDst)\fC [protected]\fP"
Function for deriving planar intra prediction\&. This function derives the prediction samples for planar mode (intra coding)\&. 
.PP
Definition at line \fB292\fP of file \fBIntraPrediction\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bool IntraPrediction::m_bestScanRotationMode\fC [protected]\fP"

.PP
Definition at line \fB119\fP of file \fBIntraPrediction\&.h\fP\&.
.SS "ChromaFormat IntraPrediction::m_currChromaFormat\fC [protected]\fP"

.PP
Definition at line \fB114\fP of file \fBIntraPrediction\&.h\fP\&.
.SS "int IntraPrediction::m_leftRefLength\fC [protected]\fP"

.PP
Definition at line \fB117\fP of file \fBIntraPrediction\&.h\fP\&.
.SS "Pel IntraPrediction::m_refBuffer[MAX_NUM_COMPONENT][\fBNUM_PRED_BUF\fP][(MAX_CU_SIZE *2+1+MAX_REF_LINE_IDX) *2]\fC [protected]\fP"

.PP
Definition at line \fB69\fP of file \fBIntraPrediction\&.h\fP\&.
.SS "uint32_t IntraPrediction::m_refBufferStride[MAX_NUM_COMPONENT]\fC [protected]\fP"

.PP
Definition at line \fB70\fP of file \fBIntraPrediction\&.h\fP\&.
.SS "ScanElement* IntraPrediction::m_scanOrder\fC [protected]\fP"

.PP
Definition at line \fB118\fP of file \fBIntraPrediction\&.h\fP\&.
.SS "int IntraPrediction::m_topRefLength\fC [protected]\fP"

.PP
Definition at line \fB116\fP of file \fBIntraPrediction\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
