.TH "deps/base_vvc/minimum_VTM/source/Lib/CommonLib/IntraPrediction.cpp" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deps/base_vvc/minimum_VTM/source/Lib/CommonLib/IntraPrediction.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'IntraPrediction\&.h'\fP
.br
\fC#include 'Unit\&.h'\fP
.br
\fC#include 'UnitTools\&.h'\fP
.br
\fC#include 'Buffer\&.h'\fP
.br
\fC#include 'dtrace_next\&.h'\fP
.br
\fC#include 'Rom\&.h'\fP
.br
\fC#include <memory\&.h>\fP
.br
\fC#include 'CommonLib/InterpolationFilter\&.h'\fP
.br

.SS "Functions"

.PP
.RI "\fB\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "bool \fBisAboveLeftAvailable\fP (const CodingUnit &cu, const ChannelType &chType, const Position &posLT)"
.br
.ti -1c
.RI "int \fBisAboveAvailable\fP (const CodingUnit &cu, const ChannelType &chType, const Position &posLT, const uint32_t uiNumUnitsInPU, const uint32_t unitWidth, bool *validFlags)"
.br
.ti -1c
.RI "int \fBisLeftAvailable\fP (const CodingUnit &cu, const ChannelType &chType, const Position &posLT, const uint32_t uiNumUnitsInPU, const uint32_t unitWidth, bool *validFlags)"
.br
.ti -1c
.RI "int \fBisAboveRightAvailable\fP (const CodingUnit &cu, const ChannelType &chType, const Position &posRT, const uint32_t uiNumUnitsInPU, const uint32_t unitHeight, bool *validFlags)"
.br
.ti -1c
.RI "int \fBisBelowLeftAvailable\fP (const CodingUnit &cu, const ChannelType &chType, const Position &posLB, const uint32_t uiNumUnitsInPU, const uint32_t unitHeight, bool *validFlags)"
.br
.in -1c
.in -1c
.SH "Function Documentation"
.PP 
.SS "int isAboveAvailable (const CodingUnit & cu, const ChannelType & chType, const Position & posLT, const uint32_t uiNumUnitsInPU, const uint32_t unitWidth, bool * validFlags)\fC [inline]\fP"

.PP
Definition at line \fB1219\fP of file \fBIntraPrediction\&.cpp\fP\&.
.SS "bool isAboveLeftAvailable (const CodingUnit & cu, const ChannelType & chType, const Position & posLT)\fC [inline]\fP"

.PP
Definition at line \fB1206\fP of file \fBIntraPrediction\&.cpp\fP\&.
.SS "int isAboveRightAvailable (const CodingUnit & cu, const ChannelType & chType, const Position & posRT, const uint32_t uiNumUnitsInPU, const uint32_t unitHeight, bool * validFlags)\fC [inline]\fP"

.PP
Definition at line \fB1273\fP of file \fBIntraPrediction\&.cpp\fP\&.
.SS "int isBelowLeftAvailable (const CodingUnit & cu, const ChannelType & chType, const Position & posLB, const uint32_t uiNumUnitsInPU, const uint32_t unitHeight, bool * validFlags)\fC [inline]\fP"

.PP
Definition at line \fB1300\fP of file \fBIntraPrediction\&.cpp\fP\&.
.SS "int isLeftAvailable (const CodingUnit & cu, const ChannelType & chType, const Position & posLT, const uint32_t uiNumUnitsInPU, const uint32_t unitWidth, bool * validFlags)\fC [inline]\fP"

.PP
Definition at line \fB1246\fP of file \fBIntraPrediction\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
