.TH "deps/base_vvc/minimum_VTM/source/Lib/CommonLib/IntraPrediction.h" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deps/base_vvc/minimum_VTM/source/Lib/CommonLib/IntraPrediction.h \- prediction class (header)  

.SH SYNOPSIS
.br
.PP
\fC#include 'Unit\&.h'\fP
.br
\fC#include 'Buffer\&.h'\fP
.br
\fC#include 'Picture\&.h'\fP
.br
\fC#include 'MatrixIntraPrediction\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBIntraPrediction\fP"
.br
.in -1c
.in +1c
.ti -1c
.RI "enum \fBPredBuf\fP { \fBPRED_BUF_UNFILTERED\fP = 0, \fBPRED_BUF_FILTERED\fP = 1, \fBNUM_PRED_BUF\fP = 2 }"
.br
.RI "prediction class "
.in -1c
.SH "Detailed Description"
.PP 
prediction class (header) 


.PP
Definition in file \fBIntraPrediction\&.h\fP\&.
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBPredBuf\fP"

.PP
prediction class 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIPRED_BUF_UNFILTERED \fP\fP
.TP
\fB\fIPRED_BUF_FILTERED \fP\fP
.TP
\fB\fINUM_PRED_BUF \fP\fP
.PP
Definition at line \fB57\fP of file \fBIntraPrediction\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
