.TH "decoder/include/InverseQuantize.hpp" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
decoder/include/InverseQuantize.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'Component\&.hpp'\fP
.br
\fC#include 'SignaledConfiguration\&.hpp'\fP
.br
\fC#include 'Surface\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBlctm::InverseQuantize\fP"
.br
.ti -1c
.RI "class \fBlctm::InverseQuantize_SWM\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBlctm\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int32_t \fBlctm::find_quant_matrix_coeff\fP (const \fBPictureConfiguration\fP &picture_configuration, unsigned num_layers, bool horizontal_only, unsigned loq, unsigned layer, bool is_idr, int32_t previous)"
.br
.ti -1c
.RI "int32_t \fBlctm::find_dirq_step_width\fP (int32_t orig_step_width, int32_t quant_matrix_coeff)"
.br
.ti -1c
.RI "int32_t \fBlctm::find_invq_offset\fP (const \fBPictureConfiguration\fP &picture_configuration, int32_t orig_step_width, int32_t dirq_step_width)"
.br
.ti -1c
.RI "int32_t \fBlctm::find_invq_step_width\fP (const \fBPictureConfiguration\fP &picture_configuration, int32_t dirq_step_width, int32_t invq_offset)"
.br
.ti -1c
.RI "int32_t \fBlctm::find_layer_deadzone\fP (int32_t orig_step_width, int32_t dirq_step_width)"
.br
.ti -1c
.RI "int32_t \fBlctm::find_invq_applied_offset\fP (const \fBPictureConfiguration\fP &picture_configuration, int32_t invq_offset, int32_t layer_deadzone)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const uint8_t \fBdefault_qm_coefficient_4x4\fP [][16]"
.br
.ti -1c
.RI "const uint8_t \fBdefault_qm_coefficient_2x2\fP [][4]"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const uint8_t default_qm_coefficient_2x2[][4]\fC [extern]\fP"

.PP
Definition at line \fB54\fP of file \fBInverseQuantize\&.cpp\fP\&.
.SS "const uint8_t default_qm_coefficient_4x4[][16]\fC [extern]\fP"

.PP
Definition at line \fB48\fP of file \fBInverseQuantize\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
