.TH "decoder/src/InverseQuantize.cpp" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
decoder/src/InverseQuantize.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'InverseQuantize\&.hpp'\fP
.br
\fC#include <cmath>\fP
.br
\fC#include 'Misc\&.hpp'\fP
.br
\fC#include 'Surface\&.hpp'\fP
.br
\fC#include 'TemporalDecode\&.hpp'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBlctm\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int32_t \fBlctm::find_quant_matrix_coeff\fP (const \fBPictureConfiguration\fP &picture_configuration, unsigned num_layers, bool horizontal_only, unsigned loq, unsigned layer, bool is_idr, int32_t previous)"
.br
.ti -1c
.RI "int32_t \fBlctm::find_dirq_step_width\fP (int32_t orig_step_width, int32_t quant_matrix_coeff)"
.br
.ti -1c
.RI "int32_t \fBlctm::find_invq_offset\fP (const \fBPictureConfiguration\fP &picture_configuration, int32_t orig_step_width, int32_t dirq_step_width)"
.br
.ti -1c
.RI "int32_t \fBlctm::find_invq_step_width\fP (const \fBPictureConfiguration\fP &picture_configuration, int32_t dirq_step_width, int32_t invq_offset)"
.br
.ti -1c
.RI "int32_t \fBlctm::find_layer_deadzone\fP (int32_t orig_step_width, int32_t dirq_step_width)"
.br
.ti -1c
.RI "int32_t \fBlctm::find_invq_applied_offset\fP (const \fBPictureConfiguration\fP &picture_configuration, int32_t invq_offset, int32_t layer_deadzone)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const uint8_t \fBdefault_qm_coefficient_4x4\fP [3][16]"
.br
.ti -1c
.RI "const uint8_t \fBdefault_qm_coefficient_2x2\fP [3][4]"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const uint8_t default_qm_coefficient_2x2[3][4]"
\fBInitial value:\fP.PP
.nf
= {
    {    0u,     2u,     0u,     0u},
    {   32u,     3u,     0u,    32u},
    {    0u,     3u,     0u,    32u}
}
.fi

.PP
Definition at line \fB54\fP of file \fBInverseQuantize\&.cpp\fP\&.
.SS "const uint8_t default_qm_coefficient_4x4[3][16]"
\fBInitial value:\fP.PP
.nf
= {
    {   13u,    26u,    19u,    32u,    52u,     1u,    78u,     9u,    13u,    26u,    19u,    32u,   150u,    91u,    91u,    19u},
    {   13u,    26u,    19u,    32u,    52u,     1u,    78u,     9u,    26u,    72u,     0u,     3u,   150u,    91u,    91u,    19u},
    {    0u,     0u,     0u,     2u,    52u,     1u,    78u,     9u,    26u,    72u,     0u,     3u,   150u,    91u,    91u,    19u}
}
.fi

.PP
Definition at line \fB48\fP of file \fBInverseQuantize\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
