.TH "deps/json/include/nlohmann/json.hpp" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deps/json/include/nlohmann/json.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <algorithm>\fP
.br
\fC#include <cassert>\fP
.br
\fC#include <ciso646>\fP
.br
\fC#include <cstddef>\fP
.br
\fC#include <functional>\fP
.br
\fC#include <initializer_list>\fP
.br
\fC#include <iosfwd>\fP
.br
\fC#include <iterator>\fP
.br
\fC#include <numeric>\fP
.br
\fC#include <string>\fP
.br
\fC#include <utility>\fP
.br
\fC#include <cstdint>\fP
.br
\fC#include <map>\fP
.br
\fC#include <memory>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <type_traits>\fP
.br
\fC#include <limits>\fP
.br
\fC#include <exception>\fP
.br
\fC#include <stdexcept>\fP
.br
\fC#include <array>\fP
.br
\fC#include <forward_list>\fP
.br
\fC#include <tuple>\fP
.br
\fC#include <unordered_map>\fP
.br
\fC#include <valarray>\fP
.br
\fC#include <cstring>\fP
.br
\fC#include <istream>\fP
.br
\fC#include <clocale>\fP
.br
\fC#include <cstdlib>\fP
.br
\fC#include <cstdio>\fP
.br
\fC#include <cmath>\fP
.br
\fC#include <ios>\fP
.br
\fC#include <ostream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBnlohmann::detail::index_sequence< Ints >\fP"
.br
.ti -1c
.RI "struct \fBnlohmann::detail::merge_and_renumber< index_sequence< I1\&.\&.\&. >, index_sequence< I2\&.\&.\&. > >\fP"
.br
.ti -1c
.RI "struct \fBnlohmann::detail::make_index_sequence< N >\fP"
.br
.ti -1c
.RI "struct \fBnlohmann::detail::make_index_sequence< 0 >\fP"
.br
.ti -1c
.RI "struct \fBnlohmann::detail::make_index_sequence< 1 >\fP"
.br
.ti -1c
.RI "struct \fBnlohmann::detail::priority_tag< N >\fP"
.br
.ti -1c
.RI "struct \fBnlohmann::detail::priority_tag< 0 >\fP"
.br
.ti -1c
.RI "struct \fBnlohmann::detail::static_const< T >\fP"
.br
.ti -1c
.RI "struct \fBnlohmann::detail::make_void< Ts >\fP"
.br
.ti -1c
.RI "struct \fBnlohmann::detail::nonesuch\fP"
.br
.ti -1c
.RI "struct \fBnlohmann::detail::detector< Default, AlwaysVoid, Op, Args >\fP"
.br
.ti -1c
.RI "struct \fBnlohmann::detail::detector< Default, void_t< Op< Args\&.\&.\&. > >, Op, Args\&.\&.\&. >\fP"
.br
.ti -1c
.RI "struct \fBnlohmann::detail::is_basic_json< typename >\fP"
.br
.ti -1c
.RI "struct \fBnlohmann::detail::is_basic_json< NLOHMANN_BASIC_JSON_TPL >\fP"
.br
.ti -1c
.RI "struct \fBnlohmann::detail::has_from_json< BasicJsonType, T, typename >\fP"
.br
.ti -1c
.RI "struct \fBnlohmann::detail::has_from_json< BasicJsonType, T, enable_if_t< not is_basic_json< T >::value > >\fP"
.br
.ti -1c
.RI "struct \fBnlohmann::detail::has_non_default_from_json< BasicJsonType, T, typename >\fP"
.br
.ti -1c
.RI "struct \fBnlohmann::detail::has_non_default_from_json< BasicJsonType, T, enable_if_t< not is_basic_json< T >::value > >\fP"
.br
.ti -1c
.RI "struct \fBnlohmann::detail::has_to_json< BasicJsonType, T, typename >\fP"
.br
.ti -1c
.RI "struct \fBnlohmann::detail::has_to_json< BasicJsonType, T, enable_if_t< not is_basic_json< T >::value > >\fP"
.br
.ti -1c
.RI "struct \fBnlohmann::detail::is_iterator_traits< T, typename >\fP"
.br
.ti -1c
.RI "struct \fBnlohmann::detail::is_iterator_traits< std::iterator_traits< T > >\fP"
.br
.ti -1c
.RI "struct \fBnlohmann::detail::is_complete_type< T, typename >\fP"
.br
.ti -1c
.RI "struct \fBnlohmann::detail::is_complete_type< T, decltype(void(sizeof(T)))>\fP"
.br
.ti -1c
.RI "struct \fBnlohmann::detail::is_compatible_object_type_impl< BasicJsonType, CompatibleObjectType, typename >\fP"
.br
.ti -1c
.RI "struct \fBnlohmann::detail::is_compatible_object_type_impl< BasicJsonType, CompatibleObjectType, enable_if_t< is_detected< mapped_type_t, CompatibleObjectType >::value and is_detected< key_type_t, CompatibleObjectType >::value > >\fP"
.br
.ti -1c
.RI "struct \fBnlohmann::detail::is_compatible_object_type< BasicJsonType, CompatibleObjectType >\fP"
.br
.ti -1c
.RI "struct \fBnlohmann::detail::is_constructible_object_type_impl< BasicJsonType, ConstructibleObjectType, typename >\fP"
.br
.ti -1c
.RI "struct \fBnlohmann::detail::is_constructible_object_type_impl< BasicJsonType, ConstructibleObjectType, enable_if_t< is_detected< mapped_type_t, ConstructibleObjectType >::value and is_detected< key_type_t, ConstructibleObjectType >::value > >\fP"
.br
.ti -1c
.RI "struct \fBnlohmann::detail::is_constructible_object_type< BasicJsonType, ConstructibleObjectType >\fP"
.br
.ti -1c
.RI "struct \fBnlohmann::detail::is_compatible_string_type_impl< BasicJsonType, CompatibleStringType, typename >\fP"
.br
.ti -1c
.RI "struct \fBnlohmann::detail::is_compatible_string_type_impl< BasicJsonType, CompatibleStringType, enable_if_t< is_detected_exact< typename BasicJsonType::string_t::value_type, value_type_t, CompatibleStringType >::value > >\fP"
.br
.ti -1c
.RI "struct \fBnlohmann::detail::is_compatible_string_type< BasicJsonType, ConstructibleStringType >\fP"
.br
.ti -1c
.RI "struct \fBnlohmann::detail::is_constructible_string_type_impl< BasicJsonType, ConstructibleStringType, typename >\fP"
.br
.ti -1c
.RI "struct \fBnlohmann::detail::is_constructible_string_type_impl< BasicJsonType, ConstructibleStringType, enable_if_t< is_detected_exact< typename BasicJsonType::string_t::value_type, value_type_t, ConstructibleStringType >::value > >\fP"
.br
.ti -1c
.RI "struct \fBnlohmann::detail::is_constructible_string_type< BasicJsonType, ConstructibleStringType >\fP"
.br
.ti -1c
.RI "struct \fBnlohmann::detail::is_compatible_array_type_impl< BasicJsonType, CompatibleArrayType, typename >\fP"
.br
.ti -1c
.RI "struct \fBnlohmann::detail::is_compatible_array_type_impl< BasicJsonType, CompatibleArrayType, enable_if_t< is_detected< value_type_t, CompatibleArrayType >::value and is_detected< iterator_t, CompatibleArrayType >::value and not is_iterator_traits< std::iterator_traits< CompatibleArrayType > >::value > >\fP"
.br
.ti -1c
.RI "struct \fBnlohmann::detail::is_compatible_array_type< BasicJsonType, CompatibleArrayType >\fP"
.br
.ti -1c
.RI "struct \fBnlohmann::detail::is_constructible_array_type_impl< BasicJsonType, ConstructibleArrayType, typename >\fP"
.br
.ti -1c
.RI "struct \fBnlohmann::detail::is_constructible_array_type_impl< BasicJsonType, ConstructibleArrayType, enable_if_t< std::is_same< ConstructibleArrayType, typename BasicJsonType::value_type >::value > >\fP"
.br
.ti -1c
.RI "struct \fBnlohmann::detail::is_constructible_array_type_impl< BasicJsonType, ConstructibleArrayType, enable_if_t< not std::is_same< ConstructibleArrayType, typename BasicJsonType::value_type >::value and is_detected< value_type_t, ConstructibleArrayType >::value and is_detected< iterator_t, ConstructibleArrayType >::value and is_complete_type< detected_t< value_type_t, ConstructibleArrayType > >::value > >\fP"
.br
.ti -1c
.RI "struct \fBnlohmann::detail::is_constructible_array_type< BasicJsonType, ConstructibleArrayType >\fP"
.br
.ti -1c
.RI "struct \fBnlohmann::detail::is_compatible_integer_type_impl< RealIntegerType, CompatibleNumberIntegerType, typename >\fP"
.br
.ti -1c
.RI "struct \fBnlohmann::detail::is_compatible_integer_type_impl< RealIntegerType, CompatibleNumberIntegerType, enable_if_t< std::is_integral< RealIntegerType >::value and std::is_integral< CompatibleNumberIntegerType >::value and not std::is_same< bool, CompatibleNumberIntegerType >::value > >\fP"
.br
.ti -1c
.RI "struct \fBnlohmann::detail::is_compatible_integer_type< RealIntegerType, CompatibleNumberIntegerType >\fP"
.br
.ti -1c
.RI "struct \fBnlohmann::detail::is_compatible_type_impl< BasicJsonType, CompatibleType, typename >\fP"
.br
.ti -1c
.RI "struct \fBnlohmann::detail::is_compatible_type_impl< BasicJsonType, CompatibleType, enable_if_t< is_complete_type< CompatibleType >::value > >\fP"
.br
.ti -1c
.RI "struct \fBnlohmann::detail::is_compatible_type< BasicJsonType, CompatibleType >\fP"
.br
.ti -1c
.RI "struct \fBnlohmann::detail::position_t\fP"
.br
.RI "struct to capture the start position of the current token "
.ti -1c
.RI "class \fBnlohmann::detail::exception\fP"
.br
.RI "general exception of the \fBbasic_json\fP class "
.ti -1c
.RI "class \fBnlohmann::detail::parse_error\fP"
.br
.RI "exception indicating a parse error "
.ti -1c
.RI "class \fBnlohmann::detail::invalid_iterator\fP"
.br
.RI "exception indicating errors with iterators "
.ti -1c
.RI "class \fBnlohmann::detail::type_error\fP"
.br
.RI "exception indicating executing a member function with a wrong type "
.ti -1c
.RI "class \fBnlohmann::detail::out_of_range\fP"
.br
.RI "exception indicating access out of the defined range "
.ti -1c
.RI "class \fBnlohmann::detail::other_error\fP"
.br
.RI "exception indicating other library errors "
.ti -1c
.RI "struct \fBnlohmann::detail::external_constructor< value_t::boolean >\fP"
.br
.ti -1c
.RI "struct \fBnlohmann::detail::external_constructor< value_t::string >\fP"
.br
.ti -1c
.RI "struct \fBnlohmann::detail::external_constructor< value_t::number_float >\fP"
.br
.ti -1c
.RI "struct \fBnlohmann::detail::external_constructor< value_t::number_unsigned >\fP"
.br
.ti -1c
.RI "struct \fBnlohmann::detail::external_constructor< value_t::number_integer >\fP"
.br
.ti -1c
.RI "struct \fBnlohmann::detail::external_constructor< value_t::array >\fP"
.br
.ti -1c
.RI "struct \fBnlohmann::detail::external_constructor< value_t::object >\fP"
.br
.ti -1c
.RI "struct \fBnlohmann::detail::to_json_fn\fP"
.br
.ti -1c
.RI "struct \fBnlohmann::detail::input_adapter_protocol\fP"
.br
.RI "abstract input adapter interface "
.ti -1c
.RI "class \fBnlohmann::detail::input_stream_adapter\fP"
.br
.ti -1c
.RI "class \fBnlohmann::detail::input_buffer_adapter\fP"
.br
.RI "input adapter for buffer input "
.ti -1c
.RI "struct \fBnlohmann::detail::wide_string_input_helper< WideStringType, T >\fP"
.br
.ti -1c
.RI "struct \fBnlohmann::detail::wide_string_input_helper< WideStringType, 2 >\fP"
.br
.ti -1c
.RI "class \fBnlohmann::detail::wide_string_input_adapter< WideStringType >\fP"
.br
.ti -1c
.RI "class \fBnlohmann::detail::input_adapter\fP"
.br
.ti -1c
.RI "struct \fBnlohmann::detail::is_sax< SAX, BasicJsonType >\fP"
.br
.ti -1c
.RI "struct \fBnlohmann::detail::is_sax_static_asserts< SAX, BasicJsonType >\fP"
.br
.ti -1c
.RI "struct \fBnlohmann::json_sax< BasicJsonType >\fP"
.br
.RI "SAX interface\&. "
.ti -1c
.RI "class \fBnlohmann::detail::json_sax_dom_parser< BasicJsonType >\fP"
.br
.RI "SAX implementation to create a JSON value from SAX events\&. "
.ti -1c
.RI "class \fBnlohmann::detail::json_sax_dom_callback_parser< BasicJsonType >\fP"
.br
.ti -1c
.RI "class \fBnlohmann::detail::json_sax_acceptor< BasicJsonType >\fP"
.br
.ti -1c
.RI "class \fBnlohmann::detail::parser< BasicJsonType >\fP"
.br
.RI "syntax analysis "
.ti -1c
.RI "class \fBnlohmann::detail::primitive_iterator_t\fP"
.br
.ti -1c
.RI "struct \fBnlohmann::detail::internal_iterator< BasicJsonType >\fP"
.br
.RI "an iterator value "
.ti -1c
.RI "class \fBnlohmann::detail::iter_impl< BasicJsonType >\fP"
.br
.RI "a template for a bidirectional iterator for the \fBbasic_json\fP class "
.ti -1c
.RI "struct \fBnlohmann::detail::output_adapter_protocol< CharType >\fP"
.br
.RI "abstract output adapter interface "
.ti -1c
.RI "class \fBnlohmann::detail::output_vector_adapter< CharType >\fP"
.br
.RI "output adapter for byte vectors "
.ti -1c
.RI "class \fBnlohmann::detail::output_stream_adapter< CharType >\fP"
.br
.RI "output adapter for output streams "
.ti -1c
.RI "class \fBnlohmann::detail::output_string_adapter< CharType, StringType >\fP"
.br
.RI "output adapter for basic_string "
.ti -1c
.RI "class \fBnlohmann::detail::output_adapter< CharType, StringType >\fP"
.br
.ti -1c
.RI "class \fBnlohmann::detail::serializer< BasicJsonType >\fP"
.br
.ti -1c
.RI "class \fBnlohmann::json_pointer< BasicJsonType >\fP"
.br
.RI "JSON Pointer\&. "
.ti -1c
.RI "struct \fBnlohmann::adl_serializer< typename, typename >\fP"
.br
.RI "default JSONSerializer template argument "
.ti -1c
.RI "class \fBnlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >\fP"
.br
.RI "a class to store JSON values "
.ti -1c
.RI "struct \fBstd::hash< nlohmann::json >\fP"
.br
.RI "hash value for JSON objects "
.ti -1c
.RI "struct \fBstd::less< ::nlohmann::detail::value_t >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBnlohmann\fP"
.br
.RI "namespace for Niels Lohmann "
.ti -1c
.RI "namespace \fBnlohmann::detail\fP"
.br
.RI "detail namespace with internal helper functions "
.ti -1c
.RI "namespace \fBnlohmann::detail::dtoa_impl\fP"
.br
.RI "implements the Grisu2 algorithm for binary to decimal floating-point conversion\&. "
.ti -1c
.RI "namespace \fBstd\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBNLOHMANN_JSON_VERSION_MAJOR\fP   3"
.br
.ti -1c
.RI "#define \fBNLOHMANN_JSON_VERSION_MINOR\fP   4"
.br
.ti -1c
.RI "#define \fBNLOHMANN_JSON_VERSION_PATCH\fP   0"
.br
.ti -1c
.RI "#define \fBNLOHMANN_JSON_FWD_HPP\fP"
.br
.ti -1c
.RI "#define \fBJSON_DEPRECATED\fP"
.br
.ti -1c
.RI "#define \fBJSON_THROW\fP(exception)   std::abort()"
.br
.ti -1c
.RI "#define \fBJSON_TRY\fP   if(true)"
.br
.ti -1c
.RI "#define \fBJSON_CATCH\fP(exception)   if(false)"
.br
.ti -1c
.RI "#define \fBJSON_INTERNAL_CATCH\fP(exception)   if(false)"
.br
.ti -1c
.RI "#define \fBJSON_LIKELY\fP(x)   x"
.br
.ti -1c
.RI "#define \fBJSON_UNLIKELY\fP(x)   x"
.br
.ti -1c
.RI "#define \fBNLOHMANN_JSON_SERIALIZE_ENUM\fP(ENUM_TYPE, \&.\&.\&.)"
.br
.RI "macro to briefly define a mapping between an enum and JSON "
.ti -1c
.RI "#define \fBNLOHMANN_BASIC_JSON_TPL_DECLARATION\fP"
.br
.ti -1c
.RI "#define \fBNLOHMANN_BASIC_JSON_TPL\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBnlohmann::json\fP = \fBbasic_json\fP<>"
.br
.RI "default JSON class "
.ti -1c
.RI "template<bool B, typename T  = void> using \fBnlohmann::detail::enable_if_t\fP = typename std::enable_if< B, T >::type"
.br
.ti -1c
.RI "template<typename T > using \fBnlohmann::detail::uncvref_t\fP = typename std::remove_cv< typename std::remove_reference< T >::type >::type"
.br
.ti -1c
.RI "template<typename\&.\&.\&. Ts> using \fBnlohmann::detail::index_sequence_for\fP = \fBmake_index_sequence\fP< sizeof\&.\&.\&.(Ts)>"
.br
.ti -1c
.RI "template<typename \&.\&.\&. Ts> using \fBnlohmann::detail::void_t\fP = typename \fBmake_void\fP< Ts\&.\&.\&. >::type"
.br
.ti -1c
.RI "template<template< class\&.\&.\&. > class Op, class\&.\&.\&. Args> using \fBnlohmann::detail::is_detected\fP = typename \fBdetector\fP< \fBnonesuch\fP, void, Op, Args\&.\&.\&. >::value_t"
.br
.ti -1c
.RI "template<template< class\&.\&.\&. > class Op, class\&.\&.\&. Args> using \fBnlohmann::detail::detected_t\fP = typename \fBdetector\fP< \fBnonesuch\fP, void, Op, Args\&.\&.\&. >::type"
.br
.ti -1c
.RI "template<class Default , template< class\&.\&.\&. > class Op, class\&.\&.\&. Args> using \fBnlohmann::detail::detected_or\fP = \fBdetector\fP< Default, void, Op, Args\&.\&.\&. >"
.br
.ti -1c
.RI "template<class Default , template< class\&.\&.\&. > class Op, class\&.\&.\&. Args> using \fBnlohmann::detail::detected_or_t\fP = typename \fBdetected_or\fP< Default, Op, Args\&.\&.\&. >::type"
.br
.ti -1c
.RI "template<class Expected , template< class\&.\&.\&. > class Op, class\&.\&.\&. Args> using \fBnlohmann::detail::is_detected_exact\fP = std::is_same< Expected, \fBdetected_t\fP< Op, Args\&.\&.\&. > >"
.br
.ti -1c
.RI "template<class To , template< class\&.\&.\&. > class Op, class\&.\&.\&. Args> using \fBnlohmann::detail::is_detected_convertible\fP = std::is_convertible< \fBdetected_t\fP< Op, Args\&.\&.\&. >, To >"
.br
.ti -1c
.RI "template<typename T > using \fBnlohmann::detail::mapped_type_t\fP = typename T::mapped_type"
.br
.ti -1c
.RI "template<typename T > using \fBnlohmann::detail::key_type_t\fP = typename T::key_type"
.br
.ti -1c
.RI "template<typename T > using \fBnlohmann::detail::value_type_t\fP = typename T::value_type"
.br
.ti -1c
.RI "template<typename T > using \fBnlohmann::detail::difference_type_t\fP = typename T::difference_type"
.br
.ti -1c
.RI "template<typename T > using \fBnlohmann::detail::pointer_t\fP = typename T::pointer"
.br
.ti -1c
.RI "template<typename T > using \fBnlohmann::detail::reference_t\fP = typename T::reference"
.br
.ti -1c
.RI "template<typename T > using \fBnlohmann::detail::iterator_category_t\fP = typename T::iterator_category"
.br
.ti -1c
.RI "template<typename T > using \fBnlohmann::detail::iterator_t\fP = typename T::iterator"
.br
.ti -1c
.RI "template<typename T , typename\&.\&.\&. Args> using \fBnlohmann::detail::to_json_function\fP = decltype(T::to_json(std::declval< Args >()\&.\&.\&.))"
.br
.ti -1c
.RI "template<typename T , typename\&.\&.\&. Args> using \fBnlohmann::detail::from_json_function\fP = decltype(T::from_json(std::declval< Args >()\&.\&.\&.))"
.br
.ti -1c
.RI "template<typename T , typename U > using \fBnlohmann::detail::get_template_function\fP = decltype(std::declval< T >()\&.template get< U >())"
.br
.ti -1c
.RI "using \fBnlohmann::detail::input_adapter_t\fP = std::shared_ptr< \fBinput_adapter_protocol\fP >"
.br
.RI "a type to simplify interfaces "
.ti -1c
.RI "template<typename T > using \fBnlohmann::detail::null_function_t\fP = decltype(std::declval< T & >()\&.null())"
.br
.ti -1c
.RI "template<typename T > using \fBnlohmann::detail::boolean_function_t\fP = decltype(std::declval< T & >()\&.boolean(std::declval< bool >()))"
.br
.ti -1c
.RI "template<typename T , typename Integer > using \fBnlohmann::detail::number_integer_function_t\fP = decltype(std::declval< T & >()\&.number_integer(std::declval< Integer >()))"
.br
.ti -1c
.RI "template<typename T , typename Unsigned > using \fBnlohmann::detail::number_unsigned_function_t\fP = decltype(std::declval< T & >()\&.number_unsigned(std::declval< Unsigned >()))"
.br
.ti -1c
.RI "template<typename T , typename Float , typename String > using \fBnlohmann::detail::number_float_function_t\fP = decltype(std::declval< T & >()\&.number_float(std::declval< Float >(), std::declval< const String & >()))"
.br
.ti -1c
.RI "template<typename T , typename String > using \fBnlohmann::detail::string_function_t\fP = decltype(std::declval< T & >()\&.string(std::declval< String & >()))"
.br
.ti -1c
.RI "template<typename T > using \fBnlohmann::detail::start_object_function_t\fP = decltype(std::declval< T & >()\&.start_object(std::declval< std::size_t >()))"
.br
.ti -1c
.RI "template<typename T , typename String > using \fBnlohmann::detail::key_function_t\fP = decltype(std::declval< T & >()\&.key(std::declval< String & >()))"
.br
.ti -1c
.RI "template<typename T > using \fBnlohmann::detail::end_object_function_t\fP = decltype(std::declval< T & >()\&.end_object())"
.br
.ti -1c
.RI "template<typename T > using \fBnlohmann::detail::start_array_function_t\fP = decltype(std::declval< T & >()\&.start_array(std::declval< std::size_t >()))"
.br
.ti -1c
.RI "template<typename T > using \fBnlohmann::detail::end_array_function_t\fP = decltype(std::declval< T & >()\&.end_array())"
.br
.ti -1c
.RI "template<typename T , typename Exception > using \fBnlohmann::detail::parse_error_function_t\fP = decltype(std::declval< T & >()\&.\fBparse_error\fP(std::declval< std::size_t >(), std::declval< const std::string & >(), std::declval< const Exception & >()))"
.br
.ti -1c
.RI "template<typename CharType > using \fBnlohmann::detail::output_adapter_t\fP = std::shared_ptr< \fBoutput_adapter_protocol\fP< CharType > >"
.br
.RI "a type to simplify interfaces "
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum class \fBnlohmann::detail::input_format_t\fP { \fBnlohmann::detail::json\fP, \fBnlohmann::detail::cbor\fP, \fBnlohmann::detail::msgpack\fP, \fBnlohmann::detail::ubjson\fP, \fBnlohmann::detail::bson\fP }"
.br
.RI "the supported input formats "
.ti -1c
.RI "enum class \fBnlohmann::detail::error_handler_t\fP { \fBnlohmann::detail::strict\fP, \fBnlohmann::detail::replace\fP, \fBnlohmann::detail::ignore\fP }"
.br
.RI "how to treat decoding errors "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename BasicJsonType , typename T , \fBenable_if_t\fP< std::is_same< T, typename BasicJsonType::boolean_t >::value, int >  = 0> void \fBnlohmann::detail::to_json\fP (BasicJsonType &j, T b) noexcept"
.br
.ti -1c
.RI "template<typename BasicJsonType , typename CompatibleString , \fBenable_if_t\fP< std::is_constructible< typename BasicJsonType::string_t, CompatibleString >::value, int >  = 0> void \fBnlohmann::detail::to_json\fP (BasicJsonType &j, const CompatibleString &s)"
.br
.ti -1c
.RI "template<typename BasicJsonType > void \fBnlohmann::detail::to_json\fP (BasicJsonType &j, typename BasicJsonType::string_t &&s)"
.br
.ti -1c
.RI "template<typename BasicJsonType , typename FloatType , \fBenable_if_t\fP< std::is_floating_point< FloatType >::value, int >  = 0> void \fBnlohmann::detail::to_json\fP (BasicJsonType &j, FloatType val) noexcept"
.br
.ti -1c
.RI "template<typename BasicJsonType , typename CompatibleNumberUnsignedType , \fBenable_if_t\fP< \fBis_compatible_integer_type\fP< typename BasicJsonType::number_unsigned_t, CompatibleNumberUnsignedType >::value, int >  = 0> void \fBnlohmann::detail::to_json\fP (BasicJsonType &j, CompatibleNumberUnsignedType val) noexcept"
.br
.ti -1c
.RI "template<typename BasicJsonType , typename CompatibleNumberIntegerType , \fBenable_if_t\fP< \fBis_compatible_integer_type\fP< typename BasicJsonType::number_integer_t, CompatibleNumberIntegerType >::value, int >  = 0> void \fBnlohmann::detail::to_json\fP (BasicJsonType &j, CompatibleNumberIntegerType val) noexcept"
.br
.ti -1c
.RI "template<typename BasicJsonType , typename EnumType , \fBenable_if_t\fP< std::is_enum< EnumType >::value, int >  = 0> void \fBnlohmann::detail::to_json\fP (BasicJsonType &j, EnumType e) noexcept"
.br
.ti -1c
.RI "template<typename BasicJsonType > void \fBnlohmann::detail::to_json\fP (BasicJsonType &j, const std::vector< bool > &e)"
.br
.ti -1c
.RI "template<typename BasicJsonType , typename CompatibleArrayType , \fBenable_if_t\fP< \fBis_compatible_array_type\fP< BasicJsonType, CompatibleArrayType >::value and not \fBis_compatible_object_type\fP< BasicJsonType, CompatibleArrayType >::value and not \fBis_compatible_string_type\fP< BasicJsonType, CompatibleArrayType >::value and not \fBis_basic_json\fP< CompatibleArrayType >::value, int >  = 0> void \fBnlohmann::detail::to_json\fP (BasicJsonType &j, const CompatibleArrayType &arr)"
.br
.ti -1c
.RI "template<typename BasicJsonType , typename T , \fBenable_if_t\fP< std::is_convertible< T, BasicJsonType >::value, int >  = 0> void \fBnlohmann::detail::to_json\fP (BasicJsonType &j, const std::valarray< T > &arr)"
.br
.ti -1c
.RI "template<typename BasicJsonType > void \fBnlohmann::detail::to_json\fP (BasicJsonType &j, typename BasicJsonType::array_t &&arr)"
.br
.ti -1c
.RI "template<typename BasicJsonType , typename CompatibleObjectType , \fBenable_if_t\fP< \fBis_compatible_object_type\fP< BasicJsonType, CompatibleObjectType >::value and not \fBis_basic_json\fP< CompatibleObjectType >::value, int >  = 0> void \fBnlohmann::detail::to_json\fP (BasicJsonType &j, const CompatibleObjectType &obj)"
.br
.ti -1c
.RI "template<typename BasicJsonType > void \fBnlohmann::detail::to_json\fP (BasicJsonType &j, typename BasicJsonType::object_t &&obj)"
.br
.ti -1c
.RI "template<typename BasicJsonType , typename T , std::size_t N, \fBenable_if_t\fP< not std::is_constructible< typename BasicJsonType::string_t, const T(&)[N]>::value, int >  = 0> void \fBnlohmann::detail::to_json\fP (BasicJsonType &j, const T(&arr)[N])"
.br
.ti -1c
.RI "template<typename BasicJsonType , typename\&.\&.\&. Args> void \fBnlohmann::detail::to_json\fP (BasicJsonType &j, const std::pair< Args\&.\&.\&. > &p)"
.br
.ti -1c
.RI "template<typename BasicJsonType , typename T , \fBenable_if_t\fP< std::is_same< T, typename iteration_proxy< typename BasicJsonType::iterator >::iteration_proxy_internal >::value, int >  = 0> void \fBnlohmann::detail::to_json\fP (BasicJsonType &j, const T &b)"
.br
.ti -1c
.RI "template<typename BasicJsonType , typename Tuple , std::size_t\&.\&.\&. Idx> void \fBnlohmann::detail::to_json_tuple_impl\fP (BasicJsonType &j, const Tuple &t, \fBindex_sequence\fP< Idx\&.\&.\&. >)"
.br
.ti -1c
.RI "template<typename BasicJsonType , typename\&.\&.\&. Args> void \fBnlohmann::detail::to_json\fP (BasicJsonType &j, const std::tuple< Args\&.\&.\&. > &t)"
.br
.ti -1c
.RI "template<> void \fBstd::swap< nlohmann::json >\fP (\fBnlohmann::json\fP &j1, \fBnlohmann::json\fP &j2) noexcept(is_nothrow_move_constructible< \fBnlohmann::json\fP >::value and is_nothrow_move_assignable< \fBnlohmann::json\fP >::value)"
.br
.RI "exchanges the values of two JSON objects "
.ti -1c
.RI "\fBnlohmann::json\fP \fBoperator''_json\fP (const char *s, std::size_t n)"
.br
.RI "user-defined string literal for JSON values "
.ti -1c
.RI "\fBnlohmann::json::json_pointer\fP \fBoperator''_json_pointer\fP (const char *s, std::size_t n)"
.br
.RI "user-defined string literal for JSON pointer "
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define JSON_CATCH(exception)   if(false)"

.PP
Definition at line \fB164\fP of file \fBjson\&.hpp\fP\&.
.SS "#define JSON_DEPRECATED"

.PP
Definition at line \fB152\fP of file \fBjson\&.hpp\fP\&.
.SS "#define JSON_INTERNAL_CATCH(exception)   if(false)"

.PP
Definition at line \fB165\fP of file \fBjson\&.hpp\fP\&.
.SS "#define JSON_LIKELY(x)   x"

.PP
Definition at line \fB193\fP of file \fBjson\&.hpp\fP\&.
.SS "#define JSON_THROW(exception)   std::abort()"

.PP
Definition at line \fB162\fP of file \fBjson\&.hpp\fP\&.
.SS "#define JSON_TRY   if(true)"

.PP
Definition at line \fB163\fP of file \fBjson\&.hpp\fP\&.
.SS "#define JSON_UNLIKELY(x)   x"

.PP
Definition at line \fB194\fP of file \fBjson\&.hpp\fP\&.
.SS "#define NLOHMANN_BASIC_JSON_TPL"
\fBValue:\fP.PP
.nf
    basic_json<ObjectType, ArrayType, StringType, BooleanType,             \\
    NumberIntegerType, NumberUnsignedType, NumberFloatType,                \\
    AllocatorType, JSONSerializer>
.fi

.PP
Definition at line \fB247\fP of file \fBjson\&.hpp\fP\&.
.SS "#define NLOHMANN_BASIC_JSON_TPL_DECLARATION"
\fBValue:\fP.PP
.nf
    template<template<typename, typename, typename\&.\&.\&.> class ObjectType,   \\
             template<typename, typename\&.\&.\&.> class ArrayType,              \\
             class StringType, class BooleanType, class NumberIntegerType, \\
             class NumberUnsignedType, class NumberFloatType,              \\
             template<typename> class AllocatorType,                       \\
             template<typename, typename = void> class JSONSerializer>
.fi

.PP
Definition at line \fB239\fP of file \fBjson\&.hpp\fP\&.
.SS "#define NLOHMANN_JSON_FWD_HPP"

.PP
Definition at line \fB51\fP of file \fBjson\&.hpp\fP\&.
.SS "#define NLOHMANN_JSON_SERIALIZE_ENUM(ENUM_TYPE,  \&.\&.\&.)"
\fBValue:\fP.PP
.nf
    template<typename BasicJsonType>                                                           \\
    inline void to_json(BasicJsonType& j, const ENUM_TYPE& e)                                  \\
    {                                                                                          \\
        static_assert(std::is_enum<ENUM_TYPE>::value, #ENUM_TYPE " must be an enum!");         \\
        static const std::pair<ENUM_TYPE, BasicJsonType> m[] = __VA_ARGS__;                    \\
        auto it = std::find_if(std::begin(m), std::end(m),                                     \\
                               [e](const std::pair<ENUM_TYPE, BasicJsonType>& ej_pair) \-> bool \\
        {                                                                                      \\
            return ej_pair\&.first == e;                                                         \\
        });                                                                                    \\
        j = ((it != std::end(m)) ? it : std::begin(m))\->second;                                \\
    }                                                                                          \\
    template<typename BasicJsonType>                                                           \\
    inline void from_json(const BasicJsonType& j, ENUM_TYPE& e)                                \\
    {                                                                                          \\
        static_assert(std::is_enum<ENUM_TYPE>::value, #ENUM_TYPE " must be an enum!");         \\
        static const std::pair<ENUM_TYPE, BasicJsonType> m[] = __VA_ARGS__;                    \\
        auto it = std::find_if(std::begin(m), std::end(m),                                     \\
                               [j](const std::pair<ENUM_TYPE, BasicJsonType>& ej_pair) \-> bool \\
        {                                                                                      \\
            return ej_pair\&.second == j;                                                        \\
        });                                                                                    \\
        e = ((it != std::end(m)) ? it : std::begin(m))\->first;                                 \\
    }
.fi

.PP
macro to briefly define a mapping between an enum and JSON 
.PP
\fBSince\fP
.RS 4
version 3\&.4\&.0 
.RE
.PP

.PP
Definition at line \fB210\fP of file \fBjson\&.hpp\fP\&.
.SS "#define NLOHMANN_JSON_VERSION_MAJOR   3"

.PP
Definition at line \fB33\fP of file \fBjson\&.hpp\fP\&.
.SS "#define NLOHMANN_JSON_VERSION_MINOR   4"

.PP
Definition at line \fB34\fP of file \fBjson\&.hpp\fP\&.
.SS "#define NLOHMANN_JSON_VERSION_PATCH   0"

.PP
Definition at line \fB35\fP of file \fBjson\&.hpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "\fBnlohmann::json\fP operator''_json (const char * s, std::size_t n)\fC [inline]\fP"

.PP
user-defined string literal for JSON values This operator implements a user-defined string literal for JSON objects\&. It can be used by adding \fC'_json'\fP to a string literal and returns a JSON object if no parse error occurred\&.
.PP
\fBParameters\fP
.RS 4
\fIs\fP a string representation of a JSON object 
.br
\fIn\fP the length of string \fIs\fP 
.RE
.PP
\fBReturns\fP
.RS 4
a JSON object
.RE
.PP
\fBSince\fP
.RS 4
version 1\&.0\&.0 
.RE
.PP

.PP
Definition at line \fB20235\fP of file \fBjson\&.hpp\fP\&.
.SS "\fBnlohmann::json::json_pointer\fP operator''_json_pointer (const char * s, std::size_t n)\fC [inline]\fP"

.PP
user-defined string literal for JSON pointer This operator implements a user-defined string literal for JSON Pointers\&. It can be used by adding \fC'_json_pointer'\fP to a string literal and returns a JSON pointer object if no parse error occurred\&.
.PP
\fBParameters\fP
.RS 4
\fIs\fP a string representation of a JSON Pointer 
.br
\fIn\fP the length of string \fIs\fP 
.RE
.PP
\fBReturns\fP
.RS 4
a JSON pointer object
.RE
.PP
\fBSince\fP
.RS 4
version 2\&.0\&.0 
.RE
.PP

.PP
Definition at line \fB20253\fP of file \fBjson\&.hpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
