.TH "encoder/include/LayerEncodeFlags.hpp" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
encoder/include/LayerEncodeFlags.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <bitset>\fP
.br
\fC#include <memory>\fP
.br
\fC#include 'Types\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBlctm::EncodeBits\fP"
.br
.ti -1c
.RI "class \fBlctm::EncodeBits_DD\fP"
.br
.ti -1c
.RI "class \fBlctm::EncodeBits_DDS\fP"
.br
.ti -1c
.RI "class \fBlctm::LayerEncodeFlags\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBlctm\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBlctm::EncodingMode\fP { \fBlctm::ENCODE_ALL\fP = 0, \fBlctm::Ax\fP = 1, \fBlctm::AA\fP = 2, \fBlctm::NA\fP = 3, \fBlctm::ENCODE_NONE\fP = 4 }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
