.TH "util/src/LcevcMd5.cpp" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
util/src/LcevcMd5.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <math\&.h>\fP
.br
\fC#include 'LcevcMd5\&.hpp'\fP
.br
\fC#include <stdio\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTX_SHIFT1\fP(log2_size)   ((log2_size)\-1 + BIT_DEPTH \- 8)"
.br
.ti -1c
.RI "#define \fBTX_SHIFT2\fP(log2_size)   ((log2_size) + 6)"
.br
.ti -1c
.RI "#define \fBMD5FUNC\fP(f,  w,  x,  y,  z,  msg1,  s,  msg2)   (w += f(x, y, z) + msg1 + msg2, w = w << s | w >> (32 \- s), w += x)"
.br
.ti -1c
.RI "#define \fBFF\fP(x,  y,  z)   (z ^ (x & (y ^ z)))"
.br
.ti -1c
.RI "#define \fBGG\fP(x,  y,  z)   (y ^ (z & (x ^ y)))"
.br
.ti -1c
.RI "#define \fBHH\fP(x,  y,  z)   (x ^ y ^ z)"
.br
.ti -1c
.RI "#define \fBII\fP(x,  y,  z)   (y ^ (x | ~z))"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBlcevc_md5_init\fP (\fBLCEVC_MD5\fP *md5)"
.br
.ti -1c
.RI "void \fBlcevc_md5_update\fP (\fBLCEVC_MD5\fP *md5, void *buf_t, \fBu32\fP len)"
.br
.ti -1c
.RI "void \fBlcevc_md5_update_16\fP (\fBLCEVC_MD5\fP *md5, void *buf_t, \fBu32\fP len)"
.br
.ti -1c
.RI "void \fBlcevc_md5_finish\fP (\fBLCEVC_MD5\fP *md5, \fBu8\fP digest[16])"
.br
.ti -1c
.RI "int \fBlcevc_md5_imgb\fP (\fBLCEVC_IMGB\fP *imgb, \fBu8\fP digest[\fBN_C\fP][16])"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define FF(x, y, z)   (z ^ (x & (y ^ z)))"

.PP
Definition at line \fB48\fP of file \fBLcevcMd5\&.cpp\fP\&.
.SS "#define GG(x, y, z)   (y ^ (z & (x ^ y)))"

.PP
Definition at line \fB49\fP of file \fBLcevcMd5\&.cpp\fP\&.
.SS "#define HH(x, y, z)   (x ^ y ^ z)"

.PP
Definition at line \fB50\fP of file \fBLcevcMd5\&.cpp\fP\&.
.SS "#define II(x, y, z)   (y ^ (x | ~z))"

.PP
Definition at line \fB51\fP of file \fBLcevcMd5\&.cpp\fP\&.
.SS "#define MD5FUNC(f, w, x, y, z, msg1, s, msg2)   (w += f(x, y, z) + msg1 + msg2, w = w << s | w >> (32 \- s), w += x)"

.PP
Definition at line \fB47\fP of file \fBLcevcMd5\&.cpp\fP\&.
.SS "#define TX_SHIFT1(log2_size)   ((log2_size)\-1 + BIT_DEPTH \- 8)"

.PP
Definition at line \fB42\fP of file \fBLcevcMd5\&.cpp\fP\&.
.SS "#define TX_SHIFT2(log2_size)   ((log2_size) + 6)"

.PP
Definition at line \fB44\fP of file \fBLcevcMd5\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "void lcevc_md5_finish (\fBLCEVC_MD5\fP * md5, \fBu8\fP digest[16])"

.PP
Definition at line \fB243\fP of file \fBLcevcMd5\&.cpp\fP\&.
.SS "int lcevc_md5_imgb (\fBLCEVC_IMGB\fP * imgb, \fBu8\fP digest[N_C][16])"

.PP
Definition at line \fB291\fP of file \fBLcevcMd5\&.cpp\fP\&.
.SS "void lcevc_md5_init (\fBLCEVC_MD5\fP * md5)"

.PP
Definition at line \fB154\fP of file \fBLcevcMd5\&.cpp\fP\&.
.SS "void lcevc_md5_update (\fBLCEVC_MD5\fP * md5, void * buf_t, \fBu32\fP len)"

.PP
Definition at line \fB166\fP of file \fBLcevcMd5\&.cpp\fP\&.
.SS "void lcevc_md5_update_16 (\fBLCEVC_MD5\fP * md5, void * buf_t, \fBu32\fP len)"

.PP
Definition at line \fB201\fP of file \fBLcevcMd5\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
