.TH "lctm::ConformancePadding" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lctm::ConformancePadding
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Encoder\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned \fBleft\fP"
.br
.ti -1c
.RI "unsigned \fBtop\fP"
.br
.ti -1c
.RI "unsigned \fBright\fP"
.br
.ti -1c
.RI "unsigned \fBbottom\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB59\fP of file \fBEncoder\&.hpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "unsigned lctm::ConformancePadding::bottom"

.PP
Definition at line \fB63\fP of file \fBEncoder\&.hpp\fP\&.
.SS "unsigned lctm::ConformancePadding::left"

.PP
Definition at line \fB60\fP of file \fBEncoder\&.hpp\fP\&.
.SS "unsigned lctm::ConformancePadding::right"

.PP
Definition at line \fB62\fP of file \fBEncoder\&.hpp\fP\&.
.SS "unsigned lctm::ConformancePadding::top"

.PP
Definition at line \fB61\fP of file \fBEncoder\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
