.TH "lctm::Parameters" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lctm::Parameters
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Parameters\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "const \fBParameterRef\fP \fBoperator[]\fP (const std::string &\fBname\fP) const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "\fBstatic\fP \fBParametersBuilder\fP \fBbuild\fP ()"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBParametersBuilder\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB58\fP of file \fBParameters\&.hpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBParametersBuilder\fP lctm::Parameters::build ()\fC [static]\fP"

.PP
Definition at line \fB84\fP of file \fBParameters\&.cpp\fP\&.
.SS "const \fBParameterRef\fP lctm::Parameters::operator[] (const std::string & name) const"

.PP
Definition at line \fB88\fP of file \fBParameters\&.cpp\fP\&.
.SH "Friends And Related Symbol Documentation"
.PP 
.SS "friend class \fBParametersBuilder\fP\fC [friend]\fP"

.PP
Definition at line \fB64\fP of file \fBParameters\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
