.TH "lctm::Parameter< T >" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lctm::Parameter< T >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Parameters\&.hpp>\fP
.PP
Inherits \fBlctm::ParameterBase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBParameter\fP (const std::string &\fBname\fP, const T &value)"
.br
.in -1c

Public Member Functions inherited from \fBlctm::ParameterBase\fP
.in +1c
.ti -1c
.RI "\fBParameterBase\fP (const std::string &\fBname\fP)"
.br
.ti -1c
.RI "virtual \fB~ParameterBase\fP ()=0"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Attributes inherited from \fBlctm::ParameterBase\fP
.in +1c
.ti -1c
.RI "friend \fBParameterRef\fP"
.br
.ti -1c
.RI "const std::string \fBname_\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T>
.br
class lctm::Parameter< T >"
.PP
Definition at line \fB98\fP of file \fBParameters\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename T > \fBlctm::Parameter\fP< T >::Parameter (const std::string & name, const T & value)\fC [inline]\fP"

.PP
Definition at line \fB100\fP of file \fBParameters\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
