.TH "lctm::EntropyDecoderSizes" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lctm::EntropyDecoderSizes
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <EntropyDecoder\&.hpp>\fP
.PP
Inherits \fBlctm::Component\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEntropyDecoderSizes\fP ()"
.br
.ti -1c
.RI "\fBSurface\fP \fBprocess\fP (unsigned width, unsigned height, \fBBitstreamUnpacker\fP &b, const std::vector< bool > entropy_enabled, const unsigned tile_idx, \fBCompressionType\fP compression_type)"
.br
.in -1c

Public Member Functions inherited from \fBlctm::Component\fP
.in +1c
.ti -1c
.RI "\fBComponent\fP (const std::string &\fBname\fP)"
.br
.ti -1c
.RI "virtual \fB~Component\fP ()=0"
.br
.ti -1c
.RI "virtual const std::string \fBname\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB125\fP of file \fBEntropyDecoder\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "lctm::EntropyDecoderSizes::EntropyDecoderSizes ()\fC [inline]\fP"

.PP
Definition at line \fB130\fP of file \fBEntropyDecoder\&.hpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBSurface\fP lctm::EntropyDecoderSizes::process (unsigned width, unsigned height, \fBBitstreamUnpacker\fP & b, const std::vector< bool > entropy_enabled, const unsigned tile_idx, \fBCompressionType\fP compression_type)"

.PP
Definition at line \fB425\fP of file \fBEntropyDecoder\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
