.TH "lctm::rbsp_decoder" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lctm::rbsp_decoder
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBrbsp_decoder\fP (const uint8_t *d, size_t l, bool e)"
.br
.ti -1c
.RI "uint8_t \fBget_byte\fP ()"
.br
.ti -1c
.RI "uint8_t * \fBcopy_sei\fP (uint8_t *dst, size_t \fBlen\fP)"
.br
.ti -1c
.RI "void \fBcopy\fP (\fBPacketBuilder\fP *dst)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "const uint8_t * \fBdata\fP"
.br
.ti -1c
.RI "size_t \fBlen\fP"
.br
.ti -1c
.RI "bool \fBemulatiom_prevention\fP"
.br
.ti -1c
.RI "uint32_t \fBemitted\fP"
.br
.ti -1c
.RI "size_t \fBoffs\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB59\fP of file \fBScanEnhancement\&.cpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "lctm::rbsp_decoder::rbsp_decoder (const uint8_t * d, size_t l, bool e)\fC [inline]\fP"

.PP
Definition at line \fB61\fP of file \fBScanEnhancement\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void lctm::rbsp_decoder::copy (\fBPacketBuilder\fP * dst)"

.PP
Definition at line \fB97\fP of file \fBScanEnhancement\&.cpp\fP\&.
.SS "uint8_t * lctm::rbsp_decoder::copy_sei (uint8_t * dst, size_t len)"

.PP
Definition at line \fB90\fP of file \fBScanEnhancement\&.cpp\fP\&.
.SS "uint8_t lctm::rbsp_decoder::get_byte ()"

.PP
Definition at line \fB74\fP of file \fBScanEnhancement\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "const uint8_t* lctm::rbsp_decoder::data\fC [protected]\fP"

.PP
Definition at line \fB67\fP of file \fBScanEnhancement\&.cpp\fP\&.
.SS "uint32_t lctm::rbsp_decoder::emitted\fC [protected]\fP"

.PP
Definition at line \fB70\fP of file \fBScanEnhancement\&.cpp\fP\&.
.SS "bool lctm::rbsp_decoder::emulatiom_prevention\fC [protected]\fP"

.PP
Definition at line \fB69\fP of file \fBScanEnhancement\&.cpp\fP\&.
.SS "size_t lctm::rbsp_decoder::len\fC [protected]\fP"

.PP
Definition at line \fB68\fP of file \fBScanEnhancement\&.cpp\fP\&.
.SS "size_t lctm::rbsp_decoder::offs\fC [protected]\fP"

.PP
Definition at line \fB71\fP of file \fBScanEnhancement\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
