.TH "lctm::UserDataClear" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lctm::UserDataClear
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <TemporalDecode\&.hpp>\fP
.PP
Inherits \fBlctm::Component\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBUserDataClear\fP ()"
.br
.ti -1c
.RI "\fBSurface\fP \fBprocess\fP (const \fBSurface\fP &symbols, \fBUserDataMode\fP user_data)"
.br
.in -1c

Public Member Functions inherited from \fBlctm::Component\fP
.in +1c
.ti -1c
.RI "\fBComponent\fP (const std::string &\fBname\fP)"
.br
.ti -1c
.RI "virtual \fB~Component\fP ()=0"
.br
.ti -1c
.RI "virtual const std::string \fBname\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB94\fP of file \fBTemporalDecode\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "lctm::UserDataClear::UserDataClear ()\fC [inline]\fP"

.PP
Definition at line \fB96\fP of file \fBTemporalDecode\&.hpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBSurface\fP lctm::UserDataClear::process (const \fBSurface\fP & symbols, \fBUserDataMode\fP user_data)"

.PP
Definition at line \fB375\fP of file \fBTemporalDecode\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
