.TH "lctm::Packet" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lctm::Packet
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Packet\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPacket\fP ()=default"
.br
.ti -1c
.RI "\fBPacket\fP (const \fBPacket\fP &\fBpacket\fP)=default"
.br
.ti -1c
.RI "\fBPacket\fP & \fBoperator=\fP (const \fBPacket\fP &src)=default"
.br
.ti -1c
.RI "std::string \fBname\fP () const"
.br
.ti -1c
.RI "uint64_t \fBtimestamp\fP () const"
.br
.ti -1c
.RI "uint64_t \fBchecksum\fP () const"
.br
.ti -1c
.RI "unsigned \fBsize\fP () const"
.br
.ti -1c
.RI "bool \fBempty\fP () const"
.br
.ti -1c
.RI "std::string \fBdump\fP () const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "\fBstatic\fP \fBPacketBuilder\fP \fBbuild\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB55\fP of file \fBPacket\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "lctm::Packet::Packet ()\fC [default]\fP"

.SS "lctm::Packet::Packet (const \fBPacket\fP & packet)\fC [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBPacketBuilder\fP lctm::Packet::build ()\fC [static]\fP"

.PP
Definition at line \fB58\fP of file \fBPacket\&.cpp\fP\&.
.SS "uint64_t lctm::Packet::checksum () const"

.PP
Definition at line \fB62\fP of file \fBPacket\&.cpp\fP\&.
.SS "std::string lctm::Packet::dump () const"

.PP
Definition at line \fB73\fP of file \fBPacket\&.cpp\fP\&.
.SS "bool lctm::Packet::empty () const"

.PP
Definition at line \fB56\fP of file \fBPacket\&.cpp\fP\&.
.SS "std::string lctm::Packet::name () const"

.PP
Definition at line \fB53\fP of file \fBPacket\&.cpp\fP\&.
.SS "\fBPacket\fP & lctm::Packet::operator= (const \fBPacket\fP & src)\fC [default]\fP"

.SS "unsigned lctm::Packet::size () const"

.PP
Definition at line \fB55\fP of file \fBPacket\&.cpp\fP\&.
.SS "uint64_t lctm::Packet::timestamp () const"

.PP
Definition at line \fB54\fP of file \fBPacket\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
