.TH "lctm::Surface" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lctm::Surface
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Surface\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSurface\fP ()=default"
.br
.ti -1c
.RI "\fBSurface\fP (\fBconst\fP \fBSurface\fP &p)=default"
.br
.ti -1c
.RI "\fBSurface\fP & \fBoperator=\fP (\fBconst\fP \fBSurface\fP &\fBsrc\fP)=default"
.br
.ti -1c
.RI "template<\fBtypename\fP \fBT\fP , \fBunsigned\fP S = 0> \fBSurfaceView\fP< \fBT\fP, \fBS\fP > \fBview_as\fP () \fBconst\fP"
.br
.ti -1c
.RI "std::string \fBname\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBuint64_t\fP \fBchecksum\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBunsigned\fP \fBbpp\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBunsigned\fP \fBwidth\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBunsigned\fP \fBheight\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBunsigned\fP \fBempty\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBvoid\fP \fBdump\fP (\fBconst\fP std::string &\fBname\fP) \fBconst\fP"
.br
.ti -1c
.RI "\fBvoid\fP \fBdump_p420\fP (\fBconst\fP std::string &\fBname\fP) \fBconst\fP"
.br
.ti -1c
.RI "\fBvoid\fP \fBdump_yuv\fP (\fBconst\fP std::string &\fBname\fP, \fBSurface\fP(&planes)[3], \fBImageDescription\fP desc, \fBbool\fP \fBdecorate\fP=\fBfalse\fP) \fBconst\fP"
.br
.ti -1c
.RI "\fBvoid\fP \fBdump_image\fP (\fBconst\fP std::string &\fBname\fP) \fBconst\fP"
.br
.ti -1c
.RI "template<\fBtypename\fP \fBT\fP , \fBunsigned\fP S> \fBSurfaceView\fP< \fBT\fP, \fBS\fP > \fBview_as\fP () \fBconst\fP"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename T > \fBstatic\fP \fBSurfaceBuilder\fP< T > \fBbuild_from\fP ()"
.br
.ti -1c
.RI "\fBstatic\fP \fBvoid\fP \fBset_dump_surfaces\fP (\fBbool\fP \fBb\fP)"
.br
.ti -1c
.RI "\fBstatic\fP \fBbool\fP \fBget_dump_surfaces\fP ()"
.br
.ti -1c
.RI "\fBstatic\fP \fBvoid\fP \fBdump_layers\fP (\fBconst\fP \fBSurface\fP \fBsrc_surface\fP[], \fBconst\fP std::string &\fBname\fP, \fBconst\fP \fBunsigned\fP transform_block_size)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "template<\fBtypename\fP \fBT\fP , \fBunsigned\fP S> \fBclass\fP \fBSurfaceView\fP"
.br
.ti -1c
.RI "template<\fBtypename\fP \fBT\fP > \fBclass\fP \fBSurfaceBuilder\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB151\fP of file \fBSurface\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "lctm::Surface::Surface ()\fC [default]\fP"

.SS "lctm::Surface::Surface (\fBconst\fP \fBSurface\fP & p)\fC [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBunsigned\fP lctm::Surface::bpp () const\fC [inline]\fP"

.PP
Definition at line \fB169\fP of file \fBSurface\&.hpp\fP\&.
.SS "template<typename T > \fBstatic\fP \fBSurfaceBuilder\fP< T > lctm::Surface::build_from ()\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line \fB158\fP of file \fBSurface\&.hpp\fP\&.
.SS "\fBuint64_t\fP lctm::Surface::checksum () const"

.PP
Definition at line \fB263\fP of file \fBSurface\&.cpp\fP\&.
.SS "\fBvoid\fP lctm::Surface::dump (\fBconst\fP std::string & name) const"

.PP
Definition at line \fB134\fP of file \fBSurface\&.cpp\fP\&.
.SS "\fBvoid\fP lctm::Surface::dump_image (\fBconst\fP std::string & name) const"

.PP
Definition at line \fB240\fP of file \fBSurface\&.cpp\fP\&.
.SS "\fBvoid\fP lctm::Surface::dump_layers (\fBconst\fP \fBSurface\fP src_surface[], \fBconst\fP std::string & name, \fBconst\fP \fBunsigned\fP transform_block_size)\fC [static]\fP"

.PP
Definition at line \fB163\fP of file \fBSurface\&.cpp\fP\&.
.SS "\fBvoid\fP lctm::Surface::dump_p420 (\fBconst\fP std::string & name) const"

.PP
Definition at line \fB68\fP of file \fBSurface\&.cpp\fP\&.
.SS "\fBvoid\fP lctm::Surface::dump_yuv (\fBconst\fP std::string & name, \fBSurface\fP(&) planes[3], \fBImageDescription\fP desc, \fBbool\fP decorate = \fC\fBfalse\fP\fP) const"

.PP
Definition at line \fB98\fP of file \fBSurface\&.cpp\fP\&.
.SS "\fBunsigned\fP lctm::Surface::empty () const\fC [inline]\fP"

.PP
Definition at line \fB175\fP of file \fBSurface\&.hpp\fP\&.
.SS "\fBbool\fP lctm::Surface::get_dump_surfaces ()\fC [static]\fP"

.PP
Definition at line \fB64\fP of file \fBSurface\&.cpp\fP\&.
.SS "\fBunsigned\fP lctm::Surface::height () const\fC [inline]\fP"

.PP
Definition at line \fB173\fP of file \fBSurface\&.hpp\fP\&.
.SS "std::string lctm::Surface::name () const\fC [inline]\fP"

.PP
Definition at line \fB164\fP of file \fBSurface\&.hpp\fP\&.
.SS "\fBSurface\fP & \fBlctm::Surface::operator\fP= (\fBconst\fP \fBSurface\fP & src)\fC [default]\fP"

.SS "\fBvoid\fP lctm::Surface::set_dump_surfaces (\fBbool\fP b)\fC [static]\fP"

.PP
Definition at line \fB62\fP of file \fBSurface\&.cpp\fP\&.
.SS "template<\fBtypename\fP \fBT\fP , \fBunsigned\fP S = 0> \fBSurfaceView\fP< \fBT\fP, \fBS\fP > lctm::Surface::view_as () const"

.SS "template<\fBtypename\fP \fBT\fP , \fBunsigned\fP S> \fBSurfaceView\fP< \fBT\fP, \fBS\fP > lctm::Surface::view_as () const"

.PP
Definition at line \fB274\fP of file \fBSurfaceImpl\&.hpp\fP\&.
.SS "\fBunsigned\fP lctm::Surface::width () const\fC [inline]\fP"

.PP
Definition at line \fB172\fP of file \fBSurface\&.hpp\fP\&.
.SH "Friends And Related Symbol Documentation"
.PP 
.SS "template<\fBtypename\fP \fBT\fP > \fBfriend\fP \fBclass\fP \fBSurfaceBuilder\fP\fC [friend]\fP"

.PP
Definition at line \fB201\fP of file \fBSurface\&.hpp\fP\&.
.SS "template<\fBtypename\fP \fBT\fP , \fBunsigned\fP S> \fBfriend\fP \fBclass\fP \fBSurfaceView\fP\fC [friend]\fP"

.PP
Definition at line \fB200\fP of file \fBSurface\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
