.TH "lctm::EntropyModelRleFlag" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lctm::EntropyModelRleFlag
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEntropyModelRleFlag\fP ()"
.br
.ti -1c
.RI "void \fBencode_high_count\fP (State s, unsigned c)"
.br
.ti -1c
.RI "void \fBencode_run\fP (bool value, unsigned count)"
.br
.ti -1c
.RI "\fBEncodedChunk\fP \fBfinish\fP (bool start_value)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB261\fP of file \fBEntropyEncoder\&.cpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "lctm::EntropyModelRleFlag::EntropyModelRleFlag ()\fC [inline]\fP"

.PP
Definition at line \fB266\fP of file \fBEntropyEncoder\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void lctm::EntropyModelRleFlag::encode_high_count (State s, unsigned c)"

.PP
Definition at line \fB292\fP of file \fBEntropyEncoder\&.cpp\fP\&.
.SS "void lctm::EntropyModelRleFlag::encode_run (bool value, unsigned count)"

.PP
Definition at line \fB298\fP of file \fBEntropyEncoder\&.cpp\fP\&.
.SS "\fBEncodedChunk\fP lctm::EntropyModelRleFlag::finish (bool start_value)"

.PP
Definition at line \fB307\fP of file \fBEntropyEncoder\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
