.TH "lctm::SignaledConfiguration" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lctm::SignaledConfiguration
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SignaledConfiguration\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBSequenceConfiguration\fP \fBsequence_configuration\fP"
.br
.ti -1c
.RI "\fBGlobalConfiguration\fP \fBglobal_configuration\fP"
.br
.ti -1c
.RI "\fBPictureConfiguration\fP \fBpicture_configuration\fP"
.br
.ti -1c
.RI "\fBAdditionalInfo\fP \fBadditional_info\fP"
.br
.ti -1c
.RI "\fBSurfaceConfiguration\fP \fBsurface_configuration\fP [\fBMAX_NUM_PLANES\fP][\fBMAX_NUM_LOQS\fP][\fBMAX_NUM_LAYERS\fP]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB218\fP of file \fBSignaledConfiguration\&.hpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBAdditionalInfo\fP lctm::SignaledConfiguration::additional_info"

.PP
Definition at line \fB222\fP of file \fBSignaledConfiguration\&.hpp\fP\&.
.SS "\fBGlobalConfiguration\fP lctm::SignaledConfiguration::global_configuration"

.PP
Definition at line \fB220\fP of file \fBSignaledConfiguration\&.hpp\fP\&.
.SS "\fBPictureConfiguration\fP lctm::SignaledConfiguration::picture_configuration"

.PP
Definition at line \fB221\fP of file \fBSignaledConfiguration\&.hpp\fP\&.
.SS "\fBSequenceConfiguration\fP lctm::SignaledConfiguration::sequence_configuration"

.PP
Definition at line \fB219\fP of file \fBSignaledConfiguration\&.hpp\fP\&.
.SS "\fBSurfaceConfiguration\fP lctm::SignaledConfiguration::surface_configuration[\fBMAX_NUM_PLANES\fP][\fBMAX_NUM_LOQS\fP][\fBMAX_NUM_LAYERS\fP]"

.PP
Definition at line \fB223\fP of file \fBSignaledConfiguration\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
