.TH "lctm::YUVWriter" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lctm::YUVWriter
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <YUVWriter\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBwrite\fP (const \fBImage\fP &image)"
.br
.ti -1c
.RI "void \fBwrite\fP (const \fBSurface\fP &surface)"
.br
.ti -1c
.RI "void \fBupdate_data\fP (const \fBImageDescription\fP &\fBimage_description\fP)"
.br
.ti -1c
.RI "void \fBclose\fP ()"
.br
.ti -1c
.RI "std::string \fBfilename\fP () const"
.br
.ti -1c
.RI "\fBImageDescription\fP \fBimage_description\fP () const"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "std::unique_ptr< \fBYUVWriter\fP > \fBCreateYUVWriter\fP (const std::string &\fBname\fP)"
.br
.ti -1c
.RI "std::unique_ptr< \fBYUVWriter\fP > \fBCreateYUVWriter\fP (const std::string &\fBname\fP, const \fBImageDescription\fP &\fBimage_description\fP, bool decorate)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB49\fP of file \fBYUVWriter\&.hpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void lctm::YUVWriter::close ()"

.PP
Definition at line \fB103\fP of file \fBYUVWriter\&.cpp\fP\&.
.SS "std::string lctm::YUVWriter::filename () const\fC [inline]\fP"

.PP
Definition at line \fB60\fP of file \fBYUVWriter\&.hpp\fP\&.
.SS "\fBImageDescription\fP lctm::YUVWriter::image_description () const\fC [inline]\fP"

.PP
Definition at line \fB62\fP of file \fBYUVWriter\&.hpp\fP\&.
.SS "void lctm::YUVWriter::update_data (const \fBImageDescription\fP & image_description)"

.PP
Definition at line \fB59\fP of file \fBYUVWriter\&.cpp\fP\&.
.SS "void lctm::YUVWriter::write (const \fBImage\fP & image)"

.PP
Definition at line \fB83\fP of file \fBYUVWriter\&.cpp\fP\&.
.SS "void lctm::YUVWriter::write (const \fBSurface\fP & surface)"

.PP
Definition at line \fB95\fP of file \fBYUVWriter\&.cpp\fP\&.
.SH "Friends And Related Symbol Documentation"
.PP 
.SS "std::unique_ptr< \fBYUVWriter\fP > CreateYUVWriter (const std::string & name)\fC [friend]\fP"

.PP
Definition at line \fB112\fP of file \fBYUVWriter\&.cpp\fP\&.
.SS "std::unique_ptr< \fBYUVWriter\fP > CreateYUVWriter (const std::string & name, const \fBImageDescription\fP & image_description, bool decorate)\fC [friend]\fP"

.PP
Definition at line \fB108\fP of file \fBYUVWriter\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
