.TH "lctm::ParametersBuilder" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lctm::ParametersBuilder
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Parameters\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBParametersBuilder\fP & \fBset_json\fP (const std::string &str)"
.br
.ti -1c
.RI "template<typename T > \fBParametersBuilder\fP & \fBset\fP (const std::string &\fBname\fP, const T &value)"
.br
.ti -1c
.RI "\fBParameters\fP \fBfinish\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB74\fP of file \fBParameters\&.hpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBParameters\fP lctm::ParametersBuilder::finish ()"

.PP
Definition at line \fB86\fP of file \fBParameters\&.cpp\fP\&.
.SS "template<typename T > \fBParametersBuilder\fP & lctm::ParametersBuilder::set (const std::string & name, const T & value)"

.PP
Definition at line \fB107\fP of file \fBParameters\&.hpp\fP\&.
.SS "\fBParametersBuilder\fP & lctm::ParametersBuilder::set_json (const std::string & str)"

.PP
Definition at line \fB51\fP of file \fBParameters\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
