.TH "lctm::TemporalUpdate" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lctm::TemporalUpdate
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <TemporalDecode\&.hpp>\fP
.PP
Inherits \fBlctm::Component\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTemporalUpdate\fP ()"
.br
.ti -1c
.RI "\fBSurface\fP \fBprocess\fP (const \fBSurface\fP &temporal_plane, const \fBSurface\fP &residual_plane, \fBSurface\fP &mask_plane, unsigned transform_block_size, bool refresh, bool use_reduced_signalling)"
.br
.in -1c

Public Member Functions inherited from \fBlctm::Component\fP
.in +1c
.ti -1c
.RI "\fBComponent\fP (const std::string &\fBname\fP)"
.br
.ti -1c
.RI "virtual \fB~Component\fP ()=0"
.br
.ti -1c
.RI "virtual const std::string \fBname\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB58\fP of file \fBTemporalDecode\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "lctm::TemporalUpdate::TemporalUpdate ()\fC [inline]\fP"

.PP
Definition at line \fB60\fP of file \fBTemporalDecode\&.hpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBSurface\fP lctm::TemporalUpdate::process (const \fBSurface\fP & temporal_plane, const \fBSurface\fP & residual_plane, \fBSurface\fP & mask_plane, unsigned transform_block_size, bool refresh, bool use_reduced_signalling)"

.PP
Definition at line \fB100\fP of file \fBTemporalDecode\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
