.TH "lctm::ParameterRef" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lctm::ParameterRef
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Parameters\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBParameterRef\fP (const std::string &\fBname\fP, const \fBParameterBase\fP *base)"
.br
.ti -1c
.RI "bool \fBempty\fP () const"
.br
.ti -1c
.RI "template<typename T > bool \fBis\fP () const"
.br
.ti -1c
.RI "template<typename T > T \fBget\fP (T dflt=T()) const"
.br
.ti -1c
.RI "template<typename T > T \fBget\fP (const \fBParameters\fP &defaults) const"
.br
.ti -1c
.RI "template<typename T > T \fBget_enum\fP (T dflt) const"
.br
.ti -1c
.RI "template<typename T > T \fBget_enum\fP (const \fBParameters\fP &defaults) const"
.br
.ti -1c
.RI "template<typename T > T * \fBget_vector\fP (T *dest, unsigned size) const"
.br
.ti -1c
.RI "template<> unsigned \fBget\fP (unsigned dflt) const"
.br
.ti -1c
.RI "template<> int \fBget\fP (int dflt) const"
.br
.ti -1c
.RI "template<> unsigned \fBget\fP (const \fBParameters\fP &defaults) const"
.br
.ti -1c
.RI "template<> int \fBget\fP (const \fBParameters\fP &defaults) const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB119\fP of file \fBParameters\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "lctm::ParameterRef::ParameterRef (const std::string & name, const \fBParameterBase\fP * base)\fC [inline]\fP"

.PP
Definition at line \fB121\fP of file \fBParameters\&.hpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "bool lctm::ParameterRef::empty () const\fC [inline]\fP"

.PP
Definition at line \fB124\fP of file \fBParameters\&.hpp\fP\&.
.SS "template<typename T > T lctm::ParameterRef::get (const \fBParameters\fP & defaults) const\fC [inline]\fP"

.PP
Definition at line \fB150\fP of file \fBParameters\&.hpp\fP\&.
.SS "template<> unsigned lctm::ParameterRef::get (const \fBParameters\fP & defaults) const\fC [inline]\fP"

.PP
Definition at line \fB259\fP of file \fBParameters\&.hpp\fP\&.
.SS "template<> int lctm::ParameterRef::get (const \fBParameters\fP & defaults) const\fC [inline]\fP"

.PP
Definition at line \fB284\fP of file \fBParameters\&.hpp\fP\&.
.SS "template<> int lctm::ParameterRef::get (int dflt) const\fC [inline]\fP"

.PP
Definition at line \fB246\fP of file \fBParameters\&.hpp\fP\&.
.SS "template<typename T > T lctm::ParameterRef::get (T dflt = \fCT()\fP) const\fC [inline]\fP"

.PP
Definition at line \fB136\fP of file \fBParameters\&.hpp\fP\&.
.SS "template<> unsigned lctm::ParameterRef::get (unsigned dflt) const\fC [inline]\fP"

.PP
Definition at line \fB224\fP of file \fBParameters\&.hpp\fP\&.
.SS "template<typename T > T lctm::ParameterRef::get_enum (const \fBParameters\fP & defaults) const\fC [inline]\fP"

.PP
Definition at line \fB179\fP of file \fBParameters\&.hpp\fP\&.
.SS "template<typename T > T lctm::ParameterRef::get_enum (T dflt) const\fC [inline]\fP"

.PP
Definition at line \fB166\fP of file \fBParameters\&.hpp\fP\&.
.SS "template<typename T > T * lctm::ParameterRef::get_vector (T * dest, unsigned size) const\fC [inline]\fP"

.PP
Definition at line \fB196\fP of file \fBParameters\&.hpp\fP\&.
.SS "template<typename T > bool lctm::ParameterRef::is () const\fC [inline]\fP"

.PP
Definition at line \fB127\fP of file \fBParameters\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
