.TH "lctm::EntropyDecoderResidualsBase" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lctm::EntropyDecoderResidualsBase
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <EntropyDecoder\&.hpp>\fP
.PP
Inherits \fBlctm::Component\fP\&.
.PP
Inherited by \fBlctm::EntropyDecoderResiduals\fP\fC [protected]\fP, and \fBlctm::EntropyDecoderResidualsTiled\fP\fC [protected]\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBrle_pel_t\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEntropyDecoderResidualsBase\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBlctm::Component\fP
.in +1c
.ti -1c
.RI "\fBComponent\fP (const std::string &\fBname\fP)"
.br
.ti -1c
.RI "virtual \fB~Component\fP ()=0"
.br
.ti -1c
.RI "virtual const std::string \fBname\fP () const"
.br
.in -1c
.SS "Protected Types"

.in +1c
.ti -1c
.RI "enum { \fBSTATE_LSB\fP, \fBSTATE_MSB\fP, \fBSTATE_ZERO\fP, \fBSTATE_COUNT\fP }"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBrle_pel_t\fP \fBdecode_pel\fP (\fBSymbolSource\fP &source) const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB53\fP of file \fBEntropyDecoder\&.hpp\fP\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "anonymous enum\fC [protected]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fISTATE_LSB \fP\fP
.TP
\fB\fISTATE_MSB \fP\fP
.TP
\fB\fISTATE_ZERO \fP\fP
.TP
\fB\fISTATE_COUNT \fP\fP
.PP
Definition at line \fB60\fP of file \fBEntropyDecoder\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "lctm::EntropyDecoderResidualsBase::EntropyDecoderResidualsBase ()\fC [inline]\fP"

.PP
Definition at line \fB56\fP of file \fBEntropyDecoder\&.hpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBEntropyDecoderResidualsBase::rle_pel_t\fP lctm::EntropyDecoderResidualsBase::decode_pel (\fBSymbolSource\fP & source) const\fC [protected]\fP"

.PP
Definition at line \fB141\fP of file \fBEntropyDecoder\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
