.TH "lctm::PacketBuilder" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lctm::PacketBuilder
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Packet\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPacketBuilder\fP ()"
.br
.ti -1c
.RI "\fBPacketBuilder\fP & \fBcontents\fP (const \fBPacketView\fP &view, unsigned offset, unsigned \fBsize\fP)"
.br
.ti -1c
.RI "\fBPacketBuilder\fP & \fBcontents\fP (const uint8_t *\fBdata\fP, unsigned \fBsize\fP)"
.br
.ti -1c
.RI "\fBPacketBuilder\fP & \fBcontents\fP (const std::vector< uint8_t > \fBdata\fP)"
.br
.ti -1c
.RI "\fBPacketBuilder\fP & \fBreserve\fP (unsigned \fBsize\fP)"
.br
.ti -1c
.RI "\fBPacketBuilder\fP & \fBname\fP (const std::string &name)"
.br
.ti -1c
.RI "\fBPacketBuilder\fP & \fBtimestamp\fP (uint64_t timestamp)"
.br
.ti -1c
.RI "void \fBresize\fP (unsigned \fBsize\fP)"
.br
.ti -1c
.RI "\fBPacket\fP \fBfinish\fP ()"
.br
.ti -1c
.RI "uint8_t * \fBdata\fP () const"
.br
.ti -1c
.RI "unsigned \fBsize\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB124\fP of file \fBPacket\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "lctm::PacketBuilder::PacketBuilder ()"

.PP
Definition at line \fB81\fP of file \fBPacket\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBPacketBuilder\fP & lctm::PacketBuilder::contents (const \fBPacketView\fP & view, unsigned offset, unsigned size)"

.PP
Definition at line \fB84\fP of file \fBPacket\&.cpp\fP\&.
.SS "\fBPacketBuilder\fP & lctm::PacketBuilder::contents (const std::vector< uint8_t > data)"

.PP
Definition at line \fB106\fP of file \fBPacket\&.cpp\fP\&.
.SS "\fBPacketBuilder\fP & lctm::PacketBuilder::contents (const uint8_t * data, unsigned size)"

.PP
Definition at line \fB99\fP of file \fBPacket\&.cpp\fP\&.
.SS "uint8_t * lctm::PacketBuilder::data () const"

.PP
Definition at line \fB117\fP of file \fBPacket\&.cpp\fP\&.
.SS "\fBPacket\fP lctm::PacketBuilder::finish ()"

.PP
Definition at line \fB147\fP of file \fBPacket\&.cpp\fP\&.
.SS "\fBPacketBuilder\fP & lctm::PacketBuilder::name (const std::string & name)"

.PP
Definition at line \fB128\fP of file \fBPacket\&.cpp\fP\&.
.SS "\fBPacketBuilder\fP & lctm::PacketBuilder::reserve (unsigned size)"

.PP
Definition at line \fB108\fP of file \fBPacket\&.cpp\fP\&.
.SS "void lctm::PacketBuilder::resize (unsigned size)"

.PP
Definition at line \fB138\fP of file \fBPacket\&.cpp\fP\&.
.SS "unsigned lctm::PacketBuilder::size () const"

.PP
Definition at line \fB122\fP of file \fBPacket\&.cpp\fP\&.
.SS "\fBPacketBuilder\fP & lctm::PacketBuilder::timestamp (uint64_t timestamp)"

.PP
Definition at line \fB133\fP of file \fBPacket\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
