.TH "lctm::EntropyDecoderResidualsBase::rle_pel_t" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lctm::EntropyDecoderResidualsBase::rle_pel_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <EntropyDecoder\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int16_t \fBpel\fP"
.br
.ti -1c
.RI "unsigned \fBzero_runlength\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB62\fP of file \fBEntropyDecoder\&.hpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int16_t lctm::EntropyDecoderResidualsBase::rle_pel_t::pel"

.PP
Definition at line \fB63\fP of file \fBEntropyDecoder\&.hpp\fP\&.
.SS "unsigned lctm::EntropyDecoderResidualsBase::rle_pel_t::zero_runlength"

.PP
Definition at line \fB64\fP of file \fBEntropyDecoder\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
