.TH "lctm::HuffmanEncoderBuilder" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lctm::HuffmanEncoderBuilder
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <HuffmanEncoder\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBadd_symbol\fP (unsigned symbol, unsigned count)"
.br
.ti -1c
.RI "\fBHuffmanEncoder\fP \fBfinish\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB76\fP of file \fBHuffmanEncoder\&.hpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void lctm::HuffmanEncoderBuilder::add_symbol (unsigned symbol, unsigned count)"

.PP
Definition at line \fB51\fP of file \fBHuffmanEncoder\&.cpp\fP\&.
.SS "\fBHuffmanEncoder\fP lctm::HuffmanEncoderBuilder::finish ()"

.PP
Definition at line \fB70\fP of file \fBHuffmanEncoder\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
