.TH "lctm::BufferVector" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lctm::BufferVector
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBlctm::Buffer\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB~BufferVector\fP () override"
.br
.ti -1c
.RI "\fBBufferVector\fP (const uint8_t *data, unsigned size)"
.br
.ti -1c
.RI "\fBBufferVector\fP (unsigned size)"
.br
.ti -1c
.RI "void \fBmap_read\fP (unsigned offset, unsigned size, const uint8_t *&mapped_data, unsigned &mapped_size) const override"
.br
.ti -1c
.RI "void \fBmap_write\fP (unsigned offset, unsigned size, uint8_t *&mapped_data, unsigned &mapped_size) override"
.br
.ti -1c
.RI "void \fBunmap\fP () const override"
.br
.in -1c

Public Member Functions inherited from \fBlctm::Buffer\fP
.in +1c
.ti -1c
.RI "virtual \fB~Buffer\fP ()=0"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Member Functions inherited from \fBlctm::Buffer\fP
.in +1c
.ti -1c
.RI "\fBBuffer\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB70\fP of file \fBBuffer\&.cpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "lctm::BufferVector::~BufferVector ()\fC [inline]\fP, \fC [override]\fP"

.PP
Definition at line \fB72\fP of file \fBBuffer\&.cpp\fP\&.
.SS "lctm::BufferVector::BufferVector (const uint8_t * data, unsigned size)\fC [inline]\fP"

.PP
Definition at line \fB74\fP of file \fBBuffer\&.cpp\fP\&.
.SS "lctm::BufferVector::BufferVector (unsigned size)\fC [inline]\fP"

.PP
Definition at line \fB76\fP of file \fBBuffer\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void lctm::BufferVector::map_read (unsigned offset, unsigned size, const uint8_t *& mapped_data, unsigned & mapped_size) const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBlctm::Buffer\fP\&.
.PP
Definition at line \fB78\fP of file \fBBuffer\&.cpp\fP\&.
.SS "void lctm::BufferVector::map_write (unsigned offset, unsigned size, uint8_t *& mapped_data, unsigned & mapped_size)\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBlctm::Buffer\fP\&.
.PP
Definition at line \fB86\fP of file \fBBuffer\&.cpp\fP\&.
.SS "void lctm::BufferVector::unmap () const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBlctm::Buffer\fP\&.
.PP
Definition at line \fB94\fP of file \fBBuffer\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
