.TH "lctm::Quantize" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lctm::Quantize
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Quantize\&.hpp>\fP
.PP
Inherits \fBlctm::Component\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBQuantize\fP ()"
.br
.ti -1c
.RI "\fBSurface\fP \fBprocess\fP (const \fBSurface\fP &src, int32_t dirq_step_width, int32_t deadzone, const \fBSurface\fP &pixel_sad, unsigned transform_block_size, unsigned threshold)"
.br
.in -1c

Public Member Functions inherited from \fBlctm::Component\fP
.in +1c
.ti -1c
.RI "\fBComponent\fP (const std::string &\fBname\fP)"
.br
.ti -1c
.RI "virtual \fB~Component\fP ()=0"
.br
.ti -1c
.RI "virtual const std::string \fBname\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB47\fP of file \fBQuantize\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "lctm::Quantize::Quantize ()\fC [inline]\fP"

.PP
Definition at line \fB49\fP of file \fBQuantize\&.hpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBSurface\fP lctm::Quantize::process (const \fBSurface\fP & src, int32_t dirq_step_width, int32_t deadzone, const \fBSurface\fP & pixel_sad, unsigned transform_block_size, unsigned threshold)"

.PP
Definition at line \fB49\fP of file \fBQuantize\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
