.TH "lctm::BitstreamPacker::ScopedContextLabel" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lctm::BitstreamPacker::ScopedContextLabel
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <BitstreamPacker\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBScopedContextLabel\fP (\fBBitstreamPacker\fP &b, const std::string &l)"
.br
.ti -1c
.RI "\fB~ScopedContextLabel\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB81\fP of file \fBBitstreamPacker\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "lctm::BitstreamPacker::ScopedContextLabel::ScopedContextLabel (\fBBitstreamPacker\fP & b, const std::string & l)\fC [inline]\fP"

.PP
Definition at line \fB83\fP of file \fBBitstreamPacker\&.hpp\fP\&.
.SS "lctm::BitstreamPacker::ScopedContextLabel::~ScopedContextLabel ()\fC [inline]\fP"

.PP
Definition at line \fB85\fP of file \fBBitstreamPacker\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
