.TH "lctm::HuffmanCode" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lctm::HuffmanCode
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <HuffmanDecoder\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHuffmanCode\fP (unsigned s, unsigned b)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned \fBsymbol\fP"
.br
.ti -1c
.RI "unsigned \fBbits\fP"
.br
.ti -1c
.RI "unsigned \fBvalue\fP"
.br
.ti -1c
.RI "unsigned \fBcount\fP = 0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB46\fP of file \fBHuffmanDecoder\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "lctm::HuffmanCode::HuffmanCode (unsigned s, unsigned b)\fC [inline]\fP"

.PP
Definition at line \fB47\fP of file \fBHuffmanDecoder\&.hpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "unsigned lctm::HuffmanCode::bits"

.PP
Definition at line \fB49\fP of file \fBHuffmanDecoder\&.hpp\fP\&.
.SS "unsigned lctm::HuffmanCode::count = 0"

.PP
Definition at line \fB52\fP of file \fBHuffmanDecoder\&.hpp\fP\&.
.SS "unsigned lctm::HuffmanCode::symbol"

.PP
Definition at line \fB48\fP of file \fBHuffmanDecoder\&.hpp\fP\&.
.SS "unsigned lctm::HuffmanCode::value"

.PP
Definition at line \fB50\fP of file \fBHuffmanDecoder\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
