.TH "lctm::SymbolSourceHuffman" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lctm::SymbolSourceHuffman
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBlctm::SymbolSource\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSymbolSourceHuffman\fP (unsigned num_states, \fBBitstreamUnpacker\fP &b)"
.br
.ti -1c
.RI "void \fBstart\fP () override"
.br
.ti -1c
.RI "unsigned \fBget\fP (unsigned state) override"
.br
.ti -1c
.RI "unsigned \fBget_byte\fP () override"
.br
.in -1c

Public Member Functions inherited from \fBlctm::SymbolSource\fP
.in +1c
.ti -1c
.RI "virtual \fB~SymbolSource\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB101\fP of file \fBEntropyDecoder\&.cpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "lctm::SymbolSourceHuffman::SymbolSourceHuffman (unsigned num_states, \fBBitstreamUnpacker\fP & b)\fC [inline]\fP"

.PP
Definition at line \fB103\fP of file \fBEntropyDecoder\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "unsigned lctm::SymbolSourceHuffman::get (unsigned state)\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBlctm::SymbolSource\fP\&.
.PP
Definition at line \fB111\fP of file \fBEntropyDecoder\&.cpp\fP\&.
.SS "unsigned lctm::SymbolSourceHuffman::get_byte ()\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBlctm::SymbolSource\fP\&.
.PP
Definition at line \fB116\fP of file \fBEntropyDecoder\&.cpp\fP\&.
.SS "void lctm::SymbolSourceHuffman::start ()\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBlctm::SymbolSource\fP\&.
.PP
Definition at line \fB105\fP of file \fBEntropyDecoder\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
