.TH "lctm::Image" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lctm::Image
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Image\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBImage\fP ()"
.br
.ti -1c
.RI "\fBImage\fP (const std::string &\fBname\fP, const \fBImageDescription\fP &\fBdescription\fP, uint64_t \fBtimestamp\fP, const std::vector< \fBSurface\fP > &planes)"
.br
.ti -1c
.RI "\fBImage\fP (const std::string &\fBname\fP, const \fBImageDescription\fP &\fBdescription\fP, uint64_t \fBtimestamp\fP, const \fBSurface\fP(&planes)[3])"
.br
.ti -1c
.RI "const \fBSurface\fP & \fBplane\fP (uint32_t p) const"
.br
.ti -1c
.RI "const \fBImageDescription\fP & \fBdescription\fP () const"
.br
.ti -1c
.RI "std::string \fBname\fP () const"
.br
.ti -1c
.RI "uint64_t \fBtimestamp\fP () const"
.br
.ti -1c
.RI "uint64_t \fBnumber\fP () const"
.br
.ti -1c
.RI "uint64_t \fBchecksum\fP () const"
.br
.ti -1c
.RI "bool \fBempty\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB161\fP of file \fBImage\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "lctm::Image::Image ()"

.PP
Definition at line \fB198\fP of file \fBImage\&.cpp\fP\&.
.SS "lctm::Image::Image (const std::string & name, const \fBImageDescription\fP & description, uint64_t timestamp, const std::vector< \fBSurface\fP > & planes)"

.PP
Definition at line \fB185\fP of file \fBImage\&.cpp\fP\&.
.SS "lctm::Image::Image (const std::string & name, const \fBImageDescription\fP & description, uint64_t timestamp, const \fBSurface\fP(&) planes[3])"

.PP
Definition at line \fB190\fP of file \fBImage\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "uint64_t lctm::Image::checksum () const\fC [inline]\fP"

.PP
Definition at line \fB182\fP of file \fBImage\&.hpp\fP\&.
.SS "const \fBImageDescription\fP & lctm::Image::description () const\fC [inline]\fP"

.PP
Definition at line \fB170\fP of file \fBImage\&.hpp\fP\&.
.SS "bool lctm::Image::empty () const\fC [inline]\fP"

.PP
Definition at line \fB184\fP of file \fBImage\&.hpp\fP\&.
.SS "std::string lctm::Image::name () const\fC [inline]\fP"

.PP
Definition at line \fB173\fP of file \fBImage\&.hpp\fP\&.
.SS "uint64_t lctm::Image::number () const\fC [inline]\fP"

.PP
Definition at line \fB179\fP of file \fBImage\&.hpp\fP\&.
.SS "const \fBSurface\fP & lctm::Image::plane (uint32_t p) const"

.PP
Definition at line \fB200\fP of file \fBImage\&.cpp\fP\&.
.SS "uint64_t lctm::Image::timestamp () const\fC [inline]\fP"

.PP
Definition at line \fB176\fP of file \fBImage\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
