.TH "lctm::BaseVideoDecoder" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lctm::BaseVideoDecoder
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <BaseVideoDecoder\&.hpp>\fP
.PP
Inherited by \fBlctm::BaseVideoDecoderCodecApi\fP, \fBlctm::BaseVideoDecoderExternal\fP, \fBlctm::BaseVideoDecoderHM\fP, and \fBlctm::BaseVideoDecoderJM\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBOutput\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef struct \fBCodecImage\fP \fBBasePicture\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBstart\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBstop\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBpush_au\fP (const uint8_t *data, size_t data_size, uint64_t pts, bool is_base_idr, int iPictureType)=0"
.br
.ti -1c
.RI "virtual void \fBStatisticsComputation\fP ()=0"
.br
.ti -1c
.RI "\fBPacket\fP \fBrbsp_encapsulate\fP (const \fBPacket\fP &src) const"
.br
.ti -1c
.RI "virtual \fB~BaseVideoDecoder\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBBaseVideoDecoder\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB61\fP of file \fBBaseVideoDecoder\&.hpp\fP\&.
.SH "Member Typedef Documentation"
.PP 
.SS "typedef struct \fBCodecImage\fP \fBlctm::BaseVideoDecoder::BasePicture\fP"

.PP
Definition at line \fB65\fP of file \fBBaseVideoDecoder\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "virtual lctm::BaseVideoDecoder::~BaseVideoDecoder ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Definition at line \fB99\fP of file \fBBaseVideoDecoder\&.hpp\fP\&.
.SS "lctm::BaseVideoDecoder::BaseVideoDecoder ()\fC [inline]\fP, \fC [protected]\fP"

.PP
Definition at line \fB102\fP of file \fBBaseVideoDecoder\&.hpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual void lctm::BaseVideoDecoder::push_au (const uint8_t * data, size_t data_size, uint64_t pts, bool is_base_idr, int iPictureType)\fC [pure virtual]\fP"

.PP
Implemented in \fBlctm::BaseVideoDecoderExternal\fP, \fBlctm::BaseVideoDecoderHM\fP, \fBlctm::BaseVideoDecoderJM\fP, and \fBlctm::BaseVideoDecoderCodecApi\fP\&.
.SS "\fBPacket\fP lctm::BaseVideoDecoder::rbsp_encapsulate (const \fBPacket\fP & src) const"

.PP
Definition at line \fB424\fP of file \fBBaseVideoDecoder\&.cpp\fP\&.
.SS "virtual void lctm::BaseVideoDecoder::start ()\fC [pure virtual]\fP"

.PP
Implemented in \fBlctm::BaseVideoDecoderExternal\fP, \fBlctm::BaseVideoDecoderCodecApi\fP, \fBlctm::BaseVideoDecoderHM\fP, and \fBlctm::BaseVideoDecoderJM\fP\&.
.SS "virtual void lctm::BaseVideoDecoder::StatisticsComputation ()\fC [pure virtual]\fP"

.PP
Implemented in \fBlctm::BaseVideoDecoderExternal\fP, \fBlctm::BaseVideoDecoderExternalAVC\fP, \fBlctm::BaseVideoDecoderExternalHEVC\fP, \fBlctm::BaseVideoDecoderExternalVVC\fP, \fBlctm::BaseVideoDecoderExternalEVC\fP, \fBlctm::BaseVideoDecoderExternalYUV\fP, \fBlctm::BaseVideoDecoderCodecApi\fP, \fBlctm::BaseVideoDecoderHM\fP, and \fBlctm::BaseVideoDecoderJM\fP\&.
.SS "virtual void lctm::BaseVideoDecoder::stop ()\fC [pure virtual]\fP"

.PP
Implemented in \fBlctm::BaseVideoDecoderExternal\fP, \fBlctm::BaseVideoDecoderCodecApi\fP, \fBlctm::BaseVideoDecoderHM\fP, and \fBlctm::BaseVideoDecoderJM\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
