.TH "lctm::EncodeBits" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lctm::EncodeBits
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <LayerEncodeFlags\&.hpp>\fP
.PP
Inherited by \fBlctm::EncodeBits_DD\fP, and \fBlctm::EncodeBits_DDS\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEncodeBits\fP (\fBEncodingMode\fP enc_mode)"
.br
.ti -1c
.RI "\fBEncodingMode\fP \fBencoding_mode\fP () const"
.br
.ti -1c
.RI "virtual \fBTransformType\fP \fBtransform_type\fP () const =0"
.br
.ti -1c
.RI "virtual bool \fBencode_residual\fP (unsigned layer) const =0"
.br
.ti -1c
.RI "virtual size_t \fBsize\fP () const =0"
.br
.ti -1c
.RI "virtual \fB~EncodeBits\fP ()=default"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB50\fP of file \fBLayerEncodeFlags\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "lctm::EncodeBits::EncodeBits (\fBEncodingMode\fP enc_mode)"

.PP
Definition at line \fB46\fP of file \fBLayerEncodeFlags\&.cpp\fP\&.
.SS "virtual lctm::EncodeBits::~EncodeBits ()\fC [virtual]\fP, \fC [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "virtual bool lctm::EncodeBits::encode_residual (unsigned layer) const\fC [pure virtual]\fP"

.PP
Implemented in \fBlctm::EncodeBits_DD\fP, and \fBlctm::EncodeBits_DDS\fP\&.
.SS "\fBEncodingMode\fP lctm::EncodeBits::encoding_mode () const"

.PP
Definition at line \fB48\fP of file \fBLayerEncodeFlags\&.cpp\fP\&.
.SS "virtual size_t lctm::EncodeBits::size () const\fC [pure virtual]\fP"

.PP
Implemented in \fBlctm::EncodeBits_DD\fP, and \fBlctm::EncodeBits_DDS\fP\&.
.SS "virtual \fBTransformType\fP lctm::EncodeBits::transform_type () const\fC [pure virtual]\fP"

.PP
Implemented in \fBlctm::EncodeBits_DD\fP, and \fBlctm::EncodeBits_DDS\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
