.TH "lctm::BaseVideoDecoderJM" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lctm::BaseVideoDecoderJM
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBlctm::BaseVideoDecoder\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBaseVideoDecoderJM\fP (\fBBaseVideoDecoder::Output\fP &output, \fBEncapsulation\fP encapsulation)"
.br
.ti -1c
.RI "\fB~BaseVideoDecoderJM\fP () override"
.br
.ti -1c
.RI "void \fBstart\fP () override"
.br
.ti -1c
.RI "void \fBstop\fP () override"
.br
.ti -1c
.RI "void \fBpush_au\fP (const uint8_t *data, size_t data_size, uint64_t pts, bool is_base_idr, int iPictureType) override"
.br
.ti -1c
.RI "virtual void \fBStatisticsComputation\fP () override"
.br
.in -1c

Public Member Functions inherited from \fBlctm::BaseVideoDecoder\fP
.in +1c
.ti -1c
.RI "\fBPacket\fP \fBrbsp_encapsulate\fP (const \fBPacket\fP &src) const"
.br
.ti -1c
.RI "virtual \fB~BaseVideoDecoder\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"


Public Types inherited from \fBlctm::BaseVideoDecoder\fP
.in +1c
.ti -1c
.RI "typedef struct \fBCodecImage\fP \fBBasePicture\fP"
.br
.in -1c

Protected Member Functions inherited from \fBlctm::BaseVideoDecoder\fP
.in +1c
.ti -1c
.RI "\fBBaseVideoDecoder\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB93\fP of file \fBBaseVideoDecoderJM\&.cpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "lctm::BaseVideoDecoderJM::BaseVideoDecoderJM (\fBBaseVideoDecoder::Output\fP & output, \fBEncapsulation\fP encapsulation)"

.PP
Definition at line \fB131\fP of file \fBBaseVideoDecoderJM\&.cpp\fP\&.
.SS "lctm::BaseVideoDecoderJM::~BaseVideoDecoderJM ()\fC [override]\fP"

.PP
Definition at line \fB134\fP of file \fBBaseVideoDecoderJM\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void lctm::BaseVideoDecoderJM::push_au (const uint8_t * data, size_t data_size, uint64_t pts, bool is_base_idr, int iPictureType)\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBlctm::BaseVideoDecoder\fP\&.
.PP
Definition at line \fB161\fP of file \fBBaseVideoDecoderJM\&.cpp\fP\&.
.SS "void lctm::BaseVideoDecoderJM::start ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBlctm::BaseVideoDecoder\fP\&.
.PP
Definition at line \fB137\fP of file \fBBaseVideoDecoderJM\&.cpp\fP\&.
.SS "void lctm::BaseVideoDecoderJM::StatisticsComputation ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBlctm::BaseVideoDecoder\fP\&.
.PP
Definition at line \fB316\fP of file \fBBaseVideoDecoderJM\&.cpp\fP\&.
.SS "void lctm::BaseVideoDecoderJM::stop ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBlctm::BaseVideoDecoder\fP\&.
.PP
Definition at line \fB148\fP of file \fBBaseVideoDecoderJM\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
