.TH "lctm::SurfaceConfiguration" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lctm::SurfaceConfiguration
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SignaledConfiguration\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned \fBwidth\fP"
.br
.ti -1c
.RI "unsigned \fBheight\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB210\fP of file \fBSignaledConfiguration\&.hpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "unsigned lctm::SurfaceConfiguration::height"

.PP
Definition at line \fB213\fP of file \fBSignaledConfiguration\&.hpp\fP\&.
.SS "unsigned lctm::SurfaceConfiguration::width"

.PP
Definition at line \fB212\fP of file \fBSignaledConfiguration\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
