.TH "lctm::VuiMessage" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lctm::VuiMessage
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SignaledConfiguration\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned \fBaspect_ratio_info_present_flag\fP"
.br
.ti -1c
.RI "unsigned \fBaspect_ratio_idc\fP"
.br
.ti -1c
.RI "unsigned \fBsar_width\fP"
.br
.ti -1c
.RI "unsigned \fBsar_height\fP"
.br
.ti -1c
.RI "unsigned \fBoverscan_info_present_flag\fP"
.br
.ti -1c
.RI "unsigned \fBoverscan_appropriate_flag\fP"
.br
.ti -1c
.RI "unsigned \fBvideo_signal_type_present_flag\fP"
.br
.ti -1c
.RI "unsigned \fBvideo_format\fP"
.br
.ti -1c
.RI "unsigned \fBvideo_full_range_flag\fP"
.br
.ti -1c
.RI "unsigned \fBcolour_description_present_flag\fP"
.br
.ti -1c
.RI "unsigned \fBcolour_primaries\fP"
.br
.ti -1c
.RI "unsigned \fBtransfer_characteristics\fP"
.br
.ti -1c
.RI "unsigned \fBmatrix_coefficients\fP"
.br
.ti -1c
.RI "unsigned \fBchroma_loc_info_present_flag\fP"
.br
.ti -1c
.RI "unsigned \fBchroma_sample_loc_type_top_field\fP"
.br
.ti -1c
.RI "unsigned \fBchroma_sample_loc_type_bottom_field\fP"
.br
.ti -1c
.RI "unsigned \fBtiming_info_present_flag\fP"
.br
.ti -1c
.RI "unsigned \fBnum_units_in_tick\fP"
.br
.ti -1c
.RI "unsigned \fBtime_scale\fP"
.br
.ti -1c
.RI "unsigned \fBfixed_pic_rate_flag\fP"
.br
.ti -1c
.RI "unsigned \fBbitstream_restriction_flag\fP"
.br
.ti -1c
.RI "unsigned \fBmotion_vectors_over_pic_boundaries_flag\fP"
.br
.ti -1c
.RI "unsigned \fBmax_bytes_per_pic_denom\fP"
.br
.ti -1c
.RI "unsigned \fBmax_bits_per_mb_denom\fP"
.br
.ti -1c
.RI "unsigned \fBlog2_max_mv_length_horizontal\fP"
.br
.ti -1c
.RI "unsigned \fBlog2_max_mv_length_vertical\fP"
.br
.ti -1c
.RI "unsigned \fBnum_reorder_pics\fP"
.br
.ti -1c
.RI "unsigned \fBmax_dec_pic_buffering\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB177\fP of file \fBSignaledConfiguration\&.hpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "unsigned lctm::VuiMessage::aspect_ratio_idc"

.PP
Definition at line \fB179\fP of file \fBSignaledConfiguration\&.hpp\fP\&.
.SS "unsigned lctm::VuiMessage::aspect_ratio_info_present_flag"

.PP
Definition at line \fB178\fP of file \fBSignaledConfiguration\&.hpp\fP\&.
.SS "unsigned lctm::VuiMessage::bitstream_restriction_flag"

.PP
Definition at line \fB198\fP of file \fBSignaledConfiguration\&.hpp\fP\&.
.SS "unsigned lctm::VuiMessage::chroma_loc_info_present_flag"

.PP
Definition at line \fB191\fP of file \fBSignaledConfiguration\&.hpp\fP\&.
.SS "unsigned lctm::VuiMessage::chroma_sample_loc_type_bottom_field"

.PP
Definition at line \fB193\fP of file \fBSignaledConfiguration\&.hpp\fP\&.
.SS "unsigned lctm::VuiMessage::chroma_sample_loc_type_top_field"

.PP
Definition at line \fB192\fP of file \fBSignaledConfiguration\&.hpp\fP\&.
.SS "unsigned lctm::VuiMessage::colour_description_present_flag"

.PP
Definition at line \fB187\fP of file \fBSignaledConfiguration\&.hpp\fP\&.
.SS "unsigned lctm::VuiMessage::colour_primaries"

.PP
Definition at line \fB188\fP of file \fBSignaledConfiguration\&.hpp\fP\&.
.SS "unsigned lctm::VuiMessage::fixed_pic_rate_flag"

.PP
Definition at line \fB197\fP of file \fBSignaledConfiguration\&.hpp\fP\&.
.SS "unsigned lctm::VuiMessage::log2_max_mv_length_horizontal"

.PP
Definition at line \fB202\fP of file \fBSignaledConfiguration\&.hpp\fP\&.
.SS "unsigned lctm::VuiMessage::log2_max_mv_length_vertical"

.PP
Definition at line \fB203\fP of file \fBSignaledConfiguration\&.hpp\fP\&.
.SS "unsigned lctm::VuiMessage::matrix_coefficients"

.PP
Definition at line \fB190\fP of file \fBSignaledConfiguration\&.hpp\fP\&.
.SS "unsigned lctm::VuiMessage::max_bits_per_mb_denom"

.PP
Definition at line \fB201\fP of file \fBSignaledConfiguration\&.hpp\fP\&.
.SS "unsigned lctm::VuiMessage::max_bytes_per_pic_denom"

.PP
Definition at line \fB200\fP of file \fBSignaledConfiguration\&.hpp\fP\&.
.SS "unsigned lctm::VuiMessage::max_dec_pic_buffering"

.PP
Definition at line \fB205\fP of file \fBSignaledConfiguration\&.hpp\fP\&.
.SS "unsigned lctm::VuiMessage::motion_vectors_over_pic_boundaries_flag"

.PP
Definition at line \fB199\fP of file \fBSignaledConfiguration\&.hpp\fP\&.
.SS "unsigned lctm::VuiMessage::num_reorder_pics"

.PP
Definition at line \fB204\fP of file \fBSignaledConfiguration\&.hpp\fP\&.
.SS "unsigned lctm::VuiMessage::num_units_in_tick"

.PP
Definition at line \fB195\fP of file \fBSignaledConfiguration\&.hpp\fP\&.
.SS "unsigned lctm::VuiMessage::overscan_appropriate_flag"

.PP
Definition at line \fB183\fP of file \fBSignaledConfiguration\&.hpp\fP\&.
.SS "unsigned lctm::VuiMessage::overscan_info_present_flag"

.PP
Definition at line \fB182\fP of file \fBSignaledConfiguration\&.hpp\fP\&.
.SS "unsigned lctm::VuiMessage::sar_height"

.PP
Definition at line \fB181\fP of file \fBSignaledConfiguration\&.hpp\fP\&.
.SS "unsigned lctm::VuiMessage::sar_width"

.PP
Definition at line \fB180\fP of file \fBSignaledConfiguration\&.hpp\fP\&.
.SS "unsigned lctm::VuiMessage::time_scale"

.PP
Definition at line \fB196\fP of file \fBSignaledConfiguration\&.hpp\fP\&.
.SS "unsigned lctm::VuiMessage::timing_info_present_flag"

.PP
Definition at line \fB194\fP of file \fBSignaledConfiguration\&.hpp\fP\&.
.SS "unsigned lctm::VuiMessage::transfer_characteristics"

.PP
Definition at line \fB189\fP of file \fBSignaledConfiguration\&.hpp\fP\&.
.SS "unsigned lctm::VuiMessage::video_format"

.PP
Definition at line \fB185\fP of file \fBSignaledConfiguration\&.hpp\fP\&.
.SS "unsigned lctm::VuiMessage::video_full_range_flag"

.PP
Definition at line \fB186\fP of file \fBSignaledConfiguration\&.hpp\fP\&.
.SS "unsigned lctm::VuiMessage::video_signal_type_present_flag"

.PP
Definition at line \fB184\fP of file \fBSignaledConfiguration\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
