.TH "lctm::BaseVideoDecoder::Output" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lctm::BaseVideoDecoder::Output
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <BaseVideoDecoder\&.hpp>\fP
.PP
Inherited by \fBDecoderApp\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~Output\fP ()"
.br
.ti -1c
.RI "virtual void \fBpush_base_enhancement\fP (const \fBBasePicture\fP *base_picture, const uint8_t *enhancement_data, size_t enhancement_data_size, uint64_t pts, bool \fBis_lcevc_idr\fP)=0"
.br
.ti -1c
.RI "virtual void \fBpush_base_enhancement\fP (const uint8_t *base_data, size_t base_data_size, \fBSurface\fP(&symbols)[\fBMAX_NUM_PLANES\fP][\fBMAX_NUM_LOQS\fP][\fBMAX_NUM_LAYERS\fP], uint64_t pts, bool \fBis_lcevc_idr\fP)=0"
.br
.ti -1c
.RI "virtual void \fBdeserialize_enhancement\fP (const uint8_t *enhancement_data, size_t enhancement_data_size, \fBSurface\fP(&symbols)[\fBMAX_NUM_PLANES\fP][\fBMAX_NUM_LOQS\fP][\fBMAX_NUM_LAYERS\fP])=0"
.br
.ti -1c
.RI "virtual \fBDimensions\fP \fBget_dimensions\fP ()=0"
.br
.ti -1c
.RI "virtual \fBColourspace\fP \fBget_colourspace\fP ()=0"
.br
.ti -1c
.RI "virtual unsigned \fBget_base_bitdepth\fP ()=0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB69\fP of file \fBBaseVideoDecoder\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "virtual lctm::BaseVideoDecoder::Output::~Output ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Definition at line \fB71\fP of file \fBBaseVideoDecoder\&.hpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual void lctm::BaseVideoDecoder::Output::deserialize_enhancement (const uint8_t * enhancement_data, size_t enhancement_data_size, \fBSurface\fP(&) symbols[MAX_NUM_PLANES][MAX_NUM_LOQS][MAX_NUM_LAYERS])\fC [pure virtual]\fP"

.PP
Implemented in \fBDecoderApp\fP\&.
.SS "virtual unsigned lctm::BaseVideoDecoder::Output::get_base_bitdepth ()\fC [pure virtual]\fP"

.PP
Implemented in \fBDecoderApp\fP\&.
.SS "virtual \fBColourspace\fP lctm::BaseVideoDecoder::Output::get_colourspace ()\fC [pure virtual]\fP"

.PP
Implemented in \fBDecoderApp\fP\&.
.SS "virtual \fBDimensions\fP lctm::BaseVideoDecoder::Output::get_dimensions ()\fC [pure virtual]\fP"

.PP
Implemented in \fBDecoderApp\fP\&.
.SS "virtual void lctm::BaseVideoDecoder::Output::push_base_enhancement (const \fBBasePicture\fP * base_picture, const uint8_t * enhancement_data, size_t enhancement_data_size, uint64_t pts, bool is_lcevc_idr)\fC [pure virtual]\fP"

.PP
Implemented in \fBDecoderApp\fP\&.
.SS "virtual void lctm::BaseVideoDecoder::Output::push_base_enhancement (const uint8_t * base_data, size_t base_data_size, \fBSurface\fP(&) symbols[MAX_NUM_PLANES][MAX_NUM_LOQS][MAX_NUM_LAYERS], uint64_t pts, bool is_lcevc_idr)\fC [pure virtual]\fP"

.PP
Implemented in \fBDecoderApp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
