.TH "lctm::Deblocking" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lctm::Deblocking
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Deblocking\&.hpp>\fP
.PP
Inherits \fBlctm::Component\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDeblocking\fP ()"
.br
.ti -1c
.RI "\fBSurface\fP \fBprocess\fP (const \fBSurface\fP &src_plane, unsigned corner_coefficient, unsigned side_coefficient)"
.br
.in -1c

Public Member Functions inherited from \fBlctm::Component\fP
.in +1c
.ti -1c
.RI "\fBComponent\fP (const std::string &\fBname\fP)"
.br
.ti -1c
.RI "virtual \fB~Component\fP ()=0"
.br
.ti -1c
.RI "virtual const std::string \fBname\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB48\fP of file \fBDeblocking\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "lctm::Deblocking::Deblocking ()\fC [inline]\fP"

.PP
Definition at line \fB50\fP of file \fBDeblocking\&.hpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBSurface\fP lctm::Deblocking::process (const \fBSurface\fP & src_plane, unsigned corner_coefficient, unsigned side_coefficient)"

.PP
Definition at line \fB44\fP of file \fBDeblocking\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
