.TH "lctm::BaseVideoDecoderExternalVVC" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lctm::BaseVideoDecoderExternalVVC
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBlctm::BaseVideoDecoderExternal\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBaseVideoDecoderExternalVVC\fP (\fBBaseVideoDecoder::Output\fP &output, \fBEncapsulation\fP encapsulation, const std::string &yuv_file, bool keep_base)"
.br
.ti -1c
.RI "\fBBaseCoding\fP \fBbase_coding\fP () const override"
.br
.ti -1c
.RI "bool \fBrun_decoder\fP (const string &es_file, const string &yuv_file) const override"
.br
.ti -1c
.RI "virtual void \fBStatisticsComputation\fP () override"
.br
.in -1c

Public Member Functions inherited from \fBlctm::BaseVideoDecoderExternal\fP
.in +1c
.ti -1c
.RI "\fBBaseVideoDecoderExternal\fP (\fBBaseVideoDecoder::Output\fP &output, \fBEncapsulation\fP encapsulation, const std::string &prepared_yuv_file_name, bool keep_base)"
.br
.ti -1c
.RI "\fB~BaseVideoDecoderExternal\fP () override"
.br
.ti -1c
.RI "void \fBstart\fP () override"
.br
.ti -1c
.RI "void \fBstop\fP () override"
.br
.ti -1c
.RI "void \fBpush_au\fP (const uint8_t *data, size_t data_size, uint64_t pts, bool is_base_idr, int iPictureType) override"
.br
.in -1c

Public Member Functions inherited from \fBlctm::BaseVideoDecoder\fP
.in +1c
.ti -1c
.RI "\fBPacket\fP \fBrbsp_encapsulate\fP (const \fBPacket\fP &src) const"
.br
.ti -1c
.RI "virtual \fB~BaseVideoDecoder\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"


Public Types inherited from \fBlctm::BaseVideoDecoder\fP
.in +1c
.ti -1c
.RI "typedef struct \fBCodecImage\fP \fBBasePicture\fP"
.br
.in -1c

Protected Member Functions inherited from \fBlctm::BaseVideoDecoderExternal\fP
.in +1c
.ti -1c
.RI "void \fBpush_es\fP (const uint8_t *data, size_t data_size, uint64_t pts, bool is_base_idr)"
.br
.ti -1c
.RI "void \fBflush\fP ()"
.br
.in -1c

Protected Member Functions inherited from \fBlctm::BaseVideoDecoder\fP
.in +1c
.ti -1c
.RI "\fBBaseVideoDecoder\fP ()"
.br
.in -1c

Protected Attributes inherited from \fBlctm::BaseVideoDecoderExternal\fP
.in +1c
.ti -1c
.RI "\fBOutput\fP & \fBoutput_\fP"
.br
.ti -1c
.RI "\fBEncapsulation\fP \fBencapsulation_\fP"
.br
.ti -1c
.RI "const std::string \fBprepared_yuv_file_name_\fP"
.br
.ti -1c
.RI "vector< uint8_t > \fBbuffer_\fP"
.br
.ti -1c
.RI "string \fBes_file_name_\fP"
.br
.ti -1c
.RI "FILE * \fBes_file_\fP = nullptr"
.br
.ti -1c
.RI "string \fByuv_file_name_\fP"
.br
.ti -1c
.RI "bool \fBkeep_base_\fP"
.br
.ti -1c
.RI "priority_queue< PssPacket, vector< PssPacket >, BufferCompare > \fBenhancement_queue_\fP"
.br
.ti -1c
.RI "vector< PssPacket > \fBenhancement_vector_\fP"
.br
.ti -1c
.RI "uint32_t \fBbase_buffer_size_\fP = 0"
.br
.ti -1c
.RI "uint32_t \fBbase_width_\fP = 0"
.br
.ti -1c
.RI "uint32_t \fBbase_height_\fP = 0"
.br
.ti -1c
.RI "uint32_t \fBbase_bit_depth_\fP = 0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB504\fP of file \fBBaseVideoDecoder\&.cpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "lctm::BaseVideoDecoderExternalVVC::BaseVideoDecoderExternalVVC (\fBBaseVideoDecoder::Output\fP & output, \fBEncapsulation\fP encapsulation, const std::string & yuv_file, bool keep_base)\fC [inline]\fP"

.PP
Definition at line \fB506\fP of file \fBBaseVideoDecoder\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBBaseCoding\fP lctm::BaseVideoDecoderExternalVVC::base_coding () const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBlctm::BaseVideoDecoderExternal\fP\&.
.PP
Definition at line \fB510\fP of file \fBBaseVideoDecoder\&.cpp\fP\&.
.SS "bool lctm::BaseVideoDecoderExternalVVC::run_decoder (const string & es_file, const string & yuv_file) const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBlctm::BaseVideoDecoderExternal\fP\&.
.PP
Definition at line \fB512\fP of file \fBBaseVideoDecoder\&.cpp\fP\&.
.SS "virtual void lctm::BaseVideoDecoderExternalVVC::StatisticsComputation ()\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBlctm::BaseVideoDecoderExternal\fP\&.
.PP
Definition at line \fB522\fP of file \fBBaseVideoDecoder\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
