.TH "lctm::SurfaceBuilder< T >" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lctm::SurfaceBuilder< T >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Surface\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSurfaceBuilder\fP ()"
.br
.ti -1c
.RI "\fBSurfaceBuilder\fP & \fBcontents\fP (const \fBSurfaceView\fP< T > &view, unsigned x, unsigned y, unsigned \fBwidth\fP, unsigned \fBheight\fP)"
.br
.ti -1c
.RI "\fBSurfaceBuilder\fP & \fBcontents\fP (const T *\fBdata\fP, unsigned \fBwidth\fP, unsigned \fBheight\fP, unsigned \fBstride\fP=0)"
.br
.ti -1c
.RI "\fBSurfaceBuilder\fP & \fBcontents\fP (const std::vector< T > \fBdata\fP, unsigned \fBwidth\fP, unsigned \fBheight\fP, unsigned \fBstride\fP=0)"
.br
.ti -1c
.RI "\fBSurfaceBuilder\fP & \fBreserve\fP (unsigned \fBwidth\fP, unsigned \fBheight\fP, unsigned \fBstride\fP=0)"
.br
.ti -1c
.RI "\fBSurfaceBuilder\fP & \fBreserve_bpp\fP (unsigned \fBwidth\fP, unsigned \fBheight\fP, unsigned bpp, unsigned \fBstride\fP=0)"
.br
.ti -1c
.RI "\fBSurfaceBuilder\fP & \fBfill\fP (T \fBdata\fP, unsigned \fBwidth\fP, unsigned \fBheight\fP)"
.br
.ti -1c
.RI "\fBSurfaceBuilder\fP & \fBname\fP (const std::string &name)"
.br
.ti -1c
.RI "\fBSurface\fP \fBfinish\fP ()"
.br
.ti -1c
.RI "unsigned \fBwidth\fP () const"
.br
.ti -1c
.RI "unsigned \fBheight\fP () const"
.br
.ti -1c
.RI "T * \fBdata\fP () const"
.br
.ti -1c
.RI "T * \fBdata\fP (unsigned x, unsigned y) const"
.br
.ti -1c
.RI "void \fBwrite\fP (unsigned x, unsigned y, T t)"
.br
.ti -1c
.RI "unsigned \fBstride\fP () const"
.br
.ti -1c
.RI "\fBSurfaceBuilder\fP< T > & \fBgenerate\fP (unsigned \fBwidth\fP, unsigned \fBheight\fP, std::function< T(unsigned x, unsigned y)> fn)"
.br
.ti -1c
.RI "template<typename C > \fBSurfaceBuilder\fP< T > & \fBgenerate\fP (unsigned \fBwidth\fP, unsigned \fBheight\fP, T(*fn)(unsigned x, unsigned y, const C &c), const C &c)"
.br
.ti -1c
.RI "template<typename A1 > \fBSurfaceBuilder\fP< T > & \fBgenerate\fP (unsigned \fBwidth\fP, unsigned \fBheight\fP, T(*fn)(unsigned x, unsigned y, A1 a1), A1 a1)"
.br
.ti -1c
.RI "template<typename A1 , typename A2 > \fBSurfaceBuilder\fP< T > & \fBgenerate\fP (unsigned \fBwidth\fP, unsigned \fBheight\fP, T(*fn)(unsigned x, unsigned y, A1 a1, A2 a2), A1 a1, A2 a2)"
.br
.ti -1c
.RI "template<typename A1 , typename A2 , typename A3 > \fBSurfaceBuilder\fP< T > & \fBgenerate\fP (unsigned \fBwidth\fP, unsigned \fBheight\fP, T(*fn)(unsigned x, unsigned y, A1 a1, A2 a2, A3 a3), A1 a1, A2 a2, A3 a3)"
.br
.ti -1c
.RI "template<typename F > \fBSurfaceBuilder\fP< T > & \fBxgenerate\fP (unsigned \fBwidth\fP, unsigned \fBheight\fP, F fn)"
.br
.ti -1c
.RI "template<typename T > \fBSurfaceBuilder\fP< T > & \fBgenerate\fP (unsigned \fBwidth\fP, unsigned \fBheight\fP, std::function< T(unsigned x, unsigned y)> fn)"
.br
.ti -1c
.RI "template<typename C > \fBSurfaceBuilder\fP< T > & \fBgenerate\fP (unsigned \fBwidth\fP, unsigned \fBheight\fP, T(*fn)(unsigned x, unsigned y, const C &c), const C &c)"
.br
.ti -1c
.RI "template<typename A1 > \fBSurfaceBuilder\fP< T > & \fBgenerate\fP (unsigned \fBwidth\fP, unsigned \fBheight\fP, T(*fn)(unsigned x, unsigned y, A1 a1), A1 a1)"
.br
.ti -1c
.RI "template<typename A1 , typename A2 > \fBSurfaceBuilder\fP< T > & \fBgenerate\fP (unsigned \fBwidth\fP, unsigned \fBheight\fP, T(*fn)(unsigned x, unsigned y, A1 a1, A2 a2), A1 a1, A2 a2)"
.br
.ti -1c
.RI "template<typename A1 , typename A2 , typename A3 > \fBSurfaceBuilder\fP< T > & \fBgenerate\fP (unsigned \fBwidth\fP, unsigned \fBheight\fP, T(*fn)(unsigned x, unsigned y, A1 a1, A2 a2, A3 a3), A1 a1, A2 a2, A3 a3)"
.br
.ti -1c
.RI "template<typename F > \fBSurfaceBuilder\fP< T > & \fBxgenerate\fP (unsigned \fBwidth\fP, unsigned \fBheight\fP, F fn)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T>
.br
class lctm::SurfaceBuilder< T >"
.PP
Definition at line \fB88\fP of file \fBSurface\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename T > SurfaceBuilder::SurfaceBuilder ()"

.PP
Definition at line \fB42\fP of file \fBSurfaceImpl\&.hpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "template<typename T > \fBSurfaceBuilder\fP & \fBlctm::SurfaceBuilder\fP< T >::contents (const std::vector< T > data, unsigned width, unsigned height, unsigned stride = \fC0\fP)"

.SS "template<typename T > \fBSurfaceBuilder\fP< T > & SurfaceBuilder::contents (const \fBSurfaceView\fP< T > & view, unsigned x, unsigned y, unsigned width, unsigned height)"

.PP
Definition at line \fB46\fP of file \fBSurfaceImpl\&.hpp\fP\&.
.SS "template<typename T > \fBSurfaceBuilder\fP & \fBlctm::SurfaceBuilder\fP< T >::contents (const T * data, unsigned width, unsigned height, unsigned stride = \fC0\fP)"

.SS "template<typename T > T * SurfaceBuilder::data () const"

.PP
Definition at line \fB127\fP of file \fBSurfaceImpl\&.hpp\fP\&.
.SS "template<typename T > T * SurfaceBuilder::data (unsigned x, unsigned y) const"

.PP
Definition at line \fB132\fP of file \fBSurfaceImpl\&.hpp\fP\&.
.SS "template<typename T > \fBSurfaceBuilder\fP< T > & SurfaceBuilder::fill (T data, unsigned width, unsigned height)"

.PP
Definition at line \fB223\fP of file \fBSurfaceImpl\&.hpp\fP\&.
.SS "template<typename T > \fBSurface\fP SurfaceBuilder::finish ()"

.PP
Definition at line \fB155\fP of file \fBSurfaceImpl\&.hpp\fP\&.
.SS "template<typename T > \fBSurfaceBuilder\fP< T > & \fBlctm::SurfaceBuilder\fP< T >::generate (unsigned width, unsigned height, std::function< T(unsigned x, unsigned y)> fn)"

.SS "template<typename T > template<typename T > \fBSurfaceBuilder\fP< T > & \fBlctm::SurfaceBuilder\fP< T >::generate (unsigned width, unsigned height, std::function< T(unsigned x, unsigned y)> fn)"

.PP
Definition at line \fB167\fP of file \fBSurfaceImpl\&.hpp\fP\&.
.SS "template<typename T > template<typename A1 > \fBSurfaceBuilder\fP< T > & \fBlctm::SurfaceBuilder\fP< T >::generate (unsigned width, unsigned height, T(*)(unsigned x, unsigned y, A1 a1) fn, A1 a1)"

.SS "template<typename T > template<typename A1 > \fBSurfaceBuilder\fP< T > & \fBlctm::SurfaceBuilder\fP< T >::generate (unsigned width, unsigned height, T(*)(unsigned x, unsigned y, A1 a1) fn, A1 a1)"

.PP
Definition at line \fB190\fP of file \fBSurfaceImpl\&.hpp\fP\&.
.SS "template<typename T > template<typename A1 , typename A2 > \fBSurfaceBuilder\fP< T > & \fBlctm::SurfaceBuilder\fP< T >::generate (unsigned width, unsigned height, T(*)(unsigned x, unsigned y, A1 a1, A2 a2) fn, A1 a1, A2 a2)"

.SS "template<typename T > template<typename A1 , typename A2 > \fBSurfaceBuilder\fP< T > & \fBlctm::SurfaceBuilder\fP< T >::generate (unsigned width, unsigned height, T(*)(unsigned x, unsigned y, A1 a1, A2 a2) fn, A1 a1, A2 a2)"

.PP
Definition at line \fB201\fP of file \fBSurfaceImpl\&.hpp\fP\&.
.SS "template<typename T > template<typename A1 , typename A2 , typename A3 > \fBSurfaceBuilder\fP< T > & \fBlctm::SurfaceBuilder\fP< T >::generate (unsigned width, unsigned height, T(*)(unsigned x, unsigned y, A1 a1, A2 a2, A3 a3) fn, A1 a1, A2 a2, A3 a3)"

.SS "template<typename T > template<typename A1 , typename A2 , typename A3 > \fBSurfaceBuilder\fP< T > & \fBlctm::SurfaceBuilder\fP< T >::generate (unsigned width, unsigned height, T(*)(unsigned x, unsigned y, A1 a1, A2 a2, A3 a3) fn, A1 a1, A2 a2, A3 a3)"

.PP
Definition at line \fB213\fP of file \fBSurfaceImpl\&.hpp\fP\&.
.SS "template<typename T > template<typename C > \fBSurfaceBuilder\fP< T > & \fBlctm::SurfaceBuilder\fP< T >::generate (unsigned width, unsigned height, T(*)(unsigned x, unsigned y, const C &c) fn, const C & c)"

.SS "template<typename T > template<typename C > \fBSurfaceBuilder\fP< T > & \fBlctm::SurfaceBuilder\fP< T >::generate (unsigned width, unsigned height, T(*)(unsigned x, unsigned y, const C &c) fn, const C & c)"

.PP
Definition at line \fB178\fP of file \fBSurfaceImpl\&.hpp\fP\&.
.SS "template<typename T > unsigned SurfaceBuilder::height () const"

.PP
Definition at line \fB142\fP of file \fBSurfaceImpl\&.hpp\fP\&.
.SS "template<typename T > \fBSurfaceBuilder\fP< T > & SurfaceBuilder::name (const std::string & name)"

.PP
Definition at line \fB150\fP of file \fBSurfaceImpl\&.hpp\fP\&.
.SS "template<typename T > \fBSurfaceBuilder\fP< T > & SurfaceBuilder::reserve (unsigned width, unsigned height, unsigned stride = \fC0\fP)"

.PP
Definition at line \fB100\fP of file \fBSurfaceImpl\&.hpp\fP\&.
.SS "template<typename T > \fBSurfaceBuilder\fP< T > & SurfaceBuilder::reserve_bpp (unsigned width, unsigned height, unsigned bpp, unsigned stride = \fC0\fP)"

.PP
Definition at line \fB114\fP of file \fBSurfaceImpl\&.hpp\fP\&.
.SS "template<typename T > unsigned SurfaceBuilder::stride () const"

.PP
Definition at line \fB144\fP of file \fBSurfaceImpl\&.hpp\fP\&.
.SS "template<typename T > unsigned SurfaceBuilder::width () const"

.PP
Definition at line \fB140\fP of file \fBSurfaceImpl\&.hpp\fP\&.
.SS "template<typename T > void SurfaceBuilder::write (unsigned x, unsigned y, T t)"

.PP
Definition at line \fB138\fP of file \fBSurfaceImpl\&.hpp\fP\&.
.SS "template<typename T > template<typename F > \fBSurfaceBuilder\fP< T > & \fBlctm::SurfaceBuilder\fP< T >::xgenerate (unsigned width, unsigned height, F fn)"

.SS "template<typename T > template<typename F > \fBSurfaceBuilder\fP< T > & \fBlctm::SurfaceBuilder\fP< T >::xgenerate (unsigned width, unsigned height, F fn)"

.PP
Definition at line \fB232\fP of file \fBSurfaceImpl\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
