.TH "lctm::TemporalCost_2x2" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lctm::TemporalCost_2x2
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <TemporalEncode\&.hpp>\fP
.PP
Inherits \fBlctm::Component\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTemporalCost_2x2\fP ()"
.br
.ti -1c
.RI "\fBSurface\fP \fBprocess\fP (const \fBSurface\fP &src_plane, const \fBSurface\fP &recon_plane, const \fBSurface\fP *symb_plane, unsigned transform_block_size, unsigned scale, bool intra)"
.br
.in -1c

Public Member Functions inherited from \fBlctm::Component\fP
.in +1c
.ti -1c
.RI "\fBComponent\fP (const std::string &\fBname\fP)"
.br
.ti -1c
.RI "virtual \fB~Component\fP ()=0"
.br
.ti -1c
.RI "virtual const std::string \fBname\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB47\fP of file \fBTemporalEncode\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "lctm::TemporalCost_2x2::TemporalCost_2x2 ()\fC [inline]\fP"

.PP
Definition at line \fB49\fP of file \fBTemporalEncode\&.hpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBSurface\fP lctm::TemporalCost_2x2::process (const \fBSurface\fP & src_plane, const \fBSurface\fP & recon_plane, const \fBSurface\fP * symb_plane, unsigned transform_block_size, unsigned scale, bool intra)"

.PP
Definition at line \fB51\fP of file \fBTemporalEncode\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
