.TH "lctm::ExpandU8" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lctm::ExpandU8
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Expand\&.hpp>\fP
.PP
Inherits \fBlctm::Component\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBExpandU8\fP ()"
.br
.ti -1c
.RI "\fBSurface\fP \fBprocess\fP (const \fBSurface\fP &plane, unsigned width, unsigned height, unsigned offset_x, unsigned offset_y)"
.br
.in -1c

Public Member Functions inherited from \fBlctm::Component\fP
.in +1c
.ti -1c
.RI "\fBComponent\fP (const std::string &\fBname\fP)"
.br
.ti -1c
.RI "virtual \fB~Component\fP ()=0"
.br
.ti -1c
.RI "virtual const std::string \fBname\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB48\fP of file \fBExpand\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "lctm::ExpandU8::ExpandU8 ()\fC [inline]\fP"

.PP
Definition at line \fB50\fP of file \fBExpand\&.hpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBSurface\fP lctm::ExpandU8::process (const \fBSurface\fP & plane, unsigned width, unsigned height, unsigned offset_x, unsigned offset_y)"

.PP
Definition at line \fB49\fP of file \fBExpand\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
