.TH "lctm::HuffmanDecoder" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lctm::HuffmanDecoder
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <HuffmanDecoder\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBread_codes\fP (\fBBitstreamUnpacker\fP &b)"
.br
.ti -1c
.RI "unsigned \fBdecode_symbol\fP (\fBBitstreamUnpacker\fP &b)"
.br
.ti -1c
.RI "const std::vector< \fBHuffmanCode\fP > & \fBcodes\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "\fBstatic\fP unsigned \fBbit_width\fP (unsigned n)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB55\fP of file \fBHuffmanDecoder\&.hpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "unsigned lctm::HuffmanDecoder::bit_width (unsigned n)\fC [static]\fP"

.PP
Definition at line \fB49\fP of file \fBHuffmanDecoder\&.cpp\fP\&.
.SS "const std::vector< \fBHuffmanCode\fP > & lctm::HuffmanDecoder::codes ()\fC [inline]\fP"

.PP
Definition at line \fB61\fP of file \fBHuffmanDecoder\&.hpp\fP\&.
.SS "unsigned lctm::HuffmanDecoder::decode_symbol (\fBBitstreamUnpacker\fP & b)"

.PP
Definition at line \fB129\fP of file \fBHuffmanDecoder\&.cpp\fP\&.
.SS "void lctm::HuffmanDecoder::read_codes (\fBBitstreamUnpacker\fP & b)"

.PP
Definition at line \fB65\fP of file \fBHuffmanDecoder\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
