.TH "lctm::YUVReader" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lctm::YUVReader
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <YUVReader\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBImageDescription\fP \fBdescription\fP () const"
.br
.ti -1c
.RI "unsigned \fBlength\fP () const"
.br
.ti -1c
.RI "float \fBrate\fP () const"
.br
.ti -1c
.RI "\fBImage\fP \fBread\fP (unsigned position, uint64_t timestamp=0) const"
.br
.ti -1c
.RI "void \fBupdate_data\fP (const \fBImageDescription\fP &image_description)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "std::unique_ptr< \fBYUVReader\fP > \fBCreateYUVReader\fP (const std::string &\fBname\fP)"
.br
.ti -1c
.RI "std::unique_ptr< \fBYUVReader\fP > \fBCreateYUVReader\fP (const std::string &\fBname\fP, unsigned \fBrate\fP)"
.br
.ti -1c
.RI "std::unique_ptr< \fBYUVReader\fP > \fBCreateYUVReader\fP (const std::string &\fBname\fP, const \fBImageDescription\fP &image_description, unsigned \fBrate\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB48\fP of file \fBYUVReader\&.hpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBImageDescription\fP lctm::YUVReader::description () const\fC [inline]\fP"

.PP
Definition at line \fB51\fP of file \fBYUVReader\&.hpp\fP\&.
.SS "unsigned lctm::YUVReader::length () const\fC [inline]\fP"

.PP
Definition at line \fB52\fP of file \fBYUVReader\&.hpp\fP\&.
.SS "float lctm::YUVReader::rate () const\fC [inline]\fP"

.PP
Definition at line \fB53\fP of file \fBYUVReader\&.hpp\fP\&.
.SS "\fBImage\fP lctm::YUVReader::read (unsigned position, uint64_t timestamp = \fC0\fP) const"

.PP
Definition at line \fB87\fP of file \fBYUVReader\&.cpp\fP\&.
.SS "void lctm::YUVReader::update_data (const \fBImageDescription\fP & image_description)"

.PP
Definition at line \fB64\fP of file \fBYUVReader\&.cpp\fP\&.
.SH "Friends And Related Symbol Documentation"
.PP 
.SS "std::unique_ptr< \fBYUVReader\fP > CreateYUVReader (const std::string & name)\fC [friend]\fP"

.SS "std::unique_ptr< \fBYUVReader\fP > CreateYUVReader (const std::string & name, const \fBImageDescription\fP & image_description, unsigned rate)\fC [friend]\fP"

.PP
Definition at line \fB190\fP of file \fBYUVReader\&.cpp\fP\&.
.SS "std::unique_ptr< \fBYUVReader\fP > CreateYUVReader (const std::string & name, unsigned rate)\fC [friend]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
