.TH "lctm::FileEncoderImpl::UnregisteredSEI" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lctm::FileEncoderImpl::UnregisteredSEI
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "\fBstatic\fP \fBPacket\fP \fBsei_payload\fP (const \fBPacket\fP &enhancement_data)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB138\fP of file \fBFileEncoder\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBPacket\fP lctm::FileEncoderImpl::UnregisteredSEI::sei_payload (const \fBPacket\fP & enhancement_data)\fC [static]\fP"

.PP
Definition at line \fB572\fP of file \fBFileEncoder\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
