.TH "lctm::TransformDD" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lctm::TransformDD
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <TransformDD\&.hpp>\fP
.PP
Inherits \fBlctm::Component\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTransformDD\fP ()"
.br
.ti -1c
.RI "void \fBprocess\fP (const \fBSurface\fP &residuals, \fBEncodingMode\fP mode, \fBSurface\fP layers[])"
.br
.in -1c

Public Member Functions inherited from \fBlctm::Component\fP
.in +1c
.ti -1c
.RI "\fBComponent\fP (const std::string &\fBname\fP)"
.br
.ti -1c
.RI "virtual \fB~Component\fP ()=0"
.br
.ti -1c
.RI "virtual const std::string \fBname\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB46\fP of file \fBTransformDD\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "lctm::TransformDD::TransformDD ()\fC [inline]\fP"

.PP
Definition at line \fB48\fP of file \fBTransformDD\&.hpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void lctm::TransformDD::process (const \fBSurface\fP & residuals, \fBEncodingMode\fP mode, \fBSurface\fP layers[])"

.PP
Definition at line \fB43\fP of file \fBTransformDD\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
