.TH "lctm::CropTemporal" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lctm::CropTemporal
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Crop\&.hpp>\fP
.PP
Inherits \fBlctm::Component\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCropTemporal\fP ()"
.br
.ti -1c
.RI "\fBSurface\fP \fBprocess\fP (const \fBSurface\fP &plane, unsigned x0, unsigned y0, unsigned x1, unsigned y1)"
.br
.in -1c

Public Member Functions inherited from \fBlctm::Component\fP
.in +1c
.ti -1c
.RI "\fBComponent\fP (const std::string &\fBname\fP)"
.br
.ti -1c
.RI "virtual \fB~Component\fP ()=0"
.br
.ti -1c
.RI "virtual const std::string \fBname\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB53\fP of file \fBCrop\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "lctm::CropTemporal::CropTemporal ()\fC [inline]\fP"

.PP
Definition at line \fB55\fP of file \fBCrop\&.hpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBSurface\fP lctm::CropTemporal::process (const \fBSurface\fP & plane, unsigned x0, unsigned y0, unsigned x1, unsigned y1)"

.PP
Definition at line \fB61\fP of file \fBCrop\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
