.TH "lctm::TemporalSelect" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lctm::TemporalSelect
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <TemporalEncode\&.hpp>\fP
.PP
Inherits \fBlctm::Component\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTemporalSelect\fP ()"
.br
.ti -1c
.RI "\fBSurface\fP \fBprocess\fP (const \fBSurface\fP &inter_plane, const \fBSurface\fP &intra_plane, const \fBSurface\fP &mask_plane)"
.br
.in -1c

Public Member Functions inherited from \fBlctm::Component\fP
.in +1c
.ti -1c
.RI "\fBComponent\fP (const std::string &\fBname\fP)"
.br
.ti -1c
.RI "virtual \fB~Component\fP ()=0"
.br
.ti -1c
.RI "virtual const std::string \fBname\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB67\fP of file \fBTemporalEncode\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "lctm::TemporalSelect::TemporalSelect ()\fC [inline]\fP"

.PP
Definition at line \fB69\fP of file \fBTemporalEncode\&.hpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBSurface\fP lctm::TemporalSelect::process (const \fBSurface\fP & inter_plane, const \fBSurface\fP & intra_plane, const \fBSurface\fP & mask_plane)"

.PP
Definition at line \fB219\fP of file \fBTemporalEncode\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
