.TH "lctm::BitstreamUnpacker::ScopedContextLabel" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lctm::BitstreamUnpacker::ScopedContextLabel
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <BitstreamUnpacker\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBScopedContextLabel\fP (\fBBitstreamUnpacker\fP &b, const std::string &l)"
.br
.ti -1c
.RI "\fB~ScopedContextLabel\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB86\fP of file \fBBitstreamUnpacker\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "lctm::BitstreamUnpacker::ScopedContextLabel::ScopedContextLabel (\fBBitstreamUnpacker\fP & b, const std::string & l)\fC [inline]\fP"

.PP
Definition at line \fB88\fP of file \fBBitstreamUnpacker\&.hpp\fP\&.
.SS "lctm::BitstreamUnpacker::ScopedContextLabel::~ScopedContextLabel ()\fC [inline]\fP"

.PP
Definition at line \fB90\fP of file \fBBitstreamUnpacker\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
