.TH "lctm::HuffmanEncoder" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lctm::HuffmanEncoder
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <HuffmanEncoder\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBwrite_codes\fP (\fBBitstreamPacker\fP &b)"
.br
.ti -1c
.RI "void \fBwrite_symbol\fP (\fBBitstreamPacker\fP &b, unsigned symbol)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "\fBstatic\fP \fBHuffmanEncoderBuilder\fP \fBbuild\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "\fBstatic\fP const int \fBMAX_SYMBOL\fP = 256"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBHuffmanEncoderBuilder\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB48\fP of file \fBHuffmanEncoder\&.hpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBstatic\fP \fBHuffmanEncoderBuilder\fP lctm::HuffmanEncoder::build ()\fC [static]\fP"

.SS "void lctm::HuffmanEncoder::write_codes (\fBBitstreamPacker\fP & b)"

.PP
Definition at line \fB151\fP of file \fBHuffmanEncoder\&.cpp\fP\&.
.SS "void lctm::HuffmanEncoder::write_symbol (\fBBitstreamPacker\fP & b, unsigned symbol)"

.PP
Definition at line \fB206\fP of file \fBHuffmanEncoder\&.cpp\fP\&.
.SH "Friends And Related Symbol Documentation"
.PP 
.SS "friend class \fBHuffmanEncoderBuilder\fP\fC [friend]\fP"

.PP
Definition at line \fB68\fP of file \fBHuffmanEncoder\&.hpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "const int lctm::HuffmanEncoder::MAX_SYMBOL = 256\fC [static]\fP"

.PP
Definition at line \fB50\fP of file \fBHuffmanEncoder\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
