.TH "lctm::FileEncoderImplHEVC" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lctm::FileEncoderImplHEVC
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBlctm::FileEncoderImpl\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFileEncoderImplHEVC\fP (const \fBImageDescription\fP &image_description, unsigned fps, const \fBParameters\fP &parameters)"
.br
.ti -1c
.RI "\fBBaseDecoder::Codec\fP \fBes_file_type\fP () const override"
.br
.ti -1c
.RI "\fBBaseCoding\fP \fBbase_coding\fP () const override"
.br
.ti -1c
.RI "bool \fBrun_base_encoder\fP (const string &yuv_file, const string &es_file, const string &recon_file, unsigned frame_count) const override"
.br
.ti -1c
.RI "int \fBadd_enhancement\fP (\fBESFile::AccessUnit\fP &au, bool is_idr, const \fBPacket\fP &payload) override"
.br
.ti -1c
.RI "bool \fBrun_base_decoder\fP (const string &input, const string &output) override"
.br
.in -1c

Public Member Functions inherited from \fBlctm::FileEncoderImpl\fP
.in +1c
.ti -1c
.RI "\fBFileEncoderImpl\fP (const \fBImageDescription\fP &image_description, unsigned fps, const \fBParameters\fP &parameters)"
.br
.ti -1c
.RI "\fB~FileEncoderImpl\fP () override"
.br
.ti -1c
.RI "void \fBencode_file\fP (const string &src_filename, const string &dst_filename, const string &dst_filename_yuv, unsigned limit) override"
.br
.ti -1c
.RI "void \fBencode_file_with_decoder\fP (const string &src_filename, const string base_filename, const string &dst_filename, const string &dst_filename_yuv, unsigned limit) override"
.br
.ti -1c
.RI "void \fBencode_file_with_base\fP (const string &src_filename, const string base_filename, const string base_recon_filename, const string &dst_filename, const string &dst_filename_yuv, unsigned limit) override"
.br
.ti -1c
.RI "void \fBdownsample_file\fP (const string &src_filename, const string &dst_filename, unsigned limit) override"
.br
.ti -1c
.RI "void \fBupsample_file\fP (const string &src_filename, const string &dst_filename, unsigned limit) override"
.br
.in -1c

Public Member Functions inherited from \fBlctm::FileEncoder\fP
.in +1c
.ti -1c
.RI "virtual void \fBencode_file\fP (const std::string &src_filename, const std::string &dst_filename, const std::string &dst_filename_yuv, unsigned limit=UINT_MAX)=0"
.br
.ti -1c
.RI "virtual void \fBencode_file_with_decoder\fP (const std::string &src_filename, const std::string base_filename, const std::string &dst_filename, const std::string &dst_filename_yuv, unsigned limit=UINT_MAX)=0"
.br
.ti -1c
.RI "virtual void \fBencode_file_with_base\fP (const std::string &src_filename, const std::string base_filename, const std::string base_recon_filename, const std::string &dst_filename, const std::string &dst_filename_yuv, unsigned limit=UINT_MAX)=0"
.br
.ti -1c
.RI "virtual void \fBdownsample_file\fP (const std::string &src_filename, const std::string &dst_filename, unsigned limit=UINT_MAX)=0"
.br
.ti -1c
.RI "virtual void \fBupsample_file\fP (const std::string &src_filename, const std::string &dst_filename, unsigned limit=UINT_MAX)=0"
.br
.ti -1c
.RI "virtual \fB~FileEncoder\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Member Functions inherited from \fBlctm::FileEncoderImpl\fP
.in +1c
.ti -1c
.RI "void \fBencode\fP (const \fBYUVReader\fP &src_file, const \fBYUVReader\fP &recon_file, FILE *output_file, \fBESFile\fP &es_file, const string &dst_filename_yuv, unsigned limit)"
.br
.ti -1c
.RI "bool \fBread_au\fP (\fBESFile\fP &es_file, \fBESFile::AccessUnit\fP &au)"
.br
.ti -1c
.RI "\fBPacket\fP \fBrbsp_encapsulate\fP (const \fBPacket\fP &src) const"
.br
.ti -1c
.RI "void \fBinitialize_encoder\fP (const \fBYUVReader\fP &src_file, unsigned limit)"
.br
.ti -1c
.RI "\fBPacket\fP \fBnal_payload\fP (const \fBPacket\fP &enhancement_data) const"
.br
.ti -1c
.RI "\fBESFile::NalUnit\fP \fBbuild_nalu\fP (bool is_idr, const \fBPacket\fP &payload) const"
.br
.ti -1c
.RI "unsigned \fBintra_period\fP () const"
.br
.in -1c

Protected Member Functions inherited from \fBlctm::FileEncoder\fP
.in +1c
.ti -1c
.RI "\fBFileEncoder\fP ()"
.br
.in -1c

Protected Attributes inherited from \fBlctm::FileEncoderImpl\fP
.in +1c
.ti -1c
.RI "const unsigned \fBfps_\fP"
.br
.ti -1c
.RI "const \fBParameters\fP \fBparameters_\fP"
.br
.ti -1c
.RI "const \fBScalingMode\fP \fBscaling_mode_\fP [\fBMAX_NUM_LOQS\fP]"
.br
.ti -1c
.RI "const \fBDownsample\fP \fBdownsample_luma_\fP"
.br
.ti -1c
.RI "const \fBDownsample\fP \fBdownsample_chroma_\fP"
.br
.ti -1c
.RI "const \fBUpsample\fP \fBupsample_\fP"
.br
.ti -1c
.RI "unsigned \fBupsampling_coefficients_\fP [4]"
.br
.ti -1c
.RI "const \fBEncapsulation\fP \fBencapsulation_\fP"
.br
.ti -1c
.RI "\fBEncoder\fP \fBencoder_\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB760\fP of file \fBFileEncoder\&.cpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "lctm::FileEncoderImplHEVC::FileEncoderImplHEVC (const \fBImageDescription\fP & image_description, unsigned fps, const \fBParameters\fP & parameters)\fC [inline]\fP"

.PP
Definition at line \fB762\fP of file \fBFileEncoder\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "int lctm::FileEncoderImplHEVC::add_enhancement (\fBESFile::AccessUnit\fP & au, bool is_idr, const \fBPacket\fP & payload)\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBlctm::FileEncoderImpl\fP\&.
.PP
Definition at line \fB817\fP of file \fBFileEncoder\&.cpp\fP\&.
.SS "\fBBaseCoding\fP lctm::FileEncoderImplHEVC::base_coding () const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBlctm::FileEncoderImpl\fP\&.
.PP
Definition at line \fB766\fP of file \fBFileEncoder\&.cpp\fP\&.
.SS "\fBBaseDecoder::Codec\fP lctm::FileEncoderImplHEVC::es_file_type () const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBlctm::FileEncoderImpl\fP\&.
.PP
Definition at line \fB765\fP of file \fBFileEncoder\&.cpp\fP\&.
.SS "bool lctm::FileEncoderImplHEVC::run_base_decoder (const string & input, const string & output)\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBlctm::FileEncoderImpl\fP\&.
.PP
Definition at line \fB857\fP of file \fBFileEncoder\&.cpp\fP\&.
.SS "bool lctm::FileEncoderImplHEVC::run_base_encoder (const string & yuv_file, const string & es_file, const string & recon_file, unsigned frame_count) const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBlctm::FileEncoderImpl\fP\&.
.PP
Definition at line \fB768\fP of file \fBFileEncoder\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
