.TH "lctm::BaseVideoDecoderCodecApi" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lctm::BaseVideoDecoderCodecApi
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBlctm::BaseVideoDecoder\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBaseVideoDecoderCodecApi\fP (\fBBaseVideoDecoder::Output\fP &output, \fBEncapsulation\fP encapsulation, \fBBaseCoding\fP base, const std::string &\fBname\fP, const std::string &selection_options, const std::string &create_options)"
.br
.ti -1c
.RI "\fB~BaseVideoDecoderCodecApi\fP () override"
.br
.ti -1c
.RI "void \fBstart\fP () override"
.br
.ti -1c
.RI "void \fBstop\fP () override"
.br
.ti -1c
.RI "void \fBpush_au\fP (const uint8_t *data, size_t data_size, uint64_t pts, bool is_idr, int iPictureType) override"
.br
.ti -1c
.RI "virtual void \fBStatisticsComputation\fP () override"
.br
.in -1c

Public Member Functions inherited from \fBlctm::BaseVideoDecoder\fP
.in +1c
.ti -1c
.RI "\fBPacket\fP \fBrbsp_encapsulate\fP (const \fBPacket\fP &src) const"
.br
.ti -1c
.RI "virtual \fB~BaseVideoDecoder\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"


Public Types inherited from \fBlctm::BaseVideoDecoder\fP
.in +1c
.ti -1c
.RI "typedef struct \fBCodecImage\fP \fBBasePicture\fP"
.br
.in -1c

Protected Member Functions inherited from \fBlctm::BaseVideoDecoder\fP
.in +1c
.ti -1c
.RI "\fBBaseVideoDecoder\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB83\fP of file \fBBaseVideoDecoderCodecApi\&.cpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "lctm::BaseVideoDecoderCodecApi::BaseVideoDecoderCodecApi (\fBBaseVideoDecoder::Output\fP & output, \fBEncapsulation\fP encapsulation, \fBBaseCoding\fP base, const std::string & name, const std::string & selection_options, const std::string & create_options)"

.PP
Definition at line \fB120\fP of file \fBBaseVideoDecoderCodecApi\&.cpp\fP\&.
.SS "lctm::BaseVideoDecoderCodecApi::~BaseVideoDecoderCodecApi ()\fC [override]\fP"

.PP
Definition at line \fB126\fP of file \fBBaseVideoDecoderCodecApi\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void lctm::BaseVideoDecoderCodecApi::push_au (const uint8_t * data, size_t data_size, uint64_t pts, bool is_idr, int iPictureType)\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBlctm::BaseVideoDecoder\fP\&.
.PP
Definition at line \fB152\fP of file \fBBaseVideoDecoderCodecApi\&.cpp\fP\&.
.SS "void lctm::BaseVideoDecoderCodecApi::start ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBlctm::BaseVideoDecoder\fP\&.
.PP
Definition at line \fB128\fP of file \fBBaseVideoDecoderCodecApi\&.cpp\fP\&.
.SS "void lctm::BaseVideoDecoderCodecApi::StatisticsComputation ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBlctm::BaseVideoDecoder\fP\&.
.PP
Definition at line \fB216\fP of file \fBBaseVideoDecoderCodecApi\&.cpp\fP\&.
.SS "void lctm::BaseVideoDecoderCodecApi::stop ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBlctm::BaseVideoDecoder\fP\&.
.PP
Definition at line \fB139\fP of file \fBBaseVideoDecoderCodecApi\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
