.TH "lctm::Serializer" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lctm::Serializer
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Serializer\&.hpp>\fP
.PP
Inherits \fBlctm::Component\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSerializer\fP ()"
.br
.ti -1c
.RI "\fBPacket\fP \fBemit\fP (const \fBSignaledConfiguration\fP &configuration, unsigned block_mask, const \fBSurface\fP symbols[\fBMAX_NUM_PLANES\fP][\fBMAX_NUM_LOQS\fP][\fBMAX_NUM_LAYERS\fP])"
.br
.ti -1c
.RI "\fBPacket\fP \fBemit_block\fP (const \fBSignaledConfiguration\fP &configuration, unsigned block, const \fBSurface\fP symbols[\fBMAX_NUM_PLANES\fP][\fBMAX_NUM_LOQS\fP][\fBMAX_NUM_LAYERS\fP])"
.br
.ti -1c
.RI "void \fBemit_sequence_configuration\fP (const \fBSequenceConfiguration\fP &sequence_configuration, \fBBitstreamPacker\fP &b)"
.br
.ti -1c
.RI "void \fBemit_global_configuration\fP (const \fBGlobalConfiguration\fP &global_configuration, \fBBitstreamPacker\fP &b)"
.br
.ti -1c
.RI "void \fBemit_picture_configuration\fP (const \fBPictureConfiguration\fP &picture_configuration, \fBBitstreamPacker\fP &b, unsigned num_layers)"
.br
.ti -1c
.RI "void \fBemit_encoded_data\fP (const \fBSignaledConfiguration\fP &configuration, \fBBitstreamPacker\fP &b, const \fBSurface\fP symbols[\fBMAX_NUM_PLANES\fP][\fBMAX_NUM_LOQS\fP][\fBMAX_NUM_LAYERS\fP], unsigned num_layers)"
.br
.ti -1c
.RI "void \fBemit_encoded_data_tiled\fP (const \fBSignaledConfiguration\fP &configuration, \fBBitstreamPacker\fP &b, const \fBSurface\fP symbols[\fBMAX_NUM_PLANES\fP][\fBMAX_NUM_LOQS\fP][\fBMAX_NUM_LAYERS\fP], unsigned num_layers)"
.br
.ti -1c
.RI "void \fBemit_additional_info\fP (const \fBAdditionalInfo\fP &additional_info, \fBBitstreamPacker\fP &b)"
.br
.ti -1c
.RI "void \fBemit_filler\fP (\fBBitstreamPacker\fP &b, unsigned size)"
.br
.in -1c

Public Member Functions inherited from \fBlctm::Component\fP
.in +1c
.ti -1c
.RI "\fBComponent\fP (const std::string &\fBname\fP)"
.br
.ti -1c
.RI "virtual \fB~Component\fP ()=0"
.br
.ti -1c
.RI "virtual const std::string \fBname\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB49\fP of file \fBSerializer\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "lctm::Serializer::Serializer ()\fC [inline]\fP"

.PP
Definition at line \fB51\fP of file \fBSerializer\&.hpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBPacket\fP lctm::Serializer::emit (const \fBSignaledConfiguration\fP & configuration, unsigned block_mask, const \fBSurface\fP symbols[MAX_NUM_PLANES][MAX_NUM_LOQS][MAX_NUM_LAYERS])"

.PP
Definition at line \fB82\fP of file \fBSerializer\&.cpp\fP\&.
.SS "void lctm::Serializer::emit_additional_info (const \fBAdditionalInfo\fP & additional_info, \fBBitstreamPacker\fP & b)"

.PP
Definition at line \fB942\fP of file \fBSerializer\&.cpp\fP\&.
.SS "\fBPacket\fP lctm::Serializer::emit_block (const \fBSignaledConfiguration\fP & configuration, unsigned block, const \fBSurface\fP symbols[MAX_NUM_PLANES][MAX_NUM_LOQS][MAX_NUM_LAYERS])"

.PP
Definition at line \fB96\fP of file \fBSerializer\&.cpp\fP\&.
.SS "void lctm::Serializer::emit_encoded_data (const \fBSignaledConfiguration\fP & configuration, \fBBitstreamPacker\fP & b, const \fBSurface\fP symbols[MAX_NUM_PLANES][MAX_NUM_LOQS][MAX_NUM_LAYERS], unsigned num_layers)"

.PP
Definition at line \fB666\fP of file \fBSerializer\&.cpp\fP\&.
.SS "void lctm::Serializer::emit_encoded_data_tiled (const \fBSignaledConfiguration\fP & configuration, \fBBitstreamPacker\fP & b, const \fBSurface\fP symbols[MAX_NUM_PLANES][MAX_NUM_LOQS][MAX_NUM_LAYERS], unsigned num_layers)"

.PP
Definition at line \fB764\fP of file \fBSerializer\&.cpp\fP\&.
.SS "void lctm::Serializer::emit_filler (\fBBitstreamPacker\fP & b, unsigned size)"

.PP
Definition at line \fB977\fP of file \fBSerializer\&.cpp\fP\&.
.SS "void lctm::Serializer::emit_global_configuration (const \fBGlobalConfiguration\fP & global_configuration, \fBBitstreamPacker\fP & b)"

.PP
Definition at line \fB239\fP of file \fBSerializer\&.cpp\fP\&.
.SS "void lctm::Serializer::emit_picture_configuration (const \fBPictureConfiguration\fP & picture_configuration, \fBBitstreamPacker\fP & b, unsigned num_layers)"

.PP
Definition at line \fB503\fP of file \fBSerializer\&.cpp\fP\&.
.SS "void lctm::Serializer::emit_sequence_configuration (const \fBSequenceConfiguration\fP & sequence_configuration, \fBBitstreamPacker\fP & b)"

.PP
Definition at line \fB199\fP of file \fBSerializer\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
