.TH "lctm::Conform" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lctm::Conform
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Conform\&.hpp>\fP
.PP
Inherits \fBlctm::Component\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBConform\fP ()"
.br
.ti -1c
.RI "\fBSurface\fP \fBprocess\fP (const \fBSurface\fP &plane, unsigned left, unsigned top, unsigned right, unsigned bottom)"
.br
.in -1c

Public Member Functions inherited from \fBlctm::Component\fP
.in +1c
.ti -1c
.RI "\fBComponent\fP (const std::string &\fBname\fP)"
.br
.ti -1c
.RI "virtual \fB~Component\fP ()=0"
.br
.ti -1c
.RI "virtual const std::string \fBname\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB45\fP of file \fBConform\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "lctm::Conform::Conform ()\fC [inline]\fP"

.PP
Definition at line \fB47\fP of file \fBConform\&.hpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBSurface\fP lctm::Conform::process (const \fBSurface\fP & plane, unsigned left, unsigned top, unsigned right, unsigned bottom)"

.PP
Definition at line \fB42\fP of file \fBConform\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
