.TH "lctm::ParameterBase" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lctm::ParameterBase
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Parameters\&.hpp>\fP
.PP
Inherited by \fBlctm::Parameter< T >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBParameterBase\fP (const std::string &\fBname\fP)"
.br
.ti -1c
.RI "virtual \fB~ParameterBase\fP ()=0"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "friend \fBParameterRef\fP"
.br
.ti -1c
.RI "const std::string \fBname_\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB86\fP of file \fBParameters\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "lctm::ParameterBase::ParameterBase (const std::string & name)\fC [inline]\fP"

.PP
Definition at line \fB88\fP of file \fBParameters\&.hpp\fP\&.
.SS "lctm::ParameterBase::~ParameterBase ()\fC [pure virtual]\fP"

.PP
Definition at line \fB82\fP of file \fBParameters\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "const std::string lctm::ParameterBase::name_\fC [protected]\fP"

.PP
Definition at line \fB93\fP of file \fBParameters\&.hpp\fP\&.
.SS "friend lctm::ParameterBase::ParameterRef\fC [protected]\fP"

.PP
Definition at line \fB92\fP of file \fBParameters\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
