.TH "lctm::AdditionalInfo" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lctm::AdditionalInfo
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SignaledConfiguration\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned \fBadditional_info_type\fP"
.br
.ti -1c
.RI "unsigned \fBpayload_type\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB149\fP of file \fBSignaledConfiguration\&.hpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "unsigned lctm::AdditionalInfo::additional_info_type"

.PP
Definition at line \fB150\fP of file \fBSignaledConfiguration\&.hpp\fP\&.
.SS "unsigned lctm::AdditionalInfo::payload_type"

.PP
Definition at line \fB151\fP of file \fBSignaledConfiguration\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
