.TH "lctm::PssPacket" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lctm::PssPacket
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBPacket\fP \fBpacket\fP"
.br
.ti -1c
.RI "bool \fBis_lcevc_idr\fP"
.br
.ti -1c
.RI "bool \fBis_base_idr\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB65\fP of file \fBBaseVideoDecoderCodecApi\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bool lctm::PssPacket::is_base_idr"

.PP
Definition at line \fB77\fP of file \fBBaseVideoDecoderHM\&.cpp\fP\&.
.SS "bool lctm::PssPacket::is_lcevc_idr"

.PP
Definition at line \fB67\fP of file \fBBaseVideoDecoderCodecApi\&.cpp\fP\&.
.SS "\fBPacket\fP lctm::PssPacket::packet"

.PP
Definition at line \fB66\fP of file \fBBaseVideoDecoderCodecApi\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
