.TH "lctm::PacketView" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lctm::PacketView
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Packet\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPacketView\fP (const \fBPacket\fP &\fBpacket\fP)"
.br
.ti -1c
.RI "\fB~PacketView\fP ()"
.br
.ti -1c
.RI "const uint8_t * \fBdata\fP () const"
.br
.ti -1c
.RI "unsigned \fBsize\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB100\fP of file \fBPacket\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "lctm::PacketView::PacketView (const \fBPacket\fP & packet)"

.PP
Definition at line \fB159\fP of file \fBPacket\&.cpp\fP\&.
.SS "lctm::PacketView::~PacketView ()"

.PP
Definition at line \fB168\fP of file \fBPacket\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "const uint8_t * lctm::PacketView::data () const\fC [inline]\fP"

.PP
Definition at line \fB105\fP of file \fBPacket\&.hpp\fP\&.
.SS "unsigned lctm::PacketView::size () const\fC [inline]\fP"

.PP
Definition at line \fB109\fP of file \fBPacket\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
