.TH "lctm::EntropyDecoderFlags" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lctm::EntropyDecoderFlags
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <EntropyDecoder\&.hpp>\fP
.PP
Inherits \fBlctm::Component\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEntropyDecoderFlags\fP ()"
.br
.ti -1c
.RI "\fBSurface\fP \fBprocess\fP (unsigned width, unsigned height, \fBBitstreamUnpacker\fP &b)"
.br
.in -1c

Public Member Functions inherited from \fBlctm::Component\fP
.in +1c
.ti -1c
.RI "\fBComponent\fP (const std::string &\fBname\fP)"
.br
.ti -1c
.RI "virtual \fB~Component\fP ()=0"
.br
.ti -1c
.RI "virtual const std::string \fBname\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB110\fP of file \fBEntropyDecoder\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "lctm::EntropyDecoderFlags::EntropyDecoderFlags ()\fC [inline]\fP"

.PP
Definition at line \fB115\fP of file \fBEntropyDecoder\&.hpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBSurface\fP lctm::EntropyDecoderFlags::process (unsigned width, unsigned height, \fBBitstreamUnpacker\fP & b)"

.PP
Definition at line \fB354\fP of file \fBEntropyDecoder\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
