.TH "lctm::EntropyModelSizes" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lctm::EntropyModelSizes
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEntropyModelSizes\fP ()"
.br
.ti -1c
.RI "void \fBencode_size\fP (uint16_t value)"
.br
.ti -1c
.RI "void \fBencode_size_delta\fP (int32_t value)"
.br
.ti -1c
.RI "\fBEncodedChunk\fP \fBfinish\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB446\fP of file \fBEntropyEncoder\&.cpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "lctm::EntropyModelSizes::EntropyModelSizes ()\fC [inline]\fP"

.PP
Definition at line \fB451\fP of file \fBEntropyEncoder\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void lctm::EntropyModelSizes::encode_size (uint16_t value)"

.PP
Definition at line \fB477\fP of file \fBEntropyEncoder\&.cpp\fP\&.
.SS "void lctm::EntropyModelSizes::encode_size_delta (int32_t value)"

.PP
Definition at line \fB488\fP of file \fBEntropyEncoder\&.cpp\fP\&.
.SS "\fBEncodedChunk\fP lctm::EntropyModelSizes::finish ()"

.PP
Definition at line \fB500\fP of file \fBEntropyEncoder\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
