.TH "lctm::BitstreamUnpacker" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lctm::BitstreamUnpacker
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <BitstreamUnpacker\&.hpp>\fP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBScopedContextLabel\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBitstreamUnpacker\fP (const \fBPacketView\fP &view)"
.br
.ti -1c
.RI "\fB~BitstreamUnpacker\fP ()"
.br
.ti -1c
.RI "uint32_t \fBu\fP (unsigned nbits)"
.br
.ti -1c
.RI "uint32_t \fBu\fP (unsigned nbits, const char *label)"
.br
.ti -1c
.RI "uint8_t \fBbyte\fP ()"
.br
.ti -1c
.RI "\fBPacket\fP \fBbytes\fP (unsigned nbytes)"
.br
.ti -1c
.RI "unsigned \fBbit_offset\fP () const"
.br
.ti -1c
.RI "unsigned \fBbit_size\fP () const"
.br
.ti -1c
.RI "unsigned \fBremaining_bits\fP () const"
.br
.ti -1c
.RI "bool \fBempty\fP () const"
.br
.ti -1c
.RI "void \fBpush_context_label\fP (const std::string &s)"
.br
.ti -1c
.RI "void \fBpop_context_label\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB58\fP of file \fBBitstreamUnpacker\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "lctm::BitstreamUnpacker::BitstreamUnpacker (const \fBPacketView\fP & view)"

.PP
Definition at line \fB73\fP of file \fBBitstreamUnpacker\&.cpp\fP\&.
.SS "lctm::BitstreamUnpacker::~BitstreamUnpacker ()"

.PP
Definition at line \fB84\fP of file \fBBitstreamUnpacker\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "unsigned lctm::BitstreamUnpacker::bit_offset () const\fC [inline]\fP"

.PP
Definition at line \fB75\fP of file \fBBitstreamUnpacker\&.hpp\fP\&.
.SS "unsigned lctm::BitstreamUnpacker::bit_size () const\fC [inline]\fP"

.PP
Definition at line \fB77\fP of file \fBBitstreamUnpacker\&.hpp\fP\&.
.SS "uint8_t lctm::BitstreamUnpacker::byte ()"

.PP
Definition at line \fB127\fP of file \fBBitstreamUnpacker\&.cpp\fP\&.
.SS "\fBPacket\fP lctm::BitstreamUnpacker::bytes (unsigned nbytes)"

.PP
Definition at line \fB152\fP of file \fBBitstreamUnpacker\&.cpp\fP\&.
.SS "bool lctm::BitstreamUnpacker::empty () const\fC [inline]\fP"

.PP
Definition at line \fB81\fP of file \fBBitstreamUnpacker\&.hpp\fP\&.
.SS "void lctm::BitstreamUnpacker::pop_context_label ()"

.PP
Definition at line \fB198\fP of file \fBBitstreamUnpacker\&.cpp\fP\&.
.SS "void lctm::BitstreamUnpacker::push_context_label (const std::string & s)"

.PP
Definition at line \fB192\fP of file \fBBitstreamUnpacker\&.cpp\fP\&.
.SS "unsigned lctm::BitstreamUnpacker::remaining_bits () const\fC [inline]\fP"

.PP
Definition at line \fB79\fP of file \fBBitstreamUnpacker\&.hpp\fP\&.
.SS "uint32_t lctm::BitstreamUnpacker::u (unsigned nbits)"

.PP
Definition at line \fB88\fP of file \fBBitstreamUnpacker\&.cpp\fP\&.
.SS "uint32_t lctm::BitstreamUnpacker::u (unsigned nbits, const char * label)"

.PP
Definition at line \fB179\fP of file \fBBitstreamUnpacker\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
