.TH "lctm::Dimensions" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lctm::Dimensions
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Dimensions\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDimensions\fP ()"
.br
.ti -1c
.RI "void \fBset\fP (const \fBSignaledConfiguration\fP &configuration, unsigned width, unsigned height)"
.br
.ti -1c
.RI "unsigned \fBplane_width\fP (unsigned plane, unsigned loq=\fBLOQ_LEVEL_2\fP) const"
.br
.ti -1c
.RI "unsigned \fBplane_height\fP (unsigned plane, unsigned loq=\fBLOQ_LEVEL_2\fP) const"
.br
.ti -1c
.RI "unsigned \fBlayer_width\fP (unsigned plane, unsigned loq=\fBLOQ_LEVEL_2\fP) const"
.br
.ti -1c
.RI "unsigned \fBlayer_height\fP (unsigned plane, unsigned loq=\fBLOQ_LEVEL_2\fP) const"
.br
.ti -1c
.RI "unsigned \fBtile_width\fP (unsigned plane, unsigned loq=\fBLOQ_LEVEL_2\fP) const"
.br
.ti -1c
.RI "unsigned \fBtile_height\fP (unsigned plane, unsigned loq=\fBLOQ_LEVEL_2\fP) const"
.br
.ti -1c
.RI "unsigned \fBconformant_width\fP (unsigned plane=0) const"
.br
.ti -1c
.RI "unsigned \fBconformant_height\fP (unsigned plane=0) const"
.br
.ti -1c
.RI "unsigned \fBcrop_unit_width\fP (unsigned plane=0) const"
.br
.ti -1c
.RI "unsigned \fBcrop_unit_height\fP (unsigned plane=0) const"
.br
.ti -1c
.RI "unsigned \fBintermediate_width\fP () const"
.br
.ti -1c
.RI "unsigned \fBintermediate_height\fP () const"
.br
.ti -1c
.RI "unsigned \fBbase_width\fP () const"
.br
.ti -1c
.RI "unsigned \fBbase_height\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB46\fP of file \fBDimensions\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "lctm::Dimensions::Dimensions ()"

.PP
Definition at line \fB46\fP of file \fBDimensions\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "unsigned lctm::Dimensions::base_height () const\fC [inline]\fP"

.PP
Definition at line \fB71\fP of file \fBDimensions\&.hpp\fP\&.
.SS "unsigned lctm::Dimensions::base_width () const\fC [inline]\fP"

.PP
Definition at line \fB70\fP of file \fBDimensions\&.hpp\fP\&.
.SS "unsigned lctm::Dimensions::conformant_height (unsigned plane = \fC0\fP) const\fC [inline]\fP"

.PP
Definition at line \fB62\fP of file \fBDimensions\&.hpp\fP\&.
.SS "unsigned lctm::Dimensions::conformant_width (unsigned plane = \fC0\fP) const\fC [inline]\fP"

.PP
Definition at line \fB61\fP of file \fBDimensions\&.hpp\fP\&.
.SS "unsigned lctm::Dimensions::crop_unit_height (unsigned plane = \fC0\fP) const\fC [inline]\fP"

.PP
Definition at line \fB65\fP of file \fBDimensions\&.hpp\fP\&.
.SS "unsigned lctm::Dimensions::crop_unit_width (unsigned plane = \fC0\fP) const\fC [inline]\fP"

.PP
Definition at line \fB64\fP of file \fBDimensions\&.hpp\fP\&.
.SS "unsigned lctm::Dimensions::intermediate_height () const\fC [inline]\fP"

.PP
Definition at line \fB68\fP of file \fBDimensions\&.hpp\fP\&.
.SS "unsigned lctm::Dimensions::intermediate_width () const\fC [inline]\fP"

.PP
Definition at line \fB67\fP of file \fBDimensions\&.hpp\fP\&.
.SS "unsigned lctm::Dimensions::layer_height (unsigned plane, unsigned loq = \fC\fBLOQ_LEVEL_2\fP\fP) const\fC [inline]\fP"

.PP
Definition at line \fB56\fP of file \fBDimensions\&.hpp\fP\&.
.SS "unsigned lctm::Dimensions::layer_width (unsigned plane, unsigned loq = \fC\fBLOQ_LEVEL_2\fP\fP) const\fC [inline]\fP"

.PP
Definition at line \fB55\fP of file \fBDimensions\&.hpp\fP\&.
.SS "unsigned lctm::Dimensions::plane_height (unsigned plane, unsigned loq = \fC\fBLOQ_LEVEL_2\fP\fP) const\fC [inline]\fP"

.PP
Definition at line \fB53\fP of file \fBDimensions\&.hpp\fP\&.
.SS "unsigned lctm::Dimensions::plane_width (unsigned plane, unsigned loq = \fC\fBLOQ_LEVEL_2\fP\fP) const\fC [inline]\fP"

.PP
Definition at line \fB52\fP of file \fBDimensions\&.hpp\fP\&.
.SS "void lctm::Dimensions::set (const \fBSignaledConfiguration\fP & configuration, unsigned width, unsigned height)"

.PP
Definition at line \fB114\fP of file \fBDimensions\&.cpp\fP\&.
.SS "unsigned lctm::Dimensions::tile_height (unsigned plane, unsigned loq = \fC\fBLOQ_LEVEL_2\fP\fP) const\fC [inline]\fP"

.PP
Definition at line \fB59\fP of file \fBDimensions\&.hpp\fP\&.
.SS "unsigned lctm::Dimensions::tile_width (unsigned plane, unsigned loq = \fC\fBLOQ_LEVEL_2\fP\fP) const\fC [inline]\fP"

.PP
Definition at line \fB58\fP of file \fBDimensions\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
