.TH "lctm::GlobalConfiguration" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lctm::GlobalConfiguration
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SignaledConfiguration\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned \fBbase_depth\fP"
.br
.ti -1c
.RI "unsigned \fBenhancement_depth\fP"
.br
.ti -1c
.RI "\fBColourspace\fP \fBcolourspace\fP"
.br
.ti -1c
.RI "\fBImageFormat\fP \fBimage_format\fP"
.br
.ti -1c
.RI "unsigned \fBnum_image_planes\fP"
.br
.ti -1c
.RI "unsigned \fBnum_processed_planes\fP"
.br
.ti -1c
.RI "unsigned \fBnum_residual_layers\fP"
.br
.ti -1c
.RI "unsigned \fBtransform_block_size\fP"
.br
.ti -1c
.RI "bool \fBpredicted_residual_enabled\fP"
.br
.ti -1c
.RI "unsigned \fBresolution_height\fP"
.br
.ti -1c
.RI "unsigned \fBresolution_width\fP"
.br
.ti -1c
.RI "unsigned \fBtemporal_enabled\fP"
.br
.ti -1c
.RI "bool \fBtemporal_tile_intra_signalling_enabled\fP"
.br
.ti -1c
.RI "unsigned \fBtemporal_step_width_modifier\fP"
.br
.ti -1c
.RI "\fBUpsample\fP \fBupsample\fP"
.br
.ti -1c
.RI "unsigned \fBlevel_1_filtering_first_coefficient\fP"
.br
.ti -1c
.RI "unsigned \fBlevel_1_filtering_second_coefficient\fP"
.br
.ti -1c
.RI "\fBScalingMode\fP \fBscaling_mode\fP [\fBMAX_NUM_LOQS\fP]"
.br
.ti -1c
.RI "\fBTileDimensions\fP \fBtile_dimensions_type\fP"
.br
.ti -1c
.RI "\fBUserDataMode\fP \fBuser_data_enabled\fP"
.br
.ti -1c
.RI "bool \fBlevel1_depth_flag\fP"
.br
.ti -1c
.RI "unsigned \fBchroma_step_width_multiplier\fP"
.br
.ti -1c
.RI "unsigned \fBtile_width\fP"
.br
.ti -1c
.RI "unsigned \fBtile_height\fP"
.br
.ti -1c
.RI "bool \fBcompression_type_entropy_enabled_per_tile\fP"
.br
.ti -1c
.RI "\fBCompressionType\fP \fBcompression_type_size_per_tile\fP"
.br
.ti -1c
.RI "unsigned \fBupsampling_coefficients\fP [4]"
.br
.ti -1c
.RI "bool \fBadditional_info_present\fP"
.br
.ti -1c
.RI "unsigned \fBadditional_info_type\fP"
.br
.ti -1c
.RI "bool \fBsei_message_present\fP"
.br
.ti -1c
.RI "bool \fBvui_message_present\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB85\fP of file \fBSignaledConfiguration\&.hpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bool lctm::GlobalConfiguration::additional_info_present"

.PP
Definition at line \fB114\fP of file \fBSignaledConfiguration\&.hpp\fP\&.
.SS "unsigned lctm::GlobalConfiguration::additional_info_type"

.PP
Definition at line \fB115\fP of file \fBSignaledConfiguration\&.hpp\fP\&.
.SS "unsigned lctm::GlobalConfiguration::base_depth"

.PP
Definition at line \fB86\fP of file \fBSignaledConfiguration\&.hpp\fP\&.
.SS "unsigned lctm::GlobalConfiguration::chroma_step_width_multiplier"

.PP
Definition at line \fB107\fP of file \fBSignaledConfiguration\&.hpp\fP\&.
.SS "\fBColourspace\fP lctm::GlobalConfiguration::colourspace"

.PP
Definition at line \fB88\fP of file \fBSignaledConfiguration\&.hpp\fP\&.
.SS "bool lctm::GlobalConfiguration::compression_type_entropy_enabled_per_tile"

.PP
Definition at line \fB110\fP of file \fBSignaledConfiguration\&.hpp\fP\&.
.SS "\fBCompressionType\fP lctm::GlobalConfiguration::compression_type_size_per_tile"

.PP
Definition at line \fB111\fP of file \fBSignaledConfiguration\&.hpp\fP\&.
.SS "unsigned lctm::GlobalConfiguration::enhancement_depth"

.PP
Definition at line \fB87\fP of file \fBSignaledConfiguration\&.hpp\fP\&.
.SS "\fBImageFormat\fP lctm::GlobalConfiguration::image_format"

.PP
Definition at line \fB89\fP of file \fBSignaledConfiguration\&.hpp\fP\&.
.SS "bool lctm::GlobalConfiguration::level1_depth_flag"

.PP
Definition at line \fB106\fP of file \fBSignaledConfiguration\&.hpp\fP\&.
.SS "unsigned lctm::GlobalConfiguration::level_1_filtering_first_coefficient"

.PP
Definition at line \fB101\fP of file \fBSignaledConfiguration\&.hpp\fP\&.
.SS "unsigned lctm::GlobalConfiguration::level_1_filtering_second_coefficient"

.PP
Definition at line \fB102\fP of file \fBSignaledConfiguration\&.hpp\fP\&.
.SS "unsigned lctm::GlobalConfiguration::num_image_planes"

.PP
Definition at line \fB90\fP of file \fBSignaledConfiguration\&.hpp\fP\&.
.SS "unsigned lctm::GlobalConfiguration::num_processed_planes"

.PP
Definition at line \fB91\fP of file \fBSignaledConfiguration\&.hpp\fP\&.
.SS "unsigned lctm::GlobalConfiguration::num_residual_layers"

.PP
Definition at line \fB92\fP of file \fBSignaledConfiguration\&.hpp\fP\&.
.SS "bool lctm::GlobalConfiguration::predicted_residual_enabled"

.PP
Definition at line \fB94\fP of file \fBSignaledConfiguration\&.hpp\fP\&.
.SS "unsigned lctm::GlobalConfiguration::resolution_height"

.PP
Definition at line \fB95\fP of file \fBSignaledConfiguration\&.hpp\fP\&.
.SS "unsigned lctm::GlobalConfiguration::resolution_width"

.PP
Definition at line \fB96\fP of file \fBSignaledConfiguration\&.hpp\fP\&.
.SS "\fBScalingMode\fP lctm::GlobalConfiguration::scaling_mode[\fBMAX_NUM_LOQS\fP]"

.PP
Definition at line \fB103\fP of file \fBSignaledConfiguration\&.hpp\fP\&.
.SS "bool lctm::GlobalConfiguration::sei_message_present"

.PP
Definition at line \fB116\fP of file \fBSignaledConfiguration\&.hpp\fP\&.
.SS "unsigned lctm::GlobalConfiguration::temporal_enabled"

.PP
Definition at line \fB97\fP of file \fBSignaledConfiguration\&.hpp\fP\&.
.SS "unsigned lctm::GlobalConfiguration::temporal_step_width_modifier"

.PP
Definition at line \fB99\fP of file \fBSignaledConfiguration\&.hpp\fP\&.
.SS "bool lctm::GlobalConfiguration::temporal_tile_intra_signalling_enabled"

.PP
Definition at line \fB98\fP of file \fBSignaledConfiguration\&.hpp\fP\&.
.SS "\fBTileDimensions\fP lctm::GlobalConfiguration::tile_dimensions_type"

.PP
Definition at line \fB104\fP of file \fBSignaledConfiguration\&.hpp\fP\&.
.SS "unsigned lctm::GlobalConfiguration::tile_height"

.PP
Definition at line \fB109\fP of file \fBSignaledConfiguration\&.hpp\fP\&.
.SS "unsigned lctm::GlobalConfiguration::tile_width"

.PP
Definition at line \fB108\fP of file \fBSignaledConfiguration\&.hpp\fP\&.
.SS "unsigned lctm::GlobalConfiguration::transform_block_size"

.PP
Definition at line \fB93\fP of file \fBSignaledConfiguration\&.hpp\fP\&.
.SS "\fBUpsample\fP lctm::GlobalConfiguration::upsample"

.PP
Definition at line \fB100\fP of file \fBSignaledConfiguration\&.hpp\fP\&.
.SS "unsigned lctm::GlobalConfiguration::upsampling_coefficients[4]"

.PP
Definition at line \fB112\fP of file \fBSignaledConfiguration\&.hpp\fP\&.
.SS "\fBUserDataMode\fP lctm::GlobalConfiguration::user_data_enabled"

.PP
Definition at line \fB105\fP of file \fBSignaledConfiguration\&.hpp\fP\&.
.SS "bool lctm::GlobalConfiguration::vui_message_present"

.PP
Definition at line \fB117\fP of file \fBSignaledConfiguration\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
