.TH "lctm::Decoder" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lctm::Decoder
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Decoder\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDecoder\fP ()"
.br
.ti -1c
.RI "\fBImage\fP \fBdecode\fP (const \fBImage\fP &base, \fBSurface\fP(&symbols)[\fBMAX_NUM_PLANES\fP][\fBMAX_NUM_LOQS\fP][\fBMAX_NUM_LAYERS\fP], const \fBImage\fP &src_image, bool report, bool dithering_switch, bool dithering_fixed, bool apply_enhancement)"
.br
.ti -1c
.RI "void \fBinitialize_decode\fP (const \fBPacket\fP &enhancement_data, \fBSurface\fP(&symbols)[\fBMAX_NUM_PLANES\fP][\fBMAX_NUM_LOQS\fP][\fBMAX_NUM_LAYERS\fP])"
.br
.ti -1c
.RI "\fBSignaledConfiguration\fP \fBget_configuration\fP ()"
.br
.ti -1c
.RI "\fBDimensions\fP \fBget_dimensions\fP ()"
.br
.ti -1c
.RI "void \fBset_idr\fP (bool is_idr)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB56\fP of file \fBDecoder\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "lctm::Decoder::Decoder ()"

.PP
Definition at line \fB77\fP of file \fBDecoder\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBImage\fP lctm::Decoder::decode (const \fBImage\fP & base, \fBSurface\fP(&) symbols[MAX_NUM_PLANES][MAX_NUM_LOQS][MAX_NUM_LAYERS], const \fBImage\fP & src_image, bool report, bool dithering_switch, bool dithering_fixed, bool apply_enhancement)"

.PP
Definition at line \fB361\fP of file \fBDecoder\&.cpp\fP\&.
.SS "\fBSignaledConfiguration\fP lctm::Decoder::get_configuration ()\fC [inline]\fP"

.PP
Definition at line \fB66\fP of file \fBDecoder\&.hpp\fP\&.
.SS "\fBDimensions\fP lctm::Decoder::get_dimensions ()\fC [inline]\fP"

.PP
Definition at line \fB67\fP of file \fBDecoder\&.hpp\fP\&.
.SS "void lctm::Decoder::initialize_decode (const \fBPacket\fP & enhancement_data, \fBSurface\fP(&) symbols[MAX_NUM_PLANES][MAX_NUM_LOQS][MAX_NUM_LAYERS])"

.PP
Definition at line \fB313\fP of file \fBDecoder\&.cpp\fP\&.
.SS "void lctm::Decoder::set_idr (bool is_idr)\fC [inline]\fP"

.PP
Definition at line \fB69\fP of file \fBDecoder\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
