.TH "lctm::LayerEncodeFlags" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lctm::LayerEncodeFlags
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <LayerEncodeFlags\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLayerEncodeFlags\fP (\fBTransformType\fP \fBtransform_type\fP, \fBEncodingMode\fP enc_mode)"
.br
.ti -1c
.RI "\fBTransformType\fP \fBtransform_type\fP () const"
.br
.ti -1c
.RI "\fBEncodingMode\fP \fBencoding_mode\fP () const"
.br
.ti -1c
.RI "bool \fBencode_residual\fP (unsigned layer) const"
.br
.ti -1c
.RI "size_t \fBsize\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB104\fP of file \fBLayerEncodeFlags\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "lctm::LayerEncodeFlags::LayerEncodeFlags (\fBTransformType\fP transform_type, \fBEncodingMode\fP enc_mode)"

.PP
Definition at line \fB115\fP of file \fBLayerEncodeFlags\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "bool lctm::LayerEncodeFlags::encode_residual (unsigned layer) const"

.PP
Definition at line \fB128\fP of file \fBLayerEncodeFlags\&.cpp\fP\&.
.SS "\fBEncodingMode\fP lctm::LayerEncodeFlags::encoding_mode () const"

.PP
Definition at line \fB126\fP of file \fBLayerEncodeFlags\&.cpp\fP\&.
.SS "size_t lctm::LayerEncodeFlags::size () const"

.PP
Definition at line \fB130\fP of file \fBLayerEncodeFlags\&.cpp\fP\&.
.SS "\fBTransformType\fP lctm::LayerEncodeFlags::transform_type () const"

.PP
Definition at line \fB124\fP of file \fBLayerEncodeFlags\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
