.TH "lctm::EncodedLayer" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lctm::EncodedLayer
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <EncodedLayer\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBPacket\fP \fBdata\fP"
.br
.ti -1c
.RI "bool \fBentropy_enabled_\fP = false"
.br
.ti -1c
.RI "bool \fBrle_only_\fP = false"
.br
.ti -1c
.RI "\fBSurface\fP \fBsymbols\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB45\fP of file \fBEncodedLayer\&.hpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBPacket\fP lctm::EncodedLayer::data"

.PP
Definition at line \fB46\fP of file \fBEncodedLayer\&.hpp\fP\&.
.SS "bool lctm::EncodedLayer::entropy_enabled_ = false"

.PP
Definition at line \fB47\fP of file \fBEncodedLayer\&.hpp\fP\&.
.SS "bool lctm::EncodedLayer::rle_only_ = false"

.PP
Definition at line \fB48\fP of file \fBEncodedLayer\&.hpp\fP\&.
.SS "\fBSurface\fP lctm::EncodedLayer::symbols"

.PP
Definition at line \fB49\fP of file \fBEncodedLayer\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
