.TH "lctm::InverseQuantize" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lctm::InverseQuantize
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <InverseQuantize\&.hpp>\fP
.PP
Inherits \fBlctm::Component\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBInverseQuantize\fP ()"
.br
.ti -1c
.RI "\fBSurface\fP \fBprocess\fP (const \fBSurface\fP &src_plane, int32_t invq_step_width, int32_t applied_dequant_offset)"
.br
.in -1c

Public Member Functions inherited from \fBlctm::Component\fP
.in +1c
.ti -1c
.RI "\fBComponent\fP (const std::string &\fBname\fP)"
.br
.ti -1c
.RI "virtual \fB~Component\fP ()=0"
.br
.ti -1c
.RI "virtual const std::string \fBname\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB63\fP of file \fBInverseQuantize\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "lctm::InverseQuantize::InverseQuantize ()\fC [inline]\fP"

.PP
Definition at line \fB65\fP of file \fBInverseQuantize\&.hpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBSurface\fP lctm::InverseQuantize::process (const \fBSurface\fP & src_plane, int32_t invq_step_width, int32_t applied_dequant_offset)"

.PP
Definition at line \fB232\fP of file \fBInverseQuantize\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
