.TH "lctm::EncodedChunk" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lctm::EncodedChunk
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <EntropyEncoder\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEncodedChunk\fP ()"
.br
.ti -1c
.RI "\fBEncodedChunk\fP (const \fBPacket\fP &r, const \fBPacket\fP &p)"
.br
.ti -1c
.RI "bool \fBempty\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBPacket\fP \fBraw\fP"
.br
.ti -1c
.RI "\fBPacket\fP \fBprefix\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB52\fP of file \fBEntropyEncoder\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "lctm::EncodedChunk::EncodedChunk ()\fC [inline]\fP"

.PP
Definition at line \fB53\fP of file \fBEntropyEncoder\&.hpp\fP\&.
.SS "lctm::EncodedChunk::EncodedChunk (const \fBPacket\fP & r, const \fBPacket\fP & p)\fC [inline]\fP"

.PP
Definition at line \fB54\fP of file \fBEntropyEncoder\&.hpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "bool lctm::EncodedChunk::empty () const\fC [inline]\fP"

.PP
Definition at line \fB55\fP of file \fBEntropyEncoder\&.hpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBPacket\fP lctm::EncodedChunk::prefix"

.PP
Definition at line \fB58\fP of file \fBEntropyEncoder\&.hpp\fP\&.
.SS "\fBPacket\fP lctm::EncodedChunk::raw"

.PP
Definition at line \fB57\fP of file \fBEntropyEncoder\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
