.TH "lctm::Buffer" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lctm::Buffer
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Buffer\&.hpp>\fP
.PP
Inherited by \fBlctm::BufferAligned\fP, and \fBlctm::BufferVector\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~Buffer\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBmap_read\fP (unsigned offset, unsigned size, const uint8_t *&mapped_data, unsigned &mapped_size) const =0"
.br
.ti -1c
.RI "virtual void \fBmap_write\fP (unsigned offset, unsigned size, uint8_t *&mapped_data, unsigned &mapped_size)=0"
.br
.ti -1c
.RI "virtual void \fBunmap\fP () const =0"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBBuffer\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB48\fP of file \fBBuffer\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "lctm::Buffer::~Buffer ()\fC [pure virtual]\fP"

.PP
Definition at line \fB64\fP of file \fBBuffer\&.cpp\fP\&.
.SS "lctm::Buffer::Buffer ()\fC [protected]\fP"

.PP
Definition at line \fB62\fP of file \fBBuffer\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual void lctm::Buffer::map_read (unsigned offset, unsigned size, const uint8_t *& mapped_data, unsigned & mapped_size) const\fC [pure virtual]\fP"

.PP
Implemented in \fBlctm::BufferVector\fP, and \fBlctm::BufferAligned\fP\&.
.SS "virtual void lctm::Buffer::map_write (unsigned offset, unsigned size, uint8_t *& mapped_data, unsigned & mapped_size)\fC [pure virtual]\fP"

.PP
Implemented in \fBlctm::BufferVector\fP, and \fBlctm::BufferAligned\fP\&.
.SS "virtual void lctm::Buffer::unmap () const\fC [pure virtual]\fP"

.PP
Implemented in \fBlctm::BufferVector\fP, and \fBlctm::BufferAligned\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
