.TH "lctm::EncodeBits_DD" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lctm::EncodeBits_DD
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <LayerEncodeFlags\&.hpp>\fP
.PP
Inherits \fBlctm::EncodeBits\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEncodeBits_DD\fP (\fBEncodingMode\fP enc_mode)"
.br
.ti -1c
.RI "\fBTransformType\fP \fBtransform_type\fP () const override"
.br
.ti -1c
.RI "bool \fBencode_residual\fP (unsigned layer) const override"
.br
.ti -1c
.RI "size_t \fBsize\fP () const override"
.br
.ti -1c
.RI "\fB~EncodeBits_DD\fP () override"
.br
.in -1c

Public Member Functions inherited from \fBlctm::EncodeBits\fP
.in +1c
.ti -1c
.RI "\fBEncodeBits\fP (\fBEncodingMode\fP enc_mode)"
.br
.ti -1c
.RI "\fBEncodingMode\fP \fBencoding_mode\fP () const"
.br
.ti -1c
.RI "virtual \fB~EncodeBits\fP ()=default"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB68\fP of file \fBLayerEncodeFlags\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "lctm::EncodeBits_DD::EncodeBits_DD (\fBEncodingMode\fP enc_mode)"

.PP
Definition at line \fB50\fP of file \fBLayerEncodeFlags\&.cpp\fP\&.
.SS "lctm::EncodeBits_DD::~EncodeBits_DD ()\fC [inline]\fP, \fC [override]\fP"

.PP
Definition at line \fB78\fP of file \fBLayerEncodeFlags\&.hpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "bool lctm::EncodeBits_DD::encode_residual (unsigned layer) const\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBlctm::EncodeBits\fP\&.
.PP
Definition at line \fB74\fP of file \fBLayerEncodeFlags\&.cpp\fP\&.
.SS "size_t lctm::EncodeBits_DD::size () const\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBlctm::EncodeBits\fP\&.
.PP
Definition at line \fB79\fP of file \fBLayerEncodeFlags\&.cpp\fP\&.
.SS "\fBTransformType\fP lctm::EncodeBits_DD::transform_type () const\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBlctm::EncodeBits\fP\&.
.PP
Definition at line \fB72\fP of file \fBLayerEncodeFlags\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
