.TH "lctm::Encoder" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lctm::Encoder
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Encoder\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEncoder\fP (const \fBImageDescription\fP &image_description, const \fBParameters\fP &parameters)"
.br
.ti -1c
.RI "void \fBinitialise_config\fP (const \fBParameters\fP &parameters, std::vector< std::unique_ptr< \fBImage\fP > > &src_image)"
.br
.ti -1c
.RI "const \fBDimensions\fP & \fBdimensions\fP () const"
.br
.ti -1c
.RI "\fBPacket\fP \fBencode\fP (std::vector< std::unique_ptr< \fBImage\fP > > &src, const \fBImage\fP &intermediate_src, const \fBImage\fP &base_recon, \fBBaseFrameType\fP frame_type, bool is_idr, int gop_frame_num, const std::string &output_file)"
.br
.ti -1c
.RI "unsigned \fBtransform_block_size\fP () const"
.br
.ti -1c
.RI "unsigned \fBnum_residual_layers\fP () const"
.br
.ti -1c
.RI "bool \fBlevel1_depth_flag\fP () const"
.br
.ti -1c
.RI "unsigned \fBbase_qp\fP () const"
.br
.ti -1c
.RI "const \fBImageDescription\fP & \fBsrc_image_description\fP () const"
.br
.ti -1c
.RI "const \fBImageDescription\fP & \fBbase_image_description\fP () const"
.br
.ti -1c
.RI "const \fBImageDescription\fP & \fBintermediate_image_description\fP () const"
.br
.ti -1c
.RI "const \fBImageDescription\fP & \fBenhancement_image_description\fP () const"
.br
.ti -1c
.RI "void \fBset_last_idr_frame_num\fP (int32_t frame_num)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB66\fP of file \fBEncoder\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "lctm::Encoder::Encoder (const \fBImageDescription\fP & image_description, const \fBParameters\fP & parameters)"

.PP
Definition at line \fB102\fP of file \fBEncoder\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "const \fBImageDescription\fP & lctm::Encoder::base_image_description () const\fC [inline]\fP"

.PP
Definition at line \fB82\fP of file \fBEncoder\&.hpp\fP\&.
.SS "unsigned lctm::Encoder::base_qp () const"

.PP
Definition at line \fB982\fP of file \fBEncoder\&.cpp\fP\&.
.SS "const \fBDimensions\fP & lctm::Encoder::dimensions () const\fC [inline]\fP"

.PP
Definition at line \fB71\fP of file \fBEncoder\&.hpp\fP\&.
.SS "\fBPacket\fP lctm::Encoder::encode (std::vector< std::unique_ptr< \fBImage\fP > > & src, const \fBImage\fP & intermediate_src, const \fBImage\fP & base_recon, \fBBaseFrameType\fP frame_type, bool is_idr, int gop_frame_num, const std::string & output_file)"

.PP
Definition at line \fB986\fP of file \fBEncoder\&.cpp\fP\&.
.SS "const \fBImageDescription\fP & lctm::Encoder::enhancement_image_description () const\fC [inline]\fP"

.PP
Definition at line \fB84\fP of file \fBEncoder\&.hpp\fP\&.
.SS "void lctm::Encoder::initialise_config (const \fBParameters\fP & parameters, std::vector< std::unique_ptr< \fBImage\fP > > & src_image)"

.PP
Definition at line \fB127\fP of file \fBEncoder\&.cpp\fP\&.
.SS "const \fBImageDescription\fP & lctm::Encoder::intermediate_image_description () const\fC [inline]\fP"

.PP
Definition at line \fB83\fP of file \fBEncoder\&.hpp\fP\&.
.SS "bool lctm::Encoder::level1_depth_flag () const"

.PP
Definition at line \fB980\fP of file \fBEncoder\&.cpp\fP\&.
.SS "unsigned lctm::Encoder::num_residual_layers () const"

.PP
Definition at line \fB978\fP of file \fBEncoder\&.cpp\fP\&.
.SS "void lctm::Encoder::set_last_idr_frame_num (int32_t frame_num)\fC [inline]\fP"

.PP
Definition at line \fB86\fP of file \fBEncoder\&.hpp\fP\&.
.SS "const \fBImageDescription\fP & lctm::Encoder::src_image_description () const\fC [inline]\fP"

.PP
Definition at line \fB81\fP of file \fBEncoder\&.hpp\fP\&.
.SS "unsigned lctm::Encoder::transform_block_size () const"

.PP
Definition at line \fB976\fP of file \fBEncoder\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
