.TH "lctm::ConvertRightShiftToU16" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lctm::ConvertRightShiftToU16
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Convert\&.hpp>\fP
.PP
Inherits \fBlctm::Component\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBConvertRightShiftToU16\fP ()"
.br
.ti -1c
.RI "\fBSurface\fP \fBprocess\fP (const \fBSurface\fP &surface, unsigned shift)"
.br
.in -1c

Public Member Functions inherited from \fBlctm::Component\fP
.in +1c
.ti -1c
.RI "\fBComponent\fP (const std::string &\fBname\fP)"
.br
.ti -1c
.RI "virtual \fB~Component\fP ()=0"
.br
.ti -1c
.RI "virtual const std::string \fBname\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB130\fP of file \fBConvert\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "lctm::ConvertRightShiftToU16::ConvertRightShiftToU16 ()\fC [inline]\fP"

.PP
Definition at line \fB132\fP of file \fBConvert\&.hpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBSurface\fP lctm::ConvertRightShiftToU16::process (const \fBSurface\fP & surface, unsigned shift)"

.PP
Definition at line \fB351\fP of file \fBConvert\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
