.TH "lctm::PriorityMap" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lctm::PriorityMap
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <PriorityMap\&.hpp>\fP
.PP
Inherits \fBlctm::Component\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBEnumBlockType\fP { \fBPlain\fP = 32, \fBEdge\fP = 64, \fBSmoothTexture\fP = 96, \fBCoarseTexture\fP = 128, \fBMax\fP = 255 }"
.br
.ti -1c
.RI "using \fBvalue_type\fP = int16_t"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPriorityMap\fP ()"
.br
.ti -1c
.RI "\fBSurface\fP \fBprocess\fP (const \fBSurface\fP &src_plane, unsigned priority_tile_x, unsigned priority_tile_y, \fBKillingFunction\fP killing_function=\fBKillingFunction::KILL_ALL\fP)"
.br
.ti -1c
.RI "\fBSurface\fP \fBComputeMeanValue\fP (const \fBSurface\fP &src_surface)"
.br
.ti -1c
.RI "\fBSurface\fP \fBComputeContrastTexture\fP (const \fBSurface\fP &src_surface, \fBSurface\fP &mean_surface)"
.br
.ti -1c
.RI "\fBSurface\fP \fBApplyPriorityResiduals\fP (\fBSurface\fP &src_surface, \fBSurface\fP &type_surface, unsigned step_width)"
.br
.ti -1c
.RI "void \fBApplyPriorityCoefficients\fP (int width, int height, int tu_size, int sublayer, \fBSurface\fP src_surface[], \fBSurface\fP dst_surface[], const \fBSurface\fP &type_surface, const \fBSurface\fP &pixel_sad, unsigned step_width, \fBPriorityMBType\fP priority_mb_type, \fBEncodingMode\fP mode)"
.br
.in -1c

Public Member Functions inherited from \fBlctm::Component\fP
.in +1c
.ti -1c
.RI "\fBComponent\fP (const std::string &\fBname\fP)"
.br
.ti -1c
.RI "virtual \fB~Component\fP ()=0"
.br
.ti -1c
.RI "virtual const std::string \fBname\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB62\fP of file \fBPriorityMap\&.hpp\fP\&.
.SH "Member Typedef Documentation"
.PP 
.SS "using \fBlctm::PriorityMap::value_type\fP =  int16_t"

.PP
Definition at line \fB67\fP of file \fBPriorityMap\&.hpp\fP\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBlctm::PriorityMap::EnumBlockType\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIPlain \fP\fP
.TP
\fB\fIEdge \fP\fP
.TP
\fB\fISmoothTexture \fP\fP
.TP
\fB\fICoarseTexture \fP\fP
.TP
\fB\fIMax \fP\fP
.PP
Definition at line \fB64\fP of file \fBPriorityMap\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "lctm::PriorityMap::PriorityMap ()\fC [inline]\fP"

.PP
Definition at line \fB69\fP of file \fBPriorityMap\&.hpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void lctm::PriorityMap::ApplyPriorityCoefficients (int width, int height, int tu_size, int sublayer, \fBSurface\fP src_surface[], \fBSurface\fP dst_surface[], const \fBSurface\fP & type_surface, const \fBSurface\fP & pixel_sad, unsigned step_width, \fBPriorityMBType\fP priority_mb_type, \fBEncodingMode\fP mode)"

.PP
Definition at line \fB284\fP of file \fBPriorityMap\&.cpp\fP\&.
.SS "\fBSurface\fP lctm::PriorityMap::ApplyPriorityResiduals (\fBSurface\fP & src_surface, \fBSurface\fP & type_surface, unsigned step_width)"

.PP
Definition at line \fB254\fP of file \fBPriorityMap\&.cpp\fP\&.
.SS "\fBSurface\fP lctm::PriorityMap::ComputeContrastTexture (const \fBSurface\fP & src_surface, \fBSurface\fP & mean_surface)"

.PP
Definition at line \fB173\fP of file \fBPriorityMap\&.cpp\fP\&.
.SS "\fBSurface\fP lctm::PriorityMap::ComputeMeanValue (const \fBSurface\fP & src_surface)"

.PP
Definition at line \fB151\fP of file \fBPriorityMap\&.cpp\fP\&.
.SS "\fBSurface\fP lctm::PriorityMap::process (const \fBSurface\fP & src_plane, unsigned priority_tile_x, unsigned priority_tile_y, \fBKillingFunction\fP killing_function = \fC\fBKillingFunction::KILL_ALL\fP\fP)"

.PP
Definition at line \fB75\fP of file \fBPriorityMap\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
