.TH "lctm::EntropyModelResiduals" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lctm::EntropyModelResiduals
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEntropyModelResiduals\fP ()"
.br
.ti -1c
.RI "void \fBencode_high_count\fP (State state, unsigned symbol)"
.br
.ti -1c
.RI "void \fBencode_run\fP (int16_t residual, unsigned zeros)"
.br
.ti -1c
.RI "\fBEncodedChunk\fP \fBfinish\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB53\fP of file \fBEntropyEncoder\&.cpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "lctm::EntropyModelResiduals::EntropyModelResiduals ()\fC [inline]\fP"

.PP
Definition at line \fB58\fP of file \fBEntropyEncoder\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void lctm::EntropyModelResiduals::encode_high_count (State state, unsigned symbol)"

.PP
Definition at line \fB84\fP of file \fBEntropyEncoder\&.cpp\fP\&.
.SS "void lctm::EntropyModelResiduals::encode_run (int16_t residual, unsigned zeros)"

.PP
Definition at line \fB90\fP of file \fBEntropyEncoder\&.cpp\fP\&.
.SS "\fBEncodedChunk\fP lctm::EntropyModelResiduals::finish ()"

.PP
Definition at line \fB126\fP of file \fBEntropyEncoder\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
