.TH "lctm::EntropyEncoderResiduals" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lctm::EntropyEncoderResiduals
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <EntropyEncoder\&.hpp>\fP
.PP
Inherits \fBlctm::Component\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEntropyEncoderResiduals\fP ()"
.br
.ti -1c
.RI "\fBEncodedChunk\fP \fBprocess\fP (const \fBSurface\fP &surface)"
.br
.in -1c

Public Member Functions inherited from \fBlctm::Component\fP
.in +1c
.ti -1c
.RI "\fBComponent\fP (const std::string &\fBname\fP)"
.br
.ti -1c
.RI "virtual \fB~Component\fP ()=0"
.br
.ti -1c
.RI "virtual const std::string \fBname\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB61\fP of file \fBEntropyEncoder\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "lctm::EntropyEncoderResiduals::EntropyEncoderResiduals ()\fC [inline]\fP"

.PP
Definition at line \fB63\fP of file \fBEntropyEncoder\&.hpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBEncodedChunk\fP lctm::EntropyEncoderResiduals::process (const \fBSurface\fP & surface)"

.PP
Definition at line \fB148\fP of file \fBEntropyEncoder\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
