.TH "lctm::SequenceConfiguration" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lctm::SequenceConfiguration
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SignaledConfiguration\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBProfile\fP \fBprofile_idc\fP"
.br
.ti -1c
.RI "unsigned \fBlevel_idc\fP"
.br
.ti -1c
.RI "unsigned \fBsublevel_idc\fP"
.br
.ti -1c
.RI "bool \fBconformance_window\fP"
.br
.ti -1c
.RI "unsigned \fBextended_profile_idc\fP"
.br
.ti -1c
.RI "unsigned \fBextended_level_idc\fP"
.br
.ti -1c
.RI "unsigned \fBconf_win_left_offset\fP"
.br
.ti -1c
.RI "unsigned \fBconf_win_right_offset\fP"
.br
.ti -1c
.RI "unsigned \fBconf_win_top_offset\fP"
.br
.ti -1c
.RI "unsigned \fBconf_win_bottom_offset\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB70\fP of file \fBSignaledConfiguration\&.hpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "unsigned lctm::SequenceConfiguration::conf_win_bottom_offset"

.PP
Definition at line \fB80\fP of file \fBSignaledConfiguration\&.hpp\fP\&.
.SS "unsigned lctm::SequenceConfiguration::conf_win_left_offset"

.PP
Definition at line \fB77\fP of file \fBSignaledConfiguration\&.hpp\fP\&.
.SS "unsigned lctm::SequenceConfiguration::conf_win_right_offset"

.PP
Definition at line \fB78\fP of file \fBSignaledConfiguration\&.hpp\fP\&.
.SS "unsigned lctm::SequenceConfiguration::conf_win_top_offset"

.PP
Definition at line \fB79\fP of file \fBSignaledConfiguration\&.hpp\fP\&.
.SS "bool lctm::SequenceConfiguration::conformance_window"

.PP
Definition at line \fB74\fP of file \fBSignaledConfiguration\&.hpp\fP\&.
.SS "unsigned lctm::SequenceConfiguration::extended_level_idc"

.PP
Definition at line \fB76\fP of file \fBSignaledConfiguration\&.hpp\fP\&.
.SS "unsigned lctm::SequenceConfiguration::extended_profile_idc"

.PP
Definition at line \fB75\fP of file \fBSignaledConfiguration\&.hpp\fP\&.
.SS "unsigned lctm::SequenceConfiguration::level_idc"

.PP
Definition at line \fB72\fP of file \fBSignaledConfiguration\&.hpp\fP\&.
.SS "\fBProfile\fP lctm::SequenceConfiguration::profile_idc"

.PP
Definition at line \fB71\fP of file \fBSignaledConfiguration\&.hpp\fP\&.
.SS "unsigned lctm::SequenceConfiguration::sublevel_idc"

.PP
Definition at line \fB73\fP of file \fBSignaledConfiguration\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
