.TH "lctm::BufferCompare" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lctm::BufferCompare
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator()\fP (const PssPacket &l, const PssPacket &r)"
.br
.ti -1c
.RI "bool \fBoperator()\fP (const PssPacket &l, const PssPacket &r)"
.br
.ti -1c
.RI "bool \fBoperator()\fP (const PssPacket &l, const PssPacket &r)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB79\fP of file \fBBaseVideoDecoderCodecApi\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "bool lctm::BufferCompare::operator() (const PssPacket & l, const PssPacket & r)\fC [inline]\fP"

.PP
Definition at line \fB80\fP of file \fBBaseVideoDecoderCodecApi\&.cpp\fP\&.
.SS "bool lctm::BufferCompare::operator() (const PssPacket & l, const PssPacket & r)\fC [inline]\fP"

.PP
Definition at line \fB90\fP of file \fBBaseVideoDecoderHM\&.cpp\fP\&.
.SS "bool lctm::BufferCompare::operator() (const PssPacket & l, const PssPacket & r)\fC [inline]\fP"

.PP
Definition at line \fB90\fP of file \fBBaseVideoDecoderJM\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
