.TH "lctm::BitstreamPacker" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lctm::BitstreamPacker
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <BitstreamPacker\&.hpp>\fP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBScopedContextLabel\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBitstreamPacker\fP ()"
.br
.ti -1c
.RI "\fB~BitstreamPacker\fP ()"
.br
.ti -1c
.RI "void \fBu\fP (unsigned nbits, uint32_t value)"
.br
.RI "write 0\&.\&.32 bits into unsigned integer - with optional debug label "
.ti -1c
.RI "void \fBu\fP (unsigned nbits, uint32_t value, const char *label)"
.br
.ti -1c
.RI "void \fBbytes\fP (const \fBPacketView\fP &bytes)"
.br
.ti -1c
.RI "void \fBbytes\fP (const uint8_t *data, unsigned size)"
.br
.ti -1c
.RI "unsigned \fBbit_offset\fP () const"
.br
.ti -1c
.RI "unsigned \fBbyte_size\fP () const"
.br
.ti -1c
.RI "void \fBpush_context_label\fP (const std::string &s, bool dump=false)"
.br
.ti -1c
.RI "void \fBpop_context_label\fP ()"
.br
.ti -1c
.RI "unsigned \fBemit\fP (\fBPacketBuilder\fP &builder)"
.br
.ti -1c
.RI "\fBPacket\fP \fBfinish\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB58\fP of file \fBBitstreamPacker\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "lctm::BitstreamPacker::BitstreamPacker ()"

.PP
Definition at line \fB75\fP of file \fBBitstreamPacker\&.cpp\fP\&.
.SS "lctm::BitstreamPacker::~BitstreamPacker ()"

.PP
Definition at line \fB77\fP of file \fBBitstreamPacker\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "unsigned lctm::BitstreamPacker::bit_offset () const\fC [inline]\fP"

.PP
Definition at line \fB73\fP of file \fBBitstreamPacker\&.hpp\fP\&.
.SS "unsigned lctm::BitstreamPacker::byte_size () const\fC [inline]\fP"

.PP
Definition at line \fB76\fP of file \fBBitstreamPacker\&.hpp\fP\&.
.SS "void lctm::BitstreamPacker::bytes (const \fBPacketView\fP & bytes)"

.PP
Definition at line \fB160\fP of file \fBBitstreamPacker\&.cpp\fP\&.
.SS "void lctm::BitstreamPacker::bytes (const uint8_t * data, unsigned size)"

.PP
Definition at line \fB147\fP of file \fBBitstreamPacker\&.cpp\fP\&.
.SS "unsigned lctm::BitstreamPacker::emit (\fBPacketBuilder\fP & builder)"

.PP
Definition at line \fB81\fP of file \fBBitstreamPacker\&.cpp\fP\&.
.SS "\fBPacket\fP lctm::BitstreamPacker::finish ()"

.PP
Definition at line \fB98\fP of file \fBBitstreamPacker\&.cpp\fP\&.
.SS "void lctm::BitstreamPacker::pop_context_label ()"

.PP
Definition at line \fB167\fP of file \fBBitstreamPacker\&.cpp\fP\&.
.SS "void lctm::BitstreamPacker::push_context_label (const std::string & s, bool dump = \fCfalse\fP)"

.PP
Definition at line \fB162\fP of file \fBBitstreamPacker\&.cpp\fP\&.
.SS "void lctm::BitstreamPacker::u (unsigned nbits, uint32_t value)"

.PP
write 0\&.\&.32 bits into unsigned integer - with optional debug label 
.PP
Definition at line \fB105\fP of file \fBBitstreamPacker\&.cpp\fP\&.
.SS "void lctm::BitstreamPacker::u (unsigned nbits, uint32_t value, const char * label)"

.PP
Definition at line \fB131\fP of file \fBBitstreamPacker\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
