.TH "lctm::Node" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lctm::Node
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNode\fP ()"
.br
.ti -1c
.RI "\fBNode\fP (unsigned s, unsigned c)"
.br
.ti -1c
.RI "\fBNode\fP (\fBNode\fP *l, \fBNode\fP *r, unsigned node_number)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned \fBsymbol\fP = \fBHuffmanEncoder::MAX_SYMBOL\fP"
.br
.ti -1c
.RI "unsigned \fBcount\fP = 0"
.br
.ti -1c
.RI "unsigned \fBbits\fP = 0"
.br
.ti -1c
.RI "\fBNode\fP * \fBleft\fP = nullptr"
.br
.ti -1c
.RI "\fBNode\fP * \fBright\fP = nullptr"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB57\fP of file \fBHuffmanEncoder\&.cpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "lctm::Node::Node ()\fC [inline]\fP"

.PP
Definition at line \fB58\fP of file \fBHuffmanEncoder\&.cpp\fP\&.
.SS "lctm::Node::Node (unsigned s, unsigned c)\fC [inline]\fP"

.PP
Definition at line \fB59\fP of file \fBHuffmanEncoder\&.cpp\fP\&.
.SS "lctm::Node::Node (\fBNode\fP * l, \fBNode\fP * r, unsigned node_number)\fC [inline]\fP"

.PP
Definition at line \fB60\fP of file \fBHuffmanEncoder\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "unsigned lctm::Node::bits = 0"

.PP
Definition at line \fB65\fP of file \fBHuffmanEncoder\&.cpp\fP\&.
.SS "unsigned lctm::Node::count = 0"

.PP
Definition at line \fB64\fP of file \fBHuffmanEncoder\&.cpp\fP\&.
.SS "\fBNode\fP* lctm::Node::left = nullptr"

.PP
Definition at line \fB66\fP of file \fBHuffmanEncoder\&.cpp\fP\&.
.SS "\fBNode\fP* lctm::Node::right = nullptr"

.PP
Definition at line \fB67\fP of file \fBHuffmanEncoder\&.cpp\fP\&.
.SS "unsigned lctm::Node::symbol = \fBHuffmanEncoder::MAX_SYMBOL\fP"

.PP
Definition at line \fB63\fP of file \fBHuffmanEncoder\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
