.TH "lctm::PriorityConfiguration" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lctm::PriorityConfiguration
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <PriorityConfiguration\&.hpp>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBvalue_type\fP = std::pair< \fBEncodingMode\fP, \fBPriorityMode\fP >"
.br
.ti -1c
.RI "using \fBvalue_type_mb\fP = \fBPriorityMBType\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPriorityConfiguration\fP (const std::string &priority_mode, const std::string &priority_type_mb_sl_1, const std::string &priority_type_mb_sl_2)"
.br
.ti -1c
.RI "\fB~PriorityConfiguration\fP ()=default"
.br
.ti -1c
.RI "\fBEncodingMode\fP \fBencoding_mode\fP () const"
.br
.ti -1c
.RI "bool \fBuse_priority_map_sl_1\fP () const"
.br
.ti -1c
.RI "bool \fBuse_priority_map_sl_2\fP () const"
.br
.ti -1c
.RI "\fBPriorityMBType\fP \fBpriority_map_type_sl_1\fP () const"
.br
.ti -1c
.RI "\fBPriorityMBType\fP \fBpriority_map_type_sl_2\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB50\fP of file \fBPriorityConfiguration\&.hpp\fP\&.
.SH "Member Typedef Documentation"
.PP 
.SS "using \fBlctm::PriorityConfiguration::value_type\fP =  std::pair<\fBEncodingMode\fP, \fBPriorityMode\fP>"

.PP
Definition at line \fB52\fP of file \fBPriorityConfiguration\&.hpp\fP\&.
.SS "using \fBlctm::PriorityConfiguration::value_type_mb\fP =  \fBPriorityMBType\fP"

.PP
Definition at line \fB53\fP of file \fBPriorityConfiguration\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "lctm::PriorityConfiguration::PriorityConfiguration (const std::string & priority_mode, const std::string & priority_type_mb_sl_1, const std::string & priority_type_mb_sl_2)"

.PP
Definition at line \fB74\fP of file \fBPriorityConfiguration\&.cpp\fP\&.
.SS "lctm::PriorityConfiguration::~PriorityConfiguration ()\fC [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBEncodingMode\fP lctm::PriorityConfiguration::encoding_mode () const"

.PP
Definition at line \fB108\fP of file \fBPriorityConfiguration\&.cpp\fP\&.
.SS "\fBPriorityMBType\fP lctm::PriorityConfiguration::priority_map_type_sl_1 () const"

.PP
Definition at line \fB112\fP of file \fBPriorityConfiguration\&.cpp\fP\&.
.SS "\fBPriorityMBType\fP lctm::PriorityConfiguration::priority_map_type_sl_2 () const"

.PP
Definition at line \fB113\fP of file \fBPriorityConfiguration\&.cpp\fP\&.
.SS "bool lctm::PriorityConfiguration::use_priority_map_sl_1 () const"

.PP
Definition at line \fB110\fP of file \fBPriorityConfiguration\&.cpp\fP\&.
.SS "bool lctm::PriorityConfiguration::use_priority_map_sl_2 () const"

.PP
Definition at line \fB111\fP of file \fBPriorityConfiguration\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
