.TH "lctm" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lctm
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAdd\fP"
.br
.ti -1c
.RI "class \fBAddHighlight\fP"
.br
.ti -1c
.RI "struct \fBAdditionalInfo\fP"
.br
.ti -1c
.RI "class \fBApplyPreprocessedMap\fP"
.br
.ti -1c
.RI "class \fBApplyResidualMap\fP"
.br
.ti -1c
.RI "class \fBApplyTemporalMap\fP"
.br
.ti -1c
.RI "class \fBBaseVideoDecoder\fP"
.br
.ti -1c
.RI "class \fBBaseVideoDecoderCodecApi\fP"
.br
.ti -1c
.RI "class \fBBaseVideoDecoderExternal\fP"
.br
.ti -1c
.RI "class \fBBaseVideoDecoderExternalAVC\fP"
.br
.ti -1c
.RI "class \fBBaseVideoDecoderExternalEVC\fP"
.br
.ti -1c
.RI "class \fBBaseVideoDecoderExternalHEVC\fP"
.br
.ti -1c
.RI "class \fBBaseVideoDecoderExternalVVC\fP"
.br
.ti -1c
.RI "class \fBBaseVideoDecoderExternalYUV\fP"
.br
.ti -1c
.RI "class \fBBaseVideoDecoderHM\fP"
.br
.ti -1c
.RI "class \fBBaseVideoDecoderJM\fP"
.br
.ti -1c
.RI "class \fBBitstreamPacker\fP"
.br
.ti -1c
.RI "class \fBBitstreamUnpacker\fP"
.br
.ti -1c
.RI "class \fBBuffer\fP"
.br
.ti -1c
.RI "class \fBBufferAligned\fP"
.br
.ti -1c
.RI "struct \fBBufferCompare\fP"
.br
.ti -1c
.RI "class \fBBufferVector\fP"
.br
.ti -1c
.RI "class \fBCompareGE\fP"
.br
.ti -1c
.RI "class \fBCompareLE\fP"
.br
.ti -1c
.RI "class \fBCompareSkip\fP"
.br
.ti -1c
.RI "class \fBComponent\fP"
.br
.ti -1c
.RI "class \fBConform\fP"
.br
.ti -1c
.RI "struct \fBConformancePadding\fP"
.br
.ti -1c
.RI "class \fBConvertBitShift\fP"
.br
.ti -1c
.RI "class \fBConvertDumpS15toU10\fP"
.br
.ti -1c
.RI "class \fBConvertDumpU08toU10\fP"
.br
.ti -1c
.RI "class \fBConvertFromInternal\fP"
.br
.ti -1c
.RI "class \fBConvertFromU16\fP"
.br
.ti -1c
.RI "class \fBConvertFromU8\fP"
.br
.ti -1c
.RI "class \fBConvertLeftShiftFromU16\fP"
.br
.ti -1c
.RI "class \fBConvertLeftShiftFromU8\fP"
.br
.ti -1c
.RI "class \fBConvertRightShiftToU16\fP"
.br
.ti -1c
.RI "class \fBConvertRightShiftToU8\fP"
.br
.ti -1c
.RI "class \fBConvertToInternal\fP"
.br
.ti -1c
.RI "class \fBConvertToU16\fP"
.br
.ti -1c
.RI "class \fBConvertToU8\fP"
.br
.ti -1c
.RI "class \fBCropResiduals\fP"
.br
.ti -1c
.RI "class \fBCropTemporal\fP"
.br
.ti -1c
.RI "class \fBDeblocking\fP"
.br
.ti -1c
.RI "class \fBDecoder\fP"
.br
.ti -1c
.RI "class \fBDeserializer\fP"
.br
.ti -1c
.RI "class \fBDimensions\fP"
.br
.ti -1c
.RI "class \fBDithering\fP"
.br
.ti -1c
.RI "struct \fBDownsampleKernel\fP"
.br
.ti -1c
.RI "class \fBDownsampling\fP"
.br
.ti -1c
.RI "class \fBDownsampling_1D\fP"
.br
.ti -1c
.RI "class \fBEncodeBits\fP"
.br
.ti -1c
.RI "class \fBEncodeBits_DD\fP"
.br
.ti -1c
.RI "class \fBEncodeBits_DDS\fP"
.br
.ti -1c
.RI "struct \fBEncodedChunk\fP"
.br
.ti -1c
.RI "struct \fBEncodedLayer\fP"
.br
.ti -1c
.RI "class \fBEncoder\fP"
.br
.ti -1c
.RI "struct \fBEncoderConfiguration\fP"
.br
.ti -1c
.RI "class \fBEntropyDecoderFlags\fP"
.br
.ti -1c
.RI "class \fBEntropyDecoderResiduals\fP"
.br
.ti -1c
.RI "class \fBEntropyDecoderResidualsBase\fP"
.br
.ti -1c
.RI "class \fBEntropyDecoderResidualsTiled\fP"
.br
.ti -1c
.RI "class \fBEntropyDecoderSizes\fP"
.br
.ti -1c
.RI "class \fBEntropyDecoderTemporal\fP"
.br
.ti -1c
.RI "class \fBEntropyEncoderFlags\fP"
.br
.ti -1c
.RI "class \fBEntropyEncoderResiduals\fP"
.br
.ti -1c
.RI "class \fBEntropyEncoderResidualsTiled\fP"
.br
.ti -1c
.RI "class \fBEntropyEncoderSizes\fP"
.br
.ti -1c
.RI "class \fBEntropyEncoderTemporal\fP"
.br
.ti -1c
.RI "class \fBEntropyModelResiduals\fP"
.br
.ti -1c
.RI "class \fBEntropyModelRleFlag\fP"
.br
.ti -1c
.RI "class \fBEntropyModelSizes\fP"
.br
.ti -1c
.RI "class \fBExpandU16\fP"
.br
.ti -1c
.RI "class \fBExpandU8\fP"
.br
.ti -1c
.RI "class \fBFileEncoder\fP"
.br
.ti -1c
.RI "class \fBFileEncoderImpl\fP"
.br
.ti -1c
.RI "class \fBFileEncoderImplAVC\fP"
.br
.ti -1c
.RI "class \fBFileEncoderImplEVC\fP"
.br
.ti -1c
.RI "class \fBFileEncoderImplHEVC\fP"
.br
.ti -1c
.RI "class \fBFileEncoderImplVVC\fP"
.br
.ti -1c
.RI "class \fBFileEncoderImplX265\fP"
.br
.ti -1c
.RI "struct \fBGlobalConfiguration\fP"
.br
.ti -1c
.RI "struct \fBHuffmanCode\fP"
.br
.ti -1c
.RI "class \fBHuffmanDecoder\fP"
.br
.ti -1c
.RI "class \fBHuffmanEncoder\fP"
.br
.ti -1c
.RI "class \fBHuffmanEncoderBuilder\fP"
.br
.ti -1c
.RI "class \fBImage\fP"
.br
.ti -1c
.RI "struct \fBImageDescInfo\fP"
.br
.ti -1c
.RI "class \fBImageDescription\fP"
.br
.ti -1c
.RI "class \fBInverseQuantize\fP"
.br
.ti -1c
.RI "class \fBInverseQuantize_SWM\fP"
.br
.ti -1c
.RI "class \fBInverseTransformDD\fP"
.br
.ti -1c
.RI "class \fBInverseTransformDD_1D\fP"
.br
.ti -1c
.RI "class \fBInverseTransformDDS\fP"
.br
.ti -1c
.RI "class \fBInverseTransformDDS_1D\fP"
.br
.ti -1c
.RI "class \fBLayerEncodeFlags\fP"
.br
.ti -1c
.RI "struct \fBNode\fP"
.br
.ti -1c
.RI "class \fBPacket\fP"
.br
.ti -1c
.RI "class \fBPacketBuilder\fP"
.br
.ti -1c
.RI "class \fBPacketView\fP"
.br
.ti -1c
.RI "class \fBParameter\fP"
.br
.ti -1c
.RI "class \fBParameterBase\fP"
.br
.ti -1c
.RI "class \fBParameterRef\fP"
.br
.ti -1c
.RI "class \fBParameters\fP"
.br
.ti -1c
.RI "class \fBParametersBuilder\fP"
.br
.ti -1c
.RI "struct \fBPictureConfiguration\fP"
.br
.ti -1c
.RI "class \fBPredictedResidualAdjust\fP"
.br
.ti -1c
.RI "class \fBPredictedResidualAdjust_1D\fP"
.br
.ti -1c
.RI "class \fBPredictedResidualSum\fP"
.br
.ti -1c
.RI "class \fBPredictedResidualSum_1D\fP"
.br
.ti -1c
.RI "class \fBPriorityConfiguration\fP"
.br
.ti -1c
.RI "class \fBPriorityMap\fP"
.br
.ti -1c
.RI "class \fBPriorityMapVis\fP"
.br
.ti -1c
.RI "struct \fBPssPacket\fP"
.br
.ti -1c
.RI "class \fBQuantize\fP"
.br
.ti -1c
.RI "class \fBQuantize_SWM\fP"
.br
.ti -1c
.RI "class \fBRandom\fP"
.br
.ti -1c
.RI "class \fBrbsp_decoder\fP"
.br
.ti -1c
.RI "struct \fBRegisteredSEI\fP"
.br
.ti -1c
.RI "struct \fBSeiContentLightLevelInfo\fP"
.br
.ti -1c
.RI "struct \fBSeiMasteringDisplayColourVolume\fP"
.br
.ti -1c
.RI "struct \fBSeiUserDataRegisteredItutT35\fP"
.br
.ti -1c
.RI "struct \fBSeiUserDataUnrgistered\fP"
.br
.ti -1c
.RI "struct \fBSequenceConfiguration\fP"
.br
.ti -1c
.RI "class \fBSerializer\fP"
.br
.ti -1c
.RI "struct \fBSignaledConfiguration\fP"
.br
.ti -1c
.RI "class \fBStaticResiduals\fP"
.br
.ti -1c
.RI "class \fBSubtract\fP"
.br
.ti -1c
.RI "class \fBSurface\fP"
.br
.ti -1c
.RI "class \fBSurfaceBuilder\fP"
.br
.ti -1c
.RI "struct \fBSurfaceConfiguration\fP"
.br
.ti -1c
.RI "class \fBSurfaceView\fP"
.br
.ti -1c
.RI "class \fBSymbolSource\fP"
.br
.ti -1c
.RI "class \fBSymbolSourceConstant\fP"
.br
.ti -1c
.RI "class \fBSymbolSourceHuffman\fP"
.br
.ti -1c
.RI "class \fBSymbolSourceRaw\fP"
.br
.ti -1c
.RI "class \fBTemporalClear\fP"
.br
.ti -1c
.RI "class \fBTemporalCost_2x2\fP"
.br
.ti -1c
.RI "class \fBTemporalCost_4x4\fP"
.br
.ti -1c
.RI "class \fBTemporalCost_SAD\fP"
.br
.ti -1c
.RI "class \fBTemporalExtractMask\fP"
.br
.ti -1c
.RI "class \fBTemporalInsertMask\fP"
.br
.ti -1c
.RI "class \fBTemporalMask\fP"
.br
.ti -1c
.RI "class \fBTemporalSelect\fP"
.br
.ti -1c
.RI "class \fBTemporalTileIntraClear\fP"
.br
.ti -1c
.RI "class \fBTemporalTileIntraSignal\fP"
.br
.ti -1c
.RI "class \fBTemporalTileMap\fP"
.br
.ti -1c
.RI "class \fBTemporalUpdate\fP"
.br
.ti -1c
.RI "class \fBTransformDD\fP"
.br
.ti -1c
.RI "class \fBTransformDD_1D\fP"
.br
.ti -1c
.RI "class \fBTransformDDS\fP"
.br
.ti -1c
.RI "class \fBTransformDDS_1D\fP"
.br
.ti -1c
.RI "struct \fBUniquePtrFileClose\fP"
.br
.ti -1c
.RI "struct \fBUnregisteredSEI\fP"
.br
.ti -1c
.RI "class \fBUpsampling\fP"
.br
.ti -1c
.RI "class \fBUpsampling_1D\fP"
.br
.ti -1c
.RI "class \fBUpsamplingDPI\fP"
.br
.ti -1c
.RI "class \fBUpsamplingDPI_1D\fP"
.br
.ti -1c
.RI "class \fBUserDataClear\fP"
.br
.ti -1c
.RI "class \fBUserDataInsert\fP"
.br
.ti -1c
.RI "struct \fBVuiMessage\fP"
.br
.ti -1c
.RI "class \fBYUVReader\fP"
.br
.ti -1c
.RI "class \fBYUVWriter\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef int32_t \fBUpsampleKernel\fP[4]"
.br
.ti -1c
.RI "typedef std::unique_ptr< FILE, \fBUniquePtrFileClose\fP > \fBUniquePtrFile\fP"
.br
.ti -1c
.RI "typedef uint32_t(* \fBcodec_api_version_fn_t\fP) ()"
.br
.ti -1c
.RI "typedef uint32_t(* \fBcodec_api_query_fn_t\fP) (int num, const char *buffer, uint32_t buffer_size)"
.br
.ti -1c
.RI "typedef \fBCodec\fP *(* \fBcodec_api_create_fn_t\fP) (const char *\fBname\fP, \fBCodecOperation\fP operation, const char *json_configuration)"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum { \fBMAX_NUM_PLANES\fP = 3 }"
.br
.ti -1c
.RI "enum { \fBMAX_NUM_LOQS\fP = 2 }"
.br
.ti -1c
.RI "enum { \fBMAX_NUM_LAYERS\fP = 17 }"
.br
.ti -1c
.RI "enum { \fBMIN_STEP_WIDTH\fP = 1 }"
.br
.ti -1c
.RI "enum { \fBMAX_STEP_WIDTH\fP = 32767 }"
.br
.ti -1c
.RI "enum { \fBMIN_BASE_QP\fP = 0 }"
.br
.ti -1c
.RI "enum { \fBMAX_BASE_QP\fP = 50 }"
.br
.ti -1c
.RI "enum : unsigned long { \fBMAX_OUTPUT_RATE_LEVEL_1\fP = 29410000, \fBMAX_OUTPUT_RATE_LEVEL_2\fP = 124560000, \fBMAX_OUTPUT_RATE_LEVEL_3\fP = 527650000, \fBMAX_OUTPUT_RATE_LEVEL_4\fP = 2235160000 }"
.br
.ti -1c
.RI "enum { \fBLOQ_LEVEL_1\fP = 0, \fBLOQ_LEVEL_2\fP = 1 }"
.br
.ti -1c
.RI "enum \fBEncodingMode\fP { \fBENCODE_ALL\fP = 0, \fBAx\fP = 1, \fBAA\fP = 2, \fBNA\fP = 3, \fBENCODE_NONE\fP = 4 }"
.br
.ti -1c
.RI "enum \fBPriorityMode\fP { \fBPM_ALL_OFF\fP = 0, \fBPM_ALL_ON\fP = 1, \fBPM_SL1_ON\fP = 2, \fBPM_SL2_ON\fP = 3, \fBPM_SL1_OFF\fP = 4, \fBPM_SL2_OFF\fP = 5 }"
.br
.ti -1c
.RI "enum \fBPriorityMBType\fP { \fBSmooth\fP = 0, \fBPlain\fP = 1, \fBCoarse\fP = 2, \fBEdge\fP = 3, \fBSmoothAndPlain\fP = 4, \fBCoarseAndPlain\fP = 5 }"
.br
.ti -1c
.RI "enum \fBKillingFunction\fP { \fBKILL_ALL\fP = 0, \fBKEEP_ALL\fP = 1, \fBTHRESHOLD_CUTOFF\fP = 2 }"
.br
.ti -1c
.RI "enum \fBTileType\fP { \fBTileTypePlain\fP = 0, \fBTileTypeEdge\fP, \fBTileTypeSmooth\fP, \fBTileTypeCoarse\fP }"
.br
.ti -1c
.RI "enum \fBUpsample\fP { \fBUpsample_Nearest\fP, \fBUpsample_Linear\fP, \fBUpsample_Cubic\fP, \fBUpsample_ModifiedCubic\fP, \fBUpsample_AdaptiveCubic\fP }"
.br
.ti -1c
.RI "enum \fBDownsample\fP { \fBDownsample_Area\fP, \fBDownsample_Lanczos\fP, \fBDownsample_Lanczos3\fP }"
.br
.ti -1c
.RI "enum \fBScalingMode\fP { \fBScalingMode_None\fP, \fBScalingMode_1D\fP, \fBScalingMode_2D\fP }"
.br
.ti -1c
.RI "enum \fBUserDataMode\fP { \fBUserData_None\fP, \fBUserData_2bits\fP, \fBUserData_6bits\fP }"
.br
.ti -1c
.RI "enum \fBUserDataMethod\fP { \fBUserDataMethod_Zeros\fP, \fBUserDataMethod_Ones\fP, \fBUserDataMethod_Random\fP, \fBUserDataMethod_FixedRandom\fP }"
.br
.ti -1c
.RI "enum \fBTileDimensions\fP { \fBTileDimensions_None\fP, \fBTileDimensions_512x256\fP, \fBTileDimensions_1024x512\fP, \fBTileDimensions_Custom\fP }"
.br
.ti -1c
.RI "enum \fBQuantMatrix\fP { \fBQuantMatrix_BothPrevious\fP, \fBQuantMatrix_BothDefault\fP, \fBQuantMatrix_SameAndCustom\fP, \fBQuantMatrix_Level2CustomLevel1Default\fP, \fBQuantMatrix_Level2DefaultLevel1Custom\fP, \fBQuantMatrix_DifferentAndCustom\fP }"
.br
.ti -1c
.RI "enum \fBCompressionType\fP { \fBCompressionType_None\fP, \fBCompressionType_Prefix\fP, \fBCompressionType_Prefix_OnDiff\fP }"
.br
.ti -1c
.RI "enum \fBDitheringType\fP { \fBDithering_None\fP, \fBDithering_Uniform\fP, \fBDithering_UniformFixed\fP }"
.br
.ti -1c
.RI "enum \fBDequantOffset\fP { \fBDequantOffset_Default\fP, \fBDequantOffset_ConstOffset\fP }"
.br
.ti -1c
.RI "enum \fBTransformType\fP { \fBTransformType_DD\fP, \fBTransformType_DDS\fP }"
.br
.ti -1c
.RI "enum \fBPictureType\fP { \fBPictureType_Frame\fP, \fBPictureType_Field\fP }"
.br
.ti -1c
.RI "enum \fBFieldType\fP { \fBFieldType_Top\fP, \fBFieldType_Bottom\fP }"
.br
.ti -1c
.RI "enum \fBCodingType\fP { \fBCodingType_IDR\fP, \fBCodingType_NonIDR\fP }"
.br
.ti -1c
.RI "enum \fBNalUnitType\fP { \fBLCEVC_NON_IDR\fP = 28, \fBLCEVC_IDR\fP = 29, \fBLCEVC_RSV\fP = 30 }"
.br
.ti -1c
.RI "enum \fBProfile\fP { \fBProfile_Main\fP, \fBProfile_Main444\fP, \fBProfile_Auto\fP }"
.br
.ti -1c
.RI "enum \fBBaseCoding\fP { \fBBaseCoding_Unknown\fP, \fBBaseCoding_AVC\fP, \fBBaseCoding_HEVC\fP, \fBBaseCoding_VVC\fP, \fBBaseCoding_EVC\fP, \fBBaseCoding_X265\fP, \fBBaseCoding_YUV\fP }"
.br
.ti -1c
.RI "enum \fBEncapsulation\fP { \fBEncapsulation_None\fP, \fBEncapsulation_SEI_Unregistered\fP, \fBEncapsulation_SEI_Registered\fP, \fBEncapsulation_NAL\fP }"
.br
.ti -1c
.RI "enum \fBBaseFrameType\fP { \fBBaseFrame_IDR\fP, \fBBaseFrame_Intra\fP, \fBBaseFrame_Inter\fP, \fBBaseFrame_Pred\fP, \fBBaseFrame_Bidi\fP }"
.br
.ti -1c
.RI "enum \fBTemporal_SWM\fP { \fBSWM_Disabled\fP = 0, \fBSWM_Active\fP = 1, \fBSWM_Dependent\fP = 2 }"
.br
.ti -1c
.RI "enum \fBSyntaxBlocks\fP { \fBSyntaxBlock_Sequence\fP = 1, \fBSyntaxBlock_Global\fP = 2, \fBSyntaxBlock_Picture\fP = 4, \fBSyntaxBlock_EncodedData\fP = 8, \fBSyntaxBlock_EncodedData_Tiled\fP = 16, \fBSyntaxBlock_Additional_Info\fP = 32, \fBSyntaxBlock_Filler\fP = 64 }"
.br
.ti -1c
.RI "enum \fBParameterConfig\fP { \fBParameterConfig_Default\fP, \fBParameterConfig_Conformance\fP }"
.br
.ti -1c
.RI "enum \fBResidualLabel\fP { \fBRESIDUAL_LIVE\fP = 128, \fBRESIDUAL_KILL\fP = 192 }"
.br
.ti -1c
.RI "enum \fBTemporalType\fP { \fBTEMPORAL_PRED\fP = 128, \fBTEMPORAL_INTR\fP = 192 }"
.br
.ti -1c
.RI "enum \fBImageFormat\fP { \fBIMAGE_FORMAT_NONE\fP = 0, \fBIMAGE_FORMAT_YUV420P8\fP = 1, \fBIMAGE_FORMAT_YUV422P8\fP = 2, \fBIMAGE_FORMAT_YUV444P8\fP = 3, \fBIMAGE_FORMAT_Y8\fP = 4, \fBIMAGE_FORMAT_YUV420P10\fP = 5, \fBIMAGE_FORMAT_YUV422P10\fP = 6, \fBIMAGE_FORMAT_YUV444P10\fP = 7, \fBIMAGE_FORMAT_Y10\fP = 8, \fBIMAGE_FORMAT_YUV420P12\fP = 9, \fBIMAGE_FORMAT_YUV422P12\fP = 10, \fBIMAGE_FORMAT_YUV444P12\fP = 11, \fBIMAGE_FORMAT_Y12\fP = 12, \fBIMAGE_FORMAT_YUV420P14\fP = 13, \fBIMAGE_FORMAT_YUV422P14\fP = 14, \fBIMAGE_FORMAT_YUV444P14\fP = 15, \fBIMAGE_FORMAT_Y14\fP = 16, \fBIMAGE_FORMAT_YUV420P16\fP = 17, \fBIMAGE_FORMAT_YUV422P16\fP = 18, \fBIMAGE_FORMAT_YUV444P16\fP = 19, \fBIMAGE_FORMAT_Y16\fP = 20, \fB_IMAGE_FORMAT_MAX\fP }"
.br
.ti -1c
.RI "enum \fBColourspace\fP { \fBColourspace_Y\fP = 0, \fBColourspace_YUV420\fP = 1, \fBColourspace_YUV422\fP = 2, \fBColourspace_YUV444\fP = 3 }"
.br
.ti -1c
.RI "enum \fBBitdepth\fP { \fBBitdepth_8\fP = 8, \fBBitdepth_10\fP = 10, \fBBitdepth_12\fP = 12, \fBBitdepth_14\fP = 14 }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::unique_ptr< \fBBaseVideoDecoder\fP > \fBCreateBaseVideoDecoder\fP (\fBBaseVideoDecoder::Output\fP &output, \fBBaseCoding\fP base, \fBEncapsulation\fP encapulation, bool external, const std::string &prepared_yuv_file, bool keep_base)"
.br
.ti -1c
.RI "std::unique_ptr< \fBBaseVideoDecoder\fP > \fBCreateBaseVideoDecoderCodecApi\fP (\fBBaseVideoDecoder::Output\fP &output, \fBEncapsulation\fP encapsulation, \fBBaseCoding\fP base_coding, const std::string &\fBname\fP, const std::string &selection_options, const std::string &create_options)"
.br
.ti -1c
.RI "\fBImage\fP \fBExpandImage\fP (const \fBImage\fP &src, const \fBImageDescription\fP &description)"
.br
.ti -1c
.RI "int32_t \fBfind_quant_matrix_coeff\fP (const \fBPictureConfiguration\fP &picture_configuration, unsigned num_layers, bool horizontal_only, unsigned loq, unsigned layer, bool is_idr, int32_t previous)"
.br
.ti -1c
.RI "int32_t \fBfind_dirq_step_width\fP (int32_t orig_step_width, int32_t quant_matrix_coeff)"
.br
.ti -1c
.RI "int32_t \fBfind_invq_offset\fP (const \fBPictureConfiguration\fP &picture_configuration, int32_t orig_step_width, int32_t dirq_step_width)"
.br
.ti -1c
.RI "int32_t \fBfind_invq_step_width\fP (const \fBPictureConfiguration\fP &picture_configuration, int32_t dirq_step_width, int32_t invq_offset)"
.br
.ti -1c
.RI "int32_t \fBfind_layer_deadzone\fP (int32_t orig_step_width, int32_t dirq_step_width)"
.br
.ti -1c
.RI "int32_t \fBfind_invq_applied_offset\fP (const \fBPictureConfiguration\fP &picture_configuration, int32_t invq_offset, int32_t layer_deadzone)"
.br
.ti -1c
.RI "bool \fBprobe_es_file\fP (const std::string &\fBname\fP, \fBBaseCoding\fP coding, unsigned &width, unsigned &height, unsigned &bit_depth, unsigned &chroma_format_idc)"
.br
.ti -1c
.RI "size_t \fBscan_enhancement\fP (uint8_t *data, size_t data_size, \fBEncapsulation\fP encapsulation, \fBBaseCoding\fP coding, uint64_t pts, bool is_idr, std::function< void(const \fBPacket\fP &pkt, const bool \fBis_lcevc_idr\fP)> callback)"
.br
.ti -1c
.RI "\fBImage\fP \fBUpsampleImage\fP (const \fBImage\fP &src, \fBUpsample\fP upsample, const unsigned upsampling_coefficients[4], \fBScalingMode\fP scaling_mode)"
.br
.ti -1c
.RI "unique_ptr< \fBBaseVideoDecoder\fP > \fBCreateBaseVideoDecoderHM\fP (\fBBaseVideoDecoder::Output\fP &output, \fBEncapsulation\fP encapsulation)"
.br
.ti -1c
.RI "unique_ptr< \fBBaseVideoDecoder\fP > \fBCreateBaseVideoDecoderJM\fP (\fBBaseVideoDecoder::Output\fP &output, \fBEncapsulation\fP encapsulation)"
.br
.ti -1c
.RI "bool \fBprobe_es_file\fP (const string &\fBname\fP, \fBBaseCoding\fP coding, unsigned &width, unsigned &height, unsigned &bit_depth, unsigned &chroma_format_idc)"
.br
.ti -1c
.RI "\fBImage\fP \fBDownsampleImage\fP (const \fBImage\fP &src, \fBDownsample\fP downsample_luma, \fBDownsample\fP downsample_chroma, \fBScalingMode\fP scaling_mode, unsigned dst_bit_depth=0)"
.br
.ti -1c
.RI "std::unique_ptr< \fBFileEncoder\fP > \fBCreateFileEncoder\fP (\fBBaseCoding\fP base_encoder, const \fBImageDescription\fP &image_description, unsigned fps, const \fBParameters\fP &parameters)"
.br
.ti -1c
.RI "\fBParameters\fP \fBparameter_defaults_global\fP (const \fBParameters\fP &p)"
.br
.ti -1c
.RI "\fBParameters\fP \fBparameter_defaults_picture\fP (const \fBParameters\fP &p, std::vector< std::unique_ptr< \fBImage\fP > > &src_image, unsigned base_qp)"
.br
.ti -1c
.RI "template<typename T , typename\&.\&.\&. Args> std::unique_ptr< T > \fBmake_unique\fP (Args &&\&.\&.\&.args)"
.br
.ti -1c
.RI "template<typename A , typename B , size_t N> B \fBpiecewise_linear\fP (const std::array< A, N > &a, const std::array< B, N > &b, A v)"
.br
.ti -1c
.RI "std::istream & \fBoperator>>\fP (std::istream &in, \fBUpsample\fP &v)"
.br
.ti -1c
.RI "std::istream & \fBoperator>>\fP (std::istream &in, \fBDownsample\fP &v)"
.br
.ti -1c
.RI "std::istream & \fBoperator>>\fP (std::istream &in, \fBScalingMode\fP &v)"
.br
.ti -1c
.RI "std::istream & \fBoperator>>\fP (std::istream &in, \fBDitheringType\fP &v)"
.br
.ti -1c
.RI "std::istream & \fBoperator>>\fP (std::istream &in, \fBDequantOffset\fP &v)"
.br
.ti -1c
.RI "std::istream & \fBoperator>>\fP (std::istream &in, \fBTransformType\fP &v)"
.br
.ti -1c
.RI "std::istream & \fBoperator>>\fP (std::istream &in, \fBBaseCoding\fP &v)"
.br
.ti -1c
.RI "std::istream & \fBoperator>>\fP (std::istream &in, \fBEncapsulation\fP &v)"
.br
.ti -1c
.RI "std::istream & \fBoperator>>\fP (std::istream &in, \fBQuantMatrix\fP &v)"
.br
.ti -1c
.RI "std::istream & \fBoperator>>\fP (std::istream &in, \fBCompressionType\fP &v)"
.br
.ti -1c
.RI "std::istream & \fBoperator>>\fP (std::istream &in, \fBUserDataMode\fP &v)"
.br
.ti -1c
.RI "std::istream & \fBoperator>>\fP (std::istream &in, \fBUserDataMethod\fP &v)"
.br
.ti -1c
.RI "std::istream & \fBoperator>>\fP (std::istream &in, \fBPictureType\fP &v)"
.br
.ti -1c
.RI "std::istream & \fBoperator>>\fP (std::istream &in, \fBProfile\fP &v)"
.br
.ti -1c
.RI "std::istream & \fBoperator>>\fP (std::istream &in, \fBParameterConfig\fP &v)"
.br
.ti -1c
.RI "std::unique_ptr< \fBBuffer\fP > \fBCreateBufferVector\fP (const uint8_t *data, unsigned size)"
.br
.ti -1c
.RI "std::unique_ptr< \fBBuffer\fP > \fBCreateBufferVector\fP (unsigned size)"
.br
.ti -1c
.RI "std::unique_ptr< \fBBuffer\fP > \fBCreateBufferAligned\fP (const uint8_t *data, unsigned size)"
.br
.ti -1c
.RI "std::unique_ptr< \fBBuffer\fP > \fBCreateBufferAligned\fP (unsigned size)"
.br
.ti -1c
.RI "\fBCodec\fP * \fBCodecCreate\fP (const std::string &\fBname\fP, \fBCodecOperation\fP operation, const std::string &json_codec_selection_options)"
.br
.ti -1c
.RI "void \fBCodecRelease\fP (\fBCodec\fP *codec)"
.br
.ti -1c
.RI "std::string \fBCodecErrorToString\fP (\fBCodec\fP *codec, \fBCodecError\fP error)"
.br
.ti -1c
.RI "std::string \fBformat\fP (const char *fmt,\&.\&.\&.)"
.br
.ti -1c
.RI "std::string \fBhex_dump\fP (const uint8_t *data, uint64_t size, unsigned int offset)"
.br
.ti -1c
.RI "std::string \fBjoin\fP (const std::vector< std::string > &list, const std::string &seperator, bool include_trailing=false)"
.br
.ti -1c
.RI "void \fB_check_failed\fP (const char *file, int line, const char *func, const std::string &message)"
.br
.ti -1c
.RI "template<typename T > T \fB_check\fP (T c, const char *file, int line, const char *func, const char *expr)"
.br
.ti -1c
.RI "void \fB_log\fP (const char *file, int line, const char *func, const std::string &message)"
.br
.ti -1c
.RI "void \fB_log_report\fP (const std::string &message)"
.br
.ti -1c
.RI "void \fB_raise\fP (const char *file, int line, const char *func, const std::string &message)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const class \fBImageDescription\fP &lhs, const class \fBImageDescription\fP &rhs)"
.br
.ti -1c
.RI "std::istream & \fBoperator>>\fP (std::istream &in, \fBImageFormat\fP &v)"
.br
.ti -1c
.RI "std::istream & \fBoperator>>\fP (std::istream &in, \fBColourspace\fP &v)"
.br
.ti -1c
.RI "std::string \fBget_program\fP ()"
.br
.ti -1c
.RI "std::string \fBget_program_directory\fP (const std::string &suffix)"
.br
.ti -1c
.RI "size_t \fBfile_size\fP (int fd)"
.br
.ti -1c
.RI "size_t \fBfile_size\fP (const std::string &\fBname\fP)"
.br
.ti -1c
.RI "std::string \fBread_file\fP (const std::string &\fBname\fP)"
.br
.ti -1c
.RI "bool \fBwrite_file\fP (const std::string &\fBname\fP, const std::string &contents)"
.br
.ti -1c
.RI "std::string \fBfile_extension\fP (const std::string &filename)"
.br
.ti -1c
.RI "std::string \fBlowercase\fP (const char *s)"
.br
.ti -1c
.RI "std::string \fBlowercase\fP (const std::string &s)"
.br
.ti -1c
.RI "unsigned \fBsplit\fP (std::vector< std::string > &output, const std::string &src, const char *seperators)"
.br
.ti -1c
.RI "template<typename T > T \fBclamp\fP (T val, T l, T h)"
.br
.ti -1c
.RI "uint64_t \fBcrc64\fP (uint64_t crc, const unsigned char *s, uint64_t l)"
.br
.ti -1c
.RI "uint64_t \fBsystem_timestamp\fP ()"
.br
.ti -1c
.RI "std::string \fBmake_temporary_filename\fP (const std::string &suffix)"
.br
.ti -1c
.RI "template<typename T > T \fBextract\fP (const std::string &s)"
.br
.ti -1c
.RI "template<typename T > T \fBextract\fP (const std::string &s, T dflt)"
.br
.ti -1c
.RI "std::unique_ptr< \fBYUVReader\fP > \fBCreateYUVReader\fP (const std::string &\fBname\fP)"
.br
.ti -1c
.RI "std::unique_ptr< \fBYUVReader\fP > \fBCreateYUVReader\fP (const std::string &\fBname\fP, unsigned rate)"
.br
.ti -1c
.RI "std::unique_ptr< \fBYUVReader\fP > \fBCreateYUVReader\fP (const std::string &\fBname\fP, const \fBImageDescription\fP &image_description, unsigned rate)"
.br
.ti -1c
.RI "std::unique_ptr< \fBYUVWriter\fP > \fBCreateYUVWriter\fP (const std::string &\fBname\fP)"
.br
.ti -1c
.RI "std::unique_ptr< \fBYUVWriter\fP > \fBCreateYUVWriter\fP (const std::string &\fBname\fP, const \fBImageDescription\fP &image_description, bool decorate)"
.br
.ti -1c
.RI "\fBCodec\fP * \fBCodecCreate\fP (const string &\fBname\fP, \fBCodecOperation\fP operation, const string &create_options)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBImageDescription\fP &lhs, const \fBImageDescription\fP &rhs)"
.br
.ti -1c
.RI "unique_ptr< \fBYUVReader\fP > \fBCreateYUVReader\fP (const string &\fBname\fP)"
.br
.ti -1c
.RI "unique_ptr< \fBYUVReader\fP > \fBCreateYUVReader\fP (const string &\fBname\fP, unsigned rate)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const unsigned \fBresolution_table\fP [51][2]"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef \fBCodec\fP *(* lctm::codec_api_create_fn_t) (const char *\fBname\fP, \fBCodecOperation\fP operation, const char *json_configuration)"

.PP
Definition at line \fB54\fP of file \fBCodec\&.cpp\fP\&.
.SS "typedef uint32_t(* lctm::codec_api_query_fn_t) (int num, const char *buffer, uint32_t buffer_size)"

.PP
Definition at line \fB53\fP of file \fBCodec\&.cpp\fP\&.
.SS "typedef uint32_t(* lctm::codec_api_version_fn_t) ()"

.PP
Definition at line \fB52\fP of file \fBCodec\&.cpp\fP\&.
.SS "typedef std::unique_ptr<FILE, \fBUniquePtrFileClose\fP> \fBlctm::UniquePtrFile\fP"

.PP
Definition at line \fB97\fP of file \fBMisc\&.hpp\fP\&.
.SS "typedef int32_t lctm::UpsampleKernel[4]"

.PP
Definition at line \fB50\fP of file \fBUpsampling\&.cpp\fP\&.
.SH "Enumeration Type Documentation"
.PP 
.SS "anonymous enum"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIMAX_BASE_QP \fP\fP
.PP
Definition at line \fB54\fP of file \fBSignaledConfiguration\&.hpp\fP\&.
.SS "anonymous enum : unsigned long"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIMAX_OUTPUT_RATE_LEVEL_1 \fP\fP
.TP
\fB\fIMAX_OUTPUT_RATE_LEVEL_2 \fP\fP
.TP
\fB\fIMAX_OUTPUT_RATE_LEVEL_3 \fP\fP
.TP
\fB\fIMAX_OUTPUT_RATE_LEVEL_4 \fP\fP
.PP
Definition at line \fB56\fP of file \fBSignaledConfiguration\&.hpp\fP\&.
.SS "anonymous enum"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fILOQ_LEVEL_1 \fP\fP
.TP
\fB\fILOQ_LEVEL_2 \fP\fP
.PP
Definition at line \fB63\fP of file \fBSignaledConfiguration\&.hpp\fP\&.
.SS "anonymous enum"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIMAX_NUM_PLANES \fP\fP
.PP
Definition at line \fB48\fP of file \fBSignaledConfiguration\&.hpp\fP\&.
.SS "anonymous enum"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIMAX_NUM_LOQS \fP\fP
.PP
Definition at line \fB49\fP of file \fBSignaledConfiguration\&.hpp\fP\&.
.SS "anonymous enum"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIMAX_NUM_LAYERS \fP\fP
.PP
Definition at line \fB50\fP of file \fBSignaledConfiguration\&.hpp\fP\&.
.SS "anonymous enum"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIMIN_STEP_WIDTH \fP\fP
.PP
Definition at line \fB51\fP of file \fBSignaledConfiguration\&.hpp\fP\&.
.SS "anonymous enum"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIMAX_STEP_WIDTH \fP\fP
.PP
Definition at line \fB52\fP of file \fBSignaledConfiguration\&.hpp\fP\&.
.SS "anonymous enum"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIMIN_BASE_QP \fP\fP
.PP
Definition at line \fB53\fP of file \fBSignaledConfiguration\&.hpp\fP\&.
.SS "enum \fBlctm::BaseCoding\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIBaseCoding_Unknown \fP\fP
.TP
\fB\fIBaseCoding_AVC \fP\fP
.TP
\fB\fIBaseCoding_HEVC \fP\fP
.TP
\fB\fIBaseCoding_VVC \fP\fP
.TP
\fB\fIBaseCoding_EVC \fP\fP
.TP
\fB\fIBaseCoding_X265 \fP\fP
.TP
\fB\fIBaseCoding_YUV \fP\fP
.PP
Definition at line \fB128\fP of file \fBTypes\&.hpp\fP\&.
.SS "enum \fBlctm::BaseFrameType\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIBaseFrame_IDR \fP\fP
.TP
\fB\fIBaseFrame_Intra \fP\fP
.TP
\fB\fIBaseFrame_Inter \fP\fP
.TP
\fB\fIBaseFrame_Pred \fP\fP
.TP
\fB\fIBaseFrame_Bidi \fP\fP
.PP
Definition at line \fB145\fP of file \fBTypes\&.hpp\fP\&.
.SS "enum \fBlctm::Bitdepth\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIBitdepth_8 \fP\fP
.TP
\fB\fIBitdepth_10 \fP\fP
.TP
\fB\fIBitdepth_12 \fP\fP
.TP
\fB\fIBitdepth_14 \fP\fP
.PP
Definition at line \fB91\fP of file \fBImage\&.hpp\fP\&.
.SS "enum \fBlctm::CodingType\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fICodingType_IDR \fP\fP
.TP
\fB\fICodingType_NonIDR \fP\fP
.PP
Definition at line \fB117\fP of file \fBTypes\&.hpp\fP\&.
.SS "enum \fBlctm::Colourspace\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIColourspace_Y \fP\fP
.TP
\fB\fIColourspace_YUV420 \fP\fP
.TP
\fB\fIColourspace_YUV422 \fP\fP
.TP
\fB\fIColourspace_YUV444 \fP\fP
.PP
Definition at line \fB84\fP of file \fBImage\&.hpp\fP\&.
.SS "enum \fBlctm::CompressionType\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fICompressionType_None \fP\fP
.TP
\fB\fICompressionType_Prefix \fP\fP
.TP
\fB\fICompressionType_Prefix_OnDiff \fP\fP
.PP
Definition at line \fB94\fP of file \fBTypes\&.hpp\fP\&.
.SS "enum \fBlctm::DequantOffset\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIDequantOffset_Default \fP\fP
.TP
\fB\fIDequantOffset_ConstOffset \fP\fP
.PP
Definition at line \fB106\fP of file \fBTypes\&.hpp\fP\&.
.SS "enum \fBlctm::DitheringType\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIDithering_None \fP\fP
.TP
\fB\fIDithering_Uniform \fP\fP
.TP
\fB\fIDithering_UniformFixed \fP\fP
.PP
Definition at line \fB100\fP of file \fBTypes\&.hpp\fP\&.
.SS "enum \fBlctm::Downsample\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIDownsample_Area \fP\fP
.TP
\fB\fIDownsample_Lanczos \fP\fP
.TP
\fB\fIDownsample_Lanczos3 \fP\fP
.PP
Definition at line \fB53\fP of file \fBTypes\&.hpp\fP\&.
.SS "enum \fBlctm::Encapsulation\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIEncapsulation_None \fP\fP
.TP
\fB\fIEncapsulation_SEI_Unregistered \fP\fP
.TP
\fB\fIEncapsulation_SEI_Registered \fP\fP
.TP
\fB\fIEncapsulation_NAL \fP\fP
.PP
Definition at line \fB138\fP of file \fBTypes\&.hpp\fP\&.
.SS "enum \fBlctm::EncodingMode\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIENCODE_ALL \fP\fP
.TP
\fB\fIAx \fP\fP
.TP
\fB\fIAA \fP\fP
.TP
\fB\fINA \fP\fP
.TP
\fB\fIENCODE_NONE \fP\fP
.PP
Definition at line \fB48\fP of file \fBLayerEncodeFlags\&.hpp\fP\&.
.SS "enum \fBlctm::FieldType\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIFieldType_Top \fP\fP
.TP
\fB\fIFieldType_Bottom \fP\fP
.PP
Definition at line \fB115\fP of file \fBTypes\&.hpp\fP\&.
.SS "enum \fBlctm::ImageFormat\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIIMAGE_FORMAT_NONE \fP\fP
.TP
\fB\fIIMAGE_FORMAT_YUV420P8 \fP\fP
.TP
\fB\fIIMAGE_FORMAT_YUV422P8 \fP\fP
.TP
\fB\fIIMAGE_FORMAT_YUV444P8 \fP\fP
.TP
\fB\fIIMAGE_FORMAT_Y8 \fP\fP
.TP
\fB\fIIMAGE_FORMAT_YUV420P10 \fP\fP
.TP
\fB\fIIMAGE_FORMAT_YUV422P10 \fP\fP
.TP
\fB\fIIMAGE_FORMAT_YUV444P10 \fP\fP
.TP
\fB\fIIMAGE_FORMAT_Y10 \fP\fP
.TP
\fB\fIIMAGE_FORMAT_YUV420P12 \fP\fP
.TP
\fB\fIIMAGE_FORMAT_YUV422P12 \fP\fP
.TP
\fB\fIIMAGE_FORMAT_YUV444P12 \fP\fP
.TP
\fB\fIIMAGE_FORMAT_Y12 \fP\fP
.TP
\fB\fIIMAGE_FORMAT_YUV420P14 \fP\fP
.TP
\fB\fIIMAGE_FORMAT_YUV422P14 \fP\fP
.TP
\fB\fIIMAGE_FORMAT_YUV444P14 \fP\fP
.TP
\fB\fIIMAGE_FORMAT_Y14 \fP\fP
.TP
\fB\fIIMAGE_FORMAT_YUV420P16 \fP\fP
.TP
\fB\fIIMAGE_FORMAT_YUV422P16 \fP\fP
.TP
\fB\fIIMAGE_FORMAT_YUV444P16 \fP\fP
.TP
\fB\fIIMAGE_FORMAT_Y16 \fP\fP
.TP
\fB\fI_IMAGE_FORMAT_MAX \fP\fP
.PP
Definition at line \fB52\fP of file \fBImage\&.hpp\fP\&.
.SS "enum \fBlctm::KillingFunction\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIKILL_ALL \fP\fP
.TP
\fB\fIKEEP_ALL \fP\fP
.TP
\fB\fITHRESHOLD_CUTOFF \fP\fP
.PP
Definition at line \fB60\fP of file \fBPriorityMap\&.hpp\fP\&.
.SS "enum \fBlctm::NalUnitType\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fILCEVC_NON_IDR \fP\fP
.TP
\fB\fILCEVC_IDR \fP\fP
.TP
\fB\fILCEVC_RSV \fP\fP
.PP
Definition at line \fB119\fP of file \fBTypes\&.hpp\fP\&.
.SS "enum \fBlctm::ParameterConfig\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIParameterConfig_Default \fP\fP
.TP
\fB\fIParameterConfig_Conformance \fP\fP
.PP
Definition at line \fB166\fP of file \fBTypes\&.hpp\fP\&.
.SS "enum \fBlctm::PictureType\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIPictureType_Frame \fP\fP
.TP
\fB\fIPictureType_Field \fP\fP
.PP
Definition at line \fB113\fP of file \fBTypes\&.hpp\fP\&.
.SS "enum \fBlctm::PriorityMBType\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fISmooth \fP\fP
.TP
\fB\fIPlain \fP\fP
.TP
\fB\fICoarse \fP\fP
.TP
\fB\fIEdge \fP\fP
.TP
\fB\fISmoothAndPlain \fP\fP
.TP
\fB\fICoarseAndPlain \fP\fP
.PP
Definition at line \fB48\fP of file \fBPriorityConfiguration\&.hpp\fP\&.
.SS "enum \fBlctm::PriorityMode\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIPM_ALL_OFF \fP\fP
.TP
\fB\fIPM_ALL_ON \fP\fP
.TP
\fB\fIPM_SL1_ON \fP\fP
.TP
\fB\fIPM_SL2_ON \fP\fP
.TP
\fB\fIPM_SL1_OFF \fP\fP
.TP
\fB\fIPM_SL2_OFF \fP\fP
.PP
Definition at line \fB47\fP of file \fBPriorityConfiguration\&.hpp\fP\&.
.SS "enum \fBlctm::Profile\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIProfile_Main \fP\fP
.TP
\fB\fIProfile_Main444 \fP\fP
.TP
\fB\fIProfile_Auto \fP\fP
.PP
Definition at line \fB121\fP of file \fBTypes\&.hpp\fP\&.
.SS "enum \fBlctm::QuantMatrix\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIQuantMatrix_BothPrevious \fP\fP
.TP
\fB\fIQuantMatrix_BothDefault \fP\fP
.TP
\fB\fIQuantMatrix_SameAndCustom \fP\fP
.TP
\fB\fIQuantMatrix_Level2CustomLevel1Default \fP\fP
.TP
\fB\fIQuantMatrix_Level2DefaultLevel1Custom \fP\fP
.TP
\fB\fIQuantMatrix_DifferentAndCustom \fP\fP
.PP
Definition at line \fB85\fP of file \fBTypes\&.hpp\fP\&.
.SS "enum \fBlctm::ResidualLabel\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIRESIDUAL_LIVE \fP\fP
.TP
\fB\fIRESIDUAL_KILL \fP\fP
.PP
Definition at line \fB173\fP of file \fBTypes\&.hpp\fP\&.
.SS "enum \fBlctm::ScalingMode\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIScalingMode_None \fP\fP
.TP
\fB\fIScalingMode_1D \fP\fP
.TP
\fB\fIScalingMode_2D \fP\fP
.PP
Definition at line \fB59\fP of file \fBTypes\&.hpp\fP\&.
.SS "enum \fBlctm::SyntaxBlocks\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fISyntaxBlock_Sequence \fP\fP
.TP
\fB\fISyntaxBlock_Global \fP\fP
.TP
\fB\fISyntaxBlock_Picture \fP\fP
.TP
\fB\fISyntaxBlock_EncodedData \fP\fP
.TP
\fB\fISyntaxBlock_EncodedData_Tiled \fP\fP
.TP
\fB\fISyntaxBlock_Additional_Info \fP\fP
.TP
\fB\fISyntaxBlock_Filler \fP\fP
.PP
Definition at line \fB155\fP of file \fBTypes\&.hpp\fP\&.
.SS "enum \fBlctm::Temporal_SWM\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fISWM_Disabled \fP\fP
.TP
\fB\fISWM_Active \fP\fP
.TP
\fB\fISWM_Dependent \fP\fP
.PP
Definition at line \fB147\fP of file \fBTypes\&.hpp\fP\&.
.SS "enum \fBlctm::TemporalType\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fITEMPORAL_PRED \fP\fP
.TP
\fB\fITEMPORAL_INTR \fP\fP
.PP
Definition at line \fB175\fP of file \fBTypes\&.hpp\fP\&.
.SS "enum \fBlctm::TileDimensions\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fITileDimensions_None \fP\fP
.TP
\fB\fITileDimensions_512x256 \fP\fP
.TP
\fB\fITileDimensions_1024x512 \fP\fP
.TP
\fB\fITileDimensions_Custom \fP\fP
.PP
Definition at line \fB78\fP of file \fBTypes\&.hpp\fP\&.
.SS "enum \fBlctm::TileType\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fITileTypePlain \fP\fP
.TP
\fB\fITileTypeEdge \fP\fP
.TP
\fB\fITileTypeSmooth \fP\fP
.TP
\fB\fITileTypeCoarse \fP\fP
.PP
Definition at line \fB47\fP of file \fBResidualMap\&.hpp\fP\&.
.SS "enum \fBlctm::TransformType\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fITransformType_DD \fP\fP
.TP
\fB\fITransformType_DDS \fP\fP
.PP
Definition at line \fB111\fP of file \fBTypes\&.hpp\fP\&.
.SS "enum \fBlctm::Upsample\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIUpsample_Nearest \fP\fP
.TP
\fB\fIUpsample_Linear \fP\fP
.TP
\fB\fIUpsample_Cubic \fP\fP
.TP
\fB\fIUpsample_ModifiedCubic \fP\fP
.TP
\fB\fIUpsample_AdaptiveCubic \fP\fP
.PP
Definition at line \fB45\fP of file \fBTypes\&.hpp\fP\&.
.SS "enum \fBlctm::UserDataMethod\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIUserDataMethod_Zeros \fP\fP
.TP
\fB\fIUserDataMethod_Ones \fP\fP
.TP
\fB\fIUserDataMethod_Random \fP\fP
.TP
\fB\fIUserDataMethod_FixedRandom \fP\fP
.PP
Definition at line \fB71\fP of file \fBTypes\&.hpp\fP\&.
.SS "enum \fBlctm::UserDataMode\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIUserData_None \fP\fP
.TP
\fB\fIUserData_2bits \fP\fP
.TP
\fB\fIUserData_6bits \fP\fP
.PP
Definition at line \fB65\fP of file \fBTypes\&.hpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "template<typename T > T lctm::_check (T c, const char * file, int line, const char * func, const char * expr)"

.PP
Definition at line \fB60\fP of file \fBDiagnostics\&.hpp\fP\&.
.SS "void lctm::_check_failed (const char * file, int line, const char * func, const std::string & message)"

.PP
Definition at line \fB71\fP of file \fBDiagnostics\&.cpp\fP\&.
.SS "void lctm::_log (const char * file, int line, const char * func, const std::string & message)"

.PP
Definition at line \fB88\fP of file \fBDiagnostics\&.cpp\fP\&.
.SS "void lctm::_log_report (const std::string & message)"

.PP
Definition at line \fB95\fP of file \fBDiagnostics\&.cpp\fP\&.
.SS "void lctm::_raise (const char * file, int line, const char * func, const std::string & message)"

.PP
Definition at line \fB80\fP of file \fBDiagnostics\&.cpp\fP\&.
.SS "template<typename T > T lctm::clamp (T val, T l, T h)"

.PP
Definition at line \fB102\fP of file \fBMisc\&.hpp\fP\&.
.SS "\fBCodec\fP * lctm::CodecCreate (const std::string & name, \fBCodecOperation\fP operation, const std::string & json_codec_selection_options)"

.SS "\fBCodec\fP * lctm::CodecCreate (const string & name, \fBCodecOperation\fP operation, const string & create_options)"

.PP
Definition at line \fB56\fP of file \fBCodec\&.cpp\fP\&.
.SS "string lctm::CodecErrorToString (\fBCodec\fP * codec, \fBCodecError\fP error)"

.PP
Definition at line \fB97\fP of file \fBCodec\&.cpp\fP\&.
.SS "void lctm::CodecRelease (\fBCodec\fP * codec)"

.PP
Definition at line \fB92\fP of file \fBCodec\&.cpp\fP\&.
.SS "uint64_t lctm::crc64 (uint64_t crc, const unsigned char * s, uint64_t l)"

.PP
Definition at line \fB350\fP of file \fBMisc\&.cpp\fP\&.
.SS "unique_ptr< \fBBaseVideoDecoder\fP > lctm::CreateBaseVideoDecoder (\fBBaseVideoDecoder::Output\fP & output, \fBBaseCoding\fP base, \fBEncapsulation\fP encapulation, bool external, const std::string & prepared_yuv_file, bool keep_base)"

.PP
Definition at line \fB565\fP of file \fBBaseVideoDecoder\&.cpp\fP\&.
.SS "unique_ptr< \fBBaseVideoDecoder\fP > lctm::CreateBaseVideoDecoderCodecApi (\fBBaseVideoDecoder::Output\fP & output, \fBEncapsulation\fP encapsulation, \fBBaseCoding\fP base_coding, const std::string & name, const std::string & selection_options, const std::string & create_options)"

.PP
Definition at line \fB220\fP of file \fBBaseVideoDecoderCodecApi\&.cpp\fP\&.
.SS "unique_ptr< \fBBaseVideoDecoder\fP > lctm::CreateBaseVideoDecoderHM (\fBBaseVideoDecoder::Output\fP & output, \fBEncapsulation\fP encapsulation)"

.PP
Definition at line \fB568\fP of file \fBBaseVideoDecoderHM\&.cpp\fP\&.
.SS "unique_ptr< \fBBaseVideoDecoder\fP > lctm::CreateBaseVideoDecoderJM (\fBBaseVideoDecoder::Output\fP & output, \fBEncapsulation\fP encapsulation)"

.PP
Definition at line \fB321\fP of file \fBBaseVideoDecoderJM\&.cpp\fP\&.
.SS "std::unique_ptr< \fBBuffer\fP > lctm::CreateBufferAligned (const uint8_t * data, unsigned size)"

.PP
Definition at line \fB168\fP of file \fBBuffer\&.cpp\fP\&.
.SS "std::unique_ptr< \fBBuffer\fP > lctm::CreateBufferAligned (unsigned size)"

.PP
Definition at line \fB172\fP of file \fBBuffer\&.cpp\fP\&.
.SS "std::unique_ptr< \fBBuffer\fP > lctm::CreateBufferVector (const uint8_t * data, unsigned size)"

.PP
Definition at line \fB100\fP of file \fBBuffer\&.cpp\fP\&.
.SS "std::unique_ptr< \fBBuffer\fP > lctm::CreateBufferVector (unsigned size)"

.PP
Definition at line \fB104\fP of file \fBBuffer\&.cpp\fP\&.
.SS "unique_ptr< \fBFileEncoder\fP > lctm::CreateFileEncoder (\fBBaseCoding\fP base_encoder, const \fBImageDescription\fP & image_description, unsigned fps, const \fBParameters\fP & parameters)"

.PP
Definition at line \fB1247\fP of file \fBFileEncoder\&.cpp\fP\&.
.SS "std::unique_ptr< \fBYUVReader\fP > lctm::CreateYUVReader (const std::string & name)"

.SS "std::unique_ptr< \fBYUVReader\fP > lctm::CreateYUVReader (const std::string & name, const \fBImageDescription\fP & image_description, unsigned rate)"

.PP
Definition at line \fB190\fP of file \fBYUVReader\&.cpp\fP\&.
.SS "std::unique_ptr< \fBYUVReader\fP > lctm::CreateYUVReader (const std::string & name, unsigned rate)"

.SS "unique_ptr< \fBYUVReader\fP > lctm::CreateYUVReader (const string & name)"

.PP
Definition at line \fB213\fP of file \fBYUVReader\&.cpp\fP\&.
.SS "unique_ptr< \fBYUVReader\fP > lctm::CreateYUVReader (const string & name, unsigned rate)"

.PP
Definition at line \fB225\fP of file \fBYUVReader\&.cpp\fP\&.
.SS "std::unique_ptr< \fBYUVWriter\fP > lctm::CreateYUVWriter (const std::string & name)"

.PP
Definition at line \fB112\fP of file \fBYUVWriter\&.cpp\fP\&.
.SS "std::unique_ptr< \fBYUVWriter\fP > lctm::CreateYUVWriter (const std::string & name, const \fBImageDescription\fP & image_description, bool decorate)"

.PP
Definition at line \fB108\fP of file \fBYUVWriter\&.cpp\fP\&.
.SS "\fBImage\fP lctm::DownsampleImage (const \fBImage\fP & src, \fBDownsample\fP downsample_luma, \fBDownsample\fP downsample_chroma, \fBScalingMode\fP scaling_mode, unsigned dst_bit_depth = \fC0\fP)"

.PP
Definition at line \fB142\fP of file \fBDownsampling\&.cpp\fP\&.
.SS "\fBImage\fP lctm::ExpandImage (const \fBImage\fP & src, const \fBImageDescription\fP & description)"

.PP
Definition at line \fB79\fP of file \fBExpand\&.cpp\fP\&.
.SS "template<typename T > T lctm::extract (const std::string & s)"

.PP
Definition at line \fB156\fP of file \fBMisc\&.hpp\fP\&.
.SS "template<typename T > T lctm::extract (const std::string & s, T dflt)"

.PP
Definition at line \fB167\fP of file \fBMisc\&.hpp\fP\&.
.SS "std::string lctm::file_extension (const std::string & filename)"

.PP
Definition at line \fB233\fP of file \fBMisc\&.cpp\fP\&.
.SS "size_t lctm::file_size (const std::string & name)"

.PP
Definition at line \fB135\fP of file \fBMisc\&.cpp\fP\&.
.SS "size_t lctm::file_size (int fd)"

.PP
Definition at line \fB119\fP of file \fBMisc\&.cpp\fP\&.
.SS "int32_t lctm::find_dirq_step_width (int32_t orig_step_width, int32_t quant_matrix_coeff)"

.PP
Definition at line \fB131\fP of file \fBInverseQuantize\&.cpp\fP\&.
.SS "int32_t lctm::find_invq_applied_offset (const \fBPictureConfiguration\fP & picture_configuration, int32_t invq_offset, int32_t layer_deadzone)"

.PP
Definition at line \fB218\fP of file \fBInverseQuantize\&.cpp\fP\&.
.SS "int32_t lctm::find_invq_offset (const \fBPictureConfiguration\fP & picture_configuration, int32_t orig_step_width, int32_t dirq_step_width)"

.PP
Definition at line \fB140\fP of file \fBInverseQuantize\&.cpp\fP\&.
.SS "int32_t lctm::find_invq_step_width (const \fBPictureConfiguration\fP & picture_configuration, int32_t dirq_step_width, int32_t invq_offset)"

.PP
Definition at line \fB169\fP of file \fBInverseQuantize\&.cpp\fP\&.
.SS "int32_t lctm::find_layer_deadzone (int32_t orig_step_width, int32_t dirq_step_width)"

.PP
Definition at line \fB203\fP of file \fBInverseQuantize\&.cpp\fP\&.
.SS "int32_t lctm::find_quant_matrix_coeff (const \fBPictureConfiguration\fP & picture_configuration, unsigned num_layers, bool horizontal_only, unsigned loq, unsigned layer, bool is_idr, int32_t previous)"

.PP
Definition at line \fB63\fP of file \fBInverseQuantize\&.cpp\fP\&.
.SS "std::string lctm::format (const char * fmt,  \&.\&.\&.)"

.PP
Definition at line \fB46\fP of file \fBDiagnostics\&.cpp\fP\&.
.SS "std::string lctm::get_program ()"

.PP
Definition at line \fB91\fP of file \fBMisc\&.cpp\fP\&.
.SS "std::string lctm::get_program_directory (const std::string & suffix)"

.PP
Definition at line \fB102\fP of file \fBMisc\&.cpp\fP\&.
.SS "std::string lctm::hex_dump (const uint8_t * data, uint64_t size, unsigned int offset)"

.PP
Definition at line \fB101\fP of file \fBDiagnostics\&.cpp\fP\&.
.SS "std::string lctm::join (const std::vector< std::string > & list, const std::string & seperator, bool include_trailing = \fCfalse\fP)"

.PP
Definition at line \fB57\fP of file \fBDiagnostics\&.cpp\fP\&.
.SS "std::string lctm::lowercase (const char * s)"

.PP
Definition at line \fB179\fP of file \fBMisc\&.cpp\fP\&.
.SS "std::string lctm::lowercase (const std::string & s)"

.PP
Definition at line \fB185\fP of file \fBMisc\&.cpp\fP\&.
.SS "std::string lctm::make_temporary_filename (const std::string & suffix)"

.PP
Definition at line \fB366\fP of file \fBMisc\&.cpp\fP\&.
.SS "template<typename T , typename\&.\&.\&. Args> std::unique_ptr< T > lctm::make_unique (Args &&\&.\&.\&. args)"

.PP
Definition at line \fB367\fP of file \fBFileEncoder\&.cpp\fP\&.
.SS "bool lctm::operator== (const class \fBImageDescription\fP & lhs, const class \fBImageDescription\fP & rhs)"

.SS "bool lctm::operator== (const \fBImageDescription\fP & lhs, const \fBImageDescription\fP & rhs)"

.PP
Definition at line \fB181\fP of file \fBImage\&.cpp\fP\&.
.SS "std::istream & lctm::operator>> (std::istream & in, \fBBaseCoding\fP & v)"

.PP
Definition at line \fB141\fP of file \fBTypes\&.cpp\fP\&.
.SS "std::istream & lctm::operator>> (std::istream & in, \fBColourspace\fP & v)"

.PP
Definition at line \fB327\fP of file \fBImage\&.cpp\fP\&.
.SS "std::istream & lctm::operator>> (std::istream & in, \fBCompressionType\fP & v)"

.PP
Definition at line \fB222\fP of file \fBTypes\&.cpp\fP\&.
.SS "std::istream & lctm::operator>> (std::istream & in, \fBDequantOffset\fP & v)"

.PP
Definition at line \fB113\fP of file \fBTypes\&.cpp\fP\&.
.SS "std::istream & lctm::operator>> (std::istream & in, \fBDitheringType\fP & v)"

.PP
Definition at line \fB97\fP of file \fBTypes\&.cpp\fP\&.
.SS "std::istream & lctm::operator>> (std::istream & in, \fBDownsample\fP & v)"

.PP
Definition at line \fB65\fP of file \fBTypes\&.cpp\fP\&.
.SS "std::istream & lctm::operator>> (std::istream & in, \fBEncapsulation\fP & v)"

.PP
Definition at line \fB181\fP of file \fBTypes\&.cpp\fP\&.
.SS "std::istream & lctm::operator>> (std::istream & in, \fBImageFormat\fP & v)"

.PP
Definition at line \fB239\fP of file \fBImage\&.cpp\fP\&.
.SS "std::istream & lctm::operator>> (std::istream & in, \fBParameterConfig\fP & v)"

.PP
Definition at line \fB302\fP of file \fBTypes\&.cpp\fP\&.
.SS "std::istream & lctm::operator>> (std::istream & in, \fBPictureType\fP & v)"

.PP
Definition at line \fB272\fP of file \fBTypes\&.cpp\fP\&.
.SS "std::istream & lctm::operator>> (std::istream & in, \fBProfile\fP & v)"

.PP
Definition at line \fB286\fP of file \fBTypes\&.cpp\fP\&.
.SS "std::istream & lctm::operator>> (std::istream & in, \fBQuantMatrix\fP & v)"

.PP
Definition at line \fB200\fP of file \fBTypes\&.cpp\fP\&.
.SS "std::istream & lctm::operator>> (std::istream & in, \fBScalingMode\fP & v)"

.PP
Definition at line \fB81\fP of file \fBTypes\&.cpp\fP\&.
.SS "std::istream & lctm::operator>> (std::istream & in, \fBTransformType\fP & v)"

.PP
Definition at line \fB127\fP of file \fBTypes\&.cpp\fP\&.
.SS "std::istream & lctm::operator>> (std::istream & in, \fBUpsample\fP & v)"

.PP
Definition at line \fB45\fP of file \fBTypes\&.cpp\fP\&.
.SS "std::istream & lctm::operator>> (std::istream & in, \fBUserDataMethod\fP & v)"

.PP
Definition at line \fB254\fP of file \fBTypes\&.cpp\fP\&.
.SS "std::istream & lctm::operator>> (std::istream & in, \fBUserDataMode\fP & v)"

.PP
Definition at line \fB238\fP of file \fBTypes\&.cpp\fP\&.
.SS "\fBParameters\fP lctm::parameter_defaults_global (const \fBParameters\fP & p)"

.PP
Definition at line \fB72\fP of file \fBParameterDefaults\&.cpp\fP\&.
.SS "\fBParameters\fP lctm::parameter_defaults_picture (const \fBParameters\fP & p, std::vector< std::unique_ptr< \fBImage\fP > > & src_image, unsigned base_qp)"

.PP
Definition at line \fB152\fP of file \fBParameterDefaults\&.cpp\fP\&.
.SS "template<typename A , typename B , size_t N> B lctm::piecewise_linear (const std::array< A, N > & a, const std::array< B, N > & b, A v)"

.PP
Definition at line \fB47\fP of file \fBParameterDefaults\&.cpp\fP\&.
.SS "bool lctm::probe_es_file (const std::string & name, \fBBaseCoding\fP coding, unsigned & width, unsigned & height, unsigned & bit_depth, unsigned & chroma_format_idc)"

.SS "bool lctm::probe_es_file (const string & name, \fBBaseCoding\fP coding, unsigned & width, unsigned & height, unsigned & bit_depth, unsigned & chroma_format_idc)"

.PP
Definition at line \fB52\fP of file \fBProbe\&.cpp\fP\&.
.SS "std::string lctm::read_file (const std::string & name)"

.PP
Definition at line \fB151\fP of file \fBMisc\&.cpp\fP\&.
.SS "size_t lctm::scan_enhancement (uint8_t * data, size_t data_size, \fBEncapsulation\fP encapsulation, \fBBaseCoding\fP coding, uint64_t pts, bool is_idr, std::function< void(const \fBPacket\fP &pkt, const bool \fBis_lcevc_idr\fP)> callback)"

.PP
Definition at line \fB413\fP of file \fBScanEnhancement\&.cpp\fP\&.
.SS "unsigned lctm::split (std::vector< std::string > & output, const std::string & src, const char * seperators)"

.PP
Definition at line \fB191\fP of file \fBMisc\&.cpp\fP\&.
.SS "uint64_t lctm::system_timestamp ()"

.PP
Definition at line \fB359\fP of file \fBMisc\&.cpp\fP\&.
.SS "\fBImage\fP lctm::UpsampleImage (const \fBImage\fP & src, \fBUpsample\fP upsample, const unsigned upsampling_coefficients[4], \fBScalingMode\fP scaling_mode)"

.PP
Definition at line \fB204\fP of file \fBUpsampling\&.cpp\fP\&.
.SS "bool lctm::write_file (const std::string & name, const std::string & contents)"

.PP
Definition at line \fB171\fP of file \fBMisc\&.cpp\fP\&.
.SH "Variable Documentation"
.PP 
.SS "int lctm::bits"

.PP
Definition at line \fB122\fP of file \fBYUVReader\&.cpp\fP\&.
.SS "std::string lctm::format"

.PP
Definition at line \fB123\fP of file \fBYUVReader\&.cpp\fP\&.
.SS "const char* lctm::name"

.PP
Definition at line \fB121\fP of file \fBYUVReader\&.cpp\fP\&.
.SS "const unsigned lctm::resolution_table[51][2]"
\fBInitial value:\fP.PP
.nf
= {
    {0, 0},       {360, 200},   {400, 240},   {480, 320},   {640, 360},   {640, 480},   {768, 480},   {800, 600},   {852, 480},
    {854, 480},   {856, 480},   {960, 540},   {960, 640},   {1024, 576},  {1024, 600},  {1024, 768},  {1152, 864},  {1280, 720},
    {1280, 800},  {1280, 1024}, {1360, 768},  {1366, 768},  {1440, 1050}, {1440, 900},  {1600, 1200}, {1680, 1050}, {1920, 1080},
    {1920, 1200}, {2048, 1080}, {2048, 1152}, {2048, 1536}, {2160, 1440}, {2560, 1440}, {2560, 1600}, {2560, 2048}, {3200, 1800},
    {3200, 2048}, {3200, 2400}, {3440, 1440}, {3840, 1600}, {3840, 2160}, {3840, 3072}, {4096, 2160}, {4096, 3072}, {5120, 2880},
    {5120, 3200}, {5120, 4096}, {6400, 4096}, {6400, 4800}, {7680, 4320}, {7680, 4800}}
.fi

.PP
Definition at line \fB70\fP of file \fBSerializer\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
