.TH "lctm::EntropyDecoderResiduals" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lctm::EntropyDecoderResiduals
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <EntropyDecoder\&.hpp>\fP
.PP
Inherits \fBlctm::EntropyDecoderResidualsBase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEntropyDecoderResiduals\fP ()"
.br
.ti -1c
.RI "\fBSurface\fP \fBprocess\fP (unsigned width, unsigned height, bool entropy_enabled, bool rle_only, \fBBitstreamUnpacker\fP &b)"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Types inherited from \fBlctm::EntropyDecoderResidualsBase\fP
.in +1c
.ti -1c
.RI "enum { \fBSTATE_LSB\fP, \fBSTATE_MSB\fP, \fBSTATE_ZERO\fP, \fBSTATE_COUNT\fP }"
.br
.in -1c

Protected Member Functions inherited from \fBlctm::EntropyDecoderResidualsBase\fP
.in +1c
.ti -1c
.RI "\fBrle_pel_t\fP \fBdecode_pel\fP (\fBSymbolSource\fP &source) const"
.br
.in -1c
.in +1c
.ti -1c
.RI "\fBEntropyDecoderResidualsBase\fP ()"
.br
.in -1c

Protected Member Functions inherited from \fBlctm::Component\fP
.in +1c
.ti -1c
.RI "\fBComponent\fP (const std::string &\fBname\fP)"
.br
.ti -1c
.RI "virtual \fB~Component\fP ()=0"
.br
.ti -1c
.RI "virtual const std::string \fBname\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB70\fP of file \fBEntropyDecoder\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "lctm::EntropyDecoderResiduals::EntropyDecoderResiduals ()\fC [inline]\fP"

.PP
Definition at line \fB73\fP of file \fBEntropyDecoder\&.hpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBSurface\fP lctm::EntropyDecoderResiduals::process (unsigned width, unsigned height, bool entropy_enabled, bool rle_only, \fBBitstreamUnpacker\fP & b)"

.PP
Definition at line \fB180\fP of file \fBEntropyDecoder\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
