.TH "lctm::Downsampling" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lctm::Downsampling
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Downsampling\&.hpp>\fP
.PP
Inherits \fBlctm::Component\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDownsampling\fP ()"
.br
.ti -1c
.RI "\fBSurface\fP \fBprocess\fP (const \fBSurface\fP &src_plane, \fBDownsample\fP kernel)"
.br
.in -1c

Public Member Functions inherited from \fBlctm::Component\fP
.in +1c
.ti -1c
.RI "\fBComponent\fP (const std::string &\fBname\fP)"
.br
.ti -1c
.RI "virtual \fB~Component\fP ()=0"
.br
.ti -1c
.RI "virtual const std::string \fBname\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB46\fP of file \fBDownsampling\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "lctm::Downsampling::Downsampling ()\fC [inline]\fP"

.PP
Definition at line \fB48\fP of file \fBDownsampling\&.hpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBSurface\fP lctm::Downsampling::process (const \fBSurface\fP & src_plane, \fBDownsample\fP kernel)"

.PP
Definition at line \fB78\fP of file \fBDownsampling\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
