.TH "lctm::TemporalMask" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lctm::TemporalMask
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <TemporalEncode\&.hpp>\fP
.PP
Inherits \fBlctm::Component\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTemporalMask\fP ()"
.br
.ti -1c
.RI "\fBSurface\fP \fBprocess\fP (const \fBSurface\fP &temporal_type, const \fBSurface\fP &temporal_type_next_plane, const \fBSurface\fP &residual_plane, unsigned transform_block_size, bool refresh, bool use_reduced_signalling)"
.br
.in -1c

Public Member Functions inherited from \fBlctm::Component\fP
.in +1c
.ti -1c
.RI "\fBComponent\fP (const std::string &\fBname\fP)"
.br
.ti -1c
.RI "virtual \fB~Component\fP ()=0"
.br
.ti -1c
.RI "virtual const std::string \fBname\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB73\fP of file \fBTemporalEncode\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "lctm::TemporalMask::TemporalMask ()\fC [inline]\fP"

.PP
Definition at line \fB75\fP of file \fBTemporalEncode\&.hpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBSurface\fP lctm::TemporalMask::process (const \fBSurface\fP & temporal_type, const \fBSurface\fP & temporal_type_next_plane, const \fBSurface\fP & residual_plane, unsigned transform_block_size, bool refresh, bool use_reduced_signalling)"


.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
