.TH "lctm::SurfaceView< T, S >" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lctm::SurfaceView< T, S >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Surface\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSurfaceView\fP (const \fBSurface\fP &surface)"
.br
.ti -1c
.RI "\fB~SurfaceView\fP ()"
.br
.ti -1c
.RI "unsigned \fBwidth\fP () const"
.br
.ti -1c
.RI "unsigned \fBheight\fP () const"
.br
.ti -1c
.RI "unsigned \fBstride\fP () const"
.br
.ti -1c
.RI "const T * \fBdata\fP () const"
.br
.ti -1c
.RI "const T * \fBdata\fP (unsigned x, unsigned y) const"
.br
.ti -1c
.RI "unsigned \fBsize\fP () const"
.br
.ti -1c
.RI "unsigned \fBrow_size\fP () const"
.br
.ti -1c
.RI "bool \fBrows_are_contiguous\fP () const"
.br
.ti -1c
.RI "T \fBread\fP (unsigned x, unsigned y) const"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T, unsigned S = 0>
.br
class lctm::SurfaceView< T, S >"
.PP
Definition at line \fB56\fP of file \fBSurface\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename T , unsigned S = 0> SurfaceView::SurfaceView (const \fBSurface\fP & surface)"

.PP
Definition at line \fB244\fP of file \fBSurfaceImpl\&.hpp\fP\&.
.SS "template<typename T , unsigned S = 0> SurfaceView::~SurfaceView ()"

.PP
Definition at line \fB249\fP of file \fBSurfaceImpl\&.hpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "template<typename T , unsigned S = 0> const T * SurfaceView::data () const"

.PP
Definition at line \fB251\fP of file \fBSurfaceImpl\&.hpp\fP\&.
.SS "template<typename T , unsigned S = 0> const T * SurfaceView::data (unsigned x, unsigned y) const"

.PP
Definition at line \fB253\fP of file \fBSurfaceImpl\&.hpp\fP\&.
.SS "template<typename T , unsigned S = 0> unsigned SurfaceView::height () const"

.PP
Definition at line \fB262\fP of file \fBSurfaceImpl\&.hpp\fP\&.
.SS "template<typename T , unsigned S = 0> T SurfaceView::read (unsigned x, unsigned y) const"

.PP
Definition at line \fB258\fP of file \fBSurfaceImpl\&.hpp\fP\&.
.SS "template<typename T , unsigned S = 0> unsigned SurfaceView::row_size () const"

.PP
Definition at line \fB266\fP of file \fBSurfaceImpl\&.hpp\fP\&.
.SS "template<typename T , unsigned S = 0> bool SurfaceView::rows_are_contiguous () const"

.PP
Definition at line \fB268\fP of file \fBSurfaceImpl\&.hpp\fP\&.
.SS "template<typename T , unsigned S = 0> unsigned SurfaceView::size () const"

.PP
Definition at line \fB264\fP of file \fBSurfaceImpl\&.hpp\fP\&.
.SS "template<typename T , unsigned S = 0> unsigned \fBlctm::SurfaceView\fP< T, S >::stride () const"

.SS "template<typename T , unsigned S = 0> unsigned SurfaceView::width () const"

.PP
Definition at line \fB260\fP of file \fBSurfaceImpl\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
