.TH "lctm::EncoderConfiguration" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lctm::EncoderConfiguration
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <EncoderConfiguration\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned \fBtemporal_cq_sw_multiplier\fP"
.br
.ti -1c
.RI "unsigned \fBdelta_sw_mult_gop08\fP"
.br
.ti -1c
.RI "unsigned \fBdelta_sw_mult_gop04\fP"
.br
.ti -1c
.RI "unsigned \fBdelta_sw_mult_gop02\fP"
.br
.ti -1c
.RI "unsigned \fBdelta_sw_mult_gop01\fP"
.br
.ti -1c
.RI "\fBEncodingMode\fP \fBencoding_mode\fP"
.br
.ti -1c
.RI "bool \fBtemporal_use_priority_map_sl_1\fP"
.br
.ti -1c
.RI "bool \fBtemporal_use_priority_map_sl_2\fP"
.br
.ti -1c
.RI "\fBPriorityMBType\fP \fBpriority_type_sl_1\fP"
.br
.ti -1c
.RI "\fBPriorityMBType\fP \fBpriority_type_sl_2\fP"
.br
.ti -1c
.RI "unsigned \fBsad_threshold\fP"
.br
.ti -1c
.RI "unsigned \fBsad_coeff_threshold\fP"
.br
.ti -1c
.RI "unsigned \fBquant_reduced_deadzone\fP"
.br
.ti -1c
.RI "bool \fBno_enhancement_temporal_layer\fP"
.br
.ti -1c
.RI "\fBUserDataMethod\fP \fBuser_data_method\fP"
.br
.ti -1c
.RI "unsigned \fBbase_qp\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB52\fP of file \fBEncoderConfiguration\&.hpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "unsigned lctm::EncoderConfiguration::base_qp"

.PP
Definition at line \fB72\fP of file \fBEncoderConfiguration\&.hpp\fP\&.
.SS "unsigned lctm::EncoderConfiguration::delta_sw_mult_gop01"

.PP
Definition at line \fB58\fP of file \fBEncoderConfiguration\&.hpp\fP\&.
.SS "unsigned lctm::EncoderConfiguration::delta_sw_mult_gop02"

.PP
Definition at line \fB57\fP of file \fBEncoderConfiguration\&.hpp\fP\&.
.SS "unsigned lctm::EncoderConfiguration::delta_sw_mult_gop04"

.PP
Definition at line \fB56\fP of file \fBEncoderConfiguration\&.hpp\fP\&.
.SS "unsigned lctm::EncoderConfiguration::delta_sw_mult_gop08"

.PP
Definition at line \fB55\fP of file \fBEncoderConfiguration\&.hpp\fP\&.
.SS "\fBEncodingMode\fP lctm::EncoderConfiguration::encoding_mode"

.PP
Definition at line \fB60\fP of file \fBEncoderConfiguration\&.hpp\fP\&.
.SS "bool lctm::EncoderConfiguration::no_enhancement_temporal_layer"

.PP
Definition at line \fB69\fP of file \fBEncoderConfiguration\&.hpp\fP\&.
.SS "\fBPriorityMBType\fP lctm::EncoderConfiguration::priority_type_sl_1"

.PP
Definition at line \fB63\fP of file \fBEncoderConfiguration\&.hpp\fP\&.
.SS "\fBPriorityMBType\fP lctm::EncoderConfiguration::priority_type_sl_2"

.PP
Definition at line \fB64\fP of file \fBEncoderConfiguration\&.hpp\fP\&.
.SS "unsigned lctm::EncoderConfiguration::quant_reduced_deadzone"

.PP
Definition at line \fB67\fP of file \fBEncoderConfiguration\&.hpp\fP\&.
.SS "unsigned lctm::EncoderConfiguration::sad_coeff_threshold"

.PP
Definition at line \fB66\fP of file \fBEncoderConfiguration\&.hpp\fP\&.
.SS "unsigned lctm::EncoderConfiguration::sad_threshold"

.PP
Definition at line \fB65\fP of file \fBEncoderConfiguration\&.hpp\fP\&.
.SS "unsigned lctm::EncoderConfiguration::temporal_cq_sw_multiplier"

.PP
Definition at line \fB53\fP of file \fBEncoderConfiguration\&.hpp\fP\&.
.SS "bool lctm::EncoderConfiguration::temporal_use_priority_map_sl_1"

.PP
Definition at line \fB61\fP of file \fBEncoderConfiguration\&.hpp\fP\&.
.SS "bool lctm::EncoderConfiguration::temporal_use_priority_map_sl_2"

.PP
Definition at line \fB62\fP of file \fBEncoderConfiguration\&.hpp\fP\&.
.SS "\fBUserDataMethod\fP lctm::EncoderConfiguration::user_data_method"

.PP
Definition at line \fB70\fP of file \fBEncoderConfiguration\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
