.TH "lctm::ImageDescription" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lctm::ImageDescription
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Image\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBImageDescription\fP ()"
.br
.ti -1c
.RI "\fBImageDescription\fP (\fBImageFormat\fP \fBformat\fP, unsigned \fBwidth\fP, unsigned \fBheight\fP)"
.br
.ti -1c
.RI "\fBImageFormat\fP \fBformat\fP () const"
.br
.ti -1c
.RI "\fBColourspace\fP \fBcolourspace\fP () const"
.br
.ti -1c
.RI "unsigned \fBwidth\fP (unsigned plane=0) const"
.br
.ti -1c
.RI "unsigned \fBheight\fP (unsigned plane=0) const"
.br
.ti -1c
.RI "bool \fBis_valid\fP () const"
.br
.ti -1c
.RI "unsigned \fBnum_planes\fP () const"
.br
.ti -1c
.RI "unsigned \fBbyte_size\fP () const"
.br
.ti -1c
.RI "unsigned \fBplane_size\fP (unsigned int plane) const"
.br
.ti -1c
.RI "unsigned \fBrow_offset\fP (unsigned int plane, unsigned row) const"
.br
.ti -1c
.RI "unsigned \fBrow_stride\fP (unsigned int plane) const"
.br
.ti -1c
.RI "unsigned \fBrow_size\fP (unsigned int plane) const"
.br
.ti -1c
.RI "unsigned \fBbit_depth\fP () const"
.br
.ti -1c
.RI "unsigned \fBbyte_depth\fP () const"
.br
.ti -1c
.RI "bool \fBrows_are_contiguous\fP (unsigned int plane) const"
.br
.ti -1c
.RI "std::string \fBmake_name\fP (const std::string &base) const"
.br
.ti -1c
.RI "\fBImageDescription\fP \fBwith_depth\fP (unsigned depth) const"
.br
.ti -1c
.RI "\fBImageDescription\fP \fBwith_size\fP (unsigned \fBwidth\fP, unsigned \fBheight\fP) const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB102\fP of file \fBImage\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "lctm::ImageDescription::ImageDescription ()"

.PP
Definition at line \fB96\fP of file \fBImage\&.cpp\fP\&.
.SS "lctm::ImageDescription::ImageDescription (\fBImageFormat\fP format, unsigned width, unsigned height)"

.PP
Definition at line \fB98\fP of file \fBImage\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "unsigned lctm::ImageDescription::bit_depth () const"

.PP
Definition at line \fB173\fP of file \fBImage\&.cpp\fP\&.
.SS "unsigned lctm::ImageDescription::byte_depth () const"

.PP
Definition at line \fB175\fP of file \fBImage\&.cpp\fP\&.
.SS "unsigned lctm::ImageDescription::byte_size () const"

.PP
Definition at line \fB132\fP of file \fBImage\&.cpp\fP\&.
.SS "\fBColourspace\fP lctm::ImageDescription::colourspace () const"

.PP
Definition at line \fB102\fP of file \fBImage\&.cpp\fP\&.
.SS "\fBImageFormat\fP lctm::ImageDescription::format () const"

.PP
Definition at line \fB100\fP of file \fBImage\&.cpp\fP\&.
.SS "unsigned lctm::ImageDescription::height (unsigned plane = \fC0\fP) const"

.PP
Definition at line \fB110\fP of file \fBImage\&.cpp\fP\&.
.SS "bool lctm::ImageDescription::is_valid () const"

.PP
Definition at line \fB118\fP of file \fBImage\&.cpp\fP\&.
.SS "std::string lctm::ImageDescription::make_name (const std::string & base) const"

.PP
Definition at line \fB177\fP of file \fBImage\&.cpp\fP\&.
.SS "unsigned lctm::ImageDescription::num_planes () const"

.PP
Definition at line \fB124\fP of file \fBImage\&.cpp\fP\&.
.SS "unsigned lctm::ImageDescription::plane_size (unsigned int plane) const"

.PP
Definition at line \fB126\fP of file \fBImage\&.cpp\fP\&.
.SS "unsigned lctm::ImageDescription::row_offset (unsigned int plane, unsigned row) const"

.PP
Definition at line \fB141\fP of file \fBImage\&.cpp\fP\&.
.SS "unsigned lctm::ImageDescription::row_size (unsigned int plane) const"

.PP
Definition at line \fB153\fP of file \fBImage\&.cpp\fP\&.
.SS "unsigned lctm::ImageDescription::row_stride (unsigned int plane) const"

.PP
Definition at line \fB162\fP of file \fBImage\&.cpp\fP\&.
.SS "bool lctm::ImageDescription::rows_are_contiguous (unsigned int plane) const"

.PP
Definition at line \fB171\fP of file \fBImage\&.cpp\fP\&.
.SS "unsigned lctm::ImageDescription::width (unsigned plane = \fC0\fP) const"

.PP
Definition at line \fB104\fP of file \fBImage\&.cpp\fP\&.
.SS "\fBImageDescription\fP lctm::ImageDescription::with_depth (unsigned depth) const"

.PP
Definition at line \fB206\fP of file \fBImage\&.cpp\fP\&.
.SS "\fBImageDescription\fP lctm::ImageDescription::with_size (unsigned width, unsigned height) const"

.PP
Definition at line \fB233\fP of file \fBImage\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
