.TH "lctm::UniquePtrFileClose" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lctm::UniquePtrFileClose
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Misc\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBoperator()\fP (FILE *f)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB91\fP of file \fBMisc\&.hpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void lctm::UniquePtrFileClose::operator() (FILE * f)\fC [inline]\fP"

.PP
Definition at line \fB92\fP of file \fBMisc\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
