.TH "lctm::PictureConfiguration" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lctm::PictureConfiguration
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SignaledConfiguration\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBenhancement_enabled\fP"
.br
.ti -1c
.RI "bool \fBtemporal_refresh\fP"
.br
.ti -1c
.RI "bool \fBtemporal_signalling_present\fP"
.br
.ti -1c
.RI "\fBPictureType\fP \fBpicture_type\fP"
.br
.ti -1c
.RI "\fBFieldType\fP \fBfield_type\fP"
.br
.ti -1c
.RI "\fBCodingType\fP \fBcoding_type\fP"
.br
.ti -1c
.RI "unsigned \fBstep_width_loq\fP [\fBMAX_NUM_LOQS\fP]"
.br
.ti -1c
.RI "unsigned \fBstep_width_loq_orig\fP [\fBMAX_NUM_LOQS\fP]"
.br
.ti -1c
.RI "bool \fBdithering_control\fP"
.br
.ti -1c
.RI "\fBDitheringType\fP \fBdithering_type\fP"
.br
.ti -1c
.RI "unsigned \fBdithering_strength\fP"
.br
.ti -1c
.RI "bool \fBdequant_offset_signalled\fP"
.br
.ti -1c
.RI "\fBDequantOffset\fP \fBdequant_offset_mode\fP"
.br
.ti -1c
.RI "unsigned \fBdequant_offset\fP"
.br
.ti -1c
.RI "bool \fBlevel_1_filtering_enabled\fP"
.br
.ti -1c
.RI "\fBQuantMatrix\fP \fBquant_matrix_mode\fP"
.br
.ti -1c
.RI "unsigned \fBqm_coefficient_2\fP [\fBMAX_NUM_LAYERS\fP]"
.br
.ti -1c
.RI "unsigned \fBqm_coefficient_1\fP [\fBMAX_NUM_LAYERS\fP]"
.br
.ti -1c
.RI "unsigned \fBqm_coefficient_2_mem\fP [\fBMAX_NUM_LAYERS\fP]"
.br
.ti -1c
.RI "unsigned \fBqm_coefficient_1_mem\fP [\fBMAX_NUM_LAYERS\fP]"
.br
.ti -1c
.RI "unsigned \fBqm_coefficient_2_par\fP [\fBMAX_NUM_LAYERS\fP]"
.br
.ti -1c
.RI "unsigned \fBqm_coefficient_1_par\fP [\fBMAX_NUM_LAYERS\fP]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB122\fP of file \fBSignaledConfiguration\&.hpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBCodingType\fP lctm::PictureConfiguration::coding_type"

.PP
Definition at line \fB128\fP of file \fBSignaledConfiguration\&.hpp\fP\&.
.SS "unsigned lctm::PictureConfiguration::dequant_offset"

.PP
Definition at line \fB136\fP of file \fBSignaledConfiguration\&.hpp\fP\&.
.SS "\fBDequantOffset\fP lctm::PictureConfiguration::dequant_offset_mode"

.PP
Definition at line \fB135\fP of file \fBSignaledConfiguration\&.hpp\fP\&.
.SS "bool lctm::PictureConfiguration::dequant_offset_signalled"

.PP
Definition at line \fB134\fP of file \fBSignaledConfiguration\&.hpp\fP\&.
.SS "bool lctm::PictureConfiguration::dithering_control"

.PP
Definition at line \fB131\fP of file \fBSignaledConfiguration\&.hpp\fP\&.
.SS "unsigned lctm::PictureConfiguration::dithering_strength"

.PP
Definition at line \fB133\fP of file \fBSignaledConfiguration\&.hpp\fP\&.
.SS "\fBDitheringType\fP lctm::PictureConfiguration::dithering_type"

.PP
Definition at line \fB132\fP of file \fBSignaledConfiguration\&.hpp\fP\&.
.SS "bool lctm::PictureConfiguration::enhancement_enabled"

.PP
Definition at line \fB123\fP of file \fBSignaledConfiguration\&.hpp\fP\&.
.SS "\fBFieldType\fP lctm::PictureConfiguration::field_type"

.PP
Definition at line \fB127\fP of file \fBSignaledConfiguration\&.hpp\fP\&.
.SS "bool lctm::PictureConfiguration::level_1_filtering_enabled"

.PP
Definition at line \fB137\fP of file \fBSignaledConfiguration\&.hpp\fP\&.
.SS "\fBPictureType\fP lctm::PictureConfiguration::picture_type"

.PP
Definition at line \fB126\fP of file \fBSignaledConfiguration\&.hpp\fP\&.
.SS "unsigned lctm::PictureConfiguration::qm_coefficient_1[\fBMAX_NUM_LAYERS\fP]"

.PP
Definition at line \fB140\fP of file \fBSignaledConfiguration\&.hpp\fP\&.
.SS "unsigned lctm::PictureConfiguration::qm_coefficient_1_mem[\fBMAX_NUM_LAYERS\fP]"

.PP
Definition at line \fB142\fP of file \fBSignaledConfiguration\&.hpp\fP\&.
.SS "unsigned lctm::PictureConfiguration::qm_coefficient_1_par[\fBMAX_NUM_LAYERS\fP]"

.PP
Definition at line \fB144\fP of file \fBSignaledConfiguration\&.hpp\fP\&.
.SS "unsigned lctm::PictureConfiguration::qm_coefficient_2[\fBMAX_NUM_LAYERS\fP]"

.PP
Definition at line \fB139\fP of file \fBSignaledConfiguration\&.hpp\fP\&.
.SS "unsigned lctm::PictureConfiguration::qm_coefficient_2_mem[\fBMAX_NUM_LAYERS\fP]"

.PP
Definition at line \fB141\fP of file \fBSignaledConfiguration\&.hpp\fP\&.
.SS "unsigned lctm::PictureConfiguration::qm_coefficient_2_par[\fBMAX_NUM_LAYERS\fP]"

.PP
Definition at line \fB143\fP of file \fBSignaledConfiguration\&.hpp\fP\&.
.SS "\fBQuantMatrix\fP lctm::PictureConfiguration::quant_matrix_mode"

.PP
Definition at line \fB138\fP of file \fBSignaledConfiguration\&.hpp\fP\&.
.SS "unsigned lctm::PictureConfiguration::step_width_loq[\fBMAX_NUM_LOQS\fP]"

.PP
Definition at line \fB129\fP of file \fBSignaledConfiguration\&.hpp\fP\&.
.SS "unsigned lctm::PictureConfiguration::step_width_loq_orig[\fBMAX_NUM_LOQS\fP]"

.PP
Definition at line \fB130\fP of file \fBSignaledConfiguration\&.hpp\fP\&.
.SS "bool lctm::PictureConfiguration::temporal_refresh"

.PP
Definition at line \fB124\fP of file \fBSignaledConfiguration\&.hpp\fP\&.
.SS "bool lctm::PictureConfiguration::temporal_signalling_present"

.PP
Definition at line \fB125\fP of file \fBSignaledConfiguration\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
