.TH "lctm::BufferAligned" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lctm::BufferAligned
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBlctm::Buffer\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBufferAligned\fP (const uint8_t *data, unsigned size)"
.br
.ti -1c
.RI "\fBBufferAligned\fP (unsigned size)"
.br
.ti -1c
.RI "\fB~BufferAligned\fP () override"
.br
.ti -1c
.RI "void \fBmap_read\fP (unsigned offset, unsigned size, const uint8_t *&mapped_data, unsigned &mapped_size) const override"
.br
.ti -1c
.RI "void \fBmap_write\fP (unsigned offset, unsigned size, uint8_t *&mapped_data, unsigned &mapped_size) override"
.br
.ti -1c
.RI "void \fBunmap\fP () const override"
.br
.in -1c

Public Member Functions inherited from \fBlctm::Buffer\fP
.in +1c
.ti -1c
.RI "virtual \fB~Buffer\fP ()=0"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Member Functions inherited from \fBlctm::Buffer\fP
.in +1c
.ti -1c
.RI "\fBBuffer\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB111\fP of file \fBBuffer\&.cpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "lctm::BufferAligned::BufferAligned (const uint8_t * data, unsigned size)\fC [inline]\fP"

.PP
Definition at line \fB115\fP of file \fBBuffer\&.cpp\fP\&.
.SS "lctm::BufferAligned::BufferAligned (unsigned size)\fC [inline]\fP"

.PP
Definition at line \fB125\fP of file \fBBuffer\&.cpp\fP\&.
.SS "lctm::BufferAligned::~BufferAligned ()\fC [inline]\fP, \fC [override]\fP"

.PP
Definition at line \fB134\fP of file \fBBuffer\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void lctm::BufferAligned::map_read (unsigned offset, unsigned size, const uint8_t *& mapped_data, unsigned & mapped_size) const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBlctm::Buffer\fP\&.
.PP
Definition at line \fB145\fP of file \fBBuffer\&.cpp\fP\&.
.SS "void lctm::BufferAligned::map_write (unsigned offset, unsigned size, uint8_t *& mapped_data, unsigned & mapped_size)\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBlctm::Buffer\fP\&.
.PP
Definition at line \fB153\fP of file \fBBuffer\&.cpp\fP\&.
.SS "void lctm::BufferAligned::unmap () const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBlctm::Buffer\fP\&.
.PP
Definition at line \fB161\fP of file \fBBuffer\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
