.TH "lctm::Deserializer" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lctm::Deserializer
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Deserializer\&.hpp>\fP
.PP
Inherits \fBlctm::Component\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDeserializer\fP (const \fBPacket\fP &\fBpacket\fP, \fBSignaledConfiguration\fP &dst_configuration, \fBSurface\fP(&symbols)[\fBMAX_NUM_PLANES\fP][\fBMAX_NUM_LOQS\fP][\fBMAX_NUM_LAYERS\fP])"
.br
.ti -1c
.RI "bool \fBhas_more\fP () const"
.br
.ti -1c
.RI "unsigned \fBparse_block\fP ()"
.br
.ti -1c
.RI "void \fBparse_sequence_config\fP (\fBSequenceConfiguration\fP &sequence_configuration, \fBBitstreamUnpacker\fP &b)"
.br
.ti -1c
.RI "void \fBparse_global_config\fP (\fBGlobalConfiguration\fP &global_configuration, \fBBitstreamUnpacker\fP &b)"
.br
.ti -1c
.RI "void \fBparse_picture_config\fP (\fBPictureConfiguration\fP &picture_configuration, \fBBitstreamUnpacker\fP &b, unsigned num_residual_layers, bool temporal_enabled)"
.br
.ti -1c
.RI "void \fBparse_encoded_data\fP (\fBSignaledConfiguration\fP &dst_configuration, \fBBitstreamUnpacker\fP &b, unsigned num_planes, \fBSurface\fP symbols[\fBMAX_NUM_PLANES\fP][\fBMAX_NUM_LOQS\fP][\fBMAX_NUM_LAYERS\fP])"
.br
.ti -1c
.RI "void \fBparse_encoded_data_tiled\fP (\fBSignaledConfiguration\fP &dst_configuration, \fBBitstreamUnpacker\fP &b, unsigned num_planes, \fBSurface\fP symbols[\fBMAX_NUM_PLANES\fP][\fBMAX_NUM_LOQS\fP][\fBMAX_NUM_LAYERS\fP])"
.br
.ti -1c
.RI "void \fBparse_filler\fP (\fBBitstreamUnpacker\fP &b)"
.br
.ti -1c
.RI "void \fBparse_additional_info\fP (\fBAdditionalInfo\fP &additional_info, \fBBitstreamUnpacker\fP &b)"
.br
.in -1c

Public Member Functions inherited from \fBlctm::Component\fP
.in +1c
.ti -1c
.RI "\fBComponent\fP (const std::string &\fBname\fP)"
.br
.ti -1c
.RI "virtual \fB~Component\fP ()=0"
.br
.ti -1c
.RI "virtual const std::string \fBname\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB51\fP of file \fBDeserializer\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "lctm::Deserializer::Deserializer (const \fBPacket\fP & packet, \fBSignaledConfiguration\fP & dst_configuration, \fBSurface\fP(&) symbols[MAX_NUM_PLANES][MAX_NUM_LOQS][MAX_NUM_LAYERS])"

.PP
Definition at line \fB84\fP of file \fBDeserializer\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "bool lctm::Deserializer::has_more () const"

.PP
Definition at line \fB90\fP of file \fBDeserializer\&.cpp\fP\&.
.SS "void lctm::Deserializer::parse_additional_info (\fBAdditionalInfo\fP & additional_info, \fBBitstreamUnpacker\fP & b)"

.PP
Definition at line \fB1047\fP of file \fBDeserializer\&.cpp\fP\&.
.SS "unsigned lctm::Deserializer::parse_block ()"

.PP
Definition at line \fB94\fP of file \fBDeserializer\&.cpp\fP\&.
.SS "void lctm::Deserializer::parse_encoded_data (\fBSignaledConfiguration\fP & dst_configuration, \fBBitstreamUnpacker\fP & b, unsigned num_planes, \fBSurface\fP symbols[MAX_NUM_PLANES][MAX_NUM_LOQS][MAX_NUM_LAYERS])"

.PP
Definition at line \fB706\fP of file \fBDeserializer\&.cpp\fP\&.
.SS "void lctm::Deserializer::parse_encoded_data_tiled (\fBSignaledConfiguration\fP & dst_configuration, \fBBitstreamUnpacker\fP & b, unsigned num_planes, \fBSurface\fP symbols[MAX_NUM_PLANES][MAX_NUM_LOQS][MAX_NUM_LAYERS])"

.PP
Definition at line \fB837\fP of file \fBDeserializer\&.cpp\fP\&.
.SS "void lctm::Deserializer::parse_filler (\fBBitstreamUnpacker\fP & b)"

.PP
Definition at line \fB1061\fP of file \fBDeserializer\&.cpp\fP\&.
.SS "void lctm::Deserializer::parse_global_config (\fBGlobalConfiguration\fP & global_configuration, \fBBitstreamUnpacker\fP & b)"

.PP
Definition at line \fB211\fP of file \fBDeserializer\&.cpp\fP\&.
.SS "void lctm::Deserializer::parse_picture_config (\fBPictureConfiguration\fP & picture_configuration, \fBBitstreamUnpacker\fP & b, unsigned num_residual_layers, bool temporal_enabled)"

.PP
Definition at line \fB544\fP of file \fBDeserializer\&.cpp\fP\&.
.SS "void lctm::Deserializer::parse_sequence_config (\fBSequenceConfiguration\fP & sequence_configuration, \fBBitstreamUnpacker\fP & b)"

.PP
Definition at line \fB168\fP of file \fBDeserializer\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
