.TH "lctm::BaseVideoDecoderExternal" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lctm::BaseVideoDecoderExternal
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBlctm::BaseVideoDecoder\fP\&.
.PP
Inherited by \fBlctm::BaseVideoDecoderExternalAVC\fP, \fBlctm::BaseVideoDecoderExternalEVC\fP, \fBlctm::BaseVideoDecoderExternalHEVC\fP, \fBlctm::BaseVideoDecoderExternalVVC\fP, and \fBlctm::BaseVideoDecoderExternalYUV\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBaseVideoDecoderExternal\fP (\fBBaseVideoDecoder::Output\fP &output, \fBEncapsulation\fP encapsulation, const std::string &prepared_yuv_file_name, bool keep_base)"
.br
.ti -1c
.RI "\fB~BaseVideoDecoderExternal\fP () override"
.br
.ti -1c
.RI "void \fBstart\fP () override"
.br
.ti -1c
.RI "void \fBstop\fP () override"
.br
.ti -1c
.RI "void \fBpush_au\fP (const uint8_t *data, size_t data_size, uint64_t pts, bool is_base_idr, int iPictureType) override"
.br
.in -1c

Public Member Functions inherited from \fBlctm::BaseVideoDecoder\fP
.in +1c
.ti -1c
.RI "\fBPacket\fP \fBrbsp_encapsulate\fP (const \fBPacket\fP &src) const"
.br
.ti -1c
.RI "virtual \fB~BaseVideoDecoder\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual \fBBaseCoding\fP \fBbase_coding\fP () const =0"
.br
.ti -1c
.RI "virtual bool \fBrun_decoder\fP (const string &input, const string &output) const =0"
.br
.ti -1c
.RI "void \fBpush_es\fP (const uint8_t *data, size_t data_size, uint64_t pts, bool is_base_idr)"
.br
.ti -1c
.RI "void \fBflush\fP ()"
.br
.ti -1c
.RI "virtual void \fBStatisticsComputation\fP () override"
.br
.in -1c

Protected Member Functions inherited from \fBlctm::BaseVideoDecoder\fP
.in +1c
.ti -1c
.RI "\fBBaseVideoDecoder\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBOutput\fP & \fBoutput_\fP"
.br
.ti -1c
.RI "\fBEncapsulation\fP \fBencapsulation_\fP"
.br
.ti -1c
.RI "const std::string \fBprepared_yuv_file_name_\fP"
.br
.ti -1c
.RI "vector< uint8_t > \fBbuffer_\fP"
.br
.ti -1c
.RI "string \fBes_file_name_\fP"
.br
.ti -1c
.RI "FILE * \fBes_file_\fP = nullptr"
.br
.ti -1c
.RI "string \fByuv_file_name_\fP"
.br
.ti -1c
.RI "bool \fBkeep_base_\fP"
.br
.ti -1c
.RI "priority_queue< PssPacket, vector< PssPacket >, BufferCompare > \fBenhancement_queue_\fP"
.br
.ti -1c
.RI "vector< PssPacket > \fBenhancement_vector_\fP"
.br
.ti -1c
.RI "uint32_t \fBbase_buffer_size_\fP = 0"
.br
.ti -1c
.RI "uint32_t \fBbase_width_\fP = 0"
.br
.ti -1c
.RI "uint32_t \fBbase_height_\fP = 0"
.br
.ti -1c
.RI "uint32_t \fBbase_bit_depth_\fP = 0"
.br
.in -1c
.SS "Additional Inherited Members"


Public Types inherited from \fBlctm::BaseVideoDecoder\fP
.in +1c
.ti -1c
.RI "typedef struct \fBCodecImage\fP \fBBasePicture\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB114\fP of file \fBBaseVideoDecoder\&.cpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "lctm::BaseVideoDecoderExternal::BaseVideoDecoderExternal (\fBBaseVideoDecoder::Output\fP & output, \fBEncapsulation\fP encapsulation, const std::string & prepared_yuv_file_name, bool keep_base)"

.PP
Definition at line \fB166\fP of file \fBBaseVideoDecoder\&.cpp\fP\&.
.SS "lctm::BaseVideoDecoderExternal::~BaseVideoDecoderExternal ()\fC [override]\fP"

.PP
Definition at line \fB170\fP of file \fBBaseVideoDecoder\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual \fBBaseCoding\fP lctm::BaseVideoDecoderExternal::base_coding () const\fC [protected]\fP, \fC [pure virtual]\fP"

.PP
Implemented in \fBlctm::BaseVideoDecoderExternalAVC\fP, \fBlctm::BaseVideoDecoderExternalHEVC\fP, \fBlctm::BaseVideoDecoderExternalVVC\fP, \fBlctm::BaseVideoDecoderExternalEVC\fP, and \fBlctm::BaseVideoDecoderExternalYUV\fP\&.
.SS "void lctm::BaseVideoDecoderExternal::flush ()\fC [protected]\fP"

.PP
Definition at line \fB238\fP of file \fBBaseVideoDecoder\&.cpp\fP\&.
.SS "void lctm::BaseVideoDecoderExternal::push_au (const uint8_t * data, size_t data_size, uint64_t pts, bool is_base_idr, int iPictureType)\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBlctm::BaseVideoDecoder\fP\&.
.PP
Definition at line \fB193\fP of file \fBBaseVideoDecoder\&.cpp\fP\&.
.SS "void lctm::BaseVideoDecoderExternal::push_es (const uint8_t * data, size_t data_size, uint64_t pts, bool is_base_idr)\fC [protected]\fP"

.PP
Definition at line \fB227\fP of file \fBBaseVideoDecoder\&.cpp\fP\&.
.SS "virtual bool lctm::BaseVideoDecoderExternal::run_decoder (const string & input, const string & output) const\fC [protected]\fP, \fC [pure virtual]\fP"

.PP
Implemented in \fBlctm::BaseVideoDecoderExternalAVC\fP, \fBlctm::BaseVideoDecoderExternalHEVC\fP, \fBlctm::BaseVideoDecoderExternalVVC\fP, \fBlctm::BaseVideoDecoderExternalEVC\fP, and \fBlctm::BaseVideoDecoderExternalYUV\fP\&.
.SS "void lctm::BaseVideoDecoderExternal::start ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBlctm::BaseVideoDecoder\fP\&.
.PP
Definition at line \fB172\fP of file \fBBaseVideoDecoder\&.cpp\fP\&.
.SS "void lctm::BaseVideoDecoderExternal::StatisticsComputation ()\fC [override]\fP, \fC [protected]\fP, \fC [virtual]\fP"

.PP
Implements \fBlctm::BaseVideoDecoder\fP\&.
.PP
Reimplemented in \fBlctm::BaseVideoDecoderExternalAVC\fP, \fBlctm::BaseVideoDecoderExternalHEVC\fP, \fBlctm::BaseVideoDecoderExternalVVC\fP, \fBlctm::BaseVideoDecoderExternalEVC\fP, and \fBlctm::BaseVideoDecoderExternalYUV\fP\&.
.PP
Definition at line \fB419\fP of file \fBBaseVideoDecoder\&.cpp\fP\&.
.SS "void lctm::BaseVideoDecoderExternal::stop ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBlctm::BaseVideoDecoder\fP\&.
.PP
Definition at line \fB409\fP of file \fBBaseVideoDecoder\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "uint32_t lctm::BaseVideoDecoderExternal::base_bit_depth_ = 0\fC [protected]\fP"

.PP
Definition at line \fB163\fP of file \fBBaseVideoDecoder\&.cpp\fP\&.
.SS "uint32_t lctm::BaseVideoDecoderExternal::base_buffer_size_ = 0\fC [protected]\fP"

.PP
Definition at line \fB160\fP of file \fBBaseVideoDecoder\&.cpp\fP\&.
.SS "uint32_t lctm::BaseVideoDecoderExternal::base_height_ = 0\fC [protected]\fP"

.PP
Definition at line \fB162\fP of file \fBBaseVideoDecoder\&.cpp\fP\&.
.SS "uint32_t lctm::BaseVideoDecoderExternal::base_width_ = 0\fC [protected]\fP"

.PP
Definition at line \fB161\fP of file \fBBaseVideoDecoder\&.cpp\fP\&.
.SS "vector<uint8_t> lctm::BaseVideoDecoderExternal::buffer_\fC [protected]\fP"

.PP
Definition at line \fB143\fP of file \fBBaseVideoDecoder\&.cpp\fP\&.
.SS "\fBEncapsulation\fP lctm::BaseVideoDecoderExternal::encapsulation_\fC [protected]\fP"

.PP
Definition at line \fB137\fP of file \fBBaseVideoDecoder\&.cpp\fP\&.
.SS "priority_queue<PssPacket, vector<PssPacket>, BufferCompare> lctm::BaseVideoDecoderExternal::enhancement_queue_\fC [protected]\fP"

.PP
Definition at line \fB154\fP of file \fBBaseVideoDecoder\&.cpp\fP\&.
.SS "vector<PssPacket> lctm::BaseVideoDecoderExternal::enhancement_vector_\fC [protected]\fP"

.PP
Definition at line \fB155\fP of file \fBBaseVideoDecoder\&.cpp\fP\&.
.SS "FILE* lctm::BaseVideoDecoderExternal::es_file_ = nullptr\fC [protected]\fP"

.PP
Definition at line \fB146\fP of file \fBBaseVideoDecoder\&.cpp\fP\&.
.SS "string lctm::BaseVideoDecoderExternal::es_file_name_\fC [protected]\fP"

.PP
Definition at line \fB145\fP of file \fBBaseVideoDecoder\&.cpp\fP\&.
.SS "bool lctm::BaseVideoDecoderExternal::keep_base_\fC [protected]\fP"

.PP
Definition at line \fB151\fP of file \fBBaseVideoDecoder\&.cpp\fP\&.
.SS "\fBOutput\fP& lctm::BaseVideoDecoderExternal::output_\fC [protected]\fP"

.PP
Definition at line \fB134\fP of file \fBBaseVideoDecoder\&.cpp\fP\&.
.SS "const std::string lctm::BaseVideoDecoderExternal::prepared_yuv_file_name_\fC [protected]\fP"

.PP
Definition at line \fB140\fP of file \fBBaseVideoDecoder\&.cpp\fP\&.
.SS "string lctm::BaseVideoDecoderExternal::yuv_file_name_\fC [protected]\fP"

.PP
Definition at line \fB148\fP of file \fBBaseVideoDecoder\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
