.TH "lctm::TransformDDS" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lctm::TransformDDS
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <TransformDDS\&.hpp>\fP
.PP
Inherits \fBlctm::Component\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTransformDDS\fP ()"
.br
.ti -1c
.RI "void \fBprocess\fP (const \fBSurface\fP &src_residuals, \fBEncodingMode\fP mode, \fBSurface\fP dst_layers[])"
.br
.in -1c

Public Member Functions inherited from \fBlctm::Component\fP
.in +1c
.ti -1c
.RI "\fBComponent\fP (const std::string &\fBname\fP)"
.br
.ti -1c
.RI "virtual \fB~Component\fP ()=0"
.br
.ti -1c
.RI "virtual const std::string \fBname\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB46\fP of file \fBTransformDDS\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "lctm::TransformDDS::TransformDDS ()\fC [inline]\fP"

.PP
Definition at line \fB48\fP of file \fBTransformDDS\&.hpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void lctm::TransformDDS::process (const \fBSurface\fP & src_residuals, \fBEncodingMode\fP mode, \fBSurface\fP dst_layers[])"

.PP
Definition at line \fB44\fP of file \fBTransformDDS\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
