.TH "lctm::UnregisteredSEI" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lctm::UnregisteredSEI
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "\fBstatic\fP void \fBextract_enhancement_sei\fP (const uint8_t *data, size_t size, bool emulation_prevention, uint64_t pts, bool is_base_idr, std::function< void(const \fBPacket\fP &pkt, const bool \fBis_lcevc_idr\fP)> callback)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB52\fP of file \fBScanEnhancement\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void lctm::UnregisteredSEI::extract_enhancement_sei (const uint8_t * data, size_t size, bool emulation_prevention, uint64_t pts, bool is_base_idr, std::function< void(const \fBPacket\fP &pkt, const bool \fBis_lcevc_idr\fP)> callback)\fC [static]\fP"

.PP
Definition at line \fB277\fP of file \fBScanEnhancement\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
