.TH "lctm::StaticResiduals" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lctm::StaticResiduals
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <PriorityMap\&.hpp>\fP
.PP
Inherits \fBlctm::Component\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBStaticResiduals\fP ()"
.br
.ti -1c
.RI "void \fBprocess\fP (\fBSurface\fP src_coeffs[], \fBSurface\fP dst_coeffs[], const \fBSurface\fP &pixel_sad, unsigned num_layers, unsigned step_width, unsigned sad_threshold, unsigned sad_coeff_threshold)"
.br
.in -1c

Public Member Functions inherited from \fBlctm::Component\fP
.in +1c
.ti -1c
.RI "\fBComponent\fP (const std::string &\fBname\fP)"
.br
.ti -1c
.RI "virtual \fB~Component\fP ()=0"
.br
.ti -1c
.RI "virtual const std::string \fBname\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB121\fP of file \fBPriorityMap\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "lctm::StaticResiduals::StaticResiduals ()\fC [inline]\fP"

.PP
Definition at line \fB123\fP of file \fBPriorityMap\&.hpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void lctm::StaticResiduals::process (\fBSurface\fP src_coeffs[], \fBSurface\fP dst_coeffs[], const \fBSurface\fP & pixel_sad, unsigned num_layers, unsigned step_width, unsigned sad_threshold, unsigned sad_coeff_threshold)"

.PP
Definition at line \fB686\fP of file \fBPriorityMap\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
