.TH "lctm::SeiUserDataRegisteredItutT35" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lctm::SeiUserDataRegisteredItutT35
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SignaledConfiguration\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned \fBitu_t_t35_country_code\fP"
.br
.ti -1c
.RI "unsigned \fBitu_t_t35_country_code_extension_byte\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB168\fP of file \fBSignaledConfiguration\&.hpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "unsigned lctm::SeiUserDataRegisteredItutT35::itu_t_t35_country_code"

.PP
Definition at line \fB169\fP of file \fBSignaledConfiguration\&.hpp\fP\&.
.SS "unsigned lctm::SeiUserDataRegisteredItutT35::itu_t_t35_country_code_extension_byte"

.PP
Definition at line \fB170\fP of file \fBSignaledConfiguration\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
