.TH "lctm::FileEncoderImpl" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lctm::FileEncoderImpl
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBlctm::FileEncoder\fP\&.
.PP
Inherited by \fBlctm::FileEncoderImplAVC\fP, \fBlctm::FileEncoderImplEVC\fP, \fBlctm::FileEncoderImplHEVC\fP, \fBlctm::FileEncoderImplVVC\fP, and \fBlctm::FileEncoderImplX265\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBRegisteredSEI\fP"
.br
.ti -1c
.RI "struct \fBUnregisteredSEI\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFileEncoderImpl\fP (const \fBImageDescription\fP &image_description, unsigned fps, const \fBParameters\fP &parameters)"
.br
.ti -1c
.RI "\fB~FileEncoderImpl\fP () override"
.br
.ti -1c
.RI "void \fBencode_file\fP (const string &src_filename, const string &dst_filename, const string &dst_filename_yuv, unsigned limit) override"
.br
.ti -1c
.RI "void \fBencode_file_with_decoder\fP (const string &src_filename, const string base_filename, const string &dst_filename, const string &dst_filename_yuv, unsigned limit) override"
.br
.ti -1c
.RI "void \fBencode_file_with_base\fP (const string &src_filename, const string base_filename, const string base_recon_filename, const string &dst_filename, const string &dst_filename_yuv, unsigned limit) override"
.br
.ti -1c
.RI "void \fBdownsample_file\fP (const string &src_filename, const string &dst_filename, unsigned limit) override"
.br
.ti -1c
.RI "void \fBupsample_file\fP (const string &src_filename, const string &dst_filename, unsigned limit) override"
.br
.ti -1c
.RI "virtual \fBBaseDecoder::Codec\fP \fBes_file_type\fP () const =0"
.br
.ti -1c
.RI "virtual \fBBaseCoding\fP \fBbase_coding\fP () const =0"
.br
.in -1c

Public Member Functions inherited from \fBlctm::FileEncoder\fP
.in +1c
.ti -1c
.RI "virtual void \fBencode_file\fP (const std::string &src_filename, const std::string &dst_filename, const std::string &dst_filename_yuv, unsigned limit=UINT_MAX)=0"
.br
.ti -1c
.RI "virtual void \fBencode_file_with_decoder\fP (const std::string &src_filename, const std::string base_filename, const std::string &dst_filename, const std::string &dst_filename_yuv, unsigned limit=UINT_MAX)=0"
.br
.ti -1c
.RI "virtual void \fBencode_file_with_base\fP (const std::string &src_filename, const std::string base_filename, const std::string base_recon_filename, const std::string &dst_filename, const std::string &dst_filename_yuv, unsigned limit=UINT_MAX)=0"
.br
.ti -1c
.RI "virtual void \fBdownsample_file\fP (const std::string &src_filename, const std::string &dst_filename, unsigned limit=UINT_MAX)=0"
.br
.ti -1c
.RI "virtual void \fBupsample_file\fP (const std::string &src_filename, const std::string &dst_filename, unsigned limit=UINT_MAX)=0"
.br
.ti -1c
.RI "virtual \fB~FileEncoder\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBencode\fP (const \fBYUVReader\fP &src_file, const \fBYUVReader\fP &recon_file, FILE *output_file, \fBESFile\fP &es_file, const string &dst_filename_yuv, unsigned limit)"
.br
.ti -1c
.RI "bool \fBread_au\fP (\fBESFile\fP &es_file, \fBESFile::AccessUnit\fP &au)"
.br
.ti -1c
.RI "\fBPacket\fP \fBrbsp_encapsulate\fP (const \fBPacket\fP &src) const"
.br
.ti -1c
.RI "void \fBinitialize_encoder\fP (const \fBYUVReader\fP &src_file, unsigned limit)"
.br
.ti -1c
.RI "\fBPacket\fP \fBnal_payload\fP (const \fBPacket\fP &enhancement_data) const"
.br
.ti -1c
.RI "virtual int \fBadd_enhancement\fP (\fBESFile::AccessUnit\fP &au, bool is_idr, const \fBPacket\fP &payload)=0"
.br
.ti -1c
.RI "\fBESFile::NalUnit\fP \fBbuild_nalu\fP (bool is_idr, const \fBPacket\fP &payload) const"
.br
.ti -1c
.RI "unsigned \fBintra_period\fP () const"
.br
.ti -1c
.RI "virtual bool \fBrun_base_encoder\fP (const string &input, const string &stream_output, const string &recon_output, unsigned frame_count) const =0"
.br
.ti -1c
.RI "virtual bool \fBrun_base_decoder\fP (const string &input, const string &output)=0"
.br
.in -1c

Protected Member Functions inherited from \fBlctm::FileEncoder\fP
.in +1c
.ti -1c
.RI "\fBFileEncoder\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "const unsigned \fBfps_\fP"
.br
.ti -1c
.RI "const \fBParameters\fP \fBparameters_\fP"
.br
.ti -1c
.RI "const \fBScalingMode\fP \fBscaling_mode_\fP [\fBMAX_NUM_LOQS\fP]"
.br
.ti -1c
.RI "const \fBDownsample\fP \fBdownsample_luma_\fP"
.br
.ti -1c
.RI "const \fBDownsample\fP \fBdownsample_chroma_\fP"
.br
.ti -1c
.RI "const \fBUpsample\fP \fBupsample_\fP"
.br
.ti -1c
.RI "unsigned \fBupsampling_coefficients_\fP [4]"
.br
.ti -1c
.RI "const \fBEncapsulation\fP \fBencapsulation_\fP"
.br
.ti -1c
.RI "\fBEncoder\fP \fBencoder_\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB98\fP of file \fBFileEncoder\&.cpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "lctm::FileEncoderImpl::FileEncoderImpl (const \fBImageDescription\fP & image_description, unsigned fps, const \fBParameters\fP & parameters)"

.PP
Definition at line \fB169\fP of file \fBFileEncoder\&.cpp\fP\&.
.SS "lctm::FileEncoderImpl::~FileEncoderImpl ()\fC [override]\fP"

.PP
Definition at line \fB181\fP of file \fBFileEncoder\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual int lctm::FileEncoderImpl::add_enhancement (\fBESFile::AccessUnit\fP & au, bool is_idr, const \fBPacket\fP & payload)\fC [protected]\fP, \fC [pure virtual]\fP"

.PP
Implemented in \fBlctm::FileEncoderImplAVC\fP, \fBlctm::FileEncoderImplHEVC\fP, \fBlctm::FileEncoderImplX265\fP, \fBlctm::FileEncoderImplVVC\fP, and \fBlctm::FileEncoderImplEVC\fP\&.
.SS "virtual \fBBaseCoding\fP lctm::FileEncoderImpl::base_coding () const\fC [pure virtual]\fP"

.PP
Implemented in \fBlctm::FileEncoderImplAVC\fP, \fBlctm::FileEncoderImplHEVC\fP, \fBlctm::FileEncoderImplX265\fP, \fBlctm::FileEncoderImplVVC\fP, and \fBlctm::FileEncoderImplEVC\fP\&.
.SS "\fBESFile::NalUnit\fP lctm::FileEncoderImpl::build_nalu (bool is_idr, const \fBPacket\fP & payload) const\fC [protected]\fP"

.PP
Definition at line \fB610\fP of file \fBFileEncoder\&.cpp\fP\&.
.SS "void lctm::FileEncoderImpl::downsample_file (const string & src_filename, const string & dst_filename, unsigned limit)\fC [override]\fP"

.PP
Definition at line \fB1211\fP of file \fBFileEncoder\&.cpp\fP\&.
.SS "void lctm::FileEncoderImpl::encode (const \fBYUVReader\fP & src_file, const \fBYUVReader\fP & recon_file, FILE * output_file, \fBESFile\fP & es_file, const string & dst_filename_yuv, unsigned limit)\fC [protected]\fP"

.PP
Definition at line \fB371\fP of file \fBFileEncoder\&.cpp\fP\&.
.SS "void lctm::FileEncoderImpl::encode_file (const string & src_filename, const string & dst_filename, const string & dst_filename_yuv, unsigned limit)\fC [override]\fP"

.PP
Definition at line \fB185\fP of file \fBFileEncoder\&.cpp\fP\&.
.SS "void lctm::FileEncoderImpl::encode_file_with_base (const string & src_filename, const string base_filename, const string base_recon_filename, const string & dst_filename, const string & dst_filename_yuv, unsigned limit)\fC [override]\fP"

.PP
Definition at line \fB338\fP of file \fBFileEncoder\&.cpp\fP\&.
.SS "void lctm::FileEncoderImpl::encode_file_with_decoder (const string & src_filename, const string base_filename, const string & dst_filename, const string & dst_filename_yuv, unsigned limit)\fC [override]\fP"

.PP
Definition at line \fB259\fP of file \fBFileEncoder\&.cpp\fP\&.
.SS "virtual \fBBaseDecoder::Codec\fP lctm::FileEncoderImpl::es_file_type () const\fC [pure virtual]\fP"

.PP
Implemented in \fBlctm::FileEncoderImplAVC\fP, \fBlctm::FileEncoderImplHEVC\fP, \fBlctm::FileEncoderImplX265\fP, \fBlctm::FileEncoderImplVVC\fP, and \fBlctm::FileEncoderImplEVC\fP\&.
.SS "void lctm::FileEncoderImpl::initialize_encoder (const \fBYUVReader\fP & src_file, unsigned limit)\fC [protected]\fP"

.PP
Definition at line \fB647\fP of file \fBFileEncoder\&.cpp\fP\&.
.SS "unsigned lctm::FileEncoderImpl::intra_period () const\fC [protected]\fP"

.PP
Definition at line \fB625\fP of file \fBFileEncoder\&.cpp\fP\&.
.SS "\fBPacket\fP lctm::FileEncoderImpl::nal_payload (const \fBPacket\fP & enhancement_data) const\fC [protected]\fP"

.PP
Definition at line \fB599\fP of file \fBFileEncoder\&.cpp\fP\&.
.SS "\fBPacket\fP lctm::FileEncoderImpl::rbsp_encapsulate (const \fBPacket\fP & src) const\fC [protected]\fP"

.PP
Definition at line \fB519\fP of file \fBFileEncoder\&.cpp\fP\&.
.SS "bool lctm::FileEncoderImpl::read_au (\fBESFile\fP & es_file, \fBESFile::AccessUnit\fP & au)\fC [protected]\fP"

.PP
Definition at line \fB303\fP of file \fBFileEncoder\&.cpp\fP\&.
.SS "virtual bool lctm::FileEncoderImpl::run_base_decoder (const string & input, const string & output)\fC [protected]\fP, \fC [pure virtual]\fP"

.PP
Implemented in \fBlctm::FileEncoderImplAVC\fP, \fBlctm::FileEncoderImplHEVC\fP, \fBlctm::FileEncoderImplX265\fP, \fBlctm::FileEncoderImplVVC\fP, and \fBlctm::FileEncoderImplEVC\fP\&.
.SS "virtual bool lctm::FileEncoderImpl::run_base_encoder (const string & input, const string & stream_output, const string & recon_output, unsigned frame_count) const\fC [protected]\fP, \fC [pure virtual]\fP"

.PP
Implemented in \fBlctm::FileEncoderImplAVC\fP, \fBlctm::FileEncoderImplHEVC\fP, \fBlctm::FileEncoderImplX265\fP, \fBlctm::FileEncoderImplVVC\fP, and \fBlctm::FileEncoderImplEVC\fP\&.
.SS "void lctm::FileEncoderImpl::upsample_file (const string & src_filename, const string & dst_filename, unsigned limit)\fC [override]\fP"

.PP
Definition at line \fB1229\fP of file \fBFileEncoder\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "const \fBDownsample\fP lctm::FileEncoderImpl::downsample_chroma_\fC [protected]\fP"

.PP
Definition at line \fB160\fP of file \fBFileEncoder\&.cpp\fP\&.
.SS "const \fBDownsample\fP lctm::FileEncoderImpl::downsample_luma_\fC [protected]\fP"

.PP
Definition at line \fB159\fP of file \fBFileEncoder\&.cpp\fP\&.
.SS "const \fBEncapsulation\fP lctm::FileEncoderImpl::encapsulation_\fC [protected]\fP"

.PP
Definition at line \fB164\fP of file \fBFileEncoder\&.cpp\fP\&.
.SS "\fBEncoder\fP lctm::FileEncoderImpl::encoder_\fC [protected]\fP"

.PP
Definition at line \fB166\fP of file \fBFileEncoder\&.cpp\fP\&.
.SS "const unsigned lctm::FileEncoderImpl::fps_\fC [protected]\fP"

.PP
Definition at line \fB155\fP of file \fBFileEncoder\&.cpp\fP\&.
.SS "const \fBParameters\fP lctm::FileEncoderImpl::parameters_\fC [protected]\fP"

.PP
Definition at line \fB156\fP of file \fBFileEncoder\&.cpp\fP\&.
.SS "const \fBScalingMode\fP lctm::FileEncoderImpl::scaling_mode_[\fBMAX_NUM_LOQS\fP]\fC [protected]\fP"

.PP
Definition at line \fB158\fP of file \fBFileEncoder\&.cpp\fP\&.
.SS "const \fBUpsample\fP lctm::FileEncoderImpl::upsample_\fC [protected]\fP"

.PP
Definition at line \fB161\fP of file \fBFileEncoder\&.cpp\fP\&.
.SS "unsigned lctm::FileEncoderImpl::upsampling_coefficients_[4]\fC [protected]\fP"

.PP
Definition at line \fB162\fP of file \fBFileEncoder\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
