.TH "lctm::PredictedResidualSum_1D" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lctm::PredictedResidualSum_1D
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <PredictedResidual\&.hpp>\fP
.PP
Inherits \fBlctm::Component\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPredictedResidualSum_1D\fP ()"
.br
.ti -1c
.RI "\fBSurface\fP \fBprocess\fP (const \fBSurface\fP &src_plane)"
.br
.in -1c

Public Member Functions inherited from \fBlctm::Component\fP
.in +1c
.ti -1c
.RI "\fBComponent\fP (const std::string &\fBname\fP)"
.br
.ti -1c
.RI "virtual \fB~Component\fP ()=0"
.br
.ti -1c
.RI "virtual const std::string \fBname\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB64\fP of file \fBPredictedResidual\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "lctm::PredictedResidualSum_1D::PredictedResidualSum_1D ()\fC [inline]\fP"

.PP
Definition at line \fB66\fP of file \fBPredictedResidual\&.hpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBSurface\fP lctm::PredictedResidualSum_1D::process (const \fBSurface\fP & src_plane)"

.PP
Definition at line \fB87\fP of file \fBPredictedResidual\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
