.TH "lctm::Dithering" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lctm::Dithering
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Dithering\&.hpp>\fP
.PP
Inherits \fBlctm::Component\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDithering\fP ()"
.br
.ti -1c
.RI "void \fBmake_buffer\fP (int streangth, int enhancement_depth, bool fixed_seed)"
.br
.ti -1c
.RI "bool \fBgetInitialised\fP ()"
.br
.ti -1c
.RI "void \fBsetInitialised\fP (bool bValue)"
.br
.ti -1c
.RI "\fBSurface\fP \fBprocess\fP (\fBSurface\fP &src_plane, unsigned block_size)"
.br
.in -1c

Public Member Functions inherited from \fBlctm::Component\fP
.in +1c
.ti -1c
.RI "\fBComponent\fP (const std::string &\fBname\fP)"
.br
.ti -1c
.RI "virtual \fB~Component\fP ()=0"
.br
.ti -1c
.RI "virtual const std::string \fBname\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB48\fP of file \fBDithering\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "lctm::Dithering::Dithering ()\fC [inline]\fP"

.PP
Definition at line \fB54\fP of file \fBDithering\&.hpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "bool lctm::Dithering::getInitialised ()\fC [inline]\fP"

.PP
Definition at line \fB58\fP of file \fBDithering\&.hpp\fP\&.
.SS "void lctm::Dithering::make_buffer (int streangth, int enhancement_depth, bool fixed_seed)"

.PP
Definition at line \fB56\fP of file \fBDithering\&.cpp\fP\&.
.SS "\fBSurface\fP lctm::Dithering::process (\fBSurface\fP & src_plane, unsigned block_size)"

.PP
Definition at line \fB66\fP of file \fBDithering\&.cpp\fP\&.
.SS "void lctm::Dithering::setInitialised (bool bValue)\fC [inline]\fP"

.PP
Definition at line \fB59\fP of file \fBDithering\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
