.TH "deps/base_vvc/minimum_VTM/source/Lib/libmd5/libmd5.h" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deps/base_vvc/minimum_VTM/source/Lib/libmd5/libmd5.h
.SH SYNOPSIS
.br
.PP
\fC#include <stdint\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fB_context_md5_t\fP"
.br
.in -1c
.in +1c
.ti -1c
.RI "typedef struct \fB_context_md5_t\fP \fBcontext_md5_t\fP"
.br
.ti -1c
.RI "void \fBMD5Init\fP (\fBcontext_md5_t\fP *ctx)"
.br
.ti -1c
.RI "void \fBMD5Update\fP (\fBcontext_md5_t\fP *ctx, unsigned char *buf, unsigned len)"
.br
.ti -1c
.RI "void \fBMD5Final\fP (unsigned char digest[16], \fBcontext_md5_t\fP *ctx)"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fB_context_md5_t\fP \fBcontext_md5_t\fP"

.SH "Function Documentation"
.PP 
.SS "void MD5Final (unsigned char digest[16], \fBcontext_md5_t\fP * ctx)"

.SS "void MD5Init (\fBcontext_md5_t\fP * ctx)"

.SS "void MD5Update (\fBcontext_md5_t\fP * ctx, unsigned char * buf, unsigned len)"

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
