.TH "LoopFilter" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LoopFilter \- deblocking filter class  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <LoopFilter\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "PelStorage & \fBgetDbEncPicYuvBuffer\fP ()"
.br
.ti -1c
.RI "void \fBsetEnc\fP (bool b)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "\fBstatic\fP int \fBgetBeta\fP (const int qp)"
.br
.in -1c
.in +1c
.ti -1c
.RI "void \fBxDeblockCU\fP (CodingUnit &cu, const DeblockEdgeDir edgeDir)"
.br
.RI "CU-level deblocking function\&. "
.ti -1c
.RI "void \fBinitEncPicYuvBuffer\fP (ChromaFormat chromaFormat, const Size &size, const unsigned maxCUSize)"
.br
.ti -1c
.RI "void \fBcreate\fP (const unsigned uiMaxCUDepth)"
.br
.ti -1c
.RI "void \fBdestroy\fP ()"
.br
.ti -1c
.RI "void \fBloopFilterPic\fP (CodingStructure &cs)"
.br
.RI "picture-level deblocking filter "
.ti -1c
.RI "void \fBresetFilterLengths\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
deblocking filter class 
.PP
Definition at line \fB55\fP of file \fBLoopFilter\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "LoopFilter::LoopFilter ()"

.PP
Definition at line \fB95\fP of file \fBLoopFilter\&.cpp\fP\&.
.SS "LoopFilter::~LoopFilter ()"

.PP
Definition at line \fB99\fP of file \fBLoopFilter\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void LoopFilter::create (const unsigned uiMaxCUDepth)"

.PP
Definition at line \fB106\fP of file \fBLoopFilter\&.cpp\fP\&.
.SS "void LoopFilter::destroy ()"

.PP
Definition at line \fB125\fP of file \fBLoopFilter\&.cpp\fP\&.
.SS "\fBstatic\fP int LoopFilter::getBeta (const int qp)\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line \fB126\fP of file \fBLoopFilter\&.h\fP\&.
.SS "PelStorage & LoopFilter::getDbEncPicYuvBuffer ()\fC [inline]\fP"

.PP
Definition at line \fB116\fP of file \fBLoopFilter\&.h\fP\&.
.SS "void LoopFilter::initEncPicYuvBuffer (ChromaFormat chromaFormat, const Size & size, const unsigned maxCUSize)"

.PP
Definition at line \fB118\fP of file \fBLoopFilter\&.cpp\fP\&.
.SS "void LoopFilter::loopFilterPic (CodingStructure & cs)"

.PP
picture-level deblocking filter 
.IP "\(bu" 2
call deblocking function for every CU
.PP
\fBParameters\fP
.RS 4
\fIpcPic\fP picture class (Pic) pointer 
.RE
.PP

.PP
Definition at line \fB140\fP of file \fBLoopFilter\&.cpp\fP\&.
.SS "void LoopFilter::resetFilterLengths ()"

.PP
Definition at line \fB245\fP of file \fBLoopFilter\&.cpp\fP\&.
.SS "void LoopFilter::setEnc (bool b)\fC [inline]\fP"

.PP
Definition at line \fB117\fP of file \fBLoopFilter\&.h\fP\&.
.SS "void LoopFilter::xDeblockCU (CodingUnit & cu, const DeblockEdgeDir edgeDir)"

.PP
CU-level deblocking function\&. Deblocking filter process in CU-based (the same function as conventional's)
.PP
\fBParameters\fP
.RS 4
\fIcu\fP the CU to be deblocked 
.br
\fIedgeDir\fP the direction of the edge in block boundary (horizontal/vertical), which is added newly 
.RE
.PP

.PP
Definition at line \fB266\fP of file \fBLoopFilter\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
