.TH "deps/base_vvc/minimum_VTM/source/Lib/CommonLib/LoopFilter.cpp" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deps/base_vvc/minimum_VTM/source/Lib/CommonLib/LoopFilter.cpp \- deblocking filter  

.SH SYNOPSIS
.br
.PP
\fC#include 'LoopFilter\&.h'\fP
.br
\fC#include 'Slice\&.h'\fP
.br
\fC#include 'Mv\&.h'\fP
.br
\fC#include 'Unit\&.h'\fP
.br
\fC#include 'UnitTools\&.h'\fP
.br
\fC#include 'UnitPartitioner\&.h'\fP
.br
\fC#include 'dtrace_codingstruct\&.h'\fP
.br
\fC#include 'dtrace_buffer\&.h'\fP
.br

.in +1c
.ti -1c
.RI "#define \fBDEBLOCK_SMALLEST_BLOCK\fP   8"
.br
.ti -1c
.RI "#define \fBDEFAULT_INTRA_TC_OFFSET\fP   2"
.br
.RI "Default intra TC offset\&. "
.in -1c
.SH "Detailed Description"
.PP 
deblocking filter 


.PP
Definition in file \fBLoopFilter\&.cpp\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define DEBLOCK_SMALLEST_BLOCK   8"

.PP
Definition at line \fB54\fP of file \fBLoopFilter\&.cpp\fP\&.
.SS "#define DEFAULT_INTRA_TC_OFFSET   2"

.PP
Default intra TC offset\&. 
.PP
Definition at line \fB55\fP of file \fBLoopFilter\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
