.TH "deps/base_vvc/minimum_VTM/source/Lib/CommonLib/LoopFilter.h" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deps/base_vvc/minimum_VTM/source/Lib/CommonLib/LoopFilter.h \- deblocking filter (header)  

.SH SYNOPSIS
.br
.PP
\fC#include 'CommonDef\&.h'\fP
.br
\fC#include 'Unit\&.h'\fP
.br
\fC#include 'Picture\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBLoopFilter\fP"
.br
.RI "deblocking filter class "
.in -1c
.SS "Macros"

.PP
.RI "\fB\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "#define \fBDEBLOCK_SMALLEST_BLOCK\fP   8"
.br
.in -1c
.in -1c
.SH "Detailed Description"
.PP 
deblocking filter (header) 


.PP
Definition in file \fBLoopFilter\&.h\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define DEBLOCK_SMALLEST_BLOCK   8"

.PP
Definition at line \fB48\fP of file \fBLoopFilter\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
