.TH "deps/base_vvc/minimum_VTM/source/Lib/CommonLib/MatrixIntraPrediction.h" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deps/base_vvc/minimum_VTM/source/Lib/CommonLib/MatrixIntraPrediction.h \- matrix-based intra prediction class (header)  

.SH SYNOPSIS
.br
.PP
\fC#include 'Unit\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMatrixIntraPrediction\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
matrix-based intra prediction class (header) 


.PP
Definition in file \fBMatrixIntraPrediction\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
