.TH "deps/base_vvc/minimum_VTM/source/Lib/CommonLib/MatrixIntraPrediction.cpp" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deps/base_vvc/minimum_VTM/source/Lib/CommonLib/MatrixIntraPrediction.cpp \- matrix-based intra prediction class  

.SH SYNOPSIS
.br
.PP
\fC#include 'MatrixIntraPrediction\&.h'\fP
.br
\fC#include 'dtrace_next\&.h'\fP
.br
\fC#include 'UnitTools\&.h'\fP
.br
\fC#include 'MipData\&.h'\fP
.br

.SH "Detailed Description"
.PP 
matrix-based intra prediction class 


.PP
Definition in file \fBMatrixIntraPrediction\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
