.TH "MatrixIntraPrediction" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MatrixIntraPrediction
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MatrixIntraPrediction\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMatrixIntraPrediction\fP ()"
.br
.ti -1c
.RI "void \fBprepareInputForPred\fP (const CPelBuf &pSrc, const Area &block, const int bitDepth, const ComponentID compId)"
.br
.ti -1c
.RI "void \fBpredBlock\fP (int *const result, const int modeIdx, const bool transpose, const int bitDepth, const ComponentID compId)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB48\fP of file \fBMatrixIntraPrediction\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MatrixIntraPrediction::MatrixIntraPrediction ()"

.PP
Definition at line \fB45\fP of file \fBMatrixIntraPrediction\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void MatrixIntraPrediction::predBlock (int *const result, const int modeIdx, const bool transpose, const int bitDepth, const ComponentID compId)"

.PP
Definition at line \fB120\fP of file \fBMatrixIntraPrediction\&.cpp\fP\&.
.SS "void MatrixIntraPrediction::prepareInputForPred (const CPelBuf & pSrc, const Area & block, const int bitDepth, const ComponentID compId)"

.PP
Definition at line \fB62\fP of file \fBMatrixIntraPrediction\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
