.TH "deps/base_vvc/minimum_VTM/source/Lib/CommonLib/MCTS.cpp" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deps/base_vvc/minimum_VTM/source/Lib/CommonLib/MCTS.cpp \- Motion Constrained Tile Sets class\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'MCTS\&.h'\fP
.br
\fC#include 'Buffer\&.h'\fP
.br
\fC#include 'UnitTools\&.h'\fP
.br
\fC#include <memory\&.h>\fP
.br
\fC#include <algorithm>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBvtm\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Motion Constrained Tile Sets class\&. 


.PP
Definition in file \fBMCTS\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
