.TH "deps/base_vvc/minimum_VTM/source/Lib/CommonLib/MCTS.h" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deps/base_vvc/minimum_VTM/source/Lib/CommonLib/MCTS.h \- Motion Constrained Tile Sets class (header)  

.SH SYNOPSIS
.br
.PP
\fC#include 'Unit\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBvtm::MCTSInfo\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBvtm\fP"
.br
.ti -1c
.RI "namespace \fBvtm::MCTSHelper\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBvtm::MCTSHelper::clipMvToArea\fP (\fBMv\fP &rcMv, const struct \fBArea\fP &block, const struct \fBArea\fP &\fBclipArea\fP, const \fBSPS\fP &sps, int mvFracBits=MV_FRACTIONAL_BITS_INTERNAL)"
.br
.in -1c
.PP
.RI "\fB\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "\fBArea\fP \fBvtm::MCTSHelper::getTileAreaRestricted\fP (const \fBArea\fP &tileArea, const int offLT, const int offRB)"
.br
.ti -1c
.RI "\fBArea\fP \fBvtm::MCTSHelper::getTileArea\fP (const \fBCodingStructure\fP *cs, const int ctuAddr)"
.br
.ti -1c
.RI "bool \fBvtm::MCTSHelper::isRefBlockAtRestrictedTileBoundary\fP (const \fBPredictionUnit\fP &pu)"
.br
.ti -1c
.RI "bool \fBvtm::MCTSHelper::checkMvForMCTSConstraint\fP (const \fBPredictionUnit\fP &pu, const \fBMv\fP &mv, const \fBMvPrecision\fP mvPrec=\fBMV_PRECISION_QUARTER\fP)"
.br
.ti -1c
.RI "bool \fBvtm::MCTSHelper::checkMvBufferForMCTSConstraint\fP (const \fBPredictionUnit\fP &pu, bool msgFlag=false)"
.br
.ti -1c
.RI "bool \fBvtm::MCTSHelper::checkMvIsNotInRestrictedArea\fP (const \fBPredictionUnit\fP &pu, const \fBMv\fP &mv, const \fBArea\fP &restrArea, const \fBMvPrecision\fP mvPrec)"
.br
.in -1c
.in -1c
.SH "Detailed Description"
.PP 
Motion Constrained Tile Sets class (header) 


.PP
Definition in file \fBMCTS\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
