.TH "deps/base_vvc/minimum_VTM/source/Lib/CommonLib/MipData.h" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deps/base_vvc/minimum_VTM/source/Lib/CommonLib/MipData.h \- weight and bias data for matrix-based intra prediction (MIP)  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBALIGN_DATA\fP (\fBMEMORY_ALIGN_DEF_SIZE\fP, const uint8_t mipMatrix4x4[16][16][4])"
.br
.ti -1c
.RI "\fBALIGN_DATA\fP (\fBMEMORY_ALIGN_DEF_SIZE\fP, const uint8_t mipMatrix8x8[8][16][8])"
.br
.ti -1c
.RI "\fBALIGN_DATA\fP (\fBMEMORY_ALIGN_DEF_SIZE\fP, const uint8_t mipMatrix16x16[6][64][7])"
.br
.in -1c
.SH "Detailed Description"
.PP 
weight and bias data for matrix-based intra prediction (MIP) 


.PP
Definition in file \fBMipData\&.h\fP\&.
.SH "Function Documentation"
.PP 
.SS "ALIGN_DATA (\fBMEMORY_ALIGN_DEF_SIZE\fP, const uint8_t mipMatrix16x16[6][64][7])"

.SS "ALIGN_DATA (\fBMEMORY_ALIGN_DEF_SIZE\fP, const uint8_t mipMatrix4x4[16][16][4])"

.SS "ALIGN_DATA (\fBMEMORY_ALIGN_DEF_SIZE\fP, const uint8_t mipMatrix8x8[8][16][8])"

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
