.TH "util/src/Misc.cpp" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
util/src/Misc.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'Misc\&.hpp'\fP
.br
\fC#include <algorithm>\fP
.br
\fC#include <chrono>\fP
.br
\fC#include <cstring>\fP
.br
\fC#include <string>\fP
.br
\fC#include <limits\&.h>\fP
.br
\fC#include <sys/stat\&.h>\fP
.br
\fC#include <time\&.h>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBlctm\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBPATH_SEPERATORS\fP   '/'"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::string \fBlctm::get_program\fP ()"
.br
.ti -1c
.RI "std::string \fBlctm::get_program_directory\fP (const std::string &suffix)"
.br
.ti -1c
.RI "size_t \fBlctm::file_size\fP (int fd)"
.br
.ti -1c
.RI "size_t \fBlctm::file_size\fP (const std::string &\fBname\fP)"
.br
.ti -1c
.RI "std::string \fBlctm::read_file\fP (const std::string &\fBname\fP)"
.br
.ti -1c
.RI "bool \fBlctm::write_file\fP (const std::string &\fBname\fP, const std::string &contents)"
.br
.ti -1c
.RI "std::string \fBlctm::lowercase\fP (const char *s)"
.br
.ti -1c
.RI "std::string \fBlctm::lowercase\fP (const std::string &s)"
.br
.ti -1c
.RI "unsigned \fBlctm::split\fP (std::vector< std::string > &output, const std::string &src, const char *seperators)"
.br
.ti -1c
.RI "std::string \fBlctm::file_extension\fP (const std::string &filename)"
.br
.ti -1c
.RI "uint64_t \fBlctm::crc64\fP (uint64_t crc, const unsigned char *s, uint64_t l)"
.br
.ti -1c
.RI "uint64_t \fBlctm::system_timestamp\fP ()"
.br
.ti -1c
.RI "std::string \fBlctm::make_temporary_filename\fP (const std::string &suffix)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define PATH_SEPERATORS   '/'"

.PP
Definition at line \fB230\fP of file \fBMisc\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
