.TH "util/include/Misc.hpp" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
util/include/Misc.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <algorithm>\fP
.br
\fC#include <memory>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br
\fC#include 'Diagnostics\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBlctm::UniquePtrFileClose\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBlctm\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBLCEVC_MIN\fP(a,  b)   ((a) < (b) ? (a) : (b))"
.br
.ti -1c
.RI "#define \fBLCEVC_MAX\fP(a,  b)   ((a) > (b) ? (a) : (b))"
.br
.ti -1c
.RI "#define \fBARRAY_SIZE\fP(a)   (sizeof(a) / sizeof((a)[0]))"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef std::unique_ptr< FILE, \fBUniquePtrFileClose\fP > \fBlctm::UniquePtrFile\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::string \fBlctm::get_program\fP ()"
.br
.ti -1c
.RI "std::string \fBlctm::get_program_directory\fP (const std::string &suffix)"
.br
.ti -1c
.RI "size_t \fBlctm::file_size\fP (int fd)"
.br
.ti -1c
.RI "size_t \fBlctm::file_size\fP (const std::string &\fBname\fP)"
.br
.ti -1c
.RI "std::string \fBlctm::read_file\fP (const std::string &\fBname\fP)"
.br
.ti -1c
.RI "bool \fBlctm::write_file\fP (const std::string &\fBname\fP, const std::string &contents)"
.br
.ti -1c
.RI "std::string \fBlctm::file_extension\fP (const std::string &filename)"
.br
.ti -1c
.RI "std::string \fBlctm::lowercase\fP (const char *s)"
.br
.ti -1c
.RI "std::string \fBlctm::lowercase\fP (const std::string &s)"
.br
.ti -1c
.RI "unsigned \fBlctm::split\fP (std::vector< std::string > &output, const std::string &src, const char *seperators)"
.br
.ti -1c
.RI "template<typename T > T \fBlctm::clamp\fP (T val, T l, T h)"
.br
.ti -1c
.RI "uint64_t \fBlctm::crc64\fP (uint64_t crc, const unsigned char *s, uint64_t l)"
.br
.ti -1c
.RI "uint64_t \fBlctm::system_timestamp\fP ()"
.br
.ti -1c
.RI "std::string \fBlctm::make_temporary_filename\fP (const std::string &suffix)"
.br
.ti -1c
.RI "template<typename T > T \fBlctm::extract\fP (const std::string &s)"
.br
.ti -1c
.RI "template<typename T > T \fBlctm::extract\fP (const std::string &s, T dflt)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define ARRAY_SIZE(a)   (sizeof(a) / sizeof((a)[0]))"

.PP
Definition at line \fB182\fP of file \fBMisc\&.hpp\fP\&.
.SS "#define LCEVC_MAX(a, b)   ((a) > (b) ? (a) : (b))"

.PP
Definition at line \fB50\fP of file \fBMisc\&.hpp\fP\&.
.SS "#define LCEVC_MIN(a, b)   ((a) < (b) ? (a) : (b))"

.PP
Definition at line \fB48\fP of file \fBMisc\&.hpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
