.TH "src/ModelEncoderApp.cpp" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/ModelEncoderApp.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <algorithm>\fP
.br
\fC#include <cinttypes>\fP
.br
\fC#include <cstdio>\fP
.br
\fC#include <string>\fP
.br
\fC#include <cxxopts\&.hpp>\fP
.br
\fC#include <nlohmann/json\&.hpp>\fP
.br
\fC#include 'FileEncoder\&.hpp'\fP
.br
\fC#include 'Config\&.hpp'\fP
.br
\fC#include 'Diagnostics\&.hpp'\fP
.br
\fC#include 'Image\&.hpp'\fP
.br
\fC#include 'Misc\&.hpp'\fP
.br
\fC#include 'YUVReader\&.hpp'\fP
.br
\fC#include 'SignaledConfiguration\&.hpp'\fP
.br
\fC#include <queue>\fP
.br
\fC#include <vector>\fP
.br
\fC#include 'BitstreamStatistic\&.hpp'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBGIT_VERSION\fP   ''"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBjson\fP = \fBnlohmann::json\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBBitstreamStatistic\fP \fBgoStat\fP"
.br
.ti -1c
.RI "FILE * \fBgoBits\fP = \fBNULL\fP"
.br
.ti -1c
.RI "\fBPsnrStatistic\fP \fBgoPsnr\fP"
.br
.ti -1c
.RI "uint8_t \fBgaucMd5Digest\fP [\fBlctm::MAX_NUM_PLANES\fP][16]"
.br
.ti -1c
.RI "\fBReportStructure\fP \fBgoReportStructure\fP"
.br
.ti -1c
.RI "std::priority_queue< \fBReportStructure\fP, std::vector< \fBReportStructure\fP, std::allocator< \fBReportStructure\fP > >, \fBReportStructureComp\fP > \fBgoReportQueue\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define GIT_VERSION   ''"

.PP
Definition at line \fB63\fP of file \fBModelEncoderApp\&.cpp\fP\&.
.SH "Typedef Documentation"
.PP 
.SS "using \fBjson\fP =  \fBnlohmann::json\fP"

.PP
Definition at line \fB48\fP of file \fBModelEncoderApp\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char * argv[])"

.PP
Definition at line \fB85\fP of file \fBModelEncoderApp\&.cpp\fP\&.
.SH "Variable Documentation"
.PP 
.SS "uint8_t gaucMd5Digest[\fBlctm::MAX_NUM_PLANES\fP][16]"

.PP
Definition at line \fB78\fP of file \fBModelEncoderApp\&.cpp\fP\&.
.SS "FILE* goBits = \fBNULL\fP"

.PP
Definition at line \fB76\fP of file \fBModelEncoderApp\&.cpp\fP\&.
.SS "\fBPsnrStatistic\fP goPsnr"

.PP
Definition at line \fB77\fP of file \fBModelEncoderApp\&.cpp\fP\&.
.SS "std::priority_queue<\fBReportStructure\fP, std::vector<\fBReportStructure\fP, std::allocator<\fBReportStructure\fP> >, \fBReportStructureComp\fP> goReportQueue"

.PP
Definition at line \fB81\fP of file \fBModelEncoderApp\&.cpp\fP\&.
.SS "\fBReportStructure\fP goReportStructure"

.PP
Definition at line \fB79\fP of file \fBModelEncoderApp\&.cpp\fP\&.
.SS "\fBBitstreamStatistic\fP goStat"

.PP
Definition at line \fB75\fP of file \fBModelEncoderApp\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
