.TH "deps/base_vvc/minimum_VTM/source/Lib/CommonLib/MotionInfo.h" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deps/base_vvc/minimum_VTM/source/Lib/CommonLib/MotionInfo.h \- motion information handling classes (header)  

.SH SYNOPSIS
.br
.PP
\fC#include 'CommonDef\&.h'\fP
.br
\fC#include 'Mv\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBvtm::AMVPInfo\fP"
.br
.RI "parameters for AMVP "
.ti -1c
.RI "struct \fBvtm::AffineAMVPInfo\fP"
.br
.ti -1c
.RI "struct \fBvtm::MvField\fP"
.br
.RI "class for motion vector with reference index "
.ti -1c
.RI "struct \fBvtm::MotionInfo\fP"
.br
.ti -1c
.RI "class \fBvtm::BcwMotionParam\fP"
.br
.ti -1c
.RI "struct \fBvtm::LutMotionCand\fP"
.br
.ti -1c
.RI "struct \fBvtm::PatentBvCand\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBvtm\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
motion information handling classes (header) 


.PP
\fBTodo\fP
.RS 4
MvField seems to be better to be inherited from Mv 
.RE
.PP

.PP
Definition in file \fBMotionInfo\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
