.TH "deps/base_vvc/minimum_VTM/source/Lib/CommonLib/Mv.cpp" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deps/base_vvc/minimum_VTM/source/Lib/CommonLib/Mv.cpp \- motion vector class  

.SH SYNOPSIS
.br
.PP
\fC#include 'Mv\&.h'\fP
.br
\fC#include 'Common\&.h'\fP
.br
\fC#include 'Slice\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBvtm\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBvtm::roundAffineMv\fP (int &mvx, int &mvy, int nShift)"
.br
.ti -1c
.RI "void \fBvtm::clipMvInPic\fP (\fBMv\fP &rcMv, const struct \fBPosition\fP &pos, const struct \fBSize\fP &size, const class \fBSPS\fP &sps, const class \fBPPS\fP &pps)"
.br
.ti -1c
.RI "void \fBvtm::clipMvInSubpic\fP (\fBMv\fP &rcMv, const struct \fBPosition\fP &pos, const struct \fBSize\fP &size, const class \fBSPS\fP &sps, const class \fBPPS\fP &pps)"
.br
.ti -1c
.RI "bool \fBvtm::wrapClipMv\fP (\fBMv\fP &rcMv, const \fBPosition\fP &pos, const struct \fBSize\fP &size, const \fBSPS\fP *sps, const \fBPPS\fP *pps)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "void(* \fBvtm::clipMv\fP )(\fBMv\fP &rcMv, const struct \fBPosition\fP &pos, const struct \fBSize\fP &size, const class \fBSPS\fP &sps, const class \fBPPS\fP &pps)"
.br
.in -1c
.SH "Detailed Description"
.PP 
motion vector class 


.PP
Definition in file \fBMv\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
