.TH "deps/base_vvc/minimum_VTM/source/Lib/CommonLib/Mv.h" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deps/base_vvc/minimum_VTM/source/Lib/CommonLib/Mv.h \- motion vector class (header)  

.SH SYNOPSIS
.br
.PP
\fC#include 'CommonDef\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBvtm::Mv\fP"
.br
.RI "basic motion vector class "
.ti -1c
.RI "struct \fBstd::hash< vtm::Mv >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBvtm\fP"
.br
.ti -1c
.RI "namespace \fBstd\fP"
.br
.in -1c
.SS "Enumerations"

.PP
.RI "\fB\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "enum \fBvtm::MvPrecision\fP { \fBvtm::MV_PRECISION_4PEL\fP = 0, \fBvtm::MV_PRECISION_INT\fP = 2, \fBvtm::MV_PRECISION_HALF\fP = 3, \fBvtm::MV_PRECISION_QUARTER\fP = 4, \fBvtm::MV_PRECISION_SIXTEENTH\fP = 6, \fBvtm::MV_PRECISION_INTERNAL\fP = 2 + MV_FRACTIONAL_BITS_INTERNAL }"
.br
.in -1c
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBvtm::clipMvInPic\fP (\fBMv\fP &rcMv, const struct \fBPosition\fP &pos, const struct \fBSize\fP &size, const class \fBSPS\fP &sps, const class \fBPPS\fP &pps)"
.br
.ti -1c
.RI "void \fBvtm::clipMvInSubpic\fP (\fBMv\fP &rcMv, const struct \fBPosition\fP &pos, const struct \fBSize\fP &size, const class \fBSPS\fP &sps, const class \fBPPS\fP &pps)"
.br
.ti -1c
.RI "bool \fBvtm::wrapClipMv\fP (\fBMv\fP &rcMv, const \fBPosition\fP &pos, const struct \fBSize\fP &size, const \fBSPS\fP *sps, const \fBPPS\fP *pps)"
.br
.ti -1c
.RI "void \fBvtm::roundAffineMv\fP (int &mvx, int &mvy, int nShift)"
.br
.in -1c
.SH "Detailed Description"
.PP 
motion vector class (header) 


.PP
Definition in file \fBMv\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
