.TH "NALUnit" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NALUnit
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <NAL\&.h>\fP
.PP
Inherited by \fBNALUnitEBSP\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNALUnit\fP (const \fBNALUnit\fP &src)"
.br
.ti -1c
.RI "\fBNALUnit\fP (NalUnitType nalUnitType, int temporalId=0, uint32_t nuhReservedZeroBit=0, uint32_t forbiddenZeroBit=0, int nuhLayerId=0)"
.br
.ti -1c
.RI "\fBNALUnit\fP ()"
.br
.ti -1c
.RI "virtual \fB~NALUnit\fP ()"
.br
.ti -1c
.RI "bool \fBisSlice\fP ()"
.br
.ti -1c
.RI "bool \fBisSei\fP ()"
.br
.ti -1c
.RI "bool \fBisVcl\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "\fBstatic\fP bool \fBisVclNalUnitType\fP (NalUnitType t)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "NalUnitType \fBm_nalUnitType\fP"
.br
.RI "nal_unit_type "
.ti -1c
.RI "uint32_t \fBm_temporalId\fP"
.br
.RI "temporal_id "
.ti -1c
.RI "uint32_t \fBm_nuhLayerId\fP"
.br
.RI "nuh_layer_id "
.ti -1c
.RI "uint32_t \fBm_forbiddenZeroBit\fP"
.br
.ti -1c
.RI "uint32_t \fBm_nuhReservedZeroBit\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Represents a single NALunit header and the associated RBSPayload 
.PP
Definition at line \fB48\fP of file \fBNAL\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "NALUnit::NALUnit (const \fBNALUnit\fP & src)\fC [inline]\fP"

.PP
Definition at line \fB56\fP of file \fBNAL\&.h\fP\&.
.SS "NALUnit::NALUnit (NalUnitType nalUnitType, int temporalId = \fC0\fP, uint32_t nuhReservedZeroBit = \fC0\fP, uint32_t forbiddenZeroBit = \fC0\fP, int nuhLayerId = \fC0\fP)\fC [inline]\fP"
construct an NALunit structure with given header values\&. 
.PP
Definition at line \fB64\fP of file \fBNAL\&.h\fP\&.
.SS "NALUnit::NALUnit ()\fC [inline]\fP"
default constructor - no initialization; must be performed by user 
.PP
Definition at line \fB82\fP of file \fBNAL\&.h\fP\&.
.SS "virtual NALUnit::~NALUnit ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Definition at line \fB84\fP of file \fBNAL\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "bool NALUnit::isSei ()\fC [inline]\fP"

.PP
Definition at line \fB98\fP of file \fBNAL\&.h\fP\&.
.SS "bool NALUnit::isSlice ()\fC [inline]\fP"
returns true if the NALunit is a slice NALunit 
.PP
Definition at line \fB87\fP of file \fBNAL\&.h\fP\&.
.SS "bool NALUnit::isVcl ()\fC [inline]\fP"

.PP
Definition at line \fB104\fP of file \fBNAL\&.h\fP\&.
.SS "\fBstatic\fP bool NALUnit::isVclNalUnitType (NalUnitType t)\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line \fB109\fP of file \fBNAL\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "uint32_t NALUnit::m_forbiddenZeroBit"

.PP
Definition at line \fB53\fP of file \fBNAL\&.h\fP\&.
.SS "NalUnitType NALUnit::m_nalUnitType"

.PP
nal_unit_type 
.PP
Definition at line \fB50\fP of file \fBNAL\&.h\fP\&.
.SS "uint32_t NALUnit::m_nuhLayerId"

.PP
nuh_layer_id 
.PP
Definition at line \fB52\fP of file \fBNAL\&.h\fP\&.
.SS "uint32_t NALUnit::m_nuhReservedZeroBit"

.PP
Definition at line \fB54\fP of file \fBNAL\&.h\fP\&.
.SS "uint32_t NALUnit::m_temporalId"

.PP
temporal_id 
.PP
Definition at line \fB51\fP of file \fBNAL\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
