.TH "NALUnitEBSP" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NALUnitEBSP
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <NAL\&.h>\fP
.PP
Inherits \fBNALUnit\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNALUnitEBSP\fP (OutputNALUnit &nalu)"
.br
.in -1c

Public Member Functions inherited from \fBNALUnit\fP
.in +1c
.ti -1c
.RI "\fBNALUnit\fP (const \fBNALUnit\fP &src)"
.br
.ti -1c
.RI "\fBNALUnit\fP (NalUnitType nalUnitType, int temporalId=0, uint32_t nuhReservedZeroBit=0, uint32_t forbiddenZeroBit=0, int nuhLayerId=0)"
.br
.ti -1c
.RI "\fBNALUnit\fP ()"
.br
.ti -1c
.RI "virtual \fB~NALUnit\fP ()"
.br
.ti -1c
.RI "bool \fBisSlice\fP ()"
.br
.ti -1c
.RI "bool \fBisSei\fP ()"
.br
.ti -1c
.RI "bool \fBisVcl\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::ostringstream \fBm_nalUnitData\fP"
.br
.in -1c

Public Attributes inherited from \fBNALUnit\fP
.in +1c
.ti -1c
.RI "NalUnitType \fBm_nalUnitType\fP"
.br
.RI "nal_unit_type "
.ti -1c
.RI "uint32_t \fBm_temporalId\fP"
.br
.RI "temporal_id "
.ti -1c
.RI "uint32_t \fBm_nuhLayerId\fP"
.br
.RI "nuh_layer_id "
.ti -1c
.RI "uint32_t \fBm_forbiddenZeroBit\fP"
.br
.ti -1c
.RI "uint32_t \fBm_nuhReservedZeroBit\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Static Public Member Functions inherited from \fBNALUnit\fP
.in +1c
.ti -1c
.RI "\fBstatic\fP bool \fBisVclNalUnitType\fP (NalUnitType t)"
.br
.in -1c
.SH "Detailed Description"
.PP 
A single NALunit, with complete payload in EBSP format\&. 
.PP
Definition at line \fB127\fP of file \fBNAL\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "NALUnitEBSP::NALUnitEBSP (OutputNALUnit & nalu)"
convert the OutputNALUnit nalu into EBSP format by writing out the \fBNALUnit\fP header, then the rbsp_bytes including any emulation_prevention_three_byte symbols\&. 
.SH "Member Data Documentation"
.PP 
.SS "std::ostringstream NALUnitEBSP::m_nalUnitData"

.PP
Definition at line \fB129\fP of file \fBNAL\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
