.TH "nlohmann::detail::external_constructor< value_t::string >" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nlohmann::detail::external_constructor< value_t::string >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <json\&.hpp>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename BasicJsonType > \fBstatic\fP void \fBconstruct\fP (BasicJsonType &j, const typename BasicJsonType::string_t &s)"
.br
.ti -1c
.RI "template<typename BasicJsonType > \fBstatic\fP void \fBconstruct\fP (BasicJsonType &j, typename BasicJsonType::string_t &&s)"
.br
.ti -1c
.RI "template<typename BasicJsonType , typename CompatibleStringType , \fBenable_if_t\fP< not std::is_same< CompatibleStringType, typename BasicJsonType::string_t >::value, int >  = 0> \fBstatic\fP void \fBconstruct\fP (BasicJsonType &j, const CompatibleStringType &str)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB1743\fP of file \fBjson\&.hpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "template<typename BasicJsonType , typename CompatibleStringType , \fBenable_if_t\fP< not std::is_same< CompatibleStringType, typename BasicJsonType::string_t >::value, int >  = 0> \fBstatic\fP void \fBnlohmann::detail::external_constructor\fP< value_t::string >::construct (BasicJsonType & j, const CompatibleStringType & str)\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line \fB1764\fP of file \fBjson\&.hpp\fP\&.
.SS "template<typename BasicJsonType > \fBstatic\fP void \fBnlohmann::detail::external_constructor\fP< value_t::string >::construct (BasicJsonType & j, const typename BasicJsonType::string_t & s)\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line \fB1746\fP of file \fBjson\&.hpp\fP\&.
.SS "template<typename BasicJsonType > \fBstatic\fP void \fBnlohmann::detail::external_constructor\fP< value_t::string >::construct (BasicJsonType & j, typename BasicJsonType::string_t && s)\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line \fB1754\fP of file \fBjson\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
