.TH "nlohmann::detail::is_basic_json< typename >" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nlohmann::detail::is_basic_json< typename >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <json\&.hpp>\fP
.PP
Inherits std::false_type\&.
.SH "Detailed Description"
.PP 

.SS "template<typename>
.br
struct nlohmann::detail::is_basic_json< typename >"
.PP
Definition at line \fB429\fP of file \fBjson\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
