.TH "nlohmann::detail::detector< Default, void_t< Op< Args... > >, Op, Args... >" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nlohmann::detail::detector< Default, void_t< Op< Args... > >, Op, Args... >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <json\&.hpp>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBvalue_t\fP = std::true_type"
.br
.ti -1c
.RI "using \fBtype\fP = Op< Args\&.\&.\&. >"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class Default, template< class\&.\&.\&. > class Op, class\&.\&.\&. Args>
.br
struct nlohmann::detail::detector< Default, void_t< Op< Args\&.\&.\&. > >, Op, Args\&.\&.\&. >"
.PP
Definition at line \fB374\fP of file \fBjson\&.hpp\fP\&.
.SH "Member Typedef Documentation"
.PP 
.SS "template<class Default , template< class\&.\&.\&. > class Op, class\&.\&.\&. Args> using \fBnlohmann::detail::detector\fP< Default, \fBvoid_t\fP< Op< Args\&.\&.\&. > >, Op, Args\&.\&.\&. >::type =  Op<Args\&.\&.\&.>"

.PP
Definition at line \fB377\fP of file \fBjson\&.hpp\fP\&.
.SS "template<class Default , template< class\&.\&.\&. > class Op, class\&.\&.\&. Args> using \fBnlohmann::detail::detector\fP< Default, \fBvoid_t\fP< Op< Args\&.\&.\&. > >, Op, Args\&.\&.\&. >::value_t =  std::true_type"

.PP
Definition at line \fB376\fP of file \fBjson\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
