.TH "nlohmann::detail::is_compatible_array_type_impl< BasicJsonType, CompatibleArrayType, typename >" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nlohmann::detail::is_compatible_array_type_impl< BasicJsonType, CompatibleArrayType, typename >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <json\&.hpp>\fP
.PP
Inherits std::false_type\&.
.PP
Inherited by \fBnlohmann::detail::is_compatible_array_type< BasicJsonType, CompatibleArrayType >\fP\&.
.SH "Detailed Description"
.PP 

.SS "template<typename BasicJsonType, typename CompatibleArrayType, typename = void>
.br
struct nlohmann::detail::is_compatible_array_type_impl< BasicJsonType, CompatibleArrayType, typename >"
.PP
Definition at line \fB634\fP of file \fBjson\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
