.TH "nlohmann::detail::detector< Default, AlwaysVoid, Op, Args >" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nlohmann::detail::detector< Default, AlwaysVoid, Op, Args >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <json\&.hpp>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBvalue_t\fP = std::false_type"
.br
.ti -1c
.RI "using \fBtype\fP = Default"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class Default, class AlwaysVoid, template< class\&.\&.\&. > class Op, class\&.\&.\&. Args>
.br
struct nlohmann::detail::detector< Default, AlwaysVoid, Op, Args >"
.PP
Definition at line \fB367\fP of file \fBjson\&.hpp\fP\&.
.SH "Member Typedef Documentation"
.PP 
.SS "template<class Default , class AlwaysVoid , template< class\&.\&.\&. > class Op, class\&.\&.\&. Args> using \fBnlohmann::detail::detector\fP< Default, AlwaysVoid, Op, Args >::type =  Default"

.PP
Definition at line \fB370\fP of file \fBjson\&.hpp\fP\&.
.SS "template<class Default , class AlwaysVoid , template< class\&.\&.\&. > class Op, class\&.\&.\&. Args> using \fBnlohmann::detail::detector\fP< Default, AlwaysVoid, Op, Args >::value_t =  std::false_type"

.PP
Definition at line \fB369\fP of file \fBjson\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
