.TH "nlohmann::detail" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nlohmann::detail \- detail namespace with internal helper functions  

.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBdtoa_impl\fP"
.br
.RI "implements the Grisu2 algorithm for binary to decimal floating-point conversion\&. "
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBdetector\fP"
.br
.ti -1c
.RI "struct \fBdetector< Default, void_t< Op< Args\&.\&.\&. > >, Op, Args\&.\&.\&. >\fP"
.br
.ti -1c
.RI "class \fBexception\fP"
.br
.RI "general exception of the \fBbasic_json\fP class "
.ti -1c
.RI "struct \fBexternal_constructor\fP"
.br
.ti -1c
.RI "struct \fBexternal_constructor< value_t::array >\fP"
.br
.ti -1c
.RI "struct \fBexternal_constructor< value_t::boolean >\fP"
.br
.ti -1c
.RI "struct \fBexternal_constructor< value_t::number_float >\fP"
.br
.ti -1c
.RI "struct \fBexternal_constructor< value_t::number_integer >\fP"
.br
.ti -1c
.RI "struct \fBexternal_constructor< value_t::number_unsigned >\fP"
.br
.ti -1c
.RI "struct \fBexternal_constructor< value_t::object >\fP"
.br
.ti -1c
.RI "struct \fBexternal_constructor< value_t::string >\fP"
.br
.ti -1c
.RI "struct \fBhas_from_json\fP"
.br
.ti -1c
.RI "struct \fBhas_from_json< BasicJsonType, T, enable_if_t< not is_basic_json< T >::value > >\fP"
.br
.ti -1c
.RI "struct \fBhas_non_default_from_json\fP"
.br
.ti -1c
.RI "struct \fBhas_non_default_from_json< BasicJsonType, T, enable_if_t< not is_basic_json< T >::value > >\fP"
.br
.ti -1c
.RI "struct \fBhas_to_json\fP"
.br
.ti -1c
.RI "struct \fBhas_to_json< BasicJsonType, T, enable_if_t< not is_basic_json< T >::value > >\fP"
.br
.ti -1c
.RI "struct \fBindex_sequence\fP"
.br
.ti -1c
.RI "class \fBinput_adapter\fP"
.br
.ti -1c
.RI "struct \fBinput_adapter_protocol\fP"
.br
.RI "abstract input adapter interface "
.ti -1c
.RI "class \fBinput_buffer_adapter\fP"
.br
.RI "input adapter for buffer input "
.ti -1c
.RI "class \fBinput_stream_adapter\fP"
.br
.ti -1c
.RI "struct \fBinternal_iterator\fP"
.br
.RI "an iterator value "
.ti -1c
.RI "class \fBinvalid_iterator\fP"
.br
.RI "exception indicating errors with iterators "
.ti -1c
.RI "struct \fBis_basic_json\fP"
.br
.ti -1c
.RI "struct \fBis_basic_json< NLOHMANN_BASIC_JSON_TPL >\fP"
.br
.ti -1c
.RI "struct \fBis_compatible_array_type\fP"
.br
.ti -1c
.RI "struct \fBis_compatible_array_type_impl\fP"
.br
.ti -1c
.RI "struct \fBis_compatible_array_type_impl< BasicJsonType, CompatibleArrayType, enable_if_t< is_detected< value_type_t, CompatibleArrayType >::value and is_detected< iterator_t, CompatibleArrayType >::value and not is_iterator_traits< std::iterator_traits< CompatibleArrayType > >::value > >\fP"
.br
.ti -1c
.RI "struct \fBis_compatible_integer_type\fP"
.br
.ti -1c
.RI "struct \fBis_compatible_integer_type_impl\fP"
.br
.ti -1c
.RI "struct \fBis_compatible_integer_type_impl< RealIntegerType, CompatibleNumberIntegerType, enable_if_t< std::is_integral< RealIntegerType >::value and std::is_integral< CompatibleNumberIntegerType >::value and not std::is_same< bool, CompatibleNumberIntegerType >::value > >\fP"
.br
.ti -1c
.RI "struct \fBis_compatible_object_type\fP"
.br
.ti -1c
.RI "struct \fBis_compatible_object_type_impl\fP"
.br
.ti -1c
.RI "struct \fBis_compatible_object_type_impl< BasicJsonType, CompatibleObjectType, enable_if_t< is_detected< mapped_type_t, CompatibleObjectType >::value and is_detected< key_type_t, CompatibleObjectType >::value > >\fP"
.br
.ti -1c
.RI "struct \fBis_compatible_string_type\fP"
.br
.ti -1c
.RI "struct \fBis_compatible_string_type_impl\fP"
.br
.ti -1c
.RI "struct \fBis_compatible_string_type_impl< BasicJsonType, CompatibleStringType, enable_if_t< is_detected_exact< typename BasicJsonType::string_t::value_type, value_type_t, CompatibleStringType >::value > >\fP"
.br
.ti -1c
.RI "struct \fBis_compatible_type\fP"
.br
.ti -1c
.RI "struct \fBis_compatible_type_impl\fP"
.br
.ti -1c
.RI "struct \fBis_compatible_type_impl< BasicJsonType, CompatibleType, enable_if_t< is_complete_type< CompatibleType >::value > >\fP"
.br
.ti -1c
.RI "struct \fBis_complete_type\fP"
.br
.ti -1c
.RI "struct \fBis_complete_type< T, decltype(void(sizeof(T)))>\fP"
.br
.ti -1c
.RI "struct \fBis_constructible_array_type\fP"
.br
.ti -1c
.RI "struct \fBis_constructible_array_type_impl\fP"
.br
.ti -1c
.RI "struct \fBis_constructible_array_type_impl< BasicJsonType, ConstructibleArrayType, enable_if_t< not std::is_same< ConstructibleArrayType, typename BasicJsonType::value_type >::value and is_detected< value_type_t, ConstructibleArrayType >::value and is_detected< iterator_t, ConstructibleArrayType >::value and is_complete_type< detected_t< value_type_t, ConstructibleArrayType > >::value > >\fP"
.br
.ti -1c
.RI "struct \fBis_constructible_array_type_impl< BasicJsonType, ConstructibleArrayType, enable_if_t< std::is_same< ConstructibleArrayType, typename BasicJsonType::value_type >::value > >\fP"
.br
.ti -1c
.RI "struct \fBis_constructible_object_type\fP"
.br
.ti -1c
.RI "struct \fBis_constructible_object_type_impl\fP"
.br
.ti -1c
.RI "struct \fBis_constructible_object_type_impl< BasicJsonType, ConstructibleObjectType, enable_if_t< is_detected< mapped_type_t, ConstructibleObjectType >::value and is_detected< key_type_t, ConstructibleObjectType >::value > >\fP"
.br
.ti -1c
.RI "struct \fBis_constructible_string_type\fP"
.br
.ti -1c
.RI "struct \fBis_constructible_string_type_impl\fP"
.br
.ti -1c
.RI "struct \fBis_constructible_string_type_impl< BasicJsonType, ConstructibleStringType, enable_if_t< is_detected_exact< typename BasicJsonType::string_t::value_type, value_type_t, ConstructibleStringType >::value > >\fP"
.br
.ti -1c
.RI "struct \fBis_iterator_traits\fP"
.br
.ti -1c
.RI "struct \fBis_iterator_traits< std::iterator_traits< T > >\fP"
.br
.ti -1c
.RI "struct \fBis_sax\fP"
.br
.ti -1c
.RI "struct \fBis_sax_static_asserts\fP"
.br
.ti -1c
.RI "class \fBiter_impl\fP"
.br
.RI "a template for a bidirectional iterator for the \fBbasic_json\fP class "
.ti -1c
.RI "class \fBjson_sax_acceptor\fP"
.br
.ti -1c
.RI "class \fBjson_sax_dom_callback_parser\fP"
.br
.ti -1c
.RI "class \fBjson_sax_dom_parser\fP"
.br
.RI "SAX implementation to create a JSON value from SAX events\&. "
.ti -1c
.RI "struct \fBmake_index_sequence\fP"
.br
.ti -1c
.RI "struct \fBmake_index_sequence< 0 >\fP"
.br
.ti -1c
.RI "struct \fBmake_index_sequence< 1 >\fP"
.br
.ti -1c
.RI "struct \fBmake_void\fP"
.br
.ti -1c
.RI "struct \fBmerge_and_renumber\fP"
.br
.ti -1c
.RI "struct \fBmerge_and_renumber< index_sequence< I1\&.\&.\&. >, index_sequence< I2\&.\&.\&. > >\fP"
.br
.ti -1c
.RI "struct \fBnonesuch\fP"
.br
.ti -1c
.RI "class \fBother_error\fP"
.br
.RI "exception indicating other library errors "
.ti -1c
.RI "class \fBout_of_range\fP"
.br
.RI "exception indicating access out of the defined range "
.ti -1c
.RI "class \fBoutput_adapter\fP"
.br
.ti -1c
.RI "struct \fBoutput_adapter_protocol\fP"
.br
.RI "abstract output adapter interface "
.ti -1c
.RI "class \fBoutput_stream_adapter\fP"
.br
.RI "output adapter for output streams "
.ti -1c
.RI "class \fBoutput_string_adapter\fP"
.br
.RI "output adapter for basic_string "
.ti -1c
.RI "class \fBoutput_vector_adapter\fP"
.br
.RI "output adapter for byte vectors "
.ti -1c
.RI "class \fBparse_error\fP"
.br
.RI "exception indicating a parse error "
.ti -1c
.RI "class \fBparser\fP"
.br
.RI "syntax analysis "
.ti -1c
.RI "struct \fBposition_t\fP"
.br
.RI "struct to capture the start position of the current token "
.ti -1c
.RI "class \fBprimitive_iterator_t\fP"
.br
.ti -1c
.RI "struct \fBpriority_tag\fP"
.br
.ti -1c
.RI "struct \fBpriority_tag< 0 >\fP"
.br
.ti -1c
.RI "class \fBserializer\fP"
.br
.ti -1c
.RI "struct \fBstatic_const\fP"
.br
.ti -1c
.RI "struct \fBto_json_fn\fP"
.br
.ti -1c
.RI "class \fBtype_error\fP"
.br
.RI "exception indicating executing a member function with a wrong type "
.ti -1c
.RI "class \fBwide_string_input_adapter\fP"
.br
.ti -1c
.RI "struct \fBwide_string_input_helper\fP"
.br
.ti -1c
.RI "struct \fBwide_string_input_helper< WideStringType, 2 >\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "template<bool B, typename T  = void> using \fBenable_if_t\fP = typename std::enable_if< B, T >::type"
.br
.ti -1c
.RI "template<typename T > using \fBuncvref_t\fP = typename std::remove_cv< typename std::remove_reference< T >::type >::type"
.br
.ti -1c
.RI "template<typename\&.\&.\&. Ts> using \fBindex_sequence_for\fP = \fBmake_index_sequence\fP< sizeof\&.\&.\&.(Ts)>"
.br
.ti -1c
.RI "template<typename \&.\&.\&. Ts> using \fBvoid_t\fP = typename \fBmake_void\fP< Ts\&.\&.\&. >::type"
.br
.ti -1c
.RI "template<template< class\&.\&.\&. > class Op, class\&.\&.\&. Args> using \fBis_detected\fP = typename \fBdetector\fP< \fBnonesuch\fP, void, Op, Args\&.\&.\&. >::value_t"
.br
.ti -1c
.RI "template<template< class\&.\&.\&. > class Op, class\&.\&.\&. Args> using \fBdetected_t\fP = typename \fBdetector\fP< \fBnonesuch\fP, void, Op, Args\&.\&.\&. >::type"
.br
.ti -1c
.RI "template<class Default , template< class\&.\&.\&. > class Op, class\&.\&.\&. Args> using \fBdetected_or\fP = \fBdetector\fP< Default, void, Op, Args\&.\&.\&. >"
.br
.ti -1c
.RI "template<class Default , template< class\&.\&.\&. > class Op, class\&.\&.\&. Args> using \fBdetected_or_t\fP = typename \fBdetected_or\fP< Default, Op, Args\&.\&.\&. >::type"
.br
.ti -1c
.RI "template<class Expected , template< class\&.\&.\&. > class Op, class\&.\&.\&. Args> using \fBis_detected_exact\fP = std::is_same< Expected, \fBdetected_t\fP< Op, Args\&.\&.\&. > >"
.br
.ti -1c
.RI "template<class To , template< class\&.\&.\&. > class Op, class\&.\&.\&. Args> using \fBis_detected_convertible\fP = std::is_convertible< \fBdetected_t\fP< Op, Args\&.\&.\&. >, To >"
.br
.ti -1c
.RI "template<typename T > using \fBmapped_type_t\fP = typename T::mapped_type"
.br
.ti -1c
.RI "template<typename T > using \fBkey_type_t\fP = typename T::key_type"
.br
.ti -1c
.RI "template<typename T > using \fBvalue_type_t\fP = typename T::value_type"
.br
.ti -1c
.RI "template<typename T > using \fBdifference_type_t\fP = typename T::difference_type"
.br
.ti -1c
.RI "template<typename T > using \fBpointer_t\fP = typename T::pointer"
.br
.ti -1c
.RI "template<typename T > using \fBreference_t\fP = typename T::reference"
.br
.ti -1c
.RI "template<typename T > using \fBiterator_category_t\fP = typename T::iterator_category"
.br
.ti -1c
.RI "template<typename T > using \fBiterator_t\fP = typename T::iterator"
.br
.ti -1c
.RI "template<typename T , typename\&.\&.\&. Args> using \fBto_json_function\fP = decltype(T::to_json(std::declval< Args >()\&.\&.\&.))"
.br
.ti -1c
.RI "template<typename T , typename\&.\&.\&. Args> using \fBfrom_json_function\fP = decltype(T::from_json(std::declval< Args >()\&.\&.\&.))"
.br
.ti -1c
.RI "template<typename T , typename U > using \fBget_template_function\fP = decltype(std::declval< T >()\&.template get< U >())"
.br
.ti -1c
.RI "using \fBinput_adapter_t\fP = std::shared_ptr< \fBinput_adapter_protocol\fP >"
.br
.RI "a type to simplify interfaces "
.ti -1c
.RI "template<typename T > using \fBnull_function_t\fP = decltype(std::declval< T & >()\&.null())"
.br
.ti -1c
.RI "template<typename T > using \fBboolean_function_t\fP = decltype(std::declval< T & >()\&.boolean(std::declval< bool >()))"
.br
.ti -1c
.RI "template<typename T , typename Integer > using \fBnumber_integer_function_t\fP = decltype(std::declval< T & >()\&.number_integer(std::declval< Integer >()))"
.br
.ti -1c
.RI "template<typename T , typename Unsigned > using \fBnumber_unsigned_function_t\fP = decltype(std::declval< T & >()\&.number_unsigned(std::declval< Unsigned >()))"
.br
.ti -1c
.RI "template<typename T , typename Float , typename String > using \fBnumber_float_function_t\fP = decltype(std::declval< T & >()\&.number_float(std::declval< Float >(), std::declval< const String & >()))"
.br
.ti -1c
.RI "template<typename T , typename String > using \fBstring_function_t\fP = decltype(std::declval< T & >()\&.string(std::declval< String & >()))"
.br
.ti -1c
.RI "template<typename T > using \fBstart_object_function_t\fP = decltype(std::declval< T & >()\&.start_object(std::declval< std::size_t >()))"
.br
.ti -1c
.RI "template<typename T , typename String > using \fBkey_function_t\fP = decltype(std::declval< T & >()\&.key(std::declval< String & >()))"
.br
.ti -1c
.RI "template<typename T > using \fBend_object_function_t\fP = decltype(std::declval< T & >()\&.end_object())"
.br
.ti -1c
.RI "template<typename T > using \fBstart_array_function_t\fP = decltype(std::declval< T & >()\&.start_array(std::declval< std::size_t >()))"
.br
.ti -1c
.RI "template<typename T > using \fBend_array_function_t\fP = decltype(std::declval< T & >()\&.end_array())"
.br
.ti -1c
.RI "template<typename T , typename Exception > using \fBparse_error_function_t\fP = decltype(std::declval< T & >()\&.\fBparse_error\fP(std::declval< std::size_t >(), std::declval< const std::string & >(), std::declval< const Exception & >()))"
.br
.ti -1c
.RI "template<typename CharType > using \fBoutput_adapter_t\fP = std::shared_ptr< \fBoutput_adapter_protocol\fP< CharType > >"
.br
.RI "a type to simplify interfaces "
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum class \fBinput_format_t\fP { \fBjson\fP, \fBcbor\fP, \fBmsgpack\fP, \fBubjson\fP, \fBbson\fP }"
.br
.RI "the supported input formats "
.ti -1c
.RI "enum class \fBerror_handler_t\fP { \fBstrict\fP, \fBreplace\fP, \fBignore\fP }"
.br
.RI "how to treat decoding errors "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename BasicJsonType , typename T , \fBenable_if_t\fP< std::is_same< T, typename BasicJsonType::boolean_t >::value, int >  = 0> void \fBto_json\fP (BasicJsonType &j, T b) noexcept"
.br
.ti -1c
.RI "template<typename BasicJsonType , typename CompatibleString , \fBenable_if_t\fP< std::is_constructible< typename BasicJsonType::string_t, CompatibleString >::value, int >  = 0> void \fBto_json\fP (BasicJsonType &j, const CompatibleString &s)"
.br
.ti -1c
.RI "template<typename BasicJsonType > void \fBto_json\fP (BasicJsonType &j, typename BasicJsonType::string_t &&s)"
.br
.ti -1c
.RI "template<typename BasicJsonType , typename FloatType , \fBenable_if_t\fP< std::is_floating_point< FloatType >::value, int >  = 0> void \fBto_json\fP (BasicJsonType &j, FloatType val) noexcept"
.br
.ti -1c
.RI "template<typename BasicJsonType , typename CompatibleNumberUnsignedType , \fBenable_if_t\fP< \fBis_compatible_integer_type\fP< typename BasicJsonType::number_unsigned_t, CompatibleNumberUnsignedType >::value, int >  = 0> void \fBto_json\fP (BasicJsonType &j, CompatibleNumberUnsignedType val) noexcept"
.br
.ti -1c
.RI "template<typename BasicJsonType , typename CompatibleNumberIntegerType , \fBenable_if_t\fP< \fBis_compatible_integer_type\fP< typename BasicJsonType::number_integer_t, CompatibleNumberIntegerType >::value, int >  = 0> void \fBto_json\fP (BasicJsonType &j, CompatibleNumberIntegerType val) noexcept"
.br
.ti -1c
.RI "template<typename BasicJsonType , typename EnumType , \fBenable_if_t\fP< std::is_enum< EnumType >::value, int >  = 0> void \fBto_json\fP (BasicJsonType &j, EnumType e) noexcept"
.br
.ti -1c
.RI "template<typename BasicJsonType > void \fBto_json\fP (BasicJsonType &j, const std::vector< bool > &e)"
.br
.ti -1c
.RI "template<typename BasicJsonType , typename CompatibleArrayType , \fBenable_if_t\fP< \fBis_compatible_array_type\fP< BasicJsonType, CompatibleArrayType >::value and not \fBis_compatible_object_type\fP< BasicJsonType, CompatibleArrayType >::value and not \fBis_compatible_string_type\fP< BasicJsonType, CompatibleArrayType >::value and not \fBis_basic_json\fP< CompatibleArrayType >::value, int >  = 0> void \fBto_json\fP (BasicJsonType &j, const CompatibleArrayType &arr)"
.br
.ti -1c
.RI "template<typename BasicJsonType , typename T , \fBenable_if_t\fP< std::is_convertible< T, BasicJsonType >::value, int >  = 0> void \fBto_json\fP (BasicJsonType &j, const std::valarray< T > &arr)"
.br
.ti -1c
.RI "template<typename BasicJsonType > void \fBto_json\fP (BasicJsonType &j, typename BasicJsonType::array_t &&arr)"
.br
.ti -1c
.RI "template<typename BasicJsonType , typename CompatibleObjectType , \fBenable_if_t\fP< \fBis_compatible_object_type\fP< BasicJsonType, CompatibleObjectType >::value and not \fBis_basic_json\fP< CompatibleObjectType >::value, int >  = 0> void \fBto_json\fP (BasicJsonType &j, const CompatibleObjectType &obj)"
.br
.ti -1c
.RI "template<typename BasicJsonType > void \fBto_json\fP (BasicJsonType &j, typename BasicJsonType::object_t &&obj)"
.br
.ti -1c
.RI "template<typename BasicJsonType , typename T , std::size_t N, \fBenable_if_t\fP< not std::is_constructible< typename BasicJsonType::string_t, const T(&)[N]>::value, int >  = 0> void \fBto_json\fP (BasicJsonType &j, const T(&arr)[N])"
.br
.ti -1c
.RI "template<typename BasicJsonType , typename\&.\&.\&. Args> void \fBto_json\fP (BasicJsonType &j, const std::pair< Args\&.\&.\&. > &p)"
.br
.ti -1c
.RI "template<typename BasicJsonType , typename T , \fBenable_if_t\fP< std::is_same< T, typename iteration_proxy< typename BasicJsonType::iterator >::iteration_proxy_internal >::value, int >  = 0> void \fBto_json\fP (BasicJsonType &j, const T &b)"
.br
.ti -1c
.RI "template<typename BasicJsonType , typename Tuple , std::size_t\&.\&.\&. Idx> void \fBto_json_tuple_impl\fP (BasicJsonType &j, const Tuple &t, \fBindex_sequence\fP< Idx\&.\&.\&. >)"
.br
.ti -1c
.RI "template<typename BasicJsonType , typename\&.\&.\&. Args> void \fBto_json\fP (BasicJsonType &j, const std::tuple< Args\&.\&.\&. > &t)"
.br
.in -1c
.SH "Detailed Description"
.PP 
detail namespace with internal helper functions 

This namespace collects functions that should not be exposed, implementations of some \fBbasic_json\fP methods, and meta-programming helpers\&.
.PP
\fBSince\fP
.RS 4
version 2\&.1\&.0 
.RE
.PP

.SH "Typedef Documentation"
.PP 
.SS "template<typename T > using \fBnlohmann::detail::boolean_function_t\fP = typedef decltype(std::declval<T&>()\&.boolean(std::declval<bool>()))"

.PP
Definition at line \fB3993\fP of file \fBjson\&.hpp\fP\&.
.SS "template<class Default , template< class\&.\&.\&. > class Op, class\&.\&.\&. Args> using \fBnlohmann::detail::detected_or\fP = typedef \fBdetector\fP<Default, void, Op, Args\&.\&.\&.>"

.PP
Definition at line \fB387\fP of file \fBjson\&.hpp\fP\&.
.SS "template<class Default , template< class\&.\&.\&. > class Op, class\&.\&.\&. Args> using \fBnlohmann::detail::detected_or_t\fP = typedef typename \fBdetected_or\fP<Default, Op, Args\&.\&.\&.>::type"

.PP
Definition at line \fB390\fP of file \fBjson\&.hpp\fP\&.
.SS "template<template< class\&.\&.\&. > class Op, class\&.\&.\&. Args> using \fBnlohmann::detail::detected_t\fP = typedef typename \fBdetector\fP<\fBnonesuch\fP, void, Op, Args\&.\&.\&.>::type"

.PP
Definition at line \fB384\fP of file \fBjson\&.hpp\fP\&.
.SS "template<typename T > using \fBnlohmann::detail::difference_type_t\fP = typedef typename T::difference_type"

.PP
Definition at line \fB448\fP of file \fBjson\&.hpp\fP\&.
.SS "template<bool B, typename T  = void> using \fBnlohmann::detail::enable_if_t\fP = typedef typename std::enable_if<B, T>::type"

.PP
Definition at line \fB265\fP of file \fBjson\&.hpp\fP\&.
.SS "template<typename T > using \fBnlohmann::detail::end_array_function_t\fP = typedef decltype(std::declval<T&>()\&.end_array())"

.PP
Definition at line \fB4028\fP of file \fBjson\&.hpp\fP\&.
.SS "template<typename T > using \fBnlohmann::detail::end_object_function_t\fP = typedef decltype(std::declval<T&>()\&.end_object())"

.PP
Definition at line \fB4021\fP of file \fBjson\&.hpp\fP\&.
.SS "template<typename T , typename\&.\&.\&. Args> using \fBnlohmann::detail::from_json_function\fP = typedef decltype(T::from_json(std::declval<Args>()\&.\&.\&.))"

.PP
Definition at line \fB466\fP of file \fBjson\&.hpp\fP\&.
.SS "template<typename T , typename U > using \fBnlohmann::detail::get_template_function\fP = typedef decltype(std::declval<T>()\&.template get<U>())"

.PP
Definition at line \fB469\fP of file \fBjson\&.hpp\fP\&.
.SS "template<typename\&.\&.\&. Ts> using \fBnlohmann::detail::index_sequence_for\fP = typedef \fBmake_index_sequence\fP<sizeof\&.\&.\&.(Ts)>"

.PP
Definition at line \fB299\fP of file \fBjson\&.hpp\fP\&.
.SS "using \fBnlohmann::detail::input_adapter_t\fP = typedef std::shared_ptr<\fBinput_adapter_protocol\fP>"

.PP
a type to simplify interfaces 
.PP
Definition at line \fB2095\fP of file \fBjson\&.hpp\fP\&.
.SS "template<template< class\&.\&.\&. > class Op, class\&.\&.\&. Args> using \fBnlohmann::detail::is_detected\fP = typedef typename \fBdetector\fP<\fBnonesuch\fP, void, Op, Args\&.\&.\&.>::value_t"

.PP
Definition at line \fB381\fP of file \fBjson\&.hpp\fP\&.
.SS "template<class To , template< class\&.\&.\&. > class Op, class\&.\&.\&. Args> using \fBnlohmann::detail::is_detected_convertible\fP = typedef std::is_convertible<\fBdetected_t\fP<Op, Args\&.\&.\&.>, To>"

.PP
Definition at line \fB396\fP of file \fBjson\&.hpp\fP\&.
.SS "template<class Expected , template< class\&.\&.\&. > class Op, class\&.\&.\&. Args> using \fBnlohmann::detail::is_detected_exact\fP = typedef std::is_same<Expected, \fBdetected_t\fP<Op, Args\&.\&.\&.> >"

.PP
Definition at line \fB393\fP of file \fBjson\&.hpp\fP\&.
.SS "template<typename T > using \fBnlohmann::detail::iterator_category_t\fP = typedef typename T::iterator_category"

.PP
Definition at line \fB457\fP of file \fBjson\&.hpp\fP\&.
.SS "template<typename T > using \fBnlohmann::detail::iterator_t\fP = typedef typename T::iterator"

.PP
Definition at line \fB460\fP of file \fBjson\&.hpp\fP\&.
.SS "template<typename T , typename String > using \fBnlohmann::detail::key_function_t\fP = typedef decltype(std::declval<T&>()\&.key(std::declval<String&>()))"

.PP
Definition at line \fB4017\fP of file \fBjson\&.hpp\fP\&.
.SS "template<typename T > using \fBnlohmann::detail::key_type_t\fP = typedef typename T::key_type"

.PP
Definition at line \fB442\fP of file \fBjson\&.hpp\fP\&.
.SS "template<typename T > using \fBnlohmann::detail::mapped_type_t\fP = typedef typename T::mapped_type"

.PP
Definition at line \fB439\fP of file \fBjson\&.hpp\fP\&.
.SS "template<typename T > using \fBnlohmann::detail::null_function_t\fP = typedef decltype(std::declval<T&>()\&.null())"

.PP
Definition at line \fB3990\fP of file \fBjson\&.hpp\fP\&.
.SS "template<typename T , typename Float , typename String > using \fBnlohmann::detail::number_float_function_t\fP = typedef decltype(std::declval<T&>()\&.number_float( std::declval<Float>(), std::declval<const String&>()))"

.PP
Definition at line \fB4005\fP of file \fBjson\&.hpp\fP\&.
.SS "template<typename T , typename Integer > using \fBnlohmann::detail::number_integer_function_t\fP = typedef decltype(std::declval<T&>()\&.number_integer(std::declval<Integer>()))"

.PP
Definition at line \fB3997\fP of file \fBjson\&.hpp\fP\&.
.SS "template<typename T , typename Unsigned > using \fBnlohmann::detail::number_unsigned_function_t\fP = typedef decltype(std::declval<T&>()\&.number_unsigned(std::declval<Unsigned>()))"

.PP
Definition at line \fB4001\fP of file \fBjson\&.hpp\fP\&.
.SS "template<typename CharType > using \fBnlohmann::detail::output_adapter_t\fP = typedef std::shared_ptr<\fBoutput_adapter_protocol\fP<CharType> >"

.PP
a type to simplify interfaces 
.PP
Definition at line \fB6240\fP of file \fBjson\&.hpp\fP\&.
.SS "template<typename T , typename Exception > using \fBnlohmann::detail::parse_error_function_t\fP = typedef decltype(std::declval<T&>()\&.\fBparse_error\fP( std::declval<std::size_t>(), std::declval<const std::string&>(), std::declval<const Exception&>()))"

.PP
Definition at line \fB4031\fP of file \fBjson\&.hpp\fP\&.
.SS "template<typename T > using \fBnlohmann::detail::pointer_t\fP = typedef typename T::pointer"

.PP
Definition at line \fB451\fP of file \fBjson\&.hpp\fP\&.
.SS "template<typename T > using \fBnlohmann::detail::reference_t\fP = typedef typename T::reference"

.PP
Definition at line \fB454\fP of file \fBjson\&.hpp\fP\&.
.SS "template<typename T > using \fBnlohmann::detail::start_array_function_t\fP = typedef decltype(std::declval<T&>()\&.start_array(std::declval<std::size_t>()))"

.PP
Definition at line \fB4024\fP of file \fBjson\&.hpp\fP\&.
.SS "template<typename T > using \fBnlohmann::detail::start_object_function_t\fP = typedef decltype(std::declval<T&>()\&.start_object(std::declval<std::size_t>()))"

.PP
Definition at line \fB4013\fP of file \fBjson\&.hpp\fP\&.
.SS "template<typename T , typename String > using \fBnlohmann::detail::string_function_t\fP = typedef decltype(std::declval<T&>()\&.string(std::declval<String&>()))"

.PP
Definition at line \fB4009\fP of file \fBjson\&.hpp\fP\&.
.SS "template<typename T , typename\&.\&.\&. Args> using \fBnlohmann::detail::to_json_function\fP = typedef decltype(T::to_json(std::declval<Args>()\&.\&.\&.))"

.PP
Definition at line \fB463\fP of file \fBjson\&.hpp\fP\&.
.SS "template<typename T > using \fBnlohmann::detail::uncvref_t\fP = typedef typename std::remove_cv<typename std::remove_reference<T>::type>::type"

.PP
Definition at line \fB268\fP of file \fBjson\&.hpp\fP\&.
.SS "template<typename T > using \fBnlohmann::detail::value_type_t\fP = typedef typename T::value_type"

.PP
Definition at line \fB445\fP of file \fBjson\&.hpp\fP\&.
.SS "template<typename \&.\&.\&. Ts> using \fBnlohmann::detail::void_t\fP = typedef typename \fBmake_void\fP<Ts\&.\&.\&.>::type"

.PP
Definition at line \fB345\fP of file \fBjson\&.hpp\fP\&.
.SH "Enumeration Type Documentation"
.PP 
.SS "enum class \fBnlohmann::detail::error_handler_t\fP\fC [strong]\fP"

.PP
how to treat decoding errors 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIstrict \fP\fP
throw a \fBtype_error\fP exception in case of invalid UTF-8 
.TP
\fB\fIreplace \fP\fP
replace invalid UTF-8 sequences with U+FFFD 
.TP
\fB\fIignore \fP\fP
ignore invalid UTF-8 sequences 
.PP
Definition at line \fB10804\fP of file \fBjson\&.hpp\fP\&.
.SS "enum class \fBnlohmann::detail::input_format_t\fP\fC [strong]\fP"

.PP
the supported input formats 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIjson \fP\fP
.TP
\fB\fIcbor \fP\fP
.TP
\fB\fImsgpack \fP\fP
.TP
\fB\fIubjson \fP\fP
.TP
\fB\fIbson \fP\fP
.PP
Definition at line \fB2070\fP of file \fBjson\&.hpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "template<typename BasicJsonType , typename CompatibleNumberIntegerType , \fBenable_if_t\fP< \fBis_compatible_integer_type\fP< typename BasicJsonType::number_integer_t, CompatibleNumberIntegerType >::value, int >  = 0> void nlohmann::detail::to_json (BasicJsonType & j, CompatibleNumberIntegerType val)\fC [noexcept]\fP"

.PP
Definition at line \fB1936\fP of file \fBjson\&.hpp\fP\&.
.SS "template<typename BasicJsonType , typename CompatibleNumberUnsignedType , \fBenable_if_t\fP< \fBis_compatible_integer_type\fP< typename BasicJsonType::number_unsigned_t, CompatibleNumberUnsignedType >::value, int >  = 0> void nlohmann::detail::to_json (BasicJsonType & j, CompatibleNumberUnsignedType val)\fC [noexcept]\fP"

.PP
Definition at line \fB1929\fP of file \fBjson\&.hpp\fP\&.
.SS "template<typename BasicJsonType , typename CompatibleArrayType , \fBenable_if_t\fP< \fBis_compatible_array_type\fP< BasicJsonType, CompatibleArrayType >::value and not \fBis_compatible_object_type\fP< BasicJsonType, CompatibleArrayType >::value and not \fBis_compatible_string_type\fP< BasicJsonType, CompatibleArrayType >::value and not \fBis_basic_json\fP< CompatibleArrayType >::value, int >  = 0> void nlohmann::detail::to_json (BasicJsonType & j, const CompatibleArrayType & arr)"

.PP
Definition at line \fB1963\fP of file \fBjson\&.hpp\fP\&.
.SS "template<typename BasicJsonType , typename CompatibleObjectType , \fBenable_if_t\fP< \fBis_compatible_object_type\fP< BasicJsonType, CompatibleObjectType >::value and not \fBis_basic_json\fP< CompatibleObjectType >::value, int >  = 0> void nlohmann::detail::to_json (BasicJsonType & j, const CompatibleObjectType & obj)"

.PP
Definition at line \fB1983\fP of file \fBjson\&.hpp\fP\&.
.SS "template<typename BasicJsonType , typename CompatibleString , \fBenable_if_t\fP< std::is_constructible< typename BasicJsonType::string_t, CompatibleString >::value, int >  = 0> void nlohmann::detail::to_json (BasicJsonType & j, const CompatibleString & s)"

.PP
Definition at line \fB1909\fP of file \fBjson\&.hpp\fP\&.
.SS "template<typename BasicJsonType , typename\&.\&.\&. Args> void nlohmann::detail::to_json (BasicJsonType & j, const std::pair< Args\&.\&.\&. > & p)"

.PP
Definition at line \fB2005\fP of file \fBjson\&.hpp\fP\&.
.SS "template<typename BasicJsonType , typename\&.\&.\&. Args> void nlohmann::detail::to_json (BasicJsonType & j, const std::tuple< Args\&.\&.\&. > & t)"

.PP
Definition at line \fB2025\fP of file \fBjson\&.hpp\fP\&.
.SS "template<typename BasicJsonType , typename T , \fBenable_if_t\fP< std::is_convertible< T, BasicJsonType >::value, int >  = 0> void nlohmann::detail::to_json (BasicJsonType & j, const std::valarray< T > & arr)"

.PP
Definition at line \fB1970\fP of file \fBjson\&.hpp\fP\&.
.SS "template<typename BasicJsonType > void nlohmann::detail::to_json (BasicJsonType & j, const std::vector< bool > & e)"

.PP
Definition at line \fB1950\fP of file \fBjson\&.hpp\fP\&.
.SS "template<typename BasicJsonType , typename T , \fBenable_if_t\fP< std::is_same< T, typename iteration_proxy< typename BasicJsonType::iterator >::iteration_proxy_internal >::value, int >  = 0> void nlohmann::detail::to_json (BasicJsonType & j, const T & b)"

.PP
Definition at line \fB2013\fP of file \fBjson\&.hpp\fP\&.
.SS "template<typename BasicJsonType , typename T , std::size_t N, \fBenable_if_t\fP< not std::is_constructible< typename BasicJsonType::string_t, const T(&)[N]>::value, int >  = 0> void nlohmann::detail::to_json (BasicJsonType & j, const T(&) arr[N])"

.PP
Definition at line \fB1999\fP of file \fBjson\&.hpp\fP\&.
.SS "template<typename BasicJsonType , typename EnumType , \fBenable_if_t\fP< std::is_enum< EnumType >::value, int >  = 0> void nlohmann::detail::to_json (BasicJsonType & j, EnumType e)\fC [noexcept]\fP"

.PP
Definition at line \fB1943\fP of file \fBjson\&.hpp\fP\&.
.SS "template<typename BasicJsonType , typename FloatType , \fBenable_if_t\fP< std::is_floating_point< FloatType >::value, int >  = 0> void nlohmann::detail::to_json (BasicJsonType & j, FloatType val)\fC [noexcept]\fP"

.PP
Definition at line \fB1922\fP of file \fBjson\&.hpp\fP\&.
.SS "template<typename BasicJsonType , typename T , \fBenable_if_t\fP< std::is_same< T, typename BasicJsonType::boolean_t >::value, int >  = 0> void nlohmann::detail::to_json (BasicJsonType & j, T b)\fC [noexcept]\fP"

.PP
Definition at line \fB1902\fP of file \fBjson\&.hpp\fP\&.
.SS "template<typename BasicJsonType > void nlohmann::detail::to_json (BasicJsonType & j, typename BasicJsonType::array_t && arr)"

.PP
Definition at line \fB1976\fP of file \fBjson\&.hpp\fP\&.
.SS "template<typename BasicJsonType > void nlohmann::detail::to_json (BasicJsonType & j, typename BasicJsonType::object_t && obj)"

.PP
Definition at line \fB1989\fP of file \fBjson\&.hpp\fP\&.
.SS "template<typename BasicJsonType > void nlohmann::detail::to_json (BasicJsonType & j, typename BasicJsonType::string_t && s)"

.PP
Definition at line \fB1915\fP of file \fBjson\&.hpp\fP\&.
.SS "template<typename BasicJsonType , typename Tuple , std::size_t\&.\&.\&. Idx> void nlohmann::detail::to_json_tuple_impl (BasicJsonType & j, const Tuple & t, \fBindex_sequence\fP< Idx\&.\&.\&. >)"

.PP
Definition at line \fB2019\fP of file \fBjson\&.hpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
