.TH "nlohmann::detail::external_constructor< value_t::number_unsigned >" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nlohmann::detail::external_constructor< value_t::number_unsigned >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <json\&.hpp>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename BasicJsonType > \fBstatic\fP void \fBconstruct\fP (BasicJsonType &j, typename BasicJsonType::number_unsigned_t val) noexcept"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB1785\fP of file \fBjson\&.hpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "template<typename BasicJsonType > \fBstatic\fP void \fBnlohmann::detail::external_constructor\fP< value_t::number_unsigned >::construct (BasicJsonType & j, typename BasicJsonType::number_unsigned_t val)\fC [inline]\fP, \fC [static]\fP, \fC [noexcept]\fP"

.PP
Definition at line \fB1788\fP of file \fBjson\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
