.TH "nlohmann::json_pointer< BasicJsonType >" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nlohmann::json_pointer< BasicJsonType > \- JSON Pointer\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBjson_pointer\fP (const std::string &s='')"
.br
.RI "create JSON pointer "
.ti -1c
.RI "std::string \fBto_string\fP () const"
.br
.RI "return a string representation of the JSON pointer "
.ti -1c
.RI "\fBoperator std::string\fP () const"
.br
.RI "return a string representation of the JSON pointer   "
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "\fBstatic\fP int \fBarray_index\fP (const std::string &s)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBbasic_json\fP"
.br
.ti -1c
.RI "bool \fBoperator==\fP (\fBjson_pointer\fP const &lhs, \fBjson_pointer\fP const &rhs) noexcept"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (\fBjson_pointer\fP const &lhs, \fBjson_pointer\fP const &rhs) noexcept"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename BasicJsonType>
.br
class nlohmann::json_pointer< BasicJsonType >"JSON Pointer\&. 

A JSON pointer defines a string syntax for identifying a specific value within a JSON document\&. It can be used with functions \fCat\fP and \fCoperator[]\fP\&. Furthermore, JSON pointers are the base for JSON patches\&.
.PP
\fBSee also\fP
.RS 4
\fCRFC 6901\fP
.RE
.PP
\fBSince\fP
.RS 4
version 2\&.0\&.0 
.RE
.PP

.PP
Definition at line \fB11604\fP of file \fBjson\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename BasicJsonType > \fBnlohmann::json_pointer\fP< BasicJsonType >::json_pointer (const std::string & s = \fC''\fP)\fC [inline]\fP, \fC [explicit]\fP"

.PP
create JSON pointer Create a JSON pointer according to the syntax described in \fCSection 3 of RFC6901\fP\&.
.PP
\fBParameters\fP
.RS 4
\fIs\fP string representing the JSON pointer; if omitted, the empty string is assumed which references the whole JSON value
.RE
.PP
\fBExceptions\fP
.RS 4
\fIparse_error\&.107\fP if the given JSON pointer \fIs\fP is nonempty and does not begin with a slash (\fC/\fP); see example below
.br
\fIparse_error\&.108\fP if a tilde (\fC~\fP) in the given JSON pointer \fIs\fP is not followed by \fC0\fP (representing \fC~\fP) or \fC1\fP (representing \fC/\fP); see example below
.RE
.PP
@liveexample{The example shows the construction several valid JSON pointers as well as the exceptional behavior\&.,\fBjson_pointer\fP}
.PP
\fBSince\fP
.RS 4
version 2\&.0\&.0 
.RE
.PP

.PP
Definition at line \fB11632\fP of file \fBjson\&.hpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "template<typename BasicJsonType > \fBstatic\fP int \fBnlohmann::json_pointer\fP< BasicJsonType >::array_index (const std::string & s)\fC [inline]\fP, \fC [static]\fP"

.PP
\fBParameters\fP
.RS 4
\fIs\fP reference token to be converted into an array index
.RE
.PP
\fBReturns\fP
.RS 4
integer representation of \fIs\fP 
.RE
.PP
\fBExceptions\fP
.RS 4
\fIout_of_range\&.404\fP if string \fIs\fP could not be converted to an integer 
.RE
.PP

.PP
Definition at line \fB11674\fP of file \fBjson\&.hpp\fP\&.
.SS "template<typename BasicJsonType > \fBnlohmann::json_pointer\fP< BasicJsonType >::operator std::string () const\fC [inline]\fP"

.PP
return a string representation of the JSON pointer   
.PP
\fBInvariant\fP
.RS 4
For each JSON pointer \fCptr\fP, it holds: 
.PP
.nf
ptr == json_pointer(ptr\&.to_string());

.fi
.PP
.RE
.PP
\fBReturns\fP
.RS 4
a string representation of the JSON pointer
.RE
.PP
@liveexample{The example shows the result of \fCto_string\fP\&., json_pointer__to_string}
.PP
\fBSince\fP
.RS 4
version 2\&.0\&.0   
.RE
.PP

.PP
Definition at line \fB11662\fP of file \fBjson\&.hpp\fP\&.
.SS "template<typename BasicJsonType > std::string \fBnlohmann::json_pointer\fP< BasicJsonType >::to_string () const\fC [inline]\fP"

.PP
return a string representation of the JSON pointer 
.PP
\fBInvariant\fP
.RS 4
For each JSON pointer \fCptr\fP, it holds: 
.PP
.nf
ptr == json_pointer(ptr\&.to_string());

.fi
.PP
.RE
.PP
\fBReturns\fP
.RS 4
a string representation of the JSON pointer
.RE
.PP
@liveexample{The example shows the result of \fCto_string\fP\&., json_pointer__to_string}
.PP
\fBSince\fP
.RS 4
version 2\&.0\&.0 
.RE
.PP

.PP
Definition at line \fB11651\fP of file \fBjson\&.hpp\fP\&.
.SH "Friends And Related Symbol Documentation"
.PP 
.SS "template<typename BasicJsonType > friend class \fBbasic_json\fP\fC [friend]\fP"

.PP
Definition at line \fB11608\fP of file \fBjson\&.hpp\fP\&.
.SS "template<typename BasicJsonType > bool operator!= (\fBjson_pointer\fP< BasicJsonType > const & lhs, \fBjson_pointer\fP< BasicJsonType > const & rhs)\fC [friend]\fP"

.PP
Definition at line \fB12276\fP of file \fBjson\&.hpp\fP\&.
.SS "template<typename BasicJsonType > bool operator== (\fBjson_pointer\fP< BasicJsonType > const & lhs, \fBjson_pointer\fP< BasicJsonType > const & rhs)\fC [friend]\fP"

.PP
Definition at line \fB12270\fP of file \fBjson\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
