.TH "nlohmann::detail::has_to_json< BasicJsonType, T, typename >" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nlohmann::detail::has_to_json< BasicJsonType, T, typename >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <json\&.hpp>\fP
.PP
Inherits std::false_type\&.
.SH "Detailed Description"
.PP 

.SS "template<typename BasicJsonType, typename T, typename = void>
.br
struct nlohmann::detail::has_to_json< BasicJsonType, T, typename >"
.PP
Definition at line \fB504\fP of file \fBjson\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
