.TH "nlohmann::detail::is_basic_json< NLOHMANN_BASIC_JSON_TPL >" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nlohmann::detail::is_basic_json< NLOHMANN_BASIC_JSON_TPL >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <json\&.hpp>\fP
.PP
Inherits std::true_type\&.
.SH "Detailed Description"
.PP 
Definition at line \fB432\fP of file \fBjson\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
