.TH "nlohmann::detail::is_compatible_array_type< BasicJsonType, CompatibleArrayType >" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nlohmann::detail::is_compatible_array_type< BasicJsonType, CompatibleArrayType >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <json\&.hpp>\fP
.PP
Inherits \fBnlohmann::detail::is_compatible_array_type_impl< BasicJsonType, CompatibleArrayType, typename >\fP\&.
.SH "Detailed Description"
.PP 

.SS "template<typename BasicJsonType, typename CompatibleArrayType>
.br
struct nlohmann::detail::is_compatible_array_type< BasicJsonType, CompatibleArrayType >"
.PP
Definition at line \fB653\fP of file \fBjson\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
