.TH "nlohmann::detail::input_adapter" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nlohmann::detail::input_adapter
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <json\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBinput_adapter\fP (std::istream &i)"
.br
.RI "input adapter for input stream "
.ti -1c
.RI "\fBinput_adapter\fP (std::istream &&i)"
.br
.RI "input adapter for input stream "
.ti -1c
.RI "\fBinput_adapter\fP (const std::wstring &ws)"
.br
.ti -1c
.RI "\fBinput_adapter\fP (const std::u16string &ws)"
.br
.ti -1c
.RI "\fBinput_adapter\fP (const std::u32string &ws)"
.br
.ti -1c
.RI "template<typename CharT , typename std::enable_if< std::is_pointer< CharT >::value and std::is_integral< typename std::remove_pointer< CharT >::type >::value and sizeof(typename std::remove_pointer< CharT >::type)==1, int >::type  = 0> \fBinput_adapter\fP (CharT b, std::size_t l)"
.br
.RI "input adapter for buffer "
.ti -1c
.RI "template<typename CharT , typename std::enable_if< std::is_pointer< CharT >::value and std::is_integral< typename std::remove_pointer< CharT >::type >::value and sizeof(typename std::remove_pointer< CharT >::type)==1, int >::type  = 0> \fBinput_adapter\fP (CharT b)"
.br
.RI "input adapter for string literal "
.ti -1c
.RI "template<class IteratorType , typename std::enable_if< std::is_same< typename std::iterator_traits< IteratorType >::iterator_category, std::random_access_iterator_tag >::value, int >::type  = 0> \fBinput_adapter\fP (IteratorType first, IteratorType last)"
.br
.RI "input adapter for iterator range with contiguous storage "
.ti -1c
.RI "template<class T , std::size_t N> \fBinput_adapter\fP (T(&array)[N])"
.br
.RI "input adapter for array "
.ti -1c
.RI "template<class ContiguousContainer , typename std::enable_if< not std::is_pointer< ContiguousContainer >::value and std::is_base_of< std::random_access_iterator_tag, typename std::iterator_traits< decltype(std::begin(std::declval< ContiguousContainer const >()))>::iterator_category >::value , int , ::type  = 0> \fBinput_adapter\fP (const ContiguousContainer &c)"
.br
.RI "input adapter for contiguous container "
.ti -1c
.RI "\fBoperator input_adapter_t\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB2341\fP of file \fBjson\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "nlohmann::detail::input_adapter::input_adapter (std::istream & i)\fC [inline]\fP"

.PP
input adapter for input stream 
.PP
Definition at line \fB2347\fP of file \fBjson\&.hpp\fP\&.
.SS "nlohmann::detail::input_adapter::input_adapter (std::istream && i)\fC [inline]\fP"

.PP
input adapter for input stream 
.PP
Definition at line \fB2351\fP of file \fBjson\&.hpp\fP\&.
.SS "nlohmann::detail::input_adapter::input_adapter (const std::wstring & ws)\fC [inline]\fP"

.PP
Definition at line \fB2354\fP of file \fBjson\&.hpp\fP\&.
.SS "nlohmann::detail::input_adapter::input_adapter (const std::u16string & ws)\fC [inline]\fP"

.PP
Definition at line \fB2357\fP of file \fBjson\&.hpp\fP\&.
.SS "nlohmann::detail::input_adapter::input_adapter (const std::u32string & ws)\fC [inline]\fP"

.PP
Definition at line \fB2360\fP of file \fBjson\&.hpp\fP\&.
.SS "template<typename CharT , typename std::enable_if< std::is_pointer< CharT >::value and std::is_integral< typename std::remove_pointer< CharT >::type >::value and sizeof(typename std::remove_pointer< CharT >::type)==1, int >::type  = 0> nlohmann::detail::input_adapter::input_adapter (CharT b, std::size_t l)\fC [inline]\fP"

.PP
input adapter for buffer 
.PP
Definition at line \fB2370\fP of file \fBjson\&.hpp\fP\&.
.SS "template<typename CharT , typename std::enable_if< std::is_pointer< CharT >::value and std::is_integral< typename std::remove_pointer< CharT >::type >::value and sizeof(typename std::remove_pointer< CharT >::type)==1, int >::type  = 0> nlohmann::detail::input_adapter::input_adapter (CharT b)\fC [inline]\fP"

.PP
input adapter for string literal 
.PP
Definition at line \fB2382\fP of file \fBjson\&.hpp\fP\&.
.SS "template<class IteratorType , typename std::enable_if< std::is_same< typename std::iterator_traits< IteratorType >::iterator_category, std::random_access_iterator_tag >::value, int >::type  = 0> nlohmann::detail::input_adapter::input_adapter (IteratorType first, IteratorType last)\fC [inline]\fP"

.PP
input adapter for iterator range with contiguous storage 
.PP
Definition at line \fB2391\fP of file \fBjson\&.hpp\fP\&.
.SS "template<class T , std::size_t N> nlohmann::detail::input_adapter::input_adapter (T(&) array[N])\fC [inline]\fP"

.PP
input adapter for array 
.PP
Definition at line \fB2426\fP of file \fBjson\&.hpp\fP\&.
.SS "template<class ContiguousContainer , typename std::enable_if< not std::is_pointer< ContiguousContainer >::value and std::is_base_of< std::random_access_iterator_tag, typename std::iterator_traits< decltype(std::begin(std::declval< ContiguousContainer const >()))>::iterator_category >::value , int , ::type  = 0> nlohmann::detail::input_adapter::input_adapter (const ContiguousContainer & c)\fC [inline]\fP"

.PP
input adapter for contiguous container 
.PP
Definition at line \fB2434\fP of file \fBjson\&.hpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "nlohmann::detail::input_adapter::operator \fBinput_adapter_t\fP ()\fC [inline]\fP"

.PP
Definition at line \fB2437\fP of file \fBjson\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
