.TH "nlohmann::detail::external_constructor< value_t::object >" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nlohmann::detail::external_constructor< value_t::object >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <json\&.hpp>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename BasicJsonType > \fBstatic\fP void \fBconstruct\fP (BasicJsonType &j, const typename BasicJsonType::object_t &obj)"
.br
.ti -1c
.RI "template<typename BasicJsonType > \fBstatic\fP void \fBconstruct\fP (BasicJsonType &j, typename BasicJsonType::object_t &&obj)"
.br
.ti -1c
.RI "template<typename BasicJsonType , typename CompatibleObjectType , \fBenable_if_t\fP< not std::is_same< CompatibleObjectType, typename BasicJsonType::object_t >::value, int >  = 0> \fBstatic\fP void \fBconstruct\fP (BasicJsonType &j, const CompatibleObjectType &obj)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB1865\fP of file \fBjson\&.hpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "template<typename BasicJsonType , typename CompatibleObjectType , \fBenable_if_t\fP< not std::is_same< CompatibleObjectType, typename BasicJsonType::object_t >::value, int >  = 0> \fBstatic\fP void \fBnlohmann::detail::external_constructor\fP< value_t::object >::construct (BasicJsonType & j, const CompatibleObjectType & obj)\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line \fB1885\fP of file \fBjson\&.hpp\fP\&.
.SS "template<typename BasicJsonType > \fBstatic\fP void \fBnlohmann::detail::external_constructor\fP< value_t::object >::construct (BasicJsonType & j, const typename BasicJsonType::object_t & obj)\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line \fB1868\fP of file \fBjson\&.hpp\fP\&.
.SS "template<typename BasicJsonType > \fBstatic\fP void \fBnlohmann::detail::external_constructor\fP< value_t::object >::construct (BasicJsonType & j, typename BasicJsonType::object_t && obj)\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line \fB1876\fP of file \fBjson\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
