.TH "deps/base_avc/src/output.c" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deps/base_avc/src/output.c \- Output an image and Trance support\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'contributors\&.h'\fP
.br
\fC#include 'global\&.h'\fP
.br
\fC#include 'mbuffer\&.h'\fP
.br
\fC#include 'image\&.h'\fP
.br
\fC#include 'memalloc\&.h'\fP
.br
\fC#include 'sei\&.h'\fP
.br
\fC#include 'input\&.h'\fP
.br
\fC#include 'fast_memory\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBinit_output\fP (CodingParameters *p_cps, int symbol_size_in_bytes)"
.br
.RI "selects appropriate output function given system arch\&. and data "
.ti -1c
.RI "void \fBwrite_picture\fP (VideoParameters *p_Vid, StorablePicture *p, int p_out, int real_structure)"
.br
.RI "Writes out a storable picture without doing any output modifications\&. "
.ti -1c
.RI "void \fBinit_out_buffer\fP (VideoParameters *p_Vid)"
.br
.RI "Initialize output buffer for direct output\&. "
.ti -1c
.RI "void \fBuninit_out_buffer\fP (VideoParameters *p_Vid)"
.br
.RI "Uninitialize output buffer for direct output\&. "
.ti -1c
.RI "void \fBclear_picture\fP (VideoParameters *p_Vid, StorablePicture *p)"
.br
.RI "Initialize picture memory with (Y:0,U:128,V:128) "
.ti -1c
.RI "void \fBwrite_unpaired_field\fP (VideoParameters *p_Vid, FrameStore *fs, int p_out)"
.br
.RI "Write out not paired direct output fields\&. A second empty field is generated and combined into the frame buffer\&. "
.ti -1c
.RI "void \fBflush_direct_output\fP (VideoParameters *p_Vid, int p_out)"
.br
.RI "Write out unpaired fields from output buffer\&. "
.ti -1c
.RI "void \fBwrite_stored_frame\fP (VideoParameters *p_Vid, FrameStore *fs, int p_out)"
.br
.RI "Write a frame (from FrameStore) "
.ti -1c
.RI "void \fBdirect_output\fP (VideoParameters *p_Vid, StorablePicture *p, int p_out)"
.br
.RI "Directly output a picture without storing it in the DPB\&. Fields are buffered before they are written to the file\&. "
.in -1c
.SH "Detailed Description"
.PP 
Output an image and Trance support\&. 


.PP
\fBAuthor\fP
.RS 4
Main contributors (see contributors\&.h for copyright, address and affiliation details)
.IP "\(bu" 2
Karsten Suehring 
.PP
.RE
.PP

.PP
Definition in file \fBoutput\&.c\fP\&.
.SH "Function Documentation"
.PP 
.SS "void clear_picture (VideoParameters * p_Vid, StorablePicture * p)"

.PP
Initialize picture memory with (Y:0,U:128,V:128) 
.PP
Definition at line \fB717\fP of file \fBoutput\&.c\fP\&.
.SS "void direct_output (VideoParameters * p_Vid, StorablePicture * p, int p_out)"

.PP
Directly output a picture without storing it in the DPB\&. Fields are buffered before they are written to the file\&. 
.PP
\fBParameters\fP
.RS 4
\fIp_Vid\fP image decoding parameters for current picture 
.br
\fIp\fP Picture for output 
.br
\fIp_out\fP Output file 
.RE
.PP

.PP
Definition at line \fB870\fP of file \fBoutput\&.c\fP\&.
.SS "void flush_direct_output (VideoParameters * p_Vid, int p_out)"

.PP
Write out unpaired fields from output buffer\&. 
.PP
\fBParameters\fP
.RS 4
\fIp_Vid\fP image decoding parameters for current picture 
.br
\fIp_out\fP Output file 
.RE
.PP

.PP
Definition at line \fB809\fP of file \fBoutput\&.c\fP\&.
.SS "void init_out_buffer (VideoParameters * p_Vid)"

.PP
Initialize output buffer for direct output\&. 
.PP
Definition at line \fB683\fP of file \fBoutput\&.c\fP\&.
.SS "void init_output (CodingParameters * p_cps, int symbol_size_in_bytes)"

.PP
selects appropriate output function given system arch\&. and data 
.PP
\fBReturns\fP
.RS 4

.RE
.PP

.PP
Definition at line \fB41\fP of file \fBoutput\&.c\fP\&.
.SS "void uninit_out_buffer (VideoParameters * p_Vid)"

.PP
Uninitialize output buffer for direct output\&. 
.PP
Definition at line \fB701\fP of file \fBoutput\&.c\fP\&.
.SS "void write_picture (VideoParameters * p_Vid, StorablePicture * p, int p_out, int real_structure)"

.PP
Writes out a storable picture without doing any output modifications\&. 
.PP
\fBParameters\fP
.RS 4
\fIp_Vid\fP image decoding parameters for current picture 
.br
\fIp\fP Picture to be written 
.br
\fIp_out\fP Output file 
.br
\fIreal_structure\fP real picture structure 
.RE
.PP

.PP
Definition at line \fB431\fP of file \fBoutput\&.c\fP\&.
.SS "void write_stored_frame (VideoParameters * p_Vid, FrameStore * fs, int p_out)"

.PP
Write a frame (from FrameStore) 
.PP
\fBParameters\fP
.RS 4
\fIp_Vid\fP image decoding parameters for current picture 
.br
\fIfs\fP FrameStore containing the frame 
.br
\fIp_out\fP Output file 
.RE
.PP

.PP
Definition at line \fB836\fP of file \fBoutput\&.c\fP\&.
.SS "void write_unpaired_field (VideoParameters * p_Vid, FrameStore * fs, int p_out)"

.PP
Write out not paired direct output fields\&. A second empty field is generated and combined into the frame buffer\&. 
.PP
\fBParameters\fP
.RS 4
\fIp_Vid\fP image decoding parameters for current picture 
.br
\fIfs\fP FrameStore that contains a single field 
.br
\fIp_out\fP Output file 
.RE
.PP

.PP
Definition at line \fB752\fP of file \fBoutput\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
