.TH "deps/base_vvc/minimum_VTM/source/Lib/CommonLib/ParameterSetManager.h" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deps/base_vvc/minimum_VTM/source/Lib/CommonLib/ParameterSetManager.h
.SH SYNOPSIS
.br
.PP
\fC#include 'Slice\&.h'\fP
.br
\fC#include <map>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBvtm::ParameterSetMap< T >\fP"
.br
.ti -1c
.RI "struct \fBvtm::ParameterSetMap< T >::MapData< Tm >\fP"
.br
.ti -1c
.RI "class \fBvtm::ParameterSetManager\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBvtm\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB__PARAMETERSETMANAGER__\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBvtm::calculateParameterSetChangedFlag\fP (bool &changed, const std::vector< uint8_t > *oldData, const std::vector< uint8_t > *newData)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define __PARAMETERSETMANAGER__"

.PP
Definition at line \fB37\fP of file \fBParameterSetManager\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
