.TH "encoder/include/ParameterDefaults.hpp" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
encoder/include/ParameterDefaults.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'Convert\&.hpp'\fP
.br
\fC#include 'Image\&.hpp'\fP
.br
\fC#include 'Parameters\&.hpp'\fP
.br
\fC#include 'SignaledConfiguration\&.hpp'\fP
.br
\fC#include 'Surface\&.hpp'\fP
.br
\fC#include 'TemporalEncode\&.hpp'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBlctm\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBParameters\fP \fBlctm::parameter_defaults_global\fP (const \fBParameters\fP &p)"
.br
.ti -1c
.RI "\fBParameters\fP \fBlctm::parameter_defaults_picture\fP (const \fBParameters\fP &p, std::vector< std::unique_ptr< \fBImage\fP > > &src_image, unsigned base_qp)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
