.TH "encoder/src/ParameterDefaults.cpp" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
encoder/src/ParameterDefaults.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'ParameterDefaults\&.hpp'\fP
.br
\fC#include 'Types\&.hpp'\fP
.br
\fC#include <array>\fP
.br
\fC#include <math\&.h>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBlctm\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename A , typename B , size_t N> B \fBlctm::piecewise_linear\fP (const std::array< A, N > &a, const std::array< B, N > &b, A v)"
.br
.ti -1c
.RI "\fBParameters\fP \fBlctm::parameter_defaults_global\fP (const \fBParameters\fP &p)"
.br
.ti -1c
.RI "\fBParameters\fP \fBlctm::parameter_defaults_picture\fP (const \fBParameters\fP &p, std::vector< std::unique_ptr< \fBImage\fP > > &src_image, unsigned base_qp)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
