.TH "deps/base_vvc/minimum_VTM/source/Lib/CommonLib/Picture.cpp" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deps/base_vvc/minimum_VTM/source/Lib/CommonLib/Picture.cpp \- Description of a coded picture\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'Picture\&.h'\fP
.br
\fC#include 'SEI\&.h'\fP
.br
\fC#include 'ChromaFormat\&.h'\fP
.br
\fC#include 'CommonLib/InterpolationFilter\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBvtm\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const \fBTFilterCoeff\fP \fBvtm::DownsamplingFilterSRC\fP [8][16][12]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Description of a coded picture\&. 


.PP
Definition in file \fBPicture\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
