.TH "deps/base_vvc/minimum_VTM/source/Lib/CommonLib/Picture.h" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deps/base_vvc/minimum_VTM/source/Lib/CommonLib/Picture.h \- Description of a coded picture\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'CommonDef\&.h'\fP
.br
\fC#include 'Common\&.h'\fP
.br
\fC#include 'Unit\&.h'\fP
.br
\fC#include 'Buffer\&.h'\fP
.br
\fC#include 'Slice\&.h'\fP
.br
\fC#include 'CodingStructure\&.h'\fP
.br
\fC#include 'Hash\&.h'\fP
.br
\fC#include 'MCTS\&.h'\fP
.br
\fC#include <deque>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBvtm::Picture\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBvtm\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBM_BUFS\fP(JID,  PID)   m_bufs[PID]"
.br
.in -1c
.SS "Typedefs"

.PP
.RI "\fB\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "typedef std::list< \fBSEI\fP * > \fBvtm::SEIMessages\fP"
.br
.in -1c
.in -1c
.PP
.RI "\fB\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "typedef std::list< \fBPicture\fP * > \fBvtm::PicList\fP"
.br
.in -1c
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBvtm::calcAndPrintHashStatus\fP (const \fBCPelUnitBuf\fP &pic, const class \fBSEIDecodedPictureHash\fP *pictureHashSEI, const \fBBitDepths\fP &bitDepths, const \fBMsgLevel\fP msgl)"
.br
.ti -1c
.RI "uint32_t \fBvtm::calcMD5\fP (const \fBCPelUnitBuf\fP &pic, \fBPictureHash\fP &digest, const \fBBitDepths\fP &bitDepths)"
.br
.ti -1c
.RI "uint32_t \fBvtm::calcMD5WithCropping\fP (const \fBCPelUnitBuf\fP &pic, \fBPictureHash\fP &digest, const \fBBitDepths\fP &bitDepths, const int leftOffset, const int rightOffset, const int topOffset, const int bottomOffset)"
.br
.ti -1c
.RI "std::string \fBvtm::hashToString\fP (const \fBPictureHash\fP &digest, int numChar)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Description of a coded picture\&. 


.PP
Definition in file \fBPicture\&.h\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define M_BUFS(JID, PID)   m_bufs[PID]"

.PP
Definition at line \fB96\fP of file \fBPicture\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
