.TH "deps/base_vvc/minimum_VTM/source/Lib/CommonLib/PicYuvMD5.cpp" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deps/base_vvc/minimum_VTM/source/Lib/CommonLib/PicYuvMD5.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'Picture\&.h'\fP
.br
\fC#include 'SEI\&.h'\fP
.br
\fC#include 'libmd5/MD5\&.h'\fP
.br

.SS "Functions"

.PP
.RI "\fB\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "uint32_t \fBcompCRC\fP (int bitdepth, const Pel *plane, uint32_t width, uint32_t height, uint32_t stride, PictureHash &digest)"
.br
.ti -1c
.RI "uint32_t \fBcalcCRC\fP (const CPelUnitBuf &pic, PictureHash &digest, const BitDepths &bitDepths)"
.br
.ti -1c
.RI "uint32_t \fBcompChecksum\fP (int bitdepth, const Pel *plane, uint32_t width, uint32_t height, uint32_t stride, PictureHash &digest, const BitDepths &)"
.br
.ti -1c
.RI "uint32_t \fBcalcChecksum\fP (const CPelUnitBuf &pic, PictureHash &digest, const BitDepths &bitDepths)"
.br
.ti -1c
.RI "uint32_t \fBcalcMD5\fP (const CPelUnitBuf &pic, PictureHash &digest, const BitDepths &bitDepths)"
.br
.ti -1c
.RI "uint32_t \fBcalcMD5WithCropping\fP (const CPelUnitBuf &pic, PictureHash &digest, const BitDepths &bitDepths, const int leftOffset, const int rightOffset, const int topOffset, const int bottomOffset)"
.br
.ti -1c
.RI "std::string \fBhashToString\fP (const PictureHash &digest, int numChar)"
.br
.ti -1c
.RI "int \fBcalcAndPrintHashStatus\fP (const CPelUnitBuf &pic, const SEIDecodedPictureHash *pictureHashSEI, const BitDepths &bitDepths, const MsgLevel msgl)"
.br
.in -1c
.in -1c
.SH "Function Documentation"
.PP 
.SS "int calcAndPrintHashStatus (const CPelUnitBuf & pic, const SEIDecodedPictureHash * pictureHashSEI, const BitDepths & bitDepths, const MsgLevel msgl)"

.PP
Definition at line \fB247\fP of file \fBPicYuvMD5\&.cpp\fP\&.
.SS "uint32_t calcChecksum (const CPelUnitBuf & pic, PictureHash & digest, const BitDepths & bitDepths)"

.PP
Definition at line \fB169\fP of file \fBPicYuvMD5\&.cpp\fP\&.
.SS "uint32_t calcCRC (const CPelUnitBuf & pic, PictureHash & digest, const BitDepths & bitDepths)"

.PP
Definition at line \fB130\fP of file \fBPicYuvMD5\&.cpp\fP\&.
.SS "uint32_t calcMD5 (const CPelUnitBuf & pic, PictureHash & digest, const BitDepths & bitDepths)"
Calculate the MD5sum of pic, storing the result in digest\&. \fBMD5\fP calculation is performed on Y' then Cb, then Cr; each in raster order\&. Pel data is inserted into the \fBMD5\fP function in little-endian byte order, using sufficient bytes to represent the picture bitdepth\&. Eg, 10bit data uses little-endian two byte words; 8bit data uses single byte words\&. 
.PP
Definition at line \fB188\fP of file \fBPicYuvMD5\&.cpp\fP\&.
.SS "uint32_t calcMD5WithCropping (const CPelUnitBuf & pic, PictureHash & digest, const BitDepths & bitDepths, const int leftOffset, const int rightOffset, const int topOffset, const int bottomOffset)"

.PP
Definition at line \fB193\fP of file \fBPicYuvMD5\&.cpp\fP\&.
.SS "uint32_t compChecksum (int bitdepth, const Pel * plane, uint32_t width, uint32_t height, uint32_t stride, PictureHash & digest, const BitDepths &)"

.PP
Definition at line \fB143\fP of file \fBPicYuvMD5\&.cpp\fP\&.
.SS "uint32_t compCRC (int bitdepth, const Pel * plane, uint32_t width, uint32_t height, uint32_t stride, PictureHash & digest)"

.PP
Definition at line \fB90\fP of file \fBPicYuvMD5\&.cpp\fP\&.
.SS "std::string hashToString (const PictureHash & digest, int numChar)"

.PP
Definition at line \fB229\fP of file \fBPicYuvMD5\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
