.TH "encoder/include/PriorityConfiguration.hpp" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
encoder/include/PriorityConfiguration.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <unordered_map>\fP
.br
\fC#include 'LayerEncodeFlags\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBlctm::PriorityConfiguration\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBlctm\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBlctm::PriorityMode\fP { \fBlctm::PM_ALL_OFF\fP = 0, \fBlctm::PM_ALL_ON\fP = 1, \fBlctm::PM_SL1_ON\fP = 2, \fBlctm::PM_SL2_ON\fP = 3, \fBlctm::PM_SL1_OFF\fP = 4, \fBlctm::PM_SL2_OFF\fP = 5 }"
.br
.ti -1c
.RI "enum \fBlctm::PriorityMBType\fP { \fBlctm::Smooth\fP = 0, \fBlctm::Plain\fP = 1, \fBlctm::Coarse\fP = 2, \fBlctm::Edge\fP = 3, \fBlctm::SmoothAndPlain\fP = 4, \fBlctm::CoarseAndPlain\fP = 5 }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
