.TH "encoder/include/PriorityMap.hpp" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
encoder/include/PriorityMap.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <array>\fP
.br
\fC#include <limits>\fP
.br
\fC#include 'Component\&.hpp'\fP
.br
\fC#include 'Surface\&.hpp'\fP
.br
\fC#include 'PriorityConfiguration\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBlctm::PriorityMap\fP"
.br
.ti -1c
.RI "class \fBlctm::PriorityMapVis\fP"
.br
.ti -1c
.RI "class \fBlctm::StaticResiduals\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBlctm\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBPRIORITY_COEF\fP"
.br
.ti -1c
.RI "#define \fBBLOCK_SIZE\fP   8"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBlctm::KillingFunction\fP { \fBlctm::KILL_ALL\fP = 0, \fBlctm::KEEP_ALL\fP = 1, \fBlctm::THRESHOLD_CUTOFF\fP = 2 }"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define BLOCK_SIZE   8"

.PP
Definition at line \fB56\fP of file \fBPriorityMap\&.hpp\fP\&.
.SS "#define PRIORITY_COEF"

.PP
Definition at line \fB54\fP of file \fBPriorityMap\&.hpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
