.TH "deps/base_vvc/minimum_VTM/source/Lib/CommonLib/ProfileLevelTier.h" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deps/base_vvc/minimum_VTM/source/Lib/CommonLib/ProfileLevelTier.h \- Handle profile, level and tier information\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'CommonLib/CommonDef\&.h'\fP
.br
\fC#include <stdint\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBvtm::LevelTierFeatures\fP"
.br
.ti -1c
.RI "struct \fBvtm::ProfileFeatures\fP"
.br
.ti -1c
.RI "class \fBvtm::ProfileLevelTierFeatures\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBvtm\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Handle profile, level and tier information\&. 


.PP
Definition in file \fBProfileLevelTier\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
