.TH "deps/base_vvc/minimum_VTM/source/Lib/CommonLib/ProfileLevelTier.cpp" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deps/base_vvc/minimum_VTM/source/Lib/CommonLib/ProfileLevelTier.cpp \- Handle profile, level and tier information\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'ProfileLevelTier\&.h'\fP
.br
\fC#include 'CommonLib/Slice\&.h'\fP
.br
\fC#include <math\&.h>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBvtm\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Handle profile, level and tier information\&. 


.PP
Definition in file \fBProfileLevelTier\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
