.TH "PsnrStatistic" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PsnrStatistic
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <BitstreamStatistic\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBmiBaseBytes\fP"
.br
.ti -1c
.RI "int \fBmiEnhancementBytes\fP"
.br
.ti -1c
.RI "float \fBmfCurMse\fP [3]"
.br
.ti -1c
.RI "float \fBmfCurPsnr\fP [3]"
.br
.ti -1c
.RI "float \fBmfAccMse\fP [3]"
.br
.ti -1c
.RI "float \fBmfAccPsnr\fP [3]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB68\fP of file \fBBitstreamStatistic\&.hpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "float PsnrStatistic::mfAccMse[3]"

.PP
Definition at line \fB75\fP of file \fBBitstreamStatistic\&.hpp\fP\&.
.SS "float PsnrStatistic::mfAccPsnr[3]"

.PP
Definition at line \fB76\fP of file \fBBitstreamStatistic\&.hpp\fP\&.
.SS "float PsnrStatistic::mfCurMse[3]"

.PP
Definition at line \fB73\fP of file \fBBitstreamStatistic\&.hpp\fP\&.
.SS "float PsnrStatistic::mfCurPsnr[3]"

.PP
Definition at line \fB74\fP of file \fBBitstreamStatistic\&.hpp\fP\&.
.SS "int PsnrStatistic::miBaseBytes"

.PP
Definition at line \fB70\fP of file \fBBitstreamStatistic\&.hpp\fP\&.
.SS "int PsnrStatistic::miEnhancementBytes"

.PP
Definition at line \fB71\fP of file \fBBitstreamStatistic\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
