.TH "deps/base_vvc/minimum_VTM/source/Lib/CommonLib/Quant.h" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deps/base_vvc/minimum_VTM/source/Lib/CommonLib/Quant.h \- base quantization class (header)  

.SH SYNOPSIS
.br
.PP
\fC#include 'CommonDef\&.h'\fP
.br
\fC#include 'Unit\&.h'\fP
.br
\fC#include 'ChromaFormat\&.h'\fP
.br
\fC#include 'Contexts\&.h'\fP
.br
\fC#include 'ContextModelling\&.h'\fP
.br
\fC#include 'UnitPartitioner\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBvtm::TrQuantParams\fP"
.br
.ti -1c
.RI "class \fBvtm::QpParam\fP"
.br
.RI "QP struct\&. "
.ti -1c
.RI "class \fBvtm::Quant\fP"
.br
.RI "transform and quantization class "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBvtm\fP"
.br
.in -1c
.SS "Macros"

.PP
.RI "\fB\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "#define \fBQP_BITS\fP   15"
.br
.in -1c
.in -1c
.SH "Detailed Description"
.PP 
base quantization class (header) 


.PP
Definition in file \fBQuant\&.h\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define QP_BITS   15"

.PP
Definition at line \fB58\fP of file \fBQuant\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
