.TH "deps/base_vvc/minimum_VTM/source/Lib/CommonLib/QuantRDOQ.cpp" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deps/base_vvc/minimum_VTM/source/Lib/CommonLib/QuantRDOQ.cpp \- transform and quantization class  

.SH SYNOPSIS
.br
.PP
\fC#include 'QuantRDOQ\&.h'\fP
.br
\fC#include 'UnitTools\&.h'\fP
.br
\fC#include 'ContextModelling\&.h'\fP
.br
\fC#include 'CodingStructure\&.h'\fP
.br
\fC#include 'dtrace_next\&.h'\fP
.br
\fC#include 'dtrace_buffer\&.h'\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <limits>\fP
.br
\fC#include <memory\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBcoeffGroupRDStats\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
transform and quantization class 


.PP
Definition in file \fBQuantRDOQ\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
