.TH "deps/base_vvc/minimum_VTM/source/Lib/CommonLib/RdCostWeightPrediction.h" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deps/base_vvc/minimum_VTM/source/Lib/CommonLib/RdCostWeightPrediction.h \- RD cost computation namespace (header)  

.SH SYNOPSIS
.br
.PP
\fC#include 'CommonDef\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBvtm\fP"
.br
.ti -1c
.RI "namespace \fBvtm::RdCostWeightPrediction\fP"
.br
.RI "RD cost computation namespace, with Weighted Prediction\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBDistortion\fP \fBvtm::RdCostWeightPrediction::xGetSSEw\fP (const \fBDistParam\fP &rcDtParam)"
.br
.ti -1c
.RI "\fBDistortion\fP \fBvtm::RdCostWeightPrediction::xGetSADw\fP (const \fBDistParam\fP &rcDtParam)"
.br
.ti -1c
.RI "\fBDistortion\fP \fBvtm::RdCostWeightPrediction::xGetHADsw\fP (const \fBDistParam\fP &rcDtParam)"
.br
.RI "get weighted Hadamard cost "
.in -1c
.SH "Detailed Description"
.PP 
RD cost computation namespace (header) 


.PP
Definition in file \fBRdCostWeightPrediction\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
