.TH "deps/base_vvc/minimum_VTM/source/Lib/CommonLib/RdCost.h" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deps/base_vvc/minimum_VTM/source/Lib/CommonLib/RdCost.h \- RD cost computation classes (header)  

.SH SYNOPSIS
.br
.PP
\fC#include 'CommonDef\&.h'\fP
.br
\fC#include 'Mv\&.h'\fP
.br
\fC#include 'Unit\&.h'\fP
.br
\fC#include 'Buffer\&.h'\fP
.br
\fC#include 'Slice\&.h'\fP
.br
\fC#include 'RdCostWeightPrediction\&.h'\fP
.br
\fC#include <math\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBvtm::DistParam\fP"
.br
.RI "distortion parameter class "
.ti -1c
.RI "class \fBvtm::RdCost\fP"
.br
.RI "RD cost computation class\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBvtm\fP"
.br
.in -1c
.SS "Typedefs"

.PP
.RI "\fB\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "typedef \fBDistortion\fP(* \fBvtm::FpDistFunc\fP) (const \fBDistParam\fP &)"
.br
.in -1c
.in -1c
.SH "Detailed Description"
.PP 
RD cost computation classes (header) 


.PP
Definition in file \fBRdCost\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
