.TH "deps/base_vvc/minimum_VTM/source/Lib/CommonLib/RdCost.cpp" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deps/base_vvc/minimum_VTM/source/Lib/CommonLib/RdCost.cpp \- RD cost computation class\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'RdCost\&.h'\fP
.br
\fC#include 'Rom\&.h'\fP
.br
\fC#include 'UnitPartitioner\&.h'\fP
.br
\fC#include <limits>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBvtm\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBDONT_UNDEF_SIZE_AWARE_PER_EL_OP\fP"
.br
.ti -1c
.RI "#define \fBSAD_OP\fP(ADDR)   uiSum += abs( piOrg[ADDR] \- piCur[ADDR] );"
.br
.ti -1c
.RI "#define \fBSAD_INC\fP   piOrg += iStrideOrg; piCur += iStrideCur;"
.br
.in -1c
.SS "Variables"

.PP
.RI "\fB\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "\fBPel\fP \fBvtm::orgCopy\fP [MAX_CU_SIZE *MAX_CU_SIZE]"
.br
.in -1c
.in -1c
.SH "Detailed Description"
.PP 
RD cost computation class\&. 


.PP
Definition in file \fBRdCost\&.cpp\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define DONT_UNDEF_SIZE_AWARE_PER_EL_OP"

.PP
Definition at line \fB38\fP of file \fBRdCost\&.cpp\fP\&.
.SS "#define SAD_INC   piOrg += iStrideOrg; piCur += iStrideCur;"

.SS "#define SAD_OP(ADDR)   uiSum += abs( piOrg[ADDR] \- piCur[ADDR] );"

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
