.TH "deps/base_vvc/minimum_VTM/source/Lib/CommonLib/RdCostWeightPrediction.cpp" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deps/base_vvc/minimum_VTM/source/Lib/CommonLib/RdCostWeightPrediction.cpp \- RD cost computation class with Weighted-Prediction\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'RdCostWeightPrediction\&.h'\fP
.br
\fC#include 'RdCost\&.h'\fP
.br
\fC#include <math\&.h>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBvtm\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
RD cost computation class with Weighted-Prediction\&. 


.PP
Definition in file \fBRdCostWeightPrediction\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
