.TH "ReportStructure" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ReportStructure
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <BitstreamStatistic\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBmiTimeStamp\fP"
.br
.ti -1c
.RI "int \fBmiPictureType\fP"
.br
.ti -1c
.RI "int \fBmiBaseSize\fP"
.br
.ti -1c
.RI "int \fBmiEnhancementSize\fP"
.br
.ti -1c
.RI "int \fBmiRunTime\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB81\fP of file \fBBitstreamStatistic\&.hpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int ReportStructure::miBaseSize"

.PP
Definition at line \fB84\fP of file \fBBitstreamStatistic\&.hpp\fP\&.
.SS "int ReportStructure::miEnhancementSize"

.PP
Definition at line \fB85\fP of file \fBBitstreamStatistic\&.hpp\fP\&.
.SS "int ReportStructure::miPictureType"

.PP
Definition at line \fB83\fP of file \fBBitstreamStatistic\&.hpp\fP\&.
.SS "int ReportStructure::miRunTime"

.PP
Definition at line \fB86\fP of file \fBBitstreamStatistic\&.hpp\fP\&.
.SS "int ReportStructure::miTimeStamp"

.PP
Definition at line \fB82\fP of file \fBBitstreamStatistic\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
