.TH "ReportStructureComp" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ReportStructureComp
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <BitstreamStatistic\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator()\fP (const \fBReportStructure\fP &l, const \fBReportStructure\fP &r)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB89\fP of file \fBBitstreamStatistic\&.hpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "bool ReportStructureComp::operator() (const \fBReportStructure\fP & l, const \fBReportStructure\fP & r)\fC [inline]\fP"

.PP
Definition at line \fB90\fP of file \fBBitstreamStatistic\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
