.TH "deps/base_vvc/minimum_VTM/source/Lib/CommonLib/Reshape.cpp" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deps/base_vvc/minimum_VTM/source/Lib/CommonLib/Reshape.cpp \- common reshaper class  

.SH SYNOPSIS
.br
.PP
\fC#include 'Reshape\&.h'\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <math\&.h>\fP
.br
\fC#include <UnitTools\&.h>\fP
.br

.SH "Detailed Description"
.PP 
common reshaper class 


.PP
Definition in file \fBReshape\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
