.TH "deps/base_vvc/minimum_VTM/source/Lib/CommonLib/Reshape.h" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deps/base_vvc/minimum_VTM/source/Lib/CommonLib/Reshape.h \- reshaping header and class (header)  

.SH SYNOPSIS
.br
.PP
\fC#include 'CommonDef\&.h'\fP
.br
\fC#include 'Rom\&.h'\fP
.br
\fC#include 'CommonLib/Picture\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBvtm::Reshape\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBvtm\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
reshaping header and class (header) 


.PP
Definition in file \fBReshape\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
