.TH "RingBuffer< T >" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RingBuffer< T >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <RingBuffer\&.hpp>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef T \fBvalue_type\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRingBuffer\fP (int capacity)"
.br
.ti -1c
.RI "void \fBpush\fP (T const &v)"
.br
.ti -1c
.RI "bool \fBpush_timeout\fP (T const &v, T &overflow, unsigned int usec=0)"
.br
.ti -1c
.RI "void \fBpop\fP (T &v)"
.br
.ti -1c
.RI "bool \fBpop_timeout\fP (T &v, unsigned int usec=0)"
.br
.ti -1c
.RI "template<typename P > void \fBpop_if\fP (T &v, const P &p)"
.br
.ti -1c
.RI "template<typename P > bool \fBpop_if_timeout\fP (T &v, const P &pr, unsigned int usec=0)"
.br
.ti -1c
.RI "void \fBpeek\fP (T &v)"
.br
.ti -1c
.RI "void \fBclear\fP ()"
.br
.ti -1c
.RI "bool \fBempty\fP () const"
.br
.ti -1c
.RI "bool \fBfull\fP () const"
.br
.ti -1c
.RI "unsigned int \fBspace\fP () const"
.br
.ti -1c
.RI "unsigned int \fBsize\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T>
.br
class RingBuffer< T >"
.PP
Definition at line \fB47\fP of file \fBRingBuffer\&.hpp\fP\&.
.SH "Member Typedef Documentation"
.PP 
.SS "template<typename T > typedef T \fBRingBuffer\fP< T >::value_type"

.PP
Definition at line \fB49\fP of file \fBRingBuffer\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename T > \fBRingBuffer\fP< T >\fB::RingBuffer\fP (int capacity)\fC [inline]\fP"

.PP
Definition at line \fB51\fP of file \fBRingBuffer\&.hpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "template<typename T > void \fBRingBuffer\fP< T >::clear ()\fC [inline]\fP"

.PP
Definition at line \fB153\fP of file \fBRingBuffer\&.hpp\fP\&.
.SS "template<typename T > bool \fBRingBuffer\fP< T >::empty () const\fC [inline]\fP"

.PP
Definition at line \fB160\fP of file \fBRingBuffer\&.hpp\fP\&.
.SS "template<typename T > bool \fBRingBuffer\fP< T >::full () const\fC [inline]\fP"

.PP
Definition at line \fB166\fP of file \fBRingBuffer\&.hpp\fP\&.
.SS "template<typename T > void \fBRingBuffer\fP< T >::peek (T & v)\fC [inline]\fP"

.PP
Definition at line \fB144\fP of file \fBRingBuffer\&.hpp\fP\&.
.SS "template<typename T > void \fBRingBuffer\fP< T >::pop (T & v)\fC [inline]\fP"

.PP
Definition at line \fB84\fP of file \fBRingBuffer\&.hpp\fP\&.
.SS "template<typename T > template<typename P > void \fBRingBuffer\fP< T >::pop_if (T & v, const P & p)\fC [inline]\fP"

.PP
Definition at line \fB114\fP of file \fBRingBuffer\&.hpp\fP\&.
.SS "template<typename T > template<typename P > bool \fBRingBuffer\fP< T >::pop_if_timeout (T & v, const P & pr, unsigned int usec = \fC0\fP)\fC [inline]\fP"

.PP
Definition at line \fB130\fP of file \fBRingBuffer\&.hpp\fP\&.
.SS "template<typename T > bool \fBRingBuffer\fP< T >::pop_timeout (T & v, unsigned int usec = \fC0\fP)\fC [inline]\fP"

.PP
Definition at line \fB100\fP of file \fBRingBuffer\&.hpp\fP\&.
.SS "template<typename T > void \fBRingBuffer\fP< T >::push (T const & v)\fC [inline]\fP"

.PP
Definition at line \fB54\fP of file \fBRingBuffer\&.hpp\fP\&.
.SS "template<typename T > bool \fBRingBuffer\fP< T >::push_timeout (T const & v, T & overflow, unsigned int usec = \fC0\fP)\fC [inline]\fP"

.PP
Definition at line \fB66\fP of file \fBRingBuffer\&.hpp\fP\&.
.SS "template<typename T > unsigned int \fBRingBuffer\fP< T >::size () const\fC [inline]\fP"

.PP
Definition at line \fB178\fP of file \fBRingBuffer\&.hpp\fP\&.
.SS "template<typename T > unsigned int \fBRingBuffer\fP< T >::space () const\fC [inline]\fP"

.PP
Definition at line \fB172\fP of file \fBRingBuffer\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
