.TH "deps/base_vvc/minimum_VTM/source/Lib/CommonLib/Rom.h" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deps/base_vvc/minimum_VTM/source/Lib/CommonLib/Rom.h \- global variables & functions (header)  

.SH SYNOPSIS
.br
.PP
\fC#include 'CommonDef\&.h'\fP
.br
\fC#include 'Common\&.h'\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <iostream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBvtm::ScanElement\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBvtm\fP"
.br
.in -1c
.SS "Functions"

.PP
.RI "\fB\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "void \fBvtm::initROM\fP ()"
.br
.ti -1c
.RI "void \fBvtm::destroyROM\fP ()"
.br
.ti -1c
.RI "const char * \fBvtm::nalUnitTypeToString\fP (\fBNalUnitType\fP type)"
.br
.ti -1c
.RI "int8_t \fBvtm::getBcwWeight\fP (uint8_t bcwIdx, uint8_t uhRefFrmList)"
.br
.ti -1c
.RI "void \fBvtm::resetBcwCodingOrder\fP (bool bRunDecoding, const \fBCodingStructure\fP &cs)"
.br
.ti -1c
.RI "uint32_t \fBvtm::deriveWeightIdxBits\fP (uint8_t bcwIdx)"
.br
.ti -1c
.RI "void \fBvtm::initGeoTemplate\fP ()"
.br
.in -1c
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const int \fBvtm::g_IBCBufferSize\fP = 256 * 128"
.br
.in -1c
.in +1c
.ti -1c
.RI "const \fBTMatrixCoeff\fP \fBvtm::g_trCoreDCT2P2\fP [\fBTRANSFORM_NUMBER_OF_DIRECTIONS\fP][2][2]"
.br
.ti -1c
.RI "const \fBTMatrixCoeff\fP \fBvtm::g_trCoreDCT2P4\fP [\fBTRANSFORM_NUMBER_OF_DIRECTIONS\fP][4][4]"
.br
.ti -1c
.RI "const \fBTMatrixCoeff\fP \fBvtm::g_trCoreDCT2P8\fP [\fBTRANSFORM_NUMBER_OF_DIRECTIONS\fP][8][8]"
.br
.ti -1c
.RI "const \fBTMatrixCoeff\fP \fBvtm::g_trCoreDCT2P16\fP [\fBTRANSFORM_NUMBER_OF_DIRECTIONS\fP][16][16]"
.br
.ti -1c
.RI "const \fBTMatrixCoeff\fP \fBvtm::g_trCoreDCT2P32\fP [\fBTRANSFORM_NUMBER_OF_DIRECTIONS\fP][32][32]"
.br
.ti -1c
.RI "const \fBTMatrixCoeff\fP \fBvtm::g_trCoreDCT2P64\fP [\fBTRANSFORM_NUMBER_OF_DIRECTIONS\fP][64][64]"
.br
.ti -1c
.RI "const \fBTMatrixCoeff\fP \fBvtm::g_trCoreDCT8P4\fP [\fBTRANSFORM_NUMBER_OF_DIRECTIONS\fP][4][4]"
.br
.ti -1c
.RI "const \fBTMatrixCoeff\fP \fBvtm::g_trCoreDCT8P8\fP [\fBTRANSFORM_NUMBER_OF_DIRECTIONS\fP][8][8]"
.br
.ti -1c
.RI "const \fBTMatrixCoeff\fP \fBvtm::g_trCoreDCT8P16\fP [\fBTRANSFORM_NUMBER_OF_DIRECTIONS\fP][16][16]"
.br
.ti -1c
.RI "const \fBTMatrixCoeff\fP \fBvtm::g_trCoreDCT8P32\fP [\fBTRANSFORM_NUMBER_OF_DIRECTIONS\fP][32][32]"
.br
.ti -1c
.RI "const \fBTMatrixCoeff\fP \fBvtm::g_trCoreDST7P4\fP [\fBTRANSFORM_NUMBER_OF_DIRECTIONS\fP][4][4]"
.br
.ti -1c
.RI "const \fBTMatrixCoeff\fP \fBvtm::g_trCoreDST7P8\fP [\fBTRANSFORM_NUMBER_OF_DIRECTIONS\fP][8][8]"
.br
.ti -1c
.RI "const \fBTMatrixCoeff\fP \fBvtm::g_trCoreDST7P16\fP [\fBTRANSFORM_NUMBER_OF_DIRECTIONS\fP][16][16]"
.br
.ti -1c
.RI "const \fBTMatrixCoeff\fP \fBvtm::g_trCoreDST7P32\fP [\fBTRANSFORM_NUMBER_OF_DIRECTIONS\fP][32][32]"
.br
.ti -1c
.RI "const int8_t \fBvtm::g_lfnst8x8\fP [4][2][16][48]"
.br
.ti -1c
.RI "const int8_t \fBvtm::g_lfnst4x4\fP [4][2][16][16]"
.br
.ti -1c
.RI "const uint8_t \fBvtm::g_lfnstLut\fP [NUM_INTRA_MODE+NUM_EXT_LUMA_MODE \- 1]"
.br
.ti -1c
.RI "constexpr uint8_t \fBvtm::g_tbMax\fP [257]"
.br
.ti -1c
.RI "uint32_t \fBvtm::g_auiGoRicePosCoeff0\fP (int st, uint32_t ricePar)"
.br
.ti -1c
.RI "bool \fBvtm::is34\fP (const \fBSizeType\fP &size)"
.br
.ti -1c
.RI "bool \fBvtm::is58\fP (const \fBSizeType\fP &size)"
.br
.ti -1c
.RI "bool \fBvtm::isNonLog2BlockSize\fP (const \fBSize\fP &size)"
.br
.ti -1c
.RI "bool \fBvtm::isNonLog2Size\fP (const \fBSizeType\fP &size)"
.br
.in -1c
.SH "Detailed Description"
.PP 
global variables & functions (header) 


.PP
Definition in file \fBRom\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
