.TH "deps/base_vvc/minimum_VTM/source/Lib/CommonLib/Rom.cpp" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deps/base_vvc/minimum_VTM/source/Lib/CommonLib/Rom.cpp \- global variables & functions  

.SH SYNOPSIS
.br
.PP
\fC#include 'Rom\&.h'\fP
.br
\fC#include 'UnitTools\&.h'\fP
.br
\fC#include <memory\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <math\&.h>\fP
.br
\fC#include <iomanip>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBvtm::ScanGenerator\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBvtm\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "bool \fBvtm::g_mctsDecCheckEnabled\fP = false"
.br
.in -1c
.in +1c
.ti -1c
.RI "const int8_t \fBvtm::g_BcwLog2WeightBase\fP = 3"
.br
.ti -1c
.RI "const int8_t \fBvtm::g_BcwWeightBase\fP = (1 << \fBg_BcwLog2WeightBase\fP)"
.br
.ti -1c
.RI "const int8_t \fBvtm::g_BcwWeights\fP [BCW_NUM] = { \-2, 3, 4, 5, 10 }"
.br
.ti -1c
.RI "const int8_t \fBvtm::g_BcwSearchOrder\fP [BCW_NUM] = { BCW_DEFAULT, BCW_DEFAULT \- 2, BCW_DEFAULT + 2, BCW_DEFAULT \- 1, BCW_DEFAULT + 1 }"
.br
.ti -1c
.RI "int8_t \fBvtm::g_BcwCodingOrder\fP [BCW_NUM]"
.br
.ti -1c
.RI "int8_t \fBvtm::g_BcwParsingOrder\fP [BCW_NUM]"
.br
.ti -1c
.RI "uint32_t \fBvtm::g_log2SbbSize\fP [MAX_CU_DEPTH+1][MAX_CU_DEPTH+1][2]"
.br
.ti -1c
.RI "const int \fBvtm::g_quantScales\fP [2][SCALING_LIST_REM_NUM]"
.br
.ti -1c
.RI "const int \fBvtm::g_invQuantScales\fP [2][SCALING_LIST_REM_NUM]"
.br
.ti -1c
.RI "const uint8_t \fBvtm::g_aucIntraModeNumFast_UseMPM_2D\fP [7 \- MIN_CU_LOG2+1][7 \- MIN_CU_LOG2+1]"
.br
.ti -1c
.RI "const uint8_t \fBvtm::g_aucIntraModeNumFast_UseMPM\fP [MAX_CU_DEPTH]"
.br
.ti -1c
.RI "const uint8_t \fBvtm::g_aucIntraModeNumFast_NotUseMPM\fP [MAX_CU_DEPTH]"
.br
.ti -1c
.RI "const uint8_t \fBvtm::g_chroma422IntraAngleMappingTable\fP [NUM_INTRA_MODE]"
.br
.ti -1c
.RI "\fBSizeIndexInfo\fP * \fBvtm::gp_sizeIdxInfo\fP = \fBNULL\fP"
.br
.ti -1c
.RI "const int \fBvtm::g_ictModes\fP [2][4] = { { 0, 3, 1, 2 }, { 0, \-3, \-1, \-2 } }"
.br
.ti -1c
.RI "\fBUnitScale\fP \fBvtm::g_miScaling\fP (MIN_CU_LOG2, MIN_CU_LOG2)"
.br
.ti -1c
.RI "\fBScanElement\fP * \fBvtm::g_scanOrder\fP [\fBSCAN_NUMBER_OF_GROUP_TYPES\fP][\fBSCAN_NUMBER_OF_TYPES\fP][MAX_CU_SIZE/2+1][MAX_CU_SIZE/2+1]"
.br
.ti -1c
.RI "\fBScanElement\fP \fBvtm::g_coefTopLeftDiagScan8x8\fP [MAX_CU_SIZE/2+1][64]"
.br
.ti -1c
.RI "const uint32_t \fBvtm::g_uiMinInGroup\fP [LAST_SIGNIFICANT_GROUPS] = { 0,1,2,3,4,6,8,12,16,24,32,48,64,96 }"
.br
.ti -1c
.RI "const uint32_t \fBvtm::g_uiGroupIdx\fP [MAX_TB_SIZEY] = { 0,1,2,3,4,4,5,5,6,6,6,6,7,7,7,7,8,8,8,8,8,8,8,8,9,9,9,9,9,9,9,9, 10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11 }"
.br
.ti -1c
.RI "const uint32_t \fBvtm::g_auiGoRiceParsCoeff\fP [32]"
.br
.ti -1c
.RI "const char * \fBvtm::MatrixType\fP [\fBSCALING_LIST_SIZE_NUM\fP][SCALING_LIST_NUM]"
.br
.ti -1c
.RI "const char * \fBvtm::MatrixType_DC\fP [\fBSCALING_LIST_SIZE_NUM\fP][SCALING_LIST_NUM]"
.br
.ti -1c
.RI "const int \fBvtm::g_quantTSDefault4x4\fP [4 *4]"
.br
.ti -1c
.RI "const int \fBvtm::g_quantIntraDefault8x8\fP [8 *8]"
.br
.ti -1c
.RI "const int \fBvtm::g_quantInterDefault8x8\fP [8 *8]"
.br
.ti -1c
.RI "const uint32_t \fBvtm::g_scalingListSize\fP [\fBSCALING_LIST_SIZE_NUM\fP] = { 1, 4, 16, 64, 256, 1024, 4096, 16384 }"
.br
.ti -1c
.RI "const uint32_t \fBvtm::g_scalingListSizeX\fP [\fBSCALING_LIST_SIZE_NUM\fP] = { 1, 2, 4, 8, 16, 32, 64, 128 }"
.br
.ti -1c
.RI "const uint32_t \fBvtm::g_scalingListId\fP [\fBSCALING_LIST_SIZE_NUM\fP][SCALING_LIST_NUM]"
.br
.ti -1c
.RI "\fBMv\fP \fBvtm::g_reusedUniMVs\fP [32][32][8][8][2][33]"
.br
.ti -1c
.RI "bool \fBvtm::g_isReusedUniMVsFilled\fP [32][32][8][8]"
.br
.ti -1c
.RI "uint16_t \fBvtm::g_paletteQuant\fP [57]"
.br
.ti -1c
.RI "uint8_t \fBvtm::g_paletteRunTopLut\fP [5] = { 0, 1, 1, 2, 2 }"
.br
.ti -1c
.RI "uint8_t \fBvtm::g_paletteRunLeftLut\fP [5] = { 0, 1, 2, 3, 4 }"
.br
.ti -1c
.RI "int16_t ** \fBvtm::g_GeoParams\fP"
.br
.ti -1c
.RI "int16_t * \fBvtm::g_globalGeoWeights\fP [GEO_NUM_PRESTORED_MASK]"
.br
.ti -1c
.RI "\fBPel\fP * \fBvtm::g_globalGeoEncSADmask\fP [GEO_NUM_PRESTORED_MASK]"
.br
.ti -1c
.RI "int16_t \fBvtm::g_weightOffset\fP [GEO_NUM_PARTITION_MODE][GEO_NUM_CU_SIZE][GEO_NUM_CU_SIZE][2]"
.br
.ti -1c
.RI "int8_t \fBvtm::g_angle2mask\fP [GEO_NUM_ANGLES] = { 0, \-1, 1, 2, 3, 4, \-1, \-1, 5, \-1, \-1, 4, 3, 2, 1, \-1, 0, \-1, 1, 2, 3, 4, \-1, \-1, 5, \-1, \-1, 4, 3, 2, 1, \-1 }"
.br
.ti -1c
.RI "int8_t \fBvtm::g_Dis\fP [GEO_NUM_ANGLES] = { 8, 8, 8, 8, 4, 4, 2, 1, 0, \-1, \-2, \-4, \-4, \-8, \-8, \-8, \-8, \-8, \-8, \-8, \-4, \-4, \-2, \-1, 0, 1, 2, 4, 4, 8, 8, 8 }"
.br
.ti -1c
.RI "int8_t \fBvtm::g_angle2mirror\fP [GEO_NUM_ANGLES] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 2, 2, 2, 2 }"
.br
.ti -1c
.RI "const char * \fBvtm::nalUnitTypeToString\fP (\fBNalUnitType\fP type)"
.br
.ti -1c
.RI "int8_t \fBvtm::getBcwWeight\fP (uint8_t bcwIdx, uint8_t uhRefFrmList)"
.br
.ti -1c
.RI "void \fBvtm::resetBcwCodingOrder\fP (bool bRunDecoding, const \fBCodingStructure\fP &cs)"
.br
.ti -1c
.RI "uint32_t \fBvtm::deriveWeightIdxBits\fP (uint8_t bcwIdx)"
.br
.ti -1c
.RI "void \fBvtm::initROM\fP ()"
.br
.ti -1c
.RI "void \fBvtm::destroyROM\fP ()"
.br
.ti -1c
.RI "void \fBvtm::initGeoTemplate\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
global variables & functions 


.PP
Definition in file \fBRom\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
