.TH "deps/base_vvc/minimum_VTM/source/Lib/CommonLib/RomLFNST.cpp" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deps/base_vvc/minimum_VTM/source/Lib/CommonLib/RomLFNST.cpp \- LFNST Tables\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'Rom\&.h'\fP
.br
\fC#include <memory\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <math\&.h>\fP
.br
\fC#include <iomanip>\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "const uint8_t \fBg_lfnstLut\fP [NUM_INTRA_MODE+NUM_EXT_LUMA_MODE \- 1]"
.br
.ti -1c
.RI "const int8_t \fBg_lfnst8x8\fP [4][2][16][48]"
.br
.ti -1c
.RI "const int8_t \fBg_lfnst4x4\fP [4][2][16][16]"
.br
.in -1c
.SH "Detailed Description"
.PP 
LFNST Tables\&. 


.PP
Definition in file \fBRomLFNST\&.cpp\fP\&.
.SH "Variable Documentation"
.PP 
.SS "const int8_t g_lfnst4x4[4][2][16][16]"

.PP
Definition at line \fB211\fP of file \fBRomLFNST\&.cpp\fP\&.
.SS "const int8_t g_lfnst8x8[4][2][16][48]"

.PP
Definition at line \fB56\fP of file \fBRomLFNST\&.cpp\fP\&.
.SS "const uint8_t g_lfnstLut[NUM_INTRA_MODE+NUM_EXT_LUMA_MODE \- 1]"
\fBInitial value:\fP.PP
.nf
=
{
   0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1
}
.fi

.PP
Definition at line \fB51\fP of file \fBRomLFNST\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
