.TH "deps/base_vvc/minimum_VTM/source/Lib/CommonLib/RomTr.cpp" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deps/base_vvc/minimum_VTM/source/Lib/CommonLib/RomTr.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'Rom\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBDEFINE_DCT2_P2_MATRIX\fP(a)"
.br
.ti -1c
.RI "#define \fBDEFINE_DCT2_P4_MATRIX\fP(a,  b,  c)"
.br
.ti -1c
.RI "#define \fBDEFINE_DCT2_P8_MATRIX\fP(a,  b,  c,  d,  e,  f,  g)"
.br
.ti -1c
.RI "#define \fBDEFINE_DCT2_P16_MATRIX\fP(a,  b,  c,  d,  e,  f,  g,  h,  i,  j,  k,  l,  m,  n,  o)"
.br
.ti -1c
.RI "#define \fBDEFINE_DCT2_P32_MATRIX\fP(a,  b,  c,  d,  e,  f,  g,  h,  i,  j,  k,  l,  m,  n,  o,  p,  q,  r,  s,  t,  u,  v,  w,  x,  y,  z,  A,  B,  C,  \fBD\fP,  E)"
.br
.ti -1c
.RI "#define \fBDEFINE_DCT2_P64_MATRIX\fP(aa,  ab,  ac,  ad,  ae,  af,  ag,  ah,  ai,  aj,  ak,  al,  am,  an,  ao,  ap,  aq,  ar,  as,  at,  au,  av,  aw,  ax,  ay,  az,  ba,  bb,  bc,  bd,  be,  bf,  bg,  bh,  bi,  bj,  bk,  bl,  bm,  bn,  bo,  bp,  bq,  br,  bs,  bt,  bu,  bv,  bw,  bx,  by,  bz,  ca,  cb,  cc,  cd,  ce,  cf,  cg,  ch,  ci,  cj,  ck)"
.br
.ti -1c
.RI "#define \fBDEFINE_DCT8_P4_MATRIX\fP(a,  b,  c,  d)"
.br
.ti -1c
.RI "#define \fBDEFINE_DCT8_P8_MATRIX\fP(a,  b,  c,  d,  e,  f,  g,  h)"
.br
.ti -1c
.RI "#define \fBDEFINE_DCT8_P16_MATRIX\fP(a,  b,  c,  d,  e,  f,  g,  h,  i,  j,  k,  l,  m,  n,  o,  p)"
.br
.ti -1c
.RI "#define \fBDEFINE_DCT8_P32_MATRIX\fP(a,  b,  c,  d,  e,  f,  g,  h,  i,  j,  k,  l,  m,  n,  o,  p,  q,  r,  s,  t,  u,  v,  w,  x,  y,  z,  A,  B,  C,  \fBD\fP,  E,  F)"
.br
.ti -1c
.RI "#define \fBDEFINE_DST7_P4_MATRIX\fP(a,  b,  c,  d)"
.br
.ti -1c
.RI "#define \fBDEFINE_DST7_P8_MATRIX\fP(a,  b,  c,  d,  e,  f,  g,  h)"
.br
.ti -1c
.RI "#define \fBDEFINE_DST7_P16_MATRIX\fP(a,  b,  c,  d,  e,  f,  g,  h,  i,  j,  k,  l,  m,  n,  o,  p)"
.br
.ti -1c
.RI "#define \fBDEFINE_DST7_P32_MATRIX\fP(a,  b,  c,  d,  e,  f,  g,  h,  i,  j,  k,  l,  m,  n,  o,  p,  q,  r,  s,  t,  u,  v,  w,  x,  y,  z,  A,  B,  C,  \fBD\fP,  E,  F)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const TMatrixCoeff \fBg_trCoreDCT2P2\fP [TRANSFORM_NUMBER_OF_DIRECTIONS][2][2]"
.br
.ti -1c
.RI "const TMatrixCoeff \fBg_trCoreDCT2P4\fP [TRANSFORM_NUMBER_OF_DIRECTIONS][4][4]"
.br
.ti -1c
.RI "const TMatrixCoeff \fBg_trCoreDCT2P8\fP [TRANSFORM_NUMBER_OF_DIRECTIONS][8][8]"
.br
.ti -1c
.RI "const TMatrixCoeff \fBg_trCoreDCT2P16\fP [TRANSFORM_NUMBER_OF_DIRECTIONS][16][16]"
.br
.ti -1c
.RI "const TMatrixCoeff \fBg_trCoreDCT2P32\fP [TRANSFORM_NUMBER_OF_DIRECTIONS][32][32]"
.br
.ti -1c
.RI "const TMatrixCoeff \fBg_trCoreDCT2P64\fP [TRANSFORM_NUMBER_OF_DIRECTIONS][64][64]"
.br
.ti -1c
.RI "const TMatrixCoeff \fBg_trCoreDCT8P4\fP [TRANSFORM_NUMBER_OF_DIRECTIONS][4][4]"
.br
.ti -1c
.RI "const TMatrixCoeff \fBg_trCoreDCT8P8\fP [TRANSFORM_NUMBER_OF_DIRECTIONS][8][8]"
.br
.ti -1c
.RI "const TMatrixCoeff \fBg_trCoreDCT8P16\fP [TRANSFORM_NUMBER_OF_DIRECTIONS][16][16]"
.br
.ti -1c
.RI "const TMatrixCoeff \fBg_trCoreDCT8P32\fP [TRANSFORM_NUMBER_OF_DIRECTIONS][32][32]"
.br
.ti -1c
.RI "const TMatrixCoeff \fBg_trCoreDST7P4\fP [TRANSFORM_NUMBER_OF_DIRECTIONS][4][4]"
.br
.ti -1c
.RI "const TMatrixCoeff \fBg_trCoreDST7P8\fP [TRANSFORM_NUMBER_OF_DIRECTIONS][8][8]"
.br
.ti -1c
.RI "const TMatrixCoeff \fBg_trCoreDST7P16\fP [TRANSFORM_NUMBER_OF_DIRECTIONS][16][16]"
.br
.ti -1c
.RI "const TMatrixCoeff \fBg_trCoreDST7P32\fP [TRANSFORM_NUMBER_OF_DIRECTIONS][32][32]"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define DEFINE_DCT2_P16_MATRIX(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o)"
\fBValue:\fP.PP
.nf
{ \\
  { a,  a,  a,  a,  a,  a,  a,  a,  a,  a,  a,  a,  a,  a,  a,  a}, \\
  { h,  i,  j,  k,  l,  m,  n,  o, \-o, \-n, \-m, \-l, \-k, \-j, \-i, \-h}, \\
  { d,  e,  f,  g, \-g, \-f, \-e, \-d, \-d, \-e, \-f, \-g,  g,  f,  e,  d}, \\
  { i,  l,  o, \-m, \-j, \-h, \-k, \-n,  n,  k,  h,  j,  m, \-o, \-l, \-i}, \\
  { b,  c, \-c, \-b, \-b, \-c,  c,  b,  b,  c, \-c, \-b, \-b, \-c,  c,  b}, \\
  { j,  o, \-k, \-i, \-n,  l,  h,  m, \-m, \-h, \-l,  n,  i,  k, \-o, \-j}, \\
  { e, \-g, \-d, \-f,  f,  d,  g, \-e, \-e,  g,  d,  f, \-f, \-d, \-g,  e}, \\
  { k, \-m, \-i,  o,  h,  n, \-j, \-l,  l,  j, \-n, \-h, \-o,  i,  m, \-k}, \\
  { a, \-a, \-a,  a,  a, \-a, \-a,  a,  a, \-a, \-a,  a,  a, \-a, \-a,  a}, \\
  { l, \-j, \-n,  h, \-o, \-i,  m,  k, \-k, \-m,  i,  o, \-h,  n,  j, \-l}, \\
  { f, \-d,  g,  e, \-e, \-g,  d, \-f, \-f,  d, \-g, \-e,  e,  g, \-d,  f}, \\
  { m, \-h,  l,  n, \-i,  k,  o, \-j,  j, \-o, \-k,  i, \-n, \-l,  h, \-m}, \\
  { c, \-b,  b, \-c, \-c,  b, \-b,  c,  c, \-b,  b, \-c, \-c,  b, \-b,  c}, \\
  { n, \-k,  h, \-j,  m,  o, \-l,  i, \-i,  l, \-o, \-m,  j, \-h,  k, \-n}, \\
  { g, \-f,  e, \-d,  d, \-e,  f, \-g, \-g,  f, \-e,  d, \-d,  e, \-f,  g}, \\
  { o, \-n,  m, \-l,  k, \-j,  i, \-h,  h, \-i,  j, \-k,  l, \-m,  n, \-o}  \\
}
.fi

.PP
Definition at line \fB68\fP of file \fBRomTr\&.cpp\fP\&.
.SS "#define DEFINE_DCT2_P2_MATRIX(a)"
\fBValue:\fP.PP
.nf
{ \\
  {a,  a}, \\
  {a, \-a}  \\
}
.fi

.PP
Definition at line \fB42\fP of file \fBRomTr\&.cpp\fP\&.
.SS "#define DEFINE_DCT2_P32_MATRIX(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, A, B, C, \fBD\fP, E)"

.PP
Definition at line \fB88\fP of file \fBRomTr\&.cpp\fP\&.
.SS "#define DEFINE_DCT2_P4_MATRIX(a, b, c)"
\fBValue:\fP.PP
.nf
{ \\
  { a,  a,  a,  a}, \\
  { b,  c, \-c, \-b}, \\
  { a, \-a, \-a,  a}, \\
  { c, \-b,  b, \-c}  \\
}
.fi

.PP
Definition at line \fB48\fP of file \fBRomTr\&.cpp\fP\&.
.SS "#define DEFINE_DCT2_P64_MATRIX(aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap, aq, ar, as, at, au, av, aw, ax, ay, az, ba, bb, bc, bd, be, bf, bg, bh, bi, bj, bk, bl, bm, bn, bo, bp, bq, br, bs, bt, bu, bv, bw, bx, by, bz, ca, cb, cc, cd, ce, cf, cg, ch, ci, cj, ck)"

.PP
Definition at line \fB125\fP of file \fBRomTr\&.cpp\fP\&.
.SS "#define DEFINE_DCT2_P8_MATRIX(a, b, c, d, e, f, g)"
\fBValue:\fP.PP
.nf
{ \\
  { a,  a,  a,  a,  a,  a,  a,  a}, \\
  { d,  e,  f,  g, \-g, \-f, \-e, \-d}, \\
  { b,  c, \-c, \-b, \-b, \-c,  c,  b}, \\
  { e, \-g, \-d, \-f,  f,  d,  g, \-e}, \\
  { a, \-a, \-a,  a,  a, \-a, \-a,  a}, \\
  { f, \-d,  g,  e, \-e, \-g,  d, \-f}, \\
  { c, \-b,  b, \-c, \-c,  b, \-b,  c}, \\
  { g, \-f,  e, \-d,  d, \-e,  f, \-g}  \\
}
.fi

.PP
Definition at line \fB56\fP of file \fBRomTr\&.cpp\fP\&.
.SS "#define DEFINE_DCT8_P16_MATRIX(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p)"
\fBValue:\fP.PP
.nf
{ \\
  {  a,  b,  c,  d,  e,  f,  g,  h,  i,  j,  k,  l,  m,  n,  o,  p,}, \\
  {  b,  e,  h,  k,  n,  0, \-n, \-k, \-h, \-e, \-b, \-b, \-e, \-h, \-k, \-n,}, \\
  {  c,  h,  m, \-p, \-k, \-f, \-a, \-e, \-j, \-o,  n,  i,  d,  b,  g,  l,}, \\
  {  d,  k, \-p, \-i, \-b, \-f, \-m,  n,  g,  a,  h,  o, \-l, \-e, \-c, \-j,}, \\
  {  e,  n, \-k, \-b, \-h,  0,  h,  b,  k, \-n, \-e, \-e, \-n,  k,  b,  h,}, \\
  {  f,  0, \-f, \-f,  0,  f,  f,  0, \-f, \-f,  0,  f,  f,  0, \-f, \-f,}, \\
  {  g, \-n, \-a, \-m,  h,  f, \-o, \-b, \-l,  i,  e, \-p, \-c, \-k,  j,  d,}, \\
  {  h, \-k, \-e,  n,  b,  0, \-b, \-n,  e,  k, \-h, \-h,  k,  e, \-n, \-b,}, \\
  {  i, \-h, \-j,  g,  k, \-f, \-l,  e,  m, \-d, \-n,  c,  o, \-b, \-p,  a,}, \\
  {  j, \-e, \-o,  a, \-n, \-f,  i,  k, \-d, \-p,  b, \-m, \-g,  h,  l, \-c,}, \\
  {  k, \-b,  n,  h, \-e,  0,  e, \-h, \-n,  b, \-k, \-k,  b, \-n, \-h,  e,}, \\
  {  l, \-b,  i,  o, \-e,  f, \-p, \-h,  c, \-m, \-k,  a, \-j, \-n,  d, \-g,}, \\
  {  m, \-e,  d, \-l, \-n,  f, \-c,  k,  o, \-g,  b, \-j, \-p,  h, \-a,  i,}, \\
  {  n, \-h,  b, \-e,  k,  0, \-k,  e, \-b,  h, \-n, \-n,  h, \-b,  e, \-k,}, \\
  {  o, \-k,  g, \-c,  b, \-f,  j, \-n, \-p,  l, \-h,  d, \-a,  e, \-i,  m,}, \\
  {  p, \-n,  l, \-j,  h, \-f,  d, \-b,  a, \-c,  e, \-g,  i, \-k,  m, \-o,}, \\
}
.fi

.PP
Definition at line \fB214\fP of file \fBRomTr\&.cpp\fP\&.
.SS "#define DEFINE_DCT8_P32_MATRIX(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, A, B, C, \fBD\fP, E, F)"

.PP
Definition at line \fB234\fP of file \fBRomTr\&.cpp\fP\&.
.SS "#define DEFINE_DCT8_P4_MATRIX(a, b, c, d)"
\fBValue:\fP.PP
.nf
{ \\
  {  a,  b,  c,  d,}, \\
  {  b,  0, \-b, \-b,}, \\
  {  c, \-b, \-d,  a,}, \\
  {  d, \-b,  a, \-c,}, \\
}
.fi

.PP
Definition at line \fB194\fP of file \fBRomTr\&.cpp\fP\&.
.SS "#define DEFINE_DCT8_P8_MATRIX(a, b, c, d, e, f, g, h)"
\fBValue:\fP.PP
.nf
{ \\
  {  a,  b,  c,  d,  e,  f,  g,  h,}, \\
  {  b,  e,  h, \-g, \-d, \-a, \-c, \-f,}, \\
  {  c,  h, \-e, \-a, \-f,  g,  b,  d,}, \\
  {  d, \-g, \-a, \-h,  c,  e, \-f, \-b,}, \\
  {  e, \-d, \-f,  c,  g, \-b, \-h,  a,}, \\
  {  f, \-a,  g,  e, \-b,  h,  d, \-c,}, \\
  {  g, \-c,  b, \-f, \-h,  d, \-a,  e,}, \\
  {  h, \-f,  d, \-b,  a, \-c,  e, \-g,}, \\
}
.fi

.PP
Definition at line \fB202\fP of file \fBRomTr\&.cpp\fP\&.
.SS "#define DEFINE_DST7_P16_MATRIX(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p)"
\fBValue:\fP.PP
.nf
{ \\
  {  a,  b,  c,  d,  e,  f,  g,  h,  i,  j,  k,  l,  m,  n,  o,  p,}, \\
  {  c,  f,  i,  l,  o,  o,  l,  i,  f,  c,  0, \-c, \-f, \-i, \-l, \-o,}, \\
  {  e,  j,  o,  m,  h,  c, \-b, \-g, \-l, \-p, \-k, \-f, \-a,  d,  i,  n,}, \\
  {  g,  n,  l,  e, \-b, \-i, \-p, \-j, \-c,  d,  k,  o,  h,  a, \-f, \-m,}, \\
  {  i,  o,  f, \-c, \-l, \-l, \-c,  f,  o,  i,  0, \-i, \-o, \-f,  c,  l,}, \\
  {  k,  k,  0, \-k, \-k,  0,  k,  k,  0, \-k, \-k,  0,  k,  k,  0, \-k,}, \\
  {  m,  g, \-f, \-n, \-a,  l,  h, \-e, \-o, \-b,  k,  i, \-d, \-p, \-c,  j,}, \\
  {  o,  c, \-l, \-f,  i,  i, \-f, \-l,  c,  o,  0, \-o, \-c,  l,  f, \-i,}, \\
  {  p, \-a, \-o,  b,  n, \-c, \-m,  d,  l, \-e, \-k,  f,  j, \-g, \-i,  h,}, \\
  {  n, \-e, \-i,  j,  d, \-o,  a,  m, \-f, \-h,  k,  c, \-p,  b,  l, \-g,}, \\
  {  l, \-i, \-c,  o, \-f, \-f,  o, \-c, \-i,  l,  0, \-l,  i,  c, \-o,  f,}, \\
  {  j, \-m,  c,  g, \-p,  f,  d, \-n,  i,  a, \-k,  l, \-b, \-h,  o, \-e,}, \\
  {  h, \-p,  i, \-a, \-g,  o, \-j,  b,  f, \-n,  k, \-c, \-e,  m, \-l,  d,}, \\
  {  f, \-l,  o, \-i,  c,  c, \-i,  o, \-l,  f,  0, \-f,  l, \-o,  i, \-c,}, \\
  {  d, \-h,  l, \-p,  m, \-i,  e, \-a, \-c,  g, \-k,  o, \-n,  j, \-f,  b,}, \\
  {  b, \-d,  f, \-h,  j, \-l,  n, \-p,  o, \-m,  k, \-i,  g, \-e,  c, \-a,}, \\
}
.fi

.PP
Definition at line \fB292\fP of file \fBRomTr\&.cpp\fP\&.
.SS "#define DEFINE_DST7_P32_MATRIX(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, A, B, C, \fBD\fP, E, F)"

.PP
Definition at line \fB312\fP of file \fBRomTr\&.cpp\fP\&.
.SS "#define DEFINE_DST7_P4_MATRIX(a, b, c, d)"
\fBValue:\fP.PP
.nf
{ \\
  {  a,  b,  c,  d }, \\
  {  c,  c,  0, \-c }, \\
  {  d, \-a, \-c,  b }, \\
  {  b, \-d,  c, \-a }, \\
}
.fi

.PP
Definition at line \fB272\fP of file \fBRomTr\&.cpp\fP\&.
.SS "#define DEFINE_DST7_P8_MATRIX(a, b, c, d, e, f, g, h)"
\fBValue:\fP.PP
.nf
{ \\
  {  a,  b,  c,  d,  e,  f,  g,  h,}, \\
  {  c,  f,  h,  e,  b, \-a, \-d, \-g,}, \\
  {  e,  g,  b, \-c, \-h, \-d,  a,  f,}, \\
  {  g,  c, \-d, \-f,  a,  h,  b, \-e,}, \\
  {  h, \-a, \-g,  b,  f, \-c, \-e,  d,}, \\
  {  f, \-e, \-a,  g, \-d, \-b,  h, \-c,}, \\
  {  d, \-h,  e, \-a, \-c,  g, \-f,  b,}, \\
  {  b, \-d,  f, \-h,  g, \-e,  c, \-a,}, \\
}
.fi

.PP
Definition at line \fB280\fP of file \fBRomTr\&.cpp\fP\&.
.SH "Variable Documentation"
.PP 
.SS "const TMatrixCoeff g_trCoreDCT2P16[TRANSFORM_NUMBER_OF_DIRECTIONS][16][16]"
\fBInitial value:\fP.PP
.nf
=
{
  DEFINE_DCT2_P16_MATRIX(64,    83,    36,    89,    75,    50,    18,    90,    87,    80,    70,    57,    43,    25,     9),

}
.fi

.PP
Definition at line \fB452\fP of file \fBRomTr\&.cpp\fP\&.
.SS "const TMatrixCoeff g_trCoreDCT2P2[TRANSFORM_NUMBER_OF_DIRECTIONS][2][2]"
\fBInitial value:\fP.PP
.nf
=
{
  DEFINE_DCT2_P2_MATRIX(64),

}
.fi

.PP
Definition at line \fB434\fP of file \fBRomTr\&.cpp\fP\&.
.SS "const TMatrixCoeff g_trCoreDCT2P32[TRANSFORM_NUMBER_OF_DIRECTIONS][32][32]"
\fBInitial value:\fP.PP
.nf
=
{
  DEFINE_DCT2_P32_MATRIX(64,    83,    36,    89,    75,    50,    18,    90,    87,    80,    70,    57,    43,    25,     9,    90,    90,    88,    85,    82,    78,    73,    67,    61,    54,    46,    38,    31,    22,    13,     4),

}
.fi

.PP
Definition at line \fB458\fP of file \fBRomTr\&.cpp\fP\&.
.SS "const TMatrixCoeff g_trCoreDCT2P4[TRANSFORM_NUMBER_OF_DIRECTIONS][4][4]"
\fBInitial value:\fP.PP
.nf
=
{
  DEFINE_DCT2_P4_MATRIX(64,    83,    36),

}
.fi

.PP
Definition at line \fB440\fP of file \fBRomTr\&.cpp\fP\&.
.SS "const TMatrixCoeff g_trCoreDCT2P64[TRANSFORM_NUMBER_OF_DIRECTIONS][64][64]"
\fBInitial value:\fP.PP
.nf
=
{
  DEFINE_DCT2_P64_MATRIX(64,    83,    36,    89,    75,    50,    18,    90,    87,    80,    70,    57,    43,    25,     9,    90,    90,    88,    85,    82,    78,    73,    67,    61,    54,    46,    38,    31,    22,    13,     4,    91,    90,    90,    90,    88,    87,    86,    84,    83,    81,    79,    77,    73,    71,    69,    65,    62,    59,    56,    52,    48,    44,    41,    37,    33,    28,    24,    20,    15,    11,     7,     2),

}
.fi

.PP
Definition at line \fB464\fP of file \fBRomTr\&.cpp\fP\&.
.SS "const TMatrixCoeff g_trCoreDCT2P8[TRANSFORM_NUMBER_OF_DIRECTIONS][8][8]"
\fBInitial value:\fP.PP
.nf
=
{
  DEFINE_DCT2_P8_MATRIX(64,    83,    36,    89,    75,    50,    18),

}
.fi

.PP
Definition at line \fB446\fP of file \fBRomTr\&.cpp\fP\&.
.SS "const TMatrixCoeff g_trCoreDCT8P16[TRANSFORM_NUMBER_OF_DIRECTIONS][16][16]"
\fBInitial value:\fP.PP
.nf
=
{
  DEFINE_DCT8_P16_MATRIX(88,     88,     87,     85,     81,     77,     73,     68,     62,     55,     48,     40,     33,     25,     17,      8),

}
.fi

.PP
Definition at line \fB481\fP of file \fBRomTr\&.cpp\fP\&.
.SS "const TMatrixCoeff g_trCoreDCT8P32[TRANSFORM_NUMBER_OF_DIRECTIONS][32][32]"
\fBInitial value:\fP.PP
.nf
=
{
  DEFINE_DCT8_P32_MATRIX(90,     90,     89,     88,     87,     86,     85,     84,     82,     80,     78,     77,     74,     72,     68,     66,     63,     60,     56,     53,     50,     46,     42,     38,     34,     30,     26,     21,     17,     13,      9,      4),

}
.fi

.PP
Definition at line \fB486\fP of file \fBRomTr\&.cpp\fP\&.
.SS "const TMatrixCoeff g_trCoreDCT8P4[TRANSFORM_NUMBER_OF_DIRECTIONS][4][4]"
\fBInitial value:\fP.PP
.nf
=
{
  DEFINE_DCT8_P4_MATRIX(84,     74,     55,     29),

}
.fi

.PP
Definition at line \fB471\fP of file \fBRomTr\&.cpp\fP\&.
.SS "const TMatrixCoeff g_trCoreDCT8P8[TRANSFORM_NUMBER_OF_DIRECTIONS][8][8]"
\fBInitial value:\fP.PP
.nf
=
{
  DEFINE_DCT8_P8_MATRIX(86,     85,     78,     71,     60,     46,     32,     17),

}
.fi

.PP
Definition at line \fB476\fP of file \fBRomTr\&.cpp\fP\&.
.SS "const TMatrixCoeff g_trCoreDST7P16[TRANSFORM_NUMBER_OF_DIRECTIONS][16][16]"
\fBInitial value:\fP.PP
.nf
=
{
  DEFINE_DST7_P16_MATRIX(8,    17,    25,    33,    40,    48,    55,    62,    68,    73,    77,    81,    85,    87,    88,    88),

}
.fi

.PP
Definition at line \fB503\fP of file \fBRomTr\&.cpp\fP\&.
.SS "const TMatrixCoeff g_trCoreDST7P32[TRANSFORM_NUMBER_OF_DIRECTIONS][32][32]"
\fBInitial value:\fP.PP
.nf
=
{
  DEFINE_DST7_P32_MATRIX(4,     9,    13,    17,    21,    26,    30,    34,    38,    42,    46,    50,    53,    56,    60,    63,    66,    68,    72,    74,    77,    78,    80,    82,    84,    85,    86,    87,    88,    89,    90,    90),

}
.fi

.PP
Definition at line \fB508\fP of file \fBRomTr\&.cpp\fP\&.
.SS "const TMatrixCoeff g_trCoreDST7P4[TRANSFORM_NUMBER_OF_DIRECTIONS][4][4]"
\fBInitial value:\fP.PP
.nf
=
{
  DEFINE_DST7_P4_MATRIX(29,    55,    74,    84),

}
.fi

.PP
Definition at line \fB493\fP of file \fBRomTr\&.cpp\fP\&.
.SS "const TMatrixCoeff g_trCoreDST7P8[TRANSFORM_NUMBER_OF_DIRECTIONS][8][8]"
\fBInitial value:\fP.PP
.nf
=
{
  DEFINE_DST7_P8_MATRIX(17,    32,    46,    60,    71,    78,    85,    86),

}
.fi

.PP
Definition at line \fB498\fP of file \fBRomTr\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
