.TH "deps/base_vvc/minimum_VTM/source/Lib/CommonLib/SampleAdaptiveOffset.cpp" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deps/base_vvc/minimum_VTM/source/Lib/CommonLib/SampleAdaptiveOffset.cpp \- sample adaptive offset class  

.SH SYNOPSIS
.br
.PP
\fC#include 'SampleAdaptiveOffset\&.h'\fP
.br
\fC#include 'UnitTools\&.h'\fP
.br
\fC#include 'UnitPartitioner\&.h'\fP
.br
\fC#include 'CodingStructure\&.h'\fP
.br
\fC#include 'CommonLib/dtrace_codingstruct\&.h'\fP
.br
\fC#include 'CommonLib/dtrace_buffer\&.h'\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <math\&.h>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBvtm\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
sample adaptive offset class 


.PP
Definition in file \fBSampleAdaptiveOffset\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
