.TH "decoder/include/ScanEnhancement.hpp" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
decoder/include/ScanEnhancement.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <cstdint>\fP
.br
\fC#include <functional>\fP
.br
\fC#include 'Packet\&.hpp'\fP
.br
\fC#include 'Types\&.hpp'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBlctm\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "size_t \fBlctm::scan_enhancement\fP (uint8_t *data, size_t data_size, \fBEncapsulation\fP encapsulation, \fBBaseCoding\fP coding, uint64_t pts, bool is_idr, std::function< void(const \fBPacket\fP &pkt, const bool \fBis_lcevc_idr\fP)> callback)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
