.TH "decoder/src/ScanEnhancement.cpp" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
decoder/src/ScanEnhancement.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'ScanEnhancement\&.hpp'\fP
.br
\fC#include <cstring>\fP
.br
\fC#include <stdexcept>\fP
.br
\fC#include 'Diagnostics\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBlctm::RegisteredSEI\fP"
.br
.ti -1c
.RI "struct \fBlctm::UnregisteredSEI\fP"
.br
.ti -1c
.RI "class \fBlctm::rbsp_decoder\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBlctm\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "size_t \fBlctm::scan_enhancement\fP (uint8_t *data, size_t data_size, \fBEncapsulation\fP encapsulation, \fBBaseCoding\fP coding, uint64_t pts, bool is_idr, std::function< void(const \fBPacket\fP &pkt, const bool \fBis_lcevc_idr\fP)> callback)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
