.TH "deps/base_vvc/minimum_VTM/source/Lib/CommonLib/SEI.h" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deps/base_vvc/minimum_VTM/source/Lib/CommonLib/SEI.h
.SH SYNOPSIS
.br
.PP
\fC#include <list>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <cstring>\fP
.br
\fC#include 'CommonDef\&.h'\fP
.br
\fC#include 'libmd5/MD5\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBvtm::SEI\fP"
.br
.ti -1c
.RI "class \fBvtm::SEIEquirectangularProjection\fP"
.br
.ti -1c
.RI "class \fBvtm::SEISphereRotation\fP"
.br
.ti -1c
.RI "class \fBvtm::SEIOmniViewport\fP"
.br
.ti -1c
.RI "struct \fBvtm::SEIOmniViewport::OmniViewport\fP"
.br
.ti -1c
.RI "class \fBvtm::SEIRegionWisePacking\fP"
.br
.ti -1c
.RI "class \fBvtm::SEIGeneralizedCubemapProjection\fP"
.br
.ti -1c
.RI "class \fBvtm::SEISampleAspectRatioInfo\fP"
.br
.ti -1c
.RI "class \fBvtm::SEIuserDataUnregistered\fP"
.br
.ti -1c
.RI "class \fBvtm::SEIDecodedPictureHash\fP"
.br
.ti -1c
.RI "class \fBvtm::SEIDependentRAPIndication\fP"
.br
.ti -1c
.RI "class \fBvtm::SEIBufferingPeriod\fP"
.br
.ti -1c
.RI "class \fBvtm::SEIPictureTiming\fP"
.br
.ti -1c
.RI "class \fBvtm::SEIDecodingUnitInfo\fP"
.br
.ti -1c
.RI "class \fBvtm::SEIFrameFieldInfo\fP"
.br
.ti -1c
.RI "class \fBvtm::SEIFramePacking\fP"
.br
.ti -1c
.RI "class \fBvtm::SEIParameterSetsInclusionIndication\fP"
.br
.ti -1c
.RI "class \fBvtm::SEIMasteringDisplayColourVolume\fP"
.br
.ti -1c
.RI "class \fBvtm::SEIScalableNesting\fP"
.br
.ti -1c
.RI "class \fBvtm::SEIAlternativeTransferCharacteristics\fP"
.br
.ti -1c
.RI "class \fBvtm::SEIUserDataRegistered\fP"
.br
.ti -1c
.RI "class \fBvtm::SEIFilmGrainCharacteristics\fP"
.br
.ti -1c
.RI "struct \fBvtm::SEIFilmGrainCharacteristics::CompModelIntensityValues\fP"
.br
.ti -1c
.RI "struct \fBvtm::SEIFilmGrainCharacteristics::CompModel\fP"
.br
.ti -1c
.RI "class \fBvtm::SEIContentLightLevelInfo\fP"
.br
.ti -1c
.RI "class \fBvtm::SEIAmbientViewingEnvironment\fP"
.br
.ti -1c
.RI "class \fBvtm::SEIContentColourVolume\fP"
.br
.ti -1c
.RI "class \fBvtm::SEISubpicureLevelInfo\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBvtm\fP"
.br
.in -1c
.in +1c
.ti -1c
.RI "\fBSEIMessages\fP \fBvtm::getSeisByType\fP (const \fBSEIMessages\fP &seiList, \fBSEI::PayloadType\fP seiType)"
.br
.RI "output a selection of \fBSEI\fP messages by payload type\&. Ownership stays in original message list\&. "
.ti -1c
.RI "\fBSEIMessages\fP \fBvtm::extractSeisByType\fP (\fBSEIMessages\fP &seiList, \fBSEI::PayloadType\fP seiType)"
.br
.RI "remove a selection of \fBSEI\fP messages by payload type from the original list and return them in a new list\&. "
.ti -1c
.RI "void \fBvtm::deleteSEIs\fP (\fBSEIMessages\fP &seiList)"
.br
.RI "delete list of \fBSEI\fP messages (freeing the referenced objects) "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
