.TH "deps/base_vvc/minimum_VTM/source/Lib/CommonLib/SEI.cpp" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deps/base_vvc/minimum_VTM/source/Lib/CommonLib/SEI.cpp \- helper functions for SEI handling  

.SH SYNOPSIS
.br
.PP
\fC#include 'CommonDef\&.h'\fP
.br
\fC#include 'SEI\&.h'\fP
.br
\fC#include 'dtrace_next\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "SEIMessages \fBgetSeisByType\fP (const SEIMessages &seiList, SEI::PayloadType seiType)"
.br
.ti -1c
.RI "SEIMessages \fBextractSeisByType\fP (SEIMessages &seiList, SEI::PayloadType seiType)"
.br
.ti -1c
.RI "void \fBdeleteSEIs\fP (SEIMessages &seiList)"
.br
.in -1c
.SH "Detailed Description"
.PP 
helper functions for SEI handling 


.PP
Definition in file \fBSEI\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "void deleteSEIs (SEIMessages & seiList)"

.PP
Definition at line \fB90\fP of file \fBSEI\&.cpp\fP\&.
.SS "SEIMessages extractSeisByType (SEIMessages & seiList, SEI::PayloadType seiType)"

.PP
Definition at line \fB69\fP of file \fBSEI\&.cpp\fP\&.
.SS "SEIMessages getSeisByType (const SEIMessages & seiList, SEI::PayloadType seiType)"

.PP
Definition at line \fB55\fP of file \fBSEI\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
