.TH "encoder/src/Serializer.cpp" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
encoder/src/Serializer.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'Serializer\&.hpp'\fP
.br
\fC#include 'BitstreamPacker\&.hpp'\fP
.br
\fC#include 'Config\&.hpp'\fP
.br
\fC#include 'Crop\&.hpp'\fP
.br
\fC#include 'Dimensions\&.hpp'\fP
.br
\fC#include 'Diagnostics\&.hpp'\fP
.br
\fC#include 'EntropyEncoder\&.hpp'\fP
.br
\fC#include 'Misc\&.hpp'\fP
.br
\fC#include <algorithm>\fP
.br
\fC#include <climits>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBlctm\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const unsigned \fBlctm::resolution_table\fP [51][2]"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
