.TH "util/include/SharedLibrary.hpp" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
util/include/SharedLibrary.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <dlfcn\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSHARED_PREFIX\fP   'lib'"
.br
.ti -1c
.RI "#define \fBSHARED_SUFFIX\fP   'so'"
.br
.ti -1c
.RI "#define \fBSHARED_LOAD\fP(name)   dlopen((name), RTLD_LAZY)"
.br
.ti -1c
.RI "#define \fBSHARED_SYMBOL\fP(h,  s)   dlsym((h),(s))"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef void * \fBshared_handle_t\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define SHARED_LOAD(name)   dlopen((name), RTLD_LAZY)"

.PP
Definition at line \fB56\fP of file \fBSharedLibrary\&.hpp\fP\&.
.SS "#define SHARED_PREFIX   'lib'"

.PP
Definition at line \fB54\fP of file \fBSharedLibrary\&.hpp\fP\&.
.SS "#define SHARED_SUFFIX   'so'"

.PP
Definition at line \fB55\fP of file \fBSharedLibrary\&.hpp\fP\&.
.SS "#define SHARED_SYMBOL(h, s)   dlsym((h),(s))"

.PP
Definition at line \fB57\fP of file \fBSharedLibrary\&.hpp\fP\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef void* \fBshared_handle_t\fP"

.PP
Definition at line \fB53\fP of file \fBSharedLibrary\&.hpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
