.TH "decoder/include/SignaledConfiguration.hpp" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
decoder/include/SignaledConfiguration.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'Config\&.hpp'\fP
.br
\fC#include 'Image\&.hpp'\fP
.br
\fC#include 'Packet\&.hpp'\fP
.br
\fC#include 'Types\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBlctm::SequenceConfiguration\fP"
.br
.ti -1c
.RI "struct \fBlctm::GlobalConfiguration\fP"
.br
.ti -1c
.RI "struct \fBlctm::PictureConfiguration\fP"
.br
.ti -1c
.RI "struct \fBlctm::AdditionalInfo\fP"
.br
.ti -1c
.RI "struct \fBlctm::SeiMasteringDisplayColourVolume\fP"
.br
.ti -1c
.RI "struct \fBlctm::SeiContentLightLevelInfo\fP"
.br
.ti -1c
.RI "struct \fBlctm::SeiUserDataRegisteredItutT35\fP"
.br
.ti -1c
.RI "struct \fBlctm::SeiUserDataUnrgistered\fP"
.br
.ti -1c
.RI "struct \fBlctm::VuiMessage\fP"
.br
.ti -1c
.RI "struct \fBlctm::SurfaceConfiguration\fP"
.br
.ti -1c
.RI "struct \fBlctm::SignaledConfiguration\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBlctm\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum { \fBlctm::MAX_NUM_PLANES\fP = 3 }"
.br
.ti -1c
.RI "enum { \fBlctm::MAX_NUM_LOQS\fP = 2 }"
.br
.ti -1c
.RI "enum { \fBlctm::MAX_NUM_LAYERS\fP = 17 }"
.br
.ti -1c
.RI "enum { \fBlctm::MIN_STEP_WIDTH\fP = 1 }"
.br
.ti -1c
.RI "enum { \fBlctm::MAX_STEP_WIDTH\fP = 32767 }"
.br
.ti -1c
.RI "enum { \fBlctm::MIN_BASE_QP\fP = 0 }"
.br
.ti -1c
.RI "enum { \fBlctm::MAX_BASE_QP\fP = 50 }"
.br
.ti -1c
.RI "enum : unsigned long { \fBlctm::MAX_OUTPUT_RATE_LEVEL_1\fP = 29410000, \fBlctm::MAX_OUTPUT_RATE_LEVEL_2\fP = 124560000, \fBlctm::MAX_OUTPUT_RATE_LEVEL_3\fP = 527650000, \fBlctm::MAX_OUTPUT_RATE_LEVEL_4\fP = 2235160000 }"
.br
.ti -1c
.RI "enum { \fBlctm::LOQ_LEVEL_1\fP = 0, \fBlctm::LOQ_LEVEL_2\fP = 1 }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
