.TH "deps/base_vvc/minimum_VTM/source/Lib/CommonLib/Slice.cpp" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deps/base_vvc/minimum_VTM/source/Lib/CommonLib/Slice.cpp \- slice header and SPS class  

.SH SYNOPSIS
.br
.PP
\fC#include 'CommonDef\&.h'\fP
.br
\fC#include 'Unit\&.h'\fP
.br
\fC#include 'Slice\&.h'\fP
.br
\fC#include 'Picture\&.h'\fP
.br
\fC#include 'dtrace_next\&.h'\fP
.br
\fC#include 'UnitTools\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBvtm\fP"
.br
.in -1c
.SS "Functions"

.PP
.RI "\fB\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "bool \fBvtm::operator==\fP (const \fBConstraintInfo\fP &op1, const \fBConstraintInfo\fP &op2)"
.br
.ti -1c
.RI "bool \fBvtm::operator!=\fP (const \fBConstraintInfo\fP &op1, const \fBConstraintInfo\fP &op2)"
.br
.ti -1c
.RI "bool \fBvtm::operator==\fP (const \fBProfileTierLevel\fP &op1, const \fBProfileTierLevel\fP &op2)"
.br
.ti -1c
.RI "bool \fBvtm::operator!=\fP (const \fBProfileTierLevel\fP &op1, const \fBProfileTierLevel\fP &op2)"
.br
.in -1c
.in -1c
.SH "Detailed Description"
.PP 
slice header and SPS class 


.PP
Definition in file \fBSlice\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
