.TH "deps/base_vvc/minimum_VTM/source/Lib/CommonLib/Slice.h" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deps/base_vvc/minimum_VTM/source/Lib/CommonLib/Slice.h \- slice header and SPS class (header)  

.SH SYNOPSIS
.br
.PP
\fC#include <cstring>\fP
.br
\fC#include <list>\fP
.br
\fC#include <map>\fP
.br
\fC#include <vector>\fP
.br
\fC#include 'CommonDef\&.h'\fP
.br
\fC#include 'Rom\&.h'\fP
.br
\fC#include 'ChromaFormat\&.h'\fP
.br
\fC#include 'Common\&.h'\fP
.br
\fC#include 'HRD\&.h'\fP
.br
\fC#include <unordered_map>\fP
.br
\fC#include 'AlfParameters\&.h'\fP
.br
\fC#include 'CommonLib/MotionInfo\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBvtm::DpbParameters\fP"
.br
.ti -1c
.RI "class \fBvtm::ReferencePictureList\fP"
.br
.ti -1c
.RI "class \fBvtm::RPLList\fP"
.br
.RI "Reference \fBPicture\fP List set class\&. "
.ti -1c
.RI "class \fBvtm::ScalingList\fP"
.br
.RI "SCALING_LIST class\&. "
.ti -1c
.RI "class \fBvtm::ConstraintInfo\fP"
.br
.ti -1c
.RI "class \fBvtm::ProfileTierLevel\fP"
.br
.ti -1c
.RI "class \fBvtm::SliceReshapeInfo\fP"
.br
.ti -1c
.RI "struct \fBvtm::ReshapeCW\fP"
.br
.ti -1c
.RI "struct \fBvtm::ChromaQpAdj\fP"
.br
.ti -1c
.RI "struct \fBvtm::ChromaQpMappingTableParams\fP"
.br
.ti -1c
.RI "struct \fBvtm::ChromaQpMappingTable\fP"
.br
.ti -1c
.RI "class \fBvtm::SliceMap\fP"
.br
.ti -1c
.RI "class \fBvtm::RectSlice\fP"
.br
.ti -1c
.RI "class \fBvtm::SubPic\fP"
.br
.ti -1c
.RI "class \fBvtm::DCI\fP"
.br
.ti -1c
.RI "class \fBvtm::OPI\fP"
.br
.ti -1c
.RI "class \fBvtm::VPS\fP"
.br
.ti -1c
.RI "class \fBvtm::Window\fP"
.br
.ti -1c
.RI "class \fBvtm::VUI\fP"
.br
.ti -1c
.RI "class \fBvtm::SPSRExt\fP"
.br
.RI "\fBSPS\fP RExt class\&. "
.ti -1c
.RI "class \fBvtm::SPS\fP"
.br
.RI "\fBSPS\fP class\&. "
.ti -1c
.RI "class \fBvtm::PPS\fP"
.br
.RI "\fBPPS\fP class\&. "
.ti -1c
.RI "class \fBvtm::APS\fP"
.br
.ti -1c
.RI "struct \fBvtm::WPScalingParam\fP"
.br
.ti -1c
.RI "struct \fBvtm::WPACDCParam\fP"
.br
.ti -1c
.RI "class \fBvtm::PicHeader\fP"
.br
.ti -1c
.RI "class \fBvtm::Slice\fP"
.br
.RI "slice header class "
.ti -1c
.RI "class \fBvtm::PreCalcValues\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBvtm\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
slice header and SPS class (header) 


.PP
Definition in file \fBSlice\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
