.TH "util/include/Surface.hpp" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
util/include/Surface.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'Buffer\&.hpp'\fP
.br
\fC#include 'Diagnostics\&.hpp'\fP
.br
\fC#include <cassert>\fP
.br
\fC#include <cstring>\fP
.br
\fC#include <functional>\fP
.br
\fC#include 'SurfaceImpl\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBlctm::SurfaceView< T, S >\fP"
.br
.ti -1c
.RI "class \fBlctm::SurfaceBuilder< T >\fP"
.br
.ti -1c
.RI "class \fBlctm::Surface\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBlctm\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
