.TH "encoder/include/TemporalEncode.hpp" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
encoder/include/TemporalEncode.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'Component\&.hpp'\fP
.br
\fC#include 'Dithering\&.hpp'\fP
.br
\fC#include 'Surface\&.hpp'\fP
.br
\fC#include 'Types\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBlctm::TemporalCost_2x2\fP"
.br
.ti -1c
.RI "class \fBlctm::TemporalCost_4x4\fP"
.br
.ti -1c
.RI "class \fBlctm::TemporalCost_SAD\fP"
.br
.ti -1c
.RI "class \fBlctm::TemporalSelect\fP"
.br
.ti -1c
.RI "class \fBlctm::TemporalMask\fP"
.br
.ti -1c
.RI "class \fBlctm::TemporalInsertMask\fP"
.br
.ti -1c
.RI "class \fBlctm::UserDataInsert\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBlctm\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
