.TH "deps/base_vvc/minimum_VTM/source/Lib/CommonLib/TrQuant_EMT.cpp" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deps/base_vvc/minimum_VTM/source/Lib/CommonLib/TrQuant_EMT.cpp \- transform and quantization class  

.SH SYNOPSIS
.br
.PP
\fC#include 'TrQuant_EMT\&.h'\fP
.br
\fC#include 'Rom\&.h'\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <math\&.h>\fP
.br
\fC#include <limits>\fP
.br
\fC#include <memory\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBfastForwardDCT2_B2\fP (const TCoeff *src, TCoeff *dst, int shift, int line, int iSkipLine, int iSkipLine2)"
.br
.ti -1c
.RI "void \fBfastInverseDCT2_B2\fP (const TCoeff *src, TCoeff *dst, int shift, int line, int iSkipLine, int iSkipLine2, const TCoeff outputMinimum, const TCoeff outputMaximum)"
.br
.ti -1c
.RI "void \fBfastForwardDCT2_B4\fP (const TCoeff *src, TCoeff *dst, int shift, int line, int iSkipLine, int iSkipLine2)"
.br
.ti -1c
.RI "void \fBfastInverseDCT2_B4\fP (const TCoeff *src, TCoeff *dst, int shift, int line, int iSkipLine, int iSkipLine2, const TCoeff outputMinimum, const TCoeff outputMaximum)"
.br
.ti -1c
.RI "template<int uiTrSize> void \fB_fastInverseMM\fP (const TCoeff *src, TCoeff *dst, int shift, int line, int iSkipLine, int iSkipLine2, const TCoeff outputMinimum, const TCoeff outputMaximum, const TMatrixCoeff *iT)"
.br
.ti -1c
.RI "template<int uiTrSize> void \fB_fastForwardMM\fP (const TCoeff *src, TCoeff *dst, int shift, int line, int iSkipLine, int iSkipLine2, const TMatrixCoeff *tc)"
.br
.ti -1c
.RI "void \fBfastForwardDCT2_B8\fP (const TCoeff *src, TCoeff *dst, int shift, int line, int iSkipLine, int iSkipLine2)"
.br
.ti -1c
.RI "void \fBfastInverseDCT2_B8\fP (const TCoeff *src, TCoeff *dst, int shift, int line, int iSkipLine, int iSkipLine2, const TCoeff outputMinimum, const TCoeff outputMaximum)"
.br
.ti -1c
.RI "void \fBfastForwardDCT2_B16\fP (const TCoeff *src, TCoeff *dst, int shift, int line, int iSkipLine, int iSkipLine2)"
.br
.ti -1c
.RI "void \fBfastInverseDCT2_B16\fP (const TCoeff *src, TCoeff *dst, int shift, int line, int iSkipLine, int iSkipLine2, const TCoeff outputMinimum, const TCoeff outputMaximum)"
.br
.ti -1c
.RI "void \fBfastForwardDCT2_B32\fP (const TCoeff *src, TCoeff *dst, int shift, int line, int iSkipLine, int iSkipLine2)"
.br
.ti -1c
.RI "void \fBfastInverseDCT2_B32\fP (const TCoeff *src, TCoeff *dst, int shift, int line, int iSkipLine, int iSkipLine2, const TCoeff outputMinimum, const TCoeff outputMaximum)"
.br
.ti -1c
.RI "void \fBfastForwardDCT2_B64\fP (const TCoeff *src, TCoeff *dst, int shift, int line, int iSkipLine, int iSkipLine2)"
.br
.ti -1c
.RI "void \fBfastInverseDCT2_B64\fP (const TCoeff *src, TCoeff *dst, int shift, int line, int iSkipLine, int iSkipLine2, const TCoeff outputMinimum, const TCoeff outputMaximum)"
.br
.ti -1c
.RI "void \fBfastForwardDST7_B4\fP (const TCoeff *src, TCoeff *dst, int shift, int line, int iSkipLine, int iSkipLine2)"
.br
.ti -1c
.RI "void \fBfastInverseDST7_B4\fP (const TCoeff *src, TCoeff *dst, int shift, int line, int iSkipLine, int iSkipLine2, const TCoeff outputMinimum, const TCoeff outputMaximum)"
.br
.ti -1c
.RI "void \fBfastForwardDST7_B8\fP (const TCoeff *src, TCoeff *dst, int shift, int line, int iSkipLine, int iSkipLine2)"
.br
.ti -1c
.RI "void \fBfastInverseDST7_B8\fP (const TCoeff *src, TCoeff *dst, int shift, int line, int iSkipLine, int iSkipLine2, const TCoeff outputMinimum, const TCoeff outputMaximum)"
.br
.ti -1c
.RI "void \fBfastForwardDST7_B16\fP (const TCoeff *src, TCoeff *dst, int shift, int line, int iSkipLine, int iSkipLine2)"
.br
.ti -1c
.RI "void \fBfastInverseDST7_B16\fP (const TCoeff *src, TCoeff *dst, int shift, int line, int iSkipLine, int iSkipLine2, const TCoeff outputMinimum, const TCoeff outputMaximum)"
.br
.ti -1c
.RI "void \fBfastForwardDST7_B32\fP (const TCoeff *src, TCoeff *dst, int shift, int line, int iSkipLine, int iSkipLine2)"
.br
.ti -1c
.RI "void \fBfastInverseDST7_B32\fP (const TCoeff *src, TCoeff *dst, int shift, int line, int iSkipLine, int iSkipLine2, const TCoeff outputMinimum, const TCoeff outputMaximum)"
.br
.ti -1c
.RI "void \fBfastForwardDCT8_B4\fP (const TCoeff *src, TCoeff *dst, int shift, int line, int iSkipLine, int iSkipLine2)"
.br
.ti -1c
.RI "void \fBfastInverseDCT8_B4\fP (const TCoeff *src, TCoeff *dst, int shift, int line, int iSkipLine, int iSkipLine2, const TCoeff outputMinimum, const TCoeff outputMaximum)"
.br
.ti -1c
.RI "void \fBfastForwardDCT8_B8\fP (const TCoeff *src, TCoeff *dst, int shift, int line, int iSkipLine, int iSkipLine2)"
.br
.ti -1c
.RI "void \fBfastInverseDCT8_B8\fP (const TCoeff *src, TCoeff *dst, int shift, int line, int iSkipLine, int iSkipLine2, const TCoeff outputMinimum, const TCoeff outputMaximum)"
.br
.ti -1c
.RI "void \fBfastForwardDCT8_B16\fP (const TCoeff *src, TCoeff *dst, int shift, int line, int iSkipLine, int iSkipLine2)"
.br
.ti -1c
.RI "void \fBfastInverseDCT8_B16\fP (const TCoeff *src, TCoeff *dst, int shift, int line, int iSkipLine, int iSkipLine2, const TCoeff outputMinimum, const TCoeff outputMaximum)"
.br
.ti -1c
.RI "void \fBfastForwardDCT8_B32\fP (const TCoeff *src, TCoeff *dst, int shift, int line, int iSkipLine, int iSkipLine2)"
.br
.ti -1c
.RI "void \fBfastInverseDCT8_B32\fP (const TCoeff *src, TCoeff *dst, int shift, int line, int iSkipLine, int iSkipLine2, const TCoeff outputMinimum, const TCoeff outputMaximum)"
.br
.in -1c
.SH "Detailed Description"
.PP 
transform and quantization class 


.PP
Definition in file \fBTrQuant_EMT\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "template<int uiTrSize> void _fastForwardMM (const TCoeff * src, TCoeff * dst, int shift, int line, int iSkipLine, int iSkipLine2, const TMatrixCoeff * tc)\fC [inline]\fP"

.PP
Definition at line \fB225\fP of file \fBTrQuant_EMT\&.cpp\fP\&.
.SS "template<int uiTrSize> void _fastInverseMM (const TCoeff * src, TCoeff * dst, int shift, int line, int iSkipLine, int iSkipLine2, const TCoeff outputMinimum, const TCoeff outputMaximum, const TMatrixCoeff * iT)\fC [inline]\fP"

.PP
Definition at line \fB198\fP of file \fBTrQuant_EMT\&.cpp\fP\&.
.SS "void fastForwardDCT2_B16 (const TCoeff * src, TCoeff * dst, int shift, int line, int iSkipLine, int iSkipLine2)"
16x16 forward transform implemented using partial butterfly structure (1D) 
.PP
\fBParameters\fP
.RS 4
\fIsrc\fP input data (residual) 
.br
\fIdst\fP output data (transform coefficients) 
.br
\fIshift\fP specifies right shift after 1D transform 
.br
\fIline\fP 
.RE
.PP

.PP
Definition at line \fB382\fP of file \fBTrQuant_EMT\&.cpp\fP\&.
.SS "void fastForwardDCT2_B2 (const TCoeff * src, TCoeff * dst, int shift, int line, int iSkipLine, int iSkipLine2)"

.PP
Definition at line \fB51\fP of file \fBTrQuant_EMT\&.cpp\fP\&.
.SS "void fastForwardDCT2_B32 (const TCoeff * src, TCoeff * dst, int shift, int line, int iSkipLine, int iSkipLine2)"
32x32 forward transform implemented using partial butterfly structure (1D) 
.PP
\fBParameters\fP
.RS 4
\fIsrc\fP input data (residual) 
.br
\fIdst\fP output data (transform coefficients) 
.br
\fIshift\fP specifies right shift after 1D transform 
.br
\fIline\fP 
.RE
.PP

.PP
Definition at line \fB513\fP of file \fBTrQuant_EMT\&.cpp\fP\&.
.SS "void fastForwardDCT2_B4 (const TCoeff * src, TCoeff * dst, int shift, int line, int iSkipLine, int iSkipLine2)"
4x4 forward transform implemented using partial butterfly structure (1D) 
.PP
\fBParameters\fP
.RS 4
\fIsrc\fP input data (residual) 
.br
\fIdst\fP output data (transform coefficients) 
.br
\fIshift\fP specifies right shift after 1D transform 
.br
\fIline\fP 
.RE
.PP

.PP
Definition at line \fB119\fP of file \fBTrQuant_EMT\&.cpp\fP\&.
.SS "void fastForwardDCT2_B64 (const TCoeff * src, TCoeff * dst, int shift, int line, int iSkipLine, int iSkipLine2)"

.PP
Definition at line \fB659\fP of file \fBTrQuant_EMT\&.cpp\fP\&.
.SS "void fastForwardDCT2_B8 (const TCoeff * src, TCoeff * dst, int shift, int line, int iSkipLine, int iSkipLine2)"
8x8 forward transform implemented using partial butterfly structure (1D) 
.PP
\fBParameters\fP
.RS 4
\fIsrc\fP input data (residual) 
.br
\fIdst\fP output data (transform coefficients) 
.br
\fIshift\fP specifies right shift after 1D transform 
.br
\fIline\fP 
.RE
.PP

.PP
Definition at line \fB275\fP of file \fBTrQuant_EMT\&.cpp\fP\&.
.SS "void fastForwardDCT8_B16 (const TCoeff * src, TCoeff * dst, int shift, int line, int iSkipLine, int iSkipLine2)"

.PP
Definition at line \fB1323\fP of file \fBTrQuant_EMT\&.cpp\fP\&.
.SS "void fastForwardDCT8_B32 (const TCoeff * src, TCoeff * dst, int shift, int line, int iSkipLine, int iSkipLine2)"

.PP
Definition at line \fB1447\fP of file \fBTrQuant_EMT\&.cpp\fP\&.
.SS "void fastForwardDCT8_B4 (const TCoeff * src, TCoeff * dst, int shift, int line, int iSkipLine, int iSkipLine2)"

.PP
Definition at line \fB1245\fP of file \fBTrQuant_EMT\&.cpp\fP\&.
.SS "void fastForwardDCT8_B8 (const TCoeff * src, TCoeff * dst, int shift, int line, int iSkipLine, int iSkipLine2)"

.PP
Definition at line \fB1312\fP of file \fBTrQuant_EMT\&.cpp\fP\&.
.SS "void fastForwardDST7_B16 (const TCoeff * src, TCoeff * dst, int shift, int line, int iSkipLine, int iSkipLine2)"

.PP
Definition at line \fB933\fP of file \fBTrQuant_EMT\&.cpp\fP\&.
.SS "void fastForwardDST7_B32 (const TCoeff * src, TCoeff * dst, int shift, int line, int iSkipLine, int iSkipLine2)"

.PP
Definition at line \fB1059\fP of file \fBTrQuant_EMT\&.cpp\fP\&.
.SS "void fastForwardDST7_B4 (const TCoeff * src, TCoeff * dst, int shift, int line, int iSkipLine, int iSkipLine2)"

.PP
Definition at line \fB852\fP of file \fBTrQuant_EMT\&.cpp\fP\&.
.SS "void fastForwardDST7_B8 (const TCoeff * src, TCoeff * dst, int shift, int line, int iSkipLine, int iSkipLine2)"

.PP
Definition at line \fB922\fP of file \fBTrQuant_EMT\&.cpp\fP\&.
.SS "void fastInverseDCT2_B16 (const TCoeff * src, TCoeff * dst, int shift, int line, int iSkipLine, int iSkipLine2, const TCoeff outputMinimum, const TCoeff outputMaximum)"
16x16 inverse transform implemented using partial butterfly structure (1D) 
.PP
\fBParameters\fP
.RS 4
\fIsrc\fP input data (transform coefficients) 
.br
\fIdst\fP output data (residual) 
.br
\fIshift\fP specifies right shift after 1D transform 
.br
\fIline\fP 
.br
\fIoutputMinimum\fP minimum for clipping 
.br
\fIoutputMaximum\fP maximum for clipping 
.RE
.PP

.PP
Definition at line \fB453\fP of file \fBTrQuant_EMT\&.cpp\fP\&.
.SS "void fastInverseDCT2_B2 (const TCoeff * src, TCoeff * dst, int shift, int line, int iSkipLine, int iSkipLine2, const TCoeff outputMinimum, const TCoeff outputMaximum)"

.PP
Definition at line \fB85\fP of file \fBTrQuant_EMT\&.cpp\fP\&.
.SS "void fastInverseDCT2_B32 (const TCoeff * src, TCoeff * dst, int shift, int line, int iSkipLine, int iSkipLine2, const TCoeff outputMinimum, const TCoeff outputMaximum)"
32x32 inverse transform implemented using partial butterfly structure (1D) 
.PP
\fBParameters\fP
.RS 4
\fIsrc\fP input data (transform coefficients) 
.br
\fIdst\fP output data (residual) 
.br
\fIshift\fP specifies right shift after 1D transform 
.br
\fIline\fP 
.br
\fIoutputMinimum\fP minimum for clipping 
.br
\fIoutputMaximum\fP maximum for clipping 
.RE
.PP

.PP
Definition at line \fB594\fP of file \fBTrQuant_EMT\&.cpp\fP\&.
.SS "void fastInverseDCT2_B4 (const TCoeff * src, TCoeff * dst, int shift, int line, int iSkipLine, int iSkipLine2, const TCoeff outputMinimum, const TCoeff outputMaximum)"
4x4 inverse transform implemented using partial butterfly structure (1D) 
.PP
\fBParameters\fP
.RS 4
\fIsrc\fP input data (transform coefficients) 
.br
\fIdst\fP output data (residual) 
.br
\fIshift\fP specifies right shift after 1D transform 
.br
\fIline\fP 
.br
\fIoutputMinimum\fP minimum for clipping 
.br
\fIoutputMaximum\fP maximum for clipping 
.RE
.PP

.PP
Definition at line \fB164\fP of file \fBTrQuant_EMT\&.cpp\fP\&.
.SS "void fastInverseDCT2_B64 (const TCoeff * src, TCoeff * dst, int shift, int line, int iSkipLine, int iSkipLine2, const TCoeff outputMinimum, const TCoeff outputMaximum)"

.PP
Definition at line \fB765\fP of file \fBTrQuant_EMT\&.cpp\fP\&.
.SS "void fastInverseDCT2_B8 (const TCoeff * src, TCoeff * dst, int shift, int line, int iSkipLine, int iSkipLine2, const TCoeff outputMinimum, const TCoeff outputMaximum)"
8x8 inverse transform implemented using partial butterfly structure (1D) 
.PP
\fBParameters\fP
.RS 4
\fIsrc\fP input data (transform coefficients) 
.br
\fIdst\fP output data (residual) 
.br
\fIshift\fP specifies right shift after 1D transform 
.br
\fIline\fP 
.br
\fIoutputMinimum\fP minimum for clipping 
.br
\fIoutputMaximum\fP maximum for clipping 
.RE
.PP

.PP
Definition at line \fB332\fP of file \fBTrQuant_EMT\&.cpp\fP\&.
.SS "void fastInverseDCT8_B16 (const TCoeff * src, TCoeff * dst, int shift, int line, int iSkipLine, int iSkipLine2, const TCoeff outputMinimum, const TCoeff outputMaximum)"

.PP
Definition at line \fB1391\fP of file \fBTrQuant_EMT\&.cpp\fP\&.
.SS "void fastInverseDCT8_B32 (const TCoeff * src, TCoeff * dst, int shift, int line, int iSkipLine, int iSkipLine2, const TCoeff outputMinimum, const TCoeff outputMaximum)"

.PP
Definition at line \fB1547\fP of file \fBTrQuant_EMT\&.cpp\fP\&.
.SS "void fastInverseDCT8_B4 (const TCoeff * src, TCoeff * dst, int shift, int line, int iSkipLine, int iSkipLine2, const TCoeff outputMinimum, const TCoeff outputMaximum)"

.PP
Definition at line \fB1281\fP of file \fBTrQuant_EMT\&.cpp\fP\&.
.SS "void fastInverseDCT8_B8 (const TCoeff * src, TCoeff * dst, int shift, int line, int iSkipLine, int iSkipLine2, const TCoeff outputMinimum, const TCoeff outputMaximum)"

.PP
Definition at line \fB1317\fP of file \fBTrQuant_EMT\&.cpp\fP\&.
.SS "void fastInverseDST7_B16 (const TCoeff * src, TCoeff * dst, int shift, int line, int iSkipLine, int iSkipLine2, const TCoeff outputMinimum, const TCoeff outputMaximum)"

.PP
Definition at line \fB1001\fP of file \fBTrQuant_EMT\&.cpp\fP\&.
.SS "void fastInverseDST7_B32 (const TCoeff * src, TCoeff * dst, int shift, int line, int iSkipLine, int iSkipLine2, const TCoeff outputMinimum, const TCoeff outputMaximum)"

.PP
Definition at line \fB1158\fP of file \fBTrQuant_EMT\&.cpp\fP\&.
.SS "void fastInverseDST7_B4 (const TCoeff * src, TCoeff * dst, int shift, int line, int iSkipLine, int iSkipLine2, const TCoeff outputMinimum, const TCoeff outputMaximum)"

.PP
Definition at line \fB889\fP of file \fBTrQuant_EMT\&.cpp\fP\&.
.SS "void fastInverseDST7_B8 (const TCoeff * src, TCoeff * dst, int shift, int line, int iSkipLine, int iSkipLine2, const TCoeff outputMinimum, const TCoeff outputMaximum)"

.PP
Definition at line \fB927\fP of file \fBTrQuant_EMT\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
