.TH "deps/base_vvc/minimum_VTM/source/Lib/CommonLib/TrQuant.h" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deps/base_vvc/minimum_VTM/source/Lib/CommonLib/TrQuant.h \- transform and quantization class (header)  

.SH SYNOPSIS
.br
.PP
\fC#include 'CommonDef\&.h'\fP
.br
\fC#include 'Unit\&.h'\fP
.br
\fC#include 'ChromaFormat\&.h'\fP
.br
\fC#include 'Contexts\&.h'\fP
.br
\fC#include 'ContextModelling\&.h'\fP
.br
\fC#include 'UnitPartitioner\&.h'\fP
.br
\fC#include 'Quant\&.h'\fP
.br
\fC#include 'DepQuant\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBvtm::TrQuant\fP"
.br
.RI "transform and quantization class "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBvtm\fP"
.br
.in -1c
.SS "Typedefs"

.PP
.RI "\fB\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "typedef void \fBvtm::FwdTrans\fP(const \fBTCoeff\fP *, \fBTCoeff\fP *, int, int, int, int)"
.br
.ti -1c
.RI "typedef void \fBvtm::InvTrans\fP(const \fBTCoeff\fP *, \fBTCoeff\fP *, int, int, int, int, const \fBTCoeff\fP, const \fBTCoeff\fP)"
.br
.in -1c
.in -1c
.SH "Detailed Description"
.PP 
transform and quantization class (header) 


.PP
Definition in file \fBTrQuant\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
