.TH "deps/base_hevc/include/TVideoIOYuvMem.h" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deps/base_hevc/include/TVideoIOYuvMem.h \- YUV file I/O class (header)  

.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include 'TLibCommon/CommonDef\&.h'\fP
.br
\fC#include 'TLibCommon/TComPicYuv\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTVideoIOYuvMem\fP"
.br
.RI "YUV file I/O class\&. "
.ti -1c
.RI "class \fBTVideoIOYuvMem::Writer\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
YUV file I/O class (header) 


.PP
Definition in file \fBTVideoIOYuvMem\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
