.TH "TVideoIOYuvMem::Writer" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TVideoIOYuvMem::Writer
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <TVideoIOYuvMem\&.h>\fP
.PP
Inherited by \fBContext\fP, and \fBlctm::BaseVideoDecoderHM\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBpicture_begin\fP (bool is16bit, UInt width, UInt height, ChromaFormat format)=0"
.br
.ti -1c
.RI "virtual int \fBwrite\fP (const uint8_t *data, size_t size)=0"
.br
.ti -1c
.RI "virtual void \fBpicture_end\fP ()=0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB58\fP of file \fBTVideoIOYuvMem\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual void TVideoIOYuvMem::Writer::picture_begin (bool is16bit, UInt width, UInt height, ChromaFormat format)\fC [pure virtual]\fP"

.PP
Implemented in \fBContext\fP\&.
.SS "virtual void TVideoIOYuvMem::Writer::picture_end ()\fC [pure virtual]\fP"

.PP
Implemented in \fBContext\fP, and \fBContext\fP\&.
.SS "virtual int TVideoIOYuvMem::Writer::write (const uint8_t * data, size_t size)\fC [pure virtual]\fP"

.PP
Implemented in \fBContext\fP, and \fBContext\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
