.TH "TVideoIOYuvMem" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TVideoIOYuvMem \- YUV file I/O class\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <TVideoIOYuvMem\&.h>\fP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBWriter\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTVideoIOYuvMem\fP ()"
.br
.ti -1c
.RI "virtual \fB~TVideoIOYuvMem\fP ()"
.br
.ti -1c
.RI "Void \fBopen\fP (\fBWriter\fP *writer, const Int fileBitDepth[MAX_NUM_CHANNEL_TYPE], const Int MSBExtendedBitDepth[MAX_NUM_CHANNEL_TYPE], const Int internalBitDepth[MAX_NUM_CHANNEL_TYPE])"
.br
.RI "open or create file "
.ti -1c
.RI "Void \fBclose\fP ()"
.br
.RI "close file "
.ti -1c
.RI "Void \fBskipFrames\fP (Int numFrames, UInt width, UInt height, ChromaFormat format)"
.br
.ti -1c
.RI "Bool \fBread\fP (TComPicYuv *pPicYuv, TComPicYuv *pPicYuvTrueOrg, const InputColourSpaceConversion ipcsc, Int aiPad[2], ChromaFormat fileFormat=NUM_CHROMA_FORMAT, const Bool bClipToRec709=false)"
.br
.RI "read one frame with padding parameter "
.ti -1c
.RI "Bool \fBwrite\fP (TComPicYuv *pPicYuv, const InputColourSpaceConversion ipCSC, Int confLeft=0, Int confRight=0, Int confTop=0, Int confBottom=0, ChromaFormat fileFormat=NUM_CHROMA_FORMAT, const Bool bClipToRec709=false)"
.br
.RI "write one YUV frame with padding parameter "
.ti -1c
.RI "Bool \fBwrite\fP (TComPicYuv *pPicYuvTop, TComPicYuv *pPicYuvBottom, const InputColourSpaceConversion ipCSC, Int confLeft=0, Int confRight=0, Int confTop=0, Int confBottom=0, ChromaFormat fileFormat=NUM_CHROMA_FORMAT, const Bool isTff=false, const Bool bClipToRec709=false)"
.br
.ti -1c
.RI "Bool \fBisEof\fP ()"
.br
.RI "check for end-of-file "
.ti -1c
.RI "Bool \fBisFail\fP ()"
.br
.RI "check for failure "
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "\fBstatic\fP Void \fBColourSpaceConvert\fP (const TComPicYuv &src, TComPicYuv &dest, const InputColourSpaceConversion conversion, Bool bIsForwards)"
.br
.in -1c
.SH "Detailed Description"
.PP 
YUV file I/O class\&. 
.PP
Definition at line \fB54\fP of file \fBTVideoIOYuvMem\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TVideoIOYuvMem::TVideoIOYuvMem ()\fC [inline]\fP"

.PP
Definition at line \fB72\fP of file \fBTVideoIOYuvMem\&.h\fP\&.
.SS "virtual TVideoIOYuvMem::~TVideoIOYuvMem ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Definition at line \fB73\fP of file \fBTVideoIOYuvMem\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "Void TVideoIOYuvMem::close ()"

.PP
close file 
.PP
Definition at line \fB139\fP of file \fBTVideoIOYuvMem\&.cpp\fP\&.
.SS "Void TVideoIOYuvMem::ColourSpaceConvert (const TComPicYuv & src, TComPicYuv & dest, const InputColourSpaceConversion conversion, Bool bIsForwards)\fC [static]\fP"

.PP
Definition at line \fB968\fP of file \fBTVideoIOYuvMem\&.cpp\fP\&.
.SS "Bool TVideoIOYuvMem::isEof ()"

.PP
check for end-of-file 
.PP
Definition at line \fB144\fP of file \fBTVideoIOYuvMem\&.cpp\fP\&.
.SS "Bool TVideoIOYuvMem::isFail ()"

.PP
check for failure 
.PP
Definition at line \fB149\fP of file \fBTVideoIOYuvMem\&.cpp\fP\&.
.SS "Void TVideoIOYuvMem::open (\fBWriter\fP * writer, const Int fileBitDepth[MAX_NUM_CHANNEL_TYPE], const Int MSBExtendedBitDepth[MAX_NUM_CHANNEL_TYPE], const Int internalBitDepth[MAX_NUM_CHANNEL_TYPE])"

.PP
open or create file Open file for reading/writing Y'CbCr frames\&.
.PP
Frames read/written have bitdepth fileBitDepth, and are automatically formatted as 8 or 16 bit word values (see \fBTVideoIOYuvMem::write()\fP)\&.
.PP
Image data read or written is converted to/from internalBitDepth (See scalePlane(), \fBTVideoIOYuvMem::read()\fP and \fBTVideoIOYuvMem::write()\fP for further details)\&.
.PP
\fBParameters\fP
.RS 4
\fIpchFile\fP file name string 
.br
\fIbWriteMode\fP file open mode: true=write, false=read 
.br
\fIfileBitDepth\fP bit-depth array of input/output file data\&. 
.br
\fIMSBExtendedBitDepth\fP 
.br
\fIinternalBitDepth\fP bit-depth array to scale image data to/from when reading/writing\&. 
.RE
.PP

.PP
Definition at line \fB119\fP of file \fBTVideoIOYuvMem\&.cpp\fP\&.
.SS "Bool TVideoIOYuvMem::read (TComPicYuv * pPicYuvUser, TComPicYuv * pPicYuvTrueOrg, const InputColourSpaceConversion ipcsc, Int aiPad[2], ChromaFormat format = \fCNUM_CHROMA_FORMAT\fP, const Bool bClipToRec709 = \fCfalse\fP)"

.PP
read one frame with padding parameter Read one Y'CbCr frame, performing any required input scaling to change from the bitdepth of the input file to the internal bit-depth\&.
.PP
If a bit-depth reduction is required, and internalBitdepth >= 8, then the input file is assumed to be ITU-R BT\&.601/709 compliant, and the resulting data is clipped to the appropriate legal range, as if the file had been provided at the lower-bitdepth compliant to Rec601/709\&.
.PP
\fBParameters\fP
.RS 4
\fIpPicYuvUser\fP input picture YUV buffer class pointer 
.br
\fIpPicYuvTrueOrg\fP 
.br
\fIipcsc\fP 
.br
\fIaiPad\fP source padding size, aiPad[0] = horizontal, aiPad[1] = vertical 
.br
\fIformat\fP chroma format 
.RE
.PP
\fBReturns\fP
.RS 4
true for success, false in case of error 
.RE
.PP

.PP
Definition at line \fB649\fP of file \fBTVideoIOYuvMem\&.cpp\fP\&.
.SS "Void TVideoIOYuvMem::skipFrames (Int numFrames, UInt width, UInt height, ChromaFormat format)"
Skip numFrames in input\&.
.PP
This function correctly handles cases where the input file is not seekable, by consuming bytes\&. 
.PP
Definition at line \fB160\fP of file \fBTVideoIOYuvMem\&.cpp\fP\&.
.SS "Bool TVideoIOYuvMem::write (TComPicYuv * pPicYuvUser, const InputColourSpaceConversion ipCSC, Int confLeft = \fC0\fP, Int confRight = \fC0\fP, Int confTop = \fC0\fP, Int confBottom = \fC0\fP, ChromaFormat format = \fCNUM_CHROMA_FORMAT\fP, const Bool bClipToRec709 = \fCfalse\fP)"

.PP
write one YUV frame with padding parameter Write one Y'CbCr frame\&. No bit-depth conversion is performed, pcPicYuv is assumed to be at TVideoIO::m_fileBitdepth depth\&.
.PP
\fBParameters\fP
.RS 4
\fIpPicYuvUser\fP input picture YUV buffer class pointer 
.br
\fIipCSC\fP 
.br
\fIconfLeft\fP conformance window left border 
.br
\fIconfRight\fP conformance window right border 
.br
\fIconfTop\fP conformance window top border 
.br
\fIconfBottom\fP conformance window bottom border 
.br
\fIformat\fP chroma format 
.RE
.PP
\fBReturns\fP
.RS 4
true for success, false in case of error 
.RE
.PP

.PP
Definition at line \fB730\fP of file \fBTVideoIOYuvMem\&.cpp\fP\&.
.SS "Bool TVideoIOYuvMem::write (TComPicYuv * pPicYuvTop, TComPicYuv * pPicYuvBottom, const InputColourSpaceConversion ipCSC, Int confLeft = \fC0\fP, Int confRight = \fC0\fP, Int confTop = \fC0\fP, Int confBottom = \fC0\fP, ChromaFormat fileFormat = \fCNUM_CHROMA_FORMAT\fP, const Bool isTff = \fCfalse\fP, const Bool bClipToRec709 = \fCfalse\fP)"

.PP
Definition at line \fB821\fP of file \fBTVideoIOYuvMem\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
