.TH "deps/base_hevc/src/TVideoIOYuvMem.cpp" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deps/base_hevc/src/TVideoIOYuvMem.cpp \- YUV file I/O class\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <cstdlib>\fP
.br
\fC#include <assert\&.h>\fP
.br
\fC#include <memory\&.h>\fP
.br
\fC#include 'TLibCommon/TComRom\&.h'\fP
.br
\fC#include 'TVideoIOYuvMem\&.h'\fP
.br

.SH "Detailed Description"
.PP 
YUV file I/O class\&. 


.PP
Definition in file \fBTVideoIOYuvMem\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
