.TH "src/Types.hpp" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Types.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBlctm\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBlctm::Upsample\fP { \fBlctm::Upsample_Nearest\fP, \fBlctm::Upsample_Linear\fP, \fBlctm::Upsample_Cubic\fP, \fBlctm::Upsample_ModifiedCubic\fP, \fBlctm::Upsample_AdaptiveCubic\fP }"
.br
.ti -1c
.RI "enum \fBlctm::Downsample\fP { \fBlctm::Downsample_Area\fP, \fBlctm::Downsample_Lanczos\fP, \fBlctm::Downsample_Lanczos3\fP }"
.br
.ti -1c
.RI "enum \fBlctm::ScalingMode\fP { \fBlctm::ScalingMode_None\fP, \fBlctm::ScalingMode_1D\fP, \fBlctm::ScalingMode_2D\fP }"
.br
.ti -1c
.RI "enum \fBlctm::UserDataMode\fP { \fBlctm::UserData_None\fP, \fBlctm::UserData_2bits\fP, \fBlctm::UserData_6bits\fP }"
.br
.ti -1c
.RI "enum \fBlctm::UserDataMethod\fP { \fBlctm::UserDataMethod_Zeros\fP, \fBlctm::UserDataMethod_Ones\fP, \fBlctm::UserDataMethod_Random\fP, \fBlctm::UserDataMethod_FixedRandom\fP }"
.br
.ti -1c
.RI "enum \fBlctm::TileDimensions\fP { \fBlctm::TileDimensions_None\fP, \fBlctm::TileDimensions_512x256\fP, \fBlctm::TileDimensions_1024x512\fP, \fBlctm::TileDimensions_Custom\fP }"
.br
.ti -1c
.RI "enum \fBlctm::QuantMatrix\fP { \fBlctm::QuantMatrix_BothPrevious\fP, \fBlctm::QuantMatrix_BothDefault\fP, \fBlctm::QuantMatrix_SameAndCustom\fP, \fBlctm::QuantMatrix_Level2CustomLevel1Default\fP, \fBlctm::QuantMatrix_Level2DefaultLevel1Custom\fP, \fBlctm::QuantMatrix_DifferentAndCustom\fP }"
.br
.ti -1c
.RI "enum \fBlctm::CompressionType\fP { \fBlctm::CompressionType_None\fP, \fBlctm::CompressionType_Prefix\fP, \fBlctm::CompressionType_Prefix_OnDiff\fP }"
.br
.ti -1c
.RI "enum \fBlctm::DitheringType\fP { \fBlctm::Dithering_None\fP, \fBlctm::Dithering_Uniform\fP, \fBlctm::Dithering_UniformFixed\fP }"
.br
.ti -1c
.RI "enum \fBlctm::DequantOffset\fP { \fBlctm::DequantOffset_Default\fP, \fBlctm::DequantOffset_ConstOffset\fP }"
.br
.ti -1c
.RI "enum \fBlctm::TransformType\fP { \fBlctm::TransformType_DD\fP, \fBlctm::TransformType_DDS\fP }"
.br
.ti -1c
.RI "enum \fBlctm::PictureType\fP { \fBlctm::PictureType_Frame\fP, \fBlctm::PictureType_Field\fP }"
.br
.ti -1c
.RI "enum \fBlctm::FieldType\fP { \fBlctm::FieldType_Top\fP, \fBlctm::FieldType_Bottom\fP }"
.br
.ti -1c
.RI "enum \fBlctm::CodingType\fP { \fBlctm::CodingType_IDR\fP, \fBlctm::CodingType_NonIDR\fP }"
.br
.ti -1c
.RI "enum \fBlctm::NalUnitType\fP { \fBlctm::LCEVC_NON_IDR\fP = 28, \fBlctm::LCEVC_IDR\fP = 29, \fBlctm::LCEVC_RSV\fP = 30 }"
.br
.ti -1c
.RI "enum \fBlctm::Profile\fP { \fBlctm::Profile_Main\fP, \fBlctm::Profile_Main444\fP, \fBlctm::Profile_Auto\fP }"
.br
.ti -1c
.RI "enum \fBlctm::BaseCoding\fP { \fBlctm::BaseCoding_Unknown\fP, \fBlctm::BaseCoding_AVC\fP, \fBlctm::BaseCoding_HEVC\fP, \fBlctm::BaseCoding_VVC\fP, \fBlctm::BaseCoding_EVC\fP, \fBlctm::BaseCoding_X265\fP, \fBlctm::BaseCoding_YUV\fP }"
.br
.ti -1c
.RI "enum \fBlctm::Encapsulation\fP { \fBlctm::Encapsulation_None\fP, \fBlctm::Encapsulation_SEI_Unregistered\fP, \fBlctm::Encapsulation_SEI_Registered\fP, \fBlctm::Encapsulation_NAL\fP }"
.br
.ti -1c
.RI "enum \fBlctm::BaseFrameType\fP { \fBlctm::BaseFrame_IDR\fP, \fBlctm::BaseFrame_Intra\fP, \fBlctm::BaseFrame_Inter\fP, \fBlctm::BaseFrame_Pred\fP, \fBlctm::BaseFrame_Bidi\fP }"
.br
.ti -1c
.RI "enum \fBlctm::Temporal_SWM\fP { \fBlctm::SWM_Disabled\fP = 0, \fBlctm::SWM_Active\fP = 1, \fBlctm::SWM_Dependent\fP = 2 }"
.br
.ti -1c
.RI "enum \fBlctm::SyntaxBlocks\fP { \fBlctm::SyntaxBlock_Sequence\fP = 1, \fBlctm::SyntaxBlock_Global\fP = 2, \fBlctm::SyntaxBlock_Picture\fP = 4, \fBlctm::SyntaxBlock_EncodedData\fP = 8, \fBlctm::SyntaxBlock_EncodedData_Tiled\fP = 16, \fBlctm::SyntaxBlock_Additional_Info\fP = 32, \fBlctm::SyntaxBlock_Filler\fP = 64 }"
.br
.ti -1c
.RI "enum \fBlctm::ParameterConfig\fP { \fBlctm::ParameterConfig_Default\fP, \fBlctm::ParameterConfig_Conformance\fP }"
.br
.ti -1c
.RI "enum \fBlctm::ResidualLabel\fP { \fBlctm::RESIDUAL_LIVE\fP = 128, \fBlctm::RESIDUAL_KILL\fP = 192 }"
.br
.ti -1c
.RI "enum \fBlctm::TemporalType\fP { \fBlctm::TEMPORAL_PRED\fP = 128, \fBlctm::TEMPORAL_INTR\fP = 192 }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::istream & \fBlctm::operator>>\fP (std::istream &in, \fBUpsample\fP &v)"
.br
.ti -1c
.RI "std::istream & \fBlctm::operator>>\fP (std::istream &in, \fBDownsample\fP &v)"
.br
.ti -1c
.RI "std::istream & \fBlctm::operator>>\fP (std::istream &in, \fBScalingMode\fP &v)"
.br
.ti -1c
.RI "std::istream & \fBlctm::operator>>\fP (std::istream &in, \fBQuantMatrix\fP &v)"
.br
.ti -1c
.RI "std::istream & \fBlctm::operator>>\fP (std::istream &in, \fBDitheringType\fP &v)"
.br
.ti -1c
.RI "std::istream & \fBlctm::operator>>\fP (std::istream &in, \fBDequantOffset\fP &v)"
.br
.ti -1c
.RI "std::istream & \fBlctm::operator>>\fP (std::istream &in, \fBTransformType\fP &v)"
.br
.ti -1c
.RI "std::istream & \fBlctm::operator>>\fP (std::istream &in, \fBBaseCoding\fP &v)"
.br
.ti -1c
.RI "std::istream & \fBlctm::operator>>\fP (std::istream &in, \fBEncapsulation\fP &v)"
.br
.ti -1c
.RI "std::istream & \fBlctm::operator>>\fP (std::istream &in, \fBCompressionType\fP &v)"
.br
.ti -1c
.RI "std::istream & \fBlctm::operator>>\fP (std::istream &in, \fBUserDataMode\fP &v)"
.br
.ti -1c
.RI "std::istream & \fBlctm::operator>>\fP (std::istream &in, \fBUserDataMethod\fP &v)"
.br
.ti -1c
.RI "std::istream & \fBlctm::operator>>\fP (std::istream &in, \fBPictureType\fP &v)"
.br
.ti -1c
.RI "std::istream & \fBlctm::operator>>\fP (std::istream &in, \fBProfile\fP &v)"
.br
.ti -1c
.RI "std::istream & \fBlctm::operator>>\fP (std::istream &in, \fBParameterConfig\fP &v)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
