.TH "src/Types.cpp" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Types.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'Types\&.hpp'\fP
.br
\fC#include 'Diagnostics\&.hpp'\fP
.br
\fC#include 'Misc\&.hpp'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBlctm\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::istream & \fBlctm::operator>>\fP (std::istream &in, \fBUpsample\fP &v)"
.br
.ti -1c
.RI "std::istream & \fBlctm::operator>>\fP (std::istream &in, \fBDownsample\fP &v)"
.br
.ti -1c
.RI "std::istream & \fBlctm::operator>>\fP (std::istream &in, \fBScalingMode\fP &v)"
.br
.ti -1c
.RI "std::istream & \fBlctm::operator>>\fP (std::istream &in, \fBDitheringType\fP &v)"
.br
.ti -1c
.RI "std::istream & \fBlctm::operator>>\fP (std::istream &in, \fBDequantOffset\fP &v)"
.br
.ti -1c
.RI "std::istream & \fBlctm::operator>>\fP (std::istream &in, \fBTransformType\fP &v)"
.br
.ti -1c
.RI "std::istream & \fBlctm::operator>>\fP (std::istream &in, \fBBaseCoding\fP &v)"
.br
.ti -1c
.RI "std::istream & \fBlctm::operator>>\fP (std::istream &in, \fBEncapsulation\fP &v)"
.br
.ti -1c
.RI "std::istream & \fBlctm::operator>>\fP (std::istream &in, \fBQuantMatrix\fP &v)"
.br
.ti -1c
.RI "std::istream & \fBlctm::operator>>\fP (std::istream &in, \fBCompressionType\fP &v)"
.br
.ti -1c
.RI "std::istream & \fBlctm::operator>>\fP (std::istream &in, \fBUserDataMode\fP &v)"
.br
.ti -1c
.RI "std::istream & \fBlctm::operator>>\fP (std::istream &in, \fBUserDataMethod\fP &v)"
.br
.ti -1c
.RI "std::istream & \fBlctm::operator>>\fP (std::istream &in, \fBPictureType\fP &v)"
.br
.ti -1c
.RI "std::istream & \fBlctm::operator>>\fP (std::istream &in, \fBProfile\fP &v)"
.br
.ti -1c
.RI "std::istream & \fBlctm::operator>>\fP (std::istream &in, \fBParameterConfig\fP &v)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
