.TH "src/uBaseDecoderVVC.cpp" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/uBaseDecoderVVC.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <algorithm>\fP
.br
\fC#include <assert\&.h>\fP
.br
\fC#include <climits>\fP
.br
\fC#include <cmath>\fP
.br
\fC#include <memory\&.h>\fP
.br
\fC#include <stdexcept>\fP
.br
\fC#include 'CommonLib/BitStream\&.h'\fP
.br
\fC#include 'DecoderLib/VLCReader\&.h'\fP
.br
\fC#include 'Misc\&.hpp'\fP
.br
\fC#include 'uBaseDecoderVVC\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBvnova\fP"
.br
.ti -1c
.RI "namespace \fBvnova::utility\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::unique_ptr< \fBBaseDecoder\fP > \fBvnova::utility::CreateBaseDecoderVVC\fP ()"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
