.TH "src/uBaseDecoderEVC.cpp" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/uBaseDecoderEVC.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <algorithm>\fP
.br
\fC#include <assert\&.h>\fP
.br
\fC#include <climits>\fP
.br
\fC#include <cmath>\fP
.br
\fC#include <memory\&.h>\fP
.br
\fC#include <stdexcept>\fP
.br
\fC#include 'Misc\&.hpp'\fP
.br
\fC#include 'uBaseDecoderEVC\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBvnova\fP"
.br
.ti -1c
.RI "namespace \fBvnova::utility\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSLICE_B\fP   0"
.br
.ti -1c
.RI "#define \fBSLICE_P\fP   1"
.br
.ti -1c
.RI "#define \fBSLICE_I\fP   2"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::unique_ptr< \fBBaseDecoder\fP > \fBvnova::utility::CreateBaseDecoderEVC\fP ()"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define SLICE_B   0"

.PP
Definition at line \fB55\fP of file \fBuBaseDecoderEVC\&.cpp\fP\&.
.SS "#define SLICE_I   2"

.PP
Definition at line \fB57\fP of file \fBuBaseDecoderEVC\&.cpp\fP\&.
.SS "#define SLICE_P   1"

.PP
Definition at line \fB56\fP of file \fBuBaseDecoderEVC\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
