.TH "src/uBaseDecoderVVC.h" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/uBaseDecoderVVC.h
.SH SYNOPSIS
.br
.PP
\fC#include <memory>\fP
.br
\fC#include 'uTypes\&.h'\fP
.br
\fC#include 'uBaseDecoder\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBvnova::utility::VVCNalType\fP"
.br
.ti -1c
.RI "class \fBvnova::utility::BaseDecoderVVC\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBvnova\fP"
.br
.ti -1c
.RI "namespace \fBvnova::utility\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB__BASE_VVC__\fP   1"
.br
.ti -1c
.RI "#define \fBVVCMaxSPSCount\fP   16"
.br
.ti -1c
.RI "#define \fBVVCMaxPPSCount\fP   64"
.br
.ti -1c
.RI "#define \fBVVCMaxSubLayersCount\fP   8"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define __BASE_VVC__   1"

.PP
Definition at line \fB43\fP of file \fBuBaseDecoderVVC\&.h\fP\&.
.SS "#define VVCMaxPPSCount   64"

.PP
Definition at line \fB46\fP of file \fBuBaseDecoderVVC\&.h\fP\&.
.SS "#define VVCMaxSPSCount   16"

.PP
Definition at line \fB45\fP of file \fBuBaseDecoderVVC\&.h\fP\&.
.SS "#define VVCMaxSubLayersCount   8"

.PP
Definition at line \fB47\fP of file \fBuBaseDecoderVVC\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
