.TH "src/uBaseDecoder.h" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/uBaseDecoder.h
.SH SYNOPSIS
.br
.PP
\fC#include 'uTypes\&.h'\fP
.br
\fC#include <map>\fP
.br
\fC#include <memory>\fP
.br
\fC#include <vector>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBvnova::utility::BaseDecPictType\fP"
.br
.ti -1c
.RI "struct \fBvnova::utility::BaseDecNalUnitType\fP"
.br
.ti -1c
.RI "class \fBvnova::utility::BaseDecoder\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBvnova\fP"
.br
.ti -1c
.RI "namespace \fBvnova::utility\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBvnova::utility::NALDelimitier\fP { \fBvnova::utility::NALDelimiterNone\fP = 0, \fBvnova::utility::NALDelimiterMarker\fP, \fBvnova::utility::NALDelimiterU32Length\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::unique_ptr< \fBBaseDecoder\fP > \fBvnova::utility::CreateBaseDecoder\fP (\fBBaseDecoder::Codec\fP base_codec)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
