.TH "src/uBaseDecoderHEVC.h" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/uBaseDecoderHEVC.h
.SH SYNOPSIS
.br
.PP
\fC#include 'uTypes\&.h'\fP
.br
\fC#include 'uBaseDecoder\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBvnova::utility::HEVCNalType\fP"
.br
.ti -1c
.RI "class \fBvnova::utility::BaseDecoderHEVC\fP"
.br
.ti -1c
.RI "struct \fBvnova::utility::BaseDecoderHEVC::SPS::VUI\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBvnova\fP"
.br
.ti -1c
.RI "namespace \fBvnova::utility\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBHEVCMaxSPSCount\fP   16"
.br
.ti -1c
.RI "#define \fBHEVCMaxPPSCount\fP   64"
.br
.ti -1c
.RI "#define \fBHEVCMaxSubLayersCount\fP   8"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define HEVCMaxPPSCount   64"

.PP
Definition at line \fB42\fP of file \fBuBaseDecoderHEVC\&.h\fP\&.
.SS "#define HEVCMaxSPSCount   16"

.PP
Definition at line \fB41\fP of file \fBuBaseDecoderHEVC\&.h\fP\&.
.SS "#define HEVCMaxSubLayersCount   8"

.PP
Definition at line \fB43\fP of file \fBuBaseDecoderHEVC\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
