.TH "src/uBaseDecoderEVC.h" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/uBaseDecoderEVC.h
.SH SYNOPSIS
.br
.PP
\fC#include 'uTypes\&.h'\fP
.br
\fC#include 'uBaseDecoder\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBvnova::utility::EVCNalType\fP"
.br
.ti -1c
.RI "class \fBvnova::utility::BaseDecoderEVC\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBvnova\fP"
.br
.ti -1c
.RI "namespace \fBvnova::utility\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBEVCMaxSPSCount\fP   16"
.br
.ti -1c
.RI "#define \fBEVCMaxPPSCount\fP   64"
.br
.ti -1c
.RI "#define \fBEVCMaxSubLayersCount\fP   8"
.br
.ti -1c
.RI "#define \fBEVCMaxTilesRow\fP   22"
.br
.ti -1c
.RI "#define \fBEVCMaxTilesCol\fP   20"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define EVCMaxPPSCount   64"

.PP
Definition at line \fB42\fP of file \fBuBaseDecoderEVC\&.h\fP\&.
.SS "#define EVCMaxSPSCount   16"

.PP
Definition at line \fB41\fP of file \fBuBaseDecoderEVC\&.h\fP\&.
.SS "#define EVCMaxSubLayersCount   8"

.PP
Definition at line \fB43\fP of file \fBuBaseDecoderEVC\&.h\fP\&.
.SS "#define EVCMaxTilesCol   20"

.PP
Definition at line \fB46\fP of file \fBuBaseDecoderEVC\&.h\fP\&.
.SS "#define EVCMaxTilesRow   22"

.PP
Definition at line \fB45\fP of file \fBuBaseDecoderEVC\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
