.TH "src/uBaseDecoderAVC.h" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/uBaseDecoderAVC.h
.SH SYNOPSIS
.br
.PP
\fC#include 'uTypes\&.h'\fP
.br
\fC#include 'uBaseDecoder\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBvnova::utility::AVCNalType\fP"
.br
.ti -1c
.RI "class \fBvnova::utility::BaseDecoderAVC\fP"
.br
.ti -1c
.RI "struct \fBvnova::utility::BaseDecoderAVC::SPS::VUI\fP"
.br
.ti -1c
.RI "struct \fBvnova::utility::BaseDecoderAVC::Level::Limit\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBvnova\fP"
.br
.ti -1c
.RI "namespace \fBvnova::utility\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBAVCMaxSPSCount\fP   32"
.br
.ti -1c
.RI "#define \fBAVCMaxPPSCount\fP   256"
.br
.ti -1c
.RI "#define \fBAVCMaxSliceGroupIDs\fP   8"
.br
.ti -1c
.RI "#define \fBAVCMaxShortTermRefPicSets\fP   64"
.br
.ti -1c
.RI "#define \fBAVCNumMMCO\fP   7"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define AVCMaxPPSCount   256"

.PP
Definition at line \fB42\fP of file \fBuBaseDecoderAVC\&.h\fP\&.
.SS "#define AVCMaxShortTermRefPicSets   64"

.PP
Definition at line \fB44\fP of file \fBuBaseDecoderAVC\&.h\fP\&.
.SS "#define AVCMaxSliceGroupIDs   8"

.PP
Definition at line \fB43\fP of file \fBuBaseDecoderAVC\&.h\fP\&.
.SS "#define AVCMaxSPSCount   32"

.PP
Definition at line \fB41\fP of file \fBuBaseDecoderAVC\&.h\fP\&.
.SS "#define AVCNumMMCO   7"

.PP
Definition at line \fB45\fP of file \fBuBaseDecoderAVC\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
