.TH "src/uESFile.h" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/uESFile.h
.SH SYNOPSIS
.br
.PP
\fC#include 'Config\&.hpp'\fP
.br
\fC#include 'uPlatform\&.h'\fP
.br
\fC#include 'uBaseDecoder\&.h'\fP
.br
\fC#include <algorithm>\fP
.br
\fC#include <cstdio>\fP
.br
\fC#include <map>\fP
.br
\fC#include <memory>\fP
.br
\fC#include <string>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBvnova::utility::ESFile\fP"
.br
.ti -1c
.RI "struct \fBvnova::utility::ESFile::NalUnit\fP"
.br
.ti -1c
.RI "struct \fBvnova::utility::ESFile::AccessUnit\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBvnova\fP"
.br
.ti -1c
.RI "namespace \fBvnova::utility\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBBITSTREAM_BUFFER_SIZE\fP   (1024 * 1024)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define BITSTREAM_BUFFER_SIZE   (1024 * 1024)"

.PP
Definition at line \fB45\fP of file \fBuESFile\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
