.TH "deps/base_vvc/minimum_VTM/source/Lib/CommonLib/UnitPartitioner.h" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deps/base_vvc/minimum_VTM/source/Lib/CommonLib/UnitPartitioner.h \- Provides a class for partitioning management\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'Unit\&.h'\fP
.br
\fC#include 'CommonDef\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBvtm::PartLevel\fP"
.br
.ti -1c
.RI "class \fBvtm::Partitioner\fP"
.br
.ti -1c
.RI "class \fBvtm::AdaptiveDepthPartitioner\fP"
.br
.ti -1c
.RI "class \fBvtm::QTBTPartitioner\fP"
.br
.ti -1c
.RI "class \fBvtm::TUIntraSubPartitioner\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBvtm\fP"
.br
.ti -1c
.RI "namespace \fBvtm::PartitionerImpl\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef std::vector< \fBUnitArea\fP > \fBvtm::Partitioning\fP"
.br
.ti -1c
.RI "typedef \fBstatic_vector\fP< \fBPartLevel\fP, 2 *MAX_CU_DEPTH+1 > \fBvtm::PartitioningStack\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBvtm::PartSplit\fP { \fBvtm::CTU_LEVEL\fP = 0, \fBvtm::CU_QUAD_SPLIT\fP, \fBvtm::CU_HORZ_SPLIT\fP, \fBvtm::CU_VERT_SPLIT\fP, \fBvtm::CU_TRIH_SPLIT\fP, \fBvtm::CU_TRIV_SPLIT\fP, \fBvtm::TU_MAX_TR_SPLIT\fP, \fBvtm::TU_NO_ISP\fP, \fBvtm::TU_1D_HORZ_SPLIT\fP, \fBvtm::TU_1D_VERT_SPLIT\fP, \fBvtm::SBT_VER_HALF_POS0_SPLIT\fP, \fBvtm::SBT_VER_HALF_POS1_SPLIT\fP, \fBvtm::SBT_HOR_HALF_POS0_SPLIT\fP, \fBvtm::SBT_HOR_HALF_POS1_SPLIT\fP, \fBvtm::SBT_VER_QUAD_POS0_SPLIT\fP, \fBvtm::SBT_VER_QUAD_POS1_SPLIT\fP, \fBvtm::SBT_HOR_QUAD_POS0_SPLIT\fP, \fBvtm::SBT_HOR_QUAD_POS1_SPLIT\fP, \fBvtm::NUM_PART_SPLIT\fP, \fBvtm::CU_MT_SPLIT\fP = 1000, \fBvtm::CU_BT_SPLIT\fP = 1001, \fBvtm::CU_DONT_SPLIT\fP = 2000 }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBPartitioning\fP \fBvtm::PartitionerImpl::getCUSubPartitions\fP (const \fBUnitArea\fP &cuArea, const \fBCodingStructure\fP &cs, const \fBPartSplit\fP splitType=\fBCU_QUAD_SPLIT\fP)"
.br
.ti -1c
.RI "\fBPartitioning\fP \fBvtm::PartitionerImpl::getMaxTuTiling\fP (const \fBUnitArea\fP &curArea, const \fBCodingStructure\fP &cs)"
.br
.ti -1c
.RI "void \fBvtm::PartitionerImpl::getTUIntraSubPartitions\fP (\fBPartitioning\fP &sub, const \fBUnitArea\fP &tuArea, const \fBCodingStructure\fP &cs, const \fBPartSplit\fP splitType)"
.br
.ti -1c
.RI "\fBPartitioning\fP \fBvtm::PartitionerImpl::getSbtTuTiling\fP (const \fBUnitArea\fP &curArea, const \fBCodingStructure\fP &cs, const \fBPartSplit\fP splitType)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Provides a class for partitioning management\&. 


.PP
Definition in file \fBUnitPartitioner\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
