.TH "deps/base_vvc/minimum_VTM/source/Lib/CommonLib/UnitTools.h" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deps/base_vvc/minimum_VTM/source/Lib/CommonLib/UnitTools.h
.SH SYNOPSIS
.br
.PP
\fC#include 'Unit\&.h'\fP
.br
\fC#include 'UnitPartitioner\&.h'\fP
.br
\fC#include 'ContextModelling\&.h'\fP
.br
\fC#include 'InterPrediction\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBvtm\fP"
.br
.ti -1c
.RI "namespace \fBvtm::CS\fP"
.br
.ti -1c
.RI "namespace \fBvtm::CU\fP"
.br
.ti -1c
.RI "namespace \fBvtm::PU\fP"
.br
.ti -1c
.RI "namespace \fBvtm::TU\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "uint64_t \fBvtm::CS::getEstBits\fP (const \fBCodingStructure\fP &cs)"
.br
.ti -1c
.RI "\fBUnitArea\fP \fBvtm::CS::getArea\fP (const \fBCodingStructure\fP &cs, const \fBUnitArea\fP &area, const \fBChannelType\fP chType)"
.br
.ti -1c
.RI "bool \fBvtm::CS::isDualITree\fP (const \fBCodingStructure\fP &cs)"
.br
.ti -1c
.RI "void \fBvtm::CS::setRefinedMotionField\fP (\fBCodingStructure\fP &cs)"
.br
.ti -1c
.RI "bool \fBvtm::CU::isIntra\fP (const \fBCodingUnit\fP &cu)"
.br
.ti -1c
.RI "bool \fBvtm::CU::isInter\fP (const \fBCodingUnit\fP &cu)"
.br
.ti -1c
.RI "bool \fBvtm::CU::isIBC\fP (const \fBCodingUnit\fP &cu)"
.br
.ti -1c
.RI "bool \fBvtm::CU::isPLT\fP (const \fBCodingUnit\fP &cu)"
.br
.ti -1c
.RI "bool \fBvtm::CU::isSameCtu\fP (const \fBCodingUnit\fP &cu, const \fBCodingUnit\fP &cu2)"
.br
.ti -1c
.RI "bool \fBvtm::CU::isSameSlice\fP (const \fBCodingUnit\fP &cu, const \fBCodingUnit\fP &cu2)"
.br
.ti -1c
.RI "bool \fBvtm::CU::isSameTile\fP (const \fBCodingUnit\fP &cu, const \fBCodingUnit\fP &cu2)"
.br
.ti -1c
.RI "bool \fBvtm::CU::isSameSliceAndTile\fP (const \fBCodingUnit\fP &cu, const \fBCodingUnit\fP &cu2)"
.br
.ti -1c
.RI "bool \fBvtm::CU::isSameSubPic\fP (const \fBCodingUnit\fP &cu, const \fBCodingUnit\fP &cu2)"
.br
.ti -1c
.RI "bool \fBvtm::CU::isLastSubCUOfCtu\fP (const \fBCodingUnit\fP &cu)"
.br
.ti -1c
.RI "uint32_t \fBvtm::CU::getCtuAddr\fP (const \fBCodingUnit\fP &cu)"
.br
.ti -1c
.RI "int \fBvtm::CU::predictQP\fP (const \fBCodingUnit\fP &cu, const int prevQP)"
.br
.ti -1c
.RI "uint32_t \fBvtm::CU::getNumPUs\fP (const \fBCodingUnit\fP &cu)"
.br
.ti -1c
.RI "void \fBvtm::CU::addPUs\fP (\fBCodingUnit\fP &cu)"
.br
.ti -1c
.RI "void \fBvtm::CU::saveMotionInHMVP\fP (const \fBCodingUnit\fP &cu, const bool isToBeDone)"
.br
.ti -1c
.RI "\fBPartSplit\fP \fBvtm::CU::getSplitAtDepth\fP (const \fBCodingUnit\fP &cu, const unsigned depth)"
.br
.ti -1c
.RI "\fBModeType\fP \fBvtm::CU::getModeTypeAtDepth\fP (const \fBCodingUnit\fP &cu, const unsigned depth)"
.br
.ti -1c
.RI "uint32_t \fBvtm::CU::getNumNonZeroCoeffNonTsCorner8x8\fP (const \fBCodingUnit\fP &cu, const bool lumaFlag=true, const bool chromaFlag=true)"
.br
.ti -1c
.RI "bool \fBvtm::CU::isPredRegDiffFromTB\fP (const \fBCodingUnit\fP &cu, const \fBComponentID\fP compID)"
.br
.ti -1c
.RI "bool \fBvtm::CU::isFirstTBInPredReg\fP (const \fBCodingUnit\fP &cu, const \fBComponentID\fP compID, const \fBCompArea\fP &area)"
.br
.ti -1c
.RI "bool \fBvtm::CU::isMinWidthPredEnabledForBlkSize\fP (const int w, const int h)"
.br
.ti -1c
.RI "void \fBvtm::CU::adjustPredArea\fP (\fBCompArea\fP &area)"
.br
.ti -1c
.RI "bool \fBvtm::CU::isBcwIdxCoded\fP (const \fBCodingUnit\fP &cu)"
.br
.ti -1c
.RI "uint8_t \fBvtm::CU::getValidBcwIdx\fP (const \fBCodingUnit\fP &cu)"
.br
.ti -1c
.RI "void \fBvtm::CU::setBcwIdx\fP (\fBCodingUnit\fP &cu, uint8_t uh)"
.br
.ti -1c
.RI "uint8_t \fBvtm::CU::deriveBcwIdx\fP (uint8_t bcwLO, uint8_t bcwL1)"
.br
.ti -1c
.RI "bool \fBvtm::CU::bdpcmAllowed\fP (const \fBCodingUnit\fP &cu, const \fBComponentID\fP compID)"
.br
.ti -1c
.RI "bool \fBvtm::CU::isMTSAllowed\fP (const \fBCodingUnit\fP &cu, const \fBComponentID\fP compID)"
.br
.ti -1c
.RI "bool \fBvtm::CU::divideTuInRows\fP (const \fBCodingUnit\fP &cu)"
.br
.ti -1c
.RI "\fBPartSplit\fP \fBvtm::CU::getISPType\fP (const \fBCodingUnit\fP &cu, const \fBComponentID\fP compID)"
.br
.ti -1c
.RI "bool \fBvtm::CU::isISPLast\fP (const \fBCodingUnit\fP &cu, const \fBCompArea\fP &tuArea, const \fBComponentID\fP compID)"
.br
.ti -1c
.RI "bool \fBvtm::CU::isISPFirst\fP (const \fBCodingUnit\fP &cu, const \fBCompArea\fP &tuArea, const \fBComponentID\fP compID)"
.br
.ti -1c
.RI "bool \fBvtm::CU::canUseISP\fP (const \fBCodingUnit\fP &cu, const \fBComponentID\fP compID)"
.br
.ti -1c
.RI "bool \fBvtm::CU::canUseISP\fP (const int width, const int height, const int maxTrSize=MAX_TB_SIZEY)"
.br
.ti -1c
.RI "bool \fBvtm::CU::canUseLfnstWithISP\fP (const \fBCompArea\fP &cuArea, const \fBISPType\fP ispSplitType)"
.br
.ti -1c
.RI "bool \fBvtm::CU::canUseLfnstWithISP\fP (const \fBCodingUnit\fP &cu, const \fBChannelType\fP chType)"
.br
.ti -1c
.RI "uint32_t \fBvtm::CU::getISPSplitDim\fP (const int width, const int height, const \fBPartSplit\fP ispType)"
.br
.ti -1c
.RI "bool \fBvtm::CU::allLumaCBFsAreZero\fP (const \fBCodingUnit\fP &cu)"
.br
.ti -1c
.RI "PUTraverser \fBvtm::CU::traversePUs\fP (\fBCodingUnit\fP &cu)"
.br
.ti -1c
.RI "TUTraverser \fBvtm::CU::traverseTUs\fP (\fBCodingUnit\fP &cu)"
.br
.ti -1c
.RI "cPUTraverser \fBvtm::CU::traversePUs\fP (const \fBCodingUnit\fP &cu)"
.br
.ti -1c
.RI "cTUTraverser \fBvtm::CU::traverseTUs\fP (const \fBCodingUnit\fP &cu)"
.br
.ti -1c
.RI "bool \fBvtm::CU::hasSubCUNonZeroMVd\fP (const \fBCodingUnit\fP &cu)"
.br
.ti -1c
.RI "bool \fBvtm::CU::hasSubCUNonZeroAffineMVd\fP (const \fBCodingUnit\fP &cu)"
.br
.ti -1c
.RI "uint8_t \fBvtm::CU::getSbtInfo\fP (uint8_t idx, uint8_t pos)"
.br
.ti -1c
.RI "uint8_t \fBvtm::CU::getSbtIdx\fP (const uint8_t sbtInfo)"
.br
.ti -1c
.RI "uint8_t \fBvtm::CU::getSbtPos\fP (const uint8_t sbtInfo)"
.br
.ti -1c
.RI "uint8_t \fBvtm::CU::getSbtMode\fP (const uint8_t sbtIdx, const uint8_t sbtPos)"
.br
.ti -1c
.RI "uint8_t \fBvtm::CU::getSbtIdxFromSbtMode\fP (const uint8_t sbtMode)"
.br
.ti -1c
.RI "uint8_t \fBvtm::CU::getSbtPosFromSbtMode\fP (const uint8_t sbtMode)"
.br
.ti -1c
.RI "uint8_t \fBvtm::CU::targetSbtAllowed\fP (uint8_t idx, uint8_t sbtAllowed)"
.br
.ti -1c
.RI "uint8_t \fBvtm::CU::numSbtModeRdo\fP (uint8_t sbtAllowed)"
.br
.ti -1c
.RI "bool \fBvtm::CU::isSbtMode\fP (const uint8_t sbtInfo)"
.br
.ti -1c
.RI "bool \fBvtm::CU::isSameSbtSize\fP (const uint8_t sbtInfo1, const uint8_t sbtInfo2)"
.br
.ti -1c
.RI "bool \fBvtm::CU::getRprScaling\fP (const \fBSPS\fP *sps, const \fBPPS\fP *curPPS, \fBPicture\fP *refPic, int &xScale, int &yScale)"
.br
.ti -1c
.RI "void \fBvtm::CU::checkConformanceILRP\fP (\fBSlice\fP *slice)"
.br
.ti -1c
.RI "int \fBvtm::PU::getLMSymbolList\fP (const \fBPredictionUnit\fP &pu, int *modeList)"
.br
.ti -1c
.RI "int \fBvtm::PU::getIntraMPMs\fP (const \fBPredictionUnit\fP &pu, unsigned *mpm, const \fBChannelType\fP &channelType=\fBCHANNEL_TYPE_LUMA\fP)"
.br
.ti -1c
.RI "bool \fBvtm::PU::isMIP\fP (const \fBPredictionUnit\fP &pu, const \fBChannelType\fP &chType=\fBCHANNEL_TYPE_LUMA\fP)"
.br
.ti -1c
.RI "bool \fBvtm::PU::isDMChromaMIP\fP (const \fBPredictionUnit\fP &pu)"
.br
.ti -1c
.RI "uint32_t \fBvtm::PU::getIntraDirLuma\fP (const \fBPredictionUnit\fP &pu)"
.br
.ti -1c
.RI "void \fBvtm::PU::getIntraChromaCandModes\fP (const \fBPredictionUnit\fP &pu, unsigned modeList[NUM_CHROMA_MODE])"
.br
.ti -1c
.RI "const \fBPredictionUnit\fP & \fBvtm::PU::getCoLocatedLumaPU\fP (const \fBPredictionUnit\fP &pu)"
.br
.ti -1c
.RI "uint32_t \fBvtm::PU::getFinalIntraMode\fP (const \fBPredictionUnit\fP &pu, const \fBChannelType\fP &chType)"
.br
.ti -1c
.RI "uint32_t \fBvtm::PU::getCoLocatedIntraLumaMode\fP (const \fBPredictionUnit\fP &pu)"
.br
.ti -1c
.RI "int \fBvtm::PU::getWideAngle\fP (const \fBTransformUnit\fP &tu, const uint32_t dirMode, const \fBComponentID\fP compID)"
.br
.ti -1c
.RI "void \fBvtm::PU::getInterMergeCandidates\fP (const \fBPredictionUnit\fP &pu, \fBMergeCtx\fP &mrgCtx, int mmvdList, const int &mrgCandIdx=\-1)"
.br
.ti -1c
.RI "void \fBvtm::PU::getIBCMergeCandidates\fP (const \fBPredictionUnit\fP &pu, \fBMergeCtx\fP &mrgCtx, const int &mrgCandIdx=\-1)"
.br
.ti -1c
.RI "void \fBvtm::PU::getInterMMVDMergeCandidates\fP (const \fBPredictionUnit\fP &pu, \fBMergeCtx\fP &mrgCtx, const int &mrgCandIdx=\-1)"
.br
.ti -1c
.RI "int \fBvtm::PU::getDistScaleFactor\fP (const int &currPOC, const int &currRefPOC, const int &colPOC, const int &colRefPOC)"
.br
.ti -1c
.RI "bool \fBvtm::PU::isDiffMER\fP (const \fBPosition\fP &pos1, const \fBPosition\fP &pos2, const unsigned plevel)"
.br
.ti -1c
.RI "bool \fBvtm::PU::getColocatedMVP\fP (const \fBPredictionUnit\fP &pu, const \fBRefPicList\fP &eRefPicList, const \fBPosition\fP &pos, \fBMv\fP &rcMv, const int &refIdx, bool sbFlag)"
.br
.ti -1c
.RI "void \fBvtm::PU::fillMvpCand\fP (\fBPredictionUnit\fP &pu, const \fBRefPicList\fP &eRefPicList, const int &refIdx, \fBAMVPInfo\fP &amvpInfo)"
.br
.ti -1c
.RI "void \fBvtm::PU::fillIBCMvpCand\fP (\fBPredictionUnit\fP &pu, \fBAMVPInfo\fP &amvpInfo)"
.br
.ti -1c
.RI "void \fBvtm::PU::fillAffineMvpCand\fP (\fBPredictionUnit\fP &pu, const \fBRefPicList\fP &eRefPicList, const int &refIdx, \fBAffineAMVPInfo\fP &affiAMVPInfo)"
.br
.ti -1c
.RI "bool \fBvtm::PU::addMVPCandUnscaled\fP (const \fBPredictionUnit\fP &pu, const \fBRefPicList\fP &eRefPicList, const int &iRefIdx, const \fBPosition\fP &pos, const \fBMvpDir\fP &eDir, \fBAMVPInfo\fP &amvpInfo)"
.br
.ti -1c
.RI "void \fBvtm::PU::xInheritedAffineMv\fP (const \fBPredictionUnit\fP &pu, const \fBPredictionUnit\fP *puNeighbour, \fBRefPicList\fP eRefPicList, \fBMv\fP rcMv[3])"
.br
.ti -1c
.RI "bool \fBvtm::PU::addMergeHMVPCand\fP (const \fBCodingStructure\fP &cs, \fBMergeCtx\fP &mrgCtx, const int &mrgCandIdx, const uint32_t maxNumMergeCandMin1, int &cnt, const bool isAvailableA1, const \fBMotionInfo\fP miLeft, const bool isAvailableB1, const \fBMotionInfo\fP miAbove, const bool ibcFlag, const bool isGt4x4)"
.br
.ti -1c
.RI "void \fBvtm::PU::addAMVPHMVPCand\fP (const \fBPredictionUnit\fP &pu, const \fBRefPicList\fP eRefPicList, const int currRefPOC, \fBAMVPInfo\fP &info)"
.br
.ti -1c
.RI "bool \fBvtm::PU::addAffineMVPCandUnscaled\fP (const \fBPredictionUnit\fP &pu, const \fBRefPicList\fP &refPicList, const int &refIdx, const \fBPosition\fP &pos, const \fBMvpDir\fP &dir, \fBAffineAMVPInfo\fP &affiAmvpInfo)"
.br
.ti -1c
.RI "bool \fBvtm::PU::isBipredRestriction\fP (const \fBPredictionUnit\fP &pu)"
.br
.ti -1c
.RI "void \fBvtm::PU::spanMotionInfo\fP (\fBPredictionUnit\fP &pu, const \fBMergeCtx\fP &mrgCtx=\fBMergeCtx\fP())"
.br
.ti -1c
.RI "void \fBvtm::PU::applyImv\fP (\fBPredictionUnit\fP &pu, \fBMergeCtx\fP &mrgCtx, \fBInterPrediction\fP *interPred=\fBNULL\fP)"
.br
.ti -1c
.RI "void \fBvtm::PU::getAffineControlPointCand\fP (const \fBPredictionUnit\fP &pu, \fBMotionInfo\fP mi[4], bool isAvailable[4], int verIdx[4], int8_t bcwIdx, int modelIdx, int verNum, \fBAffineMergeCtx\fP &affMrgCtx)"
.br
.ti -1c
.RI "void \fBvtm::PU::getAffineMergeCand\fP (const \fBPredictionUnit\fP &pu, \fBAffineMergeCtx\fP &affMrgCtx, const int mrgCandIdx=\-1)"
.br
.ti -1c
.RI "void \fBvtm::PU::setAllAffineMvField\fP (\fBPredictionUnit\fP &pu, \fBMvField\fP *mvField, \fBRefPicList\fP eRefList)"
.br
.ti -1c
.RI "void \fBvtm::PU::setAllAffineMv\fP (\fBPredictionUnit\fP &pu, \fBMv\fP affLT, \fBMv\fP affRT, \fBMv\fP affLB, \fBRefPicList\fP eRefList, bool clipCPMVs=false)"
.br
.ti -1c
.RI "bool \fBvtm::PU::getInterMergeSubPuMvpCand\fP (const \fBPredictionUnit\fP &pu, \fBMergeCtx\fP &mrgCtx, bool &LICFlag, const int count, int mmvdList)"
.br
.ti -1c
.RI "bool \fBvtm::PU::getInterMergeSubPuRecurCand\fP (const \fBPredictionUnit\fP &pu, \fBMergeCtx\fP &mrgCtx, const int count)"
.br
.ti -1c
.RI "bool \fBvtm::PU::isBiPredFromDifferentDirEqDistPoc\fP (const \fBPredictionUnit\fP &pu)"
.br
.ti -1c
.RI "void \fBvtm::PU::restrictBiPredMergeCandsOne\fP (\fBPredictionUnit\fP &pu)"
.br
.ti -1c
.RI "bool \fBvtm::PU::isLMCMode\fP (unsigned mode)"
.br
.ti -1c
.RI "bool \fBvtm::PU::isLMCModeEnabled\fP (const \fBPredictionUnit\fP &pu, unsigned mode)"
.br
.ti -1c
.RI "bool \fBvtm::PU::isChromaIntraModeCrossCheckMode\fP (const \fBPredictionUnit\fP &pu)"
.br
.ti -1c
.RI "void \fBvtm::PU::getGeoMergeCandidates\fP (const \fBPredictionUnit\fP &pu, \fBMergeCtx\fP &GeoMrgCtx)"
.br
.ti -1c
.RI "void \fBvtm::PU::spanGeoMotionInfo\fP (\fBPredictionUnit\fP &pu, \fBMergeCtx\fP &GeoMrgCtx, const uint8_t splitDir, const uint8_t candIdx0, const uint8_t candIdx1)"
.br
.ti -1c
.RI "bool \fBvtm::PU::isAddNeighborMv\fP (const \fBMv\fP &currMv, \fBMv\fP *neighborMvs, int numNeighborMv)"
.br
.ti -1c
.RI "void \fBvtm::PU::getIbcMVPsEncOnly\fP (\fBPredictionUnit\fP &pu, \fBMv\fP *mvPred, int &nbPred)"
.br
.ti -1c
.RI "bool \fBvtm::PU::getDerivedBV\fP (\fBPredictionUnit\fP &pu, const \fBMv\fP &currentMv, \fBMv\fP &derivedMv)"
.br
.ti -1c
.RI "bool \fBvtm::PU::checkDMVRCondition\fP (const \fBPredictionUnit\fP &pu)"
.br
.ti -1c
.RI "uint32_t \fBvtm::TU::getNumNonZeroCoeffsNonTSCorner8x8\fP (const \fBTransformUnit\fP &tu, const bool bLuma=true, const bool bChroma=true)"
.br
.ti -1c
.RI "bool \fBvtm::TU::isNonTransformedResidualRotated\fP (const \fBTransformUnit\fP &tu, const \fBComponentID\fP &compID)"
.br
.ti -1c
.RI "bool \fBvtm::TU::getCbf\fP (const \fBTransformUnit\fP &tu, const \fBComponentID\fP &compID)"
.br
.ti -1c
.RI "bool \fBvtm::TU::getCbfAtDepth\fP (const \fBTransformUnit\fP &tu, const \fBComponentID\fP &compID, const unsigned &depth)"
.br
.ti -1c
.RI "void \fBvtm::TU::setCbfAtDepth\fP (\fBTransformUnit\fP &tu, const \fBComponentID\fP &compID, const unsigned &depth, const bool &cbf)"
.br
.ti -1c
.RI "bool \fBvtm::TU::isTSAllowed\fP (const \fBTransformUnit\fP &tu, const \fBComponentID\fP compID)"
.br
.ti -1c
.RI "bool \fBvtm::TU::needsSqrt2Scale\fP (const \fBTransformUnit\fP &tu, const \fBComponentID\fP &compID)"
.br
.ti -1c
.RI "bool \fBvtm::TU::needsBlockSizeTrafoScale\fP (const \fBTransformUnit\fP &tu, const \fBComponentID\fP &compID)"
.br
.ti -1c
.RI "\fBTransformUnit\fP * \fBvtm::TU::getPrevTU\fP (const \fBTransformUnit\fP &tu, const \fBComponentID\fP compID)"
.br
.ti -1c
.RI "bool \fBvtm::TU::getPrevTuCbfAtDepth\fP (const \fBTransformUnit\fP &tu, const \fBComponentID\fP compID, const int trDepth)"
.br
.ti -1c
.RI "int \fBvtm::TU::getICTMode\fP (const \fBTransformUnit\fP &tu, int jointCbCr=\-1)"
.br
.ti -1c
.RI "uint32_t \fBvtm::getCtuAddr\fP (const \fBPosition\fP &pos, const \fBPreCalcValues\fP &pcv)"
.br
.ti -1c
.RI "int \fBvtm::getNumModesMip\fP (const \fBSize\fP &block)"
.br
.ti -1c
.RI "int \fBvtm::getMipSizeId\fP (const \fBSize\fP &block)"
.br
.ti -1c
.RI "bool \fBvtm::allowLfnstWithMip\fP (const \fBSize\fP &block)"
.br
.ti -1c
.RI "template<typename T , size_t N> uint32_t \fBvtm::updateCandList\fP (T uiMode, double uiCost, \fBstatic_vector\fP< T, N > &candModeList, \fBstatic_vector\fP< double, N > &candCostList, size_t uiFastCandNum=N, int *iserttPos=nullptr)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
