.TH "deps/base_vvc/minimum_VTM/source/Lib/CommonLib/Unit.h" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deps/base_vvc/minimum_VTM/source/Lib/CommonLib/Unit.h \- defines unit as a set of blocks and basic unit types (coding, prediction, transform)  

.SH SYNOPSIS
.br
.PP
\fC#include 'CommonDef\&.h'\fP
.br
\fC#include 'Common\&.h'\fP
.br
\fC#include 'Mv\&.h'\fP
.br
\fC#include 'MotionInfo\&.h'\fP
.br
\fC#include 'ChromaFormat\&.h'\fP
.br
\fC#include 'Buffer\&.h'\fP
.br
\fC#include <iterator>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBvtm::PLTBuf\fP"
.br
.ti -1c
.RI "struct \fBvtm::CompArea\fP"
.br
.ti -1c
.RI "struct \fBvtm::UnitArea\fP"
.br
.ti -1c
.RI "struct \fBvtm::UnitAreaRelative\fP"
.br
.ti -1c
.RI "struct \fBvtm::CodingUnit\fP"
.br
.ti -1c
.RI "struct \fBvtm::IntraPredictionData\fP"
.br
.ti -1c
.RI "struct \fBvtm::InterPredictionData\fP"
.br
.ti -1c
.RI "struct \fBvtm::PredictionUnit\fP"
.br
.ti -1c
.RI "struct \fBvtm::TransformUnit\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBvtm\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBstatic_vector\fP< \fBCompArea\fP, \fBMAX_NUM_TBLOCKS\fP > \fBvtm::UnitBlocksType\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBPosition\fP \fBvtm::recalcPosition\fP (const \fBChromaFormat\fP _cf, const \fBComponentID\fP srcCId, const \fBComponentID\fP dstCId, const \fBPosition\fP &pos)"
.br
.ti -1c
.RI "\fBPosition\fP \fBvtm::recalcPosition\fP (const \fBChromaFormat\fP _cf, const \fBChannelType\fP srcCHt, const \fBChannelType\fP dstCHt, const \fBPosition\fP &pos)"
.br
.ti -1c
.RI "\fBSize\fP \fBvtm::recalcSize\fP (const \fBChromaFormat\fP _cf, const \fBComponentID\fP srcCId, const \fBComponentID\fP dstCId, const \fBSize\fP &size)"
.br
.ti -1c
.RI "\fBSize\fP \fBvtm::recalcSize\fP (const \fBChromaFormat\fP _cf, const \fBChannelType\fP srcCHt, const \fBChannelType\fP dstCHt, const \fBSize\fP &size)"
.br
.ti -1c
.RI "\fBCompArea\fP \fBvtm::clipArea\fP (const \fBCompArea\fP &compArea, const \fBArea\fP &boundingBox)"
.br
.ti -1c
.RI "\fBUnitArea\fP \fBvtm::clipArea\fP (const \fBUnitArea\fP &area, const \fBUnitArea\fP &boundingBox)"
.br
.in -1c
.SH "Detailed Description"
.PP 
defines unit as a set of blocks and basic unit types (coding, prediction, transform) 


.PP
Definition in file \fBUnit\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
