.TH "deps/base_vvc/minimum_VTM/source/Lib/CommonLib/Unit.cpp" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deps/base_vvc/minimum_VTM/source/Lib/CommonLib/Unit.cpp \- defines unit as a set of blocks and basic unit types (coding, prediction, transform)  

.SH SYNOPSIS
.br
.PP
\fC#include 'Unit\&.h'\fP
.br
\fC#include 'Buffer\&.h'\fP
.br
\fC#include 'Picture\&.h'\fP
.br
\fC#include 'ChromaFormat\&.h'\fP
.br
\fC#include 'UnitTools\&.h'\fP
.br
\fC#include 'UnitPartitioner\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBvtm\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
defines unit as a set of blocks and basic unit types (coding, prediction, transform) 


.PP
Definition in file \fBUnit\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
