.TH "deps/base_vvc/minimum_VTM/source/Lib/CommonLib/UnitTools.cpp" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deps/base_vvc/minimum_VTM/source/Lib/CommonLib/UnitTools.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'UnitTools\&.h'\fP
.br
\fC#include 'dtrace_next\&.h'\fP
.br
\fC#include 'Unit\&.h'\fP
.br
\fC#include 'Slice\&.h'\fP
.br
\fC#include 'Picture\&.h'\fP
.br
\fC#include <utility>\fP
.br
\fC#include <algorithm>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBvtm\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBvtm::convertMvFixedToFloat\fP (int32_t val)"
.br
.ti -1c
.RI "int \fBvtm::convertMvFloatToFixed\fP (int val)"
.br
.ti -1c
.RI "int \fBvtm::roundMvComp\fP (int x)"
.br
.ti -1c
.RI "const int \fBvtm::getAvailableAffineNeighboursForLeftPredictor\fP (const \fBPredictionUnit\fP &pu, const \fBPredictionUnit\fP *npu[])"
.br
.ti -1c
.RI "const int \fBvtm::getAvailableAffineNeighboursForAbovePredictor\fP (const \fBPredictionUnit\fP &pu, const \fBPredictionUnit\fP *npu[], int numAffNeighLeft)"
.br
.ti -1c
.RI "void \fBvtm::clipColPos\fP (int &posX, int &posY, const \fBPredictionUnit\fP &pu)"
.br
.ti -1c
.RI "uint32_t \fBvtm::getCtuAddr\fP (const \fBPosition\fP &pos, const \fBPreCalcValues\fP &pcv)"
.br
.ti -1c
.RI "int \fBvtm::getNumModesMip\fP (const \fBSize\fP &block)"
.br
.ti -1c
.RI "int \fBvtm::getMipSizeId\fP (const \fBSize\fP &block)"
.br
.ti -1c
.RI "bool \fBvtm::allowLfnstWithMip\fP (const \fBSize\fP &block)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
