.TH "src/uPlatform.h" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/uPlatform.h
.SH SYNOPSIS
.br
.PP
\fC#include <assert\&.h>\fP
.br
\fC#include <cstring>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <string>\fP
.br
\fC#include <stdexcept>\fP
.br
\fC#include 'uTypes\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBvnova\fP"
.br
.ti -1c
.RI "namespace \fBvnova::utility\fP"
.br
.ti -1c
.RI "namespace \fBvnova::utility::os\fP"
.br
.ti -1c
.RI "namespace \fBvnova::utility::lib\fP"
.br
.ti -1c
.RI "namespace \fBvnova::utility::file\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBVNAlign\fP(x)   __attribute__((aligned(x)))"
.br
.ti -1c
.RI "#define \fBVNEmptyFile\fP()"
.br
.ti -1c
.RI "#define \fBVNThreadLocal\fP   __thread"
.br
.ti -1c
.RI "#define \fBVNUnused\fP(x)   (void)(x)"
.br
.ti -1c
.RI "#define \fBVNStringify\fP(a)   \fBVNStringifyHelper\fP(a)"
.br
.ti -1c
.RI "#define \fBVNStringifyHelper\fP(s)   #s"
.br
.ti -1c
.RI "#define \fBVNConcatHelper\fP(a,  b)   a ## b"
.br
.ti -1c
.RI "#define \fBVNConcat\fP(a,  b)   \fBVNConcatHelper\fP(a, b)"
.br
.ti -1c
.RI "#define \fBVNAssert\fP(condition)   assert((condition))"
.br
.ti -1c
.RI "#define \fBVNAssertf\fP(condition,  format, \&.\&.\&.)   assert((condition))"
.br
.ti -1c
.RI "#define \fBVNFail\fP(format, \&.\&.\&.)   assert(false)"
.br
.ti -1c
.RI "#define \fBVNStaticAssert\fP(condition)   ;enum { \fBVNConcat\fP(static_assert_line_, __LINE__) = 1/(int)(!!(condition)) }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::string \fBvnova::utility::os::GetAppPath\fP ()"
.br
.ti -1c
.RI "std::string \fBvnova::utility::os::GetCwd\fP ()"
.br
.ti -1c
.RI "void * \fBvnova::utility::lib::Open\fP (const std::string &name, const std::string &version='', std::string *returnmsg=\fBNULL\fP)"
.br
.ti -1c
.RI "bool \fBvnova::utility::lib::Close\fP (void *handle)"
.br
.ti -1c
.RI "void * \fBvnova::utility::lib::GetSymbol\fP (void *handle, const std::string &name)"
.br
.ti -1c
.RI "std::string \fBvnova::utility::lib::GetError\fP ()"
.br
.ti -1c
.RI "uint64_t \fBvnova::utility::file::Tell\fP (FILE *f)"
.br
.ti -1c
.RI "void \fBvnova::utility::file::Seek\fP (FILE *f, long long offset, int32_t origin)"
.br
.ti -1c
.RI "uint64_t \fBvnova::utility::file::Size\fP (FILE *f)"
.br
.ti -1c
.RI "FILE * \fBvnova::utility::file::OpenFileSearched\fP (const std::string &filename, const char *mode)"
.br
.ti -1c
.RI "bool \fBvnova::utility::file::ReadContentsText\fP (const std::string &filename, std::string &output)"
.br
.ti -1c
.RI "bool \fBvnova::utility::file::ReadContentsBinary\fP (const std::string &filename, \fBDataBuffer\fP &output)"
.br
.ti -1c
.RI "bool \fBvnova::utility::file::Exists\fP (const char *path)"
.br
.ti -1c
.RI "bool \fBvnova::utility::file::Exists\fP (const std::string &path)"
.br
.ti -1c
.RI "uint64_t \fBvnova::utility::file::GetModifiedTime\fP (const char *path)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define VNAlign(x)   __attribute__((aligned(x)))"

.PP
Definition at line \fB47\fP of file \fBuPlatform\&.h\fP\&.
.SS "#define VNAssert(condition)   assert((condition))"

.PP
Definition at line \fB63\fP of file \fBuPlatform\&.h\fP\&.
.SS "#define VNAssertf(condition, format,  \&.\&.\&.)   assert((condition))"

.PP
Definition at line \fB64\fP of file \fBuPlatform\&.h\fP\&.
.SS "#define VNConcat(a, b)   \fBVNConcatHelper\fP(a, b)"

.PP
Definition at line \fB60\fP of file \fBuPlatform\&.h\fP\&.
.SS "#define VNConcatHelper(a, b)   a ## b"

.PP
Definition at line \fB59\fP of file \fBuPlatform\&.h\fP\&.
.SS "#define VNEmptyFile()"

.PP
Definition at line \fB48\fP of file \fBuPlatform\&.h\fP\&.
.SS "#define VNFail(format,  \&.\&.\&.)   assert(false)"

.PP
Definition at line \fB65\fP of file \fBuPlatform\&.h\fP\&.
.SS "#define VNStaticAssert(condition)   ;enum { \fBVNConcat\fP(static_assert_line_, __LINE__) = 1/(int)(!!(condition)) }"

.PP
Definition at line \fB77\fP of file \fBuPlatform\&.h\fP\&.
.SS "#define VNStringify(a)   \fBVNStringifyHelper\fP(a)"

.PP
Definition at line \fB55\fP of file \fBuPlatform\&.h\fP\&.
.SS "#define VNStringifyHelper(s)   #s"

.PP
Definition at line \fB56\fP of file \fBuPlatform\&.h\fP\&.
.SS "#define VNThreadLocal   __thread"

.PP
Definition at line \fB49\fP of file \fBuPlatform\&.h\fP\&.
.SS "#define VNUnused(x)   (void)(x)"

.PP
Definition at line \fB52\fP of file \fBuPlatform\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
