.TH "decoder/include/UpsamplingDPI.hpp" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
decoder/include/UpsamplingDPI.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'Component\&.hpp'\fP
.br
\fC#include 'SignaledConfiguration\&.hpp'\fP
.br
\fC#include 'Surface\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBlctm::UpsamplingDPI\fP"
.br
.ti -1c
.RI "class \fBlctm::UpsamplingDPI_1D\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBlctm\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
