.TH "decoder/src/Upsampling.cpp" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
decoder/src/Upsampling.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'Upsampling\&.hpp'\fP
.br
\fC#include 'Convert\&.hpp'\fP
.br
\fC#include 'Misc\&.hpp'\fP
.br
\fC#include <algorithm>\fP
.br
\fC#include <vector>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBlctm\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef int32_t \fBlctm::UpsampleKernel\fP[4]"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBImage\fP \fBlctm::UpsampleImage\fP (const \fBImage\fP &src, \fBUpsample\fP upsample, const unsigned upsampling_coefficients[4], \fBScalingMode\fP scaling_mode)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
