.TH "src/uString.h" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/uString.h
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBvnova\fP"
.br
.ti -1c
.RI "namespace \fBvnova::utility\fP"
.br
.ti -1c
.RI "namespace \fBvnova::utility::string\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBvnova::utility::string::IEquals\fP (const std::string &a, const std::string &b)"
.br
.ti -1c
.RI "const std::string & \fBvnova::utility::string::ToLower\fP (std::string &str)"
.br
.ti -1c
.RI "std::string \fBvnova::utility::string::ToLowerCopy\fP (const std::string &str)"
.br
.ti -1c
.RI "const std::string & \fBvnova::utility::string::ToUpper\fP (std::string &str)"
.br
.ti -1c
.RI "std::string \fBvnova::utility::string::ToUpperCopy\fP (const std::string &str)"
.br
.ti -1c
.RI "std::string \fBvnova::utility::string::PathDirectory\fP (const std::string &path)"
.br
.ti -1c
.RI "std::string \fBvnova::utility::string::PathFile\fP (const std::string &path)"
.br
.ti -1c
.RI "std::string \fBvnova::utility::string::PathExtension\fP (const std::string &path)"
.br
.ti -1c
.RI "const std::string & \fBvnova::utility::string::PathNormalise\fP (std::string &path, bool bDirectory)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
