.TH "deps/base_evc/src/util.h" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deps/base_evc/src/util.h
.SH SYNOPSIS
.br
.PP
\fC#include <stdlib\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <time\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB_CRT_SECURE_NO_WARNINGS\fP"
.br
.ti -1c
.RI "#define \fBAPP_PEL_16BIT\fP"
.br
.ti -1c
.RI "#define \fBCONV8_16BIT\fP"
.br
.ti -1c
.RI "#define \fBRECON_POC_ORDER\fP   1"
.br
.ti -1c
.RI "#define \fBUSE_CPU_TIME_CLOCK\fP   1"
.br
.ti -1c
.RI "#define \fBprint\fP(args\&.\&.\&.)   printf(args)"
.br
.ti -1c
.RI "#define \fBVERBOSE_0\fP   0"
.br
.ti -1c
.RI "#define \fBVERBOSE_1\fP   1"
.br
.ti -1c
.RI "#define \fBVERBOSE_2\fP   2"
.br
.ti -1c
.RI "#define \fBv0print\fP(args\&.\&.\&.)   {if(op_verbose >= \fBVERBOSE_0\fP) {\fBprint\fP(args);}}"
.br
.ti -1c
.RI "#define \fBv1print\fP(args\&.\&.\&.)   {if(op_verbose >= \fBVERBOSE_1\fP) {\fBprint\fP(args);}}"
.br
.ti -1c
.RI "#define \fBv2print\fP(args\&.\&.\&.)   {if(op_verbose >= \fBVERBOSE_2\fP) {\fBprint\fP(args);}}"
.br
.ti -1c
.RI "#define \fBevc_clk_diff\fP(t1,  t2)       (((t2) >= (t1)) ? ((t2) \- (t1)) : ((EVC_CLK_MAX \- (t1)) + (t2)))"
.br
.ti -1c
.RI "#define \fBevc_clk_msec\fP(clk)       ((int)((clk + (EVC_CLK_PER_MSEC/2))/EVC_CLK_PER_MSEC))"
.br
.ti -1c
.RI "#define \fBevc_clk_sec\fP(clk)       ((int)((clk + (EVC_CLK_PER_SEC/2))/EVC_CLK_PER_SEC))"
.br
.ti -1c
.RI "#define \fBIFVCA_CLIP\fP(n,  min,  max)   (((n)>(max))? (max) : (((n)<(min))? (min) : (n)))"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "EVC_IMGB * \fBimgb_alloc\fP (int w, int h, int cs)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define _CRT_SECURE_NO_WARNINGS"

.PP
Definition at line \fB37\fP of file \fButil\&.h\fP\&.
.SS "#define APP_PEL_16BIT"

.PP
Definition at line \fB47\fP of file \fButil\&.h\fP\&.
.SS "#define CONV8_16BIT"

.PP
Definition at line \fB49\fP of file \fButil\&.h\fP\&.
.SS "#define evc_clk_diff(t1, t2)       (((t2) >= (t1)) ? ((t2) \- (t1)) : ((EVC_CLK_MAX \- (t1)) + (t2)))"

.PP
Definition at line \fB124\fP of file \fButil\&.h\fP\&.
.SS "#define evc_clk_msec(clk)       ((int)((clk + (EVC_CLK_PER_MSEC/2))/EVC_CLK_PER_MSEC))"

.PP
Definition at line \fB141\fP of file \fButil\&.h\fP\&.
.SS "#define evc_clk_sec(clk)       ((int)((clk + (EVC_CLK_PER_SEC/2))/EVC_CLK_PER_SEC))"

.PP
Definition at line \fB143\fP of file \fButil\&.h\fP\&.
.SS "#define IFVCA_CLIP(n, min, max)   (((n)>(max))? (max) : (((n)<(min))? (min) : (n)))"

.PP
Definition at line \fB146\fP of file \fButil\&.h\fP\&.
.SS "#define print(args\&.\&.\&.)   printf(args)"

.PP
Definition at line \fB68\fP of file \fButil\&.h\fP\&.
.SS "#define RECON_POC_ORDER   1"

.PP
Definition at line \fB55\fP of file \fButil\&.h\fP\&.
.SS "#define USE_CPU_TIME_CLOCK   1"

.PP
Definition at line \fB58\fP of file \fButil\&.h\fP\&.
.SS "#define v0print(args\&.\&.\&.)   {if(op_verbose >= \fBVERBOSE_0\fP) {\fBprint\fP(args);}}"

.PP
Definition at line \fB82\fP of file \fButil\&.h\fP\&.
.SS "#define v1print(args\&.\&.\&.)   {if(op_verbose >= \fBVERBOSE_1\fP) {\fBprint\fP(args);}}"

.PP
Definition at line \fB83\fP of file \fButil\&.h\fP\&.
.SS "#define v2print(args\&.\&.\&.)   {if(op_verbose >= \fBVERBOSE_2\fP) {\fBprint\fP(args);}}"

.PP
Definition at line \fB84\fP of file \fButil\&.h\fP\&.
.SS "#define VERBOSE_0   0"

.PP
Definition at line \fB71\fP of file \fButil\&.h\fP\&.
.SS "#define VERBOSE_1   1"

.PP
Definition at line \fB72\fP of file \fButil\&.h\fP\&.
.SS "#define VERBOSE_2   2"

.PP
Definition at line \fB73\fP of file \fButil\&.h\fP\&.
.SH "Function Documentation"
.PP 
.SS "EVC_IMGB * imgb_alloc (int w, int h, int cs)"

.PP
Definition at line \fB387\fP of file \fButil\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
