.TH "src/uTypes.h" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/uTypes.h
.SH SYNOPSIS
.br
.PP
\fC#include <stdint\&.h>\fP
.br
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <inttypes\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBvnova::utility::Callback< T >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBvnova\fP"
.br
.ti -1c
.RI "namespace \fBvnova::utility\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB__STDC_LIMIT_MACROS\fP"
.br
.ti -1c
.RI "#define \fB__STDC_FORMAT_MACROS\fP"
.br
.ti -1c
.RI "#define \fBPRId32\fP   'd'"
.br
.ti -1c
.RI "#define \fBPRIu32\fP   'u'"
.br
.ti -1c
.RI "#define \fBPRId64\fP   'ld'"
.br
.ti -1c
.RI "#define \fBPRIx64\fP   'llx'"
.br
.ti -1c
.RI "#define \fBPRIu64\fP   'lu'"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef std::vector< uint8_t > \fBvnova::utility::DataBuffer\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define __STDC_FORMAT_MACROS"

.PP
Definition at line \fB67\fP of file \fBuTypes\&.h\fP\&.
.SS "#define __STDC_LIMIT_MACROS"

.PP
Definition at line \fB35\fP of file \fBuTypes\&.h\fP\&.
.SS "#define PRId32   'd'"

.PP
Definition at line \fB70\fP of file \fBuTypes\&.h\fP\&.
.SS "#define PRId64   'ld'"

.PP
Definition at line \fB78\fP of file \fBuTypes\&.h\fP\&.
.SS "#define PRIu32   'u'"

.PP
Definition at line \fB74\fP of file \fBuTypes\&.h\fP\&.
.SS "#define PRIu64   'lu'"

.PP
Definition at line \fB86\fP of file \fBuTypes\&.h\fP\&.
.SS "#define PRIx64   'llx'"

.PP
Definition at line \fB82\fP of file \fBuTypes\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
