.TH "src/uTypeTraits.h" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/uTypeTraits.h
.SH SYNOPSIS
.br
.PP
\fC#include 'uPlatform\&.h'\fP
.br
\fC#include 'uTypes\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBvnova::utility::IntegralConstant< T, v >\fP"
.br
.ti -1c
.RI "struct \fBvnova::utility::IsIntegral< T >\fP"
.br
.ti -1c
.RI "struct \fBvnova::utility::IsIntegral< const T >\fP"
.br
.ti -1c
.RI "struct \fBvnova::utility::IsIntegral< volatile T >\fP"
.br
.ti -1c
.RI "struct \fBvnova::utility::IsIntegral< volatile const T >\fP"
.br
.ti -1c
.RI "struct \fBvnova::utility::IsIntegral< uint8_t >\fP"
.br
.ti -1c
.RI "struct \fBvnova::utility::IsIntegral< uint16_t >\fP"
.br
.ti -1c
.RI "struct \fBvnova::utility::IsIntegral< uint32_t >\fP"
.br
.ti -1c
.RI "struct \fBvnova::utility::IsIntegral< uint64_t >\fP"
.br
.ti -1c
.RI "struct \fBvnova::utility::IsIntegral< int8_t >\fP"
.br
.ti -1c
.RI "struct \fBvnova::utility::IsIntegral< int16_t >\fP"
.br
.ti -1c
.RI "struct \fBvnova::utility::IsIntegral< int32_t >\fP"
.br
.ti -1c
.RI "struct \fBvnova::utility::IsIntegral< int64_t >\fP"
.br
.ti -1c
.RI "struct \fBvnova::utility::IsIntegral< bool >\fP"
.br
.ti -1c
.RI "struct \fBvnova::utility::IsFloat< T >\fP"
.br
.ti -1c
.RI "struct \fBvnova::utility::IsFloat< const T >\fP"
.br
.ti -1c
.RI "struct \fBvnova::utility::IsFloat< volatile T >\fP"
.br
.ti -1c
.RI "struct \fBvnova::utility::IsFloat< volatile const T >\fP"
.br
.ti -1c
.RI "struct \fBvnova::utility::IsFloat< float >\fP"
.br
.ti -1c
.RI "struct \fBvnova::utility::IsFloat< double >\fP"
.br
.ti -1c
.RI "struct \fBvnova::utility::IsSigned< T >\fP"
.br
.ti -1c
.RI "struct \fBvnova::utility::IsSigned< const T >\fP"
.br
.ti -1c
.RI "struct \fBvnova::utility::IsSigned< volatile T >\fP"
.br
.ti -1c
.RI "struct \fBvnova::utility::IsSigned< volatile const T >\fP"
.br
.ti -1c
.RI "struct \fBvnova::utility::IsSigned< uint8_t >\fP"
.br
.ti -1c
.RI "struct \fBvnova::utility::IsSigned< uint16_t >\fP"
.br
.ti -1c
.RI "struct \fBvnova::utility::IsSigned< uint32_t >\fP"
.br
.ti -1c
.RI "struct \fBvnova::utility::IsSigned< uint64_t >\fP"
.br
.ti -1c
.RI "struct \fBvnova::utility::IsSigned< int8_t >\fP"
.br
.ti -1c
.RI "struct \fBvnova::utility::IsSigned< int16_t >\fP"
.br
.ti -1c
.RI "struct \fBvnova::utility::IsSigned< int32_t >\fP"
.br
.ti -1c
.RI "struct \fBvnova::utility::IsSigned< int64_t >\fP"
.br
.ti -1c
.RI "struct \fBvnova::utility::IsEnum< T >\fP"
.br
.ti -1c
.RI "struct \fBvnova::utility::LowBitMask< INTEGER_TYPE, Bits >\fP"
.br
.ti -1c
.RI "struct \fBvnova::utility::MinValue< INTEGER_TYPE, Bits >\fP"
.br
.ti -1c
.RI "struct \fBvnova::utility::MaxValue< INTEGER_TYPE, Bits >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBvnova\fP"
.br
.ti -1c
.RI "namespace \fBvnova::utility\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBIntegralConstant\fP< bool, true > \fBvnova::utility::TrueType\fP"
.br
.ti -1c
.RI "typedef \fBIntegralConstant\fP< bool, false > \fBvnova::utility::FalseType\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
