.TH "src/uYUVDesc.cpp" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/uYUVDesc.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'uYUVDesc\&.h'\fP
.br
\fC#include 'uEnumMap\&.h'\fP
.br
\fC#include <assert\&.h>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBvnova\fP"
.br
.ti -1c
.RI "namespace \fBvnova::utility\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "uint8_t m_bitDepth"

.PP
Definition at line \fB51\fP of file \fBuYUVDesc\&.cpp\fP\&.
.SS "uint32_t m_horizontalDownsample"

.PP
Definition at line \fB52\fP of file \fBuYUVDesc\&.cpp\fP\&.
.SS "uint32_t m_planeCount"

.PP
Definition at line \fB48\fP of file \fBuYUVDesc\&.cpp\fP\&.
.SS "uint32_t m_sizeDiv"

.PP
Definition at line \fB50\fP of file \fBuYUVDesc\&.cpp\fP\&.
.SS "uint32_t m_sizeMult"

.PP
Definition at line \fB49\fP of file \fBuYUVDesc\&.cpp\fP\&.
.SS "uint32_t m_verticalDownsample"

.PP
Definition at line \fB53\fP of file \fBuYUVDesc\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
