.TH "deps/base_vvc/minimum_VTM/source/Lib/CommonLib/version.h" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deps/base_vvc/minimum_VTM/source/Lib/CommonLib/version.h
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBVTM_VERSION\fP   '11\&.0'"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define VTM_VERSION   '11\&.0'"

.PP
Definition at line \fB2\fP of file \fBversion\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
