.TH "VideoIOYuvMem" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VideoIOYuvMem \- YUV file I/O class\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <VideoIOYuvMem\&.h>\fP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBWriter\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBVideoIOYuvMem\fP ()"
.br
.ti -1c
.RI "virtual \fB~VideoIOYuvMem\fP ()"
.br
.ti -1c
.RI "void \fBopen\fP (\fBWriter\fP *writer, bool bWriteMode, const int fileBitDepth[MAX_NUM_CHANNEL_TYPE], const int MSBExtendedBitDepth[MAX_NUM_CHANNEL_TYPE], const int internalBitDepth[MAX_NUM_CHANNEL_TYPE])"
.br
.RI "open or create file "
.ti -1c
.RI "void \fBclose\fP ()"
.br
.RI "close file "
.ti -1c
.RI "void \fBskipFrames\fP (uint32_t numFrames, uint32_t width, uint32_t height, ChromaFormat format)"
.br
.ti -1c
.RI "bool \fBread\fP (PelUnitBuf &pic, PelUnitBuf &picOrg, const InputColourSpaceConversion ipcsc, int aiPad[2], ChromaFormat fileFormat=NUM_CHROMA_FORMAT, const bool bClipToRec709=false)"
.br
.RI "read one frame with padding parameter "
.ti -1c
.RI "bool \fBwrite\fP (uint32_t orgWidth, uint32_t orgHeight, const CPelUnitBuf &pic, const InputColourSpaceConversion ipCSC, const bool bPackedYUVOutputMode, int confLeft=0, int confRight=0, int confTop=0, int confBottom=0, ChromaFormat format=NUM_CHROMA_FORMAT, const bool bClipToRec709=false, const bool subtractConfWindowOffsets=true)"
.br
.RI "write one YUV frame with padding parameter "
.ti -1c
.RI "bool \fBwrite\fP (const CPelUnitBuf &picTop, const CPelUnitBuf &picBot, const InputColourSpaceConversion ipCSC, const bool bPackedYUVOutputMode, int confLeft=0, int confRight=0, int confTop=0, int confBottom=0, ChromaFormat format=NUM_CHROMA_FORMAT, const bool isTff=false, const bool bClipToRec709=false)"
.br
.ti -1c
.RI "bool \fBisEof\fP ()"
.br
.RI "check for end-of-file "
.ti -1c
.RI "bool \fBisFail\fP ()"
.br
.RI "check for failure "
.ti -1c
.RI "bool \fBisOpen\fP ()"
.br
.ti -1c
.RI "void \fBsetBitdepthShift\fP (int ch, int bd)"
.br
.ti -1c
.RI "int \fBgetBitdepthShift\fP (int ch)"
.br
.ti -1c
.RI "int \fBgetFileBitdepth\fP (int ch)"
.br
.ti -1c
.RI "bool \fBwriteUpscaledPicture\fP (const SPS &sps, const PPS &pps, const CPelUnitBuf &pic, const InputColourSpaceConversion ipCSC, const bool bPackedYUVOutputMode, int outputChoice=0, ChromaFormat format=NUM_CHROMA_FORMAT, const bool bClipToRec709=false)"
.br
.RI "write one upsaled YUV frame "
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "\fBstatic\fP void \fBColourSpaceConvert\fP (const CPelUnitBuf &src, PelUnitBuf &dest, const InputColourSpaceConversion conversion, bool bIsForwards)"
.br
.in -1c
.SH "Detailed Description"
.PP 
YUV file I/O class\&. 
.PP
Definition at line \fB57\fP of file \fBVideoIOYuvMem\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "VideoIOYuvMem::VideoIOYuvMem ()\fC [inline]\fP"

.PP
Definition at line \fB76\fP of file \fBVideoIOYuvMem\&.h\fP\&.
.SS "virtual VideoIOYuvMem::~VideoIOYuvMem ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Definition at line \fB77\fP of file \fBVideoIOYuvMem\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void VideoIOYuvMem::close ()"

.PP
close file 
.PP
Definition at line \fB167\fP of file \fBVideoIOYuvMem\&.cpp\fP\&.
.SS "void VideoIOYuvMem::ColourSpaceConvert (const CPelUnitBuf & src, PelUnitBuf & dest, const InputColourSpaceConversion conversion, bool bIsForwards)\fC [static]\fP"

.PP
Definition at line \fB1203\fP of file \fBVideoIOYuvMem\&.cpp\fP\&.
.SS "int VideoIOYuvMem::getBitdepthShift (int ch)\fC [inline]\fP"

.PP
Definition at line \fB110\fP of file \fBVideoIOYuvMem\&.h\fP\&.
.SS "int VideoIOYuvMem::getFileBitdepth (int ch)\fC [inline]\fP"

.PP
Definition at line \fB111\fP of file \fBVideoIOYuvMem\&.h\fP\&.
.SS "bool VideoIOYuvMem::isEof ()"

.PP
check for end-of-file 
.PP
Definition at line \fB172\fP of file \fBVideoIOYuvMem\&.cpp\fP\&.
.SS "bool VideoIOYuvMem::isFail ()"

.PP
check for failure 
.PP
Definition at line \fB177\fP of file \fBVideoIOYuvMem\&.cpp\fP\&.
.SS "bool VideoIOYuvMem::isOpen ()\fC [inline]\fP"

.PP
Definition at line \fB108\fP of file \fBVideoIOYuvMem\&.h\fP\&.
.SS "void VideoIOYuvMem::open (\fBWriter\fP * writer, bool bWriteMode, const int fileBitDepth[MAX_NUM_CHANNEL_TYPE], const int MSBExtendedBitDepth[MAX_NUM_CHANNEL_TYPE], const int internalBitDepth[MAX_NUM_CHANNEL_TYPE])"

.PP
open or create file Open file for reading/writing Y'CbCr frames\&.
.PP
Frames read/written have bitdepth fileBitDepth, and are automatically formatted as 8 or 16 bit word values (see \fBVideoIOYuvMem::write()\fP)\&.
.PP
Image data read or written is converted to/from internalBitDepth (See scalePlane(), \fBVideoIOYuvMem::read()\fP and \fBVideoIOYuvMem::write()\fP for further details)\&.
.PP
\fBParameters\fP
.RS 4
\fIpchFile\fP file name string 
.br
\fIbWriteMode\fP file open mode: true=write, false=read 
.br
\fIfileBitDepth\fP bit-depth array of input/output file data\&. 
.br
\fIMSBExtendedBitDepth\fP 
.br
\fIinternalBitDepth\fP bit-depth array to scale image data to/from when reading/writing\&. 
.RE
.PP

.PP
Definition at line \fB127\fP of file \fBVideoIOYuvMem\&.cpp\fP\&.
.SS "bool VideoIOYuvMem::read (PelUnitBuf & pic, PelUnitBuf & picOrg, const InputColourSpaceConversion ipcsc, int aiPad[2], ChromaFormat format = \fCNUM_CHROMA_FORMAT\fP, const bool bClipToRec709 = \fCfalse\fP)"

.PP
read one frame with padding parameter Read one Y'CbCr frame, performing any required input scaling to change from the bitdepth of the input file to the internal bit-depth\&.
.PP
If a bit-depth reduction is required, and internalBitdepth >= 8, then the input file is assumed to be ITU-R BT\&.601/709 compliant, and the resulting data is clipped to the appropriate legal range, as if the file had been provided at the lower-bitdepth compliant to Rec601/709\&.
.PP
\fBParameters\fP
.RS 4
\fIpPicYuvUser\fP input picture YUV buffer class pointer 
.br
\fIpPicYuvTrueOrg\fP 
.br
\fIipcsc\fP 
.br
\fIaiPad\fP source padding size, aiPad[0] = horizontal, aiPad[1] = vertical 
.br
\fIformat\fP chroma format 
.RE
.PP
\fBReturns\fP
.RS 4
true for success, false in case of error 
.RE
.PP

.PP
Definition at line \fB888\fP of file \fBVideoIOYuvMem\&.cpp\fP\&.
.SS "void VideoIOYuvMem::setBitdepthShift (int ch, int bd)\fC [inline]\fP"

.PP
Definition at line \fB109\fP of file \fBVideoIOYuvMem\&.h\fP\&.
.SS "void VideoIOYuvMem::skipFrames (uint32_t numFrames, uint32_t width, uint32_t height, ChromaFormat format)"
Skip numFrames in input\&.
.PP
This function correctly handles cases where the input file is not seekable, by consuming bytes\&. 
.PP
Definition at line \fB191\fP of file \fBVideoIOYuvMem\&.cpp\fP\&.
.SS "bool VideoIOYuvMem::write (const CPelUnitBuf & picTop, const CPelUnitBuf & picBot, const InputColourSpaceConversion ipCSC, const bool bPackedYUVOutputMode, int confLeft = \fC0\fP, int confRight = \fC0\fP, int confTop = \fC0\fP, int confBottom = \fC0\fP, ChromaFormat format = \fCNUM_CHROMA_FORMAT\fP, const bool isTff = \fCfalse\fP, const bool bClipToRec709 = \fCfalse\fP)"

.PP
Definition at line \fB1081\fP of file \fBVideoIOYuvMem\&.cpp\fP\&.
.SS "bool VideoIOYuvMem::write (uint32_t orgWidth, uint32_t orgHeight, const CPelUnitBuf & pic, const InputColourSpaceConversion ipCSC, const bool bPackedYUVOutputMode, int confLeft = \fC0\fP, int confRight = \fC0\fP, int confTop = \fC0\fP, int confBottom = \fC0\fP, ChromaFormat format = \fCNUM_CHROMA_FORMAT\fP, const bool bClipToRec709 = \fCfalse\fP, const bool subtractConfWindowOffsets = \fCtrue\fP)"

.PP
write one YUV frame with padding parameter Write one Y'CbCr frame\&. No bit-depth conversion is performed, pcPicYuv is assumed to be at TVideoIO::m_fileBitdepth depth\&.
.PP
\fBParameters\fP
.RS 4
\fIpPicYuvUser\fP input picture YUV buffer class pointer 
.br
\fIipCSC\fP 
.br
\fIconfLeft\fP conformance window left border 
.br
\fIconfRight\fP conformance window right border 
.br
\fIconfTop\fP conformance window top border 
.br
\fIconfBottom\fP conformance window bottom border 
.br
\fIformat\fP chroma format 
.RE
.PP
\fBReturns\fP
.RS 4
true for success, false in case of error 
.RE
.PP

.PP
Definition at line \fB987\fP of file \fBVideoIOYuvMem\&.cpp\fP\&.
.SS "bool VideoIOYuvMem::writeUpscaledPicture (const SPS & sps, const PPS & pps, const CPelUnitBuf & pic, const InputColourSpaceConversion ipCSC, const bool bPackedYUVOutputMode, int outputChoice = \fC0\fP, ChromaFormat format = \fCNUM_CHROMA_FORMAT\fP, const bool bClipToRec709 = \fCfalse\fP)"

.PP
write one upsaled YUV frame 
.PP
Definition at line \fB1264\fP of file \fBVideoIOYuvMem\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
