.TH "deps/base_vvc/include/VideoIOYuvMem.h" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deps/base_vvc/include/VideoIOYuvMem.h \- YUV general I/O class (header)  

.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include 'CommonLib/CommonDef\&.h'\fP
.br
\fC#include 'CommonLib/Unit\&.h'\fP
.br
\fC#include 'CommonLib/Slice\&.h'\fP
.br
\fC#include 'CommonLib/Picture\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBVideoIOYuvMem\fP"
.br
.RI "YUV file I/O class\&. "
.ti -1c
.RI "class \fBVideoIOYuvMem::Writer\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
YUV general I/O class (header) 


.PP
Definition in file \fBVideoIOYuvMem\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
