.TH "deps/base_vvc/src/VideoIOYuvMem.cpp" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deps/base_vvc/src/VideoIOYuvMem.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <cstdlib>\fP
.br
\fC#include <fcntl\&.h>\fP
.br
\fC#include <sys/stat\&.h>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <memory\&.h>\fP
.br
\fC#include 'CommonLib/Rom\&.h'\fP
.br
\fC#include 'VideoIOYuvMem\&.h'\fP
.br
\fC#include 'CommonLib/Unit\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBFLIP_PIC\fP   0"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define FLIP_PIC   0"

.PP
Definition at line \fB51\fP of file \fBVideoIOYuvMem\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
