.TH "deps/base_vvc/minimum_VTM/source/Lib/DecoderLib/VLCReader.h" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deps/base_vvc/minimum_VTM/source/Lib/DecoderLib/VLCReader.h
.SH SYNOPSIS
.br
.PP
\fC#include 'CommonLib/Rom\&.h'\fP
.br
\fC#include 'CommonLib/BitStream\&.h'\fP
.br
\fC#include 'CommonLib/Slice\&.h'\fP
.br
\fC#include 'CommonLib/SampleAdaptiveOffset\&.h'\fP
.br
\fC#include 'CommonLib/ParameterSetManager\&.h'\fP
.br
\fC#include 'CABACReader\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBvtm::VLCReader\fP"
.br
.ti -1c
.RI "class \fBvtm::AUDReader\fP"
.br
.ti -1c
.RI "class \fBvtm::FDReader\fP"
.br
.ti -1c
.RI "class \fBvtm::HLSyntaxReader\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBvtm\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBREAD_SCODE\fP(length,  code,  name)   xReadSCode ( length, code )"
.br
.ti -1c
.RI "#define \fBREAD_CODE\fP(length,  code,  name)   xReadCode ( length, code )"
.br
.ti -1c
.RI "#define \fBREAD_UVLC\fP( code,  name)   xReadUvlc (         code )"
.br
.ti -1c
.RI "#define \fBREAD_SVLC\fP( code,  name)   xReadSvlc (         code )"
.br
.ti -1c
.RI "#define \fBREAD_FLAG\fP( code,  name)   xReadFlag (         code )"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define READ_CODE(length, code, name)   xReadCode ( length, code )"

.PP
Definition at line \fB71\fP of file \fBVLCReader\&.h\fP\&.
.SS "#define READ_FLAG(code, name)   xReadFlag (         code )"

.PP
Definition at line \fB74\fP of file \fBVLCReader\&.h\fP\&.
.SS "#define READ_SCODE(length, code, name)   xReadSCode ( length, code )"

.PP
Definition at line \fB70\fP of file \fBVLCReader\&.h\fP\&.
.SS "#define READ_SVLC(code, name)   xReadSvlc (         code )"

.PP
Definition at line \fB73\fP of file \fBVLCReader\&.h\fP\&.
.SS "#define READ_UVLC(code, name)   xReadUvlc (         code )"

.PP
Definition at line \fB72\fP of file \fBVLCReader\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
