.TH "deps/base_vvc/minimum_VTM/source/Lib/CommonLib/WeightPrediction.cpp" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deps/base_vvc/minimum_VTM/source/Lib/CommonLib/WeightPrediction.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'CommonDef\&.h'\fP
.br
\fC#include 'Unit\&.h'\fP
.br
\fC#include 'InterpolationFilter\&.h'\fP
.br
\fC#include 'WeightPrediction\&.h'\fP
.br
\fC#include 'CodingStructure\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBvtm\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
