.TH "deps/base_vvc/minimum_VTM/source/Lib/CommonLib/WeightPrediction.h" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deps/base_vvc/minimum_VTM/source/Lib/CommonLib/WeightPrediction.h \- weighting prediction class (header)  

.SH SYNOPSIS
.br
.PP
\fC#include 'CommonDef\&.h'\fP
.br
\fC#include 'Slice\&.h'\fP
.br
\fC#include 'Unit\&.h'\fP
.br
\fC#include 'Buffer\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBvtm::WeightPrediction\fP"
.br
.RI "weighting prediction class "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBvtm\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
weighting prediction class (header) 


.PP
Definition in file \fBWeightPrediction\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
