.TH "util/src/YUVReader.cpp" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
util/src/YUVReader.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'YUVReader\&.hpp'\fP
.br
\fC#include <cstdio>\fP
.br
\fC#include <memory>\fP
.br
\fC#include <mutex>\fP
.br
\fC#include <regex>\fP
.br
\fC#include <string>\fP
.br
\fC#include 'Diagnostics\&.hpp'\fP
.br
\fC#include 'Image\&.hpp'\fP
.br
\fC#include 'Misc\&.hpp'\fP
.br
\fC#include 'Platform\&.hpp'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBlctm\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::unique_ptr< \fBYUVReader\fP > \fBlctm::CreateYUVReader\fP (const std::string &\fBname\fP, const \fBImageDescription\fP &image_description, unsigned rate)"
.br
.ti -1c
.RI "unique_ptr< \fBYUVReader\fP > \fBlctm::CreateYUVReader\fP (const string &\fBname\fP)"
.br
.ti -1c
.RI "unique_ptr< \fBYUVReader\fP > \fBlctm::CreateYUVReader\fP (const string &\fBname\fP, unsigned rate)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
