.TH "util/include/YUVReader.hpp" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
util/include/YUVReader.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'Image\&.hpp'\fP
.br
\fC#include 'Misc\&.hpp'\fP
.br
\fC#include <memory>\fP
.br
\fC#include <string>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBlctm::YUVReader\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBlctm\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::unique_ptr< \fBYUVReader\fP > \fBlctm::CreateYUVReader\fP (const std::string &\fBname\fP)"
.br
.ti -1c
.RI "std::unique_ptr< \fBYUVReader\fP > \fBlctm::CreateYUVReader\fP (const std::string &\fBname\fP, unsigned rate)"
.br
.ti -1c
.RI "std::unique_ptr< \fBYUVReader\fP > \fBlctm::CreateYUVReader\fP (const std::string &\fBname\fP, const \fBImageDescription\fP &image_description, unsigned rate)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
