.TH "util/src/YUVWriter.cpp" 3 "LTM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
util/src/YUVWriter.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'YUVWriter\&.hpp'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBlctm\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::unique_ptr< \fBYUVWriter\fP > \fBlctm::CreateYUVWriter\fP (const std::string &\fBname\fP, const \fBImageDescription\fP &image_description, bool decorate)"
.br
.ti -1c
.RI "std::unique_ptr< \fBYUVWriter\fP > \fBlctm::CreateYUVWriter\fP (const std::string &\fBname\fP)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LTM from the source code\&.
